<?php /** @var Zolago_SalesManago_Block_Customer_Cart $this */ ?>

<?php $customerCart = $this->getCustomerCart(); ?>

<?php if (!empty($customerCart)): ?>
    <style scoped>
        .item {
            width: 30%;
        }
        @media (max-width: 500px) {
            .item {
                width: 30%;
            }
        }
        @media (max-width: 380px) {
            .item {
                width: 45%;
            }
        }
        @media (max-width: 340px) {
            .item {
                width: 80%;
            }
        }
    </style>
<div class="container-fluid bg-w" style="background: #fff; margin-right: auto; margin-left: auto;">
    <div id="items-product" class="container-fluid">
        <div>
            <?php $helper = Mage::helper("zolagosalesmanago"); ?>
            <div>
                <h3 style="display: block;margin: 0 -20px 10px;padding: 0px;position: relative;font-family: 'latoregular'; font-size: 20px; line-height: 20px;text-align: left;text-transform: uppercase;width: 100%;">
                    <i style="content: ' ';position: absolute; display: block;height: 18px;left: 0;top: 0;width: 18px;background: none repeat scroll 0 0 #6fffcf;float: left; margin-right: 5px;"></i>
                    <?php echo $helper->__("W koszyku czeka"); ?>:</h3></div>

                <?php foreach ($customerCart as $vendor => $items): ?>
                    <?php foreach ($items as $item): ?>
                        <div class="item" style="float: left; padding: 0 2px;">
                            <div class="box_listing_product"  style="
                            background: #fff;
                            font-size: 12px;
                            padding: 0 0 10px 0;
                            ">
                                <?php $_product = Mage::getModel("catalog/product")->load($item->getProduct()->getId()); ?>

                                <a href="<?php echo $_product->getProductUrl(); ?>">
                                    <figure class="img_product" style="
                                    position: relative;
                                    margin: 0 0 18px 0;
                                    display: block;
                                    ">
                                        <img style="
                                                width: 100%;
                                                height: auto;
                                                vertical-align: middle;
                                                border: 0;
                                        "
                                            src="<?php echo (string)Mage::helper('catalog/image')
                                                ->init($_product, 'image')
                                                ->resize(148, 222); ?>"
                                            alt="<?php echo Mage::helper("zolagocatalog")->getShortProductName($_product->getName(), 42); ?>"/>
                                    </figure>

                                </a>

                                <div class="name_product" style="font-size: 12px;
                                                                margin-top: 18px;
                                                                margin-bottom: 18px;
                                                                padding: 0 8px;
                                                                display: block;
                                                                min-height: 28px;
                                    ">
                                    <a href="<?php echo $_product->getProductUrl(); ?>"  style="color: black;text-decoration: none;font-family: latoregular, sans-serif;"><?php echo Mage::helper("zolagocatalog")->getShortProductName($_product->getName(), 32, 32); ?></a>
                                </div>
                                <span style="color: #000000;
                                        font-size: 20px;
                                        font-family: latoregular, sans-serif;
                                        margin-bottom: 18px;
                                        padding: 0 8px;
                                        position: relative;
                                    ">
                                    <?php echo Mage::helper('checkout')->formatPrice($item->getData("base_price_incl_tax")); ?>
                                </span>


                            </div>
                        </div>
                    <?php endforeach; ?>
                <?php endforeach; ?>
        </div>
    </div>
</div>
<div style="clear: both;margin-bottom: 20px;"></div>
<?php endif; ?>