<?php $_helper = Mage::helper("zolagocatalog"); ?>

<div class="container">
    <!--=== Page Header ===-->
    <div class="page-header">
        <div class="page-title">
            <h3><?php echo $_helper->__('Attribute preview'); ?></h3>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="widget-content">
                <div class="row">
                    <div class="col-md-12">
                        <select id="attribute_set_select" class="col-md-12 select_select2">
                            <option value="0"><?php echo $_helper->__('-- choose attribute set --'); ?></option>
                            <?php foreach ($this->_getAttributeSetList() as $id => $item) : ?>
                                <option value="<?php echo $id; ?>"><?php echo $item; ?></option>
                            <?php endforeach; ?>
                        </select>
                    </div>
                </div>
                <br/>

                <div class="row" id="accordion">
                    <div class="col-md-12">
                        <div id="attribute_select" class="col-md-12">

                        </div>
                    </div>
                </div>
                <div style="display: none;">
                    <a class="btn btn-primary ask_button" disabled id="ask_button-tmp"
                       href="#askModal" data-toggle="modal" style="margin-top: 10px;"><?php echo $_helper->__('Ask about new value'); ?></a>
                </div>
            </div>
        </div>
    </div>
</div>
<div id="askModal" class="modal fade" style="display:none" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <?php echo $_helper->__('Ask about new value'); ?>
            </div>
            <div class="modal-body">
                <div class="row">
                <label class="col-md-2 control-label" for="send_attribute_label"><?php echo $_helper->__('Attribute');?></label>
                <input type="hidden" class="form-control" id="new_attribute_id"/>
                <div class="col-md-10" id="send_attribute_label">

                </div>
                </div>
                <div class="row">
                <label class="col-md-2 control-label" for="send_attribute_value"><?php echo $_helper->__('New value');?></label>
                <div class="col-md-10" id="send_attribute_value">
                    <input type="text" class="form-control" id="new_attribute_value"/>
                </div>
                </div>
            </div>
            <div class="modal-footer">
                <button class="btn btn-default" data-dismiss="modal" type="button"><?php echo $_helper->__('Cancel'); ?></button>
                <button id="send_ask_value" disabled class="btn btn-primary" type="button"><?php echo $_helper->__('Send'); ?></button>
            </div>
        </div>
    </div>
</div>
<script>
//var selectedAttrId = 0;
var noneTextTranslated = '<?php echo Mage::helper('zolagocatalog')->__('-- none --'); ?>';
jQuery(document).ready(function() {
    jQuery(".select_select2").select2();
    jQuery("#attribute_set_select").change(function() {

        jQuery('#attribute_select').html('<option style="color:#aaaaaa"><?php echo $_helper->__("Loading...");?></option>');
//        selectedAttrId = 0;
//        toggleButton(false);
        // load attributes by jquery
        var params = {};
        params.attribute_set = jQuery(this).val();
        jQuery.ajax({
            url: '/udprod/vendor_attributes/get_attributes',
            method: 'POST',
            data: params,
            success: function(answer) {
                jQuery('#attribute_select').html('');
                generateAllWidgetsBoxs(answer);
            }
        });
    });


    jQuery('#send_ask_value').click(function() {
        var text = jQuery('#new_attribute_value').val();
        var attrId = jQuery('#new_attribute_id').val();
        sendAskValue(text, attrId);

    });
    jQuery('#new_attribute_value').keyup(function(event) {
        if (checkNotEmpty() == true) {
            if (event.which == 13) {
                sendAskValue(jQuery(this).val(),jQuery('#new_attribute_id').val());
            }
        }
    });

    jQuery(document).delegate('.widget .toolbar .widget-collapse, .widget-header','click',function(e) {
        var widget = jQuery(this).parents(".widget");
        toggleWidget(widget,jQuery(this));
    });

    jQuery(document).delegate('.ask_button', 'click', function(e) {
        var elem = jQuery(this);
        var id = elem.attr('data-attr-id');
        jQuery('#new_attribute_id').val(id);
    });
});

function generateAllWidgetsBoxs(data) {
    var eData = JSON.parse(data);
    var arr = [];
    for(var x in eData){
        arr.push(eData[x]);
    }
    for(var i = 0; i < arr.length ; i++) {
        if (arr[i].id) {

            var iconRequired = "<i class='" + (arr[i].required == 'required' ? 'icon-pencil':'icon-magic') + "'></i>";
            var iconType     = "<i class='" +
                (arr[i].type == 'select' ? 'icon-tag':'') +
                (arr[i].type == 'multiselect' ? 'icon-tags':'') +
                (arr[i].type == 'text' ? 'icon-align-left':'') +
                "'></i>";
            console.log(iconRequired);
            var html = generateAttributeWidgetBox(
                arr[i].label + ' [ ' + arr[i].type_translated + ', ' + arr[i].required_translated + ' ]',
                arr[i].label + ' [ ' + iconType + arr[i].type_translated + ', ' + iconRequired + arr[i].required_translated + ' ]',
                arr[i].id);
            jQuery('#attribute_select').append(html);
            jQuery('#attr-' + arr[i].id).on('click', function () {
                getOnClickAttribute(this);
                jQuery('#attr-' + jQuery(this).attr('data-id')).off();
            });
        } else {
            jQuery('#attribute_select').append(noneTextTranslated);
            break;
        }
    }
}

function getOnClickAttribute(elem) {
    var askBtn = jQuery('#ask_button-tmp');
    var attrId = jQuery(elem).attr('data-id');
    var attrName = jQuery(elem).attr('data-attr-name');
//    selectedAttrId = 0;
    var params = {} ;
//    toggleButton(false);
    if (attrId == 0) {
        return;
    }
    jQuery('#attr-' + attrId + ' .widget-content .form-group').html('<?php echo $_helper->__("Loading...");?>');
    params.attribute = attrId;
    jQuery.ajax({
        url: '/udprod/vendor_attributes/get_values',
        method: 'POST',
        data: params,
        success: function(answer) {
//            selectedAttrId = attrId;
            jQuery('#send_attribute_label').html(attrName);
//            toggleButton(true);
            jQuery('#attr-' + attrId + ' .widget-content .form-group').html('').html(answer);
            jQuery(askBtn).clone()
                .attr('id', 'ask_button-'+attrId)
                .attr('data-attr-id', attrId)
                .appendTo('#attr-' + attrId + ' .widget-content .form-group');
            toggleButton(true, '#ask_button-'+attrId);
        }
    });
}

function generateAttributeWidgetBox(name, nameVisible, id) {
    return "<div class='widget box widget-closed' id='attr-" + id + "' data-id='" + id + "' data-attr-name='"+name+"'>" +
                "<div class='widget-header' style='cursor: pointer;'>" +
                    "<h4><i class='icon-plus'></i>" + nameVisible +"</h4>" +
                    "<div class='toolbar no-padding'>" +
                        "<div class='btn-group'>" +
                            "<span class='btn btn-xs widget-collapse'><i class='icon-angle-up'></i></span>" +
                        "</div>" +
                    "</div>" +
                "</div>"+
                "<div class='widget-content'>"+
                    "<div class='form-group widget-content not-clickable' style='margin-bottom: 0px;'>"+
                    "</div>"+
                "</div>"+
            "</div>";
}

function checkNotEmpty() {
    obj = jQuery('#new_attribute_value');
    var text = jQuery(obj).val();
    if (text.length > 0) {
        jQuery('#send_ask_value').attr('disabled',false);
        return true;
    } else {
        jQuery('#send_ask_value').attr('disabled',true);
        return false;
    }
}
function toggleButton(flag, selector) {
    if (flag) {
        jQuery(selector).attr('disabled',false);
    } else {
//        selectedAttrId = 0;
        jQuery('#new_attribute_value').val('');
        checkNotEmpty();
        jQuery('#send_attribute_label').html('');
        jQuery(selector).attr('disabled',true);
    }
}
function sendAskValue(text, attrId) {
        var params = {};
        params.attrId = attrId;
        params.value = text;
        jQuery.ajax({
            url:'/udprod/vendor_attributes/ask_value',
            method: 'POST',
            data: params,
            success: function(answer) {
                jQuery('#new_attribute_value').val('');
                jQuery('#new_attribute_id').val('');
                checkNotEmpty();
                noty({
                    text:answer,
                    type:'success',
                    timeout: 4000
                });
            },
            error: function(xhr, ajaxOptions, thrownError) {
                noty({
                    text:'<?php echo $_helper->__("Error");?>:'+xhr.status+' '+thrownError,
                    type:'error',
                    timeout: 4000
                });
            }
        });
        // after ajax
        jQuery('#askModal').modal('hide');

}
var toggleWidget = function(widget,element) {
    var widget_content = widget.children(".widget-content");
    var widget_chart   = widget.children(".widget-chart");
    var divider        = widget.children(".divider");

    if (widget.hasClass('widget-closed')) {
        // Open Widget
        element.children('i').removeClass('icon-angle-down').addClass('icon-angle-up');
        widget_content.slideDown(200, function() {
            widget.removeClass('widget-closed');
        });
        widget_chart.slideDown(200);
        divider.slideDown(200);
    } else {
        // Close Widget
        element.children('i').removeClass('icon-angle-up').addClass('icon-angle-down');
        widget_content.slideUp(200, function() {
            widget.addClass('widget-closed');
        });
        widget_chart.slideUp(200);
        divider.slideUp(200);
    }
};
</script>


