<div class="tabbable tabbabble-custom">
    <ul class="nav nav-tabs" style="margin-top:6px">
        <li class="" style="float:right">
            <a name="tmp"></a>
        </li>
        <li class="" style="float:right">
            <a data-toggle="tab" href="#tab_1_2"><?php echo Mage::helper('zolagocatalog')->__('Add');?></a>
        </li>
        <li class="active" style="float:right">
            <a data-toggle="tab" href="#tab_1_1"><?php echo Mage::helper('zolagocatalog')->__('Images');?></a>
        </li>
    </ul>
    <div class="tab-content">
        <div id="tab_1_1" class="tab-pane active">
    		<?php echo $this->getChildHtml("image_list");?>
        </div>
        <div id="tab_1_2" class="tab-pane">
    		<?php echo $this->getChildHtml("image_queue");?>
        </div>
    </div>
</div>