
<div class="container">
    <div class="page-header row">
        <div class="col-lg-4 page-title">
            <h3><?php echo Mage::helper("zolagocatalog")->__("Mass prices");?></h3>
			<span class="tageline"><?php echo Mage::helper("zolagocatalog")->__("Manage prices and stocks");?></span>
        </div>
		<div class="col-lg-4 main-actions ">
			<label><?php echo Mage::helper("zolagocatalog")->__("Selected");?>: </label>
			<button class="btn" disabled="disabled" id="change-prices">
				<i class="icon icon-pencil"></i> 
				<?php echo Mage::helper("zolagocatalog")->__("Change prices");?>
			</button>
		</div>
		<div class="main-actions align-right col-lg-4 " style="padding-right: 0;">
			<form>
				<select id="store-switcher" class="form-control">
					<?php foreach($this->getAllowedStores() as $store):?>
					<option value="<?php echo $this->escapeHtml($store->getId());?>" <?php if($this->getCurrentStoreId()==$store->getId()):?>selected="selected"<?php endif;?>><?php echo $this->escapeHtml($store->getName());?></option>
					<?php endforeach;?>
				</select>
			</form>
		</div>
    </div>
</div>

<div class="container">
	<div class="row">
		<div class="col-lg-12">
			<div id="grid-holder"></div>
		</div>
	</div>
</div>
<script type="text/javascript">
	
	sourceOptions = <?php echo $this->getAttributeSourceJson();?>;
	
	require(['vendor/catalog/priceGrid', 'dojo/store/Memory', 'dojo/store/Observable'], function(priceGrid, Memory, Observable){
		<?php /*
		var store = new Observable(new Memory({ idProperty: "entity_id", data: <?php echo $this->getJsonCollection();?>}));
		
		priceGrid.set("store", store);
		*/ ?>
	});
</script>