
<div class="container">
    <div class="page-header row">
        <div class="col-lg-9 page-title">
            <h3><?php echo Mage::helper("zolagocatalog")->__("Product prices");?></h3>
			<span class="tageline"><?php echo Mage::helper("zolagocatalog")->__("Manage prices and stocks");?></span>
        </div>
		<div class="main-actions align-right col-md-3" style="padding-right: 0;">
			<form>
				<select id="store-switcher" class="form-control">
					<?php foreach($this->getAllowedStores() as $store):?>
					<option value="<?php echo $this->escapeHtml($store->getId());?>" <?php if($this->getCurrentStoreId()==$store->getId()):?>selected="selected"<?php endif;?>><?php echo $this->escapeHtml($store->getName());?></option>
					<?php endforeach;?>
				</select>
			</form>
		</div>
    </div>
</div>

<div class="container">
	<div class="row">
		<div class="col-lg-12">
			<div id="grid-holder"></div>
		</div>
	</div>
</div>
<style>
#grid-holder{
	height: 600px;
}


#grid-holder .field-expander,
#grid-holder .field-selector{
		width: 25px;
		text-align: center;
	}
#grid-holder .ui-state-default {
	border:0;
}


#grid-holder .collapsed .expando {
	display: none;
}
#grid-holder .dgrid-sort-arrow {
	margin:0;
}
#grid-holder .text-overflow,
#grid-holder th.dgrid-cell{
	text-overflow: ellipsis;
	white-space: nowrap;
}
#grid-holder td.editable {
	font-weight: bold;
}
#grid-holder td.editable.popup-trigger,
#grid-holder .expando td.editable
{
	font-weight: normal;
}
#grid-holder td.editable.popup-trigger{
	color: #4d7496;
}
#grid-holder td.editable.popup-trigger:hover{
	text-decoration: underline;
}
#grid-holder .dgrid-row-table:hover td.editable.popup-trigger{
	color: #000
}
#grid-holder  .align-right {
	text-align: right;
}
#grid-holder  .align-center {
	text-align: center;
}
#grid-holder  .column-short {
	width: 60px;
}
#grid-holder  .column-medium {
	width: 100px;
}
#grid-holder  .column-long {
	width: 150px;
}
#grid-holder  .field-name {
	width: 250px;
}

#grid-holder .dgrid-no-data span,
#grid-holder .dgrid-loading span{
   position: absolute;
   top: 50%;
   width: 100%;
   margin-top: -5px;
   color: #aaa;
   text-align: center;
}

#grid-holder .filterable input,
#grid-holder .filterable select{
	border: 1px #ddd solid;
	background: #fff;
	height: 20px;
	display: block;
	width: 100%;
	padding: 0px !important;
}

#grid-holder .filterable .range-field{
	display: inline-block;
	width: 49.5%;
}
#grid-holder .filterable .range-field-from{
	margin-right: 1%;
}

#grid-holder .expando {
	/* style of area containing summary, expanded on click */
	background: #f9f9f9;
	border-bottom: 1px #ddd solid;
	font-size: 11px;
}

#grid-holder .dgrid-row:hover .expando,
#grid-holder .dgrid-selected .expando {
	/* style of area containing summary, expanded on click */
	background: #F1F4F9;
	
}

#grid-holder .expando{
	display: table;
	width: 100%;
}
#grid-holder .expando > div{
	display: table-cell;
	width: 50%;
}
#grid-holder div.sub-row-left{
	border-right: 1px #dddddd solid;
}
#grid-holder .table-subrow{
	margin:  0 !important;
	border-collapse: collapse;
	border: none;
	empty-cells: show;
}
#grid-holder .table-subrow input[type="checkbox"]{
	margin-top: 0 !important;
}

#grid-holder .table-subrow td{
	padding: 4px 6px 2px 6px;
}
#grid-holder .table-subrow tr.header-row td{
	font-weight: bold;
}
#grid-holder .table-subrow tr:first-child td{
	table-layout: fixed;
	border-top:0;
}
#grid-holder .table-subrow tr td.sub-checkbox {
	text-align: center;
	width: 25px;
	padding-left: 8px;
	padding-right: 8px;
}
#grid-holder .sub-row-pos,
#grid-holder .sub-row-loading
{
	display: block;
	padding: 1px 2px;
	
}

#grid-holder .sub-row-actions
{
	padding: 4px 6px;
	
}

#grid-holder .sub-row-actions a{
	display: inline-block;
	margin-right: 10px;
}

#grid-holder .campaign-date{
	width: 250px;
}

/******************************************************************************
 * Modal 
 ******************************************************************************/

.price-modal table{
	table-layout: fixed;
}
.price-modal tbody td{
	text-align: right;
	color: #999;
}
.price-modal .minimal-price td{
	font-weight: bold;
}
.price-modal .minimal-price td.caption{
	text-align: left;
}
.price-modal tbody td.effective-price{
	color: #468847;
	font-weight:bold;
}

.price-modal tbody td.option-text,
.price-modal tbody td.price-deviation{
	color: inherit;
}
.price-modal tbody td.option-text,
.price-modal tbody td.price-deviation{
	text-align: left;
}
.price-modal table .price-deviation{
	padding-top:4px;
	padding-bottom:3px;
}
.price-modal table .price-deviation input{
	height: 20px;
	padding: 0 2px !important;
}
.help-block{
	color: inherit;
}

.price-modal .help-block{
	font-weight: bold;
}

.price-modal .form-group{
	margin:0 !important;
	border:0 !important;
	padding:0 15px !important;
}

</style>
<script type="text/javascript">
	
	sourceOptions = <?php echo $this->getAttributeSourceJson();?>;
	
	require(['vendor/catalog/priceGrid', 'dojo/store/Memory', 'dojo/store/Observable'], function(priceGrid, Memory, Observable){
		<?php /*
		var store = new Observable(new Memory({ idProperty: "entity_id", data: <?php echo $this->getJsonCollection();?>}));
		
		priceGrid.set("store", store);
		*/ ?>
	});
</script>