<?php
/* @var $this Zolago_Catalog_Block_Vendor_Product */
/** @var Zolago_Catalog_Helper_Data $helper */
$helper = Mage::helper("zolagocatalog");
?>
<div class="container">
    <div class="page-header row">
        <div class="col-xs-4 page-title" style="padding-bottom:0;">
            <h3><?php echo Mage::helper("zolagocatalog")->__("Manage products descriptions");?></h3>
        </div>
		<?php echo $this->getChildHtml("mass_actions"); ?>
		<?php echo $this->getChildHtml("attribute_set_switcher"); ?>
    </div>
</div>

<?php if($this->getCanShowGrid()):?>
<div class="container">
    <div class="row">
		<div class="col-xs-8" style="font-size: 11px;">
			<a href="#" data-toggle="modal" data-target="#saveColumnsModal">
				<i class="icon-table"></i> 
				<?php echo $helper->__("Customize columns");?>
			</a>
			&nbsp;
			<a href="#" data-toggle="modal" data-target="#filtersModal">
				<i class="icon-filter"></i> 
				<?php echo $helper->__("Show more filters");?>
			</a>
			&nbsp;
			<a href="#" class="hidden" id="remove-filters">
				<i class="icon-remove"></i> 
				<?php echo $helper->__("Remove filters");?>
			</a>
            &nbsp;
			<a id="showAttributeRules-trigger" data-toggle="modal" data-target="#showAttributeRules">
				<i class="icon-puzzle-piece"></i>
				<?php echo Mage::helper("gh_attributerules")->__("Autofill rules"); ?>
			</a>
			&nbsp;
			<a id="changesHistory-trigger" data-toggle="modal" data-target="#showChangesHistory">
				<i class="icon-time"></i>
				<?php echo Mage::helper("zolagocatalog")->__("Show Changes History"); ?>
			</a>
		</div>
        <div class="col-xs-4 text-right">
            <span class="grid-total-text"><?php echo $helper->__("Products: "); ?></span><span class="grid-total-number">0</span>
        </div>
    </div>
</div>
<?php endif;?>

<?php if($this->getCanShowGrid()):?>
	<?php echo $this->getChildHtml("grid");?>
	<?php echo $this->getChildHtml("popups");?>
<?php else:?>
	<div class="container">
		<div class="row">
			<div class="col-lg-12">
				<p class="alert alert-info"><?php echo $helper->__("Choose the category");?></p>
			</div>
		</div>
	</div>
<?php endif;?>
