<?php /* @var $this Mage_Catalog_Block_Product_List */ ?>
<?php /* @var $this SolrBridge_Solrsearch_Block_Product_List */ ?>
<?php /* @var $this Unirgy_DropshipMicrosite_Block_Frontend_VendorProducts */ ?>
<?php /* @var $this Zolago_Solrsearch_Block_Catalog_Product_List */ ?>
<?php
/**
 * Author: Paweł Chyl <pawel.chyl@orba.pl>
 * Date: 19.08.2014
 */
/** @var $product Mage_Catalog_Model_Product */
$_productImageUrl = '';
$_collection = $this->getCollection();

?>

<section id="main" class="">
<div id="content" class="container-fluid">
<div class="row">
<div class="col-sm-12">
<div id="sidebar" class="hidden-xs">
    <?php echo $this->getChildHtml('searchfaces'); ?>
</div>
<div id="content-main">
<div class="container-fluid" id="items-product">
    <div class="row">
        <div class="col-xs-12 col-sm-12">
            <div class="row">
                <div id="grid" class="shuffle--container shuffle--fluid">
                    <!-- START LIST PRODUCT -->
                    <?php foreach ($_collection as $product): ?>
                        <?php $_productImageUrl = $product->getListingResizedImageUrl(); ?>
                        <?php $_productImageInfo = $product->getListingResizedImageInfo(); ?>

                        <div class="item col-phone col-xs-4 col-sm-4 col-md-3 col-lg-3 size14">
                            <div class="box_listing_product">
                                <a href="<?php echo $product->getCurrentUrl(); ?>">
                                    <figure class="img_product">
                                        <img src="<?php echo $_productImageUrl; ?>"
                                             alt="<?php $this->escapeHtml($product->getName()); ?>"
                                             class="img-responsive"
                                             data-width="<?php echo $_productImageInfo['width']; ?>"
                                             data-height="<?php echo $_productImageInfo['height']; ?>"/>
                                    </figure>
                                    <div class="logo_manufacturer">
                                        <img class="img-responsive"
                                             src="<?php echo $product->getManufacturerLogoUrl(); ?>"
                                             alt="<?php echo $this->escapeHtml($product->getManufacturer()); ?>"/>
                                    </div>
                                    <div class="name_product">
                                        <?php echo $this->escapeHtml($product->getName()); ?>
                                    </div>
                                    <div class="price clearfix">
                                        <div class="col-price">
                                            <?php if ($product->getPrice() != $product->getFinalPrice()) : ?>
                                                <span class="old">
                                                    <?php echo $this->helper('core')->currency($product->getPrice(), true, false); ?>
                                                </span>
                                            <?php endif; ?>
                                            <span>
                                                <?php echo $this->helper('core')->currency($product->getFinalPrice(), true, false); ?>
                                            </span>
                                        </div>
                                        <?php
                                        // like count
                                        $wishlistCount = "";
                                        $inMyWishlist = "";
                                        $plusSign = "";
                                        if ($product->getWishlistCount() - 1 > 0) {
                                            $wishlistCount = $product->getWishlistCount();
                                            if ($product->getInMyWishlist()) {
                                                $wishlistCount -= 1;
                                            }
                                        }

                                        if ($product->getInMyWishlist()) {
                                            $inMyWishlist = $this->__("You");
                                            if ($product->getWishlistCount() > 1) {
                                                $plusSign = " + ";
                                            }
                                        }

                                        ?>
                                        <div class="like <?php if ($product->getInMyWishlist()): ?>liked<?php endif; ?>"
                                             data-idproduct="<?php echo $product->getId(); ?>"
                                             data-status="<?php echo (int)$product->getInMyWishlist(); ?>">
                                            <span class="icoLike">
                                                <img class="img-01"
                                                     src="<?php echo $this->getSkinUrl('images/heart.png'); ?>"
                                                     alt=""/>
                                                <img class="img-02"
                                                      src="<?php echo $this->getSkinUrl('images/heart-like.png'); ?>"
                                                      alt=""/>
                                            </span>
                                            <span class="like_count">
                                                <span>
                                                    <?php echo $inMyWishlist; ?>
                                                    <?php echo $plusSign; ?>
                                                </span>
                                                <?php echo $wishlistCount; ?>
                                            </span>
                                            <div class="toolLike"></div>
                                        </div>
                                    </div>
                                </a>
                            </div>
                        </div>
                    <?php endforeach; ?>
                </div>
                <div class="col-xs-12 shuffle__sizer"></div>
                <div class="shapes_listing"></div>
            </div>
        </div>
    </div>
</div>
<div id="listing-loading">
    <img src="<?php echo $this->getSkinUrl("images/modago-ajax-loader.gif"); ?>" alt="">
</div>
<?php $noAjaxLink = $this->getNoAjaxLink(); ?>
<?php foreach ($noAjaxLink as $page => $link) : ?>
    <span class="addNewPositionListWrapper" style="width:35px"><a href="<?php echo $link ?>"><?php echo $page ?></a></span>
<?php endforeach; ?>
<div class="addNewPositionListProductWrapper">
    <a href="#" class="addNewPositionListProduct"><?php echo $this->__("Load next <span>%s</span> products", $this->getLoadMoreOffset()); ?></a>
</div>

<script type="text/javascript">
    Mall.listing.initImagesHeight();
    Mall.listing.setQuery("<?php echo Mage::helper('zolagosolrsearch')->getSolrRealQ(); ?>");
    Mall.listing.setInitProducts(<?php echo $this->getJsonProducts(); ?>);
    Mall.listing.setLoadNextOffset(<?php echo (int) $this->getLoadMoreOffset(); ?>);
    Mall.listing.setScrollLoadOffset(<?php echo (int) $this->getAppendWhenScroll(); ?>);
    Mall.listing.setPixelsBeforeAppend(<?php echo (int) $this->getPixelsBeforeAppend(); ?>);

    Mall.listing.setScat(<?php echo $this->getLayer()->getCurrentCategory()->getId(); ?>);
    Mall.listing.addToVisibleItems(<?php echo count($this->getCollection()); ?>);
    Mall.translate.add("you-like-this", "<?php echo $this->__("You like this"); ?>");
    Mall.translate.add("remove-from-favorites", "<?php echo $this->__("remove from favorites"); ?>");
    Mall.translate.add("add-to-br-favorites", "<?php echo $this->__("Add to<br />favorites"); ?>");
    Mall.translate.add("like-this-product", "<?php echo $this->__("like this product"); ?>");
    Mall.translate.add("likes-this-product", "<?php echo $this->__("likes this product"); ?>");
    Mall.translate.add("you-and", "<?php echo $this->__("You and"); ?>");
    Mall.translate.add("person", "<?php echo $this->__("person"); ?>");
    Mall.translate.add("people", "<?php echo $this->__("people"); ?>");
    Mall.translate.add("people-polish-more-than-few", "<?php echo $this->__("people polish more than few"); ?>");
    Mall.translate.add("you", "<?php echo $this->__("You"); ?>");

    var grid = jQuery('#grid'),
        sizer = jQuery(grid).find('.shuffle__sizer');

    grid.shuffle({throttleTime: 400, speed: 0, supported: false });
    grid.shuffle('update');
    setTimeout(function(){grid.shuffle('update');}, 500);//sometimes with pushstate

    jQuery(grid).on('layout.shuffle', function() {
        Mall.listing.likePriceView();
    });

    <?php foreach ($_collection as $product): ?>
    Mall.wishlist.addProduct({
        id: <?php echo $product->getId(); ?>,
        wishlist_count: <?php echo (int)$product->getWishlistCount(); ?>,
        in_your_wishlist: <?php echo $product->getInMyWishlist() ? "true" : "false"; ?>
    });
    <?php endforeach; ?>

    jQuery('#grid .like').click(function() {
        var inMyWishlisy = parseInt(jQuery(this).attr('data-status'));
        if (inMyWishlisy) {
            Mall.wishlist.removeFromSmallBlock(this);
        } else {
            Mall.wishlist.addFromSmallBlock(this);
        }
    });

    jQuery(window).on('appendToListEnd', function() {
        grid.shuffle('update');

        Mall.listing.hideLoadMoreButton();
        if(Mall.listing.getLoadNextStart() === Mall.listing.getCurrentVisibleItems()){
            if( Mall.listing.getTotal() > Mall.listing.getCurrentVisibleItems()){
                Mall.listing.showLoadMoreButton();
            }
        }

        Mall.listing.placeListingFadeContainer();
    });

    jQuery(window).resize(function() {
        Mall.listing.placeListingFadeContainer();
        Mall.listing.removeImagesHeight();
    });

    jQuery('a.addNewPositionListProduct').click(function( event){
        event.preventDefault();
        Mall.listing.loadMoreProducts();
    });
</script>

</div>
</div>
</div>
</div>
</section>