<?php /* @var $this Zolago_Modago_Block_Map */ ?>
<?php
$map = $this->getMapData();
$decodedJSON = json_decode($map, true);
?>

<?php $_helper = Mage::helper("zolagomodago"); ?>
<script type="text/javascript" src="//maps.google.com/maps/api/js?v=3&key=AIzaSyB6jZPjPGQrn83VpCi-yoxCSwCgZN2kbd4"></script>
<?php if (!empty($decodedJSON)): ?>
    <script type="text/javascript">
        var data = '<?php echo $map; ?>';
        Mall.translate.add("Show on map", "<?php echo $_helper->__("Show on map")?>");
        Mall.translate.add("Define the route", "<?php echo $_helper->__("Define the route")?>");
        Mall.translate.add("Select phone", "<?php echo $_helper->__("Select phone")?>");
    </script>
    <script type="text/javascript" src="<?php echo $this->getSkinUrl('js/storemap/storefinder.js') ?>"></script>
<?php endif; ?>

<div id="content" class="container-fluid bg-w">
    <div class="row">
        <div class="col-sm-12">
            <div id="content-main">
                <div class="stores-map">
                    <div class="container-fluid no-padding">
                        <div class="col-md-12 no-padding">
                            <?php if (!empty($decodedJSON)): ?>
                                <div id="map-list-container" class="col-md-5 col-sm-12">
                                    <div class="col-md-12 no-padding">
                                        <div class="search-by-map col-md-12 col-sm-10 col-xs-12">
                                            <h4><?php echo $_helper->__("Find your store") ?></h4>
                                            <div class="form-group">
                                                <form id="search_by_map_form"
                                                      action="<?php echo $this->getMapDataUrl(); ?>">
                                                    <input type="text"
                                                           autocomplete="off"
                                                           name="search_by_map"
                                                           placeholder="<?php echo $_helper->__("Enter city or zip"); ?>"
                                                           class="col-md-12 col-sm-12 col-xs-12"/>
                                                </form>
                                            </div>
                                            <div class="form-group">
                                                <a href="" class="stores-map-show-all hidden"
                                                   onclick="clearSearchOnMap();return false;">
                                                    <?php echo $_helper->__("Show all stores"); ?>
                                                </a>
                                            </div>
                                        </div>
                                        <div class="search-by-map-list col-md-12 col-sm-12 col-xs-12">
                                            <h4 class="the-nearest-stores hidden">
                                                <?php echo $_helper->__("The nearest stores"); ?>
                                            </h4>
                                            <div class="search-by-map-list-container"></div>
                                        </div>
                                    </div>
                                </div>
                                <div id="map-container" class="col-md-7 col-sm-12 col-xs-12">
                                    <div id="map"></div>
                                </div>
                            <?php else: ?>
                                <p><?php echo $_helper->__("There are no stores to show on the map"); ?></p>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>
