<?php
$_helper = Mage::helper("zolagorma");
$_rma = Mage::registry('current_rma');

$vendors = $_rma->getVendor()->getId();


$session = Mage::getSingleton('customer/session');

$dataPopulate = Mage::getSingleton('udqa/session')->getDataPopulate(true);

$visibility = isset($dataPopulate['visibility']) ? $dataPopulate['visibility'] : false;
$vendor_id = isset($dataPopulate['vendor_id']) ? $dataPopulate['vendor_id'] : false;

$question_text = isset($dataPopulate['question_text']) ? $dataPopulate['question_text'] : false;


?>
<form id="rma-connect-vendor-form" class="form clearfix" novalidate="novalidate" method="post" action="<?php echo $this->getFormAction(); ?>">

    <input type="hidden" name="question[visibility]" value="0" />

    <div class="form-group">
        <label class="control-label" for="rma-connect-vendor-message">
            <?php echo $_helper->__("Compose message"); ?>
        </label>

        <input type="hidden" name="question[vendor_id]" value="<?php echo $vendors; ?>"/>

        <textarea class="form-control required-entry textarea"
                  id="question_text"
                  name="question[question_text]"
                  cols="8"
                  rows="8"
                  title="<?php echo $_helper->__("Compose message"); ?>"
                  data-original-title="<?php echo $_helper->__("Compose message"); ?>"
                  required="required">
            <?php echo $question_text; ?>
        </textarea>
    </div>


    <div class="form-group text-right">
        <button class="button button-primary rma-connect-vendor-form-send"
                type="submit"
                title="<?php echo $_helper->__("Send"); ?>">
            <span><span><?php echo $_helper->__("Send"); ?></span></span>
        </button>
    </div>

</form>
<script type="text/javascript">
	Mall.i18nValidation.add("required", "<?php echo $this->__('This field is required') ?>");
</script>