<div class="content-header">
   <h3><?php echo $this->getHeaderText() ?></h3>
   <p class="content-buttons form-buttons">
        <?php echo $this->getBackButtonHtml(); ?>
        <?php echo $this->getResetButtonHtml(); ?>
        <?php echo $this->getSaveButtonHtml(); ?>
    </p>
</div>
<form action="<?php echo $this->getSaveUrl() ?>" method="post" id="vendor_global_settings_form">
    <?php echo $this->getBlockHtml('formkey')?>
    <div class="no-display">
        <input type="hidden" id="change_flag_element" name="_change_type_flag" value="" />
    </div>
    <?php echo $this->getForm() ?>
</form>
<script type="text/javascript">
    var vendorGlobalSettingsForm = new varienForm('vendor_global_settings_form');
    var vendorGlobalSettingsControl = {
        save: function() {
            vendorGlobalSettingsForm.submit();
            return false;
        }
    };
    vendorGlobalSettingsControl.init();
</script>