<?php
/**
 * Author: Paweł Chyl <pawel.chyl@orba.pl>
 * Date: 08.09.2014
 */

?>

<fieldset>
    <input type="hidden" name="billing[address_id]" value="">
    <input type="hidden" name="billing[firstname]" value="">
    <input type="hidden" name="billing[lastname]" value="">
    <input type="hidden" name="billing[region_id]" value="">
    <input type="hidden" name="billing[region]" value="">
    <input type="hidden" name="billing[country_id]" value="">
    <input type="hidden" name="billing[telephone]" value="">
    <input type="hidden" name="billing[fax]" value="">
    <input type="hidden" name="billing[use_for_shipping]" value="0">
    <input type="hidden" name="billing[use_in_address_book]" value="1">
    <legend><?php echo $this->__("Billing address:"); ?></legend>
    <div class="form-group form-checkbox small">
        <input type="checkbox" name="invoice_vat" id="invoice_vat" class="css-checkbox invoice_vat">
        <label for="invoice_vat" class="css-label"><?php echo $this->__("I want an invoice"); ?></label>
    </div>
</fieldset>

<fieldset id="invoice_data">

    <div class="form-group form-checkbox small">
        <input type="checkbox" name="invoice_data_address" id="invoice_data_address" class="css-checkbox invoice_data_address" checked="">
        <label for="invoice_data_address" class="css-label"><?php echo $this->__("Billing address same as shipping address."); ?></label>
    </div>

    <div class="form-group clearfix border-top">
        <div class="row">
            <label class="col-sm-3" for="billing:company"><?php echo $this->__("Company"); ?></label>
            <div class="col-lg-7 col-md-5 col-sm-5">
                <input type="text" class="form-control firm hint" id="billing:company" title="" name="billing[company]" data-original-title="<?php echo $this->__("Company"); ?>">
            </div>
        </div>
    </div>

    <div class="form-group clearfix border-top">
        <div class="row">
            <label class="col-sm-3" for="billing:vat_id"><?php echo $this->__("VAT ID"); ?></label>
            <div class="col-lg-3 col-md-5 col-sm-5">
                <input type="text" class="form-control nip hint" name="billing[vat_id]" id="billing:vat_id" title="" data-original-title="<?php echo $this->__("VAT ID"); ?>">
            </div>
        </div>
    </div>

    <div class="form-group border-top clearfix">
        <div class="row">
            <label class="col-sm-3" for="billing:street"><?php echo $this->__("Street and number"); ?></label>
            <div class="col-lg-7 col-md-5 col-sm-5">
                <input type="text" class="form-control street" id="billing:street" title="" name="billing[street][]" data-original-title="<?php echo $this->__("Street and number"); ?>">
            </div>
        </div>
    </div>

    <div class="form-group clearfix border-top">
        <div class="row">
            <label class="col-sm-3" for="billing:postcode"><?php echo $this->__("Zip code"); ?></label>
            <div class="col-sm-5">
                <input type="text" class="form-control zipcode" id="billing:postcode" title="" name="billing[postcode]" data-original-title="<?php echo $this->__("Zip code"); ?>">
            </div>
        </div>
    </div>

    <div class="form-group clearfix border-top">
        <div class="row">
            <label class="col-sm-3" for="billing:city"><?php echo $this->__("City"); ?></label>
            <div class="col-sm-5">
                <input type="text" class="form-control city hint" id="billing:city" title="" name="billing[city]" data-original-title="<?php echo $this->__("City"); ?>">
            </div>
        </div>
    </div>

</fieldset>