<?php /* @var $this Zolago_Modago_Block_Checkout_Onepage_Shared_Address_Shipping */ ?>
<?php
/**
 * Author: Paweł Chyl <pawel.chyl@orba.pl>
 * Date: 08.09.2014
 */
$_shippingAddress = $this->getQuote()->getShippingAddress();
$sameAsBilling = (int) $this->getQuote()->getShippingAddress()->getSameAsBilling();
?>

<fieldset>
    <input type="hidden" name="shipping[address_id]" value="<?php echo $_shippingAddress->getId(); ?>">
    <input type="hidden" name="shipping[region_id]" value="<?php echo $this->escapeHtml($_shippingAddress->getRegionId()); ?>">
    <input type="hidden" name="shipping[region]" value="<?php echo $this->escapeHtml($_shippingAddress->getRegion()); ?>">
    <input type="hidden" name="shipping[country_id]" value="<?php echo $this->getStoreDefaultCountryId();?>">
    <input type="hidden" name="shipping[fax]" value="<?php echo $this->escapeHtml($_shippingAddress->getFax()); ?>">
    <input type="hidden" name="shipping[save_in_address_book]" value="1">
    <input type="hidden" name="shipping[same_as_billing]" value="<?php echo $sameAsBilling; ?>">
    <legend><?php echo $this->__("Shipping address:"); ?></legend>
    <div class="form-group form-checkbox small">
        <input type="checkbox" name="shipping[different_shipping_address]" id="orders_someone_else" class="css-checkbox orders_someone_else" <?php if ($this->getOrderSomeoneElseFlag()) : ?>checked<?php endif; ?>>
        <label for="orders_someone_else" class="css-label orders_someone_else"><?php echo $this->__("I'm buing for someone else."); ?></label>
    </div>

    <div class="form-group clearfix hidden border-top orders_someone_else">
        <div class="form-group clearfix">
            <div class="row">
                <label class="col-sm-3" for="shipping_firstname"><?php echo $this->__("First name"); ?></label>
                <div class="col-sm-5"><input value="<?php echo $this->escapeHtml($_shippingAddress->getFirstname()); ?>" type="text" class="form-control firstName hint" id="shipping_firstname" title="" name="shipping[firstname]" data-original-title="<?php echo $this->__("Enter your name."); ?>"></div>
            </div>
        </div>
        <div class="form-group clearfix border-top">
            <div class="row">
                <label class="col-sm-3" for="shipping_lastname"><?php echo $this->__("Last name"); ?></label>
                <div class="col-sm-5">
                    <input type="text" value="<?php echo $this->escapeHtml($_shippingAddress->getLastname()); ?>" class="form-control lastName hint" id="shipping_lastname" title="" name="shipping[lastname]" data-original-title="<?php echo $this->__("Enter your last name"); ?>">
                </div>
            </div>
        </div>
    </div>

    <div class="form-group clearfix border-top hidden orders_someone_else">
        <div class="row">
            <label class="col-sm-3" for="shipping_telephone"><?php echo $this->__("Telephone number"); ?></label>
            <div class="col-sm-5">
                <input type="text" value="<?php echo $this->escapeHtml($_shippingAddress->getTelephone()); ?>" class="form-control" id="shipping_telephone" title="" name="shipping[telephone]" data-original-title="<?php echo $this->__("We need your telephone number only to complete the order."); ?>">
            </div>
        </div>
    </div>

    <div class="form-group border-top clearfix">
        <div class="row">
            <label class="col-sm-3" for="shipping_street"><?php echo $this->__("Street and number"); ?></label>
            <div class="col-lg-7 col-md-5 col-sm-5">
                <input type="text" value="<?php echo $this->escapeHtml(is_array($_shippingAddress->getStreet(-1)) ? explode(" ", $_shippingAddress->getStreet(-1)) : $_shippingAddress->getStreet(-1)); ?>" class="form-control street" id="shipping_street" title="" name="shipping[street][]" data-original-title="<?php echo $this->__("Street and number"); ?>">
            </div>
        </div>
    </div>

    <div class="form-group clearfix border-top">
        <div class="row">
            <label class="col-sm-3" for="shipping_postcode"><?php echo $this->__("Zip code"); ?></label>
            <div class="col-sm-5">
                <input type="text" value="<?php echo $this->escapeHtml($_shippingAddress->getPostcode()); ?>" class="form-control zipcode" id="shipping_postcode" title="" name="shipping[postcode]" data-original-title="<?php echo $this->__("Zip code"); ?>">
            </div>
        </div>
    </div>

    <div class="form-group clearfix border-top">
        <div class="row">
            <label class="col-sm-3" for="shipping_city"><?php echo $this->__("City"); ?></label>
            <div class="col-sm-5">
                <input type="text" value="<?php echo $this->escapeHtml($_shippingAddress->getCity()); ?>" class="form-control city hint" id="shipping_city" title="" name="shipping[city]" data-original-title="<?php echo $this->__("City"); ?>">
            </div>
        </div>
    </div>

    <div class="form-group clearfix border-top">
        <div class="row">
            <label class="col-sm-3 double-line" for="shipping_company"><?php echo $this->__("Company<br>(optional)"); ?></label>
            <div class="col-lg-7 col-md-5 col-sm-5">
                <input type="text" value="<?php echo $this->escapeHtml($_shippingAddress->getCompany()); ?>" class="form-control firm hint" id="shipping_company" title="" name="shipping[company]" data-original-title="<?php echo $this->__("Company"); ?>">
            </div>
        </div>
    </div>
</fieldset>