<?php /* @var $this Zolago_Modago_Block_Checkout_Onepage_Shared_Address_Shipping */
/**
 * Author: Paweł Chyl <pawel.chyl@orba.pl>
 * Date: 08.09.2014
 */
/** @var Zolago_Checkout_Helper_Data $helper */
$helper 			= Mage::helper("zolagocheckout");
$shippingAddress	= $this->getShippingAddress();

$deliveryPoint = $this->getDeliveryPointCheckout();
?>

<fieldset>
    <input type="hidden" name="shipping[address_id]" value="<?php echo $this->getShippingAddressId(); ?>">
    <input type="hidden" name="shipping[region_id]" value="<?php echo $this->getRegionId(); ?>">
    <input type="hidden" name="shipping[region]" value="<?php echo $this->getRegion(); ?>">
    <input type="hidden" name="shipping[country_id]" value="<?php echo $this->getCountryId(); ?>">
    <input type="hidden" name="shipping[fax]" value="<?php echo $this->getFax(); ?>">
    <input type="hidden" name="shipping[save_in_address_book]" value="<?php echo $this->getSaveInAddressBook(); ?>">
    <input type="hidden" name="shipping[same_as_billing]" value="<?php echo $this->getSameAsBilling(); ?>">
    <input type="hidden" name="shipping_address_id" value="">
    <legend><?php echo $this->__("Shipping address"); ?></legend>
	<?php if(!$deliveryPoint->id): ?>
    <div class="form-group form-checkbox small">
        <input type="checkbox" name="shipping[different_shipping_address]" id="orders_someone_else" class="css-checkbox orders_someone_else" <?php if ($this->getOrderSomeoneElseFlag()) : ?>checked<?php endif; ?> />
        <label for="orders_someone_else" class="css-label orders_someone_else"><?php echo $this->__("I'm buing for someone else."); ?></label>
    </div>

    <div class="form-group clearfix <?php if (!$this->getOrderSomeoneElseFlag()) : ?>hidden<?php endif; ?> border-top orders_someone_else">
        <div class="form-group clearfix" style="margin-bottom: 15px;">
            <div class="row">
                <label class="col-lg-3 col-md-3 col-sm-3 col-xs-12" for="shipping_firstname"><?php echo $this->__("First name"); ?></label>
                <div class="col-lg-9 col-md-9 col-sm-9 col-xs-12">
                    <input value="<?php echo $this->escapeHtml($shippingAddress->getFirstname()); ?>" type="text" class="form-control firstName hint" required="true" id="shipping_firstname" title="" name="shipping[firstname]" />
                </div>
            </div>
        </div>
        <div class="form-group clearfix border-top">
            <div class="row">
                <label class="col-lg-3 col-md-3 col-sm-3 col-xs-12" for="shipping_lastname"><?php echo $this->__("Last name"); ?></label>
                <div class="col-lg-9 col-md-9 col-sm-9 col-xs-12">
                    <input type="text" value="<?php echo $this->escapeHtml($shippingAddress->getLastname()); ?>" class="form-control lastName hint" id="shipping_lastname" title="" name="shipping[lastname]" required="true" />
                </div>
            </div>
        </div>
    </div>

    <div class="form-group clearfix border-top <?php if (!$this->getOrderSomeoneElseFlag()) : ?>hidden<?php endif; ?> orders_someone_else">
        <div class="row">
            <label class="col-lg-3 col-md-3 col-sm-3 col-xs-12" for="shipping_telephone"><?php echo $this->__("Telephone number"); ?></label>
            <div class="col-lg-9 col-md-9 col-sm-9 col-xs-12">
                <input type="tel" value="<?php echo $this->escapeHtml($shippingAddress->getTelephone()); ?>" class="form-control validate-telephone phone" id="shipping_telephone" title="" name="shipping[telephone]" required="true" data-original-title="<?php echo $this->__("Phone number we need only to contact concerning orders for example courier delivering the shipment."); ?>" />
            </div>
        </div>
    </div>

    <div class="form-group border-top clearfix">
        <div class="row">
            <label class="col-lg-3 col-md-3 col-sm-3 col-xs-12" for="shipping_street"><?php echo $this->__("Street and number"); ?></label>
            <div class="col-lg-9 col-md-9 col-sm-9 col-xs-12">
                <input type="text" value="<?php echo $this->escapeHtml(is_array($shippingAddress->getStreet(-1)) ? explode(" ", $shippingAddress->getStreet(-1)) : $shippingAddress->getStreet(-1)); ?>" class="form-control street" id="shipping_street" title="" name="shipping[street][]" required="true" />
            </div>
        </div>
    </div>

    <div class="form-group clearfix border-top">
        <div class="row">
            <label class="col-lg-3 col-md-3 col-sm-3 col-xs-12" for="shipping_postcode"><?php echo $this->__("Zip code"); ?></label>
            <div class="col-lg-9 col-md-9 col-sm-9 col-xs-12">
                <input type="tel" value="<?php echo $this->escapeHtml($shippingAddress->getPostcode()); ?>" class="form-control zipcode validate-postcodeWithReplace" required="true" id="shipping_postcode" title="" name="shipping[postcode]" data-original-title="<?php echo $this->__("Zip-code should be entered in the format xx-xxx."); ?>" />
                <div id="zip-warning" class="checkout-warning"></div>
            </div>
        </div>
    </div>

    <div class="form-group clearfix border-top">
        <div class="row">
            <label class="col-lg-3 col-md-3 col-sm-3 col-xs-12" for="shipping_city"><?php echo $this->__("City"); ?></label>
            <div class="col-lg-9 col-md-9 col-sm-9 col-xs-12">
                <input type="text" value="<?php echo $this->escapeHtml($shippingAddress->getCity()); ?>" class="form-control city hint" id="shipping_city" title="" name="shipping[city]" required="true" />
            </div>
        </div>
    </div>

    <div class="form-group clearfix border-top hide-success-vaild">
        <div class="row">
            <label class="col-lg-3 col-md-3 col-sm-3 col-xs-12 double-line" for="shipping_company"><?php echo $this->__("Company<br>(optional)"); ?></label>
            <div class="col-lg-9 col-md-9 col-sm-9 col-xs-12">
                <input type="text" value="<?php echo $this->escapeHtml($shippingAddress->getCompany()); ?>" class="form-control firm hint" id="shipping_company" title="" name="shipping[company]" />
            </div>
        </div>
    </div>
	<?php else: // is delivery point set ?>
	<div id="inpost-wrapper" class="panel panel-default checkout-delivery-point-wrapper customer-not-logged-in">
		<div class="panel-body">
			<div class="form-group">
				<input id="orders_someone_else" name="shipping[different_shipping_address]" type="checkbox" class="hidden"/>
				<input id="delivery_point_name"  name="delivery_point[name]" value="<?php echo $deliveryPoint->delivery_point_name; ?>" type="hidden"/>
				<div class="row inpost-info">
					<div class="col-xs-7 col-sm-6 col-md-6 col-lg-6" >
                        <strong><?php echo $deliveryPoint->checkout->title; ?></strong>

                        <input name="shipping[firstname]" type="hidden"
                               value="<?php echo $deliveryPoint->checkout->title; ?>"
                               class="form-control firstName hint"
                               required="true" id="shipping_firstname" title=""/>
                        <input name="shipping[lastname]" type="hidden" value="<?php echo $deliveryPoint->name; ?>"
                               class="form-control lastName hint" id="shipping_lastname"
                               title=""
                               required="true"/>
                        <br/>
                        <span id="inpost-locker-street"><?php echo $deliveryPoint->street; ?></span>
                        <span id="inpost-locker-building-number"><?php echo $deliveryPoint->buildingNumber; ?></span>
                        <input name="shipping[street][]" type="hidden"
                               value="<?php echo $deliveryPoint->street; ?> <?php echo $deliveryPoint->buildingNumber; ?>"
                               class="form-control street" id="shipping_street" title="" required="true"/>
                        <br/>
                        <span id="inpost-locker-postcode"><?php echo $deliveryPoint->postcode; ?></span>
                        <span id="inpost-locker-town"><?php echo $deliveryPoint->city; ?></span>
                        <input name="shipping[postcode]" type="hidden"
                               value="<?php echo $this->escapeHtml($deliveryPoint->postcode); ?>"
                               class="form-control zipcode validate-postcodeWithReplace" required="true"
                               id="shipping_postcode" title=""
                               data-original-title="<?php echo $this->__("Zip-code should be entered in the format xx-xxx."); ?>"/>
                        <br/>
                        <input name="shipping[city]" type="hidden"
                               value="<?php echo $this->escapeHtml($deliveryPoint->city); ?>"
                               class="form-control city hint" id="shipping_city" title="" required="true"/>
                        <span id="inpost-locker-location-description"><?php if(!empty($deliveryPoint->locationDescription)): ?>(<?php echo $deliveryPoint->locationDescription; ?>)<?php endif; ?></span>
					</div>
					<div class="col-xs-5 col-sm-6 col-md-6 col-lg-6 text-right">
						<div class="figure-button-wrapper">
							<?php echo $deliveryPoint->checkout->logo; ?>
							<a href="<?php echo Mage::getUrl("checkout/cart"); ?>" class="button button-third large change-locker"><?php echo $helper->__('Change'); ?></a>
						</div>
					</div>
				</div>
				<div class="row">
					<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12" >
						<?php echo $this->__("Telephone number"); ?>
						<fieldset>
							<div class="form-group clearfix border-top">
								<div class="row">
									<div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 telephone-for-locker">
                                        <input type="tel" value="<?php echo $this->escapeHtml($this->getLastTelephoneForLocker()); ?>" class="form-control validate-telephone phone" id="telephone_for_locker" title="" name="shipping[telephone]" required="true" data-original-title="<?php echo $this->__("Phone number we need only to contact concerning orders for example courier delivering the shipment."); ?>" />
									</div>
                                    <?php if(!empty($deliveryPoint->checkout->additionalInfo1) || !empty($deliveryPoint->checkout->additionalInfo2)): ?>
                                        <div class="col-lg-8 col-md-8 col-sm-8 col-xs-12 telephone-for-locker-comment">
                                            <?php echo $deliveryPoint->checkout->additionalInfo1; ?>
                                            <?php echo $deliveryPoint->checkout->additionalInfo2; ?>
                                        </div>
                                    <?php endif; ?>
								</div>
							</div>
						</fieldset>
					</div>
				</div>
				<div class="clearfix"></div>
			</div>
		</div>
	</div>
	<?php endif; ?>
</fieldset>