<?php
/**
 * Author: Paweł Chyl <pawel.chyl@orba.pl>
 * Date: 08.09.2014
 */

?>

<fieldset>
    <legend><?php echo $this->__("Shipping address:"); ?></legend>
    <div class="form-group form-checkbox small">
        <input type="checkbox" name="rodzaj" id="orders_someone_else" class="css-checkbox orders_someone_else">
        <label for="orders_someone_else" class="css-label orders_someone_else"><?php echo $this->__("I'm buing for someone else."); ?></label>
    </div>

    <div class="form-group clearfix hidden border-top orders_someone_else">
        <div class="form-group clearfix">
            <div class="row">
                <label class="col-sm-3" for="for_first_name"><?php echo $this->__("First name"); ?></label>
                <div class="col-sm-5"><input type="text" class="form-control firstName hint" id="for_first_name" title="" name="shipping[firstname]" data-original-title="<?php echo $this->__("Enter your name."); ?>"></div>
            </div>

        </div>
        <div class="form-group clearfix border-top">
            <div class="row">
                <label class="col-sm-3" for="for_last_name"><?php echo $this->__("Last name"); ?></label>
                <div class="col-sm-5">
                    <input type="text" class="form-control lastName hint" id="for_last_name" title="" name="shipping[lastname]" data-original-title="<?php echo $this->__("Enter your last name"); ?>">
                </div>
            </div>
        </div>
    </div>

    <div class="form-group clearfix border-top hidden orders_someone_else">
        <div class="row">
            <label class="col-sm-3" for="phone_number"><?php echo $this->__("Telephone number"); ?></label>
            <div class="col-sm-5">
                <input type="text" class="form-control" id="phone_number" title="" name="shipping[telephone]" data-original-title="<?php echo $this->__("We need your telephone number only to complete the order."); ?>">
            </div>
        </div>
    </div>

    <div class="form-group border-top clearfix">
        <div class="row">
            <label class="col-sm-3" for="street"><?php echo $this->__("Street and number"); ?></label>
            <div class="col-lg-7 col-md-5 col-sm-5">
                <input type="text" class="form-control street" id="street" title="" name="shipping[street][]" data-original-title="<?php echo $this->__("Street and number"); ?>">
            </div>
        </div>
    </div>

    <div class="form-group clearfix border-top">
        <div class="row">
            <label class="col-sm-3" for="zip_code"><?php echo $this->__("Zip code"); ?></label>
            <div class="col-sm-5">
                <input type="text" class="form-control zipcode" id="zip_code" title="" name="shipping[postcode]" data-original-title="<?php echo $this->__("Zip code"); ?>">
            </div>
        </div>
    </div>

    <div class="form-group clearfix border-top">
        <div class="row">
            <label class="col-sm-3" for="city"><?php echo $this->__("City"); ?></label>
            <div class="col-sm-5">
                <input type="text" class="form-control city hint" id="city" title="" name="shipping[city]" data-original-title="<?php echo $this->__("City"); ?>">
            </div>
        </div>
    </div>

    <div class="form-group clearfix border-top">
        <div class="row">
            <label class="col-sm-3 double-line" for="firm_name"><?php echo $this->__("Company<br>(optional)"); ?></label>
            <div class="col-lg-7 col-md-5 col-sm-5">
                <input type="text" class="form-control firm hint" id="shipping:company" title="" name="shipping[company]" data-original-title="<?php echo $this->__("Company"); ?>">
            </div>
        </div>
    </div>
</fieldset>