<?php
/**
 * Author: Paweł Chyl <pawel.chyl@orba.pl>
 * Date: 29.07.2014
 *
 * cross sell items template
 *
 * @see Mage_Catalog_Block_Product_List_Crosssell
 */

/** @var $this Mage_Catalog_Block_Product_List_Crosssell */
/** @var $_item Zolago_Catalog_Model_Product */
$likeWithStrikeoutPrice = false;
?>
<?php if(count($this->getItems()) > 0) : ?>
    <section id="complementary_product" class="section bg-w clearfix" data-mobiletoggle="true">
        <div class="block-complementary-product toggle-xs">
            <header>
                <h2 class="title_section"><?php echo $this->__("Complete whole collection"); ?> <i
                        class="bullet-strzalka-up visible-xs"></i></h2>
            </header>
            <div id="rwd-complementary-product" class="rwdCarousel">
                <div class="rwd-carousel rwd-theme">
                    <?php foreach ($this->getItems() as $_item) : ?>
                        <div class="item">
                            <a href="<?php echo $_item->getProductUrl(); ?>">

                                <div class="box_listing_product">
                                    <figure class="img_product"><img
                                            src="<?php echo $this->helper('catalog/image')->init($_item, 'thumbnail')->resize(171, 219); ?>" alt="<?php echo $this->escapeHtml($_item->getName()) ?>"
                                            class="img-responsive"></figure>
                                    <div class="name_product hidden-xs">
                                        <?php echo $this->getShortProductName($_item, 50); ?>
                                        <?php echo $_item->getStrikeoutPrice() . ' ' . $_item->getFinalPrice(); ?>
                                    </div>
                                    <div class="price clearfix hidden-xs like-two-line">
                                        <div class="col-price">

                                            <?php if($_item->getStrikeoutPrice() > $_item->getFinalPrice()) : ?>
                                                <?php $likeWithStrikeoutPrice = true; ?>
                                                <div class="strikeout-price">
                                                    <?php echo Mage::helper('core')->currency($_item->getStrikeoutPrice(), true, false); ?>
                                                </div>
                                            <?php endif; ?>
                                            <div class="final-price">
                                                <?php echo Mage::helper('core')->currency($_item->getFinalPrice(), true, false); ?>
                                            </div>
                                        </div>
                                        <div class="like <?php echo $likeWithStrikeoutPrice ? ' like-with-strikeout-price ' : ''; ?>
                                        <?php if(Mage::getBlockSingleton('zolagomodago/wishlist')->isInWishlist($_item)) {echo ' liked '; } ?>"
                                             data-idproduct="<?php echo $_item->getId(); ?>"
                                             data-status="<?php echo (int) Mage::helper('zolagowishlist')->productBelongsToMyWishlist($_item); ?>"
                                             onclick="
                                             <?php if(Mage::helper('zolagowishlist')->productBelongsToMyWishlist($_item))
                                             {
                                                 echo 'Mall.wishlist.removeFromSmallBlock(this);return false;';
                                             } else {
                                                 echo 'Mall.wishlist.addFromSmallBlock(this);return false;';
                                             } ?>">
                                            <span class="icoLike">
                                                <img class="img-01" src="<?php echo $this->getSkinUrl('images/heart.png'); ?>" alt=""/>
                                                <img class="img-02" src="<?php echo $this->getSkinUrl('images/heart-like.png'); ?>" alt=""/>
                                            </span>
                                            <span class="like_count">
                                                <span>
                                                </span>
                                            </span>

                                            <div class="toolLike"></div>
                                        </div>
                                    </div>
                                </div>

                            </a>
                        </div>
                        <?php $likeWithStrikeoutPrice = false; ?>
                    <?php endforeach; ?>
                </div>

            </div>
        </div>
    </section>
    <script type="text/javascript">
        <?php foreach($this->getItems() as $_item) : ?>
        Mall.wishlist.addProduct({
            id: <?php echo (int) $_item->getId(); ?>,
            wishlist_count: <?php echo (int) $_item->getWishlistCount(); ?>,
            in_your_wishlist: <?php echo Mage::helper('zolagowishlist')->productBelongsToMyWishlist($_item) ? "true" : "false" ;?>
        });
        <?php endforeach; ?>
        Mall.translate.add("you", "<?php echo $this->__("You"); ?>");
    </script>
<?php endif; ?>