<?php
/**
 * Product media data template
 *
 * @see Mage_Catalog_Block_Product_View_Media
 */
/** @var Mage_Catalog_Block_Product_View_Media $this */
$_product = $this->getProduct();
$_helper = $this->helper('catalog/output');
$_zolagoCatalogBlock = Mage::getBlockSingleton('zolagocatalog/product_view');
$nImagesForCssStyle = 5; //magic number, for less then 5 items height of box is auto
$_images = $this->getGalleryImages();
?>

<?php if (count($this->getGalleryImages()) > 0): ?>
    <?php $_dimensions = array(); ?>
    <?php foreach ($_images as $k => $_image): ?>
        <?php $_dimensions[$k] = @getimagesize($_image->getPath()); ?>
    <?php endforeach; ?>
    <div id="product-gallery" class="col-lg-5 col-xs-12 clearfix">
        <div id="wrapper-productGalleryThumbMedia">
            <a href="#" class="up"><?php echo $this->__("up"); ?></a>
            <div id="productGalleryThumbMedia" class="rwd-carousel <?php echo count($this->getGalleryImages()) < $nImagesForCssStyle ? 'auto-height' : ''; ?> ">
            <?php foreach ($this->getGalleryImages() as $_image): ?>
                <div class="item"><img src="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize(67, 86); ?>" width="67" height="86" alt="<?php echo $this->escapeHtml($_image->getLabel()) ?>"></div>
            <?php endforeach; ?>
            </div>
            <a href="#" class="down"><?php echo $this->__("down"); ?></a>
        </div>
        <div id="productGalleryBigMedia">
            <?php $i = 0; ?>
            <?php foreach ($_images as $k => $_image): ?>
                <?php if (isset($_dimensions[$k]) && is_array($_dimensions[$k]) && isset($_dimensions[$k][0], $_dimensions[$k][1])): ?>
                    <div class="item">
                        <div>
                            <a href="#" data-flags="<?php echo $_zolagoCatalogBlock->getProductFlagLabel(); ?>" onclick="return false;">
                                <img src="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'image', $_image->getFile())->keepAspectRatio(true)->constrainOnly(true)->keepFrame(false)->resize(319); ?>"  alt="<?php echo $this->escapeHtml($_image->getLabel()) ?>" <?php if($i == 0): ?> itemprop="image" <?php endif; ?>
                                     data-ratio="<?php echo number_format((float)($_dimensions[$k][1] / $_dimensions[$k][0]), 4, '.', ''); ?>" />
                                <span class="view_lupa view_lupa_plus"></span>
                            </a>
                        </div>
                    </div>
                    <?php $i++; ?>
                <?php endif; ?>
            <?php endforeach; ?>
        </div>
        <div class="followUs hidden-xs">
            <div class="addthis_sharing_toolbox"></div>
        </div>
    </div>
<?php endif; ?>