<?php /* @var $this Mage_Catalog_Block_Product_View_Media */ ?>
<?php /* @var $this Mage_Catalog_Block_Product_View_Media */ ?>
<?php
/**
 * Author: Paweł Chyl <pawel.chyl@orba.pl>
 * Date: 18.07.2014
 */

?>

<?php
    $_product = $this->getProduct();
    $_helper = $this->helper('catalog/output');
    $_zolagoCatalogBlock = Mage::getBlockSingleton('zolagocatalog/product_view');
?>

<div id="galeria-lightbox-wr" style="display: none;">

    <div id="galeria-lightbox" class="clearfix">
        <div id="wrapper-productGalleryThumbMediaOpen">
            <a href="#" class="up"><?php echo $this->__("up"); ?></a>
            <div id="productGalleryThumbMediaOpen" class="rwd-carousel">
                <?php foreach ($this->getGalleryImages() as $_image): ?>
                    <div class="item"><img src="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize(67, 86); ?>" width="67" height="86" alt="<?php echo $this->escapeHtml($_image->getLabel()) ?>"></div>
                <?php endforeach; ?>
            </div>
            <a href="#" class="down"><?php echo $this->__("down"); ?></a>
        </div>
        <div id="sync3" class="">
            <?php foreach ($this->getGalleryImages() as $_image): ?>
                <?php
                    $_imageInitialized = $this->helper('catalog/image')->init($this->getProduct(), 'image', $_image->getFile());
                ?>
            <div class="item">
                <div class="inner-item" data-flags="<?php echo $_zolagoCatalogBlock->getProductFlagLabel(); ?>">
                    <img src="<?php echo $_imageInitialized->keepAspectRatio(true)->constrainOnly(true)->keepFrame(false)->resize(500); ?>"  alt="<?php echo $this->escapeHtml($_image->getLabel()) ?>" data-width="<?php echo $_imageInitialized->getOriginalWidth(); ?>" data-height="<?php echo $_imageInitialized->getOriginalHeight(); ?>">
                    <a href="#" class="zoom_plus <?php echo 500 > $_imageInitialized->getOriginalWidth() ? 'disabled' : '' ?>"><span></span></a><a href="#" class="zoom_minus disabled"><span></span></a>
                </div>
            </div>
            <?php endforeach; ?>

        </div>
    </div>
</div>