<?php /* @var $this Mage_Catalog_Block_Product_View_Media */ ?>
<?php /* @var $this Mage_Catalog_Block_Product_View_Media */ ?>
<?php
/**
 * Author: Paweł Chyl <pawel.chyl@orba.pl>
 * Date: 18.07.2014
 */

?>
<?php
    $_product = $this->getProduct();
    $_helper = $this->helper('catalog/output');
?>

<div id="galeria-lightbox-wr" style="display: none;">

    <div id="galeria-lightbox" class="clearfix">
        <div id="wrapper-sync4">
            <a href="#" class="up">góra</a>
            <div id="sync4" class="rwd-carousel">

                <div class="item"><img src="skin/frontend/modago/default/images/product/thumb/product-thumb.png"    data-width="67" data-height="86" alt=""></div>
                <div class="item"><img src="skin/frontend/modago/default/images/product/thumb/product-thumb-03.png" data-width="67" data-height="86" alt=""></div>
                <div class="item"><img src="skin/frontend/modago/default/images/product/thumb/product-thumb-04.png" data-width="67" data-height="86" alt=""></div>
                <div class="item"><img src="skin/frontend/modago/default/images/product/thumb/product-thumb-05.png" data-width="67" data-height="86" alt=""></div>

                <div class="item"><img src="skin/frontend/modago/default/images/product/thumb/product-thumb.png"    data-width="67" data-height="86" alt=""></div>
                <div class="item"><img src="skin/frontend/modago/default/images/product/thumb/product-thumb-03.png" data-width="67" data-height="86" alt=""></div>
                <div class="item"><img src="skin/frontend/modago/default/images/product/thumb/product-thumb-04.png" data-width="67" data-height="86" alt=""></div>
                <div class="item"><img src="skin/frontend/modago/default/images/product/thumb/product-thumb-05.png" data-width="67" data-height="86" alt=""></div>



            </div>
            <a href="#" class="down">dół</a>
        </div>
        <div id="sync3" class="">
            <div class="item">
                <div class="inner-item">

                    <img src="skin/frontend/modago/default/images/product/images/product-large-medium-1.png"  alt="" data-width="500" data-height="636">
                    <a href="#" class="zoom_plus"><span></span></a><a href="#" class="zoom_minus disabled"><span></span></a>
                </div>
            </div>
            <div class="item">
                <div class="inner-item">

                    <img src="skin/frontend/modago/default/images/product/images/product-large-big.png"  alt="" data-width="1400" data-height="1781">
                    <a href="#" class="zoom_plus"><span></span></a><a href="#" class="zoom_minus disabled"><span></span></a>

                </div>
            </div>
            <div class="item">
                <div class="inner-item">

                    <img src="skin/frontend/modago/default/images/product/images/product-medium-3.png"  alt="" data-width="319" data-height="406">
                    <a href="#" class="zoom_plus"><span></span></a><a href="#" class="zoom_minus disabled"><span></span></a>
                </div>
            </div>
            <div class="item">
                <div class="inner-item">

                    <img src="skin/frontend/modago/default/images/product/images/product-medium-4.png"  alt="" data-width="319" data-height="406">
                    <a href="#" class="zoom_plus"><span></span></a><a href="#" class="zoom_minus disabled"><span></span></a>
                </div>
            </div>

            <div class="item">
                <div class="inner-item">

                    <img src="skin/frontend/modago/default/images/product/images/product-medium-1.png"  alt="" data-width="319" data-height="406">
                    <a href="#" class="zoom_plus"><span></span></a><a href="#" class="zoom_minus disabled"><span></span></a>
                </div>
            </div>

            <div class="item">
                <div class="inner-item">

                    <img src="skin/frontend/modago/default/images/product/images/product-medium-2.png"  alt="" data-width="319" data-height="406">
                    <a href="#" class="zoom_plus"><span></span></a><a href="#" class="zoom_minus disabled"><span></span></a>
                </div>
            </div>

            <div class="item">
                <div class="inner-item">

                    <img src="skin/frontend/modago/default/images/product/images/product-medium-3.png"  alt="" data-width="319" data-height="406">
                    <a href="#" class="zoom_plus"><span></span></a><a href="#" class="zoom_minus disabled"><span></span></a>
                </div>
            </div>

            <div class="item">
                <div class="inner-item">

                    <img src="skin/frontend/modago/default/images/product/images/product-medium-4.png"  alt="" data-width="319" data-height="406">
                    <a href="#" class="zoom_plus"><span></span></a><a href="#" class="zoom_minus disabled"><span></span></a>
                </div>
            </div>

        </div>
    </div>
</div>