<?php /* @var $this Mage_Review_Block_Product_View */ ?>
<?php
/**
 * Author: Paweł Chyl <pawel.chyl@orba.pl>
 * Date: 23.07.2014
 */
?>
<?php
    // review label
    $_reviewsCount = count($this->getReviewsCollection());
    $_reviewsLabel = '';
    switch($_reviewsCount) {
        case 0:
            $_reviewsLabel = $this->__('Zero reviews');
            break;
        case 1:
            $_reviewsLabel = $this->__('Singular review');
            break;
        case 2:
        case 3:
        case 4:
            $_reviewsLabel = $this->__('review');
            break;
        default:
            $_reviewsLabel = $this->__('Zero reviews');
            break;
    }
    // avarage rating
    $reviews = Mage::getModel('review/review')->getResourceCollection()->addStoreFilter(Mage::app()->getStore()->getId())
        ->addEntityFilter('product', $this->getProduct()->getId())
        ->addStatusFilter(Mage_Review_Model_Review::STATUS_APPROVED)
        ->setDateOrder()
        ->addRateVotes();

$avg = 0;
$ratings = array();
$v = array();
$p = array_fill(1, 5, 0);
$voteCount = 0;
/** @var $vote Mage_Rating_Model_Rating_Option_Vote */
foreach ($reviews as $review) {
    foreach ($review->getRatingVotes() as $vote) {
        $voteCount++;
            $ratings[] = $vote->getPercent();
            if(array_key_exists($vote->getRatingCode(), $v)) {
                $v[$vote->getRatingCode()] += $vote->getPercent();
            } else  {
                $v[$vote->getRatingCode()] = $vote->getPercent();
            }

            if(array_key_exists($vote->getPercent()/10/2, $p)) {
                $p[$vote->getPercent()/10/2]++;
            } else {
                $p[$vote->getPercent()/10/2] = 1;
            }
        }

}
krsort($p);
$avg = count($ratings) > 0 ? ceil(array_sum($ratings)/count($ratings)/10/2) : 0;
Mage::getBlockSingleton('page/html_pager')->setCollection($this->getReviewsCollection());
?>

<section id="note_product" class="section toggle-xs bg-w clearfix">
    <header>
        <h2 class="title_section"><?php echo $this->__("Product reviews"); ?> <i class="bullet-strzalka-down visible-xs"></i>
        <span id="average_note_client" class="visible-xs">
            <span class="note" data-number="5" data-score="<?php echo $avg; ?>"></span>
            <span>(<?php echo $_reviewsCount; ?> <?php echo $_reviewsLabel; ?>)</span>
        </span>
        </h2>

    </header>
    <div class="main clearfix no-padding-bottom">
        <div id="statystyki_opinii" class="row">
            <div class="col-md-9 col-sm-12">
                <div class="row">
                    <div class="col-sm-5">
                        <dl class="raty_note">
                            <dt><strong><?php echo $this->__("Avarage"); ?>:</strong><div id="average_rating" data-number="5" data-score="<?php echo $avg; ?>"></div></dt>
                            <?php foreach($v as $k => $_vote) : ?>
                            <dd><strong><?php echo $k; ?></strong> <div id ="<?php echo $k; ?>_rating" data-number="5" data-score="<?php echo ceil($_vote/count($ratings)/10); ?>"></div></dd>
                            <?php endforeach; ?>
                        </dl>
                    </div>
                    <div class="col-md-4 col-sm-5">
                        <dl class="rating_note">
                            <dt><?php echo $this->__("Product reviews count"); ?>: <span><?php echo $_reviewsCount; ?><span></dt>
                            <?php foreach($p as $k => $v) : ?>
                            <dd><span class="prefix"><?php echo $this->__("rating"); ?> <?php echo $k; ?>/5</span><span class="rating" data-percent="<?php echo $voteCount > 0 ? ceil($v / $voteCount * 100) : 0; ?>"><span></span></span><span class="suffix"><?php echo $v; ?></span></dd>
                            <?php endforeach; ?>
                        </dl>
                    </div>
                    <?php echo $this->getChildHtml('product_review_list.toolbar'); ?>
                </div>
            </div>
            <div class="add_opinion col-md-3 col-sm-12 hidden-xs">
                <p><?php echo $this->__("Share your review with other users"); ?><br><a href="#block-review-form" class="btn black viewFormComments"><span class="ico ico_note"></span> <?php echo $this->__("Add your review"); ?></a></p>
            </div>
        </div>

    </div>
    <!-- ==================== COMMENTS ================================ -->
    <div class="main clearfix">
        <div class="col-sm-12" id="comments">
            <div class="row">
                <?php foreach($this->getReviewsCollection()->getItems() as $review) : ?>
                    <?php
                    $ratingModel = Mage::getSingleton('rating/rating')->getReviewSummary($review->getReviewId());
                    $sum = ceil($ratingModel->getSum()/10/3/2);
                    ?>
                <div class="comment row">
                    <div class="wrapper-header col-sm-6">
                        <div class="header">
                            <div class="comment_rating" data-number="5" data-score="<?php echo $sum; ?>"></div>
                            <h3 class="title_comment"><?php echo $this->escapeHtml($review->getTitle()); ?></h3>
                        </div>
                        <div class="meta">
                            <span class="meta-label"><?php echo $this->__("Review written by"); ?>:</span><span class="date"><?php echo date("Y-m-d", strtotime($review->getCreatedAt())); ?></span> <?php echo $this->__("by"); ?> <span class="name_user"><?php echo $review->getNickname(); ?></span>
                        </div>
                    </div>
                    <div class="body_comments col-sm-12">
                        <p><?php echo $this->escapeHtml($review->getDetail()); ?></p>
                    </div>

                </div>
                <?php endforeach; ?>

                <?php echo $this->getChildHtml('product.review.form'); ?>
            </div>
        </div>
    </div>
    <!-- ====================== END :// COMMENTS ================================== -->
</section>
