<!-- PRODUCT SHOP -->
<?php
/** @var Zolago_Modago_Block_Catalog_Product_View_Shop $this */
/** @var Zolago_Catalog_Model_Product $_product */
/** @var Mage_Catalog_Helper_Output $_helper */
/** @var Zolago_Catalog_Helper_Data $hlp */

$_product = $this->getProduct();
$_helper = $this->helper('catalog/output');
$hlp = Mage::helper('catalog/data');
$isSalable = $_product->isSalable(); //product is salable
// prices
$price = $_product->getPrice();
$finalPrice = $_product->getFinalPrice();
$sizeAttr = $_product->getResource()->getAttribute('size');
$productAttrs = array();
if($_product->getTypeId() == 'configurable') {
    $productAttrs = $_product->getTypeInstance(true)->getConfigurableAttributesAsArray($_product);
}

$_helperSizetable = Mage::helper('zolagosizetable');
/** @var Zolago_Sizetable_Helper_Data $_helperSizetable */
$vendor_id = $_product->getData('udropship_vendor');
$storeId = Mage::app()->getStore()->getStoreId();
$attributeSetId = $_product->getData('attribute_set_id');
$brandId = $_product->getData( 'manufacturer');
if($_product->getTypeId() == 'configurable') { //fix for simple products
	/** @var Zolago_Catalog_Block_Product_View_Type_Configurable $salableCount */
	$salableCount = Mage::getBlockSingleton('zolagocatalog/product_view_type_configurable')->getSalableCount();
}
$sizeTableValue = $_helperSizetable->getSizetableCMS($vendor_id, $storeId, $attributeSetId, $brandId,$_product);
?>


<?php

$productName = $_helper->productAttribute($_product, $_product->getName(), 'name');

//$vendor = Mage::helper('udropship')->getVendor($vendor_id);
//$vendorName = $vendor->getData("vendor_name");
//$vendorUrl = Mage::helper("umicrosite")->getVendorUrl($vendor);
//$productName = str_replace($vendorName, "<a itemprop='brand' href='".$vendorUrl."'>".$vendorName."</a>",$productName);
?>
<div id="product-shop" class="col-lg-8 col-md-12 col-sm-12 clearfix" style="overflow-x:visible;">
    <form action="<?php echo $this->getSubmitUrl($_product) ?>" method="post" id="product_addtocart_form"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
        <?php echo $this->getBlockHtml('formkey') ?>
        <div class="no-display">
            <input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
            <input type="hidden" name="related_product" id="related-products-field" value="" />
        </div>

        <div class="product-name"><h1 itemprop="name"><?php echo $productName; ?></h1></div>
        <meta itemprop="sku" content="<?php echo $_product->getSku() ?>" />
        <p class="short-description hidden-xs">
            <?php echo $_helper->productAttribute($_product, nl2br($_product->getShortDescription()), 'short_description') ?>
        </p>

        <?php if ($_product->getCanShowPrice() !== false): ?>
            <?php
            $currencyCode = Mage::app()->getStore()->getCurrentCurrencyCode();
            $currencySymbol = Mage::app()->getLocale()->currency($currencyCode)->getSymbol();;

            ?>
            <div class="price-box-bundle">
                <div class="price-box" >
                    <p class="price" itemprop="offers" itemscope itemtype="http://schema.org/Offer">
                        <?php if($_product->getTypeId() == Mage_Catalog_Model_Product_Type::TYPE_CONFIGURABLE):  ?>
                            <meta itemprop="price" content="<?php echo round($_product->getFinalPrice(), 2); ?>" />
                        <?php endif; ?>

                        <meta itemprop="priceCurrency" content="<?php echo $currencyCode; ?>" />
                        <meta itemprop="mpn" content="<?php echo $_product->getSku(); ?>"/>

                        <?php if ($isSalable): ?>
                            <meta itemprop="availability" content="http://schema.org/InStock"/>
                        <?php else: ?>
                            <meta itemprop="availability" content="http://schema.org/OutOfStock"/>
                        <?php endif; ?>

                        <meta itemprop="itemCondition" itemtype="http://schema.org/OfferItemCondition" content="http://schema.org/NewCondition"/>
                        <span class="price-label"><?php echo $this->__("price"); ?>:</span>
                        <span class="old-price"><?php if($_product->getTypeId() != Mage_Catalog_Model_Product_Type::TYPE_CONFIGURABLE && $_product->getStrikeoutPrice() != $_product->getFinalPrice()) : ?><?php echo str_replace(" ","&nbsp;",Mage::helper('core')->currency($_product->getStrikeoutPrice(), true, false)); ?><?php endif; ?></span>
                        <span class="price"><?php if($_product->getTypeId() != Mage_Catalog_Model_Product_Type::TYPE_CONFIGURABLE):  ?><span itemprop="price"><?php echo number_format($_product->getFinalPrice(), 2, ',', ' '); ?></span> <?php echo $currencySymbol; ?><?php endif; ?></span>
                    </p>
                </div>
                <ul>
                    <li><?php echo $this->getStoreDeliveryHeadline(); ?></li>
                    <li><?php echo $this->getStoreReturnHeadline(); ?></li>
                </ul>
            </div>
        <?php endif; ?>
        <?php if($_product->getTypeId() == Mage_Catalog_Model_Product_Type::TYPE_CONFIGURABLE) : ?>

            <!--    Meta tags-->
            <?php
            $childrenData = array();
            $childProducts = Mage::getModel('catalog/product_type_configurable')
                ->getUsedProducts(null, $_product);
            foreach ($childProducts as $child) {
                $childrenData[$child->getId()] = $child->getSku();
            }

            /* @var $productViewTypeConfigurableBlock Zolago_Catalog_Block_Product_View_Type_Configurable  */
            $productViewTypeConfigurableBlock = Mage::getBlockSingleton('zolagocatalog/product_view_type_configurable');
            $config = $productViewTypeConfigurableBlock->getConfig();
            $basePrice = $config['basePrice'];
            if (isset($config['attributes']) & !empty($config['attributes'])):
                $attributes = $config['attributes'];
                foreach ($attributes as $attributeId => $attributeData):
                    if ($attributeData['code'] == "size" && (isset($attributeData['options']) & !empty($attributeData['options']))):
                        $options = $attributeData['options'];
                        foreach ($options as $option):
                            ?>
                            <span itemprop="offers" itemscope itemtype="http://schema.org/Offer">
                                <meta itemprop="price" content="<?php echo round(($_product->getFinalPrice() + $option['price']), 2); ?>"/>
                                <meta itemprop="priceCurrency" content="<?php echo $currencyCode; ?>"/>

                                <meta itemprop="mpn" content="<?php echo $childrenData[$option['products'][0]]; ?>"/>

                                <?php if ($option['is_salable']): ?>
                                    <meta itemprop="availability" content="http://schema.org/InStock"/>
                                <?php else: ?>
                                    <meta itemprop="availability" content="http://schema.org/OutOfStock"/>
                                <?php endif; ?>

                                <meta itemprop="itemCondition" itemtype="http://schema.org/OfferItemCondition" content="http://schema.org/NewCondition"/>
                            </span>
                        <?php
                        endforeach;
                    endif;
                endforeach;
            endif;
            ?>
            <!--    Meta tags-->
        <?php endif; ?>
<!--        catalog.product.related-->
        <?php echo $this->getChildHtml('catalog.product.related'); ?>
<!--        catalog.product.related end-->
        <div class="size-box-bundle" id="product-options">
            <?php if($_product->getTypeId() == Mage_Catalog_Model_Product_Type::TYPE_CONFIGURABLE) : ?>

                <?php if (!empty($productAttrs)) : ?>
                    <?php foreach($productAttrs as $_attribute) : ?>
                        <?php if(array_key_exists('attribute_code', $_attribute) && $_attribute['attribute_code'] == 'size') : ?>
				            <?php $haveSizes = true; ?>
                            <div class="size-box clearfix clr">
                                <div class="size col-sm-12 col-md-12 col-xs-12">
                                    <span class="size-label col-sm-6 col-md-6 col-xs-12"><?php echo $this->__("Select size"); ?></span>
                                    <div class=" sizes-content form-group form-radio col-sm-6 col-md-5 col-xs-4">
                                        <br />
                                        <a href="#" class="view-sizing underline pull-left" data-toggle="modal"
                                           data-target="#tabelaRozmiarow"><?php if (!empty($sizeTableValue)) : ?><?php echo $this->__("Sizes"); ?> <?php endif; ?></a>
                                    </div>
                                </div>
                            </div>
                        <?php endif; ?>
                    <?php endforeach; ?>
                <?php endif; ?>
            <?php endif; ?>

            <div class="row">
                <div class="action-box-bundle clearfix">
                    <div class="col-xs-6" id="product-likeboxes">

                    </div>

                    <?php if ($isSalable): ?>
                        <div class="col-xs-6 text-right">
                            <button class="btn button button-primary ico addBasket"
                                    <?php if(isset($haveSizes) && $haveSizes == true): ?><?php if ($salableCount > 1): ?>title="<?php echo $hlp->__("Choose size first"); ?>" data-toggle="tooltip" <?php endif; ?>data-placemen="top"<?php endif; ?>
                                    id="add-to-cart"
                                    onclick="Mall.addToCart(<?php echo $_product->getId(); ?>, <?php echo !$_product->getStockItem()->getMinSaleQty() ? 1 : $_product->getStockItem()->getMinSaleQty(); ?>);return false;"><?php echo $this->__("add to cart"); ?></button>
                        </div>
                    <?php else: ?>
                        <div class="col-xs-6 text-right">
                            <div class="temporary-absence-product-wrapper">
                                <span class="temporary-absence-product"><?php echo $hlp->__("temporary absence product");//?></span>
                            </div>
                        </div>
                    <?php endif; ?>
                </div>
            </div>
        </div>
    </form>
</div>
<?php /* configurable price/stock data */?>
<?php if($_product->getTypeId() == Mage_Catalog_Model_Product_Type::TYPE_CONFIGURABLE) : ?>

<script type="text/javascript">
    var jsonConfig = <?php echo Mage::getBlockSingleton('zolagocatalog/product_view_type_configurable')->getJsonConfig(); ?>;
    var useSizeboxList =  <?php echo Mage::getModel('eav/entity_attribute_set')->load($_product->getAttributeSetId())->getUseSizeboxList(); ?>;

    jsonConfig.useSizeboxList = useSizeboxList;
    Mall.product.productOptions(jsonConfig);
    Mall.product._current_product_type = "<?php echo Mage_Catalog_Model_Product_Type::TYPE_CONFIGURABLE; ?>";
</script>
<?php endif; ?>
<script type="text/javascript">
    Mall.product._entity_id = <?php echo $_product->getEntityId(); ?>;
</script>