<!-- PRODUCT SHOP -->
<?php
/** @var Zolago_Modago_Block_Catalog_Product_View_Shop $this */
/** @var Zolago_Catalog_Model_Product $_product */
/** @var Mage_Catalog_Helper_Output $_helper */
/** @var Zolago_Catalog_Helper_Data $hlp */
$i = 0;
echo $i++;
$_product = $this->getProduct();
echo $i++;
$_helper = $this->helper('catalog/output');
echo $i++;
$hlp = Mage::helper('catalog/data');
echo $i++;
$isSalable = $_product->isSalable(); //product is salable
echo $i++;
// prices
$price = $_product->getPrice();
echo $i++;
$finalPrice = $_product->getFinalPrice();
echo $i++;
$sizeAttr = $_product->getResource()->getAttribute('size');
echo $i++;
$productAttrs = array();
echo $i++;
if($_product->getTypeId() == 'configurable') {
	echo $i++;
    $productAttrs = $_product->getTypeInstance(true)->getConfigurableAttributesAsArray($_product);
}
echo $i++;

$_helperSizetable = Mage::helper('zolagosizetable');
echo $i++;
/** @var Zolago_Sizetable_Helper_Data $_helperSizetable */
$vendor_id = $_product->getData('udropship_vendor');
echo $i++;
$storeId = Mage::app()->getStore()->getStoreId();
echo $i++;
$attributeSetId = $_product->getData('attribute_set_id');
echo $i++;
$brandId = $_product->getData( 'manufacturer');
echo $i++;
$salableCount  = Mage::getBlockSingleton('zolagocatalog/product_view_type_configurable')->getSalableCount();
echo $i++;
$sizeTableValue = $_helperSizetable->getSizetableCMS($vendor_id, $storeId, $attributeSetId, $brandId);
echo $i++;
?>
<div id="product-shop" class="col-lg-8 col-md-12 col-sm-12 clearfix" style="overflow-x:visible;">
    <form action="<?php echo $this->getSubmitUrl($_product) ?>" method="post" id="product_addtocart_form"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
        <?php echo $this->getBlockHtml('formkey') ?>
        <div class="no-display">
            <input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
            <input type="hidden" name="related_product" id="related-products-field" value="" />
        </div>

        <div class="product-name"><h1><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></h1></div>
        <p class="short-description hidden-xs">
            <?php echo $_helper->productAttribute($_product, nl2br($_product->getShortDescription()), 'short_description') ?>
        </p>

        <?php if ($_product->getCanShowPrice() !== false): ?>
            <div class="price-box-bundle">
                <div class="price-box">
                    <p class="price">
                        <span class="price-label"><?php echo $this->__("price"); ?>:</span>
                        <span class="old-price"><?php if($_product->getTypeId() != Mage_Catalog_Model_Product_Type::TYPE_CONFIGURABLE && $_product->getStrikeoutPrice() != $_product->getFinalPrice()) : ?><?php echo str_replace(" ","&nbsp;",Mage::helper('core')->currency($_product->getStrikeoutPrice(), true, false)); ?><?php endif; ?></span>
                        <span class="price"><?php if($_product->getTypeId() != Mage_Catalog_Model_Product_Type::TYPE_CONFIGURABLE):  ?><?php echo str_replace(" ","&nbsp;",Mage::helper('core')->currency($_product->getFinalPrice(), true, false)); ?><?php endif; ?></span>
                    </p>
                </div>
                <ul>
                    <li><?php echo $this->getStoreDeliveryHeadline(); ?></li>
                    <li><?php echo $this->getStoreReturnHeadline(); ?></li>
                </ul>
            </div>
        <?php endif; ?>
<!--        catalog.product.related-->
        <?php echo $this->getChildHtml('catalog.product.related'); ?>
<!--        catalog.product.related end-->
        <div class="size-box-bundle" id="product-options">
            <?php if($_product->getTypeId() == Mage_Catalog_Model_Product_Type::TYPE_CONFIGURABLE) : ?>

                <?php if (!empty($productAttrs)) : ?>
                    <?php foreach($productAttrs as $_attribute) : ?>
                        <?php if(array_key_exists('attribute_code', $_attribute) && $_attribute['attribute_code'] == 'size') : ?>
				            <?php $haveSizes = true; ?>
                            <div class="size-box clearfix clr">
                                <div class="size col-sm-12 col-md-12 col-xs-12">
                                    <span class="size-label col-sm-6 col-md-6 col-xs-12"><?php echo $this->__("Select size"); ?></span>
                                    <div class=" sizes-content form-group form-radio col-sm-6 col-md-5 col-xs-4">
                                        <br />
                                        <a href="#" class="view-sizing underline pull-left" data-toggle="modal"
                                           data-target="#tabelaRozmiarow"><?php if (!empty($sizeTableValue)) : ?><?php echo $this->__("Sizes"); ?> <?php endif; ?></a>
                                    </div>
                                </div>
                            </div>
                        <?php endif; ?>
                    <?php endforeach; ?>
                <?php endif; ?>
            <?php endif; ?>

            <div class="row">
                <div class="action-box-bundle clearfix">
                    <div class="col-xs-6" id="product-likeboxes">

                    </div>
                    <?php if ($isSalable): ?>
                        <div class="col-xs-6 text-right">
                            <button class="btn button button-primary ico addBasket"
                                    <?php if(isset($haveSizes) && $haveSizes == true): ?><?php if ($salableCount > 1): ?>title="<?php echo $hlp->__("Choose size first"); ?>" data-toggle="tooltip" <?php endif; ?>data-placemen="top"<?php endif; ?>
                                    id="add-to-cart"
                                    onclick="Mall.addToCart(<?php echo $_product->getId(); ?>, <?php echo !$_product->getStockItem()->getMinSaleQty() ? 1 : $_product->getStockItem()->getMinSaleQty(); ?>);return false;"><?php echo $this->__("add to cart"); ?></button>
                        </div>
                    <?php else: ?>
                        <div class="col-xs-6 text-right">
                            <div class="temporary-absence-product-wrapper">
                                <span class="temporary-absence-product"><?php echo $hlp->__("temporary absence product");//?></span>
                            </div>
                        </div>
                    <?php endif; ?>
                </div>
            </div>
        </div>
    </form>
</div>
<?php /* configurable price/stock data */?>
<?php if($_product->getTypeId() == Mage_Catalog_Model_Product_Type::TYPE_CONFIGURABLE) : ?>
<script type="text/javascript">
    var jsonConfig = <?php echo Mage::getBlockSingleton('zolagocatalog/product_view_type_configurable')->getJsonConfig(); ?>;
    var useSizeboxList =  <?php echo Mage::getModel('eav/entity_attribute_set')->load($_product->getAttributeSetId())->getUseSizeboxList(); ?>;

    jsonConfig.useSizeboxList = useSizeboxList;

    Mall.product.productOptions(jsonConfig);
    Mall.product._current_product_type = "<?php echo Mage_Catalog_Model_Product_Type::TYPE_CONFIGURABLE; ?>";

</script>
<?php endif; ?>