<?php /* @var $this Zolago_Catalog_Block_Vendor_Price_Modal */ ?>
<?php $_product = $this->getProduct();?>
<?php $_helper = Mage::helper('core');?>
	<div class="row" style="margin-bottom: 30px">
		<div class="col-md-3 form-group">
			<span class="help-block"><?php echo $this->__("Source price");?></span>
			<select id="converter_price_type"  name="converter_price_type" type="text" class="form-control">
				<?php foreach ($this->getPriceSourceOptions() as $option):?>
				<?php $_selected = $option['value']==$_product->getData('converter_price_type');?>
				<option <?php if($_selected):?>selected="selected"<?php endif;?> value="<?php echo $this->escapeHtml($option['value']);?>"><?php echo $this->escapeHtml($option['label']);?></option>
				<?php endforeach;?>
			</select>
		</div>
		<div class="col-md-3 form-group">
			<span class="help-block"><?php echo $this->__("Margin");?></span>
			<input id="price_margin" value="<?php echo $_product->getPriceMargin();?>" name="price_margin"  type="text" class="percent form-control"/>
		</div>
		<div class="col-md-3 form-group">
			<span class="help-block"><?php echo $this->__("Regular price");?></span>
			<input id="price" name="price" value="<?php echo $_product->getPrice();?>" required="required" type="text" class="numeric form-control"/>
		</div>
		<div class="col-md-3 form-group">
			<span class="help-block"><?php echo $this->__("Msrp");?></span>
			<input id="msrp" name="msrp" value="<?php echo $_product->getMsrp();?>" type="text" class="numeric form-control"/>
		</div>
	</div>
	<?php /* Use child products */ ?>
	<?php if($_product->isComposite()):?>
	<div class="next-row">
		<table class="table table-condensed table-striped">
			
			<tbody>
			<?php foreach ($this->getChildren($_product) as $attribute):?>
				<tr>
					<th><?php echo $this->escapeHtml($attribute['label']);?></th>
					<th><?php echo $this->__("Effective price");?></th>
					<th><?php echo $this->__("Price deviation");?></th>
					<th><?php echo $this->__("Price A");?></th>
					<th><?php echo $this->__("Price B");?></th>
					<th><?php echo $this->__("Price C");?></th>
					<th><?php echo $this->__("Price Z");?></th>
					<th><?php echo $this->__("MSRP");?></th>
					<th><?php echo $this->__("MSRP-2");?></th>
				</tr>
				<?php foreach($attribute['children'] as $child):?>
				<tr>
					<td class="option-text"><?php echo $this->escapeHtml($child['option_text']);?></td>
					<td class="effective-price"></td>
					<td class="price-deviation"><input type="text" class="numeric form-control" value="<?php echo $this->escapeHtml($child['price']);?>"/></td>
					<td><?php echo Mage::helper('core')->formatPrice(0, false); ?></td>
					<td><?php echo Mage::helper('core')->formatPrice(0, false); ?></td>
					<td><?php echo Mage::helper('core')->formatPrice(0, false); ?></td>
					<td><?php echo Mage::helper('core')->formatPrice(0, false); ?></td>
					<td><?php echo Mage::helper('core')->formatPrice(0, false); ?></td>
					<td><?php echo Mage::helper('core')->formatPrice(0, false); ?></td>
				</tr>
				<?php endforeach;?>
			<?php endforeach;?>
			</tbody>
		</table>
	</div>
	<?php endif;?>
</ul>
