<?php
/** @var SalesManago_Tracking_Block_Layer $this */
$client_id = $this->getClientId();
$endpoint = $this->getEndPoint();
$additional_js = $this->getAdditionalJs();

if (!empty($client_id) && !empty($endpoint)): ?>
	<script type='text/javascript'>
		var _smid = '<?php echo $client_id; ?>';
		function initSalesManagoScript() {
			<?php echo $additional_js; ?>
			var sm = document.createElement('script');
			sm.type = 'text/javascript';
			sm.async = true;
			sm.src = ('https:' == document.location.protocol ? 'https://' : 'http://') + '<?php echo $endpoint; ?>/static/sm.js';
			var s = document.getElementsByTagName('script')[0];
			s.parentNode.insertBefore(sm, s);
		}
		jQuery(document).ready(function () {
			var smCookie = Mall.Cookie.get('smclient');
			if (smCookie) {
				initSalesManagoScript();
			} else {
				Mall.getSalesManagoInfo();
			}
		});
	</script>
<?php endif; ?>