<?php
/**
 * Author: Paweł Chyl <pawel.chyl@orba.pl>
 * Date: 02.05.14
 * @see Zolago_Modago_Block_Checkout_Cart
 */
?>

<ul class="dropdown-menu basket">
    <li>
        <table>
            <tbody>
            <tr>
                <td class="thumb">
                    <img src="<?php echo $this->getSkinUrl('images/product/thumb/img-thumb-product.png'); ?>"
                         alt="">
                </td>
                <td class="desc">
                    <p class="name_product">ZARA Krótki płaszcz z guzikami</p>

                    <p class="size">rozmiar:
                        <span>38</span>
                    </p>

                    <p class="quantity">ilość:
                        <span>1</span>
                    </p>
                </td>
                <td class="price">3 000,00 zł</td>
            </tr>
            <tr>
                <td class="thumb">
                    <img src="<?php echo $this->getSkinUrl('images/product/thumb/img-thumb-product.png'); ?>"
                         alt="">
                </td>
                <td class="desc">
                    <p class="name_product">ZARA Krótki płaszcz z guzikami</p>

                    <p class="size">rozmiar:
                        <span>38</span>
                    </p>

                    <p class="quantity">ilość:
                        <span>1</span>
                    </p>
                </td>
                <td class="price">3 000,00 zł</td>
            </tr>
            </tbody>
        </table>
        <div class="summary_basket">
            <ul>
                <li>Ilość produktów: 2</li>
                <li>Wartość produktów: 7600,00 zł</li>
                <li>Koszt dostawy: gratis</li>
            </ul>
            <a href="#" class="view_basket">Zobacz koszyk</a>
        </div>
    </li>
</ul>
