<?php
/**
 * Author: Paweł Chyl <pawel.chyl@orba.pl>
 * Date: 02.05.14
 * @see Zolago_Modago_Block_Checkout_Cart
 */
?>

<div id="dropdown-basket" class="dropdown dropdown-anchor-right basket basket-dropdown" style="display: none;">
    <div class="dropdown-panel">
        <div class="dropdown-panel-inner">
            <table>
                <tbody id="product-list">
                </tbody>
            </table>
            <div class="summary_basket">
                <ul>
                    <li>{{products_count_msg}}: {{all_products_count}}</li>
                    <li>{{products_worth_msg}}: {{total_amount}} {{currency_symbol}}</li>
                    <li>{{shipping_cost_msg}}: {{shipping_cost}}</li>
                </ul>
                <a href="{{show_cart_url}}" class="view_basket button button-primary medium link">{{see_your_cart_msg}}</a>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    Mall.i18nValidation.add("see_your_cart_msg","<?php echo $this->__("See your cart"); ?>");
    Mall.i18nValidation.add("products_count_msg","<?php echo $this->__("Products count"); ?>");
    Mall.i18nValidation.add("products_worth_msg","<?php echo $this->__("Products worth"); ?>");
    Mall.i18nValidation.add("shipping_cost_msg","<?php echo $this->__("Shipping cost"); ?>");
    Mall.i18nValidation.add("remove_my_data_from_this_device","<?php echo $this->__("Remove my data from device"); ?>");
</script>