<?php /* @var $this Mage_Checkout_Block_Cart_Sidebar */ ?>
<?php /* @var $this Zolago_Modago_Block_Checkout_Cart_Sidebar */ ?>
<?php
/**
 * Author: Paweł Chyl <pawel.chyl@orba.pl>
 * Date: 13.08.2014
 */
$checkoutSession = Mage::getSingleton('checkout/session');
$sessionShippingMethod = $checkoutSession->getData("shipping_method");

$inpostCode = $checkoutSession->getData("inpost_code");


$shippingBlock = $this->getChild('checkout_cart_shipping');
?>

<?php
    $_totals = $this->getQuote()->getData();
    $_totalWithShipment = isset($_totals['grand_total'])? $_totals['grand_total']:0; // $this->getQuote()->getGrandTotal()+ $this->getShippingTotal();
    $_hasCoupon = (bool) $this->getQuote()->getCouponCode();
    $_couponLabel = '';
    $_couponDescription = '';
    if($_hasCoupon) {
        $_salesRuleId = Mage::getModel('salesrule/coupon')->loadByCode($this->getQuote()->getCouponCode())->getRuleId();
        $_ruleModel = Mage::getModel('salesrule/rule')->load($_salesRuleId);
        $_couponLabel = $_ruleModel->getStoreLabel();
        $_couponDescription = $_ruleModel->getDescription();
    }
    
?>

<div id="sidebar-secondary" class="sidebar-second col-lg-3 col-md-4 ">
    <aside id="cart-summary" class="main bg-w clearfix">

        <div class="col-sidebar-cart-summary clearfix">
            <?php echo $this->getChildHtml('checkout_cart_shipping'); ?>
        </div>
        <!--Select Shipping-->


        
        
        <div class="col-sidebar-cart-summary clearfix">
            
            <div id="discount_voucher">
                <div class="form-group clearfix">
                    <?php if (!$_hasCoupon) : ?>
                    <a href="#" class="info_discount_voucher ff_os fz_11 underline"><?php echo $this->__("Do you have promo code?"); ?></a>
                    <?php endif; ?>
                    <div class="form_discount_voucher clearfix">
                        <input type="text" id="num_discount_voucher" name="num_discount_voucher" autocomplete="off" placeholder="<?php echo $this->__("Enter your coupon"); ?>" />
                        <a class="btn btn_black" id="applyCoupon-btn" href="#"><?php echo $this->__("Apply coupon"); ?></a>
                        <div class="coupon-errors"></div>
                    </div>
                </div>
                <dl class="coupon-list" id="cart_coupon" style="display: <?php if(!$_hasCoupon): ?>none;<?php endif; ?>">
                    <dt><?php echo $this->__("Your coupon:"); ?></dt>
                    <dd class="ff_os fz_12" <?php if($_hasCoupon && $_couponDescription): ?>data-toggle="tooltip" data-placement="bottom" title="<?php echo $_couponDescription; ?>" <?php endif; ?> style="height: auto; background: none;"><?php echo $_couponLabel; ?> <i class="fa-delete-coupon" onclick="Mall.Cart.removeCoupon();"></i></dd>
                </dl>

            </div>
            <div id="sum_price">
                <span class="val_value_sum_price"><?php echo $this->__("Total"); ?></span>
                <span class="value_sum_price"><?php echo Mage::helper('core')->currency($_totalWithShipment, true, false); ?></span>
            </div>
        </div>
        <div class="form-action">
            <button id="cart-buy" href="<?php echo $this->getCheckoutUrl(); ?>" class="button button-primary"><i></i>&nbsp;<?php echo $this->__("Checkout"); ?></button>
			<?php /* $_tosHtml = $this->getChildHtml("tos");?>
			<?php if($_tosHtml):?>
				<br><br>
				<?php echo $_tosHtml?>
			<?php endif; */?>
        </div>
        <!--</div>-->

        <div id="cart-buy-overlay" class="hidden"><i class="fa fa-spinner fa-spin"></i></div>
    </aside>
    <?php /* <aside id="payment-methods" class="main bg-w">
        <!--<div class="inner-payment-methods">-->
        <header>
            <h2><?php echo $this->__("Available payment methods:"); ?></h2>
        </header>
        <div class="payment-methods-list">
            <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('pl-cart-available-payment-methods-icons')->toHtml(); ?>
        </div>
        <div class="form-action">
            <a href="#" class="ff_os fz_11 simple" data-toggle="modal" data-target="#learn_more"><?php echo $this->__("Learn more"); ?></a>

            <!-- Modal -->
            <div class="modal fade learn_more" id="learn_more" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                <div class="modal-dialog modal-lg">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal"></button>
                            <h2 class="title_section"><?php echo $this->__("Learn more"); ?></h2>
                        </div>
                        <div class="modal-body">
                            <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('pl-cart-available-payment-methods-learn-more-popup')->toHtml(); ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!--</div>-->
    </aside>
	*/ ?>
</div>

<style type="text/css">
    #sidebar-secondary #cart-summary #discount_voucher .form-group a.btn_black {
        display: -moz-inline-stack;
        display: inline-block;
        vertical-align: middle;
        *vertical-align: auto;
        zoom: 1;
        *display: inline;
        background: #000;
        line-height: 22px;
        height: 22px;
        width: 72px;
        border: none;
        color: #fff;
        font-size: 12px;
        text-align: center;
        text-transform: uppercase;
        float: left;
    }
    #cart-buy-overlay{
        position:absolute;
        top:0px;
        left:0px;
        bottom:0px;
        right:0px;
        background-color: #fff;
        opacity: 0.5;
        padding-top: 55%;
        font-size: 40px;
        text-align: center;
    }
</style>

<script type="text/javascript">
    Mall.translate.add("coupon_code_invalid", "<?php echo $this->__("Coupon code is invalid."); ?>");
    jQuery(".ff_os").tooltip();
    jQuery('#applyCoupon-btn').click(function (e) {
        e.preventDefault();
        Mall.Cart.applyCoupon();
    })
    jQuery('[name=num_discount_voucher]').on("keydown", function (e) {
        var code = e.keyCode || e.which;
        if (code == 13) {
            e.preventDefault();
            Mall.Cart.applyCoupon();

        }
    });
</script>