<div class="container-fluid-wide">
    <div class="col-sm-12 col-featured-products">
        <div class="row">
            <section class="block-featured-products clearfix">
                <header class="title-section">
                    <div><hr class="divider short"></div>
                    <h2><?php echo Mage::helper("wfwf")->__("Featured products"); ?></h2>
                </header>
                <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('wf_featured_products')->toHtml(); ?>
            </section>
        </div>
    </div>
</div>