<?php
/** @var GH_AttributeRules_Block_Attribute $this */

/** @var GH_AttributeRules_Helper_Data $helper */
$helper = Mage::helper("gh_attributerules");

/** @var Zolago_Common_Helper_Data $_zolagoHlp */
$_modagoHlp = Mage::helper("zolagocommon");
?>
<div class="modal fade bs-example-modal-sm" id="showAttributeRules" role="dialog">
    <form method="post">
        <div class="modal-dialog modal-sm">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title"><?php echo $helper->__("Manage attributes rules"); ?></h4>
                </div>
                <div class="modal-body">
                    body
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal"><?php echo $helper->__("Cancel"); ?></button>
                    <button type="submit" class="btn btn-primary" data-loading-text="<?php echo $_modagoHlp->__("Processing...");?>"><?php echo $helper->__('Action'); ?></button>
                </div>
            </div>
        </div>
    </form>
</div>