<?php
/** @var GH_AttributeRules_Block_Attribute $this */

/** @var GH_AttributeRules_Helper_Data $helper */
$helper = Mage::helper("gh_attributerules");
$storeId = $this->getLabelStore();
/** @var Zolago_Common_Helper_Data $_zolagoHlp */
$_modagoHlp = Mage::helper("zolagocommon");
?>

<style>
    #showAttributeRules .hiddenRow.in {
        display: table-cell !important
    }
    #showAttributeRules table.table {
        margin-bottom: 0 !important;
    }
    #showAttributeRules .checkbox-column {
        width: 3%;
    }
    #showAttributeRules .show-details-column-short {
        width: 4% !important;
    }
    #showAttributeRules .show-details-column {
        width: 10%;
    }
    .accordion-toggle {
        cursor: pointer;
    }
    .prefix-lvl-1 {
        border: none;
        width: 13%;
    }
    .prefix-lvl-2 {
        border: none;
        width: 16%;
    }
    .table-lvl-1 tr:first-child > td {
        border-top: none;
    }
    #showAttributeRules .collapsing {
        -webkit-transition: 0.01s;
        transition: 0.01s;
    }
</style>

<div class="modal fade bs-example-modal-sm" id="showAttributeRules" role="dialog">
    <form method="post" action="<?php echo $this->getActionUrl();?>">
        <div class="modal-dialog modal-sm" style="width: 80%;">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title"><?php echo $helper->__("Manage attributes rules"); ?></h4>
                </div>
                <div class="modal-body">
                    <p class="alert alert-info">
                        <strong><?php echo $helper->__("Information");?>:</strong>
                        <?php echo $helper->__("Some text here");?>
                    </p>
                    <div class="widget-content">
                        <table
                            class="table-lvl-0 table table-bordered table-checkable table-no-inner-border table-hover">
                            <thead>
                            <tr>
                                <th class="checkbox-column" style="width: 3%;"></th>
                                <th class="align-center show-details-column"><?php echo $helper->__("Show details"); ?></th>
                                <th><?php echo $helper->__("Attribute"); ?></th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php
                            foreach ($this->getRulesData() as $key => $row): ?>
                            <tr class="">
                                <td class="checkbox-column">
                                    <div class="">
                                        <span class="">
                                            <input type="checkbox"
                                                   name="attribute[]"
                                                   id="attr-<?php echo $key; ?>"
                                                   value="<?php echo $key;?>"
                                                   data-checkbox-group-target="input[type=checkbox][data-checkbox-group=value-key-<?php echo $key; ?>]"
                                                   class="uniform">
                                        </span>
                                    </div>
                                </td>
                                <td class="show-details-column align-center accordion-toggle" data-toggle="collapse" data-target="#row-<?php echo $key; ?>">
                                    <span class="btn btn-xs"><i class="icon-plus"></i></span>
                                </td>
                                <td class="attribute-column accordion-toggle" data-toggle="collapse" data-target="#row-<?php echo $key; ?>">
                                    <?php
                                    /** @var Mage_Catalog_Model_Resource_Eav_Attribute $attr */
                                    $attr = $row['attribute'];
                                    echo $attr->getStoreLabel($storeId);
                                    ?>
                                </td>
                            </tr>
                            <!-- hidden table row for Value -->
                            <tr>
                                <td colspan="3" style="padding: 0;" id="row-<?php echo $key; ?>" class="body-lvl-1 accordian-body collapse hiddenRow">
                                    <div>
                                        <table class="table-lvl-1 table table-no-inner-border table-checkable table-no-inner-border table-hover">
                                            <tbody>
                                            <?php foreach ($row['value'] as $valueKey => $rulesGroup): // Rule grouped by value ?>
                                                <tr>
                                                    <td class="prefix-lvl-1"></td>
                                                    <td class="checkbox-column">
                                                        <div class="">
                                                            <span class="">
                                                                <input type="checkbox"
                                                                       name="value_key[]"
                                                                       id="value-key-<?php echo $valueKey; ?>"
                                                                       value="<?php echo $valueKey; ?>"
                                                                       data-checkbox-group="value-key-<?php echo $key; ?>"
                                                                       data-checkbox-group-parent="#attr-<?php echo $key; ?>"
                                                                       data-checkbox-group-target="input[type=checkbox][data-checkbox-group-id=rules-group-<?php echo $valueKey; ?>]"
                                                                       class="uniform">
                                                            </span>
                                                        </div>
                                                    </td>
                                                    <td class="show-details-column-short align-center accordion-toggle" data-toggle="collapse" data-target="#rulesGroup-<?php echo $valueKey; ?>" style="cursor: pointer;">
                                                        <span class="btn btn-xs"><i class="icon-plus"></i></span>
                                                    </td>
                                                    <td>
                                                        <?php echo$helper->__("Set value: <b>%s</b>", $attr->getSource()->getOptionText($valueKey)); ?>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td colspan="4" style="padding: 0;" id="rulesGroup-<?php echo $valueKey; ?>" class="body-lvl-2 accordian-body collapse hiddenRow">
                                                        <div>
                                                        <table class="table-lvl-2 table table-no-inner-border table-checkable table-no-inner-border table-hover">
                                                        <tbody>
                                                        <!-- hidden table row for filters -->
                                                        <?php /** @var GH_AttributeRules_Model_AttributeRule $rule */
                                                        foreach ($rulesGroup as $rule): ?>
                                                            <tr>
                                                                <td class="prefix-lvl-2"></td>
                                                                <td class="checkbox-column show-details-column-short">
                                                                    <div class="">
                                                                        <span class="">
                                                                            <input type="checkbox"
                                                                                   name="rule[]"
                                                                                   value="<?php echo $rule->getId(); ?>"
                                                                                   data-checkbox-group-id="rules-group-<?php echo $valueKey; ?>"
                                                                                   data-checkbox-group-parent="#value-key-<?php echo $valueKey; ?>"
                                                                                   class="uniform">
                                                                        </span>
                                                                    </div>
                                                                </td>
                                                                <td colspan="4"><?php echo $helper->__("Filters: ") ?><b><?php echo $this->getFilterAsText($rule); ?></b></td>
                                                            </tr>
                                                        <?php endforeach; ?>
                                                        </tbody>
                                                        </table>
                                                        </div>
                                                    </td>
                                                </tr>
                                            <?php endforeach; ?>
                                            </tbody>
                                        </table>
                                    </div>
                                </td>
                            </tr>

                            <?php endforeach; ?>
                            </tbody>
                        </table>
                    </div>


                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal"><?php echo $helper->__("Cancel"); ?></button>
                    <button type="submit" class="btn btn-primary" disabled="disabled" data-loading-text="<?php echo $_modagoHlp->__("Processing...");?>"><?php echo $helper->__('Action'); ?></button>
                </div>
            </div>
        </div>
    </form>
</div>

