<?php
/** @var GH_AttributeRules_Block_Attribute $this */

/** @var GH_AttributeRules_Helper_Data $helper */
$helper = Mage::helper("gh_attributerules");

/** @var Zolago_Common_Helper_Data $_zolagoHlp */
$_modagoHlp = Mage::helper("zolagocommon");
?>
<div class="modal fade bs-example-modal-sm" id="showAttributeRules" role="dialog">
    <form method="post" action="<?php echo $this->getActionUrl();?>">
        <div class="modal-dialog modal-sm" style="width: 80%;">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title"><?php echo $helper->__("Manage attributes rules"); ?></h4>
                </div>
                <div class="modal-body">
                    <p class="alert alert-info">
                        <strong><?php echo $helper->__("Information");?>:</strong>
                        <?php echo $helper->__("Some text here");?>
                    </p>

                    <?php
                    /** @var GH_AttributeRules_Model_AttributeRule $rule */
                    foreach ($this->getRules() as $rule) {
//                        $data = $rule->getData();
//                        var_dump($data);
//                        var_dump(unserialize($data['filter']));
//                        echo ' </br>';
                    }
                    ?>

                    <div class="widget-content">
                        <table
                            class="table table-striped table-bordered table-checkable table-highlight-head table-no-inner-border table-hover">
                            <thead>
                            <tr>
                                <th class="checkbox-column"></th>
                                <th><?php echo $helper->__("Attribute"); ?></th>
                                <th class="align-center"><?php echo $helper->__("Value"); ?></th>
                                <th class="align-center"><?php echo $helper->__("Filters"); ?></th>
                                <th class="align-center"><?php echo $helper->__("Delete"); ?></th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php
                            /** @var GH_AttributeRules_Model_AttributeRule $rule */
                            foreach ($this->getRules() as $rule) { ?>
                            <tr class="">
                                <td class="checkbox-column">
                                    <div class="checker"><span class=""><input type="checkbox" class="uniform"></span>
                                    </div>
                                </td>
                                <td class="attribute-column">
                                    <?php echo $rule->getAttribute()->getName(); ?>
                                </td>
                                <td class="value-column">
                                    value
                                </td>
                                <td class="filter-column">
                                    value
                                </td>
                                <td class="align-center delete-column"><span class="label label-warning">X</span></td>
                            </tr>
                            <?php
                            }
                            ?>
                            </tbody>
                        </table>
                    </div>


                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal"><?php echo $helper->__("Cancel"); ?></button>
                    <button type="submit" class="btn btn-primary" data-loading-text="<?php echo $_modagoHlp->__("Processing...");?>"><?php echo $helper->__('Action'); ?></button>
                </div>
            </div>
        </div>
    </form>
</div>