<?php /* @var $this Zolago_Catalog_Block_Vendor_Product_ChangeAttributeSet */ ?>

<?php
$_helper = Mage::helper("zolagocatalog");
?>


<div class="modal fade" id="massChangeAttributeSet" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title"><?php echo $_helper->__("Change Attribute Set"); ?></h4>
            </div>
            <div class="modal-body">
                <p class="alert alert-info">
                    <strong><?php echo $_helper->__("Information"); ?>:</strong>
                    <?php echo $_helper->__("Bla bla bla ..."); ?>
                </p>

                <p>Some text in the modal.</p>
            </div>
            <div class="modal-footer">

                <button type="button" class="btn btn-default" data-dismiss="modal">
                    <?php echo $_helper->__("Cancel"); ?>
                </button>
            </div>
        </div>

    </div>
</div>