<div class="modal fade" id="filtersModal" tabindex="-1" role="dialog"
	 aria-labelledby="mySmallModalLabel" aria-hidden="true">
	<form method="post" id="static-filters">
		<div class="modal-dialog modal-sm" style="width: 80%;">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
					<h4 class="modal-title" id="myModalLabel"><?php echo $this->__('Additional filters'); ?></h4>
				</div>
				<div class="modal-body">
					<div class="form-group">
						<div class="col-md-4">
							<?php echo $this->getChildHtml("other_filter"); ?>
						</div>
						<div class="col-md-8">
							<?php echo $this->getChildHtml("additional_filter"); ?>
						</div>
					</div>
					<div class="clearfix"></div>
					<?php echo $this->getChildHtml("static_filter"); ?>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-default" data-dismiss="modal"><?php echo $this->__('Cancel'); ?></button>
					<button type="submit" class="btn btn-primary" ><?php echo $this->__('Filter'); ?></button>
				</div>
			</div>
		</div>
	</form>
</div>
<script type="text/javascript">
	jQuery(function($){
		$("#static-filters").submit(function(){
			window.grid.refresh();
			$("#filtersModal").modal("hide");
			return false;
		})
	});
</script>