<?php
/**
 * Author: Paweł Chyl <pawel.chyl@orba.pl>
 * Date: 09.07.2014
 */
/** @var $this Zolago_Modago_Block_Catalog_Category */

$mainCategories = $this->getMainCategories();
?>

<?php if (count($mainCategories) > 0) : ?>
    <?php foreach ($mainCategories as $catFirstLevel) : ?>
        <li class="">
            <a href="<?php echo $cat['has_dropdown'] ? '#' : $catFirstLevel['url']; ?>"
               class="<?php echo $catFirstLevel['has_dropdown'] ? 'children' : '' ?>">
                <?php echo $this->escapeHtml($catFirstLevel['name']); ?> <?php echo $catFirstLevel['has_dropdown']
                    ? '<i class="fa fa-caret-down"></i>' : ''; ?></a>
            <?php if ($catFirstLevel['has_dropdown']): ?>
                <ul>
                    <li>
                        <div class="row clearfix">
                            <div class="col-left">
                                <div class="jsMasonry">
                                    <?php foreach ($catFirstLevel['has_dropdown'] as $catSecondLevel): ?>
                                        <div class="box col-sm-2 col-xs-6">
                                            <dl>
                                                <dt>
                                                    <a rel="category" data-description="<?php echo $catSecondLevel['name']; ?>" href="<?php echo $catSecondLevel['url']; ?>">
                                                        <?php echo $catSecondLevel['name']; ?>
                                                    </a>
                                                </dt>
                                                <?php if ($catSecondLevel['has_dropdown']): ?>
                                                    <?php foreach ($catSecondLevel['has_dropdown'] as $catThirdLevel): ?>
                                                        <dd><a rel="category" data-description="<?php echo $catThirdLevel['name']; ?>" href="<?php echo $catThirdLevel['url']; ?>"><?php echo $catThirdLevel['name']; ?></a></dd>
                                                    <?php endforeach; ?>
                                                    <dd><a data-description="ReadMore" href="#">Czytaj więcej <i class="fa fa-angle-right"></i></a></dd>
                                                <?php endif; ?>
                                            </dl>
                                        </div>
                                    <?php endforeach; ?>
                                </div>
                                <a href="<?php echo $catFirstLevel['url']; ?>" class="view-all-category">zobacz
                                    wszystkie kategorie <i class="fa fa-angle-right"></i></a>
                            </div>
                            <?php if ($catFirstLevel['image']): ?>
                                <div class="col-right hidden-xs">
                                    <figure>
                                        <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) ."/catalog/category/". $catFirstLevel['image']; ?>" alt="<?php echo $catFirstLevel['name']; ?>"  class="img-responsive">
                                    </figure>
                                </div>
                            <?php endif; ?>

                        </div>
                        <div class="row">
                            <a href="" class="closeSubMenu">ZWIŃ</i></a>
                        </div>
                        <!-- end row -->
                    </li>
                    <!-- end grid demo -->
                </ul>
                <!-- end drop down menu -->
            <?php endif; ?>
        </li>
    <?php endforeach; ?>
<?php endif; ?>