
<div class="header_bottom cdmm">
<div class="container_1176">
<nav class="navbar navbar-default" role="navigation">
<div class="container-fluid">
<div class="row">
<!-- Brand and toggle get grouped for better mobile display -->


<!-- Collect the nav links, forms, and other content for toggling -->
<div class="collapse navbar-collapse" id="navigation">
<ul id="nav_desc" class="nav hidden-xs" role="navigation">
<li class="dropdown cdmm-fw">
<a href="#" data-toggle="dropdown" class="dropdown-toggle">Ona <b class="caret"></b></a>

<ul class="dropdown-menu fullwidth">
    <li class="cdmm-content withoutdesc">
        <div class="row">
            <div class="col-sm-9 col-xs-12">
                <div class="jsMasonry">

                    <div class="box col-sm-2 col-xs-6">

                        <dl>
                            <dt><a rel="category" data-description="Kategory" href="#ona">Ona</a>
                            </dt>
                            <dd><a data-description="Bluzy" href="#">Bluzy</a>
                            </dd>
                            <dd><a data-description="Jeans" href="#">Jeans</a>
                            </dd>
                            <dd><a data-description="Koszule" href="#">Koszule</a>
                            </dd>
                            <dd><a data-description="Spodnie" href="#">Spodnie</a>
                            </dd>
                            <dd><a data-description="Spodnie" href="#">Spodnie</a>
                            </dd>
                            <dd><a data-description="Rajstopy" href="#">Rajstopy</a>
                            </dd>
                            <dd><a data-description="ReadMore" href="#">Czytaj więcej</a>
                            </dd>
                        </dl>
                    </div>
                    <div class="box col-sm-2 col-xs-6">
                        <dl>
                            <dt><a rel="category" data-description="Kategory" href="#">Odzież</a>
                            </dt>
                            <dd><a data-description="Bluzy" href="#">Bluzy</a>
                            </dd>
                            <dd><a data-description="Jeans" href="#">Jeans</a>
                            </dd>
                            <dd><a data-description="Koszule" href="#">Koszule</a>
                            </dd>

                            <dd><a data-description="ReadMore" href="#">Czytaj więcej</a>
                            </dd>
                        </dl>
                    </div>
                    <div class="box col-sm-2 col-xs-6">
                        <dl>
                            <dt><a rel="category" data-description="Kategory" href="#">Odzież</a>
                            </dt>
                            <dd><a data-description="Bluzy" href="#">Bluzy</a>
                            </dd>
                            <dd><a data-description="Jeans" href="#">Jeans</a>
                            </dd>
                            <dd><a data-description="Koszule" href="#">Koszule</a>
                            </dd>
                            <dd><a data-description="Spodnie" href="#">Spodnie</a>
                            </dd>
                            <dd><a data-description="Spodnie" href="#">Spodnie</a>
                            </dd>
                            <dd><a data-description="Rajstopy" href="#">Rajstopy</a>
                            </dd>
                            <dd><a data-description="ReadMore" href="#">Czytaj więcej</a>
                            </dd>
                        </dl>
                    </div>
                    <div class="box col-sm-2 col-xs-6">
                        <dl>
                            <dt><a rel="category" data-description="Kategory" href="#">Odzież</a>
                            </dt>
                            <dd><a data-description="Bluzy" href="#">Bluzy</a>
                            </dd>
                            <dd><a data-description="Jeans" href="#">Jeans</a>
                            </dd>
                            <dd><a data-description="Koszule" href="#">Koszule</a>
                            </dd>
                            <dd><a data-description="Spodnie" href="#">Spodnie</a>
                            </dd>
                            <dd><a data-description="Spodnie" href="#">Spodnie</a>
                            </dd>
                            <dd><a data-description="Rajstopy" href="#">Rajstopy</a>
                            </dd>
                            <dd><a data-description="ReadMore" href="#">Czytaj więcej</a>
                            </dd>
                        </dl>
                    </div>
                    <div class="box col-sm-2 col-xs-6">
                        <dl>
                            <dt><a rel="category" data-description="Kategory" href="#">Odzież</a>
                            </dt>
                            <dd><a data-description="Bluzy" href="#">Bluzy</a>
                            </dd>
                            <dd><a data-description="Jeans" href="#">Jeans</a>
                            </dd>
                            <dd><a data-description="Rajstopy" href="#">Rajstopy</a>
                            </dd>
                            <dd><a data-description="ReadMore" href="#">Czytaj więcej</a>
                            </dd>
                        </dl>
                    </div>
                    <div class="box col-sm-2 col-xs-6">
                        <dl>
                            <dt><a rel="category" data-description="Kategory" href="#">Odzież</a>
                            </dt>
                            <dd><a data-description="Bluzy" href="#">Bluzy</a>
                            </dd>
                            <dd><a data-description="Jeans" href="#">Jeans</a>
                            </dd>
                            <dd><a data-description="Koszule" href="#">Koszule</a>
                            </dd>
                            <dd><a data-description="Spodnie" href="#">Spodnie</a>
                            </dd>
                            <dd><a data-description="Spodnie" href="#">Spodnie</a>
                            </dd>
                            <dd><a data-description="Rajstopy" href="#">Rajstopy</a>
                            </dd>
                            <dd><a data-description="ReadMore" href="#">Czytaj więcej</a>
                            </dd>
                        </dl>
                    </div>
                    <div class="box col-sm-2 col-xs-6">
                        <dl>
                            <dt><a rel="category" data-description="Kategory" href="#">Odzież</a>
                            </dt>
                            <dd><a data-description="Bluzy" href="#">Bluzy</a>
                            </dd>
                            <dd><a data-description="Jeans" href="#">Jeans</a>
                            </dd>
                            <dd><a data-description="Koszule" href="#">Koszule</a>
                            </dd>

                            <dd><a data-description="ReadMore" href="#">Czytaj więcej</a>
                            </dd>
                        </dl>
                    </div>
                    <div class="box col-sm-2 col-xs-6">
                        <dl>
                            <dt><a rel="category" data-description="Kategory" href="#">Odzież</a>
                            </dt>
                            <dd><a data-description="Bluzy" href="#">Bluzy</a>
                            </dd>
                            <dd><a data-description="Jeans" href="#">Jeans</a>
                            </dd>
                            <dd><a data-description="Koszule" href="#">Koszule</a>
                            </dd>
                            <dd><a data-description="Spodnie" href="#">Spodnie</a>
                            </dd>
                            <dd><a data-description="Spodnie" href="#">Spodnie</a>
                            </dd>
                            <dd><a data-description="Rajstopy" href="#">Rajstopy</a>
                            </dd>
                            <dd><a data-description="ReadMore" href="#">Czytaj więcej</a>
                            </dd>
                        </dl>
                    </div>
                    <div class="box col-sm-2 col-xs-6">
                        <dl>
                            <dt><a rel="category" data-description="Kategory" href="#">Odzież</a>
                            </dt>
                            <dd><a data-description="Bluzy" href="#">Bluzy</a>
                            </dd>
                            <dd><a data-description="Jeans" href="#">Jeans</a>
                            </dd>
                            <dd><a data-description="Koszule" href="#">Koszule</a>
                            </dd>
                            <dd><a data-description="Spodnie" href="#">Spodnie</a>
                            </dd>
                            <dd><a data-description="Spodnie" href="#">Spodnie</a>
                            </dd>
                            <dd><a data-description="Rajstopy" href="#">Rajstopy</a>
                            </dd>
                            <dd><a data-description="ReadMore" href="#">Czytaj więcej</a>
                            </dd>
                        </dl>


                    </div>
                    <div class="box col-sm-2 col-xs-6">
                        <dl>
                            <dt><a rel="category" data-description="Kategory" href="#">Odzież</a>
                            </dt>
                            <dd><a data-description="Bluzy" href="#">Bluzy</a>
                            </dd>
                            <dd><a data-description="Jeans" href="#">Jeans</a>
                            </dd>
                            <dd><a data-description="Rajstopy" href="#">Rajstopy</a>
                            </dd>
                            <dd><a data-description="ReadMore" href="#">Czytaj więcej</a>
                            </dd>
                        </dl>
                    </div>
                </div>
            </div>

            <div class="col-sm-3 hidden-xs">
                <a href="#" class="closeSubMenu"><img src="<?php echo $this->getSkinUrl('images/btn-close.png'); ?>" alt=""></a>
                <figure>
                    <img src="<?php echo $this->getSkinUrl('images/hilfinger.jpg'); ?>" alt="" class="img-responsive">
                </figure>
            </div>
        </div>
        <!-- end row -->
    </li>
    <!-- end grid demo -->
</ul>
<!-- end drop down menu -->
</li>
<li class="dropdown cdmm-fw">
<a href="#" class="dropdown-toggle" data-toggle="dropdown">On <b class="caret"></b></a>
<ul class="dropdown-menu fullwidth">
    <li class="cdmm-content withoutdesc">
        <div class="row">
            <div class="col-sm-9 col-xs-12">
                <div class="jsMasonry">

                    <div class="box col-sm-2 col-xs-6">

                        <dl>
                            <dt><a rel="category" data-description="Kategory" href="#ona">Ona</a>
                            </dt>
                            <dd><a data-description="Bluzy" href="#">Bluzy</a>
                            </dd>
                            <dd><a data-description="Jeans" href="#">Jeans</a>
                            </dd>
                            <dd><a data-description="Koszule" href="#">Koszule</a>
                            </dd>
                            <dd><a data-description="Spodnie" href="#">Spodnie</a>
                            </dd>
                            <dd><a data-description="Spodnie" href="#">Spodnie</a>
                            </dd>
                            <dd><a data-description="Rajstopy" href="#">Rajstopy</a>
                            </dd>
                            <dd><a data-description="ReadMore" href="#">Czytaj więcej</a>
                            </dd>
                        </dl>
                    </div>
                    <div class="box col-sm-2 col-xs-6">
                        <dl>
                            <dt><a rel="category" data-description="Kategory" href="#">Odzież</a>
                            </dt>
                            <dd><a data-description="Bluzy" href="#">Bluzy</a>
                            </dd>
                            <dd><a data-description="Jeans" href="#">Jeans</a>
                            </dd>
                            <dd><a data-description="Koszule" href="#">Koszule</a>
                            </dd>

                            <dd><a data-description="ReadMore" href="#">Czytaj więcej</a>
                            </dd>
                        </dl>
                    </div>
                    <div class="box col-sm-2 col-xs-6">
                        <dl>
                            <dt><a rel="category" data-description="Kategory" href="#">Odzież</a>
                            </dt>
                            <dd><a data-description="Bluzy" href="#">Bluzy</a>
                            </dd>
                            <dd><a data-description="Jeans" href="#">Jeans</a>
                            </dd>
                            <dd><a data-description="Koszule" href="#">Koszule</a>
                            </dd>
                            <dd><a data-description="Spodnie" href="#">Spodnie</a>
                            </dd>
                            <dd><a data-description="Spodnie" href="#">Spodnie</a>
                            </dd>
                            <dd><a data-description="Rajstopy" href="#">Rajstopy</a>
                            </dd>
                            <dd><a data-description="ReadMore" href="#">Czytaj więcej</a>
                            </dd>
                        </dl>
                    </div>
                    <div class="box col-sm-2 col-xs-6">
                        <dl>
                            <dt><a rel="category" data-description="Kategory" href="#">Odzież</a>
                            </dt>
                            <dd><a data-description="Bluzy" href="#">Bluzy</a>
                            </dd>
                            <dd><a data-description="Jeans" href="#">Jeans</a>
                            </dd>
                            <dd><a data-description="Koszule" href="#">Koszule</a>
                            </dd>
                            <dd><a data-description="Spodnie" href="#">Spodnie</a>
                            </dd>
                            <dd><a data-description="Spodnie" href="#">Spodnie</a>
                            </dd>
                            <dd><a data-description="Rajstopy" href="#">Rajstopy</a>
                            </dd>
                            <dd><a data-description="ReadMore" href="#">Czytaj więcej</a>
                            </dd>
                        </dl>
                    </div>
                    <div class="box col-sm-2 col-xs-6">
                        <dl>
                            <dt><a rel="category" data-description="Kategory" href="#">Odzież</a>
                            </dt>
                            <dd><a data-description="Bluzy" href="#">Bluzy</a>
                            </dd>
                            <dd><a data-description="Jeans" href="#">Jeans</a>
                            </dd>
                            <dd><a data-description="Rajstopy" href="#">Rajstopy</a>
                            </dd>
                            <dd><a data-description="ReadMore" href="#">Czytaj więcej</a>
                            </dd>
                        </dl>
                    </div>
                    <div class="box col-sm-2 col-xs-6">
                        <dl>
                            <dt><a rel="category" data-description="Kategory" href="#">Odzież</a>
                            </dt>
                            <dd><a data-description="Bluzy" href="#">Bluzy</a>
                            </dd>
                            <dd><a data-description="Jeans" href="#">Jeans</a>
                            </dd>
                            <dd><a data-description="Koszule" href="#">Koszule</a>
                            </dd>
                            <dd><a data-description="Spodnie" href="#">Spodnie</a>
                            </dd>
                            <dd><a data-description="Spodnie" href="#">Spodnie</a>
                            </dd>
                            <dd><a data-description="Rajstopy" href="#">Rajstopy</a>
                            </dd>
                            <dd><a data-description="ReadMore" href="#">Czytaj więcej</a>
                            </dd>
                        </dl>
                    </div>
                    <div class="box col-sm-2 col-xs-6">
                        <dl>
                            <dt><a rel="category" data-description="Kategory" href="#">Odzież</a>
                            </dt>
                            <dd><a data-description="Bluzy" href="#">Bluzy</a>
                            </dd>
                            <dd><a data-description="Jeans" href="#">Jeans</a>
                            </dd>
                            <dd><a data-description="Koszule" href="#">Koszule</a>
                            </dd>

                            <dd><a data-description="ReadMore" href="#">Czytaj więcej</a>
                            </dd>
                        </dl>
                    </div>
                    <div class="box col-sm-2 col-xs-6">
                        <dl>
                            <dt><a rel="category" data-description="Kategory" href="#">Odzież</a>
                            </dt>
                            <dd><a data-description="Bluzy" href="#">Bluzy</a>
                            </dd>
                            <dd><a data-description="Jeans" href="#">Jeans</a>
                            </dd>
                            <dd><a data-description="Koszule" href="#">Koszule</a>
                            </dd>
                            <dd><a data-description="Spodnie" href="#">Spodnie</a>
                            </dd>
                            <dd><a data-description="Spodnie" href="#">Spodnie</a>
                            </dd>
                            <dd><a data-description="Rajstopy" href="#">Rajstopy</a>
                            </dd>
                            <dd><a data-description="ReadMore" href="#">Czytaj więcej</a>
                            </dd>
                        </dl>
                    </div>
                    <div class="box col-sm-2 col-xs-6">
                        <dl>
                            <dt><a rel="category" data-description="Kategory" href="#">Odzież</a>
                            </dt>
                            <dd><a data-description="Bluzy" href="#">Bluzy</a>
                            </dd>
                            <dd><a data-description="Jeans" href="#">Jeans</a>
                            </dd>
                            <dd><a data-description="Koszule" href="#">Koszule</a>
                            </dd>
                            <dd><a data-description="Spodnie" href="#">Spodnie</a>
                            </dd>
                            <dd><a data-description="Spodnie" href="#">Spodnie</a>
                            </dd>
                            <dd><a data-description="Rajstopy" href="#">Rajstopy</a>
                            </dd>
                            <dd><a data-description="ReadMore" href="#">Czytaj więcej</a>
                            </dd>
                        </dl>


                    </div>
                    <div class="box col-sm-2 col-xs-6">
                        <dl>
                            <dt><a rel="category" data-description="Kategory" href="#">Odzież</a>
                            </dt>
                            <dd><a data-description="Bluzy" href="#">Bluzy</a>
                            </dd>
                            <dd><a data-description="Jeans" href="#">Jeans</a>
                            </dd>
                            <dd><a data-description="Rajstopy" href="#">Rajstopy</a>
                            </dd>
                            <dd><a data-description="ReadMore" href="#">Czytaj więcej</a>
                            </dd>
                        </dl>
                    </div>
                </div>
            </div>

            <div class="col-sm-3 hidden-xs">
                <a href="#" class="closeSubMenu"><img src="<?php echo $this->getSkinUrl('images/btn-close.png'); ?>" alt=""></a>
                <figure>
                    <img src="<?php echo $this->getSkinUrl('images/hilfinger.jpg'); ?>" alt="" class="img-responsive">
                </figure>
            </div>
        </div>
        <!-- end row -->
    </li>
</ul>
<!-- end dropdown-menu -->
</li>
<li><a href="#">Dziecko</a>
</li>
<li><a href="#">Wybierz sklep</a>
</li>
<li><a href="#">Outlet</a>
</li>
<li><a href="#">W twoim stylu</a>
</li>
</ul>
<ul id="nav_mobile" class="nav visible-xs" role="navigation">
    <li><a href="#">Ona <span class="ico-submenu-mobile-right"></span></a>
        <ul>
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li class="divider"></li>
            <li><a href="#">One more separated link</a></li>
        </ul>
    </li>
    <li><a href="#">On</a></li>
    <li><a href="#">Dziecko</a></li>
    <li><a href="#">Wybierz sklep</a></li>
    <li><a href="#">Outlet</a></li>
    <li><a href="">W twoim stylu</a></li>
</ul>
</div>
<!-- /.navbar-collapse -->
</div>
<!-- /.container-fluid -->
</div>
</nav>
</div>

</div>
<div id="clone_submenu" class="hidden-xs">
    <div class="container">

    </div>
</div>
