<?php
/**
 * Author: Paweł Chyl <pawel.chyl@orba.pl>
 * Date: 09.07.2014
 */
/** @var $this Zolago_Modago_Block_Catalog_Category */

$mainCategories = $this->getMainCategories();
?>

<?php if(count($mainCategories) > 0) : ?>
    <?php foreach($mainCategories as $cat) : ?>
        <li class="navigation-main-item">
            <a href="<?php echo $cat['has_dropdown'] ? '#' : $cat['url']; ?>" class="<?php echo $cat['has_dropdown'] ? 'children' : '' ?>"><?php echo $this->escapeHtml($cat['name']); ?> <?php echo $cat['has_dropdown'] ? '<i class="fa fa-caret-down"></i>' : ''; ?></a>
            <?php if($cat['has_dropdown']): ?>
                <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('navigation-dropdown-c-' . $cat['category_id'])->toHtml(); ?>
                <!-- end drop down menu -->
            <?php endif; ?>
        </li>
    <?php endforeach; ?>

<?php endif; ?>