<div class="header_bottom">
<div class="container-fluid">
<nav role="navigation">


<div id="navigation">
<ul id="nav_desc" class="navigation hidden-xs" role="navigation">
<li class="">
<a href="#" class="children">Ona <i class="fa fa-caret-down"></i></a>

<ul>
<li>
<div class="row clearfix">
    <div class="col-left">
        <div class="jsMasonry">

            <div class="box col-sm-2 col-xs-6">

                <dl>
                    <dt><a rel="category" data-description="Kategory" href="#ona">Ona</a>
                    </dt>
                    <dd><a data-description="Bluzy" href="#">Bluzy</a>
                    </dd>
                    <dd><a data-description="Jeans" href="#">Jeans</a>
                    </dd>
                    <dd><a data-description="Koszule" href="#">Koszule</a>
                    </dd>
                    <dd><a data-description="Spodnie" href="#">Spodnie</a>
                    </dd>
                    <dd><a data-description="Spodnie" href="#">Spodnie</a>
                    </dd>
                    <dd><a data-description="Rajstopy" href="#">Rajstopy</a>
                    </dd>
                    <dd><a data-description="ReadMore" href="#">Czytaj więcej</a>
                    </dd>
                </dl>
            </div>
            <div class="box col-sm-2 col-xs-6">
                <dl>
                    <dt><a rel="category" data-description="Kategory" href="#">Odzież</a>
                    </dt>
                    <dd><a data-description="Bluzy" href="#">Bluzy</a>
                    </dd>
                    <dd><a data-description="Jeans" href="#">Jeans</a>
                    </dd>
                    <dd><a data-description="Koszule" href="#">Koszule</a>
                    </dd>

                    <dd><a data-description="ReadMore" href="#">Czytaj więcej</a>
                    </dd>
                </dl>
            </div>
            <div class="box col-sm-2 col-xs-6">
                <dl>
                    <dt><a rel="category" data-description="Kategory" href="#">Odzież</a>
                    </dt>
                    <dd><a data-description="Bluzy" href="#">Bluzy</a>
                    </dd>
                    <dd><a data-description="Jeans" href="#">Jeans</a>
                    </dd>
                    <dd><a data-description="Koszule" href="#">Koszule</a>
                    </dd>
                    <dd><a data-description="Spodnie" href="#">Spodnie</a>
                    </dd>
                    <dd><a data-description="Spodnie" href="#">Spodnie</a>
                    </dd>
                    <dd><a data-description="Rajstopy" href="#">Rajstopy</a>
                    </dd>
                    <dd><a data-description="ReadMore" href="#">Czytaj więcej</a>
                    </dd>
                </dl>
            </div>
            <div class="box col-sm-2 col-xs-6">
                <dl>
                    <dt><a rel="category" data-description="Kategory" href="#">Odzież</a>
                    </dt>
                    <dd><a data-description="Bluzy" href="#">Bluzy</a>
                    </dd>
                    <dd><a data-description="Jeans" href="#">Jeans</a>
                    </dd>
                    <dd><a data-description="Koszule" href="#">Koszule</a>
                    </dd>
                    <dd><a data-description="Spodnie" href="#">Spodnie</a>
                    </dd>
                    <dd><a data-description="Spodnie" href="#">Spodnie</a>
                    </dd>
                    <dd><a data-description="Rajstopy" href="#">Rajstopy</a>
                    </dd>
                    <dd><a data-description="ReadMore" href="#">Czytaj więcej</a>
                    </dd>
                </dl>
            </div>
            <div class="box col-sm-2 col-xs-6">
                <dl>
                    <dt><a rel="category" data-description="Kategory" href="#">Odzież</a>
                    </dt>
                    <dd><a data-description="Bluzy" href="#">Bluzy</a>
                    </dd>
                    <dd><a data-description="Jeans" href="#">Jeans</a>
                    </dd>
                    <dd><a data-description="Rajstopy" href="#">Rajstopy</a>
                    </dd>
                    <dd><a data-description="ReadMore" href="#">Czytaj więcej</a>
                    </dd>
                </dl>
            </div>
            <div class="box col-sm-2 col-xs-6">
                <dl>
                    <dt><a rel="category" data-description="Kategory" href="#">Odzież</a>
                    </dt>
                    <dd><a data-description="Bluzy" href="#">Bluzy</a>
                    </dd>
                    <dd><a data-description="Jeans" href="#">Jeans</a>
                    </dd>
                    <dd><a data-description="Koszule" href="#">Koszule</a>
                    </dd>
                    <dd><a data-description="Spodnie" href="#">Spodnie</a>
                    </dd>
                    <dd><a data-description="Spodnie" href="#">Spodnie</a>
                    </dd>
                    <dd><a data-description="Rajstopy" href="#">Rajstopy</a>
                    </dd>
                    <dd><a data-description="ReadMore" href="#">Czytaj więcej</a>
                    </dd>
                </dl>
            </div>
            <div class="box col-sm-2 col-xs-6">
                <dl>
                    <dt><a rel="category" data-description="Kategory" href="#">Odzież</a>
                    </dt>
                    <dd><a data-description="Bluzy" href="#">Bluzy</a>
                    </dd>
                    <dd><a data-description="Jeans" href="#">Jeans</a>
                    </dd>
                    <dd><a data-description="Koszule" href="#">Koszule</a>
                    </dd>

                    <dd><a data-description="ReadMore" href="#">Czytaj więcej</a>
                    </dd>
                </dl>
            </div>
            <div class="box col-sm-2 col-xs-6">
                <dl>
                    <dt><a rel="category" data-description="Kategory" href="#">Odzież</a>
                    </dt>
                    <dd><a data-description="Bluzy" href="#">Bluzy</a>
                    </dd>
                    <dd><a data-description="Jeans" href="#">Jeans</a>
                    </dd>
                    <dd><a data-description="Koszule" href="#">Koszule</a>
                    </dd>
                    <dd><a data-description="Spodnie" href="#">Spodnie</a>
                    </dd>
                    <dd><a data-description="Spodnie" href="#">Spodnie</a>
                    </dd>
                    <dd><a data-description="Rajstopy" href="#">Rajstopy</a>
                    </dd>
                    <dd><a data-description="ReadMore" href="#">Czytaj więcej</a>
                    </dd>
                </dl>
            </div>
            <div class="box col-sm-2 col-xs-6">
                <dl>
                    <dt><a rel="category" data-description="Kategory" href="#">Odzież</a>
                    </dt>
                    <dd><a data-description="Bluzy" href="#">Bluzy</a>
                    </dd>
                    <dd><a data-description="Jeans" href="#">Jeans</a>
                    </dd>
                    <dd><a data-description="Koszule" href="#">Koszule</a>
                    </dd>
                    <dd><a data-description="Spodnie" href="#">Spodnie</a>
                    </dd>
                    <dd><a data-description="Spodnie" href="#">Spodnie</a>
                    </dd>
                    <dd><a data-description="Rajstopy" href="#">Rajstopy</a>
                    </dd>
                    <dd><a data-description="ReadMore" href="#">Czytaj więcej</a>
                    </dd>
                </dl>


            </div>
            <div class="box col-sm-2 col-xs-6">
                <dl>
                    <dt><a rel="category" data-description="Kategory" href="#">Odzież</a>
                    </dt>
                    <dd><a data-description="Bluzy" href="#">Bluzy</a>
                    </dd>
                    <dd><a data-description="Jeans" href="#">Jeans</a>
                    </dd>
                    <dd><a data-description="Rajstopy" href="#">Rajstopy</a>
                    </dd>
                    <dd><a data-description="ReadMore" href="#">Czytaj więcej</a>
                    </dd>
                </dl>
            </div>
        </div>
    </div>

    <div class="col-right hidden-xs">
        <figure>
            <img src="<?php echo $this->getSkinUrl('images/hilfinger.jpg'); ?>" alt="" class="img-responsive">
        </figure>
    </div>
</div>
<div class="row">
    <a href="#" class="closeSubMenu">
        Zamknij menu kategorii
    </a>
</div>
<!-- end row -->
</li>
<!-- end grid demo -->
</ul>
<!-- end drop down menu -->
</li>
<li>
<a href="#" class="children">On <i class="fa fa-caret-down"></i></a>
<ul>
<li>
<div class="row">
    <div class="col-left">
        <div class="jsMasonry">

            <div class="box col-sm-2 col-xs-6">

                <dl>
                    <dt><a rel="category" data-description="Kategory" href="#ona">On</a>
                    </dt>
                    <dd><a data-description="Bluzy" href="#">Bluzy</a>
                    </dd>
                    <dd><a data-description="Jeans" href="#">Jeans</a>
                    </dd>
                    <dd><a data-description="Koszule" href="#">Koszule</a>
                    </dd>
                    <dd><a data-description="Spodnie" href="#">Spodnie</a>
                    </dd>
                    <dd><a data-description="Spodnie" href="#">Spodnie</a>
                    </dd>
                    <dd><a data-description="Rajstopy" href="#">Rajstopy</a>
                    </dd>
                    <dd><a data-description="ReadMore" href="#">Czytaj więcej</a>
                    </dd>
                </dl>
            </div>
            <div class="box col-sm-2 col-xs-6">
                <dl>
                    <dt><a rel="category" data-description="Kategory" href="#">Odzież</a>
                    </dt>
                    <dd><a data-description="Bluzy" href="#">Bluzy</a>
                    </dd>
                    <dd><a data-description="Jeans" href="#">Jeans</a>
                    </dd>
                    <dd><a data-description="Koszule" href="#">Koszule</a>
                    </dd>

                    <dd><a data-description="ReadMore" href="#">Czytaj więcej</a>
                    </dd>
                </dl>
            </div>
            <div class="box col-sm-2 col-xs-6">
                <dl>
                    <dt><a rel="category" data-description="Kategory" href="#">Odzież</a>
                    </dt>
                    <dd><a data-description="Bluzy" href="#">Bluzy</a>
                    </dd>
                    <dd><a data-description="Jeans" href="#">Jeans</a>
                    </dd>
                    <dd><a data-description="Koszule" href="#">Koszule</a>
                    </dd>
                    <dd><a data-description="Spodnie" href="#">Spodnie</a>
                    </dd>
                    <dd><a data-description="Spodnie" href="#">Spodnie</a>
                    </dd>
                    <dd><a data-description="Rajstopy" href="#">Rajstopy</a>
                    </dd>
                    <dd><a data-description="ReadMore" href="#">Czytaj więcej</a>
                    </dd>
                </dl>
            </div>
            <div class="box col-sm-2 col-xs-6">
                <dl>
                    <dt><a rel="category" data-description="Kategory" href="#">Odzież</a>
                    </dt>
                    <dd><a data-description="Bluzy" href="#">Bluzy</a>
                    </dd>
                    <dd><a data-description="Jeans" href="#">Jeans</a>
                    </dd>
                    <dd><a data-description="Koszule" href="#">Koszule</a>
                    </dd>
                    <dd><a data-description="Spodnie" href="#">Spodnie</a>
                    </dd>
                    <dd><a data-description="Spodnie" href="#">Spodnie</a>
                    </dd>
                    <dd><a data-description="Rajstopy" href="#">Rajstopy</a>
                    </dd>
                    <dd><a data-description="ReadMore" href="#">Czytaj więcej</a>
                    </dd>
                </dl>
            </div>
            <div class="box col-sm-2 col-xs-6">
                <dl>
                    <dt><a rel="category" data-description="Kategory" href="#">Odzież</a>
                    </dt>
                    <dd><a data-description="Bluzy" href="#">Bluzy</a>
                    </dd>
                    <dd><a data-description="Jeans" href="#">Jeans</a>
                    </dd>
                    <dd><a data-description="Rajstopy" href="#">Rajstopy</a>
                    </dd>
                    <dd><a data-description="ReadMore" href="#">Czytaj więcej</a>
                    </dd>
                </dl>
            </div>
            <div class="box col-sm-2 col-xs-6">
                <dl>
                    <dt><a rel="category" data-description="Kategory" href="#">Odzież</a>
                    </dt>
                    <dd><a data-description="Bluzy" href="#">Bluzy</a>
                    </dd>
                    <dd><a data-description="Jeans" href="#">Jeans</a>
                    </dd>
                    <dd><a data-description="Koszule" href="#">Koszule</a>
                    </dd>
                    <dd><a data-description="Spodnie" href="#">Spodnie</a>
                    </dd>
                    <dd><a data-description="Spodnie" href="#">Spodnie</a>
                    </dd>
                    <dd><a data-description="Rajstopy" href="#">Rajstopy</a>
                    </dd>
                    <dd><a data-description="ReadMore" href="#">Czytaj więcej</a>
                    </dd>
                </dl>
            </div>
            <div class="box col-sm-2 col-xs-6">
                <dl>
                    <dt><a rel="category" data-description="Kategory" href="#">Odzież</a>
                    </dt>
                    <dd><a data-description="Bluzy" href="#">Bluzy</a>
                    </dd>
                    <dd><a data-description="Jeans" href="#">Jeans</a>
                    </dd>
                    <dd><a data-description="Koszule" href="#">Koszule</a>
                    </dd>

                    <dd><a data-description="ReadMore" href="#">Czytaj więcej</a>
                    </dd>
                </dl>
            </div>
            <div class="box col-sm-2 col-xs-6">
                <dl>
                    <dt><a rel="category" data-description="Kategory" href="#">Odzież</a>
                    </dt>
                    <dd><a data-description="Bluzy" href="#">Bluzy</a>
                    </dd>
                    <dd><a data-description="Jeans" href="#">Jeans</a>
                    </dd>
                    <dd><a data-description="Koszule" href="#">Koszule</a>
                    </dd>
                    <dd><a data-description="Spodnie" href="#">Spodnie</a>
                    </dd>
                    <dd><a data-description="Spodnie" href="#">Spodnie</a>
                    </dd>
                    <dd><a data-description="Rajstopy" href="#">Rajstopy</a>
                    </dd>
                    <dd><a data-description="ReadMore" href="#">Czytaj więcej</a>
                    </dd>
                </dl>
            </div>
            <div class="box col-sm-2 col-xs-6">
                <dl>
                    <dt><a rel="category" data-description="Kategory" href="#">Odzież</a>
                    </dt>
                    <dd><a data-description="Bluzy" href="#">Bluzy</a>
                    </dd>
                    <dd><a data-description="Jeans" href="#">Jeans</a>
                    </dd>
                    <dd><a data-description="Koszule" href="#">Koszule</a>
                    </dd>
                    <dd><a data-description="Spodnie" href="#">Spodnie</a>
                    </dd>
                    <dd><a data-description="Spodnie" href="#">Spodnie</a>
                    </dd>
                    <dd><a data-description="Rajstopy" href="#">Rajstopy</a>
                    </dd>
                    <dd><a data-description="ReadMore" href="#">Czytaj więcej</a>
                    </dd>
                </dl>


            </div>
            <div class="box col-sm-2 col-xs-6">
                <dl>
                    <dt><a rel="category" data-description="Kategory" href="#">Odzież</a>
                    </dt>
                    <dd><a data-description="Bluzy" href="#">Bluzy</a>
                    </dd>
                    <dd><a data-description="Jeans" href="#">Jeans</a>
                    </dd>
                    <dd><a data-description="Rajstopy" href="#">Rajstopy</a>
                    </dd>
                    <dd><a data-description="ReadMore" href="#">Czytaj więcej</a>
                    </dd>
                </dl>
            </div>
        </div>
    </div>

    <div class="col-right hidden-xs">
        <figure>
            <img src="<?php echo $this->getSkinUrl('images/hilfinger.jpg'); ?>" alt="" class="img-responsive">
        </figure>
    </div>
</div>
<div class="row">
    <a href="#" class="closeSubMenu">
        Zamknij menu kategorii
    </a>
</div>
<!-- end row -->
</li>
</ul>
<!-- end dropdown-menu -->
</li>
<li><a href="#">Dziecko</a>
</li>
<li><a href="#">Wybierz sklep</a>
</li>
<li><a href="#">Outlet</a>
</li>
<li><a href="#">W twoim stylu</a>
</li>
</ul>
<ul id="nav_mobile" class="navigation visible-xs" role="navigation">
    <li><a href="#">Ona <span class="ico-submenu-mobile-right"></span></a>
        <ul>
            <li><a href="#">Action</a>
            </li>
            <li><a href="#">Another action</a>
            </li>
            <li><a href="#">Something else here</a>
            </li>

            <li><a href="#">Separated link</a>
            </li>

            <li><a href="#">One more separated link</a>
            </li>
        </ul>
    </li>
    <li><a href="#">On <span class="ico-submenu-mobile-right"></span></a>
        <ul>
            <li><a href="#">Action</a>
            </li>
            <li><a href="#">Another action</a>
            </li>
            <li><a href="#">Something else here</a>
            </li>

            <li><a href="#">Separated link</a>
            </li>

            <li><a href="#">One more separated link</a>
            </li>
        </ul>
    </li>
    <li><a href="#">Dziecko</a>
    </li>
    <li><a href="#">Wybierz sklep</a>
    </li>
    <li><a href="#">Outlet</a>
    </li>
    <li><a href="">W twoim stylu</a>
    </li>
</ul>
</div>


</nav>
</div>

</div>
<div id="clone_submenu" class="hidden-xs clearfix">
    <div class="container-fluid">

    </div>
</div>