<div class="header_bottom">
<div class="container-fluid">
<nav role="navigation">


<div id="navigation">
<ul id="nav_desc" class="navigation hidden-xs" role="navigation">
<li class="">
<a href="#" class="children">Ona <i class="fa fa-caret-down"></i></a>

<ul>
<li>
    <div class="row clearfix">
        <div class="col-left">
            <div class="jsMasonry">

                <div class="box col-sm-2 col-xs-6">

                    <dl>
                        <dt><a rel="category" data-description="Kategory" href="#ona">Ona</a>
                        </dt>
                        <dd><a data-description="Bluzy" href="#">Bluzy</a>
                        </dd>
                        <dd><a data-description="Jeans" href="#">Jeans</a>
                        </dd>
                        <dd><a data-description="Koszule" href="#">Koszule</a>
                        </dd>
                        <dd><a data-description="Spodnie" href="#">Spodnie</a>
                        </dd>
                        <dd><a data-description="Spodnie" href="#">Spodnie</a>
                        </dd>
                        <dd><a data-description="Rajstopy" href="#">Rajstopy</a>
                        </dd>
                        <dd><a data-description="ReadMore" href="#">Czytaj więcej <i class="fa fa-angle-right"></i></a>
                        </dd>
                    </dl>
                </div>
                <div class="box col-sm-2 col-xs-6">
                    <dl>
                        <dt><a rel="category" data-description="Kategory" href="#">Odzież</a>
                        </dt>
                        <dd><a data-description="Bluzy" href="#">Bluzy</a>
                        </dd>
                        <dd><a data-description="Jeans" href="#">Jeans</a>
                        </dd>
                        <dd><a data-description="Koszule" href="#">Koszule</a>
                        </dd>

                        <dd><a data-description="ReadMore" href="#">Czytaj więcej <i class="fa fa-angle-right"></i></a>
                        </dd>
                    </dl>
                </div>
                <div class="box col-sm-2 col-xs-6">
                    <dl>
                        <dt><a rel="category" data-description="Kategory" href="#">Odzież</a>
                        </dt>
                        <dd><a data-description="Bluzy" href="#">Bluzy</a>
                        </dd>
                        <dd><a data-description="Jeans" href="#">Jeans</a>
                        </dd>
                        <dd><a data-description="Koszule" href="#">Koszule</a>
                        </dd>
                        <dd><a data-description="Spodnie" href="#">Spodnie</a>
                        </dd>
                        <dd><a data-description="Spodnie" href="#">Spodnie</a>
                        </dd>
                        <dd><a data-description="Rajstopy" href="#">Rajstopy</a>
                        </dd>
                        <dd><a data-description="ReadMore" href="#">Czytaj więcej <i class="fa fa-angle-right"></i></a>
                        </dd>
                    </dl>
                </div>
                <div class="box col-sm-2 col-xs-6">
                    <dl>
                        <dt><a rel="category" data-description="Kategory" href="#">Odzież</a>
                        </dt>
                        <dd><a data-description="Bluzy" href="#">Bluzy</a>
                        </dd>
                        <dd><a data-description="Jeans" href="#">Jeans</a>
                        </dd>
                        <dd><a data-description="Koszule" href="#">Koszule</a>
                        </dd>
                        <dd><a data-description="Spodnie" href="#">Spodnie</a>
                        </dd>
                        <dd><a data-description="Spodnie" href="#">Spodnie</a>
                        </dd>
                        <dd><a data-description="Rajstopy" href="#">Rajstopy</a>
                        </dd>
                        <dd><a data-description="ReadMore" href="#">Czytaj więcej <i class="fa fa-angle-right"></i></a>
                        </dd>
                    </dl>
                </div>
                <div class="box col-sm-2 col-xs-6">
                    <dl>
                        <dt><a rel="category" data-description="Kategory" href="#">Odzież</a>
                        </dt>
                        <dd><a data-description="Bluzy" href="#">Bluzy</a>
                        </dd>
                        <dd><a data-description="Jeans" href="#">Jeans</a>
                        </dd>
                        <dd><a data-description="Rajstopy" href="#">Rajstopy</a>
                        </dd>
                        <dd><a data-description="ReadMore" href="#">Czytaj więcej <i class="fa fa-angle-right"></i></a>
                        </dd>
                    </dl>
                </div>
                <div class="box col-sm-2 col-xs-6">
                    <dl>
                        <dt><a rel="category" data-description="Kategory" href="#">Odzież</a>
                        </dt>
                        <dd><a data-description="Bluzy" href="#">Bluzy</a>
                        </dd>
                        <dd><a data-description="Jeans" href="#">Jeans</a>
                        </dd>
                        <dd><a data-description="Koszule" href="#">Koszule</a>
                        </dd>
                        <dd><a data-description="Spodnie" href="#">Spodnie</a>
                        </dd>
                        <dd><a data-description="Spodnie" href="#">Spodnie</a>
                        </dd>
                        <dd><a data-description="Rajstopy" href="#">Rajstopy</a>
                        </dd>
                        <dd><a data-description="ReadMore" href="#">Czytaj więcej <i class="fa fa-angle-right"></i></a>
                        </dd>
                    </dl>
                </div>
                <div class="box col-sm-2 col-xs-6">
                    <dl>
                        <dt><a rel="category" data-description="Kategory" href="#">Odzież</a>
                        </dt>
                        <dd><a data-description="Bluzy" href="#">Bluzy</a>
                        </dd>
                        <dd><a data-description="Jeans" href="#">Jeans</a>
                        </dd>
                        <dd><a data-description="Koszule" href="#">Koszule</a>
                        </dd>

                        <dd><a data-description="ReadMore" href="#">Czytaj więcej <i class="fa fa-angle-right"></i></a>
                        </dd>
                    </dl>
                </div>
                <div class="box col-sm-2 col-xs-6">
                    <dl>
                        <dt><a rel="category" data-description="Kategory" href="#">Odzież</a>
                        </dt>
                        <dd><a data-description="Bluzy" href="#">Bluzy</a>
                        </dd>
                        <dd><a data-description="Jeans" href="#">Jeans</a>
                        </dd>
                        <dd><a data-description="Koszule" href="#">Koszule</a>
                        </dd>
                        <dd><a data-description="Spodnie" href="#">Spodnie</a>
                        </dd>
                        <dd><a data-description="Spodnie" href="#">Spodnie</a>
                        </dd>
                        <dd><a data-description="Rajstopy" href="#">Rajstopy</a>
                        </dd>
                        <dd><a data-description="ReadMore" href="#">Czytaj więcej <i class="fa fa-angle-right"></i></a>
                        </dd>
                    </dl>
                </div>
                <div class="box col-sm-2 col-xs-6">
                    <dl>
                        <dt><a rel="category" data-description="Kategory" href="#">Odzież</a>
                        </dt>
                        <dd><a data-description="Bluzy" href="#">Bluzy</a>
                        </dd>
                        <dd><a data-description="Jeans" href="#">Jeans</a>
                        </dd>
                        <dd><a data-description="Koszule" href="#">Koszule</a>
                        </dd>
                        <dd><a data-description="Spodnie" href="#">Spodnie</a>
                        </dd>
                        <dd><a data-description="Spodnie" href="#">Spodnie</a>
                        </dd>
                        <dd><a data-description="Rajstopy" href="#">Rajstopy</a>
                        </dd>
                        <dd><a data-description="ReadMore" href="#">Czytaj więcej <i class="fa fa-angle-right"></i></a>
                        </dd>
                    </dl>


                </div>
                <div class="box col-sm-2 col-xs-6">
                    <dl>
                        <dt><a rel="category" data-description="Kategory" href="#">Odzież</a>
                        </dt>
                        <dd><a data-description="Bluzy" href="#">Bluzy</a>
                        </dd>
                        <dd><a data-description="Jeans" href="#">Jeans</a>
                        </dd>
                        <dd><a data-description="Rajstopy" href="#">Rajstopy</a>
                        </dd>
                        <dd><a data-description="ReadMore" href="#">Czytaj więcej <i class="fa fa-angle-right"></i></a>
                        </dd>
                    </dl>
                </div>
            </div>
            <a href="#" class="view-all-category">zobacz wszystkie kategorie <i class="fa fa-angle-right"></i></a>
        </div>

        <div class="col-right hidden-xs">
            <figure>
                <img src="skin/frontend/modago/default/images/hilfinger.jpg" alt="" class="img-responsive">
            </figure>
        </div>
    </div>
    <div class="row">
        <a href="#" class="closeSubMenu">ZWIŃ</i></a>
    </div>
    <!-- end row -->
</li>
<!-- end grid demo -->
</ul>
<!-- end drop down menu -->
</li>
<li>
<a href="#" class="children">On <i class="fa fa-caret-down"></i></a>
<ul>
<li>
    <div class="row">
        <div class="col-left">
            <div class="jsMasonry">

                <div class="box col-sm-2 col-xs-6">

                    <dl>
                        <dt><a rel="category" data-description="Kategory" href="#ona">On</a>
                        </dt>
                        <dd><a data-description="Bluzy" href="#">Bluzy</a>
                        </dd>
                        <dd><a data-description="Jeans" href="#">Jeans</a>
                        </dd>
                        <dd><a data-description="Koszule" href="#">Koszule</a>
                        </dd>
                        <dd><a data-description="Spodnie" href="#">Spodnie</a>
                        </dd>
                        <dd><a data-description="Spodnie" href="#">Spodnie</a>
                        </dd>
                        <dd><a data-description="Rajstopy" href="#">Rajstopy</a>
                        </dd>
                        <dd><a data-description="ReadMore" href="#">Czytaj więcej <i class="fa fa-angle-right"></i></a>
                        </dd>
                    </dl>
                </div>
                <div class="box col-sm-2 col-xs-6">
                    <dl>
                        <dt><a rel="category" data-description="Kategory" href="#">Odzież</a>
                        </dt>
                        <dd><a data-description="Bluzy" href="#">Bluzy</a>
                        </dd>
                        <dd><a data-description="Jeans" href="#">Jeans</a>
                        </dd>
                        <dd><a data-description="Koszule" href="#">Koszule</a>
                        </dd>

                        <dd><a data-description="ReadMore" href="#">Czytaj więcej <i class="fa fa-angle-right"></i></a>
                        </dd>
                    </dl>
                </div>
                <div class="box col-sm-2 col-xs-6">
                    <dl>
                        <dt><a rel="category" data-description="Kategory" href="#">Odzież</a>
                        </dt>
                        <dd><a data-description="Bluzy" href="#">Bluzy</a>
                        </dd>
                        <dd><a data-description="Jeans" href="#">Jeans</a>
                        </dd>
                        <dd><a data-description="Koszule" href="#">Koszule</a>
                        </dd>
                        <dd><a data-description="Spodnie" href="#">Spodnie</a>
                        </dd>
                        <dd><a data-description="Spodnie" href="#">Spodnie</a>
                        </dd>
                        <dd><a data-description="Rajstopy" href="#">Rajstopy</a>
                        </dd>
                        <dd><a data-description="ReadMore" href="#">Czytaj więcej <i class="fa fa-angle-right"></i></a>
                        </dd>
                    </dl>
                </div>
                <div class="box col-sm-2 col-xs-6">
                    <dl>
                        <dt><a rel="category" data-description="Kategory" href="#">Odzież</a>
                        </dt>
                        <dd><a data-description="Bluzy" href="#">Bluzy</a>
                        </dd>
                        <dd><a data-description="Jeans" href="#">Jeans</a>
                        </dd>
                        <dd><a data-description="Koszule" href="#">Koszule</a>
                        </dd>
                        <dd><a data-description="Spodnie" href="#">Spodnie</a>
                        </dd>
                        <dd><a data-description="Spodnie" href="#">Spodnie</a>
                        </dd>
                        <dd><a data-description="Rajstopy" href="#">Rajstopy</a>
                        </dd>
                        <dd><a data-description="ReadMore" href="#">Czytaj więcej <i class="fa fa-angle-right"></i></a>
                        </dd>
                    </dl>
                </div>
                <div class="box col-sm-2 col-xs-6">
                    <dl>
                        <dt><a rel="category" data-description="Kategory" href="#">Odzież</a>
                        </dt>
                        <dd><a data-description="Bluzy" href="#">Bluzy</a>
                        </dd>
                        <dd><a data-description="Jeans" href="#">Jeans</a>
                        </dd>
                        <dd><a data-description="Rajstopy" href="#">Rajstopy</a>
                        </dd>
                        <dd><a data-description="ReadMore" href="#">Czytaj więcej <i class="fa fa-angle-right"></i></a>
                        </dd>
                    </dl>
                </div>
                <div class="box col-sm-2 col-xs-6">
                    <dl>
                        <dt><a rel="category" data-description="Kategory" href="#">Odzież</a>
                        </dt>
                        <dd><a data-description="Bluzy" href="#">Bluzy</a>
                        </dd>
                        <dd><a data-description="Jeans" href="#">Jeans</a>
                        </dd>
                        <dd><a data-description="Koszule" href="#">Koszule</a>
                        </dd>
                        <dd><a data-description="Spodnie" href="#">Spodnie</a>
                        </dd>
                        <dd><a data-description="Spodnie" href="#">Spodnie</a>
                        </dd>
                        <dd><a data-description="Rajstopy" href="#">Rajstopy</a>
                        </dd>
                        <dd><a data-description="ReadMore" href="#">Czytaj więcej <i class="fa fa-angle-right"></i></a>
                        </dd>
                    </dl>
                </div>
                <div class="box col-sm-2 col-xs-6">
                    <dl>
                        <dt><a rel="category" data-description="Kategory" href="#">Odzież</a>
                        </dt>
                        <dd><a data-description="Bluzy" href="#">Bluzy</a>
                        </dd>
                        <dd><a data-description="Jeans" href="#">Jeans</a>
                        </dd>
                        <dd><a data-description="Koszule" href="#">Koszule</a>
                        </dd>

                        <dd><a data-description="ReadMore" href="#">Czytaj więcej <i class="fa fa-angle-right"></i></a>
                        </dd>
                    </dl>
                </div>
                <div class="box col-sm-2 col-xs-6">
                    <dl>
                        <dt><a rel="category" data-description="Kategory" href="#">Odzież</a>
                        </dt>
                        <dd><a data-description="Bluzy" href="#">Bluzy</a>
                        </dd>
                        <dd><a data-description="Jeans" href="#">Jeans</a>
                        </dd>
                        <dd><a data-description="Koszule" href="#">Koszule</a>
                        </dd>
                        <dd><a data-description="Spodnie" href="#">Spodnie</a>
                        </dd>
                        <dd><a data-description="Spodnie" href="#">Spodnie</a>
                        </dd>
                        <dd><a data-description="Rajstopy" href="#">Rajstopy</a>
                        </dd>
                        <dd><a data-description="ReadMore" href="#">Czytaj więcej <i class="fa fa-angle-right"></i></a>
                        </dd>
                    </dl>
                </div>
                <div class="box col-sm-2 col-xs-6">
                    <dl>
                        <dt><a rel="category" data-description="Kategory" href="#">Odzież</a>
                        </dt>
                        <dd><a data-description="Bluzy" href="#">Bluzy</a>
                        </dd>
                        <dd><a data-description="Jeans" href="#">Jeans</a>
                        </dd>
                        <dd><a data-description="Koszule" href="#">Koszule</a>
                        </dd>
                        <dd><a data-description="Spodnie" href="#">Spodnie</a>
                        </dd>
                        <dd><a data-description="Spodnie" href="#">Spodnie</a>
                        </dd>
                        <dd><a data-description="Rajstopy" href="#">Rajstopy</a>
                        </dd>
                        <dd><a data-description="ReadMore" href="#">Czytaj więcej <i class="fa fa-angle-right"></i></a>
                        </dd>
                    </dl>


                </div>
                <div class="box col-sm-2 col-xs-6">
                    <dl>
                        <dt><a rel="category" data-description="Kategory" href="#">Odzież</a>
                        </dt>
                        <dd><a data-description="Bluzy" href="#">Bluzy</a>
                        </dd>
                        <dd><a data-description="Jeans" href="#">Jeans</a>
                        </dd>
                        <dd><a data-description="Rajstopy" href="#">Rajstopy</a>
                        </dd>
                        <dd><a data-description="ReadMore" href="#">Czytaj więcej <i class="fa fa-angle-right"></i></a>
                        </dd>
                    </dl>
                </div>
            </div>
            <a href="#" class="view-all-category">zobacz wszystkie kategorie <i class="fa fa-angle-right"></i></a>
        </div>

        <div class="col-right hidden-xs">
            <figure>
                <img src="skin/frontend/modago/default/images/hilfinger.jpg" alt="" class="img-responsive">
            </figure>
        </div>
    </div>
    <div class="row">
        <a href="#" class="closeSubMenu">ZWIŃ</i></a>
    </div>
    <!-- end row -->
</li>
</ul>
<!-- end dropdown-menu -->
</li>
<li><a href="#">Dziecko</a>
</li>
<li><a href="#">Wybierz sklep</a>
</li>
<li><a href="#">Outlet</a>
</li>
<li><a href="#">W twoim stylu</a>
</li>
</ul>
<ul id="nav_mobile" class="navigation visible-xs" role="navigation">
    <li><a href="#">Ona <i class="fa fa-chevron-down"></i></a>
        <ul>
            <li><a href="#">Action</a>
            </li>
            <li><a href="#">Another action</a>
            </li>
            <li><a href="#">Something else here</a>
            </li>

            <li><a href="#">Separated link</a>
            </li>

            <li><a href="#">One more separated link</a>
            </li>
        </ul>
    </li>
    <li><a href="#">On <i class="fa fa-chevron-down"></i></a>
        <ul>
            <li><a href="#">Action</a>
            </li>
            <li><a href="#">Another action</a>
            </li>
            <li><a href="#">Something else here</a>
            </li>

            <li><a href="#">Separated link</a>
            </li>

            <li><a href="#">One more separated link</a>
            </li>
        </ul>
    </li>
    <li><a href="#">Dziecko <i class="fa fa-chevron-right"></i></a>
    </li>
    <li><a href="#">Wybierz sklep <i class="fa fa-chevron-right"></i></a>
    </li>
    <li><a href="#">Outlet <i class="fa fa-chevron-right"></i></a>
    </li>
    <li><a href="">W twoim stylu <i class="fa fa-chevron-right"></i></a>
    </li>
</ul>
<nav id="navCategory" class="visible-xs">
    <h3>Dla kobiet</h3>
    <a href="#" class="backToCategory">przejdź wyżej <i class="fa fa-angle-up"></i></a>
    <ul id="nav_category_mobile" class="navigation" role="navigation">
        <li><a href="#">Sukienki </a></li>
        <li><a href="#">Spodnie</a></li>
        <li><a href="#">Koszulki</a></li>
        <li><a href="#">Bluzki</a></li>
        <li><a href="#">Koszule</a></li>
        <li><a href="#">Bielizna</a></li>
        <li><a href="#">Kurtki</a></li>
        <li><a href="#">Marynarki</a></li>
    </ul>
</nav>
</div>


</nav>
</div>

</div>
<div id="clone_submenu" class="hidden-xs clearfix">
    <div class="container-fluid">

    </div>
</div>