<?php
/**
 * Used in cms block: navigation-main-mobile
 */
/** @var $this Zolago_Modago_Block_Catalog_Category */
$categories = $this->getMainCategoriesMobile();
?>
<?php if (count($categories) > 0) : ?>
    <?php foreach ($categories as $cat) : ?>
        <?php if ($cat["solr_product_count"] > 0): ?>
            <li>
                <a href="<?php echo (isset($cat['has_dropdown']) && $cat['has_dropdown'])  ? '#' : $cat['url']; ?>">
                    <?php echo $this->escapeHtml($cat['name']); ?>
                    (<?php echo $cat["solr_product_count"]; //TODO ONLY FOR TEST ?>)
                    <?php echo (isset($cat['has_dropdown']) && $cat['has_dropdown']) ? '<i class="fa fa-chevron-down"></i>'
                        : '<i class="fa fa-chevron-right"></i>'; ?>
                </a>
                <?php if (isset($cat['has_dropdown']) && $cat['has_dropdown']  && ($cat["solr_product_count"] > 0)) : ?>
                    <ul>
                        <?php foreach ($cat['has_dropdown'] as $child) : ?>
                            <?php if ($child["solr_product_count"] > 0): ?>
                                <li>
                                    <a href="<?php echo $child['url']; ?>">
                                        <?php echo $this->escapeHtml($child['name']); ?>
                                        (<?php echo $child["solr_product_count"]; //TODO ONLY FOR TEST ?>)
                                    </a>
                                </li>
                            <?php endif; ?>
                        <?php endforeach; ?>
                    </ul>
                <?php endif; ?>
            </li>
        <?php endif; ?>
    <?php endforeach; ?>
<?php endif; ?>