<?php
/**
 * Created by PhpStorm.
 * User: Andrzej Spólnicki
 * Date: 27.08.14
 * Time: 13:56
 */

/** @var $this Mage_Core_Block_Template */
/** @var Zolago_Dropship_Model_Vendor $vendor */
$vendor = Mage::helper('umicrosite')->getCurrentVendor();
/** @var Zolago_Solrsearch_Helper_Data $helper */
$helperSolrSearch = Mage::helper("zolagosolrsearch");
$category = $helperSolrSearch->getCurrentCategory();

if ($vendor && $vendor->isBrandshop()) {
    //when vendor(brandshop) show navigation only on the cms categories
    if($category && $category->getDisplayMode() == Mage_Catalog_Model_Category::DM_PAGE) {
        echo $this->getLayout()->createBlock('cms/block')->setBlockId('navigation-main-wrapper')->toHtml();
    }
} else {
    echo $this->getLayout()->createBlock('cms/block')->setBlockId('navigation-main-wrapper')->toHtml();
}