<?php
/**
 * Created by PhpStorm.
 * User: Andrzej Spólnicki
 * Date: 27.08.14
 * Time: 13:56
 */

/** @var $this Mage_Core_Block_Template */
/** @var Zolago_Dropship_Model_Vendor $vendor */
$vendor = Mage::helper('umicrosite')->getCurrentVendor();
if ($vendor && $vendor->isBrandshopType()) {
    //when vendor(brandshop) then don't show navigation
} else {
    echo $this->getLayout()->createBlock('cms/block')->setBlockId('navigation-main-wrapper')->toHtml();
}