<?php
/**
 * Author: Paweł Chyl <pawel.chyl@orba.pl>
 * Date: 02.05.14
 * @see Zolago_Modago_Block_Page_Header_Leftmenu
 */
?>

<div class="block_toggle_menu"><a href="#sliding-menu" class="toggleMenu"><i class="ico_menu"></i></a></div>

<!-- ============================================================================================================================================= -->
<!-- ========================================================= MENU SLIDING LEFT TO RIGHT  ======================================================= -->
<!-- ============================================================================================================================================= -->
<nav id="sliding-menu">

    <ul>
        <li><a href="#wrapper">Close the menu</a>
        </li>
        <li><a href="horizontal-submenus.html">Horizontal submenus example</a>
        </li>
        <li>
            <a href="vertical-submenus.html">Vertical submenus example</a>
            <ul class="list">
                <li><a href="#">First sub-item</a>
                </li>
                <li>
                    <a href="#">Second sub-item</a>
                    <ul class="list">
                        <li><a href="#">First sub-sub-item</a>
                        </li>
                        <li><a href="#">Second sub-sub-item</a>
                        </li>
                        <li><a href="#">Third sub-sub-item</a>
                        </li>
                    </ul>
                </li>
                <li><a href="#">Third sub-item</a>
                </li>
            </ul>
        </li>
        <li><a href="photos.html">Photos in sliding panels</a>
        </li>
        <li><a href="positions.html">Positioning the menu</a>
        </li>
        <li><a href="colors.html">Coloring the menu</a>
        </li>
        <li><a href="advanced.html">Advanced example</a>
        </li>
        <li><a href="onepage.html">One page scrolling example</a>
        </li>
        <li><a href="jqmobile/index.html">jQuery Mobile example</a>
        </li>
    </ul>
</nav>
<!-- ============================================================================================================================================= -->
<!-- ====================================================== END MENU SLIDING LEFT TO RIGHT  ====================================================== -->
<!-- ============================================================================================================================================= -->


