<?php
/**
 * Author: Paweł Chyl <pawel.chyl@orba.pl>
 * Date: 02.05.14
 * @see Zolago_Modago_Block_Page_Header_Rightmenu
 */
?>

<!-- NAV RIGHT -->
<div id="header_top_block_right">
    <div id="user_menu" class="pull-right">
        <ul class="user-navigation pull-right">
            <li id="link_your_account" class="hidden-sm hidden-xs">
                <a href="#"><i class="ico_your_account"></i><br><span class="hidden-sm hidden-xs"><?php echo $this->__("Your account"); ?></span></a>
            </li>
            <li id="link_favorites">
                <a href="#"><i class="ico_favorites"><span class="badge">42</span></i><br><span
                        class="hidden-sm hidden-xs"><?php echo $this->__("Favorites"); ?></span></a>

            </li>
            <li id="link_basket" style="position:relative;">
                <a class="dropdown-toggle" data-dropdown="#dropdown-basket" href="#">
                    <i class="ico_basket"><span class="badge">42</span></i>
                    <br>
                    <span class="hidden-sm hidden-xs"><?php echo $this->__("Basket"); ?></span>

                </a>


            </li>
        </ul>
    </div>
</div>