<?php
/**
 * Author: Paweł Chyl <pawel.chyl@orba.pl>
 * Date: 02.05.14
 * @see Zolago_Modago_Block_Page_Header_Rightmenu
 */
?>

<!-- NAV RIGHT -->
<div id="header_top_block_right">
    <div id="user_menu" class="pull-right">
        <ul class="user-navigation pull-right">
	        <li id="link_menu" class="hidden-md hidden-lg not-open">
		        <a href="" class="toggleMenu sb-toggle-left">
			        <img src="<?php echo $this->getSkinUrl("images/svg/menu.svg"); ?>" class="header_icon" />
		        </a>
	        </li>
	        <li id="link_search" class="hidden-md hidden-lg not-open">
		        <a class="dropdown-toggle" data-dropdown="#dropdown-search" id="toggleSearch">
			        <img src="<?php echo $this->getSkinUrl("images/svg/search.svg"); ?>" class="header_icon" />
		        </a>
	        </li>
            <li id="link_your_account">
                <a href="">
	                <img src="<?php echo $this->getSkinUrl("images/svg/user.svg"); ?>" class="header_icon" />
	                <span class="hidden-sm hidden-xs"><?php echo $this->__("Your account"); ?></span>
                </a>
            </li>
            <li id="link_favorites">
                <a href="">
	                <div class="badgeHolder">
                        <span class="badge"></span>
                        <img src="<?php echo $this->getSkinUrl("images/svg/favourite.svg"); ?>" class="header_icon" />
	                </div>
                    <span class="hidden-sm hidden-xs"><?php echo $this->__("Favorites"); ?></span>
                </a>

            </li>
            <li id="link_basket" class="basket-dropdown" style="position:relative;">
                <a class="dropdown-toggle" data-dropdown="#dropdown-basket" href="">
	                <div class="badgeHolder">
	                    <span class="badge"></span>
		                <img src="<?php echo $this->getSkinUrl("images/svg/cart.svg"); ?>" class="header_icon" />
	                </div>
                    <span class="hidden-sm hidden-xs"><?php echo $this->__("Basket"); ?></span>
                </a>
            </li>
        </ul>
    </div>
</div>