<?php /* @var $this Zolago_Solrsearch_Block_Catalog_Product_List_Toolbar */ ?>
<div style="margin-bottom: 20px;">
	<div class="left">
		<?php $_total = $this->getNumFound();?>
		<?php echo $this->__("Total %d products found", $_total);?>
	</div>
	<div class="left" style="margin-left: 20px;">
		<label for="sort">Sort by</label>
		<select name="sort" id="sort">
			<?php foreach($this->getSortOptions() as $option):?>
			<option value="<?php echo $this->escapeHtml($option['value']);?>"><?php echo $this->escapeHtml($option['label']);?></option>
			<?php endforeach;?>
		</select>
	</div>
	<div class="clearer"></div>
</div>