<?php /* @var $this Zolago_Solrsearch_Block_Catalog_Product_List_Toolbar */ ?>
<div style="margin-bottom: 20px;">
	<div class="left">
		<?php $_total = $this->getNumFound();?>
		<?php echo $this->__("Total %d products found", $_total);?>
	</div>
	<div class="left" style="margin-left: 20px;">
		<label for="sort">Sort by</label>
		<select onChange="document.location.href=this.options[this.selectedIndex].value" name="sort" id="sort">
			<?php foreach($this->getSortOptions() as $option):?>
			<option <?php if($this->getCurrentOrder()==$option['value'] && $this->getCurrentDir()==$option['dir']):?>selected="selected"<?php endif;?> 
				value="<?php echo $this->getSortUrl($option);?>"><?php echo $this->escapeHtml($option['label']);?></option>
			<?php endforeach;?>
		</select>
	</div>
	<div class="clearer"></div>
</div>