<?php /** @var Ced_SocialLogin_Block_Login $this */ ?>

<div class="social-login">
    <?php if($this->_facebookEnabled()): ?>
    <div class="social-button social-button-facebook">
        <?php echo $this->getChildHtml('ced_facebook_login_button'); ?>
    </div>
    <?php endif; ?>
	<?php if($this->_googleEnabled()): ?>
		<div class="social-button social-button-google">
			<?php echo $this->getChildHtml('ced_google_login_button'); ?>
		</div>
	<?php endif; ?>
    <?php if($this->_twitterEnabled()): ?>
    <div class="social-button social-button-twitter">
        <?php echo $this->getChildHtml('ced_twitter_login_button'); ?>
    </div>
    <?php endif; ?>
     <?php if($this->_linkedinEnabled()): ?>
    <div class="social-button social-button-linkedin">
        <?php echo $this->getChildHtml('ced_linkedin_login_button'); ?>
    </div>
    <?php endif; ?>
</div>