<?php
/** @var Gh_Regulation_Block_Adminhtml_List_Edit $this */
?>
<div class="content-header">
    <h3><?php echo $this->getHeaderText() ?></h3>
    <p class="content-buttons form-buttons">
        <?php echo $this->getButtonsHtml(); ?>
    </p>
</div>
<form action="<?php echo $this->getSaveUrl() ?>" method="post" id="regulation_document_edit_form" enctype="multipart/form-data">
    <?php echo $this->getBlockHtml('formkey')?>
    <?php echo $this->getChild('form')->toHtml(); ?>
</form>
<script type="text/javascript">
    //<![CDATA[
    var editForm = new varienForm('regulation_document_edit_form');
    var regulationDocumentControl = {
        save: function() {
            editForm.submit();
            return false;
        }
    };

</script>
