<?php
$baseUrl = Mage::helper("zolagodropshipmicrosite")->getBaseUrl();

$rootCatId = Mage::app()->getStore()->getRootCategoryId();
$rootCatId = Mage::registry('current_category') ? Mage::registry('current_category')->getId() : $rootCatId;
$categories = Mage::getModel('catalog/category')->getCategories($rootCatId);
$categories = Mage::helper('zolagomodago')->getCategoriesTree($categories, 1, 2);

?>

<div class="top_bottom  bg-w visible-xs clearfix">
    <div id="shop_navigation" class="col-sm-12">
        <ul id="shop_nav_mobile" class="navigation visible-xs" role="navigation">
            <?php if (count($categories) > 0) : ?>
                <?php foreach ($categories as $cat) : ?>
                    <li>
                        <a href="<?php echo (isset($cat['url'])) ? $cat['url'] : '#'; ?>" <?php echo (isset($cat['has_dropdown']) && $cat['has_dropdown']) ? '' : 'class="clickable"' ?>>
                            <?php echo $this->escapeHtml($cat['name']); ?>
                            <?php echo (isset($cat['has_dropdown']) && $cat['has_dropdown']) ? '<i class="fa fa-chevron-down"></i>'
                                : '<i class="fa fa-chevron-right"></i>'; ?>
                        </a>
                        <?php if (isset($cat['has_dropdown']) && $cat['has_dropdown']) : ?>
                            <ul>
                                <?php foreach ($cat['has_dropdown'] as $child) : ?>
                                    <li>
                                        <a href="<?php echo $child['url']; ?>" class="clickable">
                                            <?php echo $this->escapeHtml($child['name']); ?>
                                        </a>
                                    </li>
                                <?php endforeach; ?>
                            </ul>
                        <?php endif; ?>
                    </li>
                <?php endforeach; ?>
            <?php endif; ?>
            <!-- back to main gallery -->
            <li>
                <a href="<?php echo $baseUrl; ?>" class="clickable"><?php echo $this->__("Back to main gallery"); ?></a>
            </li>
            <!-- back to main gallery -->
        </ul>
    </div>
</div>