<?php
/** @var Zolago_Solrsearch_Helper_Data $helperZSS */
$helperZSS = Mage::helper('zolagosolrsearch');
?>
<div class="current-search">
    <h1>
        <?php if($helperZSS->getSolrRealQ() != $helperZSS->getQueryText()): ?>
           <?php echo $helperZSS->__("You're looking for: "); ?>
        <?php else: ?>
            <?php if($helperZSS->getNumFound()): ?>
                <?php echo $helperZSS->__("Search result for: "); ?>
            <?php else: ?>
                <?php echo $helperZSS->__("No search results found for"); ?>
            <?php endif; ?>
        <?php endif; ?>
        &bdquo;<?php echo $helperZSS->getQueryText(); ?>&rdquo;
    </h1>
    <?php if($helperZSS->getSolrRealQ() != $helperZSS->getQueryText()): ?>
        <?php if($helperZSS->getNumFound()): ?>
            <p class="found-product"><?php echo $helperZSS->__("Do You mean:");?> <strong><?php echo $helperZSS->getSolrRealQ(); ?>?</strong></p>
        <?php endif; ?>
    <?php endif; ?>

    <?php if($helperZSS->getNumFound()): ?>
        <p>
            <?php
            $str = "Found: %s products";
            $str = $helperZSS->getNumFound() == 2 ? "Found: 2 products" : $str;
            $str = $helperZSS->getNumFound() == 1 ? "Found: 1 product" : $str;
            ?>
            <?php echo $helperZSS->__($str, $helperZSS->getNumFound()); ?>
            <?php if($helperZSS->getSolrRealQ() != $helperZSS->getQueryText()): ?>
                <?php echo $helperZSS->__("for &quot;%s&quot;", $helperZSS->getSolrRealQ()); ?>
            <?php endif; ?>
            <span id="category-cnt-wrapper"> <?php echo $helperZSS->__("in"); ?> <span id="category-cnt"></span> <?php echo $helperZSS->__("categories"); ?></span>
        </p>
    <?php else: ?>
        <div id="search-page-empty">
            <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('search-page-empty')->toHtml(); ?>
        </div>
    <?php endif; ?>
</div>
<script>
    jQuery(document).ready(function(){
        var cnt = jQuery('#filter_category dl dd').length;
        if(cnt >= 2) {
            jQuery('#category-cnt').html(cnt);
            jQuery('#category-cnt-wrapper').show();
        } else {
            jQuery('#category-cnt-wrapper').hide();
        }
    });
</script>