<?php
/** @var Zolago_Solrsearch_Helper_Data $helperZSS */
$helperZSS = Mage::helper('zolagosolrsearch');

/** @var Zolago_Dropship_Model_Vendor $vendor */
$vendor = Mage::helper('umicrosite')->getCurrentVendor();

?>
<div class="current-search">
    <h1>
        <?php if($helperZSS->getSolrRealQ() == $helperZSS->getQueryText()): ?>
            <?php echo $helperZSS->__('Wyniki wyszukiwania dla:');//@todo translate ?>
            <span id="query-text" class="uppercase"><?php echo $helperZSS->getQueryText(); ?></span>
            <span id="query-text-iks">
                <a href="<?php echo $helperZSS->getRemoveQueryTextUrl(); ?>" class="fa fa-times active-filter-label iks"></a>
            </span>
            <?php if($helperZSS->canShowCurrentCategorySearch()): ?>
                <?php echo $helperZSS->__('w kategorii'); //@todo translate ?>
                <span id="category-text" class="uppercase"><?php echo $helperZSS->getCurrentCategoryString(); ?></span>
                <span id="category-text-iks">
                    <a href="<?php echo $helperZSS->getRemoveCurrentCategoryUrl(); ?>" class="fa fa-times active-filter-label iks"></a>
                </span>
            <?php endif; ?>
            <?php if($helperZSS->canShowVendor()): ?>
                <?php echo $vendor->isBrandshop() ? $helperZSS->__('w sklepie') : $helperZSS->__("dla sprzedawcy"); ?>
                <span id="vendor-text" class="uppercase"><?php echo $helperZSS->getVendorString(); ?></span>
                <span id="vendor-text-iks">
                    <a href="<?php echo $helperZSS->getRemoveVendorUrl(); ?>" class="fa fa-times active-filter-label iks"></a>
                </span>
            <?php endif; ?>
        <?php else: ?>

        <?php endif; ?>

    </h1>

    <?php if($helperZSS->getNumFound()): ?>
        <p>
            <?php
            $str = "Found: %s products";
            $str = $helperZSS->getNumFound() == 2 ? "Found: 2 products" : $str;
            $str = $helperZSS->getNumFound() == 1 ? "Found: 1 product" : $str;
            ?>
            <?php echo $helperZSS->__($str, $helperZSS->getNumFound()); ?>
            <?php if($helperZSS->getSolrRealQ() != $helperZSS->getQueryText()): ?>
                <?php echo $helperZSS->__("for &quot;%s&quot;", $helperZSS->getSolrRealQ()); ?>
            <?php endif; ?>
            <span id="category-cnt-wrapper"> <?php echo $helperZSS->__("in"); ?> <span id="category-cnt"></span> <?php echo $helperZSS->__("categories"); ?></span>
        </p>
    <?php else: ?>
        <div id="search-page-empty">
            <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('search-page-empty')->toHtml(); ?>
        </div>
    <?php endif; ?>
</div>
<script>
    jQuery(document).ready(function(){
        var cnt = jQuery('#filter_category dl dd').length;
        if(cnt >= 2) {
            jQuery('#category-cnt').html(cnt);
            jQuery('#category-cnt-wrapper').show();
        } else {
            jQuery('#category-cnt-wrapper').hide();
        }
    });
</script>
<style>
    #query-text, #category-text {
        font-family: latoblack;
    }

    #query-text-iks {
        position: relative;
    }

    .iks {
        border: 1px solid #ededed;
        font-weight: normal;
        color: #949494 !important;
        font-size: 11px;
        position: absolute;
        padding: 0px 3px 0 3px;
        line-height: 13px;
        text-decoration: none;
        font-family: FontAwesome;
        font-style: normal;
        -webkit-font-smoothing: antialiased;
        vertical-align: baseline;
        border-radius: .25em;
        text-align: center;
    }
</style>