<?php
$_categoryBlock = Mage::getBlockSingleton('zolagomodago/catalog_category');
/** @var Zolago_Solrsearch_Helper_Data $_helperZSS */
$_helperZSS = Mage::helper('zolagosolrsearch');


 ?>
<div class="wrapp-section bg-w" style="border: none;">
    <div class="container-fluid">
        <div id="block-current-search" class="row ">
            <div id="view-current-search" class="col-sm-12">
                <div class="current-search">

                    <h1>
                        <?php echo $this->__("Search result for: "); ?>
                        <strong>
                            <?php echo $this->getQueryString(); ?>
                        </strong>
                    </h1>

                    <?php if($_helperZSS->getNumFound()): ?>
                        <p><?php echo $this->__("Found: %s products", $_helperZSS->getNumFound()); ?></p>
                    <?php else: ?>
                        <span class="no-result" style="padding-bottom: 10px;"><?php echo $this->__("No results"); ?></span>
                        <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('search-page-empty')->toHtml(); ?>
                    <?php endif; ?>

<!--                    <a href="--><?php //echo $_categoryBlock->getMoveUpUrl(); ?><!--"-->
<!--                       class="backToCategory underline visible-xs">--><?php //echo $this->__("Go up"); ?><!--</a>-->
                </div>
            </div>
        </div>
    </div>
</div>