<?php
/** @var $this Zolago_Solrsearch_Block_Search_View */
/** @var $this Zolago_Solrsearch_Block_Catalog_Product_List_Header_Search */

$_categoryBlock = Mage::getBlockSingleton('zolagomodago/catalog_category');
/** @var Zolago_Solrsearch_Helper_Data $_helperZSS */
$_helperZSS = Mage::helper('zolagosolrsearch');


 ?>
<div class="wrapp-section bg-w" style="border: none;">
    <div class="container-fluid">
        <div id="block-current-search" class="row ">
            <div id="view-current-search" class="col-sm-12">
                <div class="current-search">

                    <h1>
                        <?php if($_helperZSS->getSolrRealQ() != $this->getQueryString()): ?>
                            <?php echo $this->__("You're looking for: "); ?>
                        <?php else: ?>
                            <?php echo $this->__("Search result for: "); ?>
                        <?php endif; ?>
                        <strong>
                            <?php echo $this->getQueryString(); ?>
                        </strong>
                    </h1>
                    <?php if($_helperZSS->getSolrRealQ() != $this->getQueryString()): ?>
                        <?php if($_helperZSS->getIsNoResult()): ?>
                            <p class="found-product"><?php echo $this->__("Do You mean:");?> <strong><?php echo $_helperZSS->getSolrRealQ(); ?>?</strong></p>
                        <?php endif; ?>
                    <?php endif; ?>

                    <?php if($_helperZSS->getIsNoResult()): ?>
                        <p>
                            <?php echo $this->__("Found: %s products", $_helperZSS->getNumFound()); ?><span id="found-dot">.</span>
                            <?php if($_helperZSS->getSolrRealQ() != $this->getQueryString()): ?>
                                <?php echo $this->__("for &quot;%s&quot;", $_helperZSS->getSolrRealQ()); ?>
                            <?php endif; ?>
                            <span id="category-cnt-wrapper"> <?php echo $this->__("in"); ?> <span id="category-cnt"></span> <?php echo $this->__("categories"); ?>.</span>
                        </p>
                    <?php else: ?>
                        <span class="no-result" style="padding-bottom: 10px;"><?php echo $this->__("No results"); ?></span>
                        <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('search-page-empty')->toHtml(); ?>
                    <?php endif; ?>

<!--                    <a href="--><?php //echo $_categoryBlock->getMoveUpUrl(); ?><!--"-->
<!--                       class="backToCategory underline visible-xs">--><?php //echo $this->__("Go up"); ?><!--</a>-->
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    jQuery(document).ready(function(){
        var cnt = jQuery('#filter_category dl dd').length;
        if(cnt >= 2) {
            jQuery('#category-cnt').html(cnt);
            jQuery('#category-cnt-wrapper').show();
            jQuery('#found-dot').hide();
        } else {
            jQuery('#category-cnt-wrapper').hide();
        }
    });
</script>