<?php
/** @var $this Zolago_Solrsearch_Block_Search_View */
/** @var $this Zolago_Solrsearch_Block_Catalog_Product_List_Header_Search */

$_categoryBlock = Mage::getBlockSingleton('zolagomodago/catalog_category');
/** @var Zolago_Solrsearch_Helper_Data $helperZSS */
$helperZSS = Mage::helper('zolagosolrsearch');

/** @var Zolago_Dropship_Model_Vendor $vendor */
$vendor = Mage::helper('umicrosite')->getCurrentVendor();
$isBrandshop = $vendor ? $vendor->isBrandshopType() : null;

 ?>
<header id="header-main-search">
    <div class="wrapp-section bg-w">
        <div class="container-fluid">
            <div id="block-current-search" class="row">
                <div id="view-current-search" class="col-sm-12">
                    <?php if(!$vendor): ?>

                        <div id="breadcrumbs-header">
                            <?php echo $this->getChildHtml('zolagocatalog_breadcrumbs'); ?>
                        </div>

                        <div class="current-search">
                            <h1>
                                <?php if($helperZSS->getSolrRealQ() != $this->getQueryString()): ?>
                                    <?php echo $this->__("You're looking for: "); ?>
                                <?php else: ?>
                                    <?php echo $this->__("Search result for: "); ?>
                                <?php endif; ?>
                                <strong>
                                    <?php echo $this->getQueryString(); ?>
                                </strong>
                            </h1>
                            <?php if($helperZSS->getSolrRealQ() != $this->getQueryString()): ?>
                                <?php if($helperZSS->getNumFound()): ?>
                                    <p class="found-product"><?php echo $this->__("Do You mean:");?> <strong><?php echo $helperZSS->getSolrRealQ(); ?>?</strong></p>
                                <?php endif; ?>
                            <?php endif; ?>

                            <?php if($helperZSS->getNumFound()): ?>
                                <p>
                                    <?php echo $this->__("Found: %s products", $helperZSS->getNumFound()); ?><span id="found-dot">.</span>
                                    <?php if($helperZSS->getSolrRealQ() != $this->getQueryString()): ?>
                                        <?php echo $this->__("for &quot;%s&quot;", $helperZSS->getSolrRealQ()); ?>
                                    <?php endif; ?>
                                    <span id="category-cnt-wrapper"> <?php echo $this->__("in"); ?> <span id="category-cnt"></span> <?php echo $this->__("categories"); ?>.</span>
                                </p>
                            <?php else: ?>
                                <span class="no-result" style="padding-bottom: 10px;"><?php echo $this->__("No results"); ?></span>
                                <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('search-page-empty')->toHtml(); ?>
                            <?php endif; ?>
                        </div>
                        <div id="active-filters-wrapper">
                            <?php echo $this->getChildHtml('solrsearch_product_list_active'); ?>
                        </div>
                    <?php else: ?>
                        tutaj header jak jest vendor
                    <?php endif; ?>
                </div>
            </div>
        </div>
    </div>
</header>
<script>
    jQuery(document).ready(function(){
        var cnt = jQuery('#filter_category dl dd').length;
        if(cnt >= 2) {
            jQuery('#category-cnt').html(cnt);
            jQuery('#category-cnt-wrapper').show();
            jQuery('#found-dot').hide();
        } else {
            jQuery('#category-cnt-wrapper').hide();
        }
    });
</script>