<?php
$element = $this->getElement();
$wrapperClass = $this->getElement()->getData("wrapper_class");
$wC = !empty($wrapperClass) ? $wrapperClass : "col-md-10";
?>

<div class="form-group"<?php echo ($element->getType()=="hidden" ? " style=\"display:none;\"" : "") ?> >
    <?php if($element->getType() == "link") : ?>
        <div class="<?php echo $wC;  ?>" id="<?php echo $element->getName(); ?>">
            <a href="<?php echo $this->getElement()->getData('url'); ?>"><?php echo $this->getElement()->getData('inside'); ?></a>
        </div>
    <?php else: ?>
        <label class="col-md-2 control-label"><?php echo $element->getLabelHtml();?></label>
        <div class="<?php echo $wC;  ?>"><?php echo $element->getElementHtml(); ?></div>
    <?php endif;?>
</div>
