<?php
$element = $this->getElement();
$formGroupWrapperClass = $this->getElement()->getData("form_group_wrapper_class");
$labelWrapperClass = $this->getElement()->getData("label_wrapper_class");
$LwC = !empty($labelWrapperClass) ? $labelWrapperClass : "col-md-2";

$wrapperClass = $this->getElement()->getData("wrapper_class");
$wC = !empty($wrapperClass) ? $wrapperClass : "col-md-10";
?>

<div class="form-group <?php echo $formGroupWrapperClass; ?>"<?php echo ($element->getType()=="hidden" ? " style=\"display:none;\"" : "") ?> >
    <?php if($element->getType() == "link") : ?>
        <div class="<?php echo $wC;  ?>" id="<?php echo $element->getName(); ?>">
            <a href="<?php echo $this->getElement()->getData('url'); ?>"><?php echo $this->getElement()->getData('inside'); ?></a>
        </div>
    <?php else: ?>
        <label class="<?php echo $LwC;  ?> control-label"><?php echo $element->getLabelHtml();?></label>
        <div class="<?php echo $wC;  ?>"><?php echo $element->getElementHtml(); ?></div>
    <?php endif;?>
</div>
