<?php /** @var $this Zolago_Sizetable_Block_Dropship_Sizetable_Assign */ ?>
<div class="container">
	<div class="row">
		<form class="form-horizontal row-border" id="sizetableAssignForm" action="<?php echo $this->getAction(); ?>" method="post">
			<input type="hidden" name="vendor_id" value="<?php echo $this->getVendorId(); ?>" />
			<select name="brand_id">
				<?php foreach($this->getBrands() as $value=>$label): ?>
					<option value="<?php echo $value; ?>"><?php echo $label; ?></option>
				<?php endforeach; ?>
			</select>
			<select name="attribute_set_id">
				<?php foreach($this->getAttributeSets() as $value=>$label): ?>
					<option value="<?php echo $value; ?>"><?php echo $label; ?></option>
				<?php endforeach; ?>
			</select>
			<input type="submit" />
		</form>
	</div>
</div>