<?php /** @var $this Zolago_Sizetable_Block_Dropship_Sizetable_Edit */
$_helper = Mage::helper('zolagosizetable');
$stores = $this->getAllowedStores();

$defaultStoreId = Mage_Catalog_Model_Abstract::DEFAULT_STORE_ID;

$locale = Mage::app()->getLocale()->getLocaleCode();
$sizetable = $this->getSizeTable();
$templates = $this->getSizeTablesTemplates();
//$anyTemplates = !empty($templates);
$anyTemplates = array();
$cssPath = "/skin/frontend/modago/default/css/sizeTableStyle.css";

//$css = $this->getSizeTablesStylesForJs();

$tinyMCEKinds = array("C", "A", "B");

?>
<script src="<?php echo $this->getUrl('skin/frontend/default/udropship/js/plugins/tinymce',array('_secure'=> $this->getRequest()->isSecure())); ?>tinymce.min.js"></script>
<script
	src="<?php echo $this->getUrl('skin/frontend/default/udropship/js/plugins/tinymce',array('_secure' => $this->getRequest()->isSecure())); ?>jquery.tinymce.min.js"></script>
<script>
	var tinymceOptions = {
			imageupload_url: "<?php echo $this->getImageUploadAction(); ?>",
			imageupload_translations: {
				title: '<?php echo $this->__("Upload image"); ?>',
				choose: '<?php echo $this->__("Select a file"); ?>',
				upload: '<?php echo $this->__("Upload"); ?>',
				cancel: '<?php echo $this->__("Cancel"); ?>'
			},
			skin: 'light',
			height: 300,
			plugins: [
				"advlist autolink lists link image charmap preview anchor textcolor",
				"searchreplace visualblocks code",
				"insertdatetime table contextmenu paste imageupload<?php echo $anyTemplates ?  " template" : "" ?>"
			],
			toolbar: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | "+
			"bullist numlist outdent indent | link image imageupload<?php echo $anyTemplates ? " | template" : "" ?>",
			relative_urls: false,
			<?php if($anyTemplates): ?>
			templates: [
				<?php foreach($templates as $tpl): ?>
				{title: '<?php echo $tpl['title'] ?>', description: '', content: '<?php echo $tpl['content'] ?>'},
				<?php endforeach ?>
			],
			<?php endif; ?>
			<?php if($locale != 'en_US'): ?>language: "<?php echo $locale; ?>" <?php endif; ?>
		};
	jQuery(function ($) {
		tinymce.init(jQuery.extend(tinymceOptions,{
			selector: '.tinymce',
			content_css: '<?php echo $cssPath; ?>'
		}));


		var form = $("#sizetableForm");
		new Zolago.formIntegrator(form);
		var validator = form.submit(function () {
			tinymce.triggerSave();
		}).validate({
			ignore: "",
			rules: {
				name: "required",
				"default_value": "required"
			}
		});
		validator.focusInvalid = function () {
			// put focus on tinymce on submit validation
			try {
				var toFocus = $(this.findLastActive() || this.errorList.length && this.errorList[0].element || []);
				if (toFocus.is("textarea")) {
					tinymce.get(toFocus.attr("id")).getBody().focus();
				} else {
					toFocus.filter(":visible").focus();
				}
			} catch (e) {
				// ignore IE throwing errors when focusing hidden elements
			}
		}
	});
</script>
<div class="container">
	<?php
	if ($sizetable):
		echo $this->getChildHtml('sizetable_edit_header_edit');
	else:
		echo $this->getChildHtml("sizetable_edit_header_new");
	endif;
	?>
	<div class="row">
		<form class="form-horizontal row-border" id="sizetableForm" action="<?php echo $this->getAction(); ?>" method="post">
			<?php echo $this->getLayout()->getBlock('formkey')->toHtml(); ?>
			<?php if ($sizetable): ?>
				<input type="hidden" name="sizetable_id" value="<?php echo $sizetable['sizetable_id']; ?>"/>
			<?php endif; ?>

            <!--Default Size Table-->
			<div class="col-md-12">
				<div class="widget box">
					<div class="widget-header">
                        <h4><i class="icon-reorder"></i> <?php echo $_helper->__("Default values"); ?></h4>
                    </div>
					<div class="widget-content">
						<div class="form-group">
							<label class="col-md-2 control-label" for="name"><?php echo $_helper->__("Name"); ?>
								<span class="required">*</span>
							</label>
							<div class="col-md-10">
								<input type="text" name="name" id="name" class="form-control required-entry" <?php if ($sizetable): ?>value="<?php echo $sizetable['name']; ?>"<?php endif; ?>>
							</div>
						</div>
						<div class="form-group">
                            <div class="col-md-12">
                                <div class="alert alert-info fade in">
                                    <?php echo $_helper->__("Default size table"); ?>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <?php $defaultValue = !empty($sizetable['default_value']) ? unserialize($sizetable['default_value']) : $sizetable['default_value']; ?>
                            <label class="col-md-2 control-label" for="name"><?php echo $_helper->__("Header"); ?>
                                <span class="required">*</span>
                            </label>

                            <div class="col-md-10">
                                <input type="text"
                                       name="default_value[title]"
                                       id="default_value_title"
                                       class="form-control"
                                       value="<?php if(isset($defaultValue["title"])): ?><?php echo $defaultValue["title"]; ?><?php endif; ?>"
                                    />
                            </div>
                        </div>
						<?php $tds = range(0, 15); $trs = range(0, 19); ?>
                        <div class="form-group">
                            <label class="col-md-2 control-label" for="name">
								<?php echo $_helper->__("Size table"); ?>
							</label>
							<div class="col-md-10">
								<table>
									<?php foreach ($trs as $i => $tr): ?>
										<tr>
											<?php foreach ($tds as $j => $td): ?>
												<td>
													<?php if($j == 0): ?>
														<input <?php if($j == 0): ?>style="background-color: #f2f1f0;"<?php endif; ?> type="text" size="18"
															name="default_value[table][<?php echo $i; ?>][<?php echo $j; ?>]"
															   value="<?php if(isset($defaultValue["table"])): ?><?php echo $defaultValue["table"][$i][$j]; ?><?php endif; ?>"
															/>
														<?php else: ?>
														<input type="text" <?php if($i == 0): ?>style="background-color: #f2f1f0;"<?php endif; ?> size="6"
															   name="default_value[table][<?php echo $i; ?>][<?php echo $j; ?>]"
															   value="<?php if(isset($defaultValue["table"])): ?><?php echo $defaultValue["table"][$i][$j]; ?><?php endif; ?>"
															/>
													<?php endif; ?>

												</td>
											<?php endforeach; ?>
										</tr>
									<?php endforeach; ?>
								</table>
							</div>

                        </div>
						<div class="form-group">
							<label class="col-md-2 control-label" for="name">
								<?php echo $_helper->__("Content"); ?>
							</label>

							<div class="col-md-10">
								<?php foreach ($tinyMCEKinds as $i => $tinyMCEKind): ?>
									<div class="col-md-<?php if ($i == 0): ?>12<?php else: ?>6<?php endif; ?>">
                                            <textarea name="default_value[<?php echo $tinyMCEKind; ?>]"
													  id="sizetable_<?php echo $defaultStoreId; ?>_<?php echo $tinyMCEKind; ?>"
													  class="form-control tinymce">
                                                <?php if (isset($defaultValue[$tinyMCEKind])) echo $defaultValue[$tinyMCEKind]; ?>
                                            </textarea>
									</div>
								<?php endforeach; ?>
								<?php unset($i, $tinyMCEKind); ?>
							</div>
						</div>
					</div>
				</div>
			</div>
            <!--Default Size Table-->

            <!--Translations per store-->
			<div class="col-md-12">
				<div class="widget box widget-closed">
					<div class="widget-header">
						<h4><i class="icon-reorder"></i> <?php echo $_helper->__("Size tables translations"); ?></h4>
						<div class="toolbar no-padding">
							<div class="btn-group">
								<span class="btn btn-xs widget-collapse"><i class="icon-angle-down"></i></span>
							</div>
						</div>
					</div>
					<div class="widget-content">
                        <div class="col-md-12">
                            <div class="alert alert-warning fade in align-center">
                                <?php echo $_helper->__("If you don't specify size table translations for one of the store views then default one will be displayed"); ?>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="tabbable tabbable-custom tabs-left">
                                    <ul class="nav nav-tabs tabs-left" id="sizeTableTabsEditor">
                                        <?php foreach ($stores as $n => $store): ?>
                                            <li class="<?php if ($n == 0): ?>active<?php endif; ?>">
                                                <a data-toggle="tab" href="#sizetable_tab_<?php echo $store['store_id']; ?>">
                                                    <?php echo $_helper->__("Size table for") . " <span class='blue'>" . $store['name'] . "</span>"; ?>
                                                </a>
                                            </li>
                                        <?php endforeach; ?>
                                    </ul>
                                    <div class="tab-content">
                                        <?php $sizeTableStoresData = $sizetable['sizetable']; ?>
                                        <?php foreach ($stores as $i => $store): ?>
                                            <?php $sizeTablePerStore = isset($sizeTableStoresData[$store['store_id']]) ? unserialize($sizeTableStoresData[$store['store_id']]) : false; ?>
											<?php //Zend_Debug::dump($sizeTablePerStore); ?>
                                            <div id="sizetable_tab_<?php echo $store['store_id']; ?>" class="tab-pane <?php if ($i == 0): ?> active<?php endif; ?>">
                                                <div class="container">
                                                    <div class="form-group">
                                                        <label class="col-md-1 control-label" for="title">
                                                            <?php echo $_helper->__("Header"); ?>
                                                        </label>
                                                        <div class="col-md-11">
                                                            <input type="text"
                                                                   name="sizetable[<?php echo $store['store_id']; ?>][title]"
                                                                   id="title_<?php echo $store['store_id']; ?>"
                                                                   class="form-control"
                                                                   value="<?php if (isset($sizeTablePerStore["title"])): ?><?php echo $sizeTablePerStore["title"]; ?><?php endif; ?>"
                                                                />
                                                        </div>
                                                    </div>
													<?php $tds = range(0, 15); $trs = range(0, 19); ?>
													<div class="form-group">
														<label class="col-md-2 control-label" for="name">
															<?php echo $_helper->__("Size table"); ?>
														</label>
														<div class="col-md-10">
															<table>
																<?php foreach ($trs as $i => $tr): ?>
																	<tr>
																		<?php foreach ($tds as $j => $td): ?>
																			<td>
																				<?php if($j == 0): ?>
																					<input <?php if($j == 0): ?>style="background-color: #f2f1f0;"<?php endif; ?> type="text" size="18"
																						   name="sizetable[<?php echo $store['store_id']; ?>][table][<?php echo $i; ?>][<?php echo $j; ?>]"
																						   value="<?php if(isset($sizeTablePerStore["table"])): ?><?php echo $sizeTablePerStore["table"][$i][$j]; ?><?php endif; ?>"
																					/>
																				<?php else: ?>
																					<input type="text" <?php if($i == 0): ?>style="background-color: #f2f1f0;"<?php endif; ?> size="6"
																						   name="sizetable[<?php echo $store['store_id']; ?>][table][<?php echo $i; ?>][<?php echo $j; ?>]"
																						   value="<?php if(isset($sizeTablePerStore["table"])): ?><?php echo $sizeTablePerStore["table"][$i][$j]; ?><?php endif; ?>"
																					/>
																				<?php endif; ?>

																			</td>
																		<?php endforeach; ?>
																	</tr>
																<?php endforeach; ?>
																<?php unset($i, $j); ?>
															</table>
														</div>

													</div>
                                                    <div class="form-group">
                                                        <label class="col-md-1 control-label" for="sizetable_<?php echo $store['store_id']; ?>">
                                                            <?php echo $_helper->__("Content"); ?>
                                                        </label>
                                                        <div class="col-md-11">
                                                            <?php foreach ($tinyMCEKinds as $j => $tinyMCEKind): ?>
                                                                <div class="col-md-<?php if ($j == 0): ?>12<?php else: ?>6<?php endif; ?>">
                                                                <textarea name="sizetable[<?php echo $store['store_id']; ?>][<?php echo $tinyMCEKind; ?>]"
                                                                          id="sizetable_<?php echo $store['store_id']; ?>_<?php echo $tinyMCEKind; ?>"
                                                                          class="form-control tinymce">
                                                                    <?php if (isset($sizeTablePerStore[$tinyMCEKind])): ?><?php echo $sizeTablePerStore[$tinyMCEKind]; ?><?php endif; ?>
                                                                </textarea>
                                                                </div>
                                                            <?php endforeach; ?>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        <?php endforeach; ?>
                                    </div>
                                </div>
                            </div>
                        </div>
					</div>
				</div>
			</div>
            <!--Translations per store-->

			<div class="col-md-12">
				<div class="form-actions">
					<input type="submit" value="<?php echo $_helper->__("Save"); ?>" class="btn btn-primary pull-right">
					<a href="<?php echo $this->getUrl("udropship/sizetable"); ?>" class="btn pull-right">
						<?php echo $_helper->__("Cancel"); ?>
					</a>
				</div>
			</div>
		</form>
	</div>
</div>