<?php
/** @var $this Zolago_Sizetable_Block_Dropship_Sizetable_List */
/** @var $_helper Zolago_Sizetable_Helper_Data */
$_helper = Mage::helper('zolagosizetable');
$sizeTables = $this->getSizeTables();
?>
<div class="row">
	<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
		<table
			class="table table-striped table-bordered table-checkable table-highlight-head table-no-inner-border table-hover"
			style="margin-top: 15px;">
			<thead>
			<tr>
				<th class="checkbox-column">
					<div class="checker"><span><input type="checkbox" class="uniform"></span></div>
				</th>
				<th><?php echo $_helper->__("Name"); ?></th>
				<th class="align-center" width="100"><?php echo $_helper->__("Actions"); ?></th>
			</tr>
			</thead>
			<tbody>
			<?php foreach ($sizeTables as $id => $name): ?>
				<tr>
					<td class="checkbox-column">
						<div class="checker"><span class="checked"><input type="checkbox" class="uniform" name="sizetable" value="<?php echo $id; ?>"></span>
						</div>
					</td>
					<td>
						<?php echo $name; ?>
					</td>
					<td class="align-center"><span class="btn-group"> <a href="<?php echo $this->getUrl("udropship/sizetable/edit").'sizetable_id/'.$id; ?>"
					                                                     class="btn btn-xs bs-tooltip" title=""
					                                                     data-original-title="<?php echo $_helper->__("Edit"); ?>"><i
									class="icon-pencil"></i></a> <a href="<?php echo $this->getUrl("udropship/sizetable/delete").$id; ?>"
					                                                class="btn btn-xs bs-tooltip" title=""
					                                                data-original-title="<?php echo $_helper->__("Delete"); ?>"><i
									class="icon-trash"></i></a> </span></td>
				</tr>
			<?php endforeach; ?>
			</tbody>
		</table>
	</div>
</div>