
<div class="content-wrapper">
    <div class="container hidden-xs">
        <div id="carousel-top-generic" class="carousel slide border1px-rd2-img-gray" data-ride="carousel">
            <!-- Indicators -->
            <ol class="carousel-indicators" id="carousel-top-indicators">
                <li data-target="#carousel-top-generic" data-slide-to="0" class="active"></li>
                <li data-target="#carousel-top-generic" data-slide-to="1"></li>
            </ol>

            <!-- Wrapper for slides -->
            <div class="carousel-inner">
                <div class="item active">
                    <img src="<?php echo $this->getSkinUrl('images/banner1.jpg'); ?>" alt="">
                    <div class="carousel-caption">
                        <a href="">przeglądaj stylizacje<img src="<?php echo $this->getSkinUrl('images/ico-green-arrow-small.png'); ?>" alt=""/></a>
                        <a class="margin-top-20px" href="">wejdź do sklepu<img src="<?php echo $this->getSkinUrl('images/ico-green-arrow-small.png'); ?>" alt=""/></a>
                    </div>
                </div>
                <div class="item">
                    <img src="<?php echo $this->getSkinUrl('images/banner1.jpg'); ?>" alt="">
                    <div class="carousel-caption">
                        <a href="">przeglądaj stylizacje<img src="<?php echo $this->getSkinUrl('images/ico-green-arrow-small.png'); ?>" alt=""/></a>
                        <a class="margin-top-20px" href="">wejdź do sklepu<img src="<?php echo $this->getSkinUrl('images/ico-green-arrow-small.png'); ?>" alt=""/></a>
                    </div>
                </div>
            </div>

        </div>
    </div>

    <div class="container visible-xs">
        <div class="row">
            <div class="col-xs-12">

                <div id="carousel-top-mobile-generic" class="carousel slide" data-ride="carousel">
                    <!-- Indicators -->
                    <ol class="carousel-indicators" id="carousel-top-mobile-indicators">
                        <li data-target="#carousel-top-mobile-generic" data-slide-to="0" class="active"></li>
                        <li data-target="#carousel-top-mobile-generic" data-slide-to="1"></li>
                    </ol>

                    <!-- Wrapper for slides -->
                    <div class="carousel-inner">
                        <div class="item active">
                            <img class="border1px-rd2-img-gray" src="<?php echo $this->getSkinUrl('images/bannermobile1.jpg'); ?>" alt="">
                            <div class="carousel-caption">
                            </div>
                        </div>
                        <div class="item">
                            <img class="border1px-rd2-img-gray" src="<?php echo $this->getSkinUrl('images/bannermobile1.jpg'); ?>" alt="">
                            <div class="carousel-caption">
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
    <!--small banners-->
    <div class="container ">
        <div class="row hidden-xs visible-lg visible-md visible-sm small-banners-lg">
            <div class="col-lg-3 col-md-3 col-sm-3">
                <a href=""><img class="border1px-rd2-img-gray margin-10-top img-responsive" width="100%" src="<?php echo $this->getSkinUrl('images/banner-small-1.jpg'); ?>" alt=""/></a>
            </div>
            <div class="col-lg-3 col-md-3 col-sm-3">
                <a href=""><img class="border1px-rd2-img-gray margin-10-top img-responsive" width="100%" src="<?php echo $this->getSkinUrl('images/banner-small-2.jpg'); ?>" alt=""/></a>
            </div>
            <div class="col-lg-3 col-md-3 col-sm-3">
                <a href=""><img class="border1px-rd2-img-gray margin-10-top img-responsive" width="100%" src="<?php echo $this->getSkinUrl('images/banner-small-3.jpg'); ?>" alt=""/></a>
            </div>
            <div class="col-lg-3 col-md-3 col-sm-3">
                <a href=""><img class="border1px-rd2-img-gray margin-10-top img-responsive" width="100%" src="<?php echo $this->getSkinUrl('images/banner-small-4.jpg'); ?>" alt=""/></a>
            </div>
        </div>
        <div class="row visible-xs">
            <div class="col-xs-6 col-sm-6 col-md-6">
                <a href=""><img class="border1px-rd2-img-gray margin-10-top img-responsive" width="100%" src="<?php echo $this->getSkinUrl('images/banner-small-1.jpg'); ?>" alt=""/></a>
            </div>
            <div class="col-xs-6 col-sm-6 col-md-6">
                <a href=""><img class="border1px-rd2-img-gray margin-10-top img-responsive" width="100%" src="<?php echo $this->getSkinUrl('images/banner-small-2.jpg'); ?>" alt=""/></a>
            </div>
        </div>
        <div class="row visible-xs hidden-md hidden-sm">
            <div class="col-xs-6 col-sm-6 col-md-6">
                <a href=""><img class="border1px-rd2-img-gray margin-10-top img-responsive" width="100%" src="<?php echo $this->getSkinUrl('images/banner-small-3.jpg'); ?>" alt=""/></a>
            </div>
            <div class="col-xs-6 col-sm-6 col-md-6">
                <a href=""><img class="border1px-rd2-img-gray margin-10-top img-responsive" width="100%" src="<?php echo $this->getSkinUrl('images/banner-small-4.jpg'); ?>" alt=""/></a>
            </div>
        </div>
    </div>
</div>

<!--inspiracje-->
<div class="white-wrapper border1px-rd2-img-gray noborder-lft-rgt">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="inspiration-strips"></div>
                <h2 class="insp-h">inspiracje</h2>
            </div>
        </div>

        <div class="jcarousel-wrapper listComics">
            <div class="canvas-left"></div>
            <div class="jcarousel">
                <ul>
                    <li class="col-sm-3">
                        <a href="#" class="productItem-wrapper">
                            <img src="<?php echo $this->getSkinUrl('images/insp-1.jpg'); ?>" alt="...">
                            <span class="insp-carousel-title-bold">lady in the bushes</span>
                            <span class="insp-carousel-title-gray">Drugi wiersz opisu</span>
                            <span class="insp-carousel-seemore">zobacz &gt;</span>
                        </a>
                    </li>
                    <li class="col-sm-3">
                        <a href="#" class="productItem-wrapper">
                            <img src="<?php echo $this->getSkinUrl('images/insp-2.jpg'); ?>" alt="...">

                            <span class="insp-carousel-title-bold">lady in the bushes</span>
                            <span class="insp-carousel-title-gray">Drugi wiersz opisu</span>
                            <span class="insp-carousel-seemore">zobacz &gt;</span>
                        </a>
                    </li>
                    <li class="col-sm-3">
                        <a href="#" class="productItem-wrapper" data-json="c_01">

                            <img src="<?php echo $this->getSkinUrl('images/insp-3.jpg'); ?>" alt="...">
                            <span class="insp-carousel-title-bold">lady in the bushes</span>
                            <span class="insp-carousel-title-gray">Drugi wiersz opisu</span>
                            <span class="insp-carousel-seemore">zobacz &gt;</span>
                        </a>
                    </li>
                    <li class="col-sm-3">
                        <a href="#" class="productItem-wrapper" data-json="c_02">

                            <img src="<?php echo $this->getSkinUrl('images/insp-1.jpg'); ?>" alt="...">
                            <span class="insp-carousel-title-bold">lady in the bushes</span>
                            <span class="insp-carousel-title-gray">Drugi wiersz opisu</span>
                            <span class="insp-carousel-seemore">zobacz &gt;</span>
                        </a>
                    </li>
                    <li class="col-sm-3">
                        <a href="#" class="productItem-wrapper">

                            <img src="<?php echo $this->getSkinUrl('images/insp-1.jpg'); ?>" alt="...">
                            <span class="insp-carousel-title-bold">lady in the bushes</span>
                            <span class="insp-carousel-title-gray">Drugi wiersz opisu</span>
                            <span class="insp-carousel-seemore">zobacz &gt;</span>
                        </a>
                    </li>
                    <li class="col-sm-3">
                        <a href="#" class="productItem-wrapper">

                            <img src="<?php echo $this->getSkinUrl('images/insp-1.jpg'); ?>" alt="...">
                            <span class="insp-carousel-title-bold">lady in the bushes</span>
                            <span class="insp-carousel-title-gray">Drugi wiersz opisu</span>
                            <span class="insp-carousel-seemore">zobacz &gt;</span>
                        </a>
                    </li>
                    <li class="col-sm-3">
                        <a href="#" class="productItem-wrapper">

                            <img src="<?php echo $this->getSkinUrl('images/insp-1.jpg'); ?>" alt="...">
                            <span class="insp-carousel-title-bold">lady in the bushes</span>
                            <span class="insp-carousel-title-gray">Drugi wiersz opisu</span>
                            <span class="insp-carousel-seemore">zobacz &gt;</span>
                        </a>
                    </li>
                    <li class="col-sm-3">
                        <a href="#" class="productItem-wrapper">

                            <img src="<?php echo $this->getSkinUrl('images/insp-1.jpg'); ?>" alt="...">
                            <span class="insp-carousel-title-bold">lady in the bushes</span>
                            <span class="insp-carousel-title-gray">Drugi wiersz opisu</span>
                            <span class="insp-carousel-seemore">zobacz &gt;</span>
                        </a>
                    </li>
                </ul>
            </div>

            <a href="#" class="jcarousel-control-prev"></a>
            <a href="#" class="jcarousel-control-next"></a>

            <div class="canvas-right"></div>
        </div>

    </div>
</div>

<!--popular brands-->
<div class="content-wrapper">
    <div class="container popular-shops">
        <h3>najpopularniejsze sklepy</h3>
        <ul class="pop-shop-lst">
            <li><a href="#"><span class="pop-shop-img-wr"><img src="<?php echo $this->getSkinUrl('images/ck-logo-small.jpg'); ?>"
                                                               alt=""/></span><span>Calvin Klein &gt;</span></a></li>
            <li><a href="#"><span class="pop-shop-img-wr"><img src="<?php echo $this->getSkinUrl('images/ck-logo-small.jpg'); ?>"
                                                               alt=""/></span><span>Calvin Klein &gt;</span></a></li>
            <li><a href="#"><span class="pop-shop-img-wr"><img src="<?php echo $this->getSkinUrl('images/ck-logo-small.jpg'); ?>"
                                                               alt=""/></span><span>Calvin Klein &gt;</span></a></li>
        </ul>
        <ul class="pop-shop-lst">
            <li><a href="#"><span class="pop-shop-img-wr"><img src="<?php echo $this->getSkinUrl('images/ck-logo-small.jpg'); ?>"
                                                               alt=""/></span><span>Calvin Klein &gt;</span></a></li>
            <li><a href="#"><span class="pop-shop-img-wr"><img src="<?php echo $this->getSkinUrl('images/ck-logo-small.jpg'); ?>"
                                                               alt="<?php echo $this->getSkinUrl('images/ck-logo-small.jpg'); ?>"/></span><span>Calvin Klein &gt;</span></a></li>
            <li><a href="#"><span class="pop-shop-img-wr"><img src="<?php echo $this->getSkinUrl('images/ck-logo-small.jpg'); ?>"
                                                               alt="<?php echo $this->getSkinUrl('images/ck-logo-small.jpg'); ?>"/></span><span>Calvin Klein &gt;</span></a></li>
        </ul>
        <ul class="pop-shop-lst">
            <li><a href="#"><span class="pop-shop-img-wr"><img src="<?php echo $this->getSkinUrl('images/ck-logo-small.jpg'); ?>"
                                                               alt="<?php echo $this->getSkinUrl('images/ck-logo-small.jpg'); ?>"/></span><span>Calvin Klein &gt;</span></a></li>
            <li><a href="#"><span class="pop-shop-img-wr"><img src="<?php echo $this->getSkinUrl('images/ck-logo-small.jpg'); ?>"
                                                               alt="<?php echo $this->getSkinUrl('images/ck-logo-small.jpg'); ?>"/></span><span>Calvin Klein &gt;</span></a></li>
            <li><a href="#"><span class="pop-shop-img-wr"><img src="<?php echo $this->getSkinUrl('images/ck-logo-small.jpg'); ?>"
                                                               alt="<?php echo $this->getSkinUrl('images/ck-logo-small.jpg'); ?>"/></span><span>Calvin Klein &gt;</span></a></li>
        </ul>
        <ul class="pop-shop-lst hidden-xs ">
            <li><a href="#"><span class="pop-shop-img-wr"><img src="<?php echo $this->getSkinUrl('images/ck-logo-small.jpg'); ?>"
                                                               alt="<?php echo $this->getSkinUrl('images/ck-logo-small.jpg'); ?>"/></span><span>Calvin Klein &gt;</span></a></li>
            <li><a href="#"><span class="pop-shop-img-wr"><img src="<?php echo $this->getSkinUrl('images/ck-logo-small.jpg'); ?>"
                                                               alt="<?php echo $this->getSkinUrl('images/ck-logo-small.jpg'); ?>"/></span><span>Calvin Klein &gt;</span></a></li>
            <li><a href="#"><span class="pop-shop-img-wr"><img src="<?php echo $this->getSkinUrl('images/ck-logo-small.jpg'); ?>"
                                                               alt="<?php echo $this->getSkinUrl('images/ck-logo-small.jpg'); ?>"/></span><span>Calvin Klein &gt;</span></a></li>
        </ul>
        <ul class="pop-shop-lst hidden-xs hidden-md hidden-sm">
            <li><a href="#"><span class="pop-shop-img-wr"><img src="<?php echo $this->getSkinUrl('images/ck-logo-small.jpg'); ?>"
                                                               alt="<?php echo $this->getSkinUrl('images/ck-logo-small.jpg'); ?>"/></span><span>Calvin Klein &gt;</span></a></li>
            <li><a href="#"><span class="pop-shop-img-wr"><img src="<?php echo $this->getSkinUrl('images/ck-logo-small.jpg'); ?>"
                                                               alt="<?php echo $this->getSkinUrl('images/ck-logo-small.jpg'); ?>"/></span><span>Calvin Klein &gt;</span></a></li>
            <li><a href="#"><span class="pop-shop-img-wr"><img src="<?php echo $this->getSkinUrl('images/ck-logo-small.jpg'); ?>"
                                                               alt="<?php echo $this->getSkinUrl('images/ck-logo-small.jpg'); ?>"/></span><span>Calvin Klein &gt;</span></a></li>
        </ul>
        <ul class="pop-shop-lst hidden-xs hidden-md hidden-sm">
            <li><a href="#"><span class="pop-shop-img-wr"><img src="<?php echo $this->getSkinUrl('images/ck-logo-small.jpg'); ?>"
                                                               alt="<?php echo $this->getSkinUrl('images/ck-logo-small.jpg'); ?>"/></span><span>Calvin Klein &gt;</span></a></li>
            <li><a href="#"><span class="pop-shop-img-wr"><img src="<?php echo $this->getSkinUrl('images/ck-logo-small.jpg'); ?>"
                                                               alt="<?php echo $this->getSkinUrl('images/ck-logo-small.jpg'); ?>"/></span><span>Calvin Klein &gt;</span></a></li>
            <li><a href="#"><span class="pop-shop-img-wr"><img src="<?php echo $this->getSkinUrl('images/ck-logo-small.jpg'); ?>"
                                                               alt="<?php echo $this->getSkinUrl('images/ck-logo-small.jpg'); ?>"/></span><span>Calvin Klein &gt;</span></a></li>
        </ul>
        <ul class="pop-shop-lst hidden-xs">
            <li><a href="#"><span class="pop-shop-img-wr"><img src="<?php echo $this->getSkinUrl('images/ck-logo-small.jpg'); ?>"
                                                               alt="<?php echo $this->getSkinUrl('images/ck-logo-small.jpg'); ?>"/></span><span>Calvin Klein &gt;</span></a></li>
            <li><a href="#"><span class="pop-shop-img-wr"><img src="<?php echo $this->getSkinUrl('images/ck-logo-small.jpg'); ?>"
                                                               alt="<?php echo $this->getSkinUrl('images/ck-logo-small.jpg'); ?>"/></span><span>Calvin Klein &gt;</span></a></li>
            <li><a href="#"><span class="pop-shop-img-wr"><img src="<?php echo $this->getSkinUrl('images/ck-logo-small.jpg'); ?>"
                                                               alt="<?php echo $this->getSkinUrl('images/ck-logo-small.jpg'); ?>"/></span><span>Calvin Klein &gt;</span></a></li>
        </ul>
    </div>
    <a class="pop-shop-seemore" href="">zobacz więcej sklepów</a>
</div>

<!--last seen-->

<!--inspiracje-->
<div class="white-wrapper ">
    <div class="container last-seen">
        <h3>ostatnio oglądane:</h3>

        <div class="jcarousel-wrapper listComics">
            <div class="canvas-left"></div>
            <div class="jcarousel last-seen1">
                <ul class="last-seen-list">
                    <li class="col-sm-2">
                        <a href="#" class="productItem-wrapper">
                            <img src="<?php echo $this->getSkinUrl('images/last-seen-1.jpg'); ?>" alt="..." class="border1px-rd2-img-gray">
                            <span>ZARA krótki płaszcz z guzikami</span>
                        </a>
                    </li>
                    <li class="col-sm-2">
                        <a href="#" class="productItem-wrapper">
                            <img src="<?php echo $this->getSkinUrl('images/last-seen-2.jpg'); ?>" alt="..." class="border1px-rd2-img-gray">
                            <span>Zara krótki płaszcz z guzikami</span>
                        </a>
                    </li>
                    <li class="col-sm-2">
                        <a href="#" class="productItem-wrapper">
                            <img src="<?php echo $this->getSkinUrl('images/last-seen-1.jpg'); ?>" alt="..." class="border1px-rd2-img-gray">
                            <span>Zara krótki płaszcz z guzikami</span>
                        </a>
                    </li>
                    <li class="col-sm-2">
                        <a href="#" class="productItem-wrapper">
                            <img src="<?php echo $this->getSkinUrl('images/last-seen-2.jpg'); ?>" alt="..." class="border1px-rd2-img-gray">
                            <span>Zara krótki płaszcz z guzikami</span>
                        </a>
                    </li>
                    <li class="col-sm-2">
                        <a href="#" class="productItem-wrapper">
                            <img src="<?php echo $this->getSkinUrl('images/last-seen-1.jpg'); ?>" alt="..." class="border1px-rd2-img-gray">
                            <span>Zara krótki płaszcz z guzikami</span>
                        </a>
                    </li>
                    <li class="col-sm-2">
                        <a href="#" class="productItem-wrapper">
                            <img src="<?php echo $this->getSkinUrl('images/last-seen-2.jpg'); ?>" alt="..." class="border1px-rd2-img-gray">
                            <span>Zara krótki płaszcz z guzikami</span>
                        </a>
                    </li>
                    <li class="col-sm-2">
                        <a href="#" class="productItem-wrapper">
                            <img src="<?php echo $this->getSkinUrl('images/last-seen-1.jpg'); ?>" alt="..." class="border1px-rd2-img-gray">
                            <span>Zara krótki płaszcz z guzikami</span>
                        </a>
                    </li>
                    <li class="col-sm-2">
                        <a href="#" class="productItem-wrapper">
                            <img src="<?php echo $this->getSkinUrl('images/last-seen-2.jpg'); ?>" alt="..." class="border1px-rd2-img-gray">
                            <span>Zara krótki płaszcz z guzikami</span>
                        </a>
                    </li>
                    <li class="col-sm-2">
                        <a href="#" class="productItem-wrapper">
                            <img src="<?php echo $this->getSkinUrl('images/last-seen-1.jpg'); ?>" alt="..." class="border1px-rd2-img-gray">
                            <span>Zara krótki płaszcz z guzikami</span>
                        </a>
                    </li>
                    <li class="col-sm-2">
                        <a href="#" class="productItem-wrapper">
                            <img src="<?php echo $this->getSkinUrl('images/last-seen-2.jpg'); ?>" alt="..." class="border1px-rd2-img-gray">
                            <span>Zara krótki płaszcz z guzikami</span>
                        </a>
                    </li>
                    <li class="col-sm-2">
                        <a href="#" class="productItem-wrapper">
                            <img src="<?php echo $this->getSkinUrl('images/last-seen-1.jpg'); ?>" alt="..." class="border1px-rd2-img-gray">
                            <span>Zara krótki płaszcz z guzikami</span>
                        </a>
                    </li>
                    <li class="col-sm-2">
                        <a href="#" class="productItem-wrapper">
                            <img src="<?php echo $this->getSkinUrl('images/last-seen-2.jpg'); ?>" alt="..." class="border1px-rd2-img-gray">
                            <span>Zara krótki płaszcz z guzikami</span>
                        </a>
                    </li>
                </ul>
            </div>

            <a href="#" class="jcarousel-control-prev carousel-small-ctr-lt"></a>
            <a href="#" class="jcarousel-control-next carousel-small-ctr-gt"></a>

            <div class="canvas-right"></div>
        </div>

    </div>
</div>
