<div id="content" class="container-fluid">
    <div class="col-sm-12">
        <?php echo $this->getChildHtml('vendor.banner'); ?>
    </div>
</div>
<section id="bottom" class="bg-w">
    <div class="container-fluid">
        <div class="col-sm-12">
            <?php echo $this->getChildHtml('vendor.banner.inspiration'); ?>
        </div>
    </div>
</section>


<?php echo $this->getChildHtml('zolago_modago_home_popularvendors'); ?>
<?php echo $this->getChildHtml('zolago_modago_home_sliderlastseen'); ?>
