<?php /* @var $this Zolago_Payment_Block_Form*/  ?>
<?php $_providers = $this->getProviderCollection();?>
<?php $_i = 0;?>
<?php if ($_providers->count()):?>
<div class="selected_bank">
    <p><?php echo Mage::helper('zolagomodago')->__('Select your bank'); ?>:</p>
    <ul id="payment_form_<?php echo $this->getMethodCode() ?>">
		<?php foreach($_providers as $_provider):?>
		<?php $_code = $_provider->getCode();?>

		<?php $_id = $this->getMethodCode()."_".$_code;?>
        <li class="logo_01">
            <div class="form-group">
                <input type="radio"
                       <?php if($this->isChecked($_provider)):?>checked="checked" <?php endif;?>
                       id="<?php echo $_id;?>" name="payment[additional_information][provider]"
                       value="<?php echo $this->escapeHtml($_code);?>"
                       data-bank-name="<?php echo $this->escapeHtml($_provider->getName());?>"
                    />
                <label for="<?php echo $_id; ?>" class="clearfix">
                    <div class="payment-provider-logo-wrapper">
                        <img class="" src="<?php echo $this->getProviderLogoUrl($_provider); ?>" alt="<?php echo $this->escapeHtml($_provider->getName()); ?>"/>
                    </div>
                    <span class="hidden-xs"><?php echo $this->escapeHtml($_provider->getName());?></span>
                </label>
            </div>
        </li>
		<?php endforeach;?>

    </ul>
</div>
<?php endif; ?>
