<?php $hlp = Mage::helper('udropship') ?>
<?php $_item = $this->getItem() ?>
<?php $_oItem = $_item->getOrderItem() ?>
<tr class="border" id="udpo_item_<?php echo$_item->getId()?>">
    <td><?php echo $this->getColumnHtml($_item, 'name') ?></td>
    <td class="po-item-vendor"><?php echo Mage::helper('udpo')->getOrderItemVendorName($_item) ?></td>
    <td class="udpo_item_cost a-center" nowrap="true">
        <input style="width: 100px;" type="text" class="input-text qty-input" name="udpo[costs][<?php echo $_item->getId() ?>]" value="<?php echo $_item->getBaseCost()*1 ?>" onchange="udpoRecalcCosts(this)" />
    </td>
    <td class="udpo_item_qty"><?php echo $_item->getQty()*1 ?></td>
    <td class="udpo_item_rowcost last a-right" alt="<?php echo $_item->getBaseCost()*$_item->getQty() ?>"><?php echo $hlp->displayPrices($this->getOrder(), $_item->getBaseCost()*$_item->getQty()) ?></td>
</tr>

<script type="text/javascript">
//<![CDATA[
//]]>
</script>
