<form action="<?php echo $this->getFormUrl(); ?>" id="<?php echo $this->getHtmlId(); ?>" method="post" role="form" class="vendor-contact-form">
	<input name="form_key" type="hidden" value="<?php echo $this->getFormKey();?>">
	<input type="hidden" name="question[vendor_id]" value="<?php echo $this->getVendorId(); ?>">
	<input type="hidden" name="question[order_id]" value="<?php echo $this->getOrderId(); ?>">
	<input type="hidden" name="question[shipment_id]" value="<?php echo $this->getShipmentId(); ?>">
	<input type="hidden" name="redirect_referer" value="<?php echo $this->getRedirectReferer();?>">
	<input type="hidden" name="question[visibility]" value="0">
	<?php if($this->isLoggedIn()):?>
		<input type="hidden" name="question[customer_name]" value="">
		<input type="hidden" name="question[customer_email]" value="">
	<?php endif;?>
	<div class="form-group">
		<label for="question_text" class="required" aria-required="true">
			<?php echo $this->__("Question");?>:<em>*</em>
		</label>
		<textarea name="question[question_text]" title="<?php echo $this->__("Question");?>" 
				  class="required-entry input-text form-control" 
				  cols="5" rows="3" required="required"></textarea>
	</div>
	<p class="required" aria-required="true">* Pola wymagane</p>
	<div class="form-group">
		<button type="submit" title="<?php echo $this->__("Submit");?>" class="btn sending button button-primary"> 
			<i></i> <?php echo $this->__("Submit");?>
		</button>
	</div>
		
</form>