<?php /* @var $this Zolago_Customer_Block_Privacy */ ?>
<?php
$_helper = Mage::helper("customer");
$zolagoCustomerHelper = Mage::helper("customer");

?>

<div class="page-title box-wrapper">
    <h1>
        <span><?php echo $zolagoCustomerHelper->__('Privacy settings') ?></span>
		<span class="back-sm">
            <a href="<?php echo $this->getUrl('customer/account/index') ?>"
               class="underline"><?php echo $zolagoCustomerHelper->__('back: my account'); ?> &gt;</a>
        </span>
		<span class="back-xs">
            <a href="<?php echo $this->getUrl('customer/account/index') ?>"
               class="underline"><?php echo $zolagoCustomerHelper->__('back'); ?> &gt;</a>
        </span>
    </h1>
</div>
<div class="background-wrapper box-wrapper container-fluid">
    <form action="<?php echo $this->getUrl('customer/account/forgetMe') ?>" method="post" id="forgetCustomer-form" autocomplete="off">
        <?php echo $this->getBlockHtml('formkey'); ?>
        <div class="fieldset privacy-border">
            <div id="general-subscription" class="row bigger-padding">
                <div class="col-sm-12">
                    <div class="form-group form-checkbox">
                        <input type="checkbox" name="is_not_remembered" id="is_not_remembered" value="0" class="css-checkbox"/>
                        <label for="is_not_remembered"
                               class="css-label css-label-bold">
                        </label>

                        <div class="pseudo-label label-bold">
                            <?php echo $zolagoCustomerHelper->__('Forget me') ?>
                        </div>
                    </div>
                </div>
                <div class="col-sm-12">
                    <?php echo $this->getLayout()
                        ->createBlock('cms/block')
                        ->setBlockId('privacy-settings-remember-me-description')
                        ->toHtml();
                    ?>
                </div>
                <div class="col-sm-12">

                </div>
            </div>
        </div>

        <div class="bottom-links">
            <a class="button button-third large" href="<?php echo Mage::getUrl("customer/account"); ?>">
                <i class="glyphicon glyphicon-chevron-left"></i>
                <?php echo $zolagoCustomerHelper->__('back') ?>
            </a>
            <button type="submit" class="btn button button-primary pull-right">
                <?php echo $zolagoCustomerHelper->__("Save"); ?>
            </button>
            <div class="clearfix"></div>
        </div>
    </form>
</div>

<script type="text/javascript">
    jQuery(document).ready(function () {
        jQuery('.more-info').on("click", function (event) {
            event.preventDefault();

            var field = jQuery(this).parents('.fieldset');

            field.find('.three-dots').hide();
            field.find('.more-info').hide();
            field.find('.more-info-txt').show();
        });
    });
</script>

