<?php $_order = $this->getOrder() ?>
<?php Mage::helper('urma')->initOrderRmasCollection($_order) ?>
<div class="box-title">
	<h3>RMAs</h3>
</div>
<div class="box-content">
<?php foreach ($_order->getRmasCollection() as $_rma):
    $_vendor = $_rma->getVendor();
?>
<h4 style="margin-bottom:10px;"><?php echo $this->__('RMA #') ?><?php echo $_rma->getIncrementId(); ?> - <span style="text-transform:capitalize"><?php echo Mage::helper('urma')->__($_rma->getRmaStatus()); ?></span></h4>

<?php if ($_rma->getStatusCustomerNotes()): ?>
    <div class="col1-set order-info-box">
        <div class="col-1">
            <div class="box">
                <div class="box-title">
                    <h2><?php echo Mage::helper('urma')->__('General Notes') ?></h2>
                </div>
                <div class="box-content">
                    <?php echo $_rma->getStatusCustomerNotes(); ?>
                </div>
            </div>
        </div>
    </div>
<?php endif; ?>

<div class="col2-set order-info-box">
    <div class="col-1">
        <div class="box">
            <div class="box-title">
                <h2><?php echo $this->__('RMA Sender') ?></h2>
            </div>
            <div class="box-content">
                <address><?php echo $_order->getShippingAddress()->format('html') ?></address>
            </div>
        </div>
    </div>
    <div class="col-2">
        <div class="box">
            <div class="box-title">
                <h2><?php echo $this->__('RMA Receiver') ?></h2>
            </div>
            <div class="box-content">
                <address><?php echo $_vendor->getFormatedAddress('html') ?></address>
            </div>
        </div>
    </div>
</div>

<?php $tracks = $_rma->getTracksCollection(); ?>
<?php  if ($tracks->count()): ?>
    <table class="data-table tracking-table" id="my-tracking-table-<?php echo $_rma->getId(); ?>">
        <tbody>
            <tr>
                <td colspan="2">
                    <a href="#" onclick="popWin('<?php echo $this->helper('urma/shipping')->getTrackingPopupUrlBySalesModel($_rma) ?>','trackrma','width=800,height=600,top=0,left=0,resizable=yes,scrollbars=yes'); return false;" title="<?php echo $this->__('Track this RMA') ?>"><?php echo $this->__('Track this RMA') ?></a>
                    <?php if ($_rma->hasPrintableTracks()): ?>
                    <span class="separator">|</span>
                    <a href="<?php echo $this->getUrl('urma/order/printLabel', array('order_id'=>$_order->getId(), 'rma_id'=>$_rma->getId())) ?>" class="link-print"><?php echo $this->__('Print Label') ?></a>
                    <?php endif ?>
                </td>
            </tr>
            <tr>
                <th class="label"><?php echo $this->__('Tracking Number(s):') ?></th>
                <td>&nbsp;
                <?php
                $i = 1;
                $_size = $tracks->count();
                foreach($tracks as $track): ?>
                <?php if($track->isCustom()): ?>
                    <?php echo $track->getNumber() ?>
                <?php else: ?>
                    <a href="#" onclick="popWin('<?php echo $this->helper('urma/shipping')->getTrackingPopupUrlBySalesModel($track) ?>','trackorder','width=800,height=600,left=0,top=0,resizable=yes,scrollbars=yes')" ><?php echo $track->getNumber() ?></a>
                <?php endif; ?>
                <?php if($i!=$_size): ?>, <?php endif; ?>
                <?php $i++;
                endforeach; ?>
                </td>
            </tr>
        </tbody>
    </table>
    <script type="text/javascript">decorateTable('my-tracking-table-<?php echo $_rma->getId(); ?>')</script>
<?php  endif; ?>

<table class="data-table" id="my-rma-table-<?php echo $_rma->getId(); ?>">
    <col />
    <col width="1" />
    <col width="1" />
    <thead>
        <tr>
            <th><?php echo $this->__('Product Name') ?></th>
            <th><?php echo $this->__('SKU') ?></th>
            <th><?php echo $this->__('Condition') ?></th>
            <th class="a-center"><span class="nobr"><?php echo $this->__('Qty') ?></span></th>
        </tr>
    </thead>
    <?php $_items = $_rma->getAllItems(); ?>
    <?php $_count = count($_items) ?>
    <?php foreach ($_items as $_item): ?>
    <?php if ($_item->getOrderItem()->getParentItem()) continue; ?>
        <?php echo $this->getItemHtml($_item) ?>
    <?php endforeach; ?>
</table>
<script type="text/javascript">decorateTable('my-rma-table-<?php echo $_rma->getId(); ?>', {'tbody' : ['odd', 'even'], 'tbody tr' : ['first', 'last']})</script>
<?php echo $this->getCommentsHtml($_rma)?>
<div class="divider" style="margin:10px -15px;"></div>
<?php endforeach; ?>
</div>