<?php /* @var $this Mage_Catalog_Block_Product_List */ ?>
<?php /* @var $this SolrBridge_Solrsearch_Block_Product_List */ ?>
<?php /* @var $this Unirgy_DropshipMicrosite_Block_Frontend_VendorProducts */ ?>
<?php /* @var $this Zolago_Solrsearch_Block_Catalog_Product_List */ ?>
<?php
/**
 * Author: Paweł Chyl <pawel.chyl@orba.pl>
 * Date: 19.08.2014
 */
/** @var $product Mage_Catalog_Model_Product */
$_productImageUrl = '';
?>


<div id="items-product" class="jsMasonryContent">
    <!-- START LIST PRODUCT -->
    <?php if (($_collection = $this->getCollection())): ?>
    <?php if ($_collection->count()): ?>
        <?php foreach ($_collection as $product): ?>
            <?php $_productImageUrl = $product->getListingResizedImageUrl(); ?>
            <div class="item col-phone col-xs-4 col-sm-4 col-md-3 col-lg-3 size14">
                <div class="box_listing_product">
                    <a href="<?php echo $product->getCurrentUrl(); ?>">
                        <figure class="img_product"><img
                                src="<?php echo $_productImageUrl; ?>"
                                alt="<?php $this->escapeHtml($product->getName()); ?>"
                                class="img-responsive"/></figure>
                        <div class="logo_manufacturer"><img src="<?php echo $product->getUdropshipVendorLogoUrl(); ?>"
                                                            alt="<?php echo $this->escapeHtml($product->getUdropshipVendorName()); ?>"/></div>
                        <div class="name_product"><?php echo $this->escapeHtml($product->getName()); ?></div>
                        <div class="price clearfix">
                            <div class="col-price">
                                <?php if ($product->getPrice() != $product->getFinalPrice()) : ?>
                                    <span
                                        class="old"><?php echo $this->helper('core')->currency($product->getPrice(), true, false); ?></span>
                                <?php endif; ?>
                                <span><?php echo $this->helper('core')->currency($product->getFinalPrice(), true, false); ?></span>
                            </div>
                            <div class="like <?php if ($product->getInMyWishlist()): ?>liked<?php endif; ?>"
                                 data-idproduct="<?php echo $product->getId(); ?>"
                                 data-status="<?php echo (int)$product->getInMyWishlist(); ?>"
                                 onclick="Mall.wishlist.<?php if($product->getInMyWishlist()) : ?>remove<?php else: ?>add<?php endif; ?>FromSmallBlock(this);return false;">
                                <span class="icoLike">
                                  <img class="img-01" src="<?php echo $this->getSkinUrl('images/heart.png'); ?>" alt=""/>
                                  <img class="img-02" src="<?php echo $this->getSkinUrl('images/heart-like.png'); ?>" alt=""/>
                                </span>
                                <span
                                    class="like_count"><span><?php if($product->getInMyWishlist()): ?><?php echo $this->__("You"); ?><?php endif; ?><?php echo $product->getWishlistCount() > 1 && $product->getInMyWishlist() ? " + " : ""; ?></span><?php echo $product->getWishlistCount() > 1 && $product->getInMyWishlist() ? ((int) $product->getWishlistCount() - 1) : ($product->getWishlistCount() && !$product->getInMyWishlist() > 0 ? $product->getWishlistCount() : ""); ?></span>

                                <div class="toolLike"></div>
                            </div>
                        </div>
                    </a>
                </div>
            </div>
        <?php endforeach; ?>
    <?php else: ?>
        No items
    <?php endif; ?>
    <?php endif; ?>

    <div class="shapes_listing">

    </div>

</div>

<!-- END jsMasonryContent -->
<div class="addNewPositionListProductWrapper">
    <a href="javascript:;" onclick="Mall.listing.loadMoreProducts();" class="addNewPositionListProduct"><?php echo $this->__("Load next %s products", $this->getLoadLimit()); ?></a>
</div>
<script type="text/javascript">
    Mall.listing.setScat(<?php echo $this->getLayer()->getCurrentCategory()->getId(); ?>);
    Mall.listing.addToVisibleItems(<?php echo count($this->getCollection()); ?>);
    Mall.translate.add("you-like-this", "<?php echo $this->__("You like this"); ?>");
    Mall.translate.add("remove-from-favorites", "<?php echo $this->__("remove from favorites"); ?>");
    Mall.translate.add("add-to-br-favorites", "<?php echo $this->__("Add to<br />favorites"); ?>");
    Mall.translate.add("like-this-product", "<?php echo $this->__("like this product"); ?>");
    Mall.translate.add("likes-this-product", "<?php echo $this->__("likes this product"); ?>");
    Mall.translate.add("you-and", "<?php echo $this->__("You and"); ?>");
    Mall.translate.add("person", "<?php echo $this->__("person"); ?>");
    Mall.translate.add("people", "<?php echo $this->__("people"); ?>");
    Mall.translate.add("people-polish-more-than-few", "<?php echo $this->__("people polish more than few"); ?>");
    Mall.translate.add("you", "<?php echo $this->__("You"); ?>");
    <?php foreach ($_collection as $product): ?>
    Mall.wishlist.addProduct({
        id: <?php echo $product->getId(); ?>,
        wishlist_count: <?php echo (int)$product->getWishlistCount(); ?>,
        in_your_wishlist: <?php echo $product->getInMyWishlist() ? "true" : "false"; ?>
    });
    <?php endforeach; ?>
</script>