<?php /* @var $this Mage_Catalog_Block_Product_List */ ?>
<?php /* @var $this SolrBridge_Solrsearch_Block_Product_List */ ?>
<?php /* @var $this Unirgy_DropshipMicrosite_Block_Frontend_VendorProducts */ ?>
<?php /* @var $this Zolago_Solrsearch_Block_Catalog_Product_List */ ?>
<?php
/**
 * Author: Paweł Chyl <pawel.chyl@orba.pl>
 * Date: 19.08.2014
 */
/** @var $product Mage_Catalog_Model_Product */
$_productImageUrl = '';
?>


<div id="items-product" class="jsMasonryContent">
    <!-- START LIST PRODUCT -->
    <?php if (($_collection = $this->getCollection())): ?>
    <?php if ($_collection->count()): ?>
        <?php foreach ($_collection as $product): ?>
            <?php $_productImageUrl = $product->getListingResizedImageUrl(); ?>
			<?php $_productImageInfo = $product->getListingResizedImageInfo();?>

            <div class="item col-phone col-xs-4 col-sm-4 col-md-3 col-lg-3 size14">
                <div class="box_listing_product">
                    <a href="<?php echo $product->getCurrentUrl(); ?>">
                        <figure class="img_product"><img
                                src="<?php echo $_productImageUrl; ?>"
                                <?php if($_productImageInfo):?>
                                    data-height="<?php echo $_productImageInfo['height'];?>"
                                    data-width="<?php echo $_productImageInfo['width'];?>"
                                <?php endif;?>
                                alt="<?php $this->escapeHtml($product->getName()); ?>"
                                class="img-responsive"/></figure>
                        <div class="logo_manufacturer"><img class="img-responsive" src="<?php echo $product->getManufacturerLogoUrl(); ?>"
                                                            alt="<?php echo $this->escapeHtml($product->getManufacturer()); ?>"/></div>
                        <div class="name_product"><?php echo $this->escapeHtml($product->getName()); ?></div>
                        <div class="price clearfix">
                            <div class="col-price">
                                <?php if ($product->getPrice() != $product->getFinalPrice()) : ?>
                                    <span
                                        class="old"><?php echo $this->helper('core')->currency($product->getPrice(), true, false); ?></span>
                                <?php endif; ?>
                                <span><?php echo $this->helper('core')->currency($product->getFinalPrice(), true, false); ?></span>
                            </div>
                            <?php
                            // like count
                            $wishlistCount = "";
                            $inMyWishlist = "";
                            $plusSign = "";
                            if ($product->getWishlistCount() - 1 > 0) {
                                $wishlistCount = $product->getWishlistCount();
                                if ($product->getInMyWishlist()) {
                                    $wishlistCount -= 1;
                                }
                            }

                            if ($product->getInMyWishlist()) {
                                $inMyWishlist = $this->__("You");
                                if ($product->getWishlistCount() > 1) {
                                    $plusSign = " + ";
                                }
                            }

                            ?>
                            <div class="like <?php if ($product->getInMyWishlist()): ?>liked<?php endif; ?>"
                                 data-idproduct="<?php echo $product->getId(); ?>"
                                 data-status="<?php echo (int)$product->getInMyWishlist(); ?>"
                                 onclick="Mall.wishlist.<?php if($product->getInMyWishlist()) : ?>remove<?php else: ?>add<?php endif; ?>FromSmallBlock(this);return false;">
                                <span class="icoLike">
                                  <img class="img-01" src="<?php echo $this->getSkinUrl('images/heart.png'); ?>" alt=""/>
                                  <img class="img-02" src="<?php echo $this->getSkinUrl('images/heart-like.png'); ?>" alt=""/>
                                </span>
                                <span
                                    class="like_count"><span><?php echo $inMyWishlist; ?><?php echo $plusSign; ?></span><?php echo $wishlistCount; ?></span>

                                <div class="toolLike"></div>
                            </div>
                        </div>
                    </a>
                </div>
            </div>
        <?php endforeach; ?>
    <?php else: ?>
        No items
    <?php endif; ?>
    <?php endif; ?>

    <div class="shapes_listing">

    </div>

</div>

<!-- END jsMasonryContent -->
<div class="addNewPositionListProductWrapper">
    <a href="javascript:;" onclick="Mall.listing.loadMoreProducts();" class="addNewPositionListProduct"><?php echo $this->__("Load next <span>%s</span> products", $this->getLoadLimit()); ?></a>
</div>
<div id="listing-load-toplayer"><img src="<?php echo $this->getSkinUrl("images/modago-ajax-loader.gif"); ?>"</div>
<script type="text/javascript">
    Mall.listing.setScat(<?php echo $this->getLayer()->getCurrentCategory()->getId(); ?>);
    Mall.listing.addToVisibleItems(<?php echo count($this->getCollection()); ?>);
    Mall.translate.add("you-like-this", "<?php echo $this->__("You like this"); ?>");
    Mall.translate.add("remove-from-favorites", "<?php echo $this->__("remove from favorites"); ?>");
    Mall.translate.add("add-to-br-favorites", "<?php echo $this->__("Add to<br />favorites"); ?>");
    Mall.translate.add("like-this-product", "<?php echo $this->__("like this product"); ?>");
    Mall.translate.add("likes-this-product", "<?php echo $this->__("likes this product"); ?>");
    Mall.translate.add("you-and", "<?php echo $this->__("You and"); ?>");
    Mall.translate.add("person", "<?php echo $this->__("person"); ?>");
    Mall.translate.add("people", "<?php echo $this->__("people"); ?>");
    Mall.translate.add("people-polish-more-than-few", "<?php echo $this->__("people polish more than few"); ?>");
    Mall.translate.add("you", "<?php echo $this->__("You"); ?>");
    <?php foreach ($_collection as $product): ?>
    Mall.wishlist.addProduct({
        id: <?php echo $product->getId(); ?>,
        wishlist_count: <?php echo (int)$product->getWishlistCount(); ?>,
        in_your_wishlist: <?php echo $product->getInMyWishlist() ? "true" : "false"; ?>
    });
    <?php endforeach; ?>
    var listingHeight = jQuery("#items-product").outerHeight();
    var listingWidth = jQuery("#items-product").outerWidth();
    jQuery("#items-product").children(".item").hide();
    jQuery("#listing-load-toplayer").width(listingWidth).height(listingHeight).prependTo("#items-product");
</script>

<style type="text/css">
    #listing-load-toplayer {
        position:absolute;
        z-index: 10000;
    }
    #listing-load-toplayer > img {
        position: relative;
        margin: 0 auto;
        top: 50px;
        left: 50%;
    }
</style>
