<?php
/**
 * Author: Paweł Chyl <pawel.chyl@orba.pl>
 * Date: 19.08.2014
 */
/** @var $product Mage_Catalog_Model_Product */
$_productImageUrl = '';
?>


<div id="items-product" class="jsMasonryContent">
    <!-- START LIST PRODUCT -->
    <?php $_collection = $this->getCollection(); ?>
    <?php if ($_collection->count()): ?>
        <?php foreach ($_collection as $product): ?>
            <?php $_productImageUrl = $product->getListingResizedImageUrl(); ?>
            <div class="item col-phone col-xs-4 col-sm-4 col-md-3 col-lg-3 size14">
                <div class="box_listing_product">
                    <a href="<?php echo $product->getCurrentUrl(); ?>">
                        <figure class="img_product"><img
                                src="<?php echo $_productImageUrl; ?>"
                                alt="<?php $this->escapeHtml($product->getName()); ?>"
                                class="img-responsive"/></figure>
                        <div class="logo_manufacturer"><img src="<?php echo $product->getUdropshipVendorLogoUrl(); ?>"
                                                            alt=""/></div>
                        <div class="name_product"><?php echo $this->escapeHtml($product->getName()); ?></div>
                        <div class="price clearfix">
                            <div class="col-price">
                                <?php if ($product->getPrice() != $product->getFinalPrice()) : ?>
                                    <span
                                        class="old"><?php echo $this->helper('core')->currency($product->getPrice(), true, false); ?></span>
                                <?php endif; ?>
                                <span><?php echo $this->helper('core')->currency($product->getFinalPrice(), true, false); ?></span>
                            </div>
                            <div class="like <?php if ($product->getInMyWishlist()): ?>liked<?php endif; ?>"
                                 data-idproduct="<?php echo $product->getId(); ?>"
                                 data-status="<?php echo (int)$product->getInMyWishlist(); ?>"
                                 onclick="Mall.toggleWishlist(this);">
        <span class="icoLike">
          <img class="img-01" src="<?php echo $this->getSkinUrl('images/heart.png'); ?>" alt=""/>
          <img class="img-02" src="<?php echo $this->getSkinUrl('images/heart-like.png'); ?>" alt=""/>
        </span>
                                <span
                                    class="like_count"><span><?php if ($product->getInMyWishlist()): ?>Ty+ <?php endif; ?></span><?php echo (int)$product->getWishlistCount(); ?></span>

                                <div class="toolLike"></div>
                            </div>
                        </div>
                    </a>
                </div>
            </div>
        <?php endforeach; ?>
    <?php else: ?>
        No items
    <?php endif; ?>

    <div class="shapes_listing">

    </div>

</div>
