<?php
/** @var Zolago_DropshipVendorAskQuestion_Block_Product_Question $this */
$own_store = false;
if($this->isOwnStore()) {
    $own_store = true;
    $vendors = $this->getOwnStoreVendorId();
} else {
    if (!$this->isGallery()) {
        $product = $this->getProduct();
        $vendors = $product ? $product->getUdropshipVendor() : $this->getVendorsList();
    } else {
        $vendors = $this->getLocalVendorId();
    }
}

/** @var Zolago_Customer_Model_Session $session */
$session = Mage::getSingleton('customer/session');

$_helper = Mage::helper('zolagoudqa');

$dataPopulate = Mage::getSingleton('udqa/session')->getDataPopulate(true);

$visibility = isset($dataPopulate['visibility']) ? $dataPopulate['visibility'] : false ;

// if no data to populate fill with query vendor param
if($this->getRequest()->getParam("vendor")){
	$vendors = (int)$this->getRequest()->getParam("vendor");
}

if(!isset($vendors)) {
	$vendors = isset($dataPopulate['vendor_id']) ? $dataPopulate['vendor_id'] : false;
}

$customer_name = isset($dataPopulate['customer_name']) ? $dataPopulate['customer_name'] : false;
$customer_email = isset($dataPopulate['customer_email']) ? $dataPopulate['customer_email'] : false;
$question_text = isset($dataPopulate['question_text']) ? $dataPopulate['question_text'] : false;

//po id from email
$poId = $this->getRequest()->getParam('po');
$poToken = $this->getRequest()->getParam('token');

if($poId && $poToken && $this->isPoContactTokenValid($poId,$poToken)) {
    $customerPoData = $this->getCustomerDataByPoId($poId);
    $customer_name = $customerPoData['name'];
    $customer_email = $customerPoData['email'];
} else {
    $customerPoData = false;
}

?>
<form action="<?php echo $this->getFormAction(); ?>" id="question-form" method="post" novalidate="novalidate" class="form clearfix">
	<?php if(isset($product)): ?>
	    <input type="hidden" name="question[product_id]" value="<?php echo $product->getId()?>" />
	<?php endif; ?>

    <?php if($customerPoData !== false): ?>
        <input type="hidden" name="question[po_id]" value="<?php echo $poId; ?>" />
        <input type="hidden" name="question[po_contact_token]" value="<?php echo $poToken; ?>" />
    <?php endif; ?>

    <input type="hidden" name="question[visibility]" value="0" />

    <div class="row">
        <fieldset class="fieldset col-xs-11">
            <ul class="form-list">
                <?php if($own_store): ?>
                    <input type="hidden" name="question[vendor_id]" value="<?php echo $vendors; ?>" />
				<?php elseif(isset($vendors) && !is_array($vendors)): ?>
					<input type="hidden" name="question[vendor_id]" value="<?php echo $vendors; ?>" />
				<?php elseif(isset($vendors) && is_array($vendors)): ?>
					<li class="wide" id="brandshop_select">
						<div class="form-group select-box-it-select-container">
                            <select name="question[brandshop_id]" id="brandshop_id" class="form-control required-entry select-box-it-select" required>
                                    <option value=""><?php echo $_helper->__('Select brandshop'); ?></option>
                                <?php foreach($vendors as $id=>$name): ?>
                                    <option value="<?php echo $id; ?>" ><?php echo $name; ?></option>
                                <?php endforeach; ?>
                            </select>
						</div>
					</li>
				<?php endif; ?>
                <?php if(!$session->isLoggedIn() && !$customerPoData):?>

                <li class="wide">
                    <div class="form-group">
                        <label for="customer_name" class="required" aria-required="true"><?php echo $_helper->__('Your Name') ?> <em>*</em></label>
                        <div class="input-box">
                            <input type="text" name="question[customer_name]" id="customer_name" class="form-control required-entry input-text hint closer-valid-ico" required
                                value="<?php echo $customer_name; ?>"/>
                        </div>
                    </div>
                </li>


                <li class="wide">
                    <div class="form-group">
                        <label for="customer_email" class="required" aria-required="true"><?php echo $_helper->__('Your Email') ?> <em>*</em></label>
                        <div class="input-box">
                            <input type="text" name="question[customer_email]" id="customer_email" class="validate-email required-entry input-text form-control hint closer-valid-ico" required data-rule-email="true"
                                value="<?php echo $customer_email; ?>"/>
                        </div>
                    </div>
                </li>

                <?php elseif(
                    is_array($customerPoData) &&
                    isset($customerPoData['name']) &&
                    isset($customerPoData['email']) &&
                    $customerPoData['name'] &&
                    $customerPoData['email']
                ): ?>
                    <input type="hidden" name="question[customer_name]" value="<?php echo $this->escapeHtml($customerPoData['name']); ?>" />
                    <input type="hidden" name="question[customer_email]" value="<?php echo $this->escapeHtml($customerPoData['email']); ?>" />
                    <input type="hidden" name="question[customer_id]" value="<?php echo $this->escapeHtml($customerPoData['id']); ?>" />
                <?php endif;?>
                <li class="wide">
                    <div class="form-group">
                        <label for="question_text" class="required" aria-required="true"><?php echo $_helper->__('Your Question') ?> <em>*</em></label>
                        <div class="input-box">
                            <textarea name="question[question_text]" id="question_text" title="" class="required-entry input-text form-control"
                                      cols="5" rows="3" data-original-title="<?php echo $_helper->__('Your Question') ?>"
                                      required><?php echo $question_text; ?></textarea>
                        </div>
                    </div>
                </li>
            </ul>
        </fieldset>
    </div>
    <div class="row">
        <div class="col-xs-11">
            <div class="buttons-set">
                <p class="required" aria-required="true"><?php echo $_helper->__('* Required Fields') ?></p>
                <button type="submit" title="<?php echo $_helper->__('Submit') ?>" class="btn button button-primary  sending">
                    <i></i>
                    <span><span><?php echo $_helper->__('Submit') ?></span></span></button>
            </div>
        </div>
    </div>
</form>
<script type="text/javascript">
	Mall.i18nValidation.add("required", "<?php echo $_helper->__('This field is required') ?>");
	Mall.i18nValidation.add("email", "<?php echo $_helper->__('Valid email is required.') ?>");
</script>
<script>
    jQuery(document).ready(function() {
        var brandselectid = '#brandshop_id',
            brandselect =  jQuery(brandselectid),
            questionform =  jQuery("#question-form");

        brandselect.selectBoxIt({
            autoWidth: false
        });
        var validationOptions = jQuery.extend({}, Mall.validate.getDefaultValidationOptions(), {
            ignore: ''//i.e. do not ignore hidden elements
            ,errorPlacement: function (error, element) {
                error.appendTo(element.parents(".form-group"));
            }
        });

        function getVendors(value) {
            jQuery(".ajax_content").remove();
            if (value) {
                jQuery.ajax({
                    url: "/orbacommon/ajax_vendor/can_ask",
                    data: {
                        "brandshop_id":value,
                    },
                    success: function(data) {
                        jQuery("#brandshop_select").after(data);
                        var vidselect = jQuery("#vendor_id");
                        vidselect.selectBoxIt({
                            autoWidth: false
                        });
                        vidselect.on("change",function() {
                            questionform.validate(validationOptions).element("#vendor_id");
                        });

                    },
                    error: function(response) {
                        alert(response);
                    },
                    type: "POST"
                });
            }
        };
        questionform.validate(validationOptions);

        // this is required to trigger validation on select change
        brandselect.on("change", function() {
            questionform.validate(validationOptions).element(brandselectid);
            var value = brandselect.val();
            getVendors(value);
        });
        getVendors(brandselect.val());
    });
</script>