<?php
$vendors = $this->getVendors();
$visibility = Mage::getSingleton('udqa/source')->setPath('visibility')->toOptionHash();
$session = Mage::getSingleton('customer/session');
$_helper = Mage::helper('zolagoudqa');
/* @var $session Mage_Customer_Model_Session */
?>
<?php if($this->getProduct()->getUdropshipVendor()):?>
<form action="<?php echo $this->getFormAction(); ?>" id="question-form-mobile" method="post">
    <input type="hidden" name="question[product_id]" value="<?php echo $this->getProduct()->getId()?>" />
    <input type="hidden" name="question[vendor_id]" value="<?php echo $this->getProduct()->getUdropshipVendor()?>" />
    <input type="hidden" name="question[visibility]" value="0" />

    <div class="row">
        <fieldset class="fieldset col-xs-11">
            <ul class="form-list">
                <?php if (!$session->isLoggedIn()): ?>
                    <li class="wide">
                        <div class="form-group"><label for="customer_name" class="required"
                                                       aria-required="true"><?php echo $_helper->__('Your Name') ?>
                                <em>*</em>
                            </label>

                            <div class="input-box">
                                <input type="text" name="question[customer_name]" id="customer_name-mobile"
                                       class="form-control required-entry input-text hint" required/>
                            </div>
                        </div>
                    </li>
                    <li class="wide">
                        <div class="form-group"><label for="customer_email" class="required"
                                                       aria-required="true"><?php echo $_helper->__('Your Email') ?> <em>*</em></label>

                            <div class="input-box">
                                <input type="text" name="question[customer_email]" id="customer_email-mobile"
                                       class="validate-email required-entry input-text form-control hint" required
                                       data-rule-email="true"/>
                            </div>
                        </div>
                    </li>
                <?php else: ?>
                    <input type="hidden" name="question[customer_name]"
                           value="<?php $this->escapeHtml($session->getCustomer()->getName()); ?>"/>
                    <input type="hidden" name="question[customer_email]"
                           value="<?php $this->escapeHtml($session->getCustomer()->getEmail()); ?>"/>
                <?php endif; ?>
                <li class="wide">
                    <div class="form-group"><label for="question_text" class="required"
                                                   aria-required="true"><?php echo $_helper->__('Your Question') ?>
                            <em>*</em>
                        </label>

                        <div class="input-box">
                            <textarea name="question[question_text]" id="question_text-mobile"
                                      title="<?php echo $_helper ->__('Your Question') ?>"
                                      class="required-entry input-text form-control" cols="5" rows="3"
                                      data-original-title="<?php echo $_helper ->__('Your Question') ?>"
                                      required></textarea>
                        </div>
                    </div>
                </li>
            </ul>
        </fieldset>
    </div>
    <div class="row">
        <div class="col-xs-11">
            <div class="buttons-set">
                <p class="required" aria-required="true"><?php echo $_helper->__('* Required Fields') ?></p>
                <button type="submit" title="<?php echo $_helper->__('Submit') ?>" class="btn button button-primary large pull-right sending">
                    <i></i>
                    <span><span><?php echo $_helper ->__('Submit') ?></span></span>
                </button>
            </div>
        </div>
    </div>
</form>
    <script type="text/javascript">
        jQuery(document).ready(function () {
            "use strict";
            jQuery('#question-form-mobile').validate(Mall.validate.getDefaultValidationOptions());
        });
    </script>
<?php endif;?>
