<?php
$vendors = $this->getVendors();
$visibility = Mage::getSingleton('udqa/source')->setPath('visibility')->toOptionHash();
$session = Mage::getSingleton('customer/session');
/* @var $session Mage_Customer_Model_Session */
?>
<?php if($this->getProduct()->getUdropshipVendor()):?>
<form action="<?php echo $this->getFormAction(); ?>" id="question-form" method="post">
    <input type="hidden" name="question[product_id]" value="<?php echo $this->getProduct()->getId()?>" />
    <input type="hidden" name="question[vendor_id]" value="<?php echo $this->getProduct()->getUdropshipVendor()?>" />
    <input type="hidden" name="question[visibility]" value="0" />
    <div class="fieldset">
        <ul class="form-list">
			<?php if(!$session->isLoggedIn()):?>
            <li class="wide">
                <label for="customer_name" class="required"><em>*</em><?php echo $this->__('Your Name') ?></label>
                <div class="input-box">
                    <input type="text" name="question[customer_name]" id="customer_name" class="required-entry input-text form-control hint" />
                </div>
            </li>
            <li class="wide">
                <label for="customer_email" class="required"><em>*</em><?php echo $this->__('Email') ?></label>
                <div class="input-box">
                    <input type="text" name="question[customer_email]" id="customer_email" class="validate-email required-entry input-text form-control hint" />
                </div>
            </li>
			<?php else:?>
				<input type="hidden" name="question[customer_name]" value="<?php $this->escapeHtml($session->getCustomer()->getName()); ?>" />
				<input type="hidden" name="question[customer_email]" value="<?php $this->escapeHtml($session->getCustomer()->getEmail()); ?>" />
			<?php endif;?>
            <li class="wide">
                <label for="question_text" class="required"><em>*</em><?php echo $this->__('Question Text') ?></label>
                <div class="input-box">
                    <textarea name="question[question_text]" id="question_text" title="<?php echo $this->__('Question Text') ?>" class="required-entry input-text form-control" cols="5" rows="3"></textarea>
                </div>
            </li>
        </ul>
    </div>
    <div class="buttons-set">
        <p class="required"><?php echo $this->__('* Required Fields') ?></p>
        <button type="submit" title="<?php echo $this->__('Submit') ?>" class="btn sending"><span><span><?php echo $this->__('Submit') ?></span></span></button>
    </div>
</form>
    <script type="text/javascript">
        jQuery("#question-form").validate({
            highlight: function(element, errorClass, validClass) {
                var we = jQuery(element).width()+55;
                var el = jQuery(element).attr('type');
                jQuery(element).closest("div").addClass('has-error has-feedback').removeClass('has-success');
                jQuery(element).closest("div").find('.form-ico-times').remove();

                jQuery(element).closest("div").not( ".form-checkbox" ).append('<i style="left:'+we+'px; right:auto" class="form-ico-times form-control-feedback "></i>');

                jQuery(element).closest("div").find('.form-ico-checked').remove();
            },
            unhighlight: function(element, errorClass, validClass) {
                var we = jQuery(element).width()+55;
                jQuery(element).closest("div").removeClass('has-error').addClass('has-success has-feedback');
                jQuery(element).closest("div").find('.form-ico-checked').remove();
                //if (element.attr("type") != "checkbox"){
                jQuery(element).closest("div").append('<i style="left:'+we+'px; right:auto" class="form-ico-checked form-control-feedback"></i>');
                //}
                jQuery(element).closest("div").find('.form-ico-times').remove();
            },
            errorPlacement: function(error, element) {
                if (element.attr("type") == "checkbox"){
                    jQuery(element).closest('div').append(error).hide().slideToggle(300);
                    //error.prepend(element).hide().slideToggle(300);
                } else {
                    error.insertAfter(element).hide().slideToggle(300);
                }

            },
            success: "valid",
            errorElement: "span",
            onfocusout: function (element) {
                jQuery(element).valid();
            },
            onsubmit: function (element) {
                jQuery(element).valid();
            },
            messages: {
                "question[customer_email]" : {
                    required: "<?php echo $this->__("This field is required"); ?>",
                    email: "<?php echo $this->__("Valid email is required."); ?>"
                },
                "question[customer_name]": {
                    required: "<?php echo $this->__("This field is required"); ?>"
                },
                "question[question_text]": {
                    required: "<?php echo $this->__("This field is required"); ?>"
                }

            },
            rules: {
                "question[customer_email]": {
                    email: true,
                    required: true
                },
                "question[customer_name]": {
                    required: true
                },
                "question[question_text]": {
                    required: true
                }
            }
        });
    </script>
<?php endif;?>
