<?php
/**
 * Altima Lookbook Professional Extension
 *
 * Altima web systems.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is available through the world-wide-web at this URL:
 * http://blog.altima.net.au/lookbook-magento-extension/lookbook-professional-licence/
 *
 * @category   Altima
 * @package    Altima_LookbookProfessional
 * @author     Altima Web Systems http://altimawebsystems.com/
 * @license    http://blog.altima.net.au/lookbook-magento-extension/lookbook-professional-licence/
 * @email      support@altima.net.au
 * @copyright  Copyright (c) 2012 Altima Web Systems (http://altimawebsystems.com/)
 */
?>
<?php
$slider = $this->getSlider();
if (!$slider):
    echo $this->getChildHtml();
else:
    $helper = Mage::helper('lookbookslider');
    $slides = $this->_getSlidesCollection($slider->getId());
    if ($slides->getSize()) :
        $content_before = $this->helper('cms')->getBlockTemplateProcessor()->filter($slider->getContentbefore());
        $content_after = $this->helper('cms')->getBlockTemplateProcessor()->filter($slider->getContentafter());
        $width = $slider->getWidth();
        $height = $slider->getHeight();
        $height_procent = $height / $width * 100;
        $thumb_width = intval($width / ($height / 100));
        $effect = $slider->getEffect();
        $effect_opt = FALSE;
        if ($effect == 'shuffle_revert') {
            $effect = 'shuffle';
            $effect_opt = 'data-cycle-reverse=true';
        }
        if ($effect == '' || $effect == 'all') {
            $effect = 'fade,' .
                    'scrollLeft,scrollRight,scrollVert,scrollUp,scrollDown,' .
                    'cover,tileSlide,tileSlideHorz,tileBlind,tileBlindHorz,' .
                    'slideLeft,slideRight,slideTop,slideBottom,slideLeftTop,' .
                    'slideLeftBottom,slideRightTop,slideRightBottom';
        }
        $effect_arr = FALSE;
        $effect_arr = strpos($effect, ',');
        if ($effect_arr) {
            $effect = explode(',', $effect);
        }

        $navigation = ($slider->getNavigation() == 1) ? TRUE : FALSE;
        $navigationHover = ($slider->getNavigationHover() == 1) ? TRUE : FALSE;
        $thumbnails = ($slider->getThumbnails() == 1) ? TRUE : FALSE;
        $time = ($slider->getTime()) ? $slider->getTime() : 7000;
        $trans_period = ($slider->getTransPeriod()) ? $slider->getTransPeriod() : 1500;
        $no_resample = ($slider->getNoResample() == 1) ? TRUE : FALSE;
        $hotspots = array();
        /*         * ****************** */
        $thumb = TRUE;
        if (count($slides) <= 1):
            $navigation = FALSE;
            $thumbnails = FALSE;
            $thumb = FALSE;
        endif;

        /*         * ****************** */

        if ($slider->getIncludeJquery() == 1) {
            echo $this->helper('core/js')->includeScript('jquery/check_jquery.js');
            echo $this->helper('core/js')->includeScript('jquery/noconflict.js');
            echo $this->helper('core/js')->includeSkinScript('lookbookslider/js/jquery-migrate-1.2.1.min.js');
        }
        if ($slider->getIncludeSlidesJs() == 1) {
            echo $this->helper('core/js')->includeSkinScript('lookbookslider/js/jquery.mobile.customized.min.js');
            echo $this->helper('core/js')->includeSkinScript('lookbookslider/js/jquery.easing.1.3.js');
            echo $this->helper('core/js')->includeSkinScript('lookbookslider/js/jquery.actual.js');
            echo $this->helper('core/js')->includeSkinScript('lookbookslider/js/hotspots.min.js');
            echo $this->helper('core/js')->includeSkinScript('lookbookslider/js/jquery.cycle2.js');  
            echo $this->helper('core/js')->includeSkinScript('lookbookslider/js/jquery.cycle2.carousel.js');
            echo $this->helper('core/js')->includeSkinScript('lookbookslider/js/jquery.cycle2.center.min.js');
            echo $this->helper('core/js')->includeSkinScript('lookbookslider/js/jquery.cycle2.addEffects.js');
            echo $this->helper('core/js')->includeSkinScript('lookbookslider/js/jquery.cycle2.flip.min.js');
        }
        ?>
        <div class="content-before"><?php echo $content_before; ?></div>
        <!----------------->
        <div id="lookbookslider_container_<?php echo $slider->getId() ?>"  class="lookbookslider-container">
            <div 
                id="lookbookslider_widget_<?php echo $slider->getId() ?>"
                class="cycle-slideshow" 
                data-cycle-center-horz="true"
                data-cycle-loader="wait"
                data-cycle-log="false"
                <?php
                if (count($slides) > 1):
                    ?>
                    data-cycle-swipe="true"
                    data-cycle-pause-on-hover="#lookbookslider_container_<?php echo $slider->getId() ?>"
                    data-cycle-timeout="<?php echo $time; ?>"
                    data-cycle-speed="<?php echo $trans_period; ?>"
                    <?php
                endif;

                if ($effect_opt) {
                    echo $effect_opt;
                }
                ?>
                <?php if ($effect_arr === FALSE): ?>
                    data-cycle-fx="<?php echo $effect; ?>"
                <?php endif; ?>
                data-cycle-slides="> div.slide"
                <?php if ($navigation): ?>
                    data-cycle-prev="#lookbookslider_widget_<?php echo $slider->getId() ?> .slide-prev"
                    data-cycle-next="#lookbookslider_widget_<?php echo $slider->getId() ?> .slide-next"
                <?php endif; ?>
                <?php if (!$thumbnails): ?>
                    data-cycle-pager="#pagernav_widget_<?php echo $slider->getId() ?> .cycle"
                    data-cycle-pager-template="<li><span> {{slideNum}} </span></li>"
                <?php endif; ?>
                <?php if (isset($_GET['slide'])): $num_slide = $_GET['slide'] - 1; ?>
                    data-cycle-starting-slide="<?php echo $num_slide; ?>"
                <?php endif; ?>  
                style="max-width:<?php echo $width; ?>px; max-height:<?php echo $height; ?>px; display: block;"
                >
                    <?php if ($navigation): ?>
                    <div class="slide_commands <?php
                    if ($navigationHover) {
                        echo 'hover';
                    }
                    ?>">
                        <div class="slide_play" style="display: none;"></div>
                        <div class="slide_stop" style="display: block;"></div>
                    </div>
                    <div class="slide-prev <?php
                    if ($navigationHover) {
                        echo 'hover';
                    }
                    ?>"><span></span></div>
                    <div class="slide-next <?php
                    if ($navigationHover) {
                        echo 'hover';
                    }
                    ?>"><span></span></div>    
                     <?php endif; ?>

                <?php foreach ($slides as $slide): ?>
                    <div class="slide" 
                    <?php
                    if ($effect_arr):
                        $ind = array_rand($effect, 1);
                        ?>
                             data-cycle-fx="<?php echo $effect[$ind]; ?>"
                         <?php endif; ?>
                         >
                             <?php if ($slide->getLink()): ?>
                                             <?php 
                                             $link = $slide->getLink();
                                             $pos = strpos($link, 'http://');
                                             $pos1 = strpos($link, 'https://');
                                             if($pos === FALSE && $pos1 === FALSE){
                                             $link = 'http://'.$link;    
                                             }
                                             ?>
                                        <a href="<?php echo $link; ?>">
                            <?php endif; ?>
                            <img src="<?php echo $helper->getResizedUrl($slide->getData('image_path'), $width, $height, $no_resample); ?>" alt="Slide <?php echo $slide->getId(); ?>"/>
                            <?php if ($slide->getCaption() != '' && $slider->getShowslidenames() == 1) : ?>
                                <div class="cycle-overlay">
                                    <?php echo $slide->getCaption(); ?>
                                </div>
                            <?php endif; ?>
                            <?php if ($slide->getLink()): ?>
                            </a>
                        <?php endif; ?>
                        <?php if ($helper->canShowPinitButton()): ?>
                            <!------------ Pin It Button ------------------->
                            <div class="pinit_button">
                                <a target="_blank" href="//www.pinterest.com/pin/create/button/" data-pin-do="buttonBookmark" ><img src="//assets.pinterest.com/images/pidgets/pinit_fg_en_rect_gray_20.png" /></a>
                            </div>
                            <!------------ Pin It Button ------------------->
                        <?php endif; ?>

                    </div>
                    <?php $hotspots[] = $this->getHotspotsWithProductDetails($slide); ?>
                <?php endforeach; ?>
                <div id="progress"></div>

            </div>
            <?php if ($thumbnails && $thumb): ?>
                <?php $count_pager = 5; ?>
                <?php
                if (count($slides) < 5) {
                    $count_pager = $slides->getSize();
                }
                ?>
                <div id="pagernav_widget_<?php echo $slider->getId() ?>" class="pagernav" style="max-width:<?php echo $width; ?>px;" >
                    <ul class="cycle-slideshow" 
                        data-cycle-fx="carousel" 
                        data-cycle-center-horz="true"
                        data-cycle-center-vert="true"
                        data-cycle-hide-non-active="false"
                        data-cycle-slides="> li.thumb"
                        data-cycle-timeout="0"
                        data-cycle-carousel-fluid="true"
                        data-allow-wrap="false"
                        data-cycle-log="false"
                        data-cycle-carousel-visible="<?php echo $count_pager; ?>"
                        >
                            <?php foreach ($slides as $slide): ?>
                            <li class='thumb'>
                                <img src='<?php echo $helper->getResizedUrl($slide->getData('image_path'), $thumb_width, 100); ?>'/>
                            </li>
                        <?php endforeach; ?>
                    </ul>
                </div>
            <?php elseif ($thumb): ?>
                <div id="pagernav_widget_<?php echo $slider->getId() ?>" class="pagernav"  style="max-width:<?php echo $width; ?>px;" >
                    <ul class="cycle">

                    </ul>
                </div>
            <?php endif; ?>
        </div>
        <!-------------------------------------->         
        <div class="content-after"><?php echo $content_after; ?></div>
        <div style="clear:both;"></div>

        <script type="text/javascript">
            //<![CDATA[
            var $altima_jq = jQuery.noConflict();
            $altima_jq(window).load(function () {
                var hotspots = <?php echo json_encode($hotspots); ?>;
                $altima_jq('#lookbookslider_widget_<?php echo $slider->getId() ?> > div.slide:not(.cycle-sentinel)').each(function (i) {
                    var ind = $altima_jq(this).index();
                    var slide = $altima_jq(this);
                    $altima_jq.setHotspots(slide, hotspots[i]);
                });
        <?php if ($navigation): ?>
                    $altima_jq('#lookbookslider_widget_<?php echo $slider->getId() ?> .slide_stop').click(function () {
                        $altima_jq('#lookbookslider_widget_<?php echo $slider->getId() ?>').cycle('pause');
                        $altima_jq('#lookbookslider_widget_<?php echo $slider->getId() ?> .slide_stop').hide();
                        $altima_jq('#lookbookslider_widget_<?php echo $slider->getId() ?> .slide_play').show();
                    });
                    $altima_jq('#lookbookslider_widget_<?php echo $slider->getId() ?> .slide_play').click(function () {
                        $altima_jq('#lookbookslider_widget_<?php echo $slider->getId() ?>').cycle('resume');
                        $altima_jq('#lookbookslider_widget_<?php echo $slider->getId() ?> .slide_play').hide();
                        $altima_jq('#lookbookslider_widget_<?php echo $slider->getId() ?> .slide_stop').show();
                    });
        <?php endif; ?>
        <?php if ($thumbnails): ?>
                    $altima_jq('#lookbookslider_widget_<?php echo $slider->getId() ?>').on('cycle-next cycle-prev', function (e, opts) {
                        $altima_jq('#pagernav_widget_<?php echo $slider->getId() ?> ul.cycle-slideshow').cycle('goto', opts.currSlide);
                    });
                    $altima_jq('#pagernav_widget_<?php echo $slider->getId() ?> ul.cycle-slideshow li').click(function () {
                        var index = $altima_jq('#pagernav_widget_<?php echo $slider->getId() ?> ul.cycle-slideshow').data('cycle.API').getSlideIndex(this);
                        $altima_jq('#lookbookslider_widget_<?php echo $slider->getId() ?>').cycle('goto', index);
                        $altima_jq('#pagernav_widget_<?php echo $slider->getId() ?> ul.cycle-slideshow').cycle('goto', index);
                    });
        <?php endif; ?>
                var progress = $altima_jq('#progress'),
                        slideshow = $altima_jq('.cycle-slideshow');
                slideshow.on('cycle-initialized cycle-before', function (e, opts) {
                    progress.stop(true).css('width', 0);
                });
                slideshow.on('cycle-initialized cycle-after', function (e, opts) {
                    if (!slideshow.is('.cycle-paused'))
                        progress.animate({width: '100%'}, opts.timeout, 'linear');
                });
                slideshow.on('cycle-paused', function (e, opts) {
                    progress.stop();
                });
                slideshow.on('cycle-resumed', function (e, opts, timeoutRemaining) {
                    progress.animate({width: '100%'}, timeoutRemaining, 'linear');
                });
            });
            //]]>
        </script>
    <?php endif; ?>
<?php endif; ?>
