var OrbaLib = {
	Wishlist: {
		/** @todo add form_key **/
		add: function(data, callback) {
            OrbaLib._ajax('<?php echo Mage::getUrl('orbacommon/ajax_wishlist/add', array('_secure' => Mage::app()->getFrontController()->getRequest()->isSecure())); ?>', data, callback, 'POST');
        },
		remove: function(data, callback) {
            OrbaLib._ajax('<?php echo Mage::getUrl('orbacommon/ajax_wishlist/remove', array('_secure' => Mage::app()->getFrontController()->getRequest()->isSecure())); ?>', data, callback, 'POST');
        },
	},
	Customer: {
		getAccountInformation: function(data, callback) {
            OrbaLib._ajax('<?php echo Mage::getUrl('orbacommon/ajax_customer/get_account_information', array('_secure' => Mage::app()->getFrontController()->getRequest()->isSecure())); ?>', data, callback, 'GET');
        }
	},
	Listing: {
		getBlocks: function(data, callback) {
            OrbaLib._ajax('<?php echo Mage::getUrl('orbacommon/ajax_listing/get_blocks', array('_secure' => Mage::app()->getFrontController()->getRequest()->isSecure())); ?>', data, callback, 'GET');
        },
		getProducts: function(data, callback) {
            OrbaLib._ajax('<?php echo Mage::getUrl('orbacommon/ajax_listing/get_products', array('_secure' => Mage::app()->getFrontController()->getRequest()->isSecure())); ?>', data, callback, 'GET');
        }
	},
    Product: {
    	getRecentlyViewed: function(data, callback) {
            OrbaLib._ajax('<?php echo Mage::getUrl('orbacommon/ajax_product/get_recently_viewed', array('_secure' => Mage::app()->getFrontController()->getRequest()->isSecure())); ?>', data, callback, 'GET');
        },
        getOne: function(data, callback) {
            OrbaLib._ajax('<?php echo Mage::getUrl('orbacommon/ajax_product/get_one', array('_secure' => Mage::app()->getFrontController()->getRequest()->isSecure())); ?>', data, callback, 'GET');
        },
        getMany: function(data, callback) {
            OrbaLib._ajax('<?php echo Mage::getUrl('orbacommon/ajax_product/get_many', array('_secure' => Mage::app()->getFrontController()->getRequest()->isSecure())); ?>', data, callback, 'GET');
        }
    },
    Cart: {
        get: function(data, callback) {
            OrbaLib._ajax('<?php echo Mage::getUrl('orbacommon/ajax_cart/get', array('_secure' => Mage::app()->getFrontController()->getRequest()->isSecure())); ?>', data, callback, 'GET');
        },
        add: function(data, callback) {
            OrbaLib._ajax('<?php echo Mage::getUrl('orbacommon/ajax_cart/add', array('_secure' => Mage::app()->getFrontController()->getRequest()->isSecure())); ?>', data, callback, 'POST');
        },
        update: function(data, callback) {
            OrbaLib._ajax('<?php echo Mage::getUrl('orbacommon/ajax_cart/update', array('_secure' => Mage::app()->getFrontController()->getRequest()->isSecure())); ?>', data, callback, 'POST');
        },
        remove: function(data, callback) {
            OrbaLib._ajax('<?php echo Mage::getUrl('orbacommon/ajax_cart/remove', array('_secure' => Mage::app()->getFrontController()->getRequest()->isSecure())); ?>', data, callback, 'POST');
        },
        Coupon: {
            add: function(data, callback) {
                OrbaLib._ajax('<?php echo Mage::getUrl('orbacommon/ajax_cart_coupon/add', array('_secure' => Mage::app()->getFrontController()->getRequest()->isSecure())); ?>', data, callback, 'POST');
            },
            remove: function(data, callback) {
                OrbaLib._ajax('<?php echo Mage::getUrl('orbacommon/ajax_cart_coupon/remove', array('_secure' => Mage::app()->getFrontController()->getRequest()->isSecure())); ?>', data, callback, 'POST');
            }
        }
    },
    Rma: {
        getDateList: function(data, callback, async, cache) {
            OrbaLib.__ajax('<?php echo Mage::getUrl('orbacommon/ajax_rma/getDateList', array('_secure' => Mage::app()->getFrontController()->getRequest()->isSecure())); ?>', data, callback, 'POST', async, cache);
        }
    },
    _ajax: function(url, data, callback, type) {
        jQuery.ajax({
            'url': url,
            'data': data,
            'type': type,
            'timeout': 30000,
            'dataType': 'json',
            'success': function(response) {
                callback(response, true);
            },
            'error': function(response) {
                callback(response, true);
            }
        });
    },
    __ajax: function(url, data, callback, type, async, cache) {
        jQuery.ajax({
            'url': url,
            'data': data,
            'type': type,
            'timeout': 30000,
            'dataType': 'json',
            'cache': cache,
            'async': async
        }).done(callback.done).fail(callback.fail).always(callback.always);
    }
};