<?php /* @var $this Zolago_Solrsearch_Block_Catalog_Product_List_Pager */ ?>

<?php $_helper = Mage::helper("zolagomodago"); ?>


<?php if ($this->getCollection()->getSize()): ?>
    <div class="pager listing-pager">
        <div class="amount">
            <?php if ($this->getLastPageNum() > 1): ?>
                <?php echo $_helper->__('%s - %s of %s products', $this->getFirstNum(), $this->getLastNum(), $this->getTotalNum()) ?>
            <?php else: ?>
                <?php echo $_helper->__('%s products', $this->getTotalNum()) ?>
            <?php endif; ?>
        </div>

        <?php if ($this->getLastPageNum() > 1): ?>
            <div class="pages">
                <ol>
                    <li>
                        <?php if ($this->isFirstEnabled()): ?>
                            <a href="<?php echo $this->getPreviousPageUrl() ?>"><< PREV</a>
                        <?php else: ?>
                            <span><< PREV</span>
                        <?php endif; ?>
                    </li>
                    <li>
                        <?php if ($this->isLastEnabled()): ?>
                            <a href="<?php echo $this->getNextPageUrl() ?>">NEXT >></a>
                        <?php else: ?>
                            <span>NEXT >></span>
                        <?php endif; ?>
                    </li>
                </ol>
            </div>
        <?php endif; ?>
    </div>
<?php endif ?>
