<?php if ($this->getCollection()->getSize()): ?>


    <div class="pager">

        <div class="amount">
            <?php if ($this->getLastPageNum() > 1): ?>
                <?php echo $this->__('Items %s to %s of %s total', $this->getFirstNum(), $this->getLastNum(), $this->getTotalNum()) ?>
            <?php else: ?>
                <strong><?php echo $this->__('%s Item(s)', $this->getTotalNum()) ?></strong>
            <?php endif; ?>
        </div>

        <?php if ($this->getLastPageNum() > 1): ?>
            <div class="pages">
                <ol>
                    <li>
                       <a href="<?php echo $this->getPreviousPageUrl() ?>"><< PREV</a>
                    </li>
                    <li>
                        <a href="<?php echo $this->getNextPageUrl() ?>">NEXT >></a>
                    </li>
                </ol>

            </div>
        <?php endif; ?>


    </div>


<?php endif ?>
