<?php /* @var $this Zolago_Solrsearch_Block_Catalog_Product_List_Toolbar */ ?>
<?php $_total = $this->getNumFound();?>

<aside id="sort-criteria" class="container-fluid">
    <div class="col-sm-12">
        <ul class="sort clearfix">
            <li id="pagination">
                <div id="number_products">
	                <span class="start">1</span><span>-</span><span class="end">100</span>
	                <span><?php echo $this->__('of'); ?></span>
	                <span class="value"><?php echo $_total; ?></span>
	                <span><?php echo $this->__('products'); ?></span>
	            </div>
	            <div id="navigation_products">
		            <a href="#back" class="navigation-category navigation-back">
			            <i class="fa fa-caret-left"></i>
		            </a>
		            <a href="#next" class="navigation-category navigation-next">
			            <i class="fa fa-caret-right"></i>
		            </a>
	            </div>
            </li>
            <li class="sort-criteria-selector">
	            <label for="sort-by">
		            <?php echo $this->__("Sort by:"); ?>
	            </label>
	            <div class="sort-by-container">
		            <input type="hidden" id="sort-dir" value="<?php echo $this->getCurrentDir() ?>" />
		            <input type="hidden" id="sort-val" value="<?php echo $this->getCurrentOrder() ?>" />
		            <select id="sort-by" class="form-control">
			            <?php foreach($this->getSortOptions() as $option): ?>
				            <option value="<?php echo $option['sort'].'||'.$option['dir']; ?>"
				                    data-sort="<?php echo $option['sort']; ?>"
				                    data-dir="<?php echo $option['dir']; ?>"
				                    <?php $url = $this->getRewriteUrl($option); ?>
				                    data-url="<?php echo $url; ?>"

				                    <?php if ($option['sort'] === $this->getCurrentOrder() && $option['dir'] == $this->getCurrentDir()): ?>
					                selected
					                <?php endif; ?>>
					            <?php echo str_replace(" ", "&nbsp;", $this->__($this->escapeHtml($option['label'])));?>
		                    </option>
			            <?php endforeach;?>
		            </select>
	            </div>
            </li>
        </ul>
    </div>
</aside>

<script type="text/javascript">
	Mall.listing.setTotal(<?php echo $_total; ?>);
</script>