<?php /* @var $this Zolago_Solrsearch_Block_Catalog_Product_List_Toolbar */ ?>
		<?php $_total = $this->getNumFound();?>
<?php
    $selectedOption = $this->__("by:");
    foreach ($this->getSortOptions() as $opt) {
        if ($opt['value'] === $this->getCurrentOrder() && $opt['dir'] == $this->getCurrentDir()) {
            $selectedOption = str_replace(" ", "&nbsp;", $this->__($this->escapeHtml($opt['label'])));
        }
    }
?>

<aside id="sort-criteria" class="container-fluid">
    <div class="col-sm-12">
        <ul class="sort clearfix">
            <li id="number_products" class=""><span class="label"><?php echo $this->__("Total products count:"); ?> </span> <span class="value"> <?php echo $_total; ?></span></li>
            <li>
                <form action="">
                    <div class="form-group clearfix">
                        <div class="sort-by clearfix">
                            <label for="sort-by"><?php echo $this->__("Sort by:"); ?></label>
                            <div class="select-group small test">
                                <a class="button-select no-ajax" href="#"><span><?php echo $selectedOption; ?></span> <span class="down"></span></a>
                                <div class="dropdown-select scrollable">
                                    <ul  data-role="listview">
                                    <?php foreach($this->getSortOptions() as $option): ?>
                                        <li><a href="#" data-url="<?php echo $this->getSortUrl($option); ?>" data-dir="<?php echo $option['dir']; ?>" data-sort="<?php echo $option['value']; ?>" data-value="<?php echo $this->__($this->escapeHtml($option['label']));?>"><span><?php echo str_replace(" ", "&nbsp;", $this->__($this->escapeHtml($option['label'])));?></span></a></li>
                                    <?php endforeach;?>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            </li>
        </ul>
    </div>
</aside>

<script type="text/javascript">
    Mall.listing.setDir("<?php echo $this->getCurrentDir(); ?>");
    Mall.listing.setSort("<?php echo $this->getCurrentOrder(); ?>");
    Mall.listing.setTotal(<?php echo $_total; ?>);
</script>