<script type="text/javascript">
    jQuery(document).ready(function() {

        Mall.i18nValidation.add("cookie_close", "<?php echo Mage::helper("zolagomodago")->__("CLOSE"); ?>");

        jQuery.cookieBar({
            fixed: true,
            bottom: true,
            zindex: 9999,
            message: '<?php echo Mage::app()->getLayout()->createBlock("cms/block")->setBlockId("cookie_restriction_notice_block")->toHtml(); ?>',
            acceptText: Mall.i18nValidation.__("cookie_close")
        });
    });
</script>