<?php
    $headerBlock = $this->getLayout()->getBlockSingleton('Mage_Page_Block_Html_Header');
?>

<footer id="footer">
    <div class="container-fluid footer-black">
        <div class="col-xs-12">
            <div class="row">
                <div class="footer-logo ">

                    <a href="<?php echo $this->getUrl(''); ?>"><img src="<?php echo $headerBlock->getLogoSrc() ?>" alt="<?php $headerBlock->getLogoAlt(); ?>" /></a>

                </div>

                <?php echo $this->getChildHtml('footer.links'); ?>

                <div class="footer-connect ">
                    <span>dołącz <br class="visible-xs">do nas</span>
                    <a href="#" class="ico_social_twitter"></a>
                    <a href="#" class="ico_social_fb"></a>
                    <a href="#" class="ico_social_instagram"></a>
                    <a href="#" class="ico_social_gplus"></a>
                    <a href="#" class="ico_social_pinterest"></a>
                </div>
            </div>
        </div>
    </div>
    <div class=" footer-gray-wr">
        <div class="container-fluid">
            <div class="col-xs-12">
                <div class="row">
                    <div class="footer-payment  hidden-xs">
                        <span class="footer-pay-visa "></span>
                        <span class="footer-pay-master "></span>
                        <span class="footer-pay-paypal "></span>
                    </div>
                    <div class="footer-utils visible-xs">
                        <div>
                            <a href=" "><?php echo $this->__("cookies policy"); ?> <i class="fa fa-angle-right"></i></a>
                            <a href=" "><?php echo $this->__("full page version"); ?> <i class="fa fa-angle-right"></i></a>
                        </div>
                    </div>
                    <div class="copy">
                        <?php echo Mage::getStoreConfig('design/footer/copyright'); ?>
                    </div>

                </div>
            </div>
        </div>
    </div>
</footer>