<?php
    $headerBlock = $this->getLayout()->getBlockSingleton('Mage_Page_Block_Html_Header');
?>

<footer id="footer">
    <div class="container-fluid footer-black">
        <div class="col-xs-12">
            <div class="row">
                <div class="footer-logo ">

                    <a href="index.php/ "><img src="<?php echo $headerBlock->getLogoSrc() ?>" alt="<?php $headerBlock->getLogoAlt(); ?>" /></a>

                </div>
                <div class="footer-about ">
                    <ul class="hidden-sm hidden-xs">
                        <li><a href="#"><i class="fa fa-angle-right"></i> Pomoc</a></li>
                        <li><a href="#"><i class="fa fa-angle-right"></i> Twoje konto</a></li>
                        <li><a href="#"><i class="fa fa-angle-right"></i> Regulamin</a></li>
                        <li><a href="#"><i class="fa fa-angle-right"></i> O nas</a></li>
                    </ul>

                    <ul class="visible-sm visible-xs">
                        <li><a href="#"><i class="fa fa-angle-right"></i> Pomoc</a></li>
                        <li><a href="#"><i class="fa fa-angle-right"></i> O nas</a></li>
                        <li><a href="#"><i class="fa fa-angle-right"></i> Twoje konto</a></li>
                        <li><a href="#"><i class="fa fa-angle-right"></i> Kontakt</a></li>
                        <li><a href="#"><i class="fa fa-angle-right"></i> Pełna wersja wpisu</a></li>
                    </ul>
                </div>
                <div class="footer-connect ">
                    <span>dołącz <br class="visible-xs">do nas</span>
                    <a href=" " class="connect-twitter "></a>
                    <a href=" " class="connect-fb "></a>
                    <a href=" " class="connect-rss "></a>
                    <a href=" " class="connect-gplus "></a>
                    <a href=" " class="connect-pin "></a>
                </div>
            </div>
        </div>
    </div>
    <div class=" footer-gray-wr">
        <div class="container-fluid">
            <div class="col-xs-12">
                <div class="row">
                    <div class="footer-payment  hidden-xs">
                        <span class="footer-pay-visa "></span>
                        <span class="footer-pay-master "></span>
                        <span class="footer-pay-paypal "></span>
                    </div>
                    <div class="footer-utils visible-xs">
                        <div>
                            <a href=" ">polityka cookies <i class="fa fa-angle-right"></i></a>
                            <a href=" ">pełna wersja strony <i class="fa fa-angle-right"></i></a>
                        </div>
                    </div>
                    <div class="copy">
                        Copyright &copy; 2014 MODAGO. All Rights Reserved
                    </div>

                </div>
            </div>
        </div>
    </div>
</footer>