<?php
    $headerBlock = $this->getLayout()->getBlockSingleton('Mage_Page_Block_Html_Header');
?>
<footer>
    <div class="container footer-black hidden-xs">
        <div class="row">
            <div class="col-sm-3 col-md-4 col-lg-3 footer-logo">
                <a href="<?php echo $this->getUrl(''); ?>"><img src="<?php echo $headerBlock->getLogoSrc() ?>" alt="<?php echo $headerBlock->getLogoAlt(); ?>" /></a>
            </div>
            <div class="col-sm-8 col-md-6 col-lg-5 footer-about">
                <ul>
                    <li><a href="#">&gt; <?php echo $this->__("about us"); ?></a></li>
                    <li><a href="#">&gt; <?php echo $this->__("contact"); ?></a></li>
                    <li><a href="#">&gt; <?php echo $this->__("portfolio"); ?></a></li>
                    <li><a href="#">&gt; <?php echo $this->__("service"); ?></__s></a></li>
                </ul>
            </div>
            <div class="col-sm-1 col-md-2 col-lg-4 footer-connect">
                <span><?php echo $this->__("connect with us"); ?></span>
                <a href="#" class="connect-twitter"></a>
                <a href="#" class="connect-fb"></a>
                <a href="#" class="connect-rss"></a>
                <a href="#" class="connect-gplus"></a>
                <a href="#" class="connect-pin"></a>
            </div>
        </div>
    </div>
    <div class="footer-gray-wr hidden-xs">
        <div class="container">
            <div class="row">
                <div class="col-sm-4 col-md-3 col-lg-2 footer-payment">
                    <span class="footer-pay-visa"></span>
                    <span class="footer-pay-master"></span>
                    <span class="footer-pay-paypal"></span>
                </div>
                <div class="col-sm-8 col-md-9 col-lg-10">
                    <?php echo $this->getCopyright(); ?>
                </div>
            </div>
        </div>
    </div>
    <!--    small screens-->
    <div class="container visible-xs footer-xs-black">
        <div class="row">
            <div class="col-xs-6 footer-xs-pageinfo">
                <ul>
                    <li><a href="#">&gt; <?php echo $this->__("about us"); ?></a></li>
                    <li><a href="#">&gt; <?php echo $this->__("contact"); ?></a></li>
                    <li><a href="#">&gt; <?php echo $this->__("portfolio"); ?></a></li>
                    <li><a href="#">&gt; <?php echo $this->__("service"); ?></__s></a></li>
                </ul>
            </div>
            <div class="col-xs-6 footer-xs-logo">
                <a href="<?php echo $this->getUrl(''); ?>"><img src="<?php echo $headerBlock->getSkinUrl('images/mobile_logo.png'); ?>" alt="<?php echo $headerBlock->getLogoAlt(); ?>" /></a>
            </div>
        </div>
        <div class="row footer-xs-connect">
            <div class="col-xs-2"><?php echo $this->__("connect with us"); ?>:</div>
            <div class="col-xs-10">
                <a href="#" class="connect-twitter"></a>
                <a href="#" class="connect-fb"></a>
                <a href="#" class="connect-rss"></a>
                <a href="#" class="connect-gplus"></a>
                <a href="#" class="connect-pin"></a>
            </div>
        </div>
    </div>
    <div class="container visible-xs footer-xs-gray">
        <div class="row">
            <div class="col-xs-6"><a href=""><?php echo $this->__("cookie policy"); ?> &gt;</a></div>
            <div class="col-xs-6"><a href=""><?php echo $this->__("full version of this page"); ?> &gt;</a></div>
        </div>
        <div class="row">
            <div class="col-xs-12"><?php echo $this->getCopyright(); ?></div>
        </div>
    </div>
</footer>