<?php
/**
 * Author: Paweł Chyl <pawel.chyl@orba.pl>
 * Date: 29.04.14
 */
?>


<header id="header">
    <div class="header_top">
        <div class="container_1176 clearfix">
            <?php echo $this->getChildHtml('page.header.left.menu'); ?>
            <?php echo $this->getChildHtml('page.header.search'); ?>
            <!-- LOGO -->
            <div id="logo">
                <a href="<?php echo $this->getUrl(''); ?>" class="logo">
                    <img src="<?php echo $this->getLogoSrc(); ?>" alt="<?php echo $this->getLogoAlt(); ?>">
                </a>
            </div>
            <?php echo $this->getChildHtml('page.header.right.menu'); ?>
        </div>
    </div>
    <?php echo $this->getChildHtml('page.header.bottom.menu'); ?>
</header>
