<header>
    <div class="header_top">
        <div class="container">
            <div class="col-sm-1 col-xs-1"><a href="#" class="toggleMenu"><i class="ico_menu"></i></a></div>
            <div class="col-sm-4 search  hidden-sm hidden-xs">
                <form class="navbar-form navbar-left" role="search">
                    <div class="form-group">
                        <input type="text" class="form-control" placeholder="Search">
                    </div>
                    <div class="dropdown">
                        <a id="value_search_category" data-toggle="dropdown" href="#"><?php echo $this->__('in whole gallery'); ?> </a>
                        <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
                            <li><a href="#"><?php echo $this->__('All categories'); ?></a></li>
                            <li><a href="#"><?php echo $this->__('She'); ?></a></li>
                            <li><a href="#"><?php echo $this->__('Him'); ?></a></li>
                        </ul>
                    </div>
                    <input type="image" src="<?php echo $this->getSkinUrl('images/ico_search.gif'); ?>" value="Szukaj">
                </form>

            </div>
            <div id="toggleSearch" class="col-xs-1 visible-sm visible-xs">
                <div class="dropdown row">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#"><i class="ico_search_mobile"></i></a>
                    <ul class="dropdown-menu searchDropdown">
                        <li>
                            <form class="navbar-form navbar-left" role="search">
                                <div class="form-group">
                                    <input type="text" class="form-control" placeholder="Search">
                                </div>
                                <div class="form-group">
                                    <select name="" id="" class="form-control">
                                        <option value=""><?php echo $this->__('All categories'); ?></option>
                                        <option value=""><?php echo $this->__('She'); ?></option>
                                        <option value=""><?php echo $this->__('Him'); ?></option>
                                    </select>
                                </div>
                                <button class="btn pull-right"><i class="btn-gold"><?php echo $this->__('Search'); ?></i></button>
                            </form>
                        </li>
                    </ul>
                </div>
            </div>
            <!-- LOGO -->
            <div class="col-xs-2">
                <a href="<?php echo $this->getUrl(''); ?>" id="logo"><img src="<?php echo $this->getSkinUrl('images/logo_header.png'); ?>" alt="<?php echo $this->getLogoAlt(); ?>"></a>
            </div>
            <!-- NAV RIGHT -->
            <div class="col-md-4 col-sm-5 col-xs-4 pull-right">
                <ul class="nav navbar-nav  pull-right">
                    <li class="hidden-xs">
                        <a href="<?php echo Mage::getUrl('customer/account', array('_secure' => true)); ?>"><i class="ico_your_account"></i><br><span class="hidden-xs"><?php echo $this->__('Your account'); ?></span></a>
                    </li>
                    <li>
                        <a href="#"><i class="ico_favorites"></i><br><span class="hidden-xs"><?php echo $this->__('Favorites'); ?></span><span class="badge">42</span></a>

                    </li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="<?php echo Mage::getUrl('checkout/cart', array('_secure' => true)); ?>">
                            <i class="ico_basket"></i><br><span class="hidden-xs"><?php echo $this->__('Basket'); ?></span>
                            <span class="badge">42</span>
                        </a>
                        <ul class="dropdown-menu basket">
                            <li>
                                <table>
                                    <tbody>
                                    <tr>
                                        <td class="thumb"><img src="<?php echo $this->getSkinUrl('images/product/thumb/img-thumb-product.png'); ?>" alt=""></td>
                                        <td class="desc">
                                            <p class="name_product">ZARA Krótki płaszcz z guzikami</p>
                                            <p class="size"><?php echo $this->__('size'); ?>: <span>38</span></p>
                                            <p class="quantity"><?php echo $this->__('quantity'); ?>: <span>1</span></p>
                                        </td>
                                        <td class="price">3 000,00 zł</td>
                                    </tr>
                                    <tr>
                                        <td class="thumb"><img src="<?php echo $this->getSkinUrl('images/product/thumb/img-thumb-product.png'); ?>" alt=""></td>
                                        <td class="desc">
                                            <p class="name_product">ZARA Krótki płaszcz z guzikami</p>
                                            <p class="size"><?php echo $this->__('size'); ?>: <span>38</span></p>
                                            <p class="quantity"><?php echo $this->__('quantity'); ?>: <span>1</span></p>
                                        </td>
                                        <td class="price">3 000,00 zł</td>
                                    </tr>
                                    </tbody>
                                </table>
                                <div class="summary_basket">
                                    <ul>
                                        <li><?php echo $this->__('Products count'); ?>: 2</li>
                                        <li><?php echo $this->__('Products worth'); ?>: 7600,00 zł</li>
                                        <li><?php echo $this->__('Shipping cost'); ?>: <?php echo $this->__("free shipping"); ?></li>
                                    </ul>
                                    <a href="<?php echo Mage::getUrl('checkout/cart', array('_secure' => true)); ?>" class="view_basket"><?php echo $this->__("See your cart"); ?></a>
                                </div>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="header_bottom">
        <div class="container"></div>
    </div>
</header>
