<?php
/**
 * Author: Paweł Chyl <pawel.chyl@orba.pl>
 * Date: 10.04.14
 */ ?>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta http-equiv="Content-Type" content="<?php echo $this->getContentType() ?>" />
<meta name = "viewport" content = "user-scalable=no, width=device-width">
<title><?php echo $this->getTitle() ?></title>
<meta name="description" content="<?php echo htmlspecialchars($this->getDescription()) ?>" />
<meta name="keywords" content="<?php echo htmlspecialchars($this->getKeywords()) ?>" />
<meta name="robots" content="<?php echo htmlspecialchars($this->getRobots()) ?>" />
<link rel="shortcut icon" href="<?php echo $this->getFaviconFile(); ?>" type="image/x-icon" />
<!--[if lt IE 7]>
<script type="text/javascript">
    //<![CDATA[
    var BLANK_URL = '<?php echo $this->helper('core/js')->getJsUrl('blank.html') ?>';
    var BLANK_IMG = '<?php echo $this->helper('core/js')->getJsUrl('spacer.gif') ?>';
//]]>
</script>
<![endif]-->
<!--[if lt IE 9]>
<script src="<?php echo $this->helper('core/js')->getJsSkinUrl('js/vendor/html5shiv.min.js'); ?>"></script>
<script src="<?php echo $this->helper('core/js')->getJsSkinUrl('js/vendor/respond.min.js'); ?>"></script>
<![endif]-->

<?php echo $this->getCssJsHtml() ?>
<?php echo $this->getChildHtml() ?>
<?php //echo $this->helper('core/js')->getTranslatorScript() ?>
<?php echo $this->getIncludes() ?>
