<?php
/*  @var $this GH_Dhl_Block_Adminhtml_Dhl_Grid */
?>
<div class="content-header">
<table cellspacing="0">
    <tr>
        <td style="width:50%;">
            <h3>
                <?php echo Mage::helper('ghdhl')->__('DHL Accounts') ?>
            </h3>
        </td>
        <td class="a-right">
            <?php echo $this->getButtonsHtml() ?>
        </td>
    </tr>
</table>
</div>
<div>
    <?php echo $this->getChildHtml('ghdhl_dhl_grid') ?>
</div>