<?php $key = $this->getFacetKey(); ?>
<?php if($this->getCanShow()): ?>
    <?php
        $backUrl = $this->getParentCategoryUrl();
        $backLabel = $this->escapeHtml($this->getParentCategoryLabel());
        $sectionClass = $this->isFilterRolled() ? 'closed' : 'open';
        $iconClass = $this->isFilterRolled() ? "fa-chevron-down" : "fa-chevron-up";
    ?>
	<div class="section clearfix">
		<h3 class="<?php echo $sectionClass; ?>"><span><?php echo $this->getFacetLabel(); ?></span> <i class="fa <?php echo $iconClass; ?>"></i></h3>
		<div class="content" id="filter_category">
			<dl>
			<?php foreach ($this->getAllItems() as $item=>$count):?>
				<?php if (is_array($count)): ?>
					<?php if($count['is_root_category']): ?>
						<?php foreach($count['children'] as $child_item=>$children_count): ?>
							<?php if($this->getCanShowItem($child_item, $children_count)): ?>
								<dd><a data-params='<?php echo $this->getItemJson($item);?>' href="<?php echo $this->getItemUrl($child_item) ?>" class="simpleChild"><span><?php echo $this->getItemText($child_item); ?></span>&nbsp;<span class="suffix">(<?php echo $children_count ?>)</span></a></dd>
							<?php endif;?>
						<?php endforeach; ?>
					<?php else: ?>
					<dt><?php echo $this->getItemText($item); ?>&nbsp;<span>(<?php echo $count['total'] ?>)</span></dt>
						<?php foreach($count['children'] as $child_item=>$children_count): ?>
							<?php if($this->getCanShowItem($child_item, $children_count)): ?>
								<dd><a data-params='<?php echo $this->getItemJson($item);?>' href="<?php echo $this->getItemUrl($child_item) ?>" class="simpleChild"><span><?php echo $this->getItemText($child_item); ?></span>&nbsp;<span class="suffix">(<?php echo $children_count ?>)</span></a></dd>
							<?php endif;?>
						<?php endforeach; ?>
						<?php endif; ?>
				<?php endif; ?>
			<?php endforeach; ?>
			</dl>
			<div class="action clearfix">
			<?php if($backUrl != null) : ?>
				<a href="<?php echo $backUrl; ?>" class="go_back underline external"><?php echo $this->__("back to category"); ?> <?php echo $backLabel; ?></a>
			<?php endif; ?>
			</div>
		</div>

	</div>
<?php endif; ?>
