<?php
/** @var $this Zolago_Modago_Block_Solrsearch_Faces_Category */
$helper = Mage::getModel("zolagosolrsearch");
?>
<?php $key = $this->getFacetKey(); ?>
<?php if($this->getCanShow()): ?>
    <?php
        $backUrl = $this->getParentCategoryUrl();
        $backLabel = strtolower($this->escapeHtml($this->getParentCategoryLabel()));
        $sectionClass = $this->isFilterRolled() ? 'closed' : 'open';
        $iconClass = $this->isFilterRolled() ? "fa-chevron-down" : "fa-chevron-up";
        $isSearch = $this->getIsSearch();
        $isParrentRoot = $this->getIsParentRootCategory();
        /* @var $landingPageHelper Zolago_Campaign_Helper_LandingPage */
        $landingPageHelper = Mage::helper("zolagocampaign/landingPage");
        /** @var Zolago_Campaign_Model_Campaign $campaign */
        $campaign = $landingPageHelper->getCampaign();
    ?>
	<div class="section clearfix" data-xs-rolled="open" data-lg-rolled="<?php echo $sectionClass; ?>">
		<h3 class="<?php echo $sectionClass; ?>"><span><?php echo $this->getFacetLabel(); ?></span> <i class="fa <?php echo $iconClass; ?>"></i></h3>
		<div class="content" id="filter_category">
			<dl>
			<?php foreach ($this->getAllItems() as $item=>$count):?>
				<?php if (is_array($count)): ?>
					<?php if($count['is_root_category']): ?>
						<?php foreach($count['children'] as $child_item=>$children_count): ?>
							<?php if($this->getCanShowItem($child_item, $children_count)): ?>
								<dd><?php $this->getItemUrl($child_item) ?><a data-params='<?php echo $this->getItemJson($item);?>' href="<?php echo $this->getItemUrl($child_item) ?>" class="simpleChild"><span><?php echo $this->getItemText($child_item); ?></span>&nbsp;<span class="suffix">(<?php echo $children_count ?>)</span></a></dd>
							<?php endif;?>
						<?php endforeach; ?>
					<?php else: ?>
					<dt><?php echo $this->getItemText($item); ?>&nbsp;<span>(<?php echo $count['total'] ?>)</span></dt>
						<?php foreach($count['children'] as $child_item=>$children_count): ?>
							<?php if($this->getCanShowItem($child_item, $children_count)): ?>
								<dd><a data-params='<?php echo $this->getItemJson($item);?>' href="<?php echo $this->getItemUrl($child_item) ?>" class="simpleChild"><span><?php echo $this->getItemText($child_item); ?></span>&nbsp;<span class="suffix">(<?php echo $children_count ?>)</span></a></dd>
							<?php endif;?>
						<?php endforeach; ?>
						<?php endif; ?>
				<?php endif; ?>
			<?php endforeach; ?>
			</dl>
			<div class="action clearfix">
			<?php if($backUrl != null) : ?>
                <?php if(!$isSearch): ?>
                    <?php if($isParrentRoot): ?>
                        <?php if($campaign && $campaign->getId()): ?>
                            <a href="<?php echo $backUrl; ?>" class="go_back underline external"><?php echo $helper->__("back to campaign"); ?></a>
                        <?php else: ?>
                            <a href="<?php echo $backUrl; ?>" class="go_back underline external"><?php echo $backLabel; ?></a>
                        <?php endif; ?>
                    <?php else: ?>
                        <?php if($campaign && $campaign->getId()): ?>
                            <a href="<?php echo $backUrl; ?>" class="go_back underline external"><?php echo $helper->__("back to campaign"); ?></a>
                        <?php else: ?>
                            <a href="<?php echo $backUrl; ?>" class="go_back underline external"><?php echo $this->__("back to category"); ?> <?php echo $backLabel; ?></a>
                        <?php endif; ?>
                    <?php endif; ?>
                <?php else: ?>
                    <?php if($isParrentRoot): ?>
                        <a href="<?php echo $backUrl; ?>" class="go_back underline external"><?php echo $backLabel; ?></a>
                    <?php else: ?>
                        <a href="<?php echo $backUrl; ?>" class="go_back underline external"><?php echo $this->__("back to category"); ?> <?php echo $backLabel; ?></a>
                    <?php endif; ?>
                <?php endif; ?>
			<?php endif; ?>
			</div>
		</div>

	</div>
<?php endif; ?>
