<?php
/** @var $this Zolago_Solrsearch_Block_Faces_Enum */
$key = $this->getFacetKey();
/** @see Zolago_Solrsearch_Block_Faces::_getRegularFilterBlocks */
$customShowFlag = $this->getCustomShowFlag();
?>
<?php if ($this->getCanShow()): ?>
    <?php
    $sectionClass = $this->isFilterRolled() ? 'closed' : 'open';
    $iconClass = $this->isFilterRolled() ? "fa-chevron-down" : "fa-chevron-up";
    $isOptionSelected = false;
    $key_withoutFacet = explode("_", $key);
    array_pop($key_withoutFacet);
	$pureKey = implode("_", $key_withoutFacet);
    ?>
    <div class="section clearfix" data-xs-rolled="closed" data-lg-rolled="<?php echo $sectionClass; ?>" <?php echo $customShowFlag ? "style='display:none;visibility:hidden;'" : ''; ?>>
        <h3 class="<?php echo $sectionClass; ?>"><span><?php echo $this->getFacetLabel(); ?></span> <i class="fa <?php echo $iconClass; ?>"></i></h3>
        <div id="filter_<?php echo $key ?>" class="content checkbox filter-enum">
            <?php foreach ($this->getItems() as $item => $count): ?>
                <?php if ($this->getCanShowItem($item, $count)): ?>
                    <?php
                    if(!$isOptionSelected && $this->isItemActive($item)) {
                        $isOptionSelected = true;
                    }
                    ?>
                    <div class="form-group form-checkbox">

                        <input data-url="<?php echo $this->getItemUrl($item) ?>"
							   data-params='<?php echo $this->getItemJson($item);?>' 
							   type="checkbox" 
							   name="<?php echo $this->getItemName($item);?>"
							   value="<?php echo $this->getItemValue($item)?>"
							   id="<?php echo $this->getItemId($item)?>"
							   class="css-checkbox" 
							   <?php if($this->isItemActive($item)): ?>checked="checked" <?php endif; ?>>
	                    <label for="<?php echo $this->getItemId($item); ?>" class="css-label">
	                        <span>
		                        <a href="<?php echo $this->getItemUrl($item); ?>"
		                           class="listing-link">
			                        <?php echo $item; ?>
		                        </a>
	                        </span>
		                    &nbsp;
	                        <span class="suffix">
		                        (<?php echo $count; ?>)
	                        </span>
	                    </label>
                    </div>
                <?php endif; ?>
            <?php endforeach; ?>
            <?php if ($this->getCanShowHidden()): ?>
                <?php foreach ($this->getHiddenItems() as $item => $count): ?>
                    <div class="form-group form-checkbox" data-state="hidden" style="display: none;">
                        <input data-url="<?php echo $this->getItemUrl($item) ?>"  
							   type="checkbox" 
							   class="css-checkbox" 
							   name="<?php echo $this->getItemName($item);?>"
							   value="<?php echo $this->getItemValue($item)?>"
							   id="<?php echo $this->getItemId($item)?>"
							   <?php if($this->isItemActive($item)): ?>checked="checked" <?php endif; ?>>
	                    <label for="<?php echo $this->getItemId($item); ?>" class="css-label">
	                        <span>
		                        <a href="<?php echo $this->getItemUrl($item); ?>"
		                           class="listing-link">
			                        <?php echo $item; ?>
		                        </a>
	                        </span>
		                    &nbsp;
	                        <span class="suffix">
		                        (<?php echo $count; ?>)
	                        </span>
	                    </label>
                    </div>
                <?php endforeach; ?>
                <div class="action clearfix">
                    <a href="#" class="go_read_filter underline showmore-filters" data-state="0"><?php echo $this->__("Show more"); ?></a>
                </div>
            <?php endif; ?>
            <div class="action clear clearfix <?php if(!$isOptionSelected) : ?>hidden<?php endif; ?>">
                <a href="<?php echo $this->getRemoveAllUrl($pureKey) ?>" data-filter-type="<?php echo $pureKey; ?>" class="button button-third clear"><?php echo $this->__("Clear"); ?></a>
            </div>
        </div>
        <?php if($isOptionSelected) : ?>
            <div class="content-xs" id="filter_<?php echo $key ?>_xs" data-content="xs">
                <div class="active-filter">
                    <?php foreach ($this->getItems() as $item => $count): ?>
                        <?php if ($this->getCanShowItem($item, $count) && $this->isItemActive($item)): ?>
                            <a href="<?php echo $this->getItemUrl($item); ?>"
                               class="active-filter-label"
                               data-input="<?php echo $this->getItemId($item); ?>">
                                <?php echo $this->getItemValue($item); ?><i class="fa fa-times"></i>
                            </a>
                            <input type="hidden" name="fq[<?php echo $pureKey; ?>]"
                                   value="<?php echo $this->getItemValue($item); ?>"/>
                        <?php endif; ?>
                    <?php endforeach; ?>
                </div>
            </div>
        <?php endif; ?>
    </div>
<?php endif; ?>