<?php $key = $this->getFacetKey(); ?>
<?php if ($this->getCanShow()): ?>
    <?php
    $sectionClass = $this->isFilterRolled() ? 'closed' : 'open';
    $iconClass = $this->isFilterRolled() ? "fa-chevron-down" : "fa-chevron-up";
    $isOptionSelected = false;
    $key_withoutFacet = explode("_", $key);
    array_pop($key_withoutFacet);
	$pureKey = implode("_", $key_withoutFacet);
    $name = '';
    ?>

    <div class="section clearfix">
        <h3 class="<?php echo $sectionClass; ?>"><span><?php echo $this->getFacetLabel(); ?></span> <i class="fa <?php echo $iconClass; ?>"></i></h3>
        <div class="content filter-flags"  id="filter_<?php echo $key ?>">
    <?php foreach ($this->getItems() as $item => $count): ?>
        <?php if ($this->getCanShowItem($item, $count)): ?>
            <?php
            if(!$isOptionSelected && $this->isItemActive($item)) {
                $isOptionSelected = true;
            }
            $name = $this->getNameBasedOnContent($item);
            $class = $this->getClassBasedOnContent($item);
            ?>
            <div class="form-group form-checkbox">
                <input type="checkbox" 
					   name="<?php echo $this->getItemName($item);?>"
					   value="<?php echo $this->getItemValue($item)?>"
					   id="<?php echo $this->getItemId($item)?>" 
					   class="css-checkbox" 
					   data-params='<?php echo $this->getItemJson($item);?>' 
					   data-url="<?php echo $this->getItemUrl($item) ?>" <?php if ($this->isItemActive($item)): ?>checked<?php endif; ?>>
	            <label for="<?php echo $this->getItemId($item); ?>" class="css-label <?php echo $class; ?>">
                    <span>
                        <a href="<?php echo $this->getItemUrl($item); ?>"
                           class="listing-link">
	                        <?php echo $item; ?>
                        </a>
                    </span>
		            &nbsp;
                    <span class="suffix">
                        (<?php echo $count; ?>)
                    </span>
	            </label>
            </div>

        <?php endif; ?>
    <?php endforeach; ?>
            <div class="action clear clearfix <?php if(!$isOptionSelected) : ?>hidden<?php endif; ?>">
                <a href="<?php echo $this->getRemoveAllUrl($pureKey) ?>" data-filter-type="<?php echo $pureKey; ?>"  class="button button-third clear"><?php echo $this->__("Clear"); ?></a>
            </div>
        </div>

    </div>
<?php endif; ?>