<?php $key = $this->getFacetKey(); ?>
<?php if ($this->getCanShow()): ?>
    <?php
    $sectionClass = $this->isFilterRolled() ? 'closed' : 'open';
    $iconClass = $this->isFilterRolled() ? "fa-chevron-down" : "fa-chevron-up";
    $isOptionSelected = false;
    $key_withoutFacet = explode("_", $key);
    array_pop($key_withoutFacet);
    $name = '';
    ?>

    <div class="section clearfix">
        <h3 class="<?php echo $sectionClass; ?>"><?php echo $this->getFacetLabel(); ?> <i class="fa <?php echo $iconClass; ?>"></i></h3>
        <div class="content filter-flags"  id="filter_<?php echo $key ?>">
    <?php foreach ($this->getItems() as $item => $count): ?>
        <?php if ($this->getCanShowItem($item, $count)): ?>
            <?php
            if(!$isOptionSelected && $this->isItemActive($item)) {
                $isOptionSelected = true;
            }
            $name = $this->getNameBasedOnContent($item);
            $class = $this->getClassBasedOnContent($item);
            ?>
            <div class="form-group form-checkbox">
                <input type="checkbox" name="<?php echo $name; ?>" id="<?php echo $name; ?>" class="css-checkbox" data-url="<?php echo $this->getItemUrl($item) ?>">
                <label for="<?php echo $name; ?>" class="css-label <?php echo $class; ?>"><span><?php echo $item; ?></span> <span class="suffix">(<?php echo $count; ?>)</span></label>
            </div>

        <?php endif; ?>
    <?php endforeach; ?>
            <div class="action clear clearfix <?php if(!$isOptionSelected) : ?>hidden<?php endif; ?>">
                <a href="#" data-filter-type="<?php echo implode("_", $key_withoutFacet); ?>" onclick="Mall.listing.removeSingleFilterType(this);Mall.listing.reloadListing();return false;" class="button button-third clear"><?php echo $this->__("Clear"); ?></a>
            </div>
        </div>

    </div>
<?php endif; ?>