<?php
$solrData = $this->getSolrData ();
$priceFieldName = Mage::helper ( 'solrsearch' )->getPriceFieldName ();

$prefix = 'solrbridge-price';

$ranges = $this->getFacetPriceRanges();

$min = $this->getMinPriceRange();
$max = $this->getMaxPriceRange();
$fromValue = $min;
$toValue = $max;

// step count

/*
 * Holds state of initial price position
 */
$initialState = false;
?>

<?php
$key = "fq[price]";
$sectionClass = $this->isFilterRolled() ? 'closed' : 'open';
$iconClass = $this->isFilterRolled() ? "fa-chevron-down" : "fa-chevron-up";
$isOptionSelected = $initialState;
$key_withoutFacet = explode("_", $key);
array_pop($key_withoutFacet);
$name = '';
?>
<?php if ($max > 0):?>
    <div class="section clearfix">
        <h3 class="<?php echo $sectionClass; ?>"><?php echo $this->__("Price"); ?> <i class="fa <?php echo $iconClass; ?>"></i></h3>
        <div class="content"  id="filter_price">
			<?php foreach($ranges as $range) : ?>
			<?php $url = $this->getFacesUrl(array('fq'=>array('price' => $range['value']),'price_facet'=>array('price'=>$range['value']))); ?>	
            <div class="form-group form-checkbox">

                <input 
					type="checkbox" 
					data-url="<?php echo $url;?>"
					value="<?php echo $range['value'];?>" 
					name="<?php echo $key; ?>" 
					id="filter_price_<?php echo $range['start'];?>_<?php echo $range['end'];?>" 
					class="css-checkbox"
					<?php if ($this->isRangeActive($range['value'])):?> checked="checked"<?php endif;?>
				/>
                <label for="filter_price_<?php echo $range['start'];?>_<?php echo $range['end'];?>" class="css-label">
	                <span>
		                <a href="<?php echo $url; ?>"
		                   class="listing-link">
			                <?php echo $range['formatted'] ?>
		                </a>
	                </span>
	                <span class="suffix">
		                (<?php echo $range['count']; ?>)
	                </span>
                </label>
            </div>
			<?php endforeach; ?>
            <div id="od_do" class="clearfix">
                <div class="clearfix">
                    <div id="checkSlider" class="form-group form-checkbox">
                        <input 
							type="checkbox" 
							name="fq[filter_slider]" 
							id="filter_slider" 
							class="css-checkbox" 
							<?php if($isOptionSelected) : ?>checked="checked"<?php endif; ?>
						/>
                        <label for="filter_slider" class="css-label"></label>
                    </div>
                    <div class="form-horizontal">
                        <div class="form-group">
                            <input type="text" id="zakres_min" value="<?php echo $fromValue; ?>" /><label for="zakres_od">-</label>
                        </div>
                    </div>
                    <div class=" form-horizontal">
                        <div class="form-group">
                            <input id="zakres_max" value="<?php echo $toValue; ?>" type="text" />
                        </div>
                    </div>
                    <div class="form-action">
                        <div class="form-group">
                            <input type="submit" class="btn black pull-right filter-price-range-submit" data-filter-type="price" value="OK"/>
                        </div>
                    </div>
                </div>
                <div id="slider-range"></div>

            </div><br />
            <div class="action clear clearfix <?php if(!$isOptionSelected): ?>hidden<?php endif; ?>">
                <a href="#" class="button button-third clear"  data-filter-type="<?php echo implode("_", $key_withoutFacet); ?>" onclick="Mall.listing.removeSingleFilterType(this);Mall.listing.reloadListing();return false;" ><?php echo $this->__("Clear"); ?></a>
            </div>
        </div>
    </div>
    <script type="text/javascript">
        Mall.listing.setCurrentPriceRange(<?php echo $fromValue; ?>, <?php echo $toValue; ?>);
    </script>
<?php endif;?>

<script type="text/javascript">
    Mall.translate.add("price-filter-not-valid", "<?php echo $this->__("Prices in filter are not valid."); ?>");
</script>
