<?php $_helper = Mage::helper("zolagorma"); ?>
<?php $_po = $this->getPo(); ?>
<?php //echo xdebug_var_dump($_po);

?>
<?php $_rma = $this->getRma();?>
<?php $_shippingAddress = $_po->getShippingAddress(); ?>
<?php $_itemsSingle = $_rma->getItemsSingle(); ?>
<?php $_itemsConditionSingle = $_rma->getItemsConditionSingle(); ?>
<?php $items = $this->getItemList();?>
<?php $dateList = $this->getDateList();?>
<?php $weekdays = Mage::app()->getLocale()->getOptionWeekdays();?>
<div class="steps step-2 background-wrapper box-wrapper" id="step-2">
    <div class="rma-container ">
		<?php if (($this->isDhlEnabled()) && count($dateList)) : ?>
        <div id="pickup-address-form" class="fieldset flow-return">
            <input type="hidden" name="rma[shipping_address_id]" value="<?php echo $_shippingAddress->getId(); ?>"/>
            <input type="hidden" name="rma[override_address]" value="0"/>
            <h3 class="legend-big"><?php echo $_helper->__("Report a return or claim"); ?></h3>
            <h3 class="legend"><?php echo $_helper->__("Confirm or change pickup address for the courier"); ?>:</h3>

            <div class="panel panel-default">
                <div class="panel-body panel-body-with-footer">
                    <div class="current-rma-address current-addres clearfix">

                        <dl class="pull-left" id="shipping-address">
                            <dt><?php echo $_shippingAddress->getFirstname(); ?> <?php echo $_shippingAddress->getLastname(); ?></dt>
                            <dd><?php echo $_shippingAddress->getData("street"); ?></dd>
                            <dd><?php echo $_shippingAddress->getPostcode(); ?> <?php echo $_shippingAddress->getCity(); ?></dd>
                            <dd class="separator phone">
                                <?php echo $this->__('Contact phone'); ?>:
                                <span><?php echo $_shippingAddress->getTelephone(); ?></span>
                            </dd>
                        </dl>
                    </div>

                </div>
                <div class="panel-footer clearfix">
                    <a class="underline pull-right change_address shipping" href="#">
                        <?php echo $_helper->__("Change address"); ?> [dev]
                    </a>
                </div>
            </div>

        </div>
        <div id="pickup-date-form">
            <h3 class="legend"><?php echo $_helper->__("Schedule pickup date that is convenient for you"); ?></h3>
            <div class="panel panel-default">
                <div class="panel-body">
                    <?php if(count($dateList) == 0): ?>
                        <div class="current-rma-date clearfix">
                            <div id="pickup-date-form-panel" class="fieldset flow-return">

                                <label class="required choose-date" for="carrier-date"><?php echo $_helper->__("Choose the date"); ?>
                                    <em>:</em></label>

                                <div class="input-box" id="dateList">

                                    <?php foreach ($dateList as $date=>$item): ?>
                                        <input
                                            type="radio"
                                            name="rma[carrier_date]"
                                            id="carrier_date_<?php echo $date;?>"
                                            value="<?php echo date('Y-m-d',$date);?>"
                                            />
                                        <label for="carrier_date_<?php echo $date;?>">
                                            <span>
                                                <span class="rma-dayname"><?php echo $weekdays[date('w',$date)]['label'];?></span>
                                                <br/>
                                                <span class="rma-date"><?php echo $this->getFormattedDate($date);?></span>
                                            </span>
                                        </label>
                                    <?php endforeach; ?>
                                </div>

                                <label class="required carrier-time-from"
                                       for="carrier-time-from"><?php echo $_helper->__("Select the time interval"); ?>
                                    <em>:</em></label>
                                <div class="choose-time">
                                    <div class="field">
                                        <div class="input-box">
                                            <input type="hidden" name="rma[carrier_time_from]" id="carrier-time-from"
                                                   value="<?php echo $_rma->getCarrierTimeFrom(); ?>"
                                                   title="<?php echo $_helper->__("Choose time-from of the day"); ?>"/>
                                            <input type="hidden" name="rma[carrier_time_to]" id="carrier-time-to"
                                                   value="<?php echo $_rma->getCarrierTimeTo(); ?>"
                                                   title="<?php echo $_helper->__("Choose time-to of the day"); ?>"/>
                                        </div>
                                        <div id="pickup-time"></div>
                                    </div>
                                    <div id="slider-range"></div>
                                </div>
                            </div>
                    <?php endif; ?>
                    <?php if(count($dateList) != 0): ?>
                        Dla podanego adresu nie ma możliwości zamówienia kuriera
                    <?php endif; ?>
                    </div>
                </div>

            </div>
        </div>

		<?php endif;?>
        <div class="fieldset hide-success-vaild " id="customer-account-wrapper">
            <div>
                <h3 class="legend"><?php echo $_helper->__("Enter your account number for your order refund"); ?></h3>
                <input type="text" value="<?php echo $this->escapeHtml($_rma->getCustomerAccount()); ?>"
                   name="rma[customer_account]" value="" id="customer-account"
                   title="<?php echo $_helper->__("Bank account"); ?>" value="" class="form-control bank-account-rma">
            </div>
        </div>
    </div>
    <div class="rma-container">
        <a href="#step-1" class="button button-third large back pull-left">
            <?php echo $_helper->__("Back"); ?>
        </a>
        <button class="btn button button-primary next pull-right"
                type="button" id="btn-next-step-2"><?php echo $_helper->__("Next"); ?></button>
    </div>
</div>



<script type="text/javascript">
    var isAcknowledged = false;
</script>
<?php  $vendor = $_po->getVendor();?>

<script type="text/javascript">
    //TRANSLATIONS
    Mall.translate.add("Selected time", "<?php echo $_helper->__('Selected time') ?>");
    //TRANSLATIONS END

    //INIT DATE LIST

    Object.size = function(obj) {
        var size = 0, key;
        for (key in obj) {
            if (obj.hasOwnProperty(key)) size++;
        }
        return size;
    };

    <?php $js_array = json_encode($dateList); ?>
    var dataList = <?php echo $js_array; ?>;
    if (Object.size(dataList) == 0) {
        jQuery('#btn-next-step-2').hide();
    } else {
        for(var day in dataList) {
            jQuery('#carrier_date_' + day).attr('data-PickupFrom', dataList[day].getPostalCodeServicesResult.drPickupFrom );
            jQuery('#carrier_date_' + day).attr('data-PickupTo', dataList[day].getPostalCodeServicesResult.drPickupTo );
        }
    }

    //INIT DATE LIST END

    //INIT SLIDER DEFAULT VALUES AND PARAMS
    if (Object.size(dataList) != 0) {
        jQuery("#slider-range").noUiSlider({
            start: [660, 840],
            step: 60,
            behaviour: 'drag-fixed',
            connect: true,
            range: {
                'min': 540,
                'max': 1200
            }
        });
    }
    //INIT SLIDER DEFAULT VALUES AND PARAMS END

    //CHANGE DESCRIPTIONS ON SLIDER SLIDE
    jQuery("#slider-range").on({
        slide: function() {
            var values = jQuery(this).val();
            var from = values[0];
            var to = values[1];
            formatTimeRange(from, to);

            var minutes0 = parseInt(from % 60, 10),
                hours0 = parseInt(from / 60 % 24, 10),
                minutes1 = parseInt(to % 60, 10),
                hours1 = parseInt(to / 60 % 24, 10);

            var startTime = getTime(hours0, minutes0);
            var endTime = getTime(hours1, minutes1);

            jQuery('#pickup-time-from').text(startTime);
            jQuery('#pickup-time-to').text(endTime);
        }
    });
    //CHANGE DESCRIPTIONS ON SLIDER SLIDE END

    //SET SLIDER, SAVE PICKUP TIME, WRITE MESSAGES
    jQuery('#pickup-date-form-panel input').click(function() {
        var _from =  jQuery(this).attr('data-PickupFrom');
        var _to =  jQuery(this).attr('data-PickupTo');

        var from = parseInt(jQuery(this).attr('data-PickupFrom'))*60;
        var to = parseInt(jQuery(this).attr('data-Pickupto'))*60;

        if( (to - from) <= (3*60) ) {

            jQuery("#slider-range").noUiSlider({
                start: [from, to],
                range: {
                    'min': from,
                    'max': to
                }
            }, true);
            var values = jQuery("#slider-range").val();
            formatTimeRange(values[0], values[1]);
            jQuery('#pickup-time').html('Dla Twojego adresu dostępny jest tylko przedział czasowy: <br>między godziną: ' +
            '<span id=pickup-time-from>' + _from + '</span>' + ' a godziną ' +
            '<span id=pickup-time-to>' + _to + '</span>');

            jQuery('#time').hide();
            jQuery("#slider-range").hide();
            jQuery('.carrier-time-from').hide();
        } else {
            jQuery('#time').hide();
            jQuery("#slider-range").show()
            jQuery('.carrier-time-from').show();
            jQuery("#slider-range").noUiSlider({
                start: [from, from + (3 * 60)],
                range: {
                    'min': from,
                    'max': to
                }
            }, true);

            var values = jQuery("#slider-range").val();
            jQuery('#pickup-time').html('Dla Twojego adresu, dostępne są terminy od ' +
            _from + ' do ' + _to + '<br/><span id="wrapper-choosen-pickup-time">' + formatTimeRange(values[0], values[1]) + '</span>');
        }
    });
    //SET SLIDER, SAVE PICKUP TIME, WRITE MESSAGES END

    //IF PAYMENT METHOD IS CHECKONDELIVERY THEN SHOW FIELD BANK ACCOUNT
    var showBankAcc = <?php echo $_po->isPaymentCheckOnDelivery() ? '1' : '0'; ?>;
    jQuery('#customer-account-wrapper').hide();
    if (showBankAcc) {
        jQuery('#customer-account-wrapper').show();
    }
    //IF PAYMENT METHOD IS CHECKONDELIVERY THEN SHOW FIELD BANK ACCOUNT END





    //applyFlow
    var returnReasons = '<?php echo Mage::helper("zolagorma")->getReturnReasons($_po, true); ?>';
    var flowAcknowledged = '<?php echo Zolago_Rma_Model_Rma::FLOW_ACKNOWLEDGED; ?>';

    jQuery("select[name^='rma[items_condition_single]']").each(function(item){
        if(item.value){
            if(returnReasons[item.value].flow == flowAcknowledged){
                isAcknowledged = true;
            }
        }
    })

    if(isAcknowledged){
        jQuery('#pickup-address-form').hide();
        jQuery('#pickup-date-form').hide();
        jQuery('#pickup-address-overview').hide();
        jQuery('#pickup-date-overview').hide();
        jQuery('#overview-message').hide();
    }
    else{
        jQuery('#pickup-address-form').show();
        jQuery('#pickup-date-form').show();
        jQuery('#pickup-address-overview').show();
        jQuery('#pickup-date-overview').show();
        jQuery('#overview-message').show();
    }



    function formatTimeRange(from, to){
        var minutes0 = parseInt(from % 60, 10),
            hours0 = parseInt(from / 60 % 24, 10),
            minutes1 = parseInt(to % 60, 10),
            hours1 = parseInt(to / 60 % 24, 10);


        var startTime = getTime(hours0, minutes0);
        var endTime = getTime(hours1, minutes1);

        var message = Mall.translate.__("Selected time") + ': <span id=pickup-time-from>' + startTime +  '</span> - ' + '<span id=pickup-time-to>' + endTime + '</span>';
//        jQuery("#time span").html(message);

        jQuery('[name="rma[carrier_time_from]"]').val(startTime);
        jQuery('[name="rma[carrier_time_to]"]').val(endTime);

        return message;

    }

    function getTime(hours, minutes) {
        minutes = minutes + "";
        if (minutes.length == 1) {minutes = "0" + minutes;}
        return hours + ":" + minutes;
    }

    var values = jQuery("#slider-range").val();
    formatTimeRange(values[0], values[1]);

    function setPickupTime(from, to, txtPrefix, txtBetween) {
        jQuery('#pickup-time').html(txtPrefix + from + txtBetween + to);
    }

    jQuery(document).ready( function() {
        jQuery('#pickup-date-form-panel input').first().click();//default set the first day
    });

</script>
