<?php $_helper = Mage::helper("zolagorma"); ?>
<?php $_po = $this->getPo(); ?>
<?php $_rma = $this->getRma();?>
<?php $_itemsSingle = $_rma->getItemsSingle(); ?>
<?php $_itemsConditionSingle = $_rma->getItemsConditionSingle(); ?>
<?php $items = $this->getItemList();?>

<div class="steps step-1" id="step-1" >
	<div class="fieldset">
		<h2 class="legend"><?php echo $_helper->__("Choose RMA items"); ?></h2>
		<ul class="form-list">
			<li class="wide">
				<div class="input-box">
					<table class="data-table" style="width: 100%;">
						<colgroup>
							<col width="30px"/>
							<col/>
							<col width="150px"/>
						</colgroup>
						<thead>
							<tr>
								<th>&nbsp;<label class="required"><em>*</em></label></th>
								<th><?php echo $_helper->__("Product"); ?></th>
								<th><label class="required"><?php echo $_helper->__("Reason"); ?><em>*</em></label></th>
							</tr>
						</thead>
						<tbody>
							<?php
							foreach ($items as $item_pack):
								foreach ($item_pack as $key => $item):
									?>
									<tr data-name="<?php echo $this->escapeHtml($item['name']); ?>">
										<td style="vertical-align: middle;">
											<input <?php if(isset($_itemsSingle[$item['entityId']][$key])):?>checked="checked"<?php endif;?> type="checkbox" class="rma-checkbox" name="rma[items_single][<?php echo $item['entityId'] ?>][<?php echo $key ?>]" value="true"/>
										</td>
										<td>
											<?php echo $this->escapeHtml($item['name']); ?>
										</td>
										<td style="vertical-align: middle;">
											<div class="condition-wrapper" >
												<select style="width: auto;" class="required-entry" id="condition-<?php echo $key; ?>-<?php echo $item['entityId']; ?>" name="rma[items_condition_single][<?php echo $item['entityId'] . '][' . $key . ']' ?>">
													<option value=""><?php echo $_helper->__('Select a reason...') ?></option>
													<?php foreach($_helper->getItemConditionTitles() as $_key=>$_label):?>
													<option <?php if(isset($_itemsConditionSingle[$item['entityId']][$key]) && $_itemsConditionSingle[$item['entityId']][$key]==$_key):?>selected="selected"<?php endif;?> value="<?php echo $this->escapeHtml($_key);?>"><?php echo $this->escapeHtml($_label); ?></option>
													<?php endforeach;?>
												</select>
											</div>
										</td>
									</tr>
									<?php
								endforeach;
							endforeach;
							?>
						</tbody>
					</table>
					<input type="hidden" name="rma[has_items]" value="" class="required-entry" id="rma-has-items"/>
				</div>
			</li>
		</ul>
	</div>
</div>