<?php $_helper = Mage::helper("zolagorma"); ?>
<?php $_po = $this->getPo(); ?>
<?php $_rma = $this->getRma();?>
<?php $_shippingAddress = $_po->getShippingAddress(); ?>
<?php $_itemsSingle = $_rma->getItemsSingle(); ?>
<?php $_itemsConditionSingle = $_rma->getItemsConditionSingle(); ?>
<?php $items = $this->getItemList();?>
<?php $dateList = $this->getDateList();?>
<?php $weekdays = Mage::app()->getLocale()->getOptionWeekdays();?>
<?php $vendor = $_po->getVendor();?>
<div class="steps step-2 background-wrapper box-wrapper" id="step-2">
    <div class="rma-container">
		<?php if (($this->isDhlEnabled()) && count($dateList)) : ?>
        <div id="pickup-address-form" class="fieldset flow-return">
            <input type="hidden" name="rma[shipping_address_id]" value="<?php echo $_shippingAddress->getId(); ?>"/>
            <input type="hidden" name="rma[override_address]" value="0"/>
            <h3 class="legend-big"><?php echo $_helper->__("Report a return or claim"); ?></h3>
            <h3 class="legend"><?php echo $_helper->__("Confirm or change pickup address for the courier"); ?>:</h3>

            <div class="panel panel-default">
                <div class="panel-body panel-body-with-footer">
                    <div class="current-rma-address current-addres clearfix">

                        <dl class="pull-left" id="shipping-address">
                            <dt><?php echo $_shippingAddress->getFirstname(); ?> <?php echo $_shippingAddress->getLastname(); ?></dt>
                            <dd><?php echo $_shippingAddress->getData("street"); ?></dd>
                            <dd><?php echo $_shippingAddress->getPostcode(); ?> <?php echo $_shippingAddress->getCity(); ?></dd>
                            <dd class="separator phone">
                                <?php echo $this->__('Contact phone'); ?>:
                                <span><?php echo $_shippingAddress->getTelephone(); ?></span>
                            </dd>
                        </dl>
                    </div>

                </div>
                <div class="panel-footer clearfix">
                    <a class="underline pull-right change_address shipping" href="#">
                        <?php echo $_helper->__("Change address"); ?> [dev]
                    </a>
                </div>
            </div>

        </div>
        <div id="pickup-date-form">
            <h3 class="legend"><?php echo $_helper->__("Schedule pickup date that is convenient for you"); ?></h3>
            <div class="panel panel-default">
                <div class="panel-body">
                    <?php if(count($dateList) != 0): ?>
                        <div class="current-rma-date clearfix">
                            <div id="pickup-date-form-panel" class="fieldset flow-return">

                                <label class="required choose-date" for="carrier-date"><?php echo $_helper->__("Choose the date"); ?>
                                    <em>:</em></label>

                                <div class="input-box" id="dateList">
                                    <?php $number = 1; ?>
                                    <?php foreach ($dateList as $date=>$item): ?>

                                        <input
                                            type="radio"
                                            name="rma[carrier_date]"
                                            id="carrier_date_<?php echo $date;?>"
                                            value="<?php echo date('Y-m-d',$date);?>"
                                            />
                                        <label for="carrier_date_<?php echo $date;?>" class="<?php echo "label-$number";?>">
                                            <span>
                                                <span class="rma-dayname"><?php echo $weekdays[date('w',$date)]['label'];?></span>
                                                <br/>
                                                <span class="rma-date"><?php echo $this->getFormattedDate($date);?></span>
                                            </span>
                                        </label>
                                        <?php $number++; ?>
                                    <?php endforeach; ?>
                                </div>

                                <label class="required carrier-time-from"
                                       for="carrier-time-from"><?php echo $_helper->__("Select the time interval"); ?>
                                    <em>:</em></label>
                                <div class="choose-time">
                                    <div class="field">
                                        <div class="input-box">
                                            <input type="hidden" name="rma[carrier_time_from]" id="carrier-time-from"
                                                   value="<?php echo $_rma->getCarrierTimeFrom(); ?>"
                                                   title="<?php echo $_helper->__("Choose time-from of the day"); ?>"/>
                                            <input type="hidden" name="rma[carrier_time_to]" id="carrier-time-to"
                                                   value="<?php echo $_rma->getCarrierTimeTo(); ?>"
                                                   title="<?php echo $_helper->__("Choose time-to of the day"); ?>"/>
                                        </div>
                                        <div id="pickup-time"></div>
                                    </div>
                                    <div id="slider-range"></div>
                                </div>
                            </div>
                    <?php endif; ?>
                    <?php if(count($dateList) == 0): ?>
                        <?php echo $_helper->__("For the given address is not possible to order a courier"); ?>
                    <?php endif; ?>
                    </div>
                </div>

            </div>
        </div>

		<?php endif;?>
        <div class="fieldset row" id="customer-account-wrapper">
            <div>
                <h3 class="legend col-sm-12"><?php echo $_helper->__("Enter your account number for your order refund"); ?></h3>
                <div class="col-sm-5">
                    <input type="text" autocomplete="off" value="<?php echo $this->escapeHtml($_rma->getCustomerAccount()); ?>"
                       name="rma[customer_account]" value="" id="customer-account"
                       title="<?php echo $_helper->__("Bank account"); ?>" value="" class="form-control bank-account-rma validate-bankAccountWithReplace">
                </div>
            </div>
        </div>
    </div>
    <div class="rma-container">
        <a href="#step-1" class="button button-third large back pull-left">
            <?php echo $_helper->__("Back"); ?>
        </a>
        <button class="btn button button-primary next pull-right"
                type="button" id="btn-next-step-2"><?php echo $_helper->__("Next"); ?></button>
    </div>
</div>

<script type="text/javascript">
    //TRANSLATIONS
    Mall.translate.add("Selected time", "<?php echo $_helper->__('Selected time') ?>");
    Mall.translate.add("For your address is only available time interval", "<?php echo $_helper->__('For your address is only available time interval') ?>");
    Mall.translate.add("between the hours", "<?php echo $_helper->__("between the hours") ?>");
    Mall.translate.add("and", "<?php echo $_helper->__("and") ?>");
    Mall.translate.add("For your address, there are dates from ", "<?php echo $_helper->__("For your address, there are dates from ") ?>");
    Mall.translate.add(" to ", "<?php echo $_helper->__(" to ") ?>");
    Mall.translate.add("Bank account number must contain 26 digits.", "<?php echo $_helper->__("Bank account number must contain 26 digits.") ?>");
    Mall.translate.add("Choose the date", "<?php echo $_helper->__("Choose the date") ?>");
    Mall.translate.add("Select the time interval", "<?php echo $_helper->__("Select the time interval") ?>");
    Mall.translate.add("Choose time-from of the day", "<?php echo $_helper->__("Choose time-from of the day") ?>");
    Mall.translate.add("Choose time-to of the day", "<?php echo $_helper->__("Choose time-to of the day") ?>");
    Mall.translate.add("For the given address is not possible to order a courier", "<?php echo $_helper->__("For the given address is not possible to order a courier") ?>");
    //TRANSLATIONS END

    //INIT DATA
    var rmaCarrierTimeFrom = '<?php echo $_rma->getCarrierTimeFrom(); ?>';
    var rmaCarrierTimeTo = '<?php echo $_rma->getCarrierTimeTo(); ?>';
    var dateList = <?php echo json_encode($dateList); ?>;
    var dateListFormatedDate = [];

    <?php // formatted date for next 20 (max) days from today
    for($count = 0; $count < 20 ; $count++) {
        $timestamp = time()+$count*3600*24;
        $index = date('Y-m-d',$timestamp);
        echo "dateListFormatedDate['$index'] = '" . $this->getFormattedDate($timestamp) . "';\n";
    }
    ?>

    //converting weekdays to array
    var weekdays = <?php echo json_encode($weekdays); ?>;
    var arr = [];
    for (var prop in weekdays) {
        arr[prop] = (weekdays[prop].label);
    }
    weekdays = arr;
    //converting weekdays to array END

    var showBankAcc = <?php echo $_po->isPaymentCheckOnDelivery() ? '1' : '0'; ?>;
    //applyFlow
    var isAcknowledged = false;
    var returnReasons = '<?php echo Mage::helper("zolagorma")->getReturnReasons($_po, true); ?>';
    var flowAcknowledged = '<?php echo Zolago_Rma_Model_Rma::FLOW_ACKNOWLEDGED; ?>';
    //INIT DATE END

</script>
