<?php /* @var $this Zolago_Rma_Block_New_Step1 */ ?>
<?php $_helper = Mage::helper("zolagorma"); ?>
<?php $_po = $this->getPo(); ?>
<?php $_rma = $this->getRma();?>
<?php $_itemsSingle = $_rma->getItemsSingle(); ?>
<?php $_itemsConditionSingle = $_rma->getItemsConditionSingle(); ?>
<?php $items = $this->getItemList();?>
<?php $_complaint = $this->getIsCompleint();?>
<div class="steps step-1 background-wrapper box-wrapper" id="step-1" >
	<p><?php echo $_helper->__("Choose items that you want to return or complaint"); ?></p>
	<div class="rma-bordered">
		<h5 class="uppercase"><?php echo $_helper->__("Order: #%s", $_po->getIncrementId()); ?></h5>
		<div class="table-wrapper">
			<table class="data-table no-border fixed" >
			<colgroup>
				<col width="30px"/>
				<col width=70px"/>
				<col/>
			</colgroup>
			<tbody>
				<?php
				foreach ($items as $item_pack):
					foreach ($item_pack as $key => $item):
						?>
						<tr data-name="<?php echo $this->escapeHtml($item['name']); ?>" target="list" data-reasonselected="0">
							<td style="vertical-align: middle;" class="form-group form-checkbox">
								<input <?php if(isset($_itemsSingle[$item['entityId']][$key])):?>checked="checked"<?php endif;?> type="checkbox" class="css-checkbox rma-checkbox" id="rma_item_<?php echo $item['entityId'];?>_<?php echo $key;?>" name="rma[items_single][<?php echo $item['entityId'] ?>][<?php echo $key ?>]" value="true"/>
								<label class="css-label"  for="rma_item_<?php echo $item['entityId'];?>_<?php echo $key;?>"></label>
							</td>
							<td class="top">
								<?php if($thumbHelper=$this->getPoItemThumb($item['entityId'])):?>
								<img src="<?php echo $thumbHelper;?>" alt="<?php echo $this->escapeHtml($item['name']);?>"/>
								<?php endif;?>
							</td>
							<td class="top hide-success-vaild">
								<div class="desc-holder">
									<?php echo $this->escapeHtml($item['name']); ?>
									<?php if($_attributes = $this->getConfigurableAttributesByItem($item['entityId'])):?>
										<br/>
										<small>
										<?php foreach($_attributes as $_attribute):?>
											<?php echo $this->escapeHtml($_attribute['label']);?>:
											<?php echo $this->escapeHtml($_attribute['value']);?>
										<?php endforeach;?>
										</small>
									<?php endif;?>
								</div>
								<div class="reason-holder">
									<div class="condition-wrapper form-group" >
										<label for="condition-<?php echo $key; ?>-<?php echo $item['entityId']; ?>">
											<span><?php echo $this->__("Return reason");?>:</span>
										</label>
										<select class="form-control" title="<?php echo $this->__("Return reason");?>" id="condition-<?php echo $key; ?>-<?php echo $item['entityId']; ?>" name="rma[items_condition_single][<?php echo $item['entityId'] . '][' . $key . ']' ?>">
											<option value=""><?php echo $_helper->__('Select a reason...') ?></option>
											<?php foreach($_helper->getItemConditionTitlesForFront() as $_key=>$_label):?>
											<option <?php if(isset($_itemsConditionSingle[$item['entityId']][$key]) && $_itemsConditionSingle[$item['entityId']][$key]==$_key):?>selected="selected"<?php endif;?> value="<?php echo $this->escapeHtml($_key);?>"><?php echo $this->escapeHtml($_label); ?></option>
											<?php endforeach;?>
										</select>
									</div>
								</div>
							</td>
						</tr>
						<?php
					endforeach;
				endforeach;
				?>
				<tr>
					<td colspan="3" class="hide-success-vaild">
						<div class="form-group">
							<label for="rma-text"><?php echo $_helper->__("Additional informations (optional)");?>:</label>
							<textarea class="form-control" id="rma-text" name="rma[comment_text]"><?php echo $this->escapeHtml($_rma->getCommentText());?></textarea>
						</div>
					</td>
				</tr>
			</tbody>
		</table>
		</div>
	</div>
	<input type="hidden" name="rma[has_items]" value="" class="required-entry" id="rma-has-items"/>
	<div>
		<a href="<?php echo $this->getUrl("sales/po/rmalist");?>"  class="button button-third large back pull-left">
			<?php echo $_helper->__("Move back"); ?>
		</a>
		<button class="btn button button-primary next pull-right hidden">
			<?php echo $_helper->__("Next"); ?>
		</button>
		<div class="clearfix"></div>
	</div>
</div>
