<?php $_helper = Mage::helper("zolagorma"); ?>
<?php $_po = $this->getPo(); ?>
<?php $_rma = $this->getRma();?>
<?php $_shippingAddress = $_po->getShippingAddress(); ?>
<?php $_itemsSingle = $_rma->getItemsSingle(); ?>
<?php $_itemsConditionSingle = $_rma->getItemsConditionSingle(); ?>
<?php $items = $this->getItemList();?>
<?php $dateList = $this->getDateList();?>
<?php $weekdays = Mage::app()->getLocale()->getOptionWeekdays();?>
<div class="steps step-2 background-wrapper box-wrapper" id="step-2">
    <div class="rma-container">
		<?php if (($this->isDhlEnabled()) && count($dateList)) : ?>
        <div id="pickup-address-form" class="fieldset flow-return">
            <input type="hidden" name="rma[shipping_address_id]" value="<?php $_shippingAddress->getId(); ?>"/>
            <input type="hidden" name="rma[override_address]" value="0"/>

            <h3 class="legend"><?php echo $_helper->__("Confirm or change pickup address for the courier"); ?></h3>

            <div class="panel panel-default">
                <div class="panel-body">
                    <div class="current-rma-address current-addres clearfix">

                        <dl class="pull-left" id="shipping-address">
                            <dt><?php echo $_shippingAddress->getFirstname(); ?> <?php echo $_shippingAddress->getLastname(); ?></dt>
                            <dd><?php echo $_shippingAddress->getData("street"); ?></dd>
                            <dd><?php echo $_shippingAddress->getPostcode(); ?> <?php echo $_shippingAddress->getCity(); ?></dd>
                            <dd class="separator phone">
                                <?php echo $this->__('Contact phone'); ?>
                                : <span><?php echo $_shippingAddress->getTelephone(); ?>
                        </span>
                            </dd>
                        </dl>
                    </div>

                </div>
                <div class="panel-footer clearfix">
                    <a class="underline pull-right change_address shipping" href="#">
                        <?php echo $_helper->__("Change address"); ?> [dev]
                    </a>
                </div>
            </div>

        </div>
        <div id="pickup-date-form">
            <h3 class="legend"><?php echo $_helper->__("Schedule pickup date that is convenient for you"); ?></h3>
            <div class="panel panel-default">
                <div class="panel-body">
                    <div class="current-rma-date clearfix">
                        <div id="pickup-date-form" class="fieldset flow-return">

                            <label class="required" for="carrier-date"><?php echo $_helper->__("Choose the date"); ?>
                                <em>*</em></label>

                            <div class="input-box">
								<?php foreach ($dateList as $date=>$item): ?>
									<label for="carrier_date_<?php echo $date;?>">
									<input 
										type="radio" 
										name="rma[carrier_date]" 
										id="carrier_date_<?php echo $date;?>"
										value="<?php echo date('Y-m-d',$date);?>"
									/>
									<span>										
										<span class="rma-dayname"><?php echo $weekdays[date('w',$date)]['label'];?></span>	
										<span class="rma-date"><?php echo $this->getFormattedDate($date);?></span>
									</span>
									</label>
								<?php endforeach; ?>
<?php /*
                                <input type="text" value="<?php echo $_rma->getCarrierDate(); ?>"
                                       name="rma[carrier_date]" value="<?php echo $this->formatDate(); ?>"
                                       id="carrier-date" title="<?php echo $_helper->__("Choose the date"); ?>" value=""
                                       class="input-text required-entry ">
*/?>
                            </div>

                            <label class="required"
                                   for="carrier-time-from"><?php echo $_helper->__("Select the time interval (min. 3h)"); ?>
                                <em>*</em></label>

                            <div class="field">
                                <div class="input-box">
                                    <input type="hidden" name="rma[carrier_time_from]" id="carrier-time-from"
                                           value="<?php echo $_rma->getCarrierTimeFrom(); ?>"
                                           title="<?php echo $_helper->__("Choose time-from of the day"); ?>"/>
                                    <input type="hidden" name="rma[carrier_time_to]" id="carrier-time-to"
                                           value="<?php echo $_rma->getCarrierTimeTo(); ?>"
                                           title="<?php echo $_helper->__("Choose time-to of the day"); ?>"/>
                                </div>
                            </div>


                            <span id="time"></span><br/>
                            <span id="SlideMax">&nbsp;&nbsp;</span>

                            <div id="slider-range"></div>

                        </div>

                    </div>
                </div>

            </div>
        </div>

		<?php endif;?>
        <div class="fieldset">
            <h3 class="legend"><?php echo $_helper->__("Enter your account number for your order refund"); ?></h3>
            <input type="text" value="<?php echo $this->escapeHtml($_rma->getCustomerAccount()); ?>"
                   name="rma[customer_account]" value="" id="customer-account"
                   title="<?php echo $_helper->__("Bank account"); ?>" value="" class="input-text">
        </div>
    </div>
    <div class="rma-container">
        <a href="#step-1" class="button button-third large back pull-left">
            <?php echo $_helper->__("Back"); ?>
        </a>
        <button class="btn button button-primary next pull-right"
                type="button"><?php echo $_helper->__("Next"); ?></button>
    </div>
</div>



<script type="text/javascript">
    var isAcknowledged = false;
</script>
<?php  $vendor = $_po->getVendor();?>

<script type="text/javascript">
    //applyFlow
    var returnReasons = '<?php echo Mage::helper("zolagorma")->getReturnReasons($_po, true); ?>';
    var flowAcknowledged = '<?php echo Zolago_Rma_Model_Rma::FLOW_ACKNOWLEDGED; ?>';

    jQuery("select[name^='rma[items_condition_single]']").each(function(item){
        if(item.value){
            if(returnReasons[item.value].flow == flowAcknowledged){
                isAcknowledged = true;
            }
        }
    })

    if(isAcknowledged){
        jQuery('#pickup-address-form').hide();
        jQuery('#pickup-date-form').hide();
        jQuery('#pickup-address-overview').hide();
        jQuery('#pickup-date-overview').hide();
        jQuery('#overview-message').hide();
    }
    else{
        jQuery('#pickup-address-form').show();
        jQuery('#pickup-date-form').show();
        jQuery('#pickup-address-overview').show();
        jQuery('#pickup-date-overview').show();
        jQuery('#overview-message').show();
    }

    jQuery("#slider-range").slider({
        range: true,
        min: 540,
        max: 1260,
        step: 60,
        values: [660, 840],
        slide: slideTime
    });
    function slideTime(event, ui){
        var val0 = ui.values[0],
            val1 = ui.values[1];

        if( ui.values[0] == ui.values[1]) {
            return false;
        }

        formatTimeRange(val0, val1);

    }
    function formatTimeRange(from, to){
        var minutes0 = parseInt(from % 60, 10),
            hours0 = parseInt(from / 60 % 24, 10),
            minutes1 = parseInt(to % 60, 10),
            hours1 = parseInt(to / 60 % 24, 10);

        /**
         * @todo check if more then 3 hours
         */
//                                        if( size <= 180) {
//                                            jQuery("#slider-range div")
//                                                .addClass("ui-state-error")
//                                                .removeClass("ui-widget-header");
//                                            jQuery("#step-2-submit")
//                                                .attr("disabled","disabled")
//                                                .addClass("ui-state-disabled")
//                                                .removeClass("ui-state-default");
//                                            jQuery("#SlideMax").text("Cannot be less than 3 hours");
//                                        }
//                                        else {
//                                            jQuery("#slider-range div")
//                                                .addClass("ui-widget-header")
//                                                .removeClass("ui-state-error");
//                                            jQuery("#step-2-submit")
//                                                .removeAttr("disabled")
//                                                .addClass("ui-state-default")
//                                                .removeClass("ui-state-disabled");
//                                            jQuery("#SlideMax").html("&nbsp;&nbsp;");
//                                        }

        var startTime = getTime(hours0, minutes0);
        var endTime = getTime(hours1, minutes1);
        var message = 'Selected time: '+ startTime + ' - ' + endTime;
        jQuery("#time").html(message);

        jQuery('[name="rma[carrier_time_from]"]').val(startTime);
        jQuery('[name="rma[carrier_time_to]"]').val(endTime);
    }
    function getTime(hours, minutes) {
        minutes = minutes + "";
        if (minutes.length == 1) {minutes = "0" + minutes;}
        return hours + ":" + minutes;
    }
    formatTimeRange(jQuery("#slider-range").slider("values", 0), jQuery("#slider-range").slider("values", 1));


</script>