<?php /* @var $this Zolago_Po_Block_Rma */ ?>
<?php $_helper = Mage::helper("sales");?>
<?php $_order = Mage::getModel('sales/order'); ?>
<?php $baseUrl = Mage::helper("core/url")->getHomeUrl(); ?>
<?php $list = $this->getPoList(); ?>
<?php //$_po ?>
<div class="rma">
	<div class="page-title box-wrapper">
		<h1>
			<span><?php echo $this->__("Returns and complaints"); ?></span>
			<span class="back-sm"><a href="<?php echo $baseUrl ?>customer/account/index/" class="underline"><?php echo $_helper->__('back: my account'); ?> &gt;</a></span>
			<span class="back-xs"><a href="<?php echo $baseUrl ?>customer/account/index/" class="underline"><?php echo $_helper->__('back'); ?> &gt;</a></span>
		</h1>
	</div>
	<div class="background-wrapper box-wrapper rma-po-list">
		<p><?php echo $this->__("Choose package which contained products that you want to return or complaint"); ?>:</p>
		<?php if($list): ?>
			<table class="po-list-table data-table">
				<thead>
				<tr>
					<th>
						<span class="nowrap"><?php echo $this->__("Order number"); ?></span>
					</th>
					<th>
						<?php echo $this->__("Date"); ?>
					</th>
					<th>
						<?php echo $this->__("Shop"); ?>
					</th>
					<th>
						<?php echo $this->__("Products"); ?>
					</th>
					<th>
					</th>
				</tr>
				</thead>
				<tbody>
				<?php foreach($list as $po): ?>
					<?php /* @var $po Zolago_Po_Model_Po */ ?>
					<tr>
						<td>
							<span class="nowrap"><?php echo $po->getIncrementId(); ?></span>
						</td>
						<td>
							<span class="nowrap"><?php echo Mage::helper('core')->formatDate($po->getCreatedAt(), 'medium', false); ?></span>
						</td>
						<td>
							<span class="uppercase"><?php echo $po->getVendorName(); ?></span>
						</td>
						<td>
							<table class="po-items-table">
								<tbody>
									<?php foreach($po->getItemsCollection() as $item):?>
										<?php $item = $item->getOrderItem(); ?>
										<?php if(!$item->getParentItem()): ?>
											<?php $name = $this->escapeHtml($item->getName()); ?>
											<tr>
												<td><img src="<?php echo $this->getThumbnailUrl($item); ?>" alt="<?php echo $name; ?>" /></td>
												<td>
												<?php echo $name; ?><br/>
												<?php foreach($this->getProductAttributes($item->getProductOptions()) as $_option): ?>
													<span class="po-attribute"><?php echo $this->escapeHtml($_option['label']); ?>: <?php echo $this->escapeHtml($_option['value']); ?></span><br/>
												<?php endforeach;?>
												</td>
											</tr>
										<?php endif; ?>
									<?php endforeach;?>
								</tbody>
							</table>
						</td>
						<td>
							<a class="button button-third large" href="<?php echo $this->getUrl('sales/po/newrma/',array('po_id'=>$po->getId()));?>"><?php echo $this->__("Select"); ?></a>
						</td>
					</tr>
				<?php endforeach; ?>
				</tbody>
			</table>
			<div class="bottom-links">
				<a class="button button-third large" href="<?php echo Mage::getUrl("customer/account");?>">
					<i class="glyphicon glyphicon-chevron-left"></i>
					<?php echo $_helper->__('back') ?>
				</a>
			</div>
		<?php else: ?>
			<p><?php echo $this->__("No delivered orders"); ?></p>
		<?php endif; ?>
	</div>
</div>