<?php
/** @var $this Zolago_Modago_Block_Promotions_Login */
/** @var Zolago_Customer_Helper_Data $_hlp */
$_hlp = Mage::helper("zolagocustomer");
?>
<div class="col-sm-6 column-block login-column col-sm-offset-3">
	<div class="main bg-w equalBlock col-01">
		<form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="login-form" class="form-horizontal" autocomplete="off"
		      role="form">
			<?php echo $this->getBlockHtml('formkey'); ?>
			<section class="section clearfix">
				<header class="title-section">
					<?php echo $this->getChildHtml('login-header'); ?>
				</header>
				<ul class="form-list clearfix">
					<li>
						<div class="form-group">
							<label for="email"
							       class="col-md-3 col-sm-12 col-xs-12 control-label"><?php echo $_hlp->__("Email address"); ?></label>

							<div class="col-md-9 col-sm-12 col-xs-12">
								<input type="email" name="login[username]" value="" id="email"
								       class="form-control email input-text required-entry validate-email" autocomplete="off" title=""
								       tabindex="1">
							</div>
						</div>
					</li>
					<li>
						<div class="form-group">
							<label for="pass"
							       class="col-md-3 col-sm-12 col-xs-12 control-label required"><?php echo $_hlp->__("Password"); ?></label>

							<div class="col-md-9 col-sm-12 col-xs-12">
								<div class="inner-form-group">
									<a class="forgot-password underline visible-sm visible-xs"
									   href="<?php echo $this->getForgotPasswordUrl() ?>"
									   style="left: 186px;"><?php echo $this->__('Forgot Your Password?') ?></a>
									<input type="password" name="login[password]"
									       class="form-control input-text required-entry validate-password login-text-field" id="pass"
									       title=""
									       autocomplete="off" tabindex="2">
									<a class="forgot-password underline hidden-sm hidden-xs"
									   href="<?php echo $this->getForgotPasswordUrl() ?>"
									   style="left: 186px;"><?php echo $_hlp->__("You don't remember password?"); ?></a>
								</div>
							</div>
						</div>
					</li>
					<button type="submit" name="send"
					        class="button button-primary large link pull-right"><?php echo $_hlp->__('Login') ?></button>
				</ul>
			</section>
		</form>
	</div>
</div>
<script>
	jQuery(document).ready(function () {
		var loginForm = jQuery("#login-form");
		if (loginForm.length) {
			loginForm.validate(Mall.validate.getOptions({
				rules: {
					"login[username]": {
						required: true,
						email: true
					},
					"login[password]": {
						required: true
					}
				}
			}));
		}
		jQuery.extend(jQuery.validator.messages, {
			required: "<?php echo $_hlp->__('This field is required') ?>",
			email: "<?php echo $_hlp->__('Valid email is required.') ?>"
		});
	});
</script>