<?php
/** @var Zolago_Modago_Block_Mypromotions $this */
/** @var Zolago_Salesrule_Helper_Data $helper */
$helper = Mage::helper('zolagosalesrule');
$helperModago = Mage::helper("zolagomodago");
$galleryLogo = $this->getGalleryLogo();

?>
<?php echo $this->getChildHtml("zolago_modago_mypromotions_header"); ?>

<div id="content" class="container-fluid mypromotions-account-create account-create<?php if ($this->isLogged()): ?> logged-in<?php endif; ?>">
	<div class="row">
		<div id="content-main" class="section">
			<?php if ($this->isLogged()): ?>
				<?php $list = $this->getPromotionList(); ?>
				<div class="container-fluid">
					<div class="row">
						<section id="mypromotions-list" class="main col-lg-12 col-md-12 col-sm-12 col-xs-12 mypromotions-logged-in">
							<?php //Do not remove, only hide (by Staszek) ?>
							<!--							<header class="title-section">-->
							<!--								--><?php //echo $this->getLayout()->createBlock('cms/block')->setBlockId('mypromotions_list_header')->toHtml(); ?>
							<!--							</header>-->


							<?php if (count($list)): ?>
								<div id="promo_list">
									<?php foreach ($list as $item): ?>
										<?php $ruleItem = $item->getData("ruleItem"); ?>
										<div class="promo_item col-xs-4 col-sm-4 col-md-3 col-lg-3">
											<div class="promo_item_box">

												<div class="promo_info">
													<?php $imageName = $ruleItem->getCouponImage(); ?>

													<?php $imageResized = $helper->getResizedPromotionImage($imageName); ?>

													<figure class="promo_img">
														<img src="<?php echo $imageResized; ?>" alt="<?php echo $ruleItem->getName(); ?>" />
													</figure>

													<div class="promo_logo">
														<?php // Logo - jeśli jest LP w kontekście vendora - logo vendora, jeśli nie - logo modago ?>
														<?php if ($logoVendor = $ruleItem->getLogoVendor()): ?>
															<div class="promo_logo_img" style="background-image: url(<?php echo $logoVendor; ?>)"></div>

														<?php else: ?>
															<div class="promo_logo_img" style="background-image: url(<?php echo $galleryLogo; ?>)"></div>
														<?php endif; ?>
													</div>


													<h3 class="promo_name" title="<?php echo $ruleItem->getName(); ?>">
														<?php echo $ruleItem->getName(); ?>
													</h3>

													<div class="promo_see_more">
														<a><?php echo $helperModago->__("See more"); ?> &gt;&gt;</a>
													</div>

												</div>
											</div>
										</div>
										<?php unset($ruleItem); unset($logoVendor); ?>
									<?php endforeach; ?>
								</div>
							<?php else: ?>
								<div id="no_promo_list">
									<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('mypromotions_nocoupons')->toHtml(); ?>
								</div>
							<?php endif; ?>
							</section>
						</div>
					</div>

				<?php if(!$this->isSubscribed() && $helper->areCouponsForCustomerAvailable($this->getCustomerId())): ?>
					<div class="container-fluid">
						<div class="row">
							<section class="main bg-w mypromotions-cms col-lg-8 col-md-10 col-sm-12 col-xs-12 col-lg-push-2 col-md-push-1">
								<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('mypromotions_notsubscribed')->toHtml(); ?>
								<div class="row">
									<?php echo $this->getChildHtml('mypromotions.newsletter'); ?>
								</div>
							</section>
						</div>
					</div>
				<?php endif; ?>
				<?php //echo $this->getCmsBlock(); // Do not remove, only hide (by Staszek) ?>

			<?php elseif ($this->isPersistent()): ?>
				<?php echo $this->getChildHtml('mypromotions.gotologin'); ?>
				<?php echo $this->getCmsBlock(); ?>
				<?php echo $this->getChildHtml('mypromotions.gotoregister'); ?>
			<?php
			else: ?>
				<?php echo $this->getCmsBlock(); ?>
				<?php echo $this->getChildHtml('mypromotions.register'); ?>
				<?php echo $this->getChildHtml('mypromotions.gotologin'); ?>
			<?php endif; ?>
		</div>
	</div>
</div>