<?php
/** @var Zolago_Modago_Block_Promotions_Newsletter $this */
/** @var Zolago_Customer_Helper_Data $_hlp */
$_hlp = Mage::helper("zolagocustomer");
?>
<form action="<?php echo $this->getUrl('newsletter/manage/save') ?>" method="post" class="mypromotions-newsletter">
	<?php echo $this->getBlockHtml('formkey'); ?>
	<div class="form-group form-checkbox small text-align-left mypromotions-newsletter-checkbox">
		<input type="checkbox" id="is_subscribed" class="css-checkbox" name="is_subscribed">
		<label for="is_subscribed" class="css-label agreement-label">
			<?php echo Mage::getStoreConfig('customer/agreements/newsletter'); ?>
		</label>
	</div>
	<div class="row action mypromotions-newsletter-button">
		<div class="col-sm-12">
			<button type="submit" class="button button-primary large link">
				<?php echo $_hlp->__('Save') ?>
			</button>
		</div>
	</div>
</form>
<script type="text/javascript">
	Mall.translate.add(
		"You must check this box",
		"<?php echo $_hlp->__("You must check this box"); ?>"
	);

	jQuery(document).ready(function () {
		var form = jQuery(".mypromotions-newsletter");

		if (form.length) {
			form.validate(Mall.validate.getOptions({
				rules: {
					is_subscribed: {
						required: true
					}
				},
				messages: {
					is_subscribed: {
						required: Mall.translate.__("You must check this box")
					}
				}
			}));
			form.submit(function () {
				return
			});
		}
	});
</script>