<?php
/**/
$_session = Mage::getSingleton('udropship/session');
$_vendor = Mage::registry('reset_vendor');
?>
<div class="col-md-12">
    <div class="">
        <div style="margin-top:100px;">
            <!--=== Page Header ===-->
            <div class="page-header">
                <div class="page-title">
                    <h3>Akceptacja regulaminu</h3>
                </div>
            </div>


            <div class="row">
                <div class="col-md-12">
                    <form class="form-horizontal" method="post">
                        <div class="widget box">
                            <div class="widget-header">
                                <h4>Download documents</h4>
                            </div>
                            <div class="widget-content">
                                <div class="form-group">
                                    <label class="col-md-3 control-label">File:</label>
                                    <div class="col-md-9">
                                        <input type="file" data-style="fileinput" />
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>