<?php
/* @var $this GH_Regulation_Block_Dropship_Regulation_Accept */

$_session = Mage::getSingleton('udropship/session');
$_vendor = Mage::registry('reset_vendor');
$_helper = Mage::helper("ghregulation");

$token = $this->getRequest()->getParam('key');
/* @var $docs GH_Regulation_Model_Resource_Regulation_Document_Collection */
$docs = $this->getDocumentsList();

?>
<link rel="stylesheet" href="<?php echo Mage::getBaseUrl(); ?>skin/frontend/base/default/font-awesome-4.4.0/css/font-awesome.min.css">
<div class="col-md-8 col-md-offset-2 col-lg-8 col-lg-offset-2">
    <div class="">
        <div style="margin-top:100px;">
            <div class="row">
                <div class="col-md-12">
                    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
                    <form class="form-horizontal" id="accept_regulation_documents_form" action="<?php echo $this->getUrl("*/*/acceptPost"); ?>" method="post" enctype="multipart/form-data">
                        <input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
                        <input type="hidden" name="vendor" value="<?php echo $this->getVendor()->getId(); ?>" />
                        <input type="hidden" name="key" value="<?php echo $token; ?>" />
                        <div class="widget box">
                            <div class="widget-header" style="text-align: center;">
                                <h4><?php echo $_helper->__("Accept regulation"); ?></h4>
                            </div>
                            <div class="widget-content">
                                <div class="col-md-12">
                                    <?php echo $this->getAcceptBlock(); ?>
                                </div>
                            </div>
                            <div class="widget-content">
                                <div class="col-md-12">
                                    <p><?php echo $_helper->__("I %s declare:", $this->getVendor()->getCompanyName()); ?></p>

                                    <label class="css-label col-md-12">
                                        <input type="radio" class="" name="accept_regulations_role" value="single"/>
                                        <?php echo $_helper->__("I am authorized to represent single %s", $this->getVendor()->getCompanyName()); ?>
                                    </label>

                                    <label class="css-label col-md-12">
                                        <input type="radio" class="" name="accept_regulations_role" value="proxy"/>
                                        <?php echo $_helper->__("I have power to accept the regulations MODAGO."); ?>
                                    </label>

                                    <div class="col-md-12"></div>
                                    <div class="add_regulation_document hidden col-md-12">
                                        <label class="css-label">
                                            <?php echo $_helper->__("Upload a scan of regulations"); ?>
                                            <input type="file" data-style="fileinput-custom"
                                                   name="regulation_document"/>

                                            <input type="hidden" name="regulation_document_new_name" value=""/>

                                            <div class="add_regulation_document_preview"></div>
                                        </label>
                                    </div>
                                </div>
                            </div>
                            <?php if ($docs->getSize() > 0): ?>
                                <div class="widget-content">
                                    <div class="col-md-12">
                                        <p><?php echo $_helper->__("Download the regulations to become familiar with their content:"); ?></p>
                                        <ul class="regulation-docs-list">
                                            <?php /** @var GH_Regulation_Model_Regulation_Document $doc */
                                            foreach ($docs as $doc): ?>
                                                <li>
                                                    <i class="fa fa-file-pdf-o fa-lg"></i>
                                                    <?php echo ucfirst($doc->getName()); ?> <a
                                                        href="<?php echo $doc->getVendorUrlByToken($token, $doc->getId(), $this->getVendor()->getId()); ?>"
                                                        download="<?php echo $doc->getFileName(); ?>"><?php echo $_helper->__("download"); ?></a>
                                                </li>
                                            <?php endforeach; ?>
                                        </ul>
                                    </div>
                                </div>
                            <?php endif; ?>
                            <div class="widget-content">
                                <div class="col-md-12">
                                    <p>
                                        <?php echo $_helper->__("I %s %s  declare", $this->getVendor()->getExecutiveFirstname(), $this->getVendor()->getExecutiveLastname()); ?>
                                    </p>
                                </div>
                                <div class="col-md-12">
                                    <label class="css-label col-md-12">
                                        <input type="checkbox" class="uniform" name="accept_regulations"/>
                                        <?php echo $_helper->__("I accept the regulations", $this->getVendor()->getCompanyName()); ?>
                                    </label>
                                </div>
                            </div>
                        <div class="form-actions">
                            <button type="submit" id="filter_submit" class="btn btn-primary pull-right" >
                                <span><span><?php echo $_helper->__("Accept regulations"); ?></span></span>
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    jQuery(document).ready(function () {
        handleProxyCheck(jQuery("[name='accept_regulations_role']"));
        jQuery("[name='accept_regulations_role']").change(function () {
                handleProxyCheck(jQuery(this));
        });
    });

    jQuery("#accept_regulation_documents_form").validate({
        rules: {
            accept_regulations: {
                required: true
            },
            accept_regulations_role: {
                required: true
            },
            'regulation_document': {extension: 'jpe?g,png,pdf', fileSize: <?php echo GH_Regulation_Helper_Data::REGULATION_DOCUMENT_MAX_SIZE; ?>, required:'[name=accept_regulations_role][value=proxy]'}
        },
        messages: {
            'regulation_document': {
                extension: '<?php echo $_helper->__("File must be JPG, PNG or PDF"); ?>',
                fileSize: '<?php echo $_helper->__("File too large. File must be less than %sMB.", GH_Regulation_Helper_Data::REGULATION_DOCUMENT_MAX_SIZE); ?>'
            }
        },
        errorPlacement: function (error, element) {
            element.closest("[class^='col-']").append(error);
        }
    });

    function handleProxyCheck(element) {
        if(element.val() == "proxy"){
            jQuery(".add_regulation_document").removeClass("hidden");
        } else {
            jQuery(".add_regulation_document").addClass("hidden");
        }

    }

    jQuery("input[name=regulation_document]").on('change', function (e) {
        e.preventDefault();
        jQuery(".add_regulation_document_preview").html("");
        jQuery("[name=regulation_document_new_name]").val("");

        var formData = new FormData(jQuery('#accept_regulation_documents_form')[0]);

        jQuery.ajax({
            url: '<?php echo $this->getSaveVendorDocumentUrl(); ?>',
            type: 'POST',
            data: formData,
            cache: false,
            contentType: false,
            processData: false,
            //dataType: 'json',
            'success': function(response) {},
            'error': function(response) {}
        }).done(function(response){
            if (response.status == 1) {
                jQuery(".add_regulation_document_preview")
                    .html('<a href="' + response.content.link + '" target="_blank">' + response.content.name + '</a>');
                jQuery("[name=regulation_document_new_name]").val(response.content.new_name);
            }
            if (response.status == 0) {
                //jQuery(".add_regulation_document_preview").html(response.content);
                jQuery("[name=regulation_document_new_name]").val("");
            }
        });
    });

    jQuery(document).on('click',"button[type=submit]", function (e) {
        e.preventDefault();

        if(jQuery("form#accept_regulation_documents_form").valid()){
            bootbox.confirm({
                title: '',
                message: '<?php echo $_helper->__("Are you sure?"); ?>',
                buttons: {
                    'cancel': {
                        label: '<?php echo $_helper->__("Cancel"); ?>'
                    },
                    'confirm': {
                        label: '<?php echo $_helper->__("Save"); ?>'
                    }
                },
                callback: function(result) {
                    if (result) {
                        jQuery("form#accept_regulation_documents_form").submit();
                    }
                }
            });
        }
    });
</script>
<style>
    label.error {
        color: #e84c3d;
        font-size: 12px;
        font-weight: normal;
        line-height: 1 !important;
    }
</style>