<?php
Mage::getBlockSingleton('zolagocatalog/breadcrumbs');
?>
<section id="main" class="">
    <header data-test="1" id="header-main">
        <div class="container-fluid">
            <div class="row hidden-xs">
                <div id="breadcrumbs" class="col-sm-12 ">
                    <?php echo $this->getChildHtml('breadcrumbs') ?>
                </div>
            </div>
        </div>
    </header>
</section>