<?php
/** @var Zolago_Modago_Block_Page_Header_Rightmenu $this */
$userAccountUrl = Mage::getUrl('customer/account', array("_no_vendor"=>true));
$userAccountUrlOrders = Mage::getUrl('sales/order/process', array("_no_vendor"=>true));
$favoritesUrl = Mage::getUrl("wishlist", array("_no_vendor"=>true));
$checkoutCartUrl = Mage::getUrl('checkout/cart', array("_no_vendor"=>true));
?>

<!-- NAV RIGHT -->
<div id="header_top_block_right">
    <div class="header_bottom cart-design-2">
            <div id="user_menu" class="pull-right">
                <ul class="user-navigation pull-right">
                    <li id="link_menu" class="hidden-sm hidden-md hidden-lg not-open">
                        <a href="" class="toggleMenu sb-toggle-left">
                            <i class="fa fa-bars"></i>
                        </a>
                    </li>
                    <li id="link_account">
                        <a href="<?php echo $userAccountUrl; ?>">
                            <i class="fa fa-user"></i>
                        </a>
                    </li>
                    <li id="link_search" class="not-open hidden-sm hidden-md hidden-lg">
                        <a class="dropdown-toggle"  data-dropdown="#dropdown-search" id="toggleSearch">
                            <i class="fa fa-search"></i>
                        </a>
                    </li>
                    <li id="link_basket" class="basket-dropdown shopping-cart-widget">
                        <a class="dropdown-toggle" id="link_basket_icon" data-dropdown="#dropdown-basket" href="<?php echo $checkoutCartUrl; ?>">
                            <div class="badgeHolder">
                                <span class="badge"></span>
                                <i class="fa fa-shopping-cart"></i>
                            </div>
                        </a>
                    </li>
                </ul>
            </div>
            <?php echo $this->getChildHtml('page.header.search'); ?>
    </div>
</div>