<?php /*  @var $this Zolago_Catalog_Block_Campaign_LandingPage */   ?>

<?php $images = $this->getData("campaign_landing_page");  ?>

<?php $banners = isset($images->banners) ? (array)$images->banners : array(); ?>


<?php if (!empty($banners)): ?>
    <?php $desktop = $banners[1]["path"]; ?>
    <?php $mobile = $banners[2]["path"]; ?>
    <div style="margin: 10px 0;">
        <div class="hidden-xs">
            <img style="width:100%;height: 200px;"
                 src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . $desktop; ?>"
                 title="<?php echo $images->name_customer; ?>" alt="<?php echo $images->name_customer; ?>"/>
        </div>
        <div class="visible-xs">
            <img style="width:100%;height: 200px;"
                 src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . $mobile; ?>"
                 title="<?php echo $images->name_customer; ?>" alt="<?php echo $images->name_customer; ?>"/>
        </div>
    </div>
<?php endif; ?>