<?php
$sHlp = Mage::helper('core/string');
?>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php $_questions = $this->getQuestionsCollection(); ?>
<div class="page-title title-buttons">
    <h1><?php echo $this->__('My Questions') ?></h1>
    <button type="button" title="<?php echo $this->__('Ask New Question') ?>" class="button" onclick="window.location='<?php echo $this->getNewUrl() ?>';"><span><span><?php echo $this->__('Ask New Question') ?></span></span></button>
</div>
<?php if($_questions->getSize()): ?>
<?php echo $this->getChildHtml('toolbar') ?>
<table class="data-table" id="my-questions-table">
    <col width="150" />
    <col />
    <col />
    <col width="1" />
    <thead>
    <tr>
        <th><?php echo $this->__('Details') ?></th>
        <th><?php echo $this->__('Question Text') ?></th>
        <th><?php echo $this->__('Answer Text') ?></th>
        <th>&nbsp;</th>
    </tr>
    </thead>
    <tbody>
        <?php $_odd = ''; ?>
        <?php foreach ($_questions as $_question): ?>
    <tr>
        <td>
            <h5><?php echo $this->__('VENDOR') ?></h5>
            <span class="nobr"><?php echo $_question->getVendorName() ?></span>
            <h5><?php echo $this->__('QUESTION DATE')?></h5>
            <span class="nobr"><?php echo $this->formatDate($_question->getQuestionDate()) ?></span>
            <?php if ($_question->canCustomerViewAnswer() && !$_question->isEmptyAnswerDate()): ?>
            <h5><?php echo $this->__('ANSWER DATE')?></h5>
            <?php echo $this->formatDate($_question->getAnswerDate(), Mage_Core_Model_Locale::FORMAT_TYPE_SHORT, true); ?>
            <?php endif ?>
            <?php if ($_question->getShipmentId()): ?>
            <h5><?php echo $this->__('SHIPMENT')?></h5>
            <a href="<?php echo $this->getShipmentUrl($_question)?>"><?php echo $this->__('#%s for order #%s', $_question->getShipmentIncrementId(), $_question->getOrderIncrementId())?></a>
            <?php endif ?>
            <?php if ($_question->getProductId()): ?>
            <h5><?php echo $this->__('PRODUCT')?></h5>
            <a href="<?php echo $this->getProductUrl($_question)?>"><?php echo $_question->getProductName()?></a>
            <?php endif ?>
        </td>
        <td><?php echo $sHlp->truncate($_question->getQuestionText(), 30) ?></td>
        <td>
            <?php if ($_question->canCustomerViewAnswer()): ?>
            <?php echo $sHlp->truncate($_question->getAnswerText(), 30); ?>
            <?php else: ?>
            &nbsp;
            <?php endif ?>
        </td>
        <td class="a-center">
            <span class="nobr"><a href="<?php echo $this->getViewUrl($_question) ?>"><?php echo $this->__('View') ?></a>
            </span>
        </td>
    </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<script type="text/javascript">decorateTable('my-questions-table');</script>
<?php echo $this->getChildHtml('toolbar') ?>
<?php else: ?>
<p><?php echo $this->__('You have no questions.'); ?></p>
<?php endif ?>
