<?php /* @var $this Zolago_Modago_Block_Checkout_Address */ ?>

<?php echo $this->getStep1Sidebar(); ?>

<div id="content-main" class="col-lg-9 col-md-8 col-sm-12 col-xs-12 col-lg-pull-3 col-md-pull-4 section">
	<section class="main bg-w">
		<header class="title-section">
			<h2>Podaj dane do realizacji</h2>
		</header>
		<form action="<?php echo $this->getSaveUrl(); ?>" class="form" id="co-address">
			<fieldset>
				<legend class="first">Dane osoby zamawiającej:</legend>

				<div class="form-group clearfix">
					<div class="row">
						<label class="col-sm-3" for="for_first_name">Imię</label>
						<div class="col-sm-5">
							<input type="text" class="form-control firstName hint" id="for_first_name" title="" name="firstname" data-rule-required="true" data-original-title="Wprowadź imię">
						</div>
					</div>

				</div>
				<div class="form-group clearfix border-top">
					<div class="row">
						<label class="col-sm-3" for="for_last_name">Nazwisko</label>
						<div class="col-sm-5">
							<input type="text" class="form-control lastName hint" id="for_last_name" title="" name="lastname" data-rule-required="true" data-original-title="Wprowadź nazwisko">
						</div>
					</div>
				</div>
				<div class="form-group clearfix border-top">
					<div class="row">
						<label class="col-sm-3" for="email">Adres e-mail</label>
						<div class="col-sm-5">
							<input type="email" class="form-control email hint" id="email" title="" name="email" data-original-title="Adres e-mail">
						</div>
					</div>
				</div>
				<div class="form-group clearfix border-top">
					<div class="row">
						<label class="col-sm-3" for="phone_number">Numer telefonu</label>
						<div class="col-sm-5">
							<input type="text" class="form-control phone hint" id="phone_number" title="" name="phone_number" data-original-title="Numer telefonu potrzebujemy tylko do kontaktu dotyczącego zamówienia np. dla kuriera dostarczającego przesyłkę.">
						</div>
					</div>
				</div>
			</fieldset>

			<fieldset>
				<legend>Dane do wysyłki:</legend>
				<div class="form-group form-checkbox small">
					<input type="checkbox" name="rodzaj" id="orders_someone_else" class="css-checkbox orders_someone_else">
					<label for="orders_someone_else" class="css-label orders_someone_else">Zamawiam dla kogoś innego - chcę podać inne dane kontaktowe odbiorcy</label>
				</div>

				<div class="form-group clearfix hidden border-top orders_someone_else">
					<div class="form-group clearfix">
						<div class="row">
							<label class="col-sm-3" for="for_first_name">Imię</label>
							<div class="col-sm-5"><input type="text" class="form-control firstName hint" id="for_first_name" title="" name="firstname" data-original-title="Wprowadź imię"></div>
						</div>

					</div>
					<div class="form-group clearfix border-top">
						<div class="row">
							<label class="col-sm-3" for="for_last_name">Nazwisko</label>
							<div class="col-sm-5">
								<input type="text" class="form-control lastName hint" id="for_last_name" title="" name="lastname" data-original-title="Wprowadź nazwisko">
							</div>
						</div>
					</div>
				</div>

				<div class="form-group clearfix border-top hidden orders_someone_else">
					<div class="row">
						<label class="col-sm-3" for="phone_number">Numer telefonu</label>
						<div class="col-sm-5">
							<input type="text" class="form-control" id="phone_number" title="" data-original-title="Numer telefonu potrzebujemy tylko do kontaktu dotyczącego zamówienia np. dla kuriera dostarczającego przesyłkę.">
						</div>
					</div>
				</div>

				<div class="form-group border-top clearfix">
					<div class="row">
						<label class="col-sm-3" for="street">Ulica i numer</label>
						<div class="col-lg-7 col-md-5 col-sm-5">
							<input type="text" class="form-control street" id="street" title="" name="street" data-original-title="Ulica i numer">
						</div>
					</div>
				</div>

				<div class="form-group clearfix border-top">
					<div class="row">
						<label class="col-sm-3" for="zip_code">Kod pocztowy</label>
						<div class="col-sm-5">
							<input type="text" class="form-control zipcode" id="zip_code" title="" name="zipcode" data-original-title="Kod pocztowy">
						</div>
					</div>
				</div>

				<div class="form-group clearfix border-top">
					<div class="row">
						<label class="col-sm-3" for="city">Miejscowość</label>
						<div class="col-sm-5">
							<input type="text" class="form-control city hint" id="city" title="" name="city" data-original-title="Miejscowość">
						</div>
					</div>
				</div>

				<div class="form-group clearfix border-top">
					<div class="row">
						<label class="col-sm-3 double-line" for="firm_name">Nazwa firmy<br>(opcjonalnie)</label>
						<div class="col-lg-7 col-md-5 col-sm-5">
							<input type="text" class="form-control firm hint" id="firm_name" title="" name="firm_name" data-original-title="Nazwa firmy">
						</div>
					</div>
				</div>
			</fieldset>
			<fieldset>
				<legend>Dokument sprzedaży:</legend>
				<div class="form-group form-checkbox small">
					<input type="checkbox" name="invoice_vat" id="invoice_vat" class="css-checkbox invoice_vat">
					<label for="invoice_vat" class="css-label">Chcę otrzymać fakturę VAT</label>
				</div>
			</fieldset>

			<fieldset id="invoice_data">

				<div class="form-group form-checkbox small">
					<input type="checkbox" name="invoice_data_address" id="invoice_data_address" class="css-checkbox invoice_data_address" checked="">
					<label for="invoice_data_address" class="css-label">Adres taki sam jak adres wysyłki</label>
				</div>

				<div class="form-group clearfix border-top">
					<div class="row">
						<label class="col-sm-3" for="invoice_data_firm_name">Nazwa firmy</label>
						<div class="col-lg-7 col-md-5 col-sm-5">
							<input type="text" class="form-control firm hint" id="invoice_data_firm_name" title="" name="invoice_data_firm_name" data-original-title="Nazwa firmy">
						</div>
					</div>
				</div>

				<div class="form-group clearfix border-top">
					<div class="row">
						<label class="col-sm-3" for="invoice_data_nip">NIP</label>
						<div class="col-lg-3 col-md-5 col-sm-5">
							<input type="text" class="form-control nip hint" id="invoice_data_nip" title="" data-original-title="NIP">
						</div>
					</div>
				</div>

				<div class="form-group border-top clearfix">
					<div class="row">
						<label class="col-sm-3" for="invoice_data_street">Ulica i numer</label>
						<div class="col-lg-7 col-md-5 col-sm-5">
							<input type="text" class="form-control street" id="invoice_data_street" title="" name="invoice_data_street" data-original-title="Ulica i numer">
						</div>
					</div>
				</div>

				<div class="form-group clearfix border-top">
					<div class="row">
						<label class="col-sm-3" for="invoice_data_zip_code">Kod pocztowy</label>
						<div class="col-sm-5">
							<input type="text" class="form-control zipcode" id="invoice_data_zip_code" title="" name="invoice_data_zip_code" data-original-title="Kod pocztowy">
						</div>
					</div>
				</div>

				<div class="form-group clearfix border-top">
					<div class="row">
						<label class="col-sm-3" for="invoice_data_city">Miejscowość</label>
						<div class="col-sm-5">
							<input type="text" class="form-control city hint" id="invoice_data_city" title="" name="invoice_data_city" data-original-title="Miejscowość">
						</div>
					</div>
				</div>

			</fieldset>

			<fieldset id="remember_data">
				<legend>Zapamiętaj dane (opcjonalnie):</legend>
				<div class="row">
					<div class="col-sm-12">
						<div class="row">
							<div class="col-sm-6">  

								<p>Ustaw hasło by łatwiej śledzić stan realizacji zamówień i szybciej kupować następnym razem.</p>
							</div>
						</div> 
					</div>
				</div> 
				<div class="row">
					<div id="add_pass" class="col-sm-6">

						<div class="form-group clearfix">
							<div class="row">
								<label class="col-sm-6" for="pass">Hasło</label>
								<div class="col-sm-6">
									<input type="password" class="form-control password" id="pass" title="" data-original-title="Hasło musi mieć przynajmniej 6 znaków, nie może zawierać spacji.">
								</div>
							</div>
						</div>


					</div> 
					<div class="col-sm-1 hidden-xs">
						Lub
					</div>
					<div id="login_social" class="col-sm-5">
						<p>Nie chcesz podawać hasła? Nie musisz:</p>
						<a href="#" class="button btn-social g-plus small">Zaloguj się</a>
						<a href="#" class="button btn-social fb small">Zaloguj się</a>
					</div>  
				</div>
			</fieldset>
			<div class="row">
				<div class="form-group form-checkbox small text-align-left">
					<input type="checkbox" id="agree" class="css-checkbox invoice_vat" name="agree" required="">
					<label for="agree" class="css-label">Wyrażam zgodę na przetwarzanie moich danych osobowych przez Zolago Group Sp. Z o.o. z siedzib w Warszawie (Barkocińska 6 03-534), w celu świadczenia przez ni usług w ramach Modago.pl</label>
				</div>

				<div class="form-group form-checkbox small text-align-left">
					<input type="checkbox" id="declare" class="css-checkbox invoice_vat" name="declare" required="">
					<label for="declare" class="css-label">Oświadczam, że zapoznałem(am) się z Regulaminem sklepu Modago.pl i akceptuję jego postanowienia.</label>
				</div>
			</div>
			<div class="row action">
				<div class="col-sm-6">
					<a id="back" class="button button-third large pull-left">Wróć</a>
				</div>
				<div class="col-sm-6">
					<button class="button button-primary large link pull-right" id="step-0-submit">Dalej</button>
				</div>
			</div>



		</form>
	</section>

</div>  

