<?php $_helper = Mage::helper("zolagorma"); ?>

<?php $_rma = $this->getRma();?>

<?php $_selectedShipping = $this->getSelectedShippingAddress();?>
<?php $dateList = $this->getDateList($_selectedShipping);?>
<?php $weekdays = Mage::app()->getLocale()->getOptionWeekdays();?>


<script type="text/javascript">
    //INIT DATA
    var rmaCarrierTimeFrom = '<?php echo $_rma->getCarrierTimeFrom(); ?>';
    var rmaCarrierTimeTo = '<?php echo $_rma->getCarrierTimeTo(); ?>';
    var dateList = <?php echo json_encode($dateList); ?>;
    var dateListFormatedDate = [];

    <?php // formatted date for next 20 (max) days from today
    for($count = 0; $count < 20 ; $count++) {
        $timestamp = time()+$count*3600*24;
        $index = date('Y-m-d',$timestamp);
        echo "dateListFormatedDate['$index'] = '" . $this->getFormattedDate($timestamp) . "';\n";
    }
    ?>


    //converting weekdays to array
    var weekdays = <?php echo json_encode($weekdays); ?>;
    var arr = [];
    for (var prop in weekdays) {
        arr[prop] = (weekdays[prop].label);
    }
    weekdays = arr;
    //converting weekdays to array END

    //applyFlow
    var isAcknowledged = false;

    var ajaxLoaderSkinUrl = '<?php echo $this->getSkinUrl("images/modago-ajax-loader.gif"); ?>';
    //INIT DATE END

    jQuery(function () {
        // Address book handling
        var addressBook = new Mall.customer.AddressBook();

        addressBook.setAddressBook(<?php echo $this->getCustomerAddressesJson(); ?>);
		<?php if($_defaultShipping=$this->getDefaultShipping()):?>
        addressBook.setDefaultShipping(<?php echo $this->asJson($_defaultShipping->getId())?>);
		<?php endif;?>
        Mall.rma.edit.addressbook.setAddressBook(addressBook);

        Mall.rma.edit.setNotAvailableText('<?php echo $_helper->__('Not available');?>');
        Mall.rma.edit.init();
        <?php if(!$this->isDhlEnabled()): ?>
            Mall.rma.edit.dhlDisabled = true;
        <?php endif; ?>
    });
</script>