<?php
/**
 * Author: Paweł Chyl <pawel.chyl@orba.pl>
 * Date: 23.09.2014
 */

?>

<div class="section clearfix hidden-xs account-nav">
    <h3 class="open"><?php echo $this->__('My Account'); ?></h3>
    <ul class="nav nav-pills nav-stacked">
    <?php $_links = $this->getLinks(); ?>
    <?php $_index = 1; ?>
    <?php $_count = count($_links); ?>
    <?php foreach ($_links as $_link): ?>
        <?php $_last = ($_index++ >= $_count); ?>
        <?php if ($this->isActive($_link)): ?>
            <li><a href="<?php echo $_link->getUrl() ?>" class="simple active"><?php echo $_link->getLabel() ?></a></li>
        <?php else: ?>
            <li><a href="<?php echo $_link->getUrl() ?>" class="simple"><?php echo $_link->getLabel() ?></a></li>
        <?php endif; ?>
    <?php endforeach; ?>
    </ul>
</div>