<fieldset class="default_pay">
    <h4>Sposób płatności:</h4>
    <!-- PANEL -->
    <div class="panel panel-default">
        <div class="panel-body">
            <div class="top-panel">
                <h4>Wybierz sposób płatonści</h4>
                <div class="row" style="margin-bottom: 15px;">
                    <div class="form-group form-checkbox small default_pay">
                        <input type="checkbox" class="css-checkbox " id="default_pay" name="default_pay">
                        <label class="css-label remember_this" for="default_pay">wybierz jako domyślną opcję płatności (podpowiada przy kolejnych zakupach)</label>
                    </div>
                </div>
            </div>

            <?php echo $this->getChildHtml('methods') ?>


        </div>
    </div>
</fieldset>



