<fieldset class="default_pay">
    <h4><?php echo Mage::helper("zolagocheckout")->__("Payment method");?>:</h4>
    <!-- PANEL -->
    <div class="panel panel-default">
        <div class="panel-body">
            <div class="top-panel">
                <h4>Wybierz sposób płatonści</h4>
                <div class="row" style="margin-bottom: 15px;">
                    <div class="form-group form-checkbox small default_pay">
						<?php if($this->getHasDefaultPayment()):?>
							<input type="hidden" value="0" name="default_pay">
							<input type="checkbox" class="css-checkbox " id="default_pay" value="1" name="default_pay">
							<label class="css-label remember_this" for="default_pay">
								<?php echo Mage::helper("zolagocheckout")->__("Set as default payment");?>
							</label>
						<?php endif;?>
                    </div>
                </div>
            </div>

            <?php echo $this->getChildHtml('methods') ?>


        </div>
    </div>
</fieldset>



