<?php $items = $this->getItems();
$vendors = $items->vendors;

$vendorsJ = Mage::helper('core')->jsonEncode($vendors);

$allVendorsMethod = $items->allVendorsMethod;

$methods = $items->methods;
$rates = $items->rates;
$cost = $this->getItemsShippingCost();

$cost = $items->cost;
?>


<?php if(!empty($rates)): ?>
<div id="shipping-methods">
    <script type="text/javascript">
        var vendors = <?php echo $vendorsJ; ?>;
    </script>
    <div class="shipping-collect"></div>
<?php foreach($methods as $method): ?>
    <?php
    $formattedCost = '';
    if (isset($cost[$method['code']])) {
        $costSum = array_sum($cost[$method['code']]);
        $formattedCost = Mage::helper('core')->currency($costSum, true, false);
    }?>
    <div class="panel panel-default panel-color">
        <div class="panel-body">
            <dl class="pull-left">
                <input type="radio" value="<?php echo $method['code']; ?>" name="shipping" required="required">
                <dt><?php echo $method['carrier_title']?></dt>
                <dd><?php echo $method['method_title']?></dd>
                <dd class="separator large">Koszt przesyłki: <strong><?php echo $formattedCost; ?> </strong></dd>
            </dl>
            <figure class="logo-courier pull-right">
                <img alt="" src="/skin/frontend/modago/default/images/def-logo-kurier.png">
            </figure>
        </div>
    </div>
<?php endforeach; ?>
    <script type="text/javascript">
        jQuery('#shipping-methods .panel-color').click(function () {
            jQuery('#shipping-methods .panel-color').removeClass('selected-shipping');
            jQuery(this).addClass('selected-shipping');
            jQuery(this).find('input[name=shipping]')
                .attr("checked", "checked")
                .prop("checked", true);
        })
        //And auto select the FIRST method, if any checked before for quote
        var countMethods = jQuery('#shipping-methods .panel-color').size();
        console.log(countMethods);
        if(parseInt(countMethods) == 1){
            jQuery('#shipping-methods .panel-color').addClass('selected-shipping');
            jQuery('#shipping-methods .panel-color').find('input[name=shipping]')
                .attr("checked", "checked")
                .prop("checked", true);
        }
    </script>

<?php else: ?>
    <div class="panel panel-default panel-color">
        <div class="panel-body">
            <dl class="pull-left">
                <?php echo $this->__('No delivery method available'); ?>
            </dl>
        </div>
    </div>
<?php endif; ?>
</div>



