<?php 
/* @var $this Zolago_Modago_Block_Checkout_Onepage_Shared_Shippingpayment_Shipping */

$items = $this->getItems();
$vendors = $items->vendors;

$vendorsJ = Mage::helper('core')->jsonEncode($vendors);

$allVendorsMethod = $items->allVendorsMethod;

$methods = $items->methods;
$rates = $items->rates;
$vednorCosts = $items->vendorCosts;
$costSumm = $this->getItemsShippingCost();
$cost = $items->cost;

$checkoutSession = Mage::getSingleton('checkout/session');
$selectedShipping = Mage::helper("zolagocheckout")->getSelectedShipping();
$address = $checkoutSession->getQuote()->getShippingAddress();
$sessionShippingMethod = "";
foreach($selectedShipping["methods"] as $vid => $methodSelected){
    $sessionShippingMethod = $methodSelected;
}

$deliveryPoint = $this->getDeliveryPointCheckout();

$deliveryType = '';
foreach($methods as $method){
    if($method['code'] == $sessionShippingMethod){
        $deliveryType = $method["delivery_type"];
    }
}
$extraCharge = (int)Mage::getStoreConfig('carriers/'.$deliveryType.'/cod_extra_charge');
?>


<?php if(!empty($rates)): ?>
<fieldset id="shipping-methods"  style="display: none;visibility: hidden; height: 0;">
    <h4 class="fieldset-title"><?php echo $this->__('Rodzaj dostawy'); ?>:</h4>
    <div class="data-validate"></div>
    <script type="text/javascript">
		(function(){
			Mall.reg.set("vendors", <?php echo $vendorsJ; ?>);
			Mall.reg.set("vendor_costs", <?php echo Mage::helper("core")->jsonEncode($vednorCosts); ?>);
			Mall.reg.set("extra_charge", <?php echo Mage::helper("core")->jsonEncode($extraCharge); ?>);
		})();
    </script>
    <div class="shipping-collect"></div>

    <?php if (isset($methodSelected) && isset($selectedShipping["shipping_point_code"])): ?>
        <?php $shippingPointCode = $this->getDeliveryPointData($selectedShipping["shipping_point_code"]); ?>
        <?php if(!empty($shippingPointCode)): ?>
            <input type="text" name="_shipping_point_code"
                   data-id="<?php echo $shippingPointCode["id"]; ?>"
                   data-town="<?php echo $shippingPointCode["city"]; ?>"
                   value="<?php echo $shippingPointCode["value"]; ?>" />
        <?php endif; ?>
    <?php endif; ?>


	<?php foreach($methods as $method): ?>
    <?php
    $formattedCost = '';
    if (isset($cost[$method['code']])) {
        $costSum = array_sum($cost[$method['code']]);
        $formattedCost = Mage::helper('core')->currency($costSum, true, false);
    }?>
    <div class="panel panel-default panel-color">
                <div class="panel-body">
                    <dl class="pull-left">
                        <div style="">
                            <input type="radio"
                                   value="<?php echo $method['code']; ?>"
                                   <?php if (!empty($sessionShippingMethod) && $method['code']==$sessionShippingMethod): ?>checked<?php endif; ?>
                                   name="_shipping_method"
                                   required="required"
                                   class="shipping-method"
                                   data-carrier-name="<?php echo $this->escapeHtml($method['carrier_title']); ?>"
                                   data-carrier-method="<?php echo $this->escapeHtml($method['method_title']); ?>"
                                   data-method-cost="<?php echo $costSum; ?>"/>
                        </div>

                        <dt><?php echo $method['carrier_title'] ?></dt>
                        <dd><?php echo $method['method_title'] ?></dd>
                        <dd class="separator large"><?php echo $this->__('Shipping cost'); ?>: <strong><?php echo $formattedCost; ?> </strong></dd>
                    </dl>
                    <figure class="logo-courier pull-right">
                        <div class="shipment-icon">
                            <i class="fa fa-truck fa-3x"></i>
                        </div>
                    </figure>
                </div>
            </div>
<?php endforeach; ?>
    <script type="text/javascript">
        jQuery('#shipping-methods .panel-color').click(function () {
            jQuery('#shipping-methods .panel-color').removeClass('selected-shipping');
            jQuery(this).addClass('selected-shipping');
            jQuery(this).find('input[name=_shipping_method]')
                .attr("checked", "checked")
                .prop("checked", true);
        })
        //And auto select the FIRST method, if any checked before for quote
        var countMethods = jQuery('#shipping-methods .panel-color').size();
        if(parseInt(countMethods) == 1){
            jQuery('#shipping-methods .panel-color').addClass('selected-shipping');
            jQuery('#shipping-methods .panel-color').find('input[name=_shipping_method]')
                .attr("checked", "checked")
                .prop("checked", true);
        }
    </script>
    <script type="text/javascript">
        Mall.translate.add("please-select-shipping", "<?php echo $this->__("Please select shipping"); ?>");
    </script>
<?php else: ?>
    <div class="panel panel-default panel-color">
        <div class="panel-body">
            <dl class="pull-left">
                <?php echo $this->__('No delivery method available'); ?>
            </dl>
        </div>
    </div>
<?php endif; ?>
</fieldset>



