<?php /* @var $this Zolago_Campaign_Block_Vendor_Campaign_Edit */ ?>
<?php $_helper = Mage::helper("zolagocampaign"); ?>
<?php $_model = $this->getModel();?>


<div class="container">
    <div class="page-heading row">
        <div class="col-lg-12">
            <?php if ($this->isModelNew()): ?>
                <h3><?php echo $_helper->__("New campaign"); ?></h3>
                <p><?php echo $_helper->__("Create new campaign. Required fields are marked with an asterisk."); ?></p>
            <?php else: ?>
                <h3><?php echo $_helper->__("Edit campaign '%s'", $_model->getName()); ?></h3>
                <p><?php echo $_helper->__("Poniżej znajdziesz szczegóły kampanii. Możesz wprowadzić zmiany w ustawieniach kampanii edytując poszczególne pola. Możesz dodać krecje i dodać produkty."); ?></p>
            <?php endif; ?>
        </div>
    </div>
</div>

<div class="container z-grid">
	<form id="edit-campaign" class="form-horizontal row-border" action="<?php echo $this->getForm()->getAction();?>" method="POST">
		<input type="hidden" name="campaign_id" value="<?php echo $_model->getId();?>"/>
		<?php echo $this->getLayout()->getBlock('formkey')->toHtml();?>
		<?php echo $this->getForm()->toHtml();?>


		<div class="form-actions">
            <input type="submit" value="<?php echo $_helper->__("Save");?>" class="btn btn-primary pull-right">
            <a href="<?php echo Mage::getUrl('campaign/vendor'); ?>" class="btn btn-default pull-right"><?php echo $_helper->__("Cancel");?></a>
        </div>
	</form>
</div>



<!--        Show product tab and banners tab only on edit page-->
<?php if(!$this->isModelNew()) :?>
<ul style="margin-top:6px" class="nav nav-tabs">

    <li style="float:right" class="">
        <a name="tmp"></a>
    </li>
    <li style="float:right" class="">
        <a href="#tab_products" data-toggle="tab"><i class="icon-folder-open"></i>&nbsp;<?php echo $_helper->__('Products'); ?></a>
    </li>
    <li style="float:right" class="active">
        <a href="#tab_banners" data-toggle="tab"><i class="icon-picture"></i>&nbsp;<?php echo $_helper->__('Campaign creatives'); ?></a>
    </li>

</ul>
<div class="tab-content">
    <div id="tab_products" class="tab-pane ">
        <br>
        <div class="container z-grid">

            <div class="widget box">
                <div class="widget-header">
                    <h4><i class="icon-folder-open"></i>&nbsp;<?php echo $_helper->__("Products"); ?></h4>

                </div>
                <div class="widget-content">
                    <?php echo $this->getProductsGrid()->toHtml(); ?>
                </div>
            </div>

        </div>
    </div>
    <div id="tab_banners" class="tab-pane active">
        <br>
        <div class="container z-grid">
            <div class="widget box">
                <div class="widget-header">
                    <h4><i class="icon-picture"></i>&nbsp;<?php echo $_helper->__("Campaign creatives"); ?></h4>

                </div>
                <div class="widget-content">
                    <?php echo $this->getBannersGrid()->toHtml(); ?>
                </div>
            </div>

        </div>
    </div>
</div>
<!--Products tab-->
<div class="modal fade" id="browseProducts">
    <div class="modal-dialog" style="width: 80%">
        <form id="campaign_products" action="/campaign/vendor/saveProducts"  class="form-horizontal row-border" method="post">
            <input type="hidden" name="campaign_id" value="<?php echo $_model->getId();?>"/>

            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title"><?php echo $_helper->__("Add products");?></h4>
                </div>
                <div class="modal-body">
                    <?php echo $_helper->__("Enter SKUs Comma-separated"); ?>
                    <textarea type="text" name="campaign_products_source" class="form-control input-text"
                              rows="10"><?php echo $this->getCampaignProducts(); ?></textarea>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal"><?php echo $_helper->__("Cancel");?></button>
                    <button type="submit" class="btn form-btn-loading btn-primary" data-loading-text="<?php echo $_helper->__("Loading...");?>"><?php echo $_helper->__("Add");?></button>
                </div>
            </div>
        </form>
    </div>
</div>
<?php endif; ?>
<div class="modal fade" id="browseCategory">
    <div class="modal-dialog" style="width: 50%">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title"><?php echo $_helper->__("Select Category");?></h4>
            </div>
            <div class="modal-body">
                <div id='jqxWidget'>
                    <div >
                        <div id='jqxTree' style="padding: 10px 0;">
                            <?php echo Mage::helper("zolagocampaign")->getCategoriesTree(); ?>
                        </div>
                    </div>

                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal"><?php echo $_helper->__("Cancel");?></button>
                <button type="submit" class="btn form-btn-loading btn-primary" data-loading-text="<?php echo $_helper->__("Loading...");?>"><?php echo $_helper->__("Add");?></button>
            </div>
        </div>
    </div>
</div>


    <script type="text/javascript">
        jQuery(document).ready(function () {

            jQuery("#browseProducts form").submit(function (e) {
                e.preventDefault();
                var campaignProductsSource = jQuery("textarea[name=campaign_products_source]").val();

                if (campaignProductsSource.length <= 0) {
                    noty({
                        text: "<?php echo $_helper->__('Enter product SKUs please'); ?>",
                        type: 'error',
                        timeout: 2000
                    });
                } else {
                    //push products to campaign form field
                    jQuery("input[name=campaign_products]").val(campaignProductsSource);
                    jQuery("#browseProducts").modal("hide");
                    //update grid if edit
                    var modelId = '<?php echo $_model->getId();?>';
                    if (modelId.length > 0) {
                        jQuery.ajax({
                            url: '/campaign/vendor/products',
                            contentType: "application/json; charset=utf-8",
                            type: 'GET',
                            data: {id: modelId, products: campaignProductsSource, isAjax: true},
                            success: function (result) {
                                jQuery(('#zolagocampaign_campaign_product_grid')).html(jQuery(result).find('#zolagocampaign_campaign_product_grid').html());
                                jQuery("#zolagocampaign_campaign_product_grid_table .filter input")
                                    .addClass("form-control");
                            }
                        })
                    }
                }
            });

            jQuery("#browseProducts").on("show.bs.modal", function () {
                console.log("Init loading products")
            });
            jQuery(".grid table .filter input,.grid table .filter select")
                .addClass("form-control");
            jQuery(document).on('click', '.btn[data-action=remove]', function (e) {
                e.preventDefault();
                var campaignId = jQuery("input[name=campaign_id]").val();
                var path = jQuery(this).attr('href');
                removeCampaignGridItemLink(path, campaignId);
            })
            function removeCampaignGridItemLink(path, campaignId) {
                var link = path + "campaignId/" + campaignId;
                window.location = link;
            }

            jQuery('.datetimepicker').datetimepicker({
                format: 'd-m-Y H:i'
            });
            jQuery(".icon-calendar").click(function () {
                jQuery(this).parents(".datetimepicker-wrapper").find(".datetimepicker")
                    .datetimepicker("show")
                    .blur();
            });

            var form = jQuery("#edit-campaign");
            new Zolago.formIntegrator(form);
            form.validate({
                rules: {
                    "percent": {
                        max: 100
                    },
                    "date_from": {dateBefore: '#date_to'},
                    "date_to": {dateAfter: '#date_from'},
                    //url_key:"urlKeyFormat"
                },
                messages: {
                    date_from: {
                        dateBefore: '<?php echo $_helper->__('Must be before corresponding end date'); ?>'
                    },
                    date_to: {
                        dateAfter: '<?php echo $_helper->__('Must be after corresponding start date'); ?>'
                    }
                },
                errorPlacement: function($error, $element){
                    var name = $element.attr("name");
                    $element.closest("div").append($error);
                }
            });


            var urlKeyContainer = jQuery('.landing-page-config').parents(".form-group");
            toggleUrlKeyField(jQuery(form).find('input[name="is_landing_page"]'), urlKeyContainer);

            jQuery(form).find('input[name="is_landing_page"]').on('click', function () {
                toggleUrlKeyField(this, urlKeyContainer);

            })
            function toggleUrlKeyField(element, toggleContainer) {
                var showLandingPageConfig = jQuery(element).is(":checked");

                if (showLandingPageConfig) {
                    toggleContainer.show();
                } else {
                    toggleContainer.hide();
                }

            }
        });
    </script>
