<?php /* @var $this Zolago_Campaign_Block_Vendor_Campaign_Edit */ ?>
<?php $_helper = Mage::helper("zolagocampaign");?>
<?php $_model = $this->getModel();?>
<div class="container">
	<div class="page-heading row">
		<div class="col-lg-6">
			<h3>
				<?php if($this->isModelNew()):?>
					<?php echo Mage::helper("zolagopo")->__("New campaign");?>
				<?php else: ?>
					<?php echo Mage::helper("zolagopo")->__("Edit campaign '%s'", $_model->getName());?>
				<?php endif;?>
			</h3>
		</div>
		
	</div>
</div>

<div class="container z-grid">
	<form id="edit-campaign" class="form-horizontal row-border" action="<?php echo $this->getForm()->getAction();?>" method="POST">
		<input type="hidden" name="campaign_id" value="<?php echo $_model->getId();?>"/>
		<?php echo $this->getLayout()->getBlock('formkey')->toHtml();?>
		<?php echo $this->getForm()->toHtml();?>
		<div class="widget box"> 
			<div class="widget-header"> 
				<h4>
					<i class="icon-reorder"></i> 
					Products		
				</h4> 
				<div class="toolbar no-padding"> 
					<div class="btn-group"> 
						<span data-toggle="modal" data-target="#browseProducts" class="btn btn-xs">
							<i class="icon-plus"></i> 
							<?php echo $_helper->__("Add products");?>
						</span> 
					</div> 
				</div>
			</div> 
			<div class="widget-content">
                <?php echo $this->getGrid()->toHtml(); ?>

			</div>
		</div>
		<div class="form-actions"> <input type="submit" value="<?php echo $_helper->__("Save");?>" class="btn btn-primary pull-right"> </div>
	</form>
</div>

<div class="modal fade" id="browseProducts">
	<div class="modal-dialog" style="width: 80%">
		<form id="campaign_products" action="/campaign/vendor/saveProducts"  class="form-horizontal row-border" method="post">
			<input type="hidden" name="campaign_id" value="<?php echo $_model->getId();?>"/>

			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
					<h4 class="modal-title"><?php echo $_helper->__("Add products");?></h4>
				</div>
                <div class="modal-body">
                    <?php echo $_helper->__("Enter SKUs Comma-separated"); ?>
                    <textarea type="text" name="campaign_products_source" class="form-control input-text"
                              rows="10"><?php echo $this->getCampaignProducts(); ?></textarea>
                </div>
				<div class="modal-footer">
					<button type="button" class="btn btn-default" data-dismiss="modal"><?php echo $_helper->__("Cancel");?></button>
					<button type="submit" class="btn form-btn-loading btn-primary" data-loading-text="<?php echo $_helper->__("Loading...");?>"><?php echo $_helper->__("Add");?></button>
				</div>
			</div>
		</form>
	</div>
	<script type="text/javascript">
        jQuery(function ($) {
            $("#browseProducts form").submit(function (e) {
                e.preventDefault();
                var campaignProductsSource = $("textarea[name=campaign_products_source]").val();
                console.log(campaignProductsSource);
                if (campaignProductsSource.length <= 0) {
                    noty({
                        text: "Enter product SKUs please",
                        type: 'error',
                        timeout: 2000
                    });
                } else {
                    //push products to campaign form field
                    $("input[name=campaign_products]").val(campaignProductsSource);
                    $("#browseProducts").modal("hide");
                    //update grid if edit
                    var modelId = '<?php echo $_model->getId();?>';
                    if (modelId.length > 0) {
                        $.ajax({
                            url: '/campaign/vendor/products',
                            contentType: "application/json; charset=utf-8",
                            type: 'GET',
                            data: {id: modelId, products: campaignProductsSource, isAjax: true},
                            success: function(result){
                                $(('#zolagocampaign_campaign_product_grid')).html($(result).find('#zolagocampaign_campaign_product_grid').html());
                                $("#zolagocampaign_campaign_product_grid_table .filter input")
                                    .addClass("form-control");
                            }
                        })
                    }
                }
            });
            $("#browseProducts").on("show.bs.modal", function () {
                console.log("Init loading products")
            });
            //If info campaign selected price data fieldset should not to be visible
            var typeSelected = $('#edit-campaign select[name=type]').val();
            if (typeSelected == 'info') {
                $('#price_source_id').parents('.widget.box').hide();
            }
            $('#edit-campaign select[name=type]').change(function () {
                var pricesContainer = $('#price_source_id').parents('.widget.box');
                var type = $(this).val();
                if (type == 'info') {
                    pricesContainer.hide();
                } else {
                    pricesContainer.show();
                }
            })

            $("#zolagocampaign_campaign_product_grid_table .filter input")
                .addClass("form-control");
            $(".btn[data-action=remove]").click(function (e) {
                e.preventDefault();
                var campaignId = $("input[name=campaign_id]").val();
                var productId = $(this).data("item");
                removeCampaignProductLink(campaignId, productId);
            })
            function removeCampaignProductLink(campaignId, productId) {
                var removePath = '<?php echo $this->getRemoveProductPath(); ?>';
                var link = removePath + "?campaignId=" + campaignId + "&productId=" + productId;
                window.location = link;
            }

            $('.datetimepicker').datetimepicker({
                format: 'd-m-Y H:i'
            });

            var form = $("#edit-campaign");
            new Zolago.formIntegrator(form);
            form.validate({
                rules: {
                    "percent": {
                        max: 100
                    },
                    "date_from": {dateBefore: '#date_to'},
                    "date_to": {dateAfter: '#date_from'}
                }
            });

});
</script>