<?php
/**
 * Author: Paweł Chyl <pawel.chyl@orba.pl>
 * Date: 08.09.2014
 */

?>

<div class="form-group clearfix">
    <div class="row">
        <label class="col-sm-6" for="pass"><?php echo $this->__("Password"); ?></label>
        <div class="col-sm-6">
            <input type="password" class="form-control password" id="billing:customer_password" title="" name="billing[customer_password]" data-original-title="<?php echo $this->__("Password has to be strong."); ?>">
            <input type="hidden" class="form-control password" id="billing:confirm_password" title="" name="billing[confirm_password]">
        </div>
    </div>
</div>
