<br/>
<div class="container z-grid">
    <div class="widget box">   
        <div class="widget-content">
            <?php echo $this->getGridHtml(); ?>
        </div>
    </div>
</div>
<script type="text/javascript">
(function(){
	var gridObj = <?php echo $this->getGridJsObjectName();?>;
	var topForm = $("filter_form");
	// create integrator
	new Zolago.gridIntegrator(gridObj);
	
	gridObj.doFilter = (function(){
        var filters = $$('#'+this.containerId+' .filter input', '#'+this.containerId+' .filter select');
        var filters2 = $$('#'+topForm.id+' input', '#'+topForm.id+' select');
        var elements = [],
			elements2 = [];
        for(var i in filters){
            if(filters[i].value && filters[i].value.length) elements.push(filters[i]);
        }
        for(var i in filters2){
            if(filters2[i].value && filters2[i].value.length) elements2.push(filters2[i]);
        }
		
		var serialized = Form.serializeElements(elements);
		var serialized2 = Form.serializeElements(elements2);
		var params = []
		
		if(serialized){
			params.push(serialized);
		}
		if(serialized2){
			params.push(serialized2);
		}
		
        if (!this.doFilterCallback || (this.doFilterCallback && this.doFilterCallback())) {
            this.reload(this.addVarToUrl(this.filterVar, encode_base64(params.join("&"))));
        }
    }).bind(gridObj);
	
	
	topForm.observe("submit", function(e){
		gridObj.doFilter();
		e.preventDefault();
	});
	topForm.observe("reset", function(e){
		gridObj.resetFilter();
		e.preventDefault();
	});

})();
// Do pickers
jQuery(function($){
	$( ".datepicker" ).datepicker();
});
</script>                                    
