<div class="widget">
	<div class="align-center form-group" style="margin:5px 0px 5px 0px">
		<div class="col-md-8">
			<button class="btn">Dodaj</button>
			<button class="btn">Usuń</button>
			<button class="btn">Mapuj po nazwach</button>
			<button class="btn">Mapuj z CSV</button>
			<button class="btn btn-primary"><i class="icon-question-sign"></i></button>
		</div>
		<div class="input-group" style="width:200px"><input type="text" class="form-control input-width-medium" id="input_search"><span class="input-group-btn"><button class="btn btn-default" type="button"><i class="icon-search">
			</i></button></span></div>
	</div>
<div style="clear:both"></div>
	<div id="uploader_wrapper" class="widget-content"></div>

<script type="text/javascript">
function init_uploader() {	
	// Setup html5 version
	jQuery('#uploader_wrapper').append('<div id="uploader"></div>');
	jQuery("#uploader").pluploadQueue({
		// General settings
		runtimes : 'html5,flash,silverlight,html4',
		url : '<?php echo Mage::getUrl('udprod/vendor_image/upload'); ?>',
		chunk_size: '1mb',
		rename : true,
		dragdrop: true,
		
		filters : {
			// Maximum file size
			max_file_size : '10mb',
			// Specify what files to browse for
			mime_types: [
				{title : "Image files", extensions : "jpg,gif,png,jpeg"},
			]
		},

		// Resize images on clientside if we can
		resize : {width : 320, height : 240, quality : 90},

		flash_swf_url : '../../js/Moxie.swf',
		silverlight_xap_url : '../../js/Moxie.xap',
	});
	var uploader = jQuery('#uploader').pluploadQueue();
	uploader.bind('UploadComplete',function() {
		elf.sync();
		alert('<?php echo Mage::helper('zolagocatalog')->__('Upload completed'); ?>');
		jQuery('#uploader').remove();
		init_uploader();
	});
}
			var elf;
			jQuery().ready(function() {
				elf = jQuery('#uploader_wrapper').elfinder({
					url : '<?php echo Mage::getUrl('udprod/vendor_image/connector');?>',  // connector URL (REQUIRED)
					lang: '<?php echo $this->localeCode ?>',             // language (OPTIONAL)
				}).elfinder('instance');
			});
		</script>
</div>