<?php /* @var $this Zolago_Modago_Block_Sales_Order_Item_Renderer_Default */ ?>
<?php 
$_item = $this->getItem();

$_itemPriceInclTax = (float)$_item->getPriceInclTax();
$_rowPriceInclTax = (float)$_item->getRowTotalInclTax();
$_discountPercent = (float)$_item->getDiscountPercent();
$_discountAmount = (float)$_item->getDiscountAmount();
$_qty = round($_item->getQty());

$_productMsrpPrice = $_itemPriceInclTax;
if($_item->getProduct()){
	$_productMsrpPrice = $_item->getProduct()->getPrice();
}
?>

<tr>
	<td>
		<img src="<?php echo $this->getProductThumbnail()->resize(53, 69); ?>"
			 alt="<?php echo $this->escapeHtml($this->getProductName()) ?>" />
	</td>
	<td>
		<?php echo $this->escapeHtml($_item->getName());?>
		<?php if ($_options = $this->getOptionList()):?>
			<br/>
			<small>
			<?php foreach ($_options as $_option) : ?>
				<?php $_formatedOptionValue = $this->getFormatedOptionValue($_option) ?>
				
					<?php echo $this->escapeHtml($_option['label']) ?>: <?php echo  $this->escapeHtml($_formatedOptionValue['value']); ?>
				</div>
			<?php endforeach; ?>
			</small>
		<?php endif;?>
	</td>
	<td class="number">
		<?php if($_productMsrpPrice>$_itemPriceInclTax):?>
		<em>
			<?php echo Mage::helper("core")->formatPrice($_productMsrpPrice, false);?>
		</em>
		<?php endif;?>
		<span>
			<?php echo Mage::helper("core")->formatPrice($_itemPriceInclTax, false);?>
		</span>
	</td>
	<td class="number">
		<?php echo $_qty; ?>
	</td>
	<td class="number">
		<?php echo Mage::helper("core")->formatPrice($_itemPriceInclTax * $_qty, false);?>
	</td>
</tr>
