<?php /* @var $this Zolago_Modago_Block_Sales_Order_Item_Renderer_Default */ ?>
<?php 
$_item = $this->getItem();

$_itemPriceInclTax = (float)$_item->getPriceInclTax();
$_rowPriceInclTax = (float)$_item->getRowTotalInclTax();
$_discountPercent = (float)$_item->getDiscountPercent();
$_discountAmount = (float)$_item->getDiscountAmount();
$_qty = round($_item->getQty());

$_productMsrpPrice = $_itemPriceInclTax;
if($_item->getProduct()){
	$_productMsrpPrice = $_item->getProduct()->getPrice();
}
?>
<tr>
	<td>
		<?php /* <img src="<?php echo $this->getProductThumbnail()->resize(53, 69) ?>"
			 alt="<?php echo $this->escapeHtml($this->getProductName()) ?>" 
			 width="53" height="69"/> */ ?>
		<?php /* Images as cid:<itemId>.jpg @see Zolago_Po_Helper_Data::getPoImagesAsAttachments(); */ ?>
		<img src="cid:<?php echo $_item->getId() ?>.jpg"
			 alt="<?php echo $this->escapeHtml($this->getProductName()) ?>" 
			 width="53" height="69"/>
	</td>
	<td style="padding: 5px">
		<?php echo $this->escapeHtml($_item->getName());?>
		<?php if ($_options = $this->getOptionList()):?>
			<br/>
			<small>
			<?php foreach ($_options as $_option) : ?>
				<?php $_formatedOptionValue = $this->getFormatedOptionValue($_option) ?>
				<?php echo $this->escapeHtml($_option['label']) ?>: <?php echo  $this->escapeHtml($_formatedOptionValue['value']); ?>
			<?php endforeach; ?>
			</small>
		<?php endif;?>
	</td>
	<td style="text-align: right; padding: 5px">
		<?php if($_productMsrpPrice>$_itemPriceInclTax):?>
		<del style="color: #ccc; font-size: 10px;">
			<?php echo Mage::helper("core")->formatPrice($_productMsrpPrice, false);?></del>
		<?php endif;?>
		<span>
			<?php echo Mage::helper("core")->formatPrice($_itemPriceInclTax, false);?>
		</span> 
	</td>
	<td style="text-align: right; padding: 5px">
		<?php echo $_qty; ?>
	</td>
	<td style="text-align: right; padding: 5px">
		<?php echo Mage::helper("core")->formatPrice($_itemPriceInclTax * $_qty, false);?>
	</td>
</tr>
