<?php /* @var $this Zolago_Solrsearch_Block_Catalog_Product_List_Header_Category */?>
<section id="main" class="<?php echo $this->getElementClass(); ?>">
    <header id="header-main">
        <div class="wrapp-section bg-w">
            <div class="container-fluid">
                <div class="row ">
                    <div id="view-current-filter" class="col-sm-12 ">
                        <?php echo $this->getChildHtml('breadcrumbs') ?>

                        <h1><?php echo $this->getCategory()->getName(); ?></h1>
                        <a href="#" class="backToCategory underline visible-xs">Wróć do kategorii: Ona ></a>

                        <div class="view_filter clearfix">

                            <dl class="clearfix">
                                <dt>Aktualnie ogladasz:</dt>
                                <dd>
                                    <span class="label">Rozmiar: <span class="value">M</span><i class="fa fa-times"></i></span>
                                    <span class="label">Rozmiar: <span class="value">M</span><i class="fa fa-times"></i></span>
                                    <span class="label">Marka: <span class="value">Adidas</span><i
                                            class="fa fa-times"></i></span>
                                    <span class="label">Marka: <span class="value">Adidas</span><i
                                            class="fa fa-times"></i></span>
                                </dd>
                                <dd class="action"><a href="#" class="button button-third">Wyczyść filtry</a></dd>
                            </dl>
                            <a href="#" class="actionViewFilter button button-primary medium visible-xs"><i
                                    class="fa fa-chevron-right"></i> Filtruj Produkty</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </header>