<?php
/** @var Zolago_SalesRule_Block_Email_Promotion $this */
/** @var Zolago_SalesRule_Helper_Data $_hlp */
$_hlp = Mage::helper('zolagosalesrule');
$list = $this->getPromotions();
?>

<?php foreach ($list as $item) : ?>
<!--[if (gte mso 9)|(IE)]>
<table align="center" border="0" cellspacing="0" cellpadding="0" width="580">
	<tr>
		<td align="left" valign="top" width="270">
<![endif]-->
<div style="display:inline-block; max-width:50%; min-width:270px; vertical-align:top; width:100%;"
     class="wrapper">
	<table align="left" border="0" cellpadding="0" cellspacing="0" width="100%" style="max-width:270px;"
	       class="wrapper">
		<tr>
			<td align="center" valign="top">
				<table border="0" cellpadding="0" cellspacing="0" width="100%">
					<tr>
						<td style="padding-top:15px"></td>
					</tr>
					<tr>
						<td>
							<a href="<?php echo Mage::getUrl('mypromotions'); ?>" target="_blank"
							   style="text-decoration:none !important;" class="promo-item">
								<table bgcolor="#FFFFFF" cellpadding="0" cellspacing="0" border="0"
								       width="100%" style="border:1px solid #ebebeb">
									<tr>
										<td align="center" valign="middle">
											<img src="cid:<?php echo $item['ruleItem']->getPromoImage();?>"
											     width="270"
											     style="display: block; color: #666666; font-family: Helvetica, Arial, Helvetica, sans-serif; font-size: 13px; width: 270px; height: auto;"
											     alt="<?php echo $item['ruleItem']->getName();?>" border="0" class="img-max">
										</td>
									</tr>
									<tr>
										<td style="padding-top: 18px"></td>
									</tr>
									<tr>
										<td align="center" valign="middle">
											<img src="cid:<?php echo $item['ruleItem']->getVendorLogo();?>"
											     alt="<?php echo $item['ruleItem']->getVendorName(); ?>"
											     width="104"
											     style="padding: 8px 11px;border: 1px solid #ebebeb; height: auto;" />
										</td>
									</tr>
									<tr>
										<td align="center"
										    style="padding: 15px 10px; font-family: Arial, Helvetica, sans-serif; color: #333333; font-size: 20px; text-transform: uppercase">
											<?php echo htmlentities($item['ruleItem']->getName());?>
										</td>
									</tr>
									<tr>
										<td align="center"
										    style="color:#484848;text-decoration:none;font-size:12px;font-family: Arial, Helvetica, sans-serif;">
                                                                                <span class="promo-showmore">
                                                                                    <?php echo htmlentities("Dowiedz się więcej >>"); ?>
                                                                                </span>
										</td>
									</tr>
									<tr>
										<td style="padding-top:18px;"></td>
									</tr>
								</table>
							</a>
						</td>
					</tr>
				</table>

			</td>
		</tr>
	</table>
</div>
<!--[if (gte mso 9)|(IE)]>
</td>
<td width="20" style="font-size: 1px;">&nbsp;</td>
<td align="right" valign="top" width="270">
<![endif]-->
<?php endforeach; ?>