<?php
$_items = $this->getItems();
/** @var Zolago_Checkout_Helper_Data $_helper */
$_helper = Mage::helper("zolagocheckout");
$basketDataLayer = $_helper->getBasketDataLayer();
?>

<?php if (!empty($basketDataLayer)): ?>
    <script>
        if (typeof dataLayer != "undefined") {
            dataLayer.push(<?php echo json_encode($basketDataLayer); ?>);
        }
    </script>
<?php endif; ?>

<div id="content" class="container-fluid">
    <div id="shopping-cart" class="row">
        <form action="<?php echo $this->getUrl('checkout/cart/updatePost') ?>" method="post" id="cart-form">
            <?php echo $this->getBlockHtml('formkey'); ?>
            <div id="content-main" class="col-lg-9 col-md-8  section">
                <div class="main bg-w">
                    <section>
                        <header>
                            <h2><?php echo $this->__("Shopping Cart"); ?></h2>
                        </header>

                        <?php foreach($_items as $_item) : ?>

                            <?php echo $this->getItemHtml($_item); ?>

                        <?php endforeach; ?>

                        <div class="modal fade" id="trigger_conditions_shipping" tabindex="-1" role="dialog" aria-labelledby="trigger_conditions_shipping" aria-hidden="true">
                            <div class="modal-dialog modal-lg modal-md modal-sm">
                                <div class="modal-content">
                                    <button type="button" class="close" data-dismiss="modal"></button>
                                    <div class="modal-body"></div>

                                </div>
                            </div>
                        </div>

                        <?php /* <footer class="hidden-xs">
                            <a href="#" id="clearAllShopping" class="simple"><i class="fa-remove"></i> <?php echo $this->__("Empty cart"); ?></a>
                        </footer> */ ?>
                    </section>
                </div>
            </div>


        </form>
        <?php echo $this->getChildHtml('zolagomodago.checkout.cart.sidebar'); ?>
    </div>
</div>

