<?php $id = intval($this->getRequest()->getParam('cat_id')); ?>
<?php if($this->isSearchEnabled()): ?>
<div class="faq">
	<form name="faqsearch" action="<?php echo $this->getSearchUrl() ?>" method="get">
		<div id="searchform" class="form-group row">
            <div class="col-md-12 col-sm-12">
                <div class="row">
                    <label for="keyword"><?php echo $this->__('Search questions and answers'); ?>:</label>
                    <div class="col-md-5 col-sm-8 col-xs-12 faq-search-keyword">
                        <input type="text"  id="keyword" name="keyword" class=form-control>
                        <?php if ($id): ?>
                            <input type="hidden" name="cat_id" id="cat_id" value="<?php echo $id; ?>"/>
                        <?php endif; ?>

                    <a id="faq-search"  class="button button-third large pull-left" href="" style="margin-left: 20px;">
                        <?php echo $this->__('Search'); ?>
                    </a>

                </div>
            </div>


		</div>
	</form>
</div>
<?php endif; ?>
<script type="text/javascript">
    jQuery("#faq-search").click(function(e){
        e.preventDefault();
        jQuery("form[name=faqsearch]").submit();
    })
</script>