<script type="text/javascript" src="//maps.google.com/maps/api/js"></script>
<?php
$inPostData = Zolago_Modago_Block_Checkout_Cart_Sidebar_Shipping_Map_Inpost::getPopulateMapData();

$inPostPoints = isset($inPostData["map_points"]) ? $inPostData["map_points"] : "";
?>
<script type="text/javascript">
    var inPostPoints = '<?php echo $inPostPoints; ?>';
</script>
<?php
$_items = $this->getItems();
?>

<div id="content" class="container-fluid">
    <div id="shopping-cart" class="row">
        <form action="<?php echo $this->getUrl('checkout/cart/updatePost') ?>" method="post" id="cart-form">
            <?php echo $this->getBlockHtml('formkey'); ?>
            <div id="content-main" class="col-lg-9 col-md-8  section">
                <div class="main bg-w">
                    <section>
                        <header>
                            <h1><?php echo $this->__("Shopping Cart"); ?></h1>
                        </header>

                        <?php foreach($_items as $_item) : ?>

                            <?php echo $this->getItemHtml($_item); ?>

                        <?php endforeach; ?>

                        <div class="modal fade" id="trigger_conditions_shipping" tabindex="-1" role="dialog" aria-labelledby="trigger_conditions_shipping" aria-hidden="true">
                            <div class="modal-dialog modal-lg modal-md modal-sm">
                                <div class="modal-content">
                                    <button type="button" class="close" data-dismiss="modal"></button>
                                    <div class="modal-body"></div>

                                </div>
                            </div>
                        </div>

                        <?php /* <footer class="hidden-xs">
                            <a href="#" id="clearAllShopping" class="simple"><i class="fa-remove"></i> <?php echo $this->__("Empty cart"); ?></a>
                        </footer> */ ?>
                    </section>
                </div>
            </div>

            <?php echo $this->getChildHtml('zolagomodago.checkout.cart.sidebar'); ?>
        </form>
    </div>
</div>

