<div class="row">
    <section class="blockCarouselTop">

        <div id="carousel-top-generic" class="carousel slide border-gray-1x" data-ride="carousel">

            <!-- Indicators -->
            <ol class="carousel-indicators " id="carousel-top-indicators">
                <li data-target="#carousel-top-generic" data-slide-to="0" class="active"></li>
                <li data-target="#carousel-top-generic" data-slide-to="1" class=""></li>
            </ol>

            <!-- Wrapper for slides -->
            <div class="carousel-inner">
                <div class="item active">
                    <img src="<?php echo $this->getSkinUrl('images/banner1.jpg'); ?>" alt="" class="hidden-xs">
                    <img src="<?php echo $this->getSkinUrl('images/bannermobile1.jpg'); ?>" alt=""
                         class="visible-xs">

                    <div class="carousel-caption hidden-xs">
                        <a href="">przeglądaj stylizacje&nbsp;&nbsp;&nbsp;<i class="fa fa-caret-right"></i></a>
                        <a class="margin-top-20px" href="">wejdź do sklepu&nbsp;&nbsp;&nbsp;<i
                                class="fa fa-caret-right"></i></a>
                    </div>
                </div>
                <div class="item">
                    <img src="<?php echo $this->getSkinUrl('images/banner1.jpg'); ?>" alt="" class="hidden-xs">
                    <img src="<?php echo $this->getSkinUrl('images/bannermobile1.jpg'); ?>" alt=""
                         class="visible-xs">

                    <div class="carousel-caption hidden-xs">
                        <a href="">przeglądaj stylizacje&nbsp;&nbsp;&nbsp;<i class="fa fa-caret-right"></i></a>
                        <a class="margin-top-20px" href="">wejdź do sklepu&nbsp;&nbsp;&nbsp;<i
                                class="fa fa-caret-right"></i></a>
                    </div>
                </div>
            </div>


        </div>
    </section>
</div>