<div class="row">
	<section id="topSlider">
		<div class="topSlide">
			<div class="topSlideImages">
				<a href="/">
					<img src="<?php echo $this->getSkinUrl('images/banner1.jpg'); ?>"
					     class="hidden-xs" />
				</a>
				<a href="/">
					<img src="<?php echo $this->getSkinUrl('images/bannermobile1.jpg'); ?>"
					     class="visible-xs" />
				</a>
			</div>
			<div class="topSlideCaptions">
				<a href="/">
					<span>przeglądaj stylizacje <i class="fa fa-caret-right"></i></span>
				</a>
				<br />
				<a href="/">
					<span>wejdź do sklepu <i class="fa fa-caret-right"></i></span>
				</a>
			</div>
		</div>
		<div class="topSlide">
			<div class="topSlideImages">
				<img src="<?php echo $this->getSkinUrl('images/banner1.jpg'); ?>"
				     class="hidden-xs" />
				<img src="<?php echo $this->getSkinUrl('images/bannermobile1.jpg'); ?>"
				     class="visible-xs" />
			</div>
			<div class="topSlideCaptions">
				<a href="/">
					<span>przeglądaj stylizacje <i class="fa fa-caret-right"></i></span>
				</a>
				<br />
				<a href="/">
					<span>wejdź do sklepu <i class="fa fa-caret-right"></i></span>
				</a>
			</div>
		</div>
	</section>
</div>