<div class="row">


    <!--small banners-->
    <div class="container-fluid small-banners">
        <div class="row">

            <div class="col-xs-6 col-sm-3 tight-padding clear-left-nth">
                <a href=""><img class="border1px-rd2-img-gray margin-10-top img-responsive"
                                src="<?php echo $this->getSkinUrl('images/banner-small-1.jpg'); ?>"
                                alt=""></a>
            </div>
            <div class="col-xs-6 col-sm-3 tight-padding clear-left-nth">
                <a href=""><img class="border1px-rd2-img-gray margin-10-top img-responsive"
                                src="<?php echo $this->getSkinUrl('images/banner-small-2.jpg'); ?>"
                                alt=""></a>
            </div>
            <div class="col-xs-6 col-sm-3 tight-padding clear-left-nth">
                <a href=""><img class="border1px-rd2-img-gray margin-10-top img-responsive"
                                src="<?php echo $this->getSkinUrl('images/banner-small-3.jpg'); ?>"
                                alt=""></a>
            </div>
            <div class="col-xs-6 col-sm-3 tight-padding clear-left-nth">
                <a href=""><img class="border1px-rd2-img-gray margin-10-top img-responsive"
                                src="<?php echo $this->getSkinUrl('images/banner-small-4.jpg'); ?>"
                                alt=""></a>
            </div>
        </div>
    </div>
</div>