<style>
	.grid.custom-grid tbody td{
		background: #e7efef;
	}
</style>
<div class="grid custom-grid" id="<?php echo $this->getGrid()->getId();?>_editor">
	<form>
	<?php if($this->getGrid()): ?>
	<table cellpadding="0" cellspacing="0" style="width:100%;" class="data">
		<colgroup>
			<?php foreach ($this->getGrid()->getColumns() as $_column): ?>
				<col <?php echo $_column->getHtmlProperty() ?> />
			<?php endforeach;?>
		</colgroup>
		<tbody>
			<tr>
				<?php $i=0;?>
				<?php foreach ($this->getGrid()->getColumns() as $_column): ?>
					<?php if($i++==0):?>
						<td class="a-center" rowspan="2" style="vertical-align: middle;">
							<!-- <input type="checkbox" name="change"  value="1"/><br/> -->
						</td>
					<?php else:?>
						<td>
							<div class="field-100"><input type="text" class="input-text"/></div>
						</td>
					<?php endif;?>
				</td>
				<?php endforeach;?>
			</tr>
			<tr>
				<?php $i=0;?>
				<?php foreach ($this->getGrid()->getColumns() as $_column): ?>
					<?php if($i++==0):?>
					<?php else:?>
						<td>
							<input type="checkbox" name="change" value="1"/>
							<label>Change</label>
						</td>
					<?php endif;?>
				<?php endforeach;?>
			</tr>
		</tbody>
		<tfoot>
			<tr>
				<td  class="totals a-right" colspan="5">
					<?php echo $this->getSubmitButtonHtml(); ?>
				</td>
			<tr>
		</tfoot>
	</table>
	</form>
	<?php endif;?>
</div>
<script type="text/javascript">
	(function(){
		var assignEditorLayout = function(){
			var editor = $("<?php echo $this->getGrid()->getId();?>_editor").select("tbody tr:first-child td");
			var grid = $("<?php echo $this->getGrid()->getId();?>").select(".grid thead tr:first-child th");
			grid.each(function(el,i){
				editor[i].style.width = (el.clientWidth - 7) + "px";
			});
			console.log("TAK")
		}
		Event.observe(window, "resize", assignEditorLayout);
		Ajax.Responders.register({
			onComplete: assignEditorLayout
		});
		assignEditorLayout();
	})();
</script>