<div class="grid z-grid" id="grid-editor">
	<?php if($this->getGrid()): ?>
	<table style="display: none;">
		<tfoot id="<?php echo $this->buildFieldId("foot");?>">
			<tr id="<?php echo $this->buildFieldId("change");?>">
				<?php $i=0;?>
				<?php foreach ($this->getGrid()->getColumns() as $_column): ?>
					<?php if($i++==0):?>
						<td class="a-center" rowspan="2" style="vertical-align: middle;">
							<!-- <input type="checkbox" name="change"  value="1"/><br/> -->
						</td>
					<?php else:?>
						<td>
							<?php if($_field = $this->getChangeField($_column)):?>
								<div data-rel="<?php echo $_field->getRel();?>" class="relChanger">
                                    <label for="<?php echo $_field->getId();?>"><?php echo $_field->getLabel();?></label>
                                    <br />
									<?php echo $_field->getElementHtml();?>
								</div>
							<?php endif;?>
						</td>
					<?php endif;?>
				<?php endforeach;?>
			</tr>

			<tr class="filter" style="display:none;" id="<?php echo $this->buildFieldId("fields");?>">
				<?php $i=0;?>
				<?php foreach ($this->getGrid()->getColumns() as $_column): ?>
					<?php if($i++==0):?>
					<?php else:?>
						<td>
							<?php if($_field = $this->getField($_column)):?>
								<div class="filter-field-100 element-wrapper" style="display: none;" id="<?php echo $_field->getId() . "_wrapper";?>">
                                    <form>
                                        <?php echo $this->getEmptyValueField($_field);?>
                                        <?php echo $_field->toHtml();?>
                                        <div>
                                        <?php foreach($this->getAdditionalFields($_column) as $_field):?>
                                            <?php echo $_field->toHtml();?>
                                        <?php endforeach;?>
                                        </div>
                                        <?php if($_column->getAttribute()):?>
    <!--									<div class="scope">[--><?php ////echo $this->getScope($_column->getAttribute());?><!--]</div>-->
                                        <?php endif;?>
                                        <div class="apply-all-selected">
                                            <input type="checkbox" name="apply_all_selected"> <?php echo $this->__('Apply to all selected'); ?>
                                        </div>
                                        <?php echo $this->getSubmitButtonHtml(); ?>
                                    </form>
								</div>
							<?php endif;?>
						</td>
					<?php endif;?>
				</td>
				<?php endforeach;?>
			</tr>

		</tfoot>
	</table>
	<?php endif;?>
</div>
<script type="text/javascript">

    var saveGridLocation = '<?php echo $this->getSaveUrl();?>';

</script>