<?php
$storeId		= $this->_getLabelStore()->getId();
$activeFilters	= $this->getCurrentStaticFilterValues();
?>

	<?php if ($this->getStaticFilters($this->getCurrentAttributeSetId()) && $this->getCurrentAttributeSetId()): ?>
        <div class="form-actions">
            <button type="button" title="<?php echo $this->__('Cancel') ?>" class="cancel-btn btn btn-secondary pull-right"><span><span><?php echo $this->__('Cancel') ?></span></span></button>
            <button type="button" title="<?php echo $this->__('Search') ?>" class="search-btn btn btn-primary pull-right"><span><span><?php echo $this->__('Search') ?></span></span></button>
        </div>
	<?php else: ?>
        <div class="form-group">
            <div class="col-md-6">
                <div class="row">
                    <div class="col-md-8">
                        <p class="switcher">
                            <?php echo $this->__('There are no Static Filters for this Attribute Set'); ?>
                        </p>
                    </div>
                </div>
            </div>
        </div>
	<?php endif; ?>