<style>
	.staticFilter {
		width: 155px; 
	}
	.staticFilter option {
		width: 130px;
	}
	.filter-box {
		padding: 2px 0 2px 0;
		display: inline-block;
		width: 48.5%;
		vertical-align: top;
	}
	.filter-box .selectedFilter {
		display: inline-block;
		font-weight: bold;
	}
	.staticFilter-box .box {
		background: none repeat scroll 0 0 #EEEFFD;
		padding-bottom: 0;
	}
	.staticFilter-box .box .left, 
	.staticFilter-box .box .right {
		width: 48.5%;
	}	
	.staticFilter-box .box .scalable {
		margin-top: 5px;
		margin-bottom: 10px;
	}
	.filterSearch {
		float: right;
	}
</style>
<?php
$activeFilters = $this->getCurrentStaticFilterValues();
?>
<div class="staticFilter-box">
	<?php if ($this->getStaticFilters($this->getCurrentAttributeSetId()) && $this->getCurrentAttributeSetId()): ?>
	<div class="box">
		<!-- Static Filters from All Attribute Groups: Start -->
		<div class="left">
			<?php foreach($this->getStaticFilters($this->getCurrentAttributeSetId()) as $singleFilter): ?>
				<?php if ($singleFilter): ?>
					<?php
						$firstFilter = current($singleFilter);
						$filterLabel = $this->getAttributeLabel($firstFilter['code'], $this->getStore());
						$selectedFilter = false;
					?>
					<?php if ($firstFilter['group'] !== Zolago_Catalog_Helper_Data::ADDITIONAL_ATTRIBUTES_GROUP): ?>
						<span class="filter-box">
							<label for="staticFilter"><?php echo $filterLabel; ?>:</label>
							<select name="staticFilter" id="staticFilter-<?php echo $firstFilter['attribute_id']; ?>" class="staticFilter">
								<option value=""><?php echo Mage::helper("zolagocatalog")->__("--- Select ---"); ?></option>
								<?php foreach($singleFilter as $value): ?>
									<?php if ($value['value'] && $value['group'] !== Zolago_Catalog_Helper_Data::ADDITIONAL_ATTRIBUTES_GROUP): ?>
										<option value="<?php echo $value['attribute_id']; ?>" <?php if($activeFilters && array_key_exists($value['attribute_id'], $activeFilters) && $activeFilters[$value['attribute_id']]==$value['value']): $selectedFilter = $value['value']; ?> selected="selected"<?php endif;?> filterValue="<?php echo $this->escapeHtml($value['value']); ?>"><?php echo substr($this->escapeHtml($value['value']), 0, 20);?></option>
									<?php endif; ?>
								<?php endforeach; ?>
							</select>
							<?php // if ($selectedFilter): ?>
								<br /><span class="selectedFilter"><?php echo $selectedFilter; ?></span>
							<?php // endif; ?>
						</span>
					<?php endif; ?>
				<?php endif; ?>
			<?php endforeach; ?>
		</div>
		<!-- Static Filters from All Attribute Groups: End -->

		<!-- Static Filters from Special Attribute Group: Start -->
		<div class="right">
			<?php foreach($this->getStaticFilters($this->getCurrentAttributeSetId()) as $singleFilter): ?>
				<?php if ($singleFilter): ?>
					<?php
						$firstFilter = current($singleFilter);
						$filterLabel = $this->getAttributeLabel($firstFilter['code'], $this->getStore());
						$selectedFilter = false;
					?>
					<?php if ($firstFilter['group'] == Zolago_Catalog_Helper_Data::ADDITIONAL_ATTRIBUTES_GROUP): ?>
						<span class="filter-box">
							<label for="staticFilter"><?php echo $filterLabel; ?>:</label>
							<select name="staticFilter" id="staticFilter-<?php echo $firstFilter['attribute_id']; ?>" class="staticFilter">
								<option value=""><?php echo Mage::helper("zolagocatalog")->__("--- Select ---"); ?></option>
							<?php foreach($singleFilter as $value): ?>
									<?php if ($value['value'] && $value['group'] == Zolago_Catalog_Helper_Data::ADDITIONAL_ATTRIBUTES_GROUP): ?>
										<option value="<?php echo $value['attribute_id']; ?>" <?php if($activeFilters && array_key_exists($value['attribute_id'], $activeFilters) && $activeFilters[$value['attribute_id']]==$value['value']): $selectedFilter = $value['value']; ?> selected="selected"<?php endif;?> filterValue="<?php echo $this->escapeHtml($value['value']); ?>"><?php echo substr($this->escapeHtml($value['value']), 0, 20);?></option>
									<?php endif; ?>
								<?php endforeach; ?>
							</select>
							<?php // if ($selectedFilter): ?>
								<br /><span class="selectedFilter"><?php echo $selectedFilter; ?></span>
							<?php // endif; ?>
						</span>
					<?php endif; ?>
				<?php endif; ?>
			<?php endforeach; ?>
		</div>
		<!-- Static Filters from Special Attribute Group: End -->
		<span class="filterSearch">
			<button type="button" title="<?php echo $this->__('Reset Filter') ?>" class="scalable task" onclick="resetStaticFilter(this);"><span><span><?php echo $this->__('Reset Filter') ?></span></span></button>
			<button type="button" title="<?php echo $this->__('Search') ?>" class="scalable task" onclick="changeStaticFilter(this);"><span><span><?php echo $this->__('Search') ?></span></span></button>
		</span>
		<div class="clear"></div>
	</div>
	<?php else: ?>
		<p class="switcher">
			<?php echo $this->__('There are no Static Filters for this Attribute Set'); ?>
		</p>
	<?php endif; ?>
</div>
<script type="text/javascript">
function resetStaticFilter(select){
	var location = '<?php echo $this->getChangeUrl();?>';

	if ($("attribute_set_switcher") && $F("attribute_set_switcher")) {
		location += "attribute_set/" + $F("attribute_set_switcher") + "/";
	}
	if ($("store_switcher") && $F("store_switcher")) {
		location += "store/" + $F("store_switcher") + "/";
	}
	setLocation(location);
}

function changeStaticFilter(select){
	var location = '<?php echo $this->getChangeUrl();?>';
	var filtersCount = $$('.staticFilter').length;
	var activeFilter = 1;
	$$('.staticFilter').each(function(element) {
		if ($F(element)) {
			var selectedFilterOption = $$('#' + element.id + ' option').find(function(ele){
				return !!ele.selected;
			});

			var filterValue = selectedFilterOption.getAttribute('filtervalue');
			location += "staticFilterId-"+activeFilter+"/" + $F(element) + "/" + "staticFilterValue-"+activeFilter+"/" + encodeURIComponent(filterValue) + "/";
			activeFilter++;
		} else {
			filtersCount--;
		}
	});

	location += "staticFilters/" + filtersCount + "/";

	if ($("attribute_set_switcher") && $F("attribute_set_switcher")) {
		location += "attribute_set/" + $F("attribute_set_switcher") + "/";
	}
	if ($("store_switcher") && $F("store_switcher")) {
		location += "store/" + $F("store_switcher") + "/";
	}
	setLocation(location);
}
</script>