<?php /* @var $this Mage_Catalog_Block_Product_List */ ?>
<?php /* @var $this SolrBridge_Solrsearch_Block_Product_List */ ?>
<?php /* @var $this ZolagoOs_OmniChannelMicrosite_Block_Frontend_VendorProducts */ ?>
<?php /* @var $this Zolago_Solrsearch_Block_Catalog_Product_List */ ?>
<?php
$imgUrl = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . "catalog/product/cache/";
/** @var Zend_Currency $currency */
$currency = Mage::app()->getLocale()->currency(Mage::app()->getStore()->getCurrentCurrency()->getCode());
$symbol = " " . $currency->getSymbol();

/**
 * Author: Paweł Chyl <pawel.chyl@orba.pl>
 * Date: 19.08.2014
 */
/** @var $product Zolago_Solrsearch_Model_Catalog_Product */
$_productImageUrl = '';

/** @var Zolago_Customer_Model_Session $customerSession */
$customerSession = Mage::getSingleton('zolagocustomer/session');
$_cache = $customerSession->getProductsCache();
$_products = $_cache['products'];
?>
<noscript>
	<?php //dont show overlay for web crawlers and javascript disabled browsers ?>
	<style>
		.listing-overlay {
			display:none !important;
			width: 0;
			height: 0;
			visibility: hidden;
			z-index: -1;
			background: #F2F1F0;
		}
	</style>
</noscript>
<div class="listing-overlay" style="position: fixed; width: 100%; height: 100%; left: 0; top: 0; z-index: 1000000; background: url('<?php echo $this->getSkinUrl("images/default-ajax-loader.gif"); ?>') 50% 50% no-repeat rgba(255,255,255,0.5);"></div>
<section id="main">
	<div id="content" class="container-fluid">
		<div class="row">
			<div class="col-sm-12">
				<div class="listing-overlay" style="position: absolute; width: 100%; height: 100%; top: 0; left: 0; z-index: 999;"></div>
				<div id="content-main">
					<?php echo $this->getChildHtml('solrsearch_result_title'); ?>
					<?php echo $this->getChildHtml('solrsearch_product_list_header_search'); ?>
					<?php echo $this->getChildHtml('solrsearch_product_list_toolbar'); ?>

					<div class="container-fluid" id="items-product">
						<div class="row">
							<div class="col-xs-12 col-sm-12">
								<div class="row">
									<div id="grid" class="shuffle--container shuffle--fluid">
										<?php $n = 1; ?>
										<!-- START LIST PRODUCT -->
										<?php foreach ($_products as $product): ?>
											<?php
											/**
											 * @see Zolago_Solrsearch_Helper_Data::prepareAjaxProducts()
											 * product[0] = id
											 * product[1] = name
											 * product[2] = url
											 * product[3] = price
											 * product[4] = final_price
											 * product[5] = wishlist_count
											 * product[6] = in_my_wishlist
											 * product[7] = image_url
											 * product[8] = image_ratio
											 * product[9] = manufacturer_logo_url
											 * product[10]= sku
											 * product[11]= skuv
											 * product[12]= product_flag
											 * product[13]= is_new
											 * product[15]= flag
											 * product[16]= prod_type
											 * product[17] = qty
											 * product[18] = min_qty
											 */
											?>

											<div id="prod-<?php echo $product[0];?>" class="item col-phone col-xs-4 col-sm-6 col-md-4 col-lg-4 size14">
												<div class="box_listing_product">
													<a href="<?php echo $product[2]; ?>"
													   title="<?php echo $product[1]; ?>"
													   data-entity="<?php echo $product[0]; ?>"
													   data-sku="<?php echo $product[10]; ?>"
													   data-skuv="<?php echo $product[11]; ?>"
													   data-product-type="<?php echo $product[16]; ?>">
														<?php if($product[15]) : ?>
															<div class="label-product">
																<div class="listing-label type-label-<?php echo $product[15]; ?>">
																	<div class="flag-<?php echo $product[15];?>"></div>
																</div>
															</div>
														<?php endif;?>
														<figure class="img_product boxed">
															<img
																src="<?php echo $imgUrl . $product[7]; ?>"
																alt="<?php echo $product[1]; ?>"
																class="img-responsive"/>
														</figure>
														<div class="name_product"><?php echo $product[1]; ?></div>

														<div class="price clearfix">
															<div class="col-price">
																<?php if ($product[3] != $product[4]) : ?>
																<span class="old"><?php echo str_replace(".",",",Zend_Locale_Math::round(sprintf("%F", $product[3]), 2)).$symbol; ?></span>
																<?php endif; ?>
																<span><?php echo str_replace(".",",",Zend_Locale_Math::round(sprintf("%F", $product[4]), 2)).$symbol; ?></span>
															</div>
															<div class="size-box-bundle col-lg-12 col-md-12 col-sm-12 col-xs-12 clearfix">
																<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12 clearfix quantity_block">
																	<?php if (	$product[16] == Mage_Catalog_Model_Product_Type::TYPE_SIMPLE ||
																				$product[16] == Mage_Catalog_Model_Product_Type::TYPE_BUNDLE) : ?>
																	<a href="#" class="qty_less" id="qty-less-<?php echo $product[0];?>" data-min_qty="<?php echo $product[18]; ?>">-</a>
																	<div class="qty qty-box" id="input-box-<?php echo $product[0];?>"
																		 title="<?php echo Mage::helper('zolagosolrsearch')->__("Maximum quantity&nbsp;%s", $product[17]); ?>"
																		 data-toggle="tooltip" data-placemen="top"><input type="text" name="quantity" value="1"/></div>
																	<a href="#" class="qty_more" id="qty-more-<?php echo $product[0];?>" data-qty="<?php echo $product[17]; ?>">+</a>
																	<?php else: ?>
																	<p class="variants"><?php echo Mage::helper('zolagosolrsearch')->__("Available in several variants"); ?></p>
																	<?php endif; ?>
																</div>
																<div class="action-box-container col-lg-6 col-md-6 col-sm-6 col-xs-12 clearfix">
																	<div class="action-box-bundle clearfix">
																		<?php if (	$product[16] == Mage_Catalog_Model_Product_Type::TYPE_SIMPLE ||
																					$product[16] == Mage_Catalog_Model_Product_Type::TYPE_BUNDLE) : ?>
																		<button class="btn button button-primary addBasket"
																				onclick="Mall.validateAddingToCartListing(<?php echo $product[0] ?>, <?php echo $product[18]; ?>, <?php echo $product[17]; ?>);return false;">
																			<i class="fa fa-shopping-cart" aria-hidden="true"></i>
																			<?php echo Mage::helper('zolagosolrsearch')->__("Add"); ?>
																		</button>
																		<?php else: ?>
																		<span class="btn button button-primary addBasket">
																			<i class="fa fa-shopping-cart" aria-hidden="true"></i>
																			<?php echo Mage::helper('zolagosolrsearch')->__("See"); ?>
																		</span>
																		<?php endif; ?>
																	</div>
																</div>
															</div>
														</div>
													</a>
												</div>
											</div>

											<?php if ($n % 2 == 0): ?>
												<div class="clearfix visible-two-listing-columns"></div>
											<?php endif; ?>

											<?php if ($n % 3 == 0): ?>
												<div class="clearfix visible-three-listing-columns"></div>
											<?php endif; ?>





											<?php $n++; ?>
										<?php endforeach; ?>
									</div>
									<div class="col-xs-12 shuffle__sizer"></div>

								</div>
							</div>
						</div>
					</div>
					<div class="pagination-line pagination-bottom">
						<?php echo $this->getChildHtml('product_list_toolbar_pager'); ?>
					</div>
					<div id="listing-loading">
						<img src="<?php echo $this->getSkinUrl("images/ajax-loader.gif"); ?>" alt="">
					</div>




					<?php if ($this->getListModel()->isGoogleBot()): ?>
						<?php echo $this->getChildHtml('product_list_toolbar_pager_full'); ?>
					<?php endif; ?>

					<script type="text/javascript">

						Mall.listing.setQuery("<?php echo Mage::helper('catalogsearch')->getQueryText(); ?>");
						Mall.listing.setScat(<?php echo $this->getLayer()->getCurrentCategory()->getId(); ?>);
						Mall.listing.setInitProducts(<?php echo $this->getJsonProducts($_products); ?>);
						Mall.listing.setProductsPerPage(<?php echo count($_products) - 8; ?>);

						Mall.translate.add("you-like-this", "<?php echo $this->__("You like this"); ?>");
						Mall.translate.add("added-to-shopping-list", "<?php echo Mage::helper("zolagocatalog")->__("Added to shopping list"); ?>");
						Mall.translate.add("add-to-br-favorites", "<?php echo $this->__("Add to<br />favorites"); ?>");
						Mall.translate.add("like-this-product", "<?php echo $this->__("like this product"); ?>");
						Mall.translate.add("likes-this-product", "<?php echo $this->__("likes this product"); ?>");
						Mall.translate.add("you-and", "<?php echo $this->__("You and"); ?>");
						Mall.translate.add("person", "<?php echo $this->__("person"); ?>");
						Mall.translate.add("people", "<?php echo $this->__("people"); ?>");
						Mall.translate.add("people-polish-more-than-few", "<?php echo $this->__("people polish more than few"); ?>");
						Mall.translate.add("you", "<?php echo $this->__("You"); ?>");
						Mall.translate.add("Show more", "<?php echo Mage::helper('zolagosolrsearch')->__("Show more"); ?>");
						Mall.translate.add("Show less", "<?php echo Mage::helper('zolagosolrsearch')->__("Show less"); ?>");

						Mall.translate.add("Promotion", "<?php echo Mage::helper('zolagosolrsearch')->__("Promotion"); ?>");
						Mall.translate.add("Sale", "<?php echo Mage::helper('zolagosolrsearch')->__("Sale"); ?>");
						Mall.translate.add("New", "<?php echo Mage::helper('zolagosolrsearch')->__("New"); ?>");

						Mall.translate.add("Add", "<?php echo Mage::helper('zolagosolrsearch')->__("Add"); ?>");
						Mall.translate.add("See", "<?php echo Mage::helper('zolagosolrsearch')->__("See"); ?>");
						Mall.translate.add("Available in several variants", "<?php echo Mage::helper('zolagosolrsearch')->__("Available in several variants"); ?>");
						Mall.translate.add("Maximum quantity", "<?php echo Mage::helper('zolagosolrsearch')->__("Maximum quantity"); ?>");

						Mall.initUrls("<?php echo Mage::getBaseUrl(); ?>", "<?php echo Mage::getBaseUrl(); ?>");

						<?php foreach ($_products as $product): ?>
						Mall.wishlist.addProduct({
							id: <?php echo $product[0]; ?>,
							wishlist_count: <?php echo (int)$product[5]; ?>,
							in_your_wishlist: <?php echo $product[6] ? "true" : "false"; ?>
						});
						<?php endforeach; ?>

						Mall.reg.set("varnish_category_id", <?php echo $this->getLayer()->getCurrentCategory()->getId(); ?>);

						jQuery(window).on("resize", function () {
							jQuery("#items-product .name_product").each(function(){
								let t = jQuery(this);
								let height = t.height();
								t.height("auto");

								if (!t.data("origText")) t.data("origText", t.text());
								else t.text(t.data("origText"));

								while (t.height() > height)
									t.text(function (index, text) {
										return text.replace(/\W*\s(\S)*$/, '...');
									});
								
								t.height(height);
							});
						}).resize();
					</script>

				</div>
			</div>
		</div>
	</div>
</section>

<div class="modal bs-example-modal-lg" id="popup-after-add-to-cart" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel"
	 aria-hidden="true">
	<div class="modal-dialog modal-lg">
		<div class="modal-content">
			<div class="modal-error modal-header" style="display: none;">
				<button type="button" class="close" data-dismiss="modal"></button>
				<h2 class="title_section"><?php echo $this->__("Error occured!"); ?></h2>
			</div>
			<div class="modal-loading modal-header">
				<button type="button" class="close" data-dismiss="modal"></button>
				<h2 class="title_section"><?php echo $this->__("Adding product to cart..."); ?></h2>
			</div>
			<div class="modal-loaded modal-header" style="display: none;">
				<button type="button" class="close" data-dismiss="modal"></button>
				<h2 class="title_section"><?php echo $this->__("Product has been added to cart:"); ?></h2>
			</div>
			<div class="modal-body modal-error" style="display: none">
				<div class="modal-error-txt">

				</div>
			</div>
			<div class="modal-body modal-loading" style="text-align: center">
				<i class="fa fa-spinner fa-spin fa-2x"></i>
			</div>
			<div class="modal-loaded modal-body" style="display: none;">
				<table>
					<tbody id="product-added">
					<tr id="full-width-popup-table">
						<td class="thumb" style="width: 55px;"><img style="width: 42px;" alt=""></td>
						<td class="desc"><p class="name_product"></p>
							<p class="quantity"><?php echo ucfirst($this->__("quantity")); ?>: <span>1</span></p></td>
						<td class="price"></td>
					</tr>
					<tr id="small-width-popup-table">
						<td></td>
						<td class="price" style="padding: 0 5px;"></td>
					</tr>
					</tbody>
				</table>
				<div id="buttons-after-add-to-cart">
					<div class="button-after-add-to-cart" id="continue-shopping-after-add-to-cart">
						<a href="#" data-dismiss="modal" class="button button-third">
							<?php echo $this->__("Continue shopping"); ?>
						</a>
					</div>
					<div class="button-after-add-to-cart" id="cart-after-add-to-cart">
						<a href="<?php echo Mage::getUrl('checkout/cart'); ?>" class="button button-primary medium link">
							<?php echo $this->__("Go to shopping cart"); ?>
						</a>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>