<?php
/**
 * Author: Paweł Chyl <pawel.chyl@orba.pl>
 * Date: 08.09.2014
 */

?>

<div class="form-group clearfix hide-success-vaild">
    <div class="row">
        <label class="col-lg-3 col-md-3 col-sm-3 col-xs-12" for="account_password"><?php echo $this->__("Password"); ?></label>
        <div class="col-lg-9 col-md-9 col-sm-9 col-xs-12">
            <input type="password" class="form-control password validate-passwordbackend" id="account_password" title="" name="account[password]" data-original-title="<?php echo $this->__("Enter a password with at least six characters."); ?>">
        </div>
	    <input type="hidden" class="form-control password" id="account_confirmation" title="" name="account[confirmation]">
    </div>
</div>
