<?php
$_item = $this->getItem();
$_helper = Mage::helper("zolagocataloginventory");
$isVisibleProduct = $_item->getProduct()->isVisibleInSiteVisibility();
$canApplyMsrp = Mage::helper('catalog')->canApplyMsrp($_item->getProduct(), Mage_Catalog_Model_Product_Attribute_Source_Msrp_Type::TYPE_BEFORE_ORDER_CONFIRM);
?>

	<div class="table-heading hidden-xs">
		<div class="hcena"><?php echo $this->__("Price");?></div>
		<div class="hilosc"><?php echo $this->__("Quantity");?></div>
		<div class="hwartosc"><?php echo $this->__("Value");?></div>
	</div>



	<div class="table-group clearfix">
		<div class="tabcol-2">
			<div class="ilosc">
				<span class="lb visible-xs"><?php echo $this->__("Quantity");?>:</span> 
				<span><?php echo $this->getQty($_item); ?></span>
			</div>
			<div class="cena">
				<?php echo Mage::helper("core")->formatPrice($_item->getPriceInclTax());?>
			</div>
			<div class="wartosc hidden-xs">
				<span class="wartosc_zakupu"><?php echo Mage::helper("core")->formatPrice($_item->getPriceInclTax() * $this->getQty($_item));?></span>
			</div>
		</div>
		<div class="tabcol-1">
			<div class="zdjecie">
				<img src="<?php echo $this->getProductThumbnail()->resize(53, 69); ?>" alt="<?php echo $this->escapeHtml($this->getProductName()) ?>"/>
			</div>
			<div class="nazwa_rozmiar">
				<dl>
					<dt class="nazwa_produktu"><?php echo $this->escapeHtml($this->getProductName()) ?></dt>
					<?php if ($_options = $this->getOptionList()):?>
                    <?php foreach ($_options as $_option) : ?>
                        <?php $_formatedOptionValue = $this->getFormatedOptionValue($_option) ?>
						<dd class="rozmiar_produktu"><?php echo $this->escapeHtml($_option['label']) ?>: <?php echo $_formatedOptionValue['value'] ?></dd>
                    <?php endforeach; ?>
                <?php endif;?>
				</dl>
			</div>
		</div>
	</div>

