<?php
/** @var Zolago_Solrsearch_Helper_Data $helperZSS */
$helperZSS = Mage::helper('zolagosolrsearch');
/** @var Zolago_Dropship_Model_Vendor $vendor */
$vendor = Mage::helper('umicrosite')->getCurrentVendor();
$currentCategory = Mage::getSingleton('zolagosolrsearch/catalog_product_list')->getCurrentCategory();

/** @var Zolago_DropshipMicrosite_Helper_Data $helperZDM */
$helperZDM = Mage::helper("zolagodropshipmicrosite");
$vendorRootCategoryId = $helperZDM->getVendorRootCategoryObject()->getId();

$rootCategoryId = Mage::app()->getStore()->getRootCategoryId();
$rootCategory = Mage::getModel('catalog/category')->load($rootCategoryId);

?>
<div class="current-search">
	<h1>
		<?php if (!$helperZSS->getNumFound()): ?>
			<?php echo $helperZSS->__("Search results for query &bdquo;%s&rdquo; not found.", $helperZSS->getQueryText()) ?>
			<br/>
		<?php elseif ($category = $helperZSS->getFallbackCategory()) : ?>
			<?php if ($helperZSS->isOriginalQuery()) : ?>
				<?php echo $helperZSS->__("Search results for query &bdquo;%s&rdquo; not found for category %s", $helperZSS->getQueryText(), $category->getName()) ?>
				<br/>
			<?php else : ?>
				<?php echo $helperZSS->__("Search results for query &bdquo;%s&rdquo; not found in gallery.", $helperZSS->getQueryText()) ?>
				<br/>
			<?php endif; ?>
		<?php elseif (!$helperZSS->isOriginalQuery()) : ?>
			<?php echo $helperZSS->__("Search results for query &bdquo;%s&rdquo; not found.", $helperZSS->getQueryText()) ?>
			<br/>
		<?php endif; ?>
		<?php if (!$helperZSS->isOriginalQuery() && $helperZSS->getNumFound()) : ?>
			<?php echo $helperZSS->__("Did you mean &bdquo;%s&rdquo; ?", $helperZSS->getSolrRealQ()) ?>
			<br/>
		<?php endif; ?>

		<?php if ($helperZSS->getNumFound()): ?>
			<?php if ($helperZSS->getFallbackCategory()): ?>
				<br/>
			<?php endif; ?>
			<?php if (!$helperZSS->isOriginalQuery()): ?>
				<br/>
			<?php endif; ?>
			<?php echo $helperZSS->__('Search results for:'); ?>
			<span style="white-space:nowrap">
                <span class="query-text uppercase"><?php echo $helperZSS->getSolrRealQ(); ?></span>
				<span class="query-text-iks">
                    <a href="<?php echo $helperZSS->getFilterUrl(null, $currentCategory, $vendor); ?>"
                       class="fa fa-times active-filter-label iks"></a>
                </span>
            </span>
			<?php if ($vendor) : ?>
				<?php if ($currentCategory && ($currentCategory->getId() != $vendorRootCategoryId)) : ?>
					<?php echo $helperZSS->__('in category'); ?>
					<span style="white-space:nowrap">
		                <span class="query-text uppercase"><?php echo $currentCategory->getName(); ?></span>
						<span class="query-text-iks">
	                        <a href="<?php echo $helperZSS->getFilterUrl($helperZSS->getSolrRealQ(), null, $vendor); ?>"
		                       class="fa fa-times active-filter-label iks"></a>
	                    </span>
                    </span>
				<?php endif; ?>
				<?php echo $helperZSS->__("in "); ?>
				<span style="white-space:nowrap">
                    <span class="query-text uppercase"><?php echo $vendor->getVendorName(); ?></span>
					<span class="query-text-iks">
                        <a href="<?php echo $helperZSS->getFilterUrl($helperZSS->getSolrRealQ(), ($currentCategory->getId() == $vendorRootCategoryId) ? $rootCategory : $currentCategory, null); ?>"
                           class="fa fa-times active-filter-label iks"></a>
                    </span>
                </span>
			<?php else : ?>
				<?php if (!$currentCategory || ($currentCategory->getId() == Mage::app()->getStore()->getRootCategoryId())) : ?>
					<?php echo $helperZSS->__('in whole shop'); ?>
				<?php else : ?>
					<?php echo $helperZSS->__('in category'); ?>
					<span style="white-space:nowrap">
                        <span class="query-text uppercase"><?php echo $currentCategory->getName(); ?></span>
                        <span class="query-text-iks">
                            <a href="<?php echo $helperZSS->getFilterUrl($helperZSS->getSolrRealQ(), null, null); ?>"
                               class="fa fa-times active-filter-label iks"></a>
                        </span>
                    </span>
				<?php endif; ?>
			<?php endif; ?>
		<?php endif; ?>

	</h1>

	<?php if (!$helperZSS->getNumFound()): ?>
		<div id="search-page-empty">
			<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('search-page-empty')->toHtml(); ?>
		</div>
	<?php endif; ?>
</div>
<script>
    Mall.setQueryText('<?php echo addslashes($helperZSS->getQueryText()); // Fix for Varnish ?>');
    Mall.Navigation.currentCategoryId.push('<?php echo $currentCategory->getId();?>');
</script>