<?php /* @var $this Zolago_Blog_Block_Catalog_Product_Posts */ ?>

<div class="col-md-12 product-blog-post-items">

    <?php $productBlogItems = $this->_productBlogItems; ?>

    <?php if ($productBlogItems->getSize() > 0): ?>
        <?php foreach ($productBlogItems as $productBlogItem): ?>
            <div class="col-md-12 product-blog-post-item">
                <?php if (!empty($postThumb = $productBlogItem->getPostThumbnail())): ?>
                    <a href="<?php echo $productBlogItem->getUrl(); ?>">
                        <img class="resize"
                             src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . $postThumb; ?>"/>
                        <?php echo $productBlogItem->getTitle(); ?>
                    </a>
                <?php endif; ?>
            </div>
            <?php //Zend_Debug::dump($productBlogItem->getData("post_thumbnail")); ?>
        <?php endforeach; ?>
    <?php endif; ?>
</div>
<style>
    .product-blog-post-items {

    }

    .product-blog-post-item {
        margin-bottom: 10px;
        height: 100px;
    }

    img.resize {
        max-width: 100px;
        max-height: 100px;
        width: auto;
        height: auto;
    }
</style>