<?php /* @var $this Zolago_Blog_Block_Catalog_Product_Posts */ ?>

<div class="product-blog-post-items">
    <?php $productBlogItems = $this->_productBlogItems; ?>

    <?php if ($productBlogItems->getSize() > 0): ?>
        <?php foreach ($productBlogItems as $productBlogItem): ?>
            <div class="col-md-12 col-sm-6 col-xs-6 product-blog-post-item">
                <div class="product-blog-post-item-container">
                    <a href="<?php echo $productBlogItem->getUrl(); ?>">
                        <?php if (!empty($postThumb = $productBlogItem->getPostThumbnail())): ?>
                            <div class="col-md-6 col-sm-4 col-xs-12 post-thumb">
                                <img class="product-post-thumb"
                                     src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . $postThumb; ?>"/>
                            </div>

                        <?php elseif (!empty($listThumb = $productBlogItem->getListThumbnail())): ?>
                            <div class="col-md-6 col-sm-4 col-xs-12 post-thumb">
                                <img class="product-post-thumb"
                                     src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . $listThumb; ?>"/>
                            </div>
                        <?php endif; ?>
                        <div class="col-md-6 col-sm-8 col-xs-12 post-title">
                            <span><?php echo $productBlogItem->getTitle(); ?></span>
                        </div>
                    </a>
                </div>
            </div>
        <?php endforeach; ?>
    <?php endif; ?>
</div>