<div class="content-header">
<table cellspacing="0">
    <tr>
        <td style="width:50%;"><h3><?php echo Mage::helper('zolagomapper')->__('Category Mapper') ?></h3></td>
        <td class="a-right">
            <?php echo $this->getButtonsHtml() ?>
        </td>
    </tr>
</table>
</div>
<div>
    <?php echo $this->getChildHtml('zolagomapper_mapper_grid') ?>
</div>
<script>
    <?php //echo $this->prepareJsCustomIds(); ?>
</script>