<?php
/**
 * Customer "Remember Me" template
 *
 * @var $this Mage_Persistent_Block_Form_Remember
 */
?>

<li class=" col-md-offset-3 col-sm-offset-0 col-xs-offset-0">
	<div class="form-group form-checkbox small">
		<input type="checkbox" name="rodzaj" id="remember_this" class="css-checkbox ">
		<label for="remember_this" class="css-label remember_this"><?php echo Mage::helper("zolagocustomer")->__('Remember Me') ?></label>
		<span class="badge hint" title="<?php echo Mage::helper("zolagocustomer")->__("Access favourites without login");?>">?</span>
	</div>
</li>

<?php /*
<li id="remember-me-box" class="control">
    <?php $rememberMeId = 'remember_me' . Mage::helper('core')->getRandomString(10); ?>
    <div class="input-box">
        <input type="checkbox" name="persistent_remember_me" class="checkbox" id="<?php echo $rememberMeId; ?>"<?php if ($this->isRememberMeChecked()): ?> checked="checked"<?php endif; ?> title="<?php echo $this->__('Remember Me') ?>" />
    </div>
    <label for="<?php echo $rememberMeId; ?>"><?php echo $this->__('Remember Me') ?></label>
    <a class="link-tip" href="#"><?php echo $this->__('What\'s this?') ?></a>
</li> */?>
