<?php
/**
 * Customer "Remember Me" template
 *
 * @var $this Mage_Persistent_Block_Form_Remember
 */
$_sessChecked = Mage::getSingleton('customer/session')->getIsPersistent(true);
$_checked = $_sessChecked!==null ? $_sessChecked : $this->isRememberMeChecked();

?>

<li class=" col-md-offset-3 col-sm-offset-0 col-xs-offset-0">
	<div class="form-group form-checkbox small">
		<input type="hidden" name="persistent_remember_me" value="0"/>
		<input type="checkbox" <?php if ($_checked): ?> checked="checked"<?php endif; ?> name="persistent_remember_me" id="remember_this" class="css-checkbox"/>
		<label for="remember_this" class="css-label remember_this"><?php echo Mage::helper("zolagocustomer")->__('Remember Me') ?></label>
		<!-- <span class="badge hint" title="<?php echo Mage::helper("zolagocustomer")->__("Access favourites without login");?>">?</span> -->
	</div>
</li>