<?php /** @var Zolago_Pos_Block_Dropship_Pos $this */
$_helper = Mage::helper("zolagopos");?>
<div class="container">
	<!--=== Page Header ===-->
	<div class="page-heading row">
		<div class="col-lg-6">
			<h3><?php echo $_helper->__("POS List");?></h3>
			<span class="tageline"><?php echo Mage::helper("zolagopo")->__("Browse your POS");?></span>
		</div>
		<div class="main-actions align-right col-md-6">
			<a class="btn btn-success" href="<?php echo Mage::getUrl('udropship/pos/new');?>">
					<i class="icon-plus"></i>
					<?php echo $_helper->__("Create POS");?>
				</a> 
		</div>
	</div>
    <div class="tabbable tabbabble-custom">
        <ul class="nav nav-tabs" style="margin-top:6px">
            <li class="" style="float:left;">
                <a name="tmp"></a>
            </li>
            <li class="active" style="float:left">
                <a data-toggle="tab" href="#tab_1_1"><?php echo Mage::helper('zolagopos')->__('List'); ?></a>
            </li>
            <li class="" style="float:left;">
                <a data-toggle="tab" href="#tab_1_2"><?php echo Mage::helper('zolagopos')->__('Settings'); ?></a>
            </li>


        </ul>
        <div class="tab-content">
            <div id="tab_1_1" class="tab-pane active">
                <?php echo $this->getChildHtml("pos_list"); ?>
            </div>

            <div id="tab_1_2" class="tab-pane">
                <?php echo $this->getChildHtml("pos_settings"); ?>
            </div>

        </div>
    </div>

</div>


