<?php
/**
 * Used in cms block: navigation-main-desktop
 */
/** @var $this Zolago_Modago_Block_Catalog_Category */

$mainCategories = $this->getMainCategories();

?>

<?php foreach($mainCategories as $cat) : ?>
    <li>
        <a data-catids="<?php echo $cat['category_id'] .','. $cat['ids']; ?>" href="<?php echo $cat['dropdown'] ? '#' : $cat['url']; ?>" class="<?php echo $cat['dropdown'] ? 'children' : '' ?>"><?php echo $this->escapeHtml($cat['name']); ?> <?php echo $cat['dropdown'] ? '<i class="fa fa-caret-down"></i>' : ''; ?></a>
        <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('navigation-dropdown-c-' . $cat['category_id'])->toHtml(); ?>
    </li>
<?php endforeach; ?>
