<?php
/**
 * Used in cms block: navigation-main-mobile
 */
/** @var $this Zolago_Modago_Block_Catalog_Category */
$categories = $this->getMainCategoriesMobile();
?>
<?php if (count($categories) > 0) : ?>
    <?php foreach ($categories as $cat) : ?>
        <li>
            <a href="<?php echo (isset($cat['has_dropdown']) && $cat['has_dropdown'])  ? '#' : $cat['url']; ?>">
                <?php echo $this->escapeHtml($cat['name']); ?>
                <?php echo (isset($cat['has_dropdown']) && $cat['has_dropdown']) ? '<i class="fa fa-chevron-down"></i>'
                    : '<i class="fa fa-chevron-right"></i>'; ?>
            </a>
            <?php if (isset($cat['has_dropdown']) && $cat['has_dropdown']) : ?>
                <ul>
                    <?php foreach ($cat['has_dropdown'] as $child) : ?>
                        <li>
                            <a href="<?php echo $child['url']; ?>">
                                <?php echo $this->escapeHtml($child['name']); ?>
                            </a>
                        </li>
                    <?php endforeach; ?>
                </ul>
            <?php endif; ?>
        </li>
    <?php endforeach; ?>

<?php endif; ?>