<?php
/**
 * Content of this block is ajax loaded
 * for varnish
 */
?>

<div class="block_search search hidden-sm hidden-xs">
    <form action="<?php echo Mage::getUrl("search/index/index", array("_secure" => Mage::app()->getStore()->isCurrentlySecure())); ?>" method="get" role="search">
        <div class="form-group">
            <input type="text" class="form-control" name="q" placeholder="<?php echo $this->__('Search entire store here...'); ?>" value="">
        </div>
        <div class="select-box">
            <select name="scat" class="form-control select-styled search-context">
                <?php /* foreach($options['select_options'] as $opt) : ?>
                <option value="<?php echo $opt['value']; ?>" <?php if($opt['selected']) : ?>selected="selected"<?php endif; ?>><?php echo $opt['text']; ?></option>
                <?php endforeach; */ ?>
            </select>
        </div>
        <input type="image" src="<?php echo $this->getSkinUrl('images/ico_search.gif'); ?>" name="<?php echo $this->__("Search"); ?>" alt="<?php echo $this->__("Search"); ?>">
    </form>
</div>
<script>
    jQuery('div.block_search select').selectbox();
</script>