<?php
/**
 * Author: Paweł Chyl <pawel.chyl@orba.pl>
 * Date: 02.05.14
 */
?>

<div class="block_search search hidden-sm hidden-xs">
    <form role="search">
        <div class="form-group">
            <input type="text" class="form-control" placeholder="<?php echo $this->__("Search"); ?>">
        </div>
        <div class="select-box">
            <select name="" class="form-control select-styled">
                <option value=""><?php echo $this->__("in whole gallery"); ?></option>
                <option value=""><?php echo $this->__("She"); ?></option>
                <option value=""><?php echo $this->__("Him"); ?></option>
            </select>
        </div>
        <input type="image" src="<?php echo $this->getSkinUrl('images/ico_search.gif'); ?>" name="<?php echo $this->__("Search"); ?>"
               alt="<?php echo $this->__("Search"); ?>">
    </form>
</div>
<!-- MOBILE -->
<div id="toggleSearch" class="block_search_m visible-sm visible-xs">
    <a class="dropdown-toggle" data-dropdown="#dropdown-search" href="javascript:void"><i
            class="ico_search_mobile"></i></a>
</div>
<!-- END :// MOBILE -->

<div id="dropdown-search" class="dropdown hidden-md hidden-lg">
    <div class="dropdown-panel">
        <div class="dropdown-panel-inner">
            <div class="searchDropdown">

                <form class="clearfix" role="search">
                    <div class="form-group">
                        <input type="text" class="form-control" placeholder="<?php echo $this->__("Search"); ?>">
                    </div>
                    <div class="form-group styledSelected">
                        <select name="" class="form-control  select-styled">
                            <option value=""><?php echo $this->__("All categories"); ?></option>
                            <option value=""><?php echo $this->__("She"); ?></option>
                            <option value=""><?php echo $this->__("Him"); ?></option>
                        </select>
                    </div>
                    <div class="form-group action">
                        <button class="btn sending pull-right"><?php echo $this->__("Search"); ?></button>
                    </div>
                </form>

            </div>
        </div>
    </div>
</div>
<!-- END:/ TOGGLE BLOCK -->