<?php
/**
 * Author: Paweł Chyl <pawel.chyl@orba.pl>
 * Date: 19.05.14
 */
?>

<div id="dropdown-search" class="dropdown hidden-md hidden-lg">
    <div class="dropdown-panel">
        <div class="dropdown-panel-inner">
            <div class="searchDropdown">

                <form class="clearfix" role="search">
                    <div class="form-group">
                        <input type="text" class="form-control" placeholder="<?php echo $this->__("Search"); ?>">
                    </div>
                    <div class="form-group styledSelected">
                        <select name="" class="form-control  select-styled">
                            <option value=""><?php echo $this->__("All categories"); ?></option>
                            <option value=""><?php echo $this->__("She"); ?></option>
                            <option value=""><?php echo $this->__("Him"); ?></option>
                        </select>
                    </div>
                    <div class="form-group action">
                        <button class="btn sending pull-right"><?php echo $this->__("Search"); ?></button>
                    </div>
                </form>

            </div>
        </div>
    </div>
</div>
<!-- END:/ TOGGLE BLOCK -->