<?php
/**
 * Author: Paweł Chyl <pawel.chyl@orba.pl>
 * Date: 19.05.14
 */
$options = Mage::helper('zolagosolrsearch')->getContextSelectorArray();
?>

<div id="dropdown-search" class="dropdown hidden-md hidden-lg">
    <div class="dropdown-panel">
        <div class="dropdown-panel-inner">
            <div class="searchDropdown">

                <form class="clearfix" role="search" action="<?php echo $options['url']; ?>" method="<?php echo $options['method']; ?>">
                    <div class="form-group">
                        <input type="text" class="form-control" name="<?php echo $options['input_name']; ?>" placeholder="<?php echo $options['input_empty_text']; ?>" value="<?php echo $options['input_current_value']; ?>">
                    </div>
                    <div class="form-group styledSelected">
                        <select name="<?php echo $options['select_name']; ?>" class="form-control  select-styled">
                            <?php foreach($options['select_options'] as $opt) : ?>
                                <option value="<?php echo $opt['value']; ?>" <?php if($opt['selected']) : ?>selected="selected"<?php endif; ?>><?php echo $opt['text']; ?></option>
                            <?php endforeach; ?>
                        </select>
                    </div>
                    <div class="form-group action">
                        <button class="btn sending pull-right"><?php echo $this->__("Search"); ?></button>
                    </div>
                </form>

            </div>
        </div>
    </div>
</div>