<?php
/**
 * Content of this block is ajax loaded
 * for varnish
 */
?>

<div id="dropdown-search" class="dropdown hidden-md hidden-lg">
    <div class="dropdown-panel">
        <div class="dropdown-panel-inner">
            <div class="searchDropdown">

                <form class="clearfix" role="search" action="<?php echo Mage::getUrl("search/index/index", array("_secure" => Mage::app()->getStore()->isCurrentlySecure())); ?>" method="get">
                    <div class="form-group">
                        <input type="text" class="form-control" name="q" placeholder="<?php echo $this->__('Search entire store here...'); ?>">
                    </div>
                    <div class="form-group styledSelected">
						
                        <select name="scat" class="form-control  select-styled search-context">
                            <?php /* foreach($options['select_options'] as $opt) : ?>
                                <option value="<?php echo $opt['value']; ?>" <?php if($opt['selected']) : ?>selected="selected"<?php endif; ?>><?php echo $opt['text']; ?></option>
                            <?php endforeach; */ ?>
                        </select>
                    </div>
                    <div class="form-group action">
                        <button class="btn sending pull-right"><?php echo $this->__("Search"); ?></button>
                    </div>
                </form>

            </div>
        </div>
    </div>
</div>