<?php
/**
 * Author: Paweł Chyl <pawel.chyl@orba.pl>
 * Date: 10.07.2014
 *
 */


/**
 * Product view template
 *
 * @see Mage_Catalog_Block_Product_View
 * @see Mage_Review_Block_Product_View
 */

/** @var $this Zolago_Catalog_Block_Product_View */
?>

<?php
/** @var Zolago_Modago_Block_Review_Product_View_List $_reviewBlock */
$_reviewBlock = Mage::getBlockSingleton('zolagomodago/review_product_view_list');
?>

<?php
// review label
$_reviewsCount = count($_reviewBlock->getReviewsForProduct());
$_reviewsLabel = '';
switch ($_reviewsCount) {
	case 0:
		$_reviewsLabel = $this->__('Zero reviews');
		break;
	case 1:
		$_reviewsLabel = $this->__('Singular review');
		break;
	case 2:
	case 3:
	case 4:
		$_reviewsLabel = $this->__('review');
		break;
	default:
		$_reviewsLabel = $this->__('Zero reviews');
		break;
}
$avg = $_reviewBlock->getAvarageRating();

/** @var Zolago_Dropship_Model_Vendor $vendorContext */
$vendorContext = Mage::helper('umicrosite')->getCurrentVendor();
$isVendorContent = false;
if ($vendorContext && $vendorContext->getId()) {
	$isVendorContent = true;
}


$_helper = $this->helper('catalog/output');
/** @var $_product Zolago_Catalog_Model_Product */
$_product = $this->getProduct();
?>

<div id="content" class="container-fluid">
	<div class="row">
		<div class="col-sm-12">
			<div id="content-main" class="clearfix">
				<div class="row" itemscope itemtype="http://schema.org/Product">
					<section id="product_shop" class="section bg-w clearfix">

						<!-- GALLERY PRODUCT -->
						<div class="path_back_to_category visible-xs">
							<?php if ($isVendorContent): ?>
								<div class="col-xs-12 brandshop">
									<a href="<?php echo $this->getVendorUrl(); ?>">
										<?php echo $vendorContext->isBrandshop() ? $this->__("Brandshop") : $this->__("Vendor"); ?>
										<img alt="<?php echo $this->escapeHtml($this->getVendorName()); ?>"
										     src="<?php echo $this->getVendorLogoUrl(); ?>">
									</a>
								</div>
							<?php endif; ?>
							<div class="col-xs-12">
								<?php if (Mage::registry('mobile_breadcrumb')): ?>
									<?php $mobileBreadcrumb = Mage::registry('mobile_breadcrumb'); ?>
									<a href="<?php echo $mobileBreadcrumb['link']; ?>" id="pbtc_link"><i
											class="fa fa-angle-left"></i> <?php echo $mobileBreadcrumb['label']; ?></a>
								<?php else: ?>
									<a href="<?php echo $this->getParentCategoryUrl(); ?>" id="pbtc_link"><i
											class="fa fa-angle-left"></i> <?php echo $this->getParentCategoryName(); ?></a>
								<?php endif; ?>
							</div>
						</div>


						<?php echo $this->getChildHtml('media') ?>
						<!-- END GALERY PRODUCT -->
						<?php echo
						$this->getChild('product.shop')
							->setReviewsCount($_reviewsCount)
							->setReviewsLabel($_reviewsLabel)
							->setReviewsAvg($avg)
							->toHtml();
						?>
						<!-- END:/ PRODUCT SHOP -->
					</section>
					<!-- SECTION : SKOMPLETUJ CAŁOŚĆ -->
					<?php echo $this->getChildHtml('crosssell'); ?>
					<!-- END:/ SKOMPLETUJ CAŁOŚĆ -->
					<!-- SECTION : OPIS PRODUKTU -->
					<?php echo $this->getChildHtml('product.vendor.info'); ?>
					<section id="description_product" class="section toggle-xs bg-w clearfix" data-mobiletoggle="false">
						<header>
							<h2 class="title_section">Opis produktu <i class="bullet-strzalka-down visible-xs"></i></h2>
						</header>
						<?php $attributesData = $this->getAdditionalDataDetailed(true, false); ?>
						<?php
						$productDescription = $_helper->productAttribute($_product, nl2br($_product->getDescription()), 'description');
						$brandShopProductId = $_product->getData('brandshop');
						?>
						<div class="main">
							<div itemprop="description"><?php echo $productDescription; ?></div>
							<?php if (!empty($attributesData)) : ?>
								<ul class="list">
									<?php foreach ($attributesData as $attr) : ?>
										<li>
											<strong><?php echo array_key_exists('label', $attr) ? $attr['label'] : ""; ?>: </strong>

											<?php if ($attr['code'] == "color"): ?>
												<span itemprop="color"><?php echo $this->escapeHtml($attr['value']); ?></span>
											<?php elseif ($attr['code'] == "manufacturer"): ?>
												<?php
												$vendorsCollection = Mage::getModel("udropship/vendor")->getCollection();
												$vendorsCollection->addFieldToFilter("vendor_name", array("like" => $attr['value']));
												$brand = $vendorsCollection->getFirstItem();

												$brandShopId = $brand->getId();
												$brandShop = Mage::helper('udropship')->getVendor($brandShopId);
												$brandShopName = $brandShop->getData("vendor_name");
												$brandShopUrl = Mage::helper("umicrosite")->getVendorUrl($brandShop);
												?>

												<?php if ($brandShopProductId == $brandShopId): ?>
													<h3 class="itemprop-brand"><a
															href="<?php echo $brandShopUrl; ?>"><?php echo $brandShopName; ?></a></h3>
												<?php else: ?>
													<?php echo $this->escapeHtml($attr['value']); ?>
												<?php endif; ?>


											<?php else: ?>

												<?php if (array_key_exists('value', $attr) && !is_array($attr['value'])) : ?>
													<?php echo $this->escapeHtml($attr['value']); ?>
												<?php else: ?>
													<?php echo implode(",", $attr['value']); ?>
												<?php endif; ?>

											<?php endif; ?>
										</li>
									<?php endforeach; ?>
								</ul>
							<?php endif; ?>
						</div>
					</section>
					<!-- SECTION : OPIS PRODUKTU -->
					<!--reviews-->
					<?php echo $this->getChildHtml('product.review.section'); ?>
					<!--end reviews-->
					<section id="share" class="section clearfix visible-xs">
						<div class="addthis_sharing_toolbox"></div>
					</section>

				</div>
			</div>
		</div>
	</div>
</div>

<div class="modal fade" id="tabelaRozmiarow" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="z-index: 1050">
	<div class="modal-dialog">
		<div class="modal-content">
			<button type="button" class="close" data-dismiss="modal"></button>

			<div class="modal-body">
				<div id="sizeTableIframeContainer">
					<iframe id="sizeTableIframe"></iframe>
				</div>
			</div>
		</div>
	</div>
</div>

<?php echo $this->getChildHtml('product.info.media.modal'); ?>


<!--zadaj pytanie sprzedajacemu-->

<div class="modal fade bs-example-modal-lg" id="ask_question" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
	<div class="modal-dialog modal-lg">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal"></button>
				<h2 class="title_section"><?php echo $this->__("Submit a question about product"); ?></h2>
			</div>
			<div class="modal-body">
				<?php echo $this->getChildHtml('udqa.product.question.product'); ?>
			</div>
		</div>
	</div>
</div>

<!--end zadaj pytanie sprzedajacemu-->


<div class="modal bs-example-modal-lg" id="popup-after-add-to-cart" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel"
     aria-hidden="true">
	<div class="modal-dialog modal-lg">
		<div class="modal-content">
			<div class="modal-error modal-header" style="display: none;">
				<button type="button" class="close" data-dismiss="modal"></button>
				<h2 class="title_section"><?php echo $this->__("Error occured!"); ?></h2>
			</div>
			<div class="modal-loading modal-header">
				<button type="button" class="close" data-dismiss="modal"></button>
				<h2 class="title_section"><?php echo $this->__("Adding product to cart..."); ?></h2>
			</div>
			<div class="modal-loaded modal-header" style="display: none;">
				<button type="button" class="close" data-dismiss="modal"></button>
				<h2 class="title_section"><?php echo $this->__("Product has been added to cart:"); ?></h2>
			</div>
			<div class="modal-body modal-error" style="display: none">
				<div class="modal-error-txt">

				</div>
			</div>
			<div class="modal-body modal-loading" style="text-align: center">
				<i class="fa fa-spinner fa-spin fa-2x"></i>
			</div>
			<div class="modal-loaded modal-body" style="display: none;">
				<table>
					<tbody id="product-added">
					<tr id="full-width-popup-table">
						<td class="thumb" style="width: 55px;"><img
								src="<?php echo Mage::helper('catalog/image')->init($_product, 'image')->resize(40, 50) ?>"
								alt=""></td>
						<td class="desc"><p class="name_product"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></p>

							<p class="size"><?php echo ucfirst($this->__("size")); ?>: <span></span></p>

							<p class="quantity"><?php echo ucfirst($this->__("quantity")); ?>: <span>1</span></p></td>
						<?php /* ensure the price in popup is correct */ ?>
						<td class="price"></td>
					</tr>
					<tr id="small-width-popup-table">
						<td></td>
						<td class="price" style="padding: 0 5px;"></td>
					</tr>
					</tbody>
				</table>
				<div id="buttons-after-add-to-cart">
					<div class="button-after-add-to-cart" id="continue-shopping-after-add-to-cart">
						<a href="#" data-dismiss="modal" class="button button-third">
							<?php echo $this->__("Continue shopping"); ?>
						</a>
					</div>
					<div class="button-after-add-to-cart" id="cart-after-add-to-cart">
						<a href="<?php echo Mage::getUrl('checkout/cart'); ?>" class="button button-primary medium link">
							<?php echo $this->__("Go to shopping cart"); ?>
						</a>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<?php echo $this->getChildHtml('zolago_modago_home_sliderlastseen'); ?>
<?php echo $this->getChildHtml('zolago.page.benefits'); ?>

<script type="text/javascript">
	Mall.wishlist.addProduct({
		id: <?php echo $_product->getId(); ?>,
		wishlist_count: <?php echo (int)$this->getProduct()->getWishlistCount() ?>,
		in_your_wishlist: <?php echo Mage::helper('zolagowishlist')->productBelongsToMyWishlist($_product) ? "true" : "false"; ?>
	});
	Mall.translate.add("you-like-this", "<?php echo $this->__("You like this"); ?>");
	Mall.translate.add("remove-from-favorites", "<?php echo $this->__("remove from favorites"); ?>");
	Mall.translate.add("add-to-br-favorites", "<?php echo $this->__("Add to<br />favorites"); ?>");
	Mall.translate.add("like-this-product", "<?php echo $this->__("like this product"); ?>");
	Mall.translate.add("likes-this-product", "<?php echo $this->__("likes this product"); ?>");
	Mall.translate.add("you-and", "<?php echo $this->__("You and"); ?>");
	Mall.translate.add("person", "<?php echo $this->__("person"); ?>");
	Mall.translate.add("person like", "<?php echo $this->__("person like"); ?>");
	Mall.translate.add("people", "<?php echo $this->__("people"); ?>");
	Mall.translate.add("people likes", "<?php echo $this->__("people likes"); ?>");

	Mall.translate.add("people-polish-more-than-few", "<?php echo $this->__("people polish more than few"); ?>");
	Mall.translate.add("people-polish-more-than-few likes", "<?php echo $this->__("people polish more than few likes"); ?>");
	Mall.translate.add("Select size", "<?php echo $this->__("Select size"); ?>");


	Mall.reg.set("varnish_product_id", <?php echo $_product->getId();?>);
	<?php if($_product->getCategory()):?>
	Mall.reg.set("varnish_category_id", <?php echo $_product->getCategory()->getId();?>);
	<?php endif;?>

	jQuery('.no-size').attr('title', "<?php echo $this->__("This size is temporarily unavailable."); ?>");

	Mall.product.sizetable.setContent(<?php echo $this->getSizeTableForJs();?>);

</script>