<?php $helper = Mage::helper('zolagosalesrule'); ?>
<?php echo $this->getCmsBlock(); ?>
<?php if (($this->isLogged()) || ($this->isPersistent())): ?>
<?php $list = $this->getPromotionList(); ?>
<?php if ($list): ?>
<section id="promotions_list">
    <div class="container-fluid">
    <?php foreach ($list as $item): ?>
        <div class="col-md-3">
            <div class="row">
                <?php if ($item['ruleItem']->getPromoImage()):?>
                <img src="<?php echo $helper->getPromotionImageUrl().DS.$item['ruleItem']->getPromoImage(); ?>">
                <?php endif; ?>
            </div>
            <div class="row">
                <h3><?php echo $item['ruleItem']->getName();?></h3>
            </div>
            <div class="row">
                <?php echo $item['ruleItem']->getDescription();?>
            </div>
            <div class="row">
                <?php if ($this->isLogged()) : ?>
                <h4><?php echo $item['code'];?></h4>
                <?php else : ?>
                <h4><?php for($a=0;$a<strlen($item['code']);$a++): echo '*';endfor; ?></h4>
                <?php endif; ?>
            </div>
        </div>
    <?php endforeach; ?>
    </div>
</section>
<?php endif; ?>
<?php else: ?>
<?php $block = $this->getLayout()->createBlock('customer_account_login');  ?>
<?php // todo - make block visible ?>
<?php endif; ?>
