<?php /* @var $this Mage_Bundle_Block_Catalog_Product_View_Type_Bundle_Option_Radio */ ?>
<?php $_option = $this->getOption(); ?>
<?php $productId = $this->getProduct()->getId(); $ruleId = $this->getRuleId();?>
<?php $_selections  = $_option->getSelections(); ?>
<?php $_default     = $_option->getDefaultSelection(); ?>
<?php list($_defaultQty, $_canChangeQty) = $this->_getDefaultValues(); ?>

<dt>
	<label<?php if ($_option->getRequired()) echo ' class="required"' ?>><?php echo $this->htmlEscape($_option->getTitle()) ?><?php if ($_option->getRequired()) echo '<em>*</em>' ?></label>
</dt>
<dd<?php if ($_option->decoratedIsLast){?> class="last"<?php }?>>
	<div class="input-box">
        <span id="bundle-option-<?php echo $_option->getId() ?>-tier-prices" style="display: none;"></span>
		<?php if ($this->_showSingle()): ?>
		<?php echo $this->getSelectionTitlePrice($_selections[0]) ?>
		<input type="hidden" name="bundle_option[<?php echo $productId ?>][<?php echo $_option->getId() ?>]" value="<?php echo $_selections[0]->getSelectionId() ?>" />
		<?php else:?>
		<ul class="options-list">
			<?php if (!$_option->getRequired()): ?>
			<li><input type="radio" onclick="bundle<?php echo $productId . '_' . $ruleId ; ?>.changeSelection(this)" class="radio" id="bundle-option-<?php echo $_option->getId() ?>" name="bundle_option[<?php echo $productId ?>][<?php echo $_option->getId() ?>]"<?php echo ($_default && $_default->isSalable())?'':' checked="checked" ' ?> value=""/>
				<span class="label"><label for="bundle-option-<?php echo $_option->getId() ?>"><?php echo $this->__('None') ?></label></span>
			</li>
			<?php endif; ?>
			<?php foreach ($_selections as $_selection): ?>
			<li><input type="radio" onclick="bundle<?php echo $productId . '_' . $ruleId ; ?>.changeSelection(this)" class="radio<?php echo $_option->getRequired()?' validate-one-required-by-name':'' ?> change-container-classname" id="bundle-option-<?php echo $_option->getId() ?>-<?php echo $_selection->getSelectionId() ?>" name="bundle_option[<?php echo $productId ?>][<?php echo $_option->getId() ?>]"<?php if ($this->_isSelected($_selection)) echo ' checked="checked"' ?><?php if (!$_selection->isSaleable()) echo ' disabled="disabled"' ?>value="<?php echo $_selection->getSelectionId() ?>"/>
				<span class="label"><label for="bundle-option-<?php echo $_option->getId() ?>-<?php echo $_selection->getSelectionId() ?>"><?php echo $this->getSelectionTitlePrice($_selection) ?></label></span>
				<?php if ($_option->getRequired()): ?>
					<script type="text/javascript">
						$('bundle-option-' + <?php echo $_option->getId().'-'.$_selection->getSelectionId(); ?>).advaiceContainer = 'bundle-option-' + <?php echo $_option->getId(); ?> + '-container';
						$('bundle-option-' + <?php echo $_option->getId().'-'.$_selection->getSelectionId(); ?>).callbackFunction  = bundle<?php echo $productId . '_' . $ruleId ; ?>.validationCallback;
					</script>
					<?php endif; ?>
			</li>
			<?php endforeach; ?>
		</ul>
		<div id="bundle-option-<?php echo $_option->getId() ?>-container"></div>
		<?php endif; ?>
	</div>
    <span class="qty-holder">
        <label for="bundle-option-<?php echo $_option->getId() ?>-qty-input"><?php echo $this->__('Qty:') ?>&nbsp;</label><input onkeyup="bundle<?php echo $productId . '_' . $ruleId ; ?>.changeOptionQty(this, event)" onblur="bundle<?php echo $productId; ?>.changeOptionQty(this, event)" <?php if (!$_canChangeQty) echo ' disabled="disabled"' ?> id="bundle-option-<?php echo $_option->getId() ?>-qty-input" class="input-text qty<?php if (!$_canChangeQty) echo ' qty-disabled' ?>" type="text" name="bundle_option_qty[<?php echo $productId ?>][<?php echo $_option->getId() ?>]" value="<?php echo $_defaultQty ?>"/>
    </span>
</dd>


