<?php
/** @var Ced_SocialLogin_Block_Facebook_Button $this */
$url = $this->escapeUrl($this->_getButtonUrl());
$customerHelper = Mage::helper("zolagocustomer");
?>
<?php if($this->isLogged()): ?>
	<?php $redirect = $this->getClient()->getRedirectUri(); ?>
	<a onclick="Mall.socialLogin('<?php echo $url ?>','<?php echo $redirect ?>');">
    <?php //echo $this->_getButtonText(); ?>
		<?php /* <div class="ced-sociallogin-facebook-inner <?php echo $this->_getButtonClass(); ?>"></div> */ ?>
		<div class="button btn-social fb small"><?php echo $customerHelper->__("Login"); ?></div>
    </a>
<?php else: ?>
	<a href="<?php echo $url ?>">
		<?php //echo $this->_getButtonText(); ?>
		<?php /* <div class="ced-sociallogin-facebook-inner <?php echo $this->_getButtonClass(); ?>"></div> */ ?>
		<div class="button btn-social fb small"><?php echo Mage::helper('customer')->__("Log Out"); ?></div>
	</a>
<?php endif; ?>