<div id="content" class="container-fluid">
	<div id="logIn" class="row">
		<div id="content-main" class="">
			<div class="col-sm-12 column-block">
				<div class="main bg-w equalBlock col-01">
					<form action="<?php echo $this->getUrl("*/*/forgetSave");?>" method="post" class="form-horizontal" >
						<?php echo $this->getChildHtml("persistent.forget.formkey");?>
						<section class="section clearfix">
							<header class="title-section">
								<h2><?php echo $this->__("Remove my products from this device");?></h2>
							</header>
							<div>
								<?php echo $this->getChildHtml("persistent.forget.guest");?>
							</div>
							<button type="submit" name="send" class="button button-primary large link pull-right" style="width:auto"><?php echo $this->__("Remove my data")?></button>
						</section>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>