<form id="search_mini_form" action="<?php echo $this->helper('solrsearch')->getResultUrl() ?>" method="get">
    <div class="form-search">
        <label for="search"><?php echo $this->__('Search') ?>:</label>
        <input id="search" type="text" name="<?php echo $this->helper('catalogsearch')->getQueryParamName() ?>" value="<?php echo trim(trim($this->helper('catalogsearch')->getEscapedQueryText(),'"')) ?>" class="input-text" />
        <button type="submit" title="<?php echo $this->__('Search') ?>" class="button"><span><span><?php echo $this->__('Search') ?></span></span></button>
        <div id="search_autocomplete" class="search-autocomplete"></div>
        <script type="text/javascript">
        //<![CDATA[
            var searchForm = new Varien.searchForm('search_mini_form', 'search', '<?php echo $this->__('Search entire store here...') ?>');
        //]]>
        </script>
        <script type="text/javascript">
        //<![CDATA[
            var Manager;
			Manager = new AjaxSolr.Manager({solrUrl: '<?php echo $this->helper('solrsearch')->getAjaxQueryUrl();?>?r='});
            Manager.addWidget(new AjaxSolr.AutocompleteWidget(<?php echo $this->helper('solrsearch')->getAutocompleteConfig('search', 'search_mini_form')?>));			
			Manager.init();
        //]]>
        </script>
    </div>
</form>