<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2016 Amasty (https://www.amasty.com)
 * @package Magpleasure_Blog
 */

/** @var Magpleasure_Blog_Model_Mysql4_Category_Collection $collection  */
/** @var Magpleasure_Blog_Block_Sidebar_Category $this  */
$collection = $this->getCollection();
?>
<?php if ($this->getDisplay() && count($collection)): ?>
<div class="block mpblog-categories">
    <h3 class="open"><span><?php echo $this->getBlockHeader(); ?></span></h3>
    <div class="block-content content">
        <dd class="mplog-categories">
        <?php foreach ($collection as $category): ?>
            <dl class="mpblog-category<?php if ($category->getIsActive()): ?> active<?php endif; ?> mpblog-category-<?php echo $category->getId(); ?>">
                <a href="<?php echo $category->getCategoryUrl(); ?>"><?php echo $this->escapeHtml($category->getName()); ?></a>
            </dl>
        <?php endforeach; ?>
        </dd>
    </div>
</div>
<?php endif; ?>
