<div class="content-header">
   <h3><?php echo $this->getHeaderText() ?></h3>
   <p class="content-buttons form-buttons">
        <?php echo $this->getButtonsHtml(); ?>
    </p>
</div>
<form action="<?php echo $this->getForm()->getAction() ?>" method="post" id="mapper_edit_form">
    <?php echo $this->getBlockHtml('formkey')?>
    <div class="no-display">
        <input type="hidden" id="change_flag_element" name="_change_type_flag" value="" />
    </div>
	<div class="grid">
		<table class="data" cellspacing="0">
			<thead>
				<tr class="headings">
					<th class="no-link"><span class="nobr">Attr</span></th>
					<th class="no-link"><span class="nobr">Sortorder</span></th>
					<th class="no-link"><span class="nobr">Options</span></th>
					<th class="no-link"><span class="nobr">Renderer</span></th>
					<th class="no-link"><span class="nobr">Depends</span></th>
					<th class="no-link"><span class="nobr">Lonley</span></th>
					<th class="no-link a-right"><span class="nobr">Remove</span></th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<td class="a-left">
						content
					</td>
					<td class="a-left">
						content
					</td>
					<td class="a-left">
						content
					</td>
					<td class="a-left">
						<?php echo $this->getRenderSelectHtml("render_1");?>
					</td>
					<td class="a-left">
						content
					</td>
					<td class="a-left">
						content
					</td>
					<td class="a-right">
						rm button
					</td>
				</tr>
			</tbody>
		</table>
	</div>
	<div class="a-right">
		<?php echo $this->getAttributesSelectHtml("test_id");?>
		<?php echo $this->getAddButtonHtml("test2_id");?>
	</div>
</form>