<?php
/** @var Mage_Checkout_Block_Onepage_Success $this */
/** @var Zolago_Checkout_Helper_Data $helper */
$helper = Mage::helper("zolagocheckout");
?>

<div id="content" class="container-fluid">
    <div id="checkout" class="row checkout-success">
        <aside class="col-md-10 col-md-push-1 col-sm-12 section helpful-vote">
            <div class="main bg-w">
                <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('checkout-thank-you-page')->toHtml(); ?>
                <h4 class="open number_order"><?php echo $helper->__('YOUR ORDER NUMBER: ') ?><?php echo $this->escapeHtml($this->getOrderId()) ?></span></h4>
                <p class="see-this-order"><a href="<?php echo Mage::getUrl("sales/order/process");?>"><?php echo $helper->__("SEE THIS ORDER IN YOUR ACCOUNT >"); ?></a></p>
            </div>
        </aside>
    </div>
</div>

