<div id="content" class="container-fluid">
	<div id="checkout" class="row">
		<div class="step step-0 hidden" id="step-0">
			<?php echo $this->getChildHtml("checkout.onepage.guest.address");?>
		</div>
		<div class="step step-1 hidden" id="step-1">
            <?php echo $this->getChildHtml("checkout.onepage.guest.shippingpayment");?>
		</div>
		<div class="step step-2 hidden" id="step-2">
			<?php echo $this->getChildHtml("checkout.onepage.guest.review");?>
		</div>
	</div>
</div>

<script type="text/javascript">
	(function(){
		var checkout = new Mall.CheckoutGuest();
		
		checkout.setProgressObject(jQuery("#step ol"));
		checkout.set("placeUrl", '<?php echo $this->getPlaceUrl();?>');
		checkout.addStep(Mall.Checkout.steps.address);
		checkout.addStep(Mall.Checkout.steps.shippingpayment);
		checkout.addStep(Mall.Checkout.steps.review);
		
		checkout.init(0);
	})();
</script>