<?php
/* @var $this Zolago_Modago_Block_Checkout_Onepage_Abstract */
$_customer = $this->getCustomer();
$_quoteBilling = $this->getQuote()->getBillingAddress();
$_quoteShipping = $this->getQuote()->getShippingAddress();
/** @var Zolago_Checkout_Helper_Data $_helper */
$_helper = Mage::helper("zolagocheckout");
$basketDataLayer = $_helper->getBasketDataLayer();
?>
<?php if (!empty($basketDataLayer)): ?>
	<script>
		if (typeof dataLayer != "undefined") {
			dataLayer.push(<?php echo json_encode($basketDataLayer); ?>);
		}
	</script>
<?php endif; ?>
<div id="content" class="container-fluid">
	<div id="checkout" class="row">
		<div class="step step-0 hidden" id="step-0">
			<?php if($this->customerHasAddresses()):?>
			<?php echo $this->getChildHtml("checkout.onepage.logged.addressbook");?>
			<?php else:?>
			<?php echo $this->getChildHtml("checkout.onepage.logged.address");?>
			<?php endif?>
		</div>
		<div class="step step-1 hidden" id="step-1">
            <?php echo $this->getChildHtml("checkout.onepage.logged.shippingpayment");?>
		</div>
		<div class="step step-2 hidden" id="step-2">
			<?php echo $this->getChildHtml("checkout.onepage.logged.review");?>
		</div>
	</div>
</div>

<script type="text/javascript">
	Mall.translate.add("no-addresses", "<?php echo $_helper->__("No addresses");?>");
	Mall.translate.add("edit-address", "<?php echo $_helper->__("Edit address");?>");
	Mall.translate.add("add-new-address", "<?php echo $_helper->__("Add new address");?>");
	Mall.translate.add("save", "<?php echo $_helper->__("Save");?>");
	Mall.translate.add("firstname", "<?php echo $_helper->__("Firstname");?>");
	Mall.translate.add("lastname", "<?php echo $_helper->__("Lastname");?>");
	Mall.translate.add("company-name", "<?php echo $_helper->__("Company name");?>");
	Mall.translate.add("optional", "<?php echo $_helper->__("optional");?>");
	Mall.translate.add("nip", "<?php echo $_helper->__("NIP");?>");
	Mall.translate.add("street-and-number", "<?php echo $_helper->__("Street and number");?>");
	Mall.translate.add("postcode", "<?php echo $_helper->__("Postcode");?>");
	Mall.translate.add("city", "<?php echo $_helper->__("City");?>");
	Mall.translate.add("phone", "<?php echo $_helper->__("Phone");?>");
	Mall.translate.add("country", "<?php echo $_helper->__("Country");?>");
	Mall.translate.add("address-cant-be-removed", "<?php echo $_helper->__("Address can't be removed.");?>");
	Mall.translate.add("emailbackend-exits-log-in", "<?php echo $_helper->__("Email already exists. Please log in.");?>");
	Mall.translate.add("please-select-payment", "<?php echo $_helper->__("Please select payment");?>");
	Mall.translate.add("please-select-shipping", "<?php echo $_helper->__("Please select shipping");?>");
	Mall.translate.add("selected-shipping-address", "<?php echo $_helper->__("Selected shipping address");?>");
	Mall.translate.add("selected-billing-address", "<?php echo $_helper->__("Selected billing address");?>");
	Mall.translate.add("change-address", "<?php echo $_helper->__("Change address");?>");
	Mall.translate.add("your-additional-addresses", "<?php echo $_helper->__("Your additional addresses");?>");
	Mall.translate.add("roll-up", "<?php echo $_helper->__("Roll up");?>");
    Mall.translate.add("warning-wrong-zip", "<?php echo $this->__("Kod został wprowadzony poprawnie, ale nie znaleźliśmy takiego kodu w bazie adresowej. Sprawdź proszę jeszcze poprawność kodu pocztowego.");?>");


    Mall.translate.add("Invalid zip-code. Zip-code should include 5 numbers in XX-XXX format.", "<?php echo $this->__("Invalid zip-code. Zip-code should include 5 numbers in XX-XXX format."); ?>");
    Mall.translate.add("Telephone number is too short. Number must contain 9 digits, without spacing.", "<?php echo $this->__("Telephone number is too short. Number must contain 9 digits, without spacing."); ?>");
    Mall.translate.add("email", "<?php echo $this->__('Valid email is required.') ?>");
    Mall.translate.add("Password needs to have at least %s characters", "<?php echo $this->__("Password needs to have at least %s characters", Mage::helper("zolagocustomer")->getPasswordMinLength()); ?>");
    Mall.translate.add("Zip code should be entered in the format xx-xxx.", "<?php echo $this->__("Zip code should be entered in the format xx-xxx."); ?>");
    Mall.translate.add("required", "<?php echo $this->__("This is a required field."); ?>");
    Mall.translate.add("email", "<?php echo $this->__("E-mail address is in invalid format or contains invalid characters. Please enter correct address."); ?>");
    Mall.translate.add("Tax number is incorrect. Enter as a string of digits e.g. 1234567890.", "<?php echo $this->__('Tax number is incorrect. Enter as a string of digits e.g. 1234567890.') ?>");

    Mall.translate.add("Enter name.", "<?php echo $this->__('Enter name.') ?>");
    Mall.translate.add("Enter last name.", "<?php echo $this->__('Enter last name.') ?>");
    Mall.translate.add("Enter email address.", "<?php echo $this->__('Enter email address.') ?>");
    Mall.translate.add("Enter street and number.", "<?php echo $this->__('Enter street and number.') ?>");
    Mall.translate.add("Enter company name.", "<?php echo $this->__('Enter company name.') ?>");
    Mall.translate.add("Enter city name.", "<?php echo $this->__('Enter city name.') ?>");
    Mall.translate.add("Zip-code should be entered in the format xx-xxx.", "<?php echo $this->__('Zip-code should be entered in the format xx-xxx.') ?>");
    Mall.translate.add("Phone number we need only to contact concerning orders for example courier delivering the shipment.", "<?php echo $this->__('Phone number we need only to contact concerning orders for example courier delivering the shipment.') ?>");
    Mall.translate.add("Pho.", "<?php echo $this->__('Pho.') ?>");
    Mall.translate.add("Invoice", "<?php echo $this->__('Invoice') ?>");
    Mall.translate.add("VAT Id", "<?php echo $this->__('VAT Id') ?>");
    Mall.translate.add("Delivery address", "<?php echo $this->__('Delivery address') ?>");
	Mall.translate.add("Enter tax number","<?php echo $this->__("Enter tax number") ?>");




</script>
<script type="text/javascript">
	(function(){
		
		var checkout = new Mall.CheckoutLogged();
		
		checkout.setProgressObject(jQuery("#step ol"));
		checkout.set("placeUrl", '<?php echo $this->getPlaceUrl();?>');
		
		<?php if($this->customerHasAddresses()):?>
		var addressBook = new Mall.customer.AddressBook();
		
		addressBook.setAddressBook(<?php echo $this->getCustomerAddressesJson(); ?>);
		addressBook.setDefaultShipping(<?php echo $this->asJson($_customer->getDefaultShipping())?>);
		addressBook.setDefaultBilling(<?php echo $this->asJson($_customer->getDefaultBilling())?>);
		addressBook.setSelectedShipping(<?php echo $this->asJson($_quoteShipping->getCustomerAddressId())?>);
		addressBook.setSelectedBilling(<?php echo $this->asJson($_quoteBilling->getCustomerAddressId())?>);
                addressBook.setAvailableCountry(<?php echo $this->getAvailableCountryJson(); ?>);			
		Mall.Checkout.steps.addressbook.setAddressBook(addressBook);
			
		checkout.addStep(Mall.Checkout.steps.addressbook);
		<?php else:?>
		checkout.addStep(Mall.Checkout.steps.address);
		<?php endif?>
		checkout.addStep(Mall.Checkout.steps.shippingpayment);
		checkout.addStep(Mall.Checkout.steps.review);
		checkout.init(0);
	
		Mall.reg.set("checkout", checkout);

        //visual fix for hints
        initFixHints = function() {
            jQuery('input[type=text],input[type=email],input[type=password],textarea').not('.phone, .zipcode, .nip').tooltip({
                placement: function (a, element) {
                    var isModal= jQuery(element).parents('.modal-body').length;
                    var viewport = window.innerWidth;
                    var placement = "right";
                    if (!isModal) { //is not modal window
                        if (viewport < 470) {
                            placement = "top";
                        }
                    } else {//is modal window
                        if (viewport < 991) {
                            placement = "top";
                        }
                        if (viewport < 768) {
                            placement = "right";
                        }
                        if (viewport < 600) {
                            placement = "top";
                        }
                    }

                    return placement;
                },
                trigger: "focus"
            });

            jQuery('.phone, .zipcode, .nip').tooltip({
                placement: "right",
                trigger: "focus"
            });

            jQuery('input[type=text],input[type=email],input[type=password],textarea ').off('shown.bs.tooltip').on('shown.bs.tooltip', function () {
                if(jQuery(this).parent(':has(i)').length && jQuery(this).parent().find('i').is(":visible")) {
                    jQuery(this).next('div.tooltip.right').animate({left: "+=25"}, 100, function () {
                    });
                }
            });

        };
        initFixHints();

        var timer = window.setTimeout(function() {}, 0);
        jQuery(window).on('resize', function() {
            window.clearTimeout(timer);
            timer = window.setTimeout(function() {
                jQuery(window).trigger('resizeend');
            }, 250);
        });

        jQuery(window).on('resizeend', function() {
            var actualElem = jQuery('input[type=text],input[type=email],input[type=password],textarea ').next('div.tooltip').prev();
            jQuery('input[type=text],input[type=email],input[type=password],textarea ').tooltip('destroy');//because on resize arrow don't work correctly
            initFixHints();
            actualElem.tooltip('show');
        });
        //end visual fix for hints
		
	})();
</script>