<?php /* @var $this Zolago_Modago_Block_Checkout_Onepage_Abstract */ ?>
<?php $_customer = $this->getCustomer();?>
<div id="content" class="container-fluid">
	<div id="checkout" class="row">
		<div class="step step-0 hidden" id="step-0">
			<?php if($this->customerHasAddresses()):?>
			<?php echo $this->getChildHtml("checkout.onepage.logged.addressbook");?>
			<?php else:?>
			<?php echo $this->getChildHtml("checkout.onepage.logged.address");?>
			<?php endif?>
		</div>
		<div class="step step-1 hidden" id="step-1">
            <?php echo $this->getChildHtml("checkout.onepage.logged.shippingpayment");?>
		</div>
		<div class="step step-2 hidden" id="step-2">
			<?php echo $this->getChildHtml("checkout.onepage.logged.review");?>
		</div>
	</div>
</div>

<script type="text/javascript">
	(function(){
		var checkout = new Mall.CheckoutLogged();
		
		checkout.setProgressObject(jQuery("#step ol"));
		checkout.set("placeUrl", '<?php echo $this->getPlaceUrl();?>');
		
		<?php if($this->customerHasAddresses()):?>
		var addressBook = new Mall.customer.AddressBook();
		
		addressBook.setAddressBook(<?php echo $this->getCustomerAddressesJson(); ?>);
		addressBook.setDefaultShipping(<?php echo $this->asJson($_customer->getDefaultShipping())?>);
		addressBook.setDefaultBilling(<?php echo $this->asJson($_customer->getDefaultBilling())?>);
		addressBook.setSelectedShipping(<?php echo $this->asJson($this->getQuote()->getShippingAddress()->getCustomerAddressId())?>);
		addressBook.setSelectedBilling(<?php echo $this->asJson($this->getQuote()->getBillingAddress()->getCustomerAddressId())?>);
			
		Mall.Checkout.steps.addressbook.setAddressBook(addressBook);
			
		checkout.addStep(Mall.Checkout.steps.addressbook);
		<?php else:?>
		checkout.addStep(Mall.Checkout.steps.address);
		<?php endif?>
		checkout.addStep(Mall.Checkout.steps.shippingpayment);
		checkout.addStep(Mall.Checkout.steps.review);
		
		checkout.init(0);
	})();
</script>