<?php $_hlp = Mage::helper("zolagocheckout");?>
<div class="content-step">
	<div id="step">
		<ol class="step_01 step_02"><!-- Actywny [current-checkout] , Punkt Zrealizowany  [current-checkout executed] -->
			<li id="step_01" class="current-checkout executed">
				<span><span><?php echo $_hlp->__("Cart");?></span></span>
			</li>
			<li id="step_02" class="current-checkout">
				<span><span><?php echo $_hlp->__("Shipping data");?></span></span>
			</li>
			<li id="step_03">
				<span><span><?php echo $_hlp->__("Delivery and payment");?></span></span>
			</li>
			<li id="step_04">
				<span><span><?php echo $_hlp->__("Summary");?></span></span>
			</li>
		</ol>
	</div>
</div>