<?php
/**
 * Author: Paweł Chyl <pawel.chyl@orba.pl>
 * Date: 08.09.2014
 */

?>

<div id="content" class="container-fluid">
<div id="checkout" class="row">
<div class="sidebar-secound col-lg-3 col-md-4 col-sm-12 col-xs-12 col-lg-push-9 col-md-push-8">
    <section class="p main bg-w hidden-sm hidden-xs">
        <header>
            <h2 class="open">Blok CMS</h2>
        </header>
        <div class="clearfix border-top">
            <ul>
                <li>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</li>
                <li>Pellentesque ultrices lectus ut felis tempor, eget rutrum nulla sodales.</li>
                <li>Nullam vel nunc eu enim hendrerit hendrerit eget non leo.</li>
                <li>Quisque sit amet diam elementum, aliquet risus non, dignissim tortor.</li>
            </ul>
            <figure>
                <img src="/skin/frontend/modago/default/images/home_main_callout.jpg" alt="">
            </figure>
        </div>
        <div class="clearfix border-top">
            <ol>
                <li>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</li>
                <li>Pellentesque oltrices lectus ut felis tempor, eget rutrum nulla sodales.</li>
                <li>Nullam vel nunc eu enim hendrerit hendrerit eget non leo.</li>
                <li>Quisque sit amet diam elementum, aliquet risus non, dignissim tortor.</li>
                </ol>
        </div>
        <div class="clearfix border-top">
            <dl>
                <dt>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</dt>
                <dd class="separator">Pellentesque ultrices lectus ut fedds tempor, eget rutrum nulla sodales.</dd>
                <dd>Nullam vel nunc eu enim hendrerit hendrerit eget non leo.</dd>
                <dd class="separator">Quisque sit amet diam elementum, addquet risus non, dignissim tortor.</dd>
            </dl>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.Pellentesque ultrices lectus ut fedds tempor,
                eget rutrum nulla sodales.</p>
            <figure>
                <img src="/skin/frontend/modago/default/images/home_main_callout.jpg" alt="">
            </figure>

        </div>
    </section>
</div>
<div id="content-main" class="col-lg-9 col-md-8 col-sm-12 col-xs-12 col-lg-pull-3 col-md-pull-4 section">
<section class="main bg-w">
<header class="title-section">
    <h2>Podaj dane do realizacji</h2>
</header>
<form action="" class="form">
<fieldset>
    <legend class="first">Dane osoby zamawiającej:</legend>

    <div class="form-group clearfix">
        <div class="row">
            <label class="col-sm-3" for="for_first_name">Imię</label>

            <div class="col-sm-5">
                <input type="text" class="form-control firstName hint" id="for_first_name" title="Wprowadź imię"
                       name="firstname" data-rule-required="true">
            </div>
        </div>

    </div>
    <div class="form-group clearfix border-top">
        <div class="row">
            <label class="col-sm-3" for="for_last_name" class="hidden">Nazwisko</label>

            <div class="col-sm-5">
                <input type="text" class="form-control lastName hint" id="for_last_name" title="Wprowadź nazwisko"
                       name="lastname" data-rule-required="true">
            </div>
        </div>
    </div>
    <div class="form-group clearfix border-top">
        <div class="row">
            <label class="col-sm-3" for="email" class="hidden">Adres e-mail</label>

            <div class="col-sm-5">
                <input type="email" class="form-control email hint" id="email" title="Adres e-mail" name="email">
            </div>
        </div>
    </div>
    <div class="form-group clearfix border-top">
        <div class="row">
            <label class="col-sm-3" for="phone_number" class="hidden">Numer telefonu</label>

            <div class="col-sm-5">
                <input type="text" class="form-control phone hint" id="phone_number"
                       title="Numer telefonu potrzebujemy tylko do kontaktu dotyczącego zamówienia np. dla kuriera dostarczającego przesyłkę."
                       name="phone_number">
            </div>
        </div>
    </div>
</fieldset>

<fieldset>
    <legend>Dane do wysyłki:</legend>
    <div class="form-group form-checkbox small">
        <input type="checkbox" name="rodzaj" id="orders_someone_else" class="css-checkbox orders_someone_else">
        <label for="orders_someone_else" class="css-label orders_someone_else">Zamawiam dla kogoś innego - chcę podać
            inne dane kontaktowe odbiorcy</label>
    </div>

    <div class="form-group clearfix hidden border-top orders_someone_else">
        <div class="form-group clearfix">
            <div class="row">
                <label class="col-sm-3" for="for_first_name">Imię</label>

                <div class="col-sm-5"><input type="text" class="form-control firstName hint" id="for_first_name"
                                             title="Wprowadź imię" name="firstname"></div>
            </div>

        </div>
        <div class="form-group clearfix border-top">
            <div class="row">
                <label class="col-sm-3" for="for_last_name" class="hidden">Nazwisko</label>

                <div class="col-sm-5">
                    <input type="text" class="form-control lastName hint" id="for_last_name" title="Wprowadź nazwisko"
                           name="lastname">
                </div>
            </div>
        </div>
    </div>

    <div class="form-group clearfix border-top hidden orders_someone_else">
        <div class="row">
            <label class="col-sm-3" for="phone_number" class="hidden">Numer telefonu</label>

            <div class="col-sm-5">
                <input type="text" class="form-control" id="phone_number"
                       title="Numer telefonu potrzebujemy tylko do kontaktu dotyczącego zamówienia np. dla kuriera dostarczającego przesyłkę.">
            </div>
        </div>
    </div>

    <div class="form-group border-top clearfix">
        <div class="row">
            <label class="col-sm-3" for="street" class="hidden">Ulica i numer</label>

            <div class="col-lg-7 col-md-5 col-sm-5">
                <input type="text" class="form-control street" id="street" title="Ulica i numer" name="street">
            </div>
        </div>
    </div>

    <div class="form-group clearfix border-top">
        <div class="row">
            <label class="col-sm-3" for="zip_code" class="hidden">Kod pocztowy</label>

            <div class="col-sm-5">
                <input type="text" class="form-control zipcode" id="zip_code" title="Kod pocztowy" name="zipcode">
            </div>
        </div>
    </div>

    <div class="form-group clearfix border-top">
        <div class="row">
            <label class="col-sm-3" for="city" class="hidden">Miejscowość</label>

            <div class="col-sm-5">
                <input type="text" class="form-control city hint" id="city" title="Miejscowość" name="city">
            </div>
        </div>
    </div>

    <div class="form-group clearfix border-top">
        <div class="row">
            <label class="col-sm-3 double-line" for="firm_name" class="hidden">Nazwa firmy<br>(opcjonalnie)</label>

            <div class="col-lg-7 col-md-5 col-sm-5">
                <input type="text" class="form-control firm hint" id="firm_name" title="Nazwa firmy" name="firm_name">
            </div>
        </div>
    </div>
</fieldset>
<fieldset>
    <legend>Dokument sprzedaży:</legend>
    <div class="form-group form-checkbox small">
        <input type="checkbox" name="invoice_vat" id="invoice_vat" class="css-checkbox invoice_vat">
        <label for="invoice_vat" class="css-label">Chcę otrzymać fakturę VAT</label>
    </div>
</fieldset>

<fieldset id="invoice_data">

    <div class="form-group form-checkbox small">
        <input type="checkbox" name="invoice_data_address" id="invoice_data_address"
               class="css-checkbox invoice_data_address" checked>
        <label for="invoice_data_address" class="css-label">Adres taki sam jak adres wysyłki</label>
    </div>

    <div class="form-group clearfix border-top">
        <div class="row">
            <label class="col-sm-3" for="invoice_data_firm_name" class="hidden">Nazwa firmy</label>

            <div class="col-lg-7 col-md-5 col-sm-5">
                <input type="text" class="form-control firm hint" id="invoice_data_firm_name" title="Nazwa firmy"
                       name="invoice_data_firm_name">
            </div>
        </div>
    </div>

    <div class="form-group clearfix border-top">
        <div class="row">
            <label class="col-sm-3" for="invoice_data_nip" class="hidden">NIP</label>

            <div class="col-lg-3 col-md-5 col-sm-5">
                <input type="text" class="form-control nip hint" id="invoice_data_nip" title="NIP">
            </div>
        </div>
    </div>

    <div class="form-group border-top clearfix">
        <div class="row">
            <label class="col-sm-3" for="invoice_data_street" class="hidden">Ulica i numer</label>

            <div class="col-lg-7 col-md-5 col-sm-5">
                <input type="text" class="form-control street" id="invoice_data_street" title="Ulica i numer"
                       name="invoice_data_street">
            </div>
        </div>
    </div>

    <div class="form-group clearfix border-top">
        <div class="row">
            <label class="col-sm-3" for="invoice_data_zip_code" class="hidden">Kod pocztowy</label>

            <div class="col-sm-5">
                <input type="text" class="form-control zipcode" id="invoice_data_zip_code" title="Kod pocztowy"
                       name="invoice_data_zip_code">
            </div>
        </div>
    </div>

    <div class="form-group clearfix border-top">
        <div class="row">
            <label class="col-sm-3" for="invoice_data_city" class="hidden">Miejscowość</label>

            <div class="col-sm-5">
                <input type="text" class="form-control city hint" id="invoice_data_city" title="Miejscowość"
                       name="invoice_data_city">
            </div>
        </div>
    </div>

</fieldset>

<fieldset id="remember_data">
    <legend>Zapamiętaj dane (opcjonalnie):</legend>
    <div class="row">
        <div class="col-sm-12">
            <div class="row">
                <div class="col-sm-6">

                    <p>Ustaw hasło by łatwiej śledzić stan realizacji zamówień i szybciej kupować następnym razem.</p>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div id="add_pass" class="col-sm-6">

            <div class="form-group clearfix">
                <div class="row">
                    <label class="col-sm-6" for="pass" class="hidden">Hasło</label>

                    <div class="col-sm-6">
                        <input type="password" class="form-control password" id="pass"
                               title="Hasło musi mieć przynajmniej 6 znaków, nie może zawierać spacji.">
                    </div>
                </div>
            </div>


        </div>
        <div class="col-sm-1 hidden-xs">
            Lub
        </div>
        <div id="login_social" class="col-sm-5">
            <p>Nie chcesz podawać hasła? Nie musisz:</p>
            <a href="#" class="button btn-social g-plus small">Zaloguj się</a>
            <a href="#" class="button btn-social fb small">Zaloguj się</a>
        </div>
    </div>
</fieldset>
<div class="row">
    <div class="form-group form-checkbox small text-align-left">
        <input type="checkbox" id="agree" class="css-checkbox invoice_vat" name="agree" required>
        <label for="agree" class="css-label">Wyrażam zgodę na przetwarzanie moich danych osobowych przez Zolago Group
            Sp. Z o.o. z siedzib w Warszawie (Barkocińska 6 03-534), w celu świadczenia przez ni usług w ramach
            Modago.pl</label>
    </div>

    <div class="form-group form-checkbox small text-align-left">
        <input type="checkbox" id="declare" class="css-checkbox invoice_vat" name="declare" required>
        <label for="declare" class="css-label">Oświadczam, że zapoznałem(am) się z Regulaminem sklepu Modago.pl i
            akceptuję jego postanowienia.</label>
    </div>
</div>
<div class="row action">
    <div class="col-sm-6">
        <a id="back" class="button button-third large pull-left">Wróć</a>
    </div>
    <div class="col-sm-6">
        <button class="button button-primary large link pull-right">Dalej</button>
    </div>
</div>


</form>
</section>

</div>

</div>
</div>