<?php /* @var $this Zolago_Modago_Block_Map */ ?>
<?php $map = $this->getMapData(); ?>

<?php $_helper = Mage::helper("zolagomodago"); ?>

<script type="text/javascript" src="//maps.google.com/maps/api/js?sensor=FALSE"></script>
<script type="text/javascript">var data = '<?php echo $map; ?>';</script>
<script type="text/javascript" src="<?php echo Mage::getBaseUrl(); ?>js/gh/storemap/storefinder.js"></script>

<style type="text/css">
    #map-container {
        padding: 6px;
        border: 1px solid #ccc;
        -webkit-box-shadow: rgba(64, 64, 64, 0.5) 0 2px 5px;
        -moz-box-shadow: rgba(64, 64, 64, 0.5) 0 2px 5px;
        box-shadow: rgba(64, 64, 64, 0.1) 0 2px 5px;
    }

    #map {
        width: 100%;
        height: 450px;
    }

    #inline-actions {
        padding-top: 10px;
    }

    .item {
        margin-left: 20px;
    }

    .marker-window {
        max-width: 170px;
        text-align: center;
    }

    .info_window_text .iw_header {
        width: 100%;
        margin: 0;
        line-height: 1.2;
        text-transform: capitalize;
    }

    .info_window_text .iw_header .shop_name {
        display: block;
        text-transform: capitalize;
        font-style: normal;
        margin: 6px 0;
    }

    .search-by-map input[type=text] {
        /*float: left;*/
        /*width: 75%;*/
        margin-right: 5px;
        margin-bottom: 10px;
        border: 1px solid #787878;
        padding: 0 10px;
    }
    .search-by-map .button.button-primary {
        padding: 7px 15px;

    }
</style>

<div id="content" class="container-fluid bg-w">
    <div class="row">
        <div class="col-sm-12">
            <div id="content-main">
                <div class="my-account">

                    <div class="container-fluid">
                        <div class="col-md-12">
                            <div class="container-fluid">
                                <div class="col-md-8" id="#map-container">
                                    <div id="map"></div>
                                </div>
                                <div class="col-md-4">
                                    <div class="col-md-12">
                                        <div class="search-by-map col-md-12">
                                            <div class="form-group">
                                                <form id="search_by_map_form" action="<?php echo Mage::getUrl("modago/map/getMapData")?>">
                                                    <input type="text" class="form-control" name="search_by_map" placeholder="<?php echo $_helper->__("Enter city or zip"); ?>" value="">
                                                    <button class="button button-primary button-search pull-right"
                                                            onclick="searchOnMap();return false;">
                                                        <?php echo $_helper->__("Search"); ?>
                                                    </button>
                                                </form>
                                            </div>
                                        </div>
                                        <div class="search-by-map-list col-md-12">


                                        </div>
                                    </div>
                                    <div id="inline-actions" class="hidden">
                                        <a href="#" id="clear">Clear</a>
                                    </div>
                                </div>

                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>
