<?php /* @var $this Zolago_Modago_Block_Map */ ?>
<?php $map = $this->getMapData(); ?>

<?php $_helper = Mage::helper("zolagomodago"); ?>

<script type="text/javascript" src="//maps.google.com/maps/api/js?sensor=FALSE"></script>
<script type="text/javascript">
    var data = '<?php echo $map; ?>';
    var clickToSeeMore = '<?php echo $_helper->__("Click the name to see more info")?>';
</script>
<script type="text/javascript" src="<?php echo Mage::getBaseUrl(); ?>js/gh/storemap/storefinder.js"></script>

<style type="text/css">
    #map-container {
        padding: 0 10px;
        border: 1px solid #ccc;
        -webkit-box-shadow: rgba(64, 64, 64, 0.5) 0 2px 5px;
        -moz-box-shadow: rgba(64, 64, 64, 0.5) 0 2px 5px;
        box-shadow: rgba(64, 64, 64, 0.1) 0 2px 5px;
    }

    #map {
        width: 100%;
        height: 450px;
    }

    @media (max-width: 768px) {
        #map {
            width: 85%;
            height: 200px;
            margin: 10px auto;
        }
    }
    #inline-actions {
        padding-top: 10px;
    }

    .item {
        margin-left: 20px;
    }

    .marker-window {
        max-width: 170px;
        /*text-align: center;*/
    }

    .info_window_text .iw_header {
        width: 100%;
        margin: 0;
        line-height: 1.2;
        text-transform: capitalize;
    }

    .info_window_text .iw_header .shop_name {
        display: block;
        text-transform: capitalize;
        font-style: normal;
        margin: 6px 0;
    }

    .search-by-map input[type=text] {
        margin-right: 5px;
        margin-bottom: 10px;
        border: 1px solid #787878;
        padding: 0 10px;
        color: #000000;
    }

    .search-by-map .button.button-primary {
        padding: 7px 15px;

    }

    .search-by-map-list {
        max-height: 335px;
        overflow-y: auto;
    }

    .search-by-map-list ul {
        list-style-image: url("http://chart.apis.google.com/chart?cht=mm&chs=15x15&chco=ffffff,000000,000000&ext=.png");
        padding-left: 5px;
    }
    .search-by-map-list ul li{
        padding: 5px 7px;
    }
    .search-by-map-list ul li:hover {
        background-color: #EBEBEB;
    }

    .search-by-map h4 {
        padding-left: 10px;
        padding-top: 2px;
        padding-bottom: 10px;
        font-weight: bold;
        font-family: Roboto, sans-serif;
        display: block;
        overflow: hidden;
        font-size: 15px;
        text-transform: uppercase;
    }

    .search-by-map h4:before {
        content: ' ';
        display: block;
        width: 18px;
        height: 18px;
        background: #CD0027;
        position: absolute;
        left: 0px;
        top: 0px;
    }

    #search_by_map_form label.error {
        padding: 0 !important;
    }

    #search_by_map_form input.error {
        padding-top: 0 !important;
    }

    .no-padding {
        padding: 0;
    }
</style>

<div id="content" class="container-fluid bg-w">
    <div class="row">
        <div class="col-sm-12">
            <div id="content-main">
                <div class="my-account">

                    <div class="container-fluid no-padding">
                        <div class="col-md-12 no-padding">
                                <div class="col-md-8" id="#map-container">
                                    <div id="map"></div>
                                </div>
                                <div class="col-md-4 no-padding">
                                    <div class="col-md-12 no-padding">
                                        <div class="search-by-map col-md-12">
                                            <h4><?php echo $_helper->__("Find your store") ?></h4>

                                            <div class="form-group">
                                                <form id="search_by_map_form"
                                                      action="<?php echo Mage::getUrl("modago/map/getMapData") ?>">
                                                    <input type="text" class="form-control" name="search_by_map"
                                                           autocomplete="off"
                                                           required
                                                           placeholder="<?php echo $_helper->__("Enter city or zip"); ?>"
                                                           value="">
                                                    <button class="button button-primary button-search pull-right"
                                                            type="submit"
                                                        >
                                                        <?php echo $_helper->__("Search"); ?>
                                                    </button>
                                                </form>
                                            </div>
                                            <div class="form-group">
                                                <a href="" onclick="clearSearchOnMap();return false;">
                                                    <?php echo $_helper->__("Show all stores"); ?>
                                                </a>
                                            </div>
                                        </div>
                                        <div class="search-by-map-list col-md-12"></div>
                                    </div>
                                </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    jQuery(document).ready(function () {
        jQuery("#search_by_map_form").validate({
            rules: {
                search_by_map: {
                    required: true,
                    minlength: 3
                }
            },
            messages: {
                search_by_map: {
                    required: '<?php echo Mage::helper("zolagocommon")->__("This field is required."); ?>',
                    minlength: '<?php echo Mage::helper("zolagocommon")->__("Please enter at least {0} characters"); ?>'
                }
            }
        })
    });
</script>
