<?php
/** @var $this Zolago_Solrsearch_Block_Faces_Flag */
$key = $this->getFacetKey();
?>
<?php if ($this->getCanShow()): ?>
    <?php
    $sectionClass = $this->isFilterRolled() ? 'closed' : 'open';
    $iconClass = $this->isFilterRolled() ? "fa-angle-down" : "fa-angle-up";
    $isOptionSelected = false;
    $key_withoutFacet = explode("_", $key);
    array_pop($key_withoutFacet);
	$pureKey = implode("_", $key_withoutFacet);
    $name = '';
    ?>

    <div class="section clearfix" data-xs-rolled="closed" data-lg-rolled="<?php echo $sectionClass; ?>">
        <h3 class="<?php echo $sectionClass; ?>"><span><?php echo $this->getFacetLabel(); ?></span> <i class="fa <?php echo $iconClass; ?>"></i></h3>
        <div class="content filter-flags"  id="filter_<?php echo $key ?>">
    <?php foreach ($this->getItems() as $item): ?>
        <?php if ($this->getCanShowItem($item)): ?>
            <?php
            if(!$isOptionSelected && $item['active']) {
                $isOptionSelected = true;
            }
            $name = $this->getNameBasedOnContent($item['item']);
            $class = $this->getClassBasedOnContent($item['item']);
            ?>
            <div class="form-group form-checkbox">
                <input type="checkbox" 
					   name="<?php echo $item['name'];?>"
					   value="<?php echo $item['value']?>"
					   id="<?php echo $item['itemId']?>" 
					   class="css-checkbox" 
					   data-params='<?php echo $item['params'];?>' 
					   data-url="<?php echo $item['url'] ?>" <?php if ($item['active']): ?>checked<?php endif; ?>>
	            <label for="<?php echo $item['itemId']; ?>" class="css-label <?php echo $class; ?>">
                    <span>
                        <a href="<?php echo $item['url']; ?>"
                           class="listing-link">
	                        <?php echo $item['item']; ?>
                        </a>
                    </span>
		            &nbsp;
                    <span class="suffix">
                        (<?php echo $item['count']; ?>)
                    </span>
	            </label>
            </div>

        <?php endif; ?>
    <?php endforeach; ?>

        </div>
        <?php if($isOptionSelected) : ?>
            <div class="content-xs" id="filter_<?php echo $key ?>_xs" data-content="xs">
                <div class="active-filter">
                    <?php foreach ($this->getItems() as $item): ?>
                        <?php if ($this->getCanShowItem($item) && $item['active']): ?>

                                <a href="<?php echo $item['url']; ?>"
                                   class="active-filter-label"
                                   data-input="<?php echo $item['itemId']; ?>">
									<?php echo $item['value']; ?><div class="wrapper-x"><i class="fa fa-times"></i></div>
                                </a>
                                <input type="hidden" name="fq[<?php echo $pureKey; ?>]"
                                       value="<?php echo $item['value']; ?>"/>
                        <?php endif; ?>
                    <?php endforeach; ?>
                </div>
            </div>
        <?php endif; ?>
    </div>
<?php endif; ?>