<?php
/* @var $this Zolago_Solrsearch_Block_Faces_Price */
$solrData = $this->getSolrData ();
$priceFieldName = Mage::helper ( 'solrsearch' )->getPriceFieldName ();

$prefix = 'solrbridge-price';

$ranges = $this->getFacetPriceRanges();

$key = "fq[price]";
$sectionClass = $this->isFilterRolled() ? 'closed' : 'open';
$iconClass = $this->isFilterRolled() ? "fa-angle-down" : "fa-angle-up";
$isOptionSelected = $this->getIsRangeActive();

$min = $this->getMinPriceRange();
$max = $this->getMaxPriceRange();

if($isOptionSelected){
	$fromValue = $this->getCurrentStartPrice();
	$toValue = $this->getCurrentEndPrice();
}else{
	$fromValue = $min;
	$toValue = $max;
}


if($toValue==0){
	$toValue = $max;
}

$name = '';
$somethingIsActive = $isOptionSelected;

$currencyCode = Mage::app()->getStore()->getCurrentCurrencyCode();
$currencySymbol = Mage::app()->getLocale()->currency($currencyCode)->getSymbol();
?>
<?php if ($max > 0 && (int)$max > (int)$min):?>
    <div class="section clearfix" data-xs-rolled="closed" data-lg-rolled="<?php echo $sectionClass; ?>">
        <h3 class="<?php echo $sectionClass; ?>"><span><?php echo $this->__("Price"); ?></span> <i class="fa <?php echo $iconClass; ?>"></i></h3>
        <div class="content"  id="filter_price">
			<?php foreach($ranges as $range) : ?>
			<?php $url = $range['url']; ?>	
            <div class="form-group form-checkbox hidden">

                <input 
					type="checkbox" 
					data-url="<?php echo $url;?>"
					value="<?php echo $range['value'];?>" 
					name="<?php echo $key; ?>" 
					id="<?php echo $range['itemId'];?>" 
					class="css-checkbox"
					<?php if ($range['active'] && !$isOptionSelected):?> checked="checked"<?php $somethingIsActive = true; endif;?>
				/>
                <label for="<?php echo $range['itemId'];?>" class="css-label">
	                <span>
		                <a href="<?php echo $url; ?>"
		                   class="listing-link">
			                <?php echo $range['formatted'] ?>
		                </a>
	                </span>
	                <span class="suffix">
		                (<?php echo $range['count']; ?>)
	                </span>
                </label>
            </div>
			<?php endforeach; ?>
            <div id="od_do" class="clearfix">

                <div id="slider-range" data-min="<?php echo $min;?>" data-max="<?php echo ceil($max);?>"></div>
                <div class="clearfix">
                    <div id="checkSlider" class="form-group form-checkbox hidden">
                        <?php $value = $fromValue . " TO " . $toValue; ?>
                        <?php $url = $this->getItemUrl($value, array('slider'=>1, 'fq'=>array('price' => $value))); ?>
                        <input
                            type="checkbox"
                            data-url="<?php echo $url;?>"
                            name="<?php echo $key; ?>"
                            value="<?php echo ($isOptionSelected) ? $fromValue . " TO " . $toValue  : "";?>"
                            id="filter_slider"
                            class="css-checkbox"
                            <?php if($isOptionSelected) : ?>checked="checked"<?php endif; ?>
                        />
                        <label for="filter_slider" class="css-label"><a class="listing-link" href="<?php echo $url; ?>"></a></label>
                    </div>
                    <div class="slider-range-info">
                        <input id="price_submit" type="submit" class="btn hidden black filter-price-range-submit" data-url="<?php echo $this->getItemUrl('price',array('fq'=>array('price'=> '__min TO __max')));?>" data-filter-type="price" value="<?php echo Mage::helper("zolagocatalog")->__("Filter"); ?>" />

                            <label><?php echo Mage::helper("zolagocatalog")->__("Price"); ?>:</label>
                            <input type="tel" id="zakres_min" disabled="disabled" value="<?php echo $fromValue; ?>" /><label for="zakres_od"> <?php echo $currencySymbol; ?> - </label>

                            <input id="zakres_max" disabled="disabled" value="<?php echo $toValue; ?>" type="tel" /><label><?php echo $currencySymbol; ?></label>

                    </div>
                </div>
            </div><br />


        </div>
        <?php if($somethingIsActive) : ?>
            <div class="content-xs" id="filter_price_xs" data-content="xs">
                <div class="active-filter">
                    <?php foreach($ranges as $range) : ?>
                        <?php if ($range['active'] && !$isOptionSelected): ?>
                                <a href="<?php echo $this->getRemoveFacesUrl("price", $range['value']); ?>"
                                   class="active-filter-label"
                                   data-input="<?php echo $range['itemId']; ?>">
									<?php echo $item['value']; ?><div class="wrapper-x"><i class="fa fa-times"></i></div>
                                   </a>
                        <?php endif; ?>
                    <?php endforeach; ?>
                </div>
            </div>
        <?php endif; ?>
    </div>
    <script type="text/javascript">
        Mall.listing.setCurrentPriceRange(<?php echo $fromValue; ?>, <?php echo $toValue; ?>);
    </script>
<?php endif;?>

<script type="text/javascript">
    Mall.translate.add("price-filter-not-valid", "<?php echo $this->__("Prices in filter are not valid."); ?>");
</script>
