<?php $_orders = $this->getOrders(); ?>
<?php $_openedOrders = $this->getOpenedOrders(); ?>
<?php $_helper = Mage::helper("zolagosales");?>
<?php $baseUrl = Mage::helper("core/url")->getHomeUrl(); ?>
<div class="page-title box-wrapper">
	<h1>
		<span><?php echo $this->__('Order history') ?></span>
		<span class="back-sm"><a href="<?php echo $baseUrl ?>customer/account/index/" class="underline"><?php echo $_helper->__('back: my account'); ?>&nbsp;&gt;</a></span>
		<span class="back-xs"><a href="<?php echo $baseUrl ?>customer/account/index/" class="underline"><?php echo $_helper->__('back'); ?>&nbsp;&gt;</a></span>
	</h1>
</div>
<?php echo $this->getChildHtml("attach"); ?>
<?php if($_orders->getSize()): ?>
	<div class="background-wrapper box-wrapper">
	<?php if ($_openedOrders): ?>
	<div>
		<p><a class="underline" href="<?php echo Mage::getUrl("sales/order/process") ?>"><?php echo $_helper->__('You have %s. Click to browse your open orders.',Mage::helper('orbacommon')->formatOrdersText($_openedOrders)); ?> > </a></p>
	</div>
	<?php endif; ?>
		<table class="data-table table-top" id="my-orders-table">
			<col width="120px" />
			<col class="order-no" width="120px" />
			<col />
			<col  class="products"/>
			<col  class="total" width="90px" />
			<col  class="status" width="90px" />
			<col width="90px" />
			<thead>
				<tr>
					<th><?php echo $_helper->__('Date placed') ?></th>
					<th class="order-no"><?php echo $_helper->__('Order no') ?></th>
					<th><?php echo $_helper->__('Shops') ?></th>
					<th class="products"><?php echo $_helper->__('Products') ?></th>
					<th class="total"><?php echo $_helper->__('Value') ?></th>
					<th class="status"><?php echo $_helper->__('Status') ?></th>
					<th><?php echo $_helper->__('Order details') ?></th>
				</tr>
			</thead>
			<tbody>
				<?php foreach ($_orders as $_order): ?>
				<?php $_hasPo = $this->hasPo($_order,true);?>
				<tr>
					<td><span class="nobr"><?php echo $this->formatDate($_order->getCreatedAtStoreDate()) ?></span></td>
					<td class="order-no"><?php echo $_order->getRealOrderId() ?></td>
					<td class="data-table-td-shops">
						<ul class="list-unstyled">
						<?php foreach($this->getVendors($_order,true) as $_vendor):?>
							<li class="uppercase"><?php echo $this->escapeHtml($_vendor->getVendorName());?></li>
						<?php endforeach;?>
						</ul>
					</td>
					<td class="products">
						<?php if($_hasPo):?>
						<ul class="list-unstyled product-list">
							<?php foreach($this->getSortedPoItemsByOrder($_order,true) as $_itemArray):?>
							<li>
								<?php echo $this->escapeHtml($_itemArray['item']->getName());?><br/>
								<?php foreach($this->extractProductOptions($_itemArray['options']) as $_option): ?>
									<span class="product-attribute"><?php echo $this->escapeHtml($_option['label']); ?>: <?php echo $this->escapeHtml($_option['value']); ?></span><br/>
								<?php endforeach;?>
							</li>
							<?php endforeach;?>
						</ul>
						<?php endif;?>
					</td>
					<td class="total">
						<?php if($_hasPo):?>
							<?php echo $_order->formatPrice($this->getTotal($_order,true)); ?>
						<?php endif;?>
					</td>
					<td class="status">
						<?php if($_hasPo):?>
							<nobr>
							<?php echo $this->getOrderStatus($_order);?>
							<?php /**  todo make icon configurable
							<?php $_icon = $this->getStatusIcon($_order);?>
							<?php if($_icon):?>
								<img src="<?php echo $_icon;?>"/>
							<?php endif;?>
							<?php */ ?>
							<?php if ($_order->getStatus() == 'complete') : ?>							
								&nbsp;&nbsp;<i class="fa fa-check-square"> </i>
							<?php endif; ?>
							</nobr>
						<?php else:?>
							<?php echo $_helper->__("Processing");?>
						<?php endif;?>
					</td>
					<td class="a-center">
						<?php if($_hasPo):?>
						<a class="underline" href="<?php echo $this->getViewUrl($_order) ?>">
							<?php echo $_helper->__('view') ?> &gt;
						</a>
						<?php endif;?>
					</td>
				</tr>
				<?php endforeach; ?>
			</tbody>
		</table>
		<div class="bottom-links">
			<a class="button button-third large" href="<?php echo Mage::getUrl("customer/account");?>">
				<i class="glyphicon glyphicon-chevron-left"></i>
				<?php echo $_helper->__('back') ?>
			</a>
		</div>
	</div>
<?php else: ?>
	<?php echo $this->getChildHtml("empty"); ?>
<?php endif ?>