<?php

/* @var $po ZolagoOs_OmniChannelPo_Model_Po */
$po = $this->getItem();

$deliveryCode = $po->getOmniChannelMethodInfoByMethod()->getDeliveryCode();

$ghInpostCarrierCode = Mage::getModel("ghinpost/carrier")->getCarrierCode();
$address = $this->getItem()->getShippingAddress();
$inpostLockerName = $po->getDeliveryPointName();

?>
<div class="sales-order-top col-md-6 col-sm-6 col-xs-12 sales-order-hide">
	<div class="sales-order-info">
		<div class="order-info-address">
			<span class="order-top-title"><?php echo $this->__("Shipping address"); ?></span>
			<?php if (($ghInpostCarrierCode == $deliveryCode) && $inpostLockerName): ?>
				<span class="order-top-txt"><?php echo Mage::helper('ghinpost')->__("Locker") . ' ' . $inpostLockerName; ?></span>
			<?php else: ?>
				<span class="order-top-txt"><?php echo $this->escapeHtml($address->getFirstname().' '.$address->getMiddlename().' '.$address->getLastname()); ?></span>
			<?php endif; ?>
			<span class="order-top-txt order-top-address"><?php echo implode('<br />',$address->getStreet()); ?></span>
			<span class="order-top-txt"><?php echo $this->escapeHtml($address->getPostcode().' '.$address->getCity()); ?></span>
			<span class="order-top-txt"><?php echo $this->__('tel').': '.$this->escapeHtml($address->getTelephone()); ?></span>
		</div>
		<div class="order-info-document">
			<span class="order-top-title"><?php echo $this->__("Sale document"); ?></span>
			<span class="order-top-txt"><?php echo $this->__($this->getSaleDocument()); ?></span>
		</div>
	</div>
</div>