<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php $_orders = $this->getOrders(); ?>
<?php $_helper = Mage::helper("zolagosales");?>
<?php $baseUrl = Mage::helper("core/url")->getHomeUrl(); ?>
<div class="page-title box-wrapper">
	<h1>
		<span><?php echo $this->__('Orders in the realization') ?></span>
		<span class="back-sm"><a href="<?php echo $baseUrl ?>customer/account/index/" class="underline"><?php echo $_helper->__('back: my account'); ?> &gt;</a></span>
		<span class="back-xs"><a href="<?php echo $baseUrl ?>customer/account/index/" class="underline"><?php echo $_helper->__('back'); ?> &gt;</a></span>
	</h1>
</div>
<div class="order-view order-view-multi">
	<div class="section " id="content-main">
	<?php if($_orders->getSize()): ?>
		<?php foreach($_orders as $_order):?>
		<?php /* @var $_order Mage_Sales_Model_Order */ ?>
			<?php echo $this->getOrderHtml($_order); ?>
		<?php endforeach;?>
	<?php else: ?>
		Empty list info
	<?php endif ?>
	</div>
</div>