<?php /* @var $this Zolago_Modago_Block_Sales_Order_View */ ?>
<?php $_items = $this->getItems(); ?>
<?php $_helper = Mage::helper("sales"); ?>
<?php $baseUrl = Mage::helper("core/url")->getHomeUrl(); ?>
<div class="page-title box-wrapper">
	<h1>
		<span><?php echo $this->__('Order history'); ?></span>
		<span class="back-sm"><a href="<?php echo $baseUrl ?>customer/account/index/" class="underline"><?php echo $_helper->__('back: my account'); ?> &gt;</a></span>
		<span class="back-xs"><a href="<?php echo $baseUrl ?>customer/account/index/" class="underline"><?php echo $_helper->__('back'); ?> &gt;</a></span>
	</h1>
</div>
<div class="order-view box-wrapper">
	<div class="section " id="content-main">
		<section class="main bg-w">
			<header class="title-section">
				<div class="headerTop">
					<div class="table-row clearfix" id="order_header">
						<div class="pull-left">
							<h2><?php echo $this->__("Order number") . ': ' . $this->getOrder()->getIncrementId(); ?></h2>
						</div>
						<div class="order-date hidden-xs">
							<?php echo $this->__('Order date') . ': ' . $this->helper('core')->formatDate(($this->getOrder()->getCreatedAt()), Mage_Core_Model_Locale::FORMAT_TYPE_SHORT);
							; ?>
						</div>
					</div>
				</div>
				<?php $_grandTotal = $this->getGrandTotal(); ?>
				<p class="visible-xs"><?php echo $this->__('Order date') . ': ' . date('Y-m-d', strtotime($this->getOrder()->getCreatedAt())); ?></p>
				<p><?php echo $this->__('Status') . ': ' . $this->getOrder()->getStatusLabel(); ?> <i class="fa fa-question-circle"></i></p>
				<p><?php echo $this->__('Total order value') . ': ' . Mage::helper('core')->formatPrice($_grandTotal); ?> </p>
				<p><?php echo $this->__('Payment') . ': ' . $this->getPaymentHtml(); ?> </p>
			</header>
			<?php $total = 1; ?>
				<?php foreach ($_items as $nr => $_item) : ?>
				<?php $_shipment = $_item->getLastNotCanceledShipment();?>
				<div class="panel panel-default no-border-top">
					<div class="tableWrapper">
						<div class="table-row clearfix panel-header">
							<?php $_v = $_item->getVendor(); ?>
								<?php if ($_v->getId()): ?>
								<div class="panel-heading pull-left col-sm-6 col-xs-12"><?php echo $this->__("Shop"); ?>: <strong><?php echo $_v->getVendorName() ?></strong>


									<?php else: ?>
									<div class="panel-heading"><?php echo $this->__("Unknown vendor"); ?>
									<?php endif ?>
									<?php if (count($_items) > 1) : ?>
										(<?php printf($this->__('Shipment %d of %d'), ($total++), count($_items)); ?>)
									<?php endif; ?>
									<br/>
									<a class="small underline visible-xs contact-vendor" href="#" 
										data-order-id="<?php echo $_item->getId();?>" data-vendor-id="<?php echo $_v->getId();?>"
										data-vendor-name="<?php echo $this->escapeHtml($_v->getVendorName());?>"
										<?php if($_shipment):?>data-shipment-id="<?php echo $_shipment->getId();?>"<?php endif;?>>
											<?php echo $_helper->__('Contact with vendor'); ?>
									</a>
								</div>		
								<div class="pull-right panel-heading col-sm-6 col-xs-12 hidden-xs">
									<a class="small underline pull-right rght-margin-30 contact-vendor" href="#" 
									   data-order-id="<?php echo $_item->getId();?>" data-vendor-id="<?php echo $_v->getId();?>"
									   data-vendor-name="<?php echo $this->escapeHtml($_v->getVendorName());?>"
									   <?php if($_shipment):?>data-shipment-id="<?php echo $_shipment->getId();?>"<?php endif;?>>
										<?php echo $_helper->__('Contact with vendor'); ?>
									</a>
								</div>
							</div>
						</div>
						<div class="panel-body visible-xs panel-contact-vendor">
							<div id="contact-vendor-<?php echo $_v->getId();?>-<?php echo $_item->getId();?>"></div>
						</div>
						<div class="panel-body">
							<div class="table-row clearfix sales-order-top-row">
								<?php echo $this->getShipmentBlock($_item); ?>
								<?php echo $this->getInfoBlock($_item); ?>
							</div>
							<div class="tableWrapper table-cart">
								<!-- Thead -->
								<?php foreach ($_item->getAllItems() as $_product) : ?>
									<?php if (!$_product->getOrderItem()->getParentItemId()): ?>
										<?php echo $this->getItemHtml($_product); ?>
									<?php endif; ?>
								<?php endforeach; ?>
								<!-- TFoot -->
								<div class="table-footer-group hidden-xs">
									<div class="table-row clearfix">
										<div class="table-cell cell-01 td">
										</div>

										<div class="table-cell cell-03 label_value td">
											<div class="value_quality_delivery">
												<?php echo $this->__("Shipping cost"); ?>:

											</div>
											<div class="value_quality_price"><?php echo $this->__('Sum:') ?></div>
										</div>
										<div class="table-cell cell-04 td">
											<div class="quality_delivery"><?php echo Mage::helper('core')->formatPrice($_item->getData('shipping_amount_incl')); ?></div>
											<div class="quality_price"><?php echo Mage::helper('core')->formatPrice($_item->getData('grand_total_incl_tax')) ?></div>
										</div>
										<div class="table-cell cell-05 td"></div>
									</div>

								</div>
								<!-- TFoot mobile-->
								<div class="table-footer-group visible-xs">
									<div class="table-row clearfix">
										<div class="table-cell cell-01 td">
										</div>
										<div class="table-cell cell-03 label_value td">
											<div class="value_quality_price"><?php echo $this->__("Sum:"); ?></div>
											<div class="value_quality_delivery"><?php echo $this->__("Shipping cost"); ?>:</div>
										</div>
										<div class="table-cell cell-04 td">
											<div class="quality_price"><?php echo Mage::helper('core')->formatPrice($_item->getData('grand_total_incl_tax')) ?></div>
											<div class="quality_delivery"><?php echo Mage::helper('core')->formatPrice($_item->getData('shipping_amount_incl')); ?></div>
										</div>
										<div class="table-cell cell-05 td">
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				<?php endforeach; ?>


				<div class="bottom-links">
					<a class="button button-third large" href="<?php echo Mage::getUrl("sales/order/history"); ?>">
						<i class="glyphicon glyphicon-chevron-left"></i>
						<?php echo $this->__('back') ?>
					</a>
				</div>
		</section>
	</div>
</div>


<div class="hidden" id="vendor_contact_form_template">
	<?php echo $this->getChild("question")->
		setVendorId("{{vendor_id}}")->
		setOrderId("{{order_id}}")->
		setShipmentId("{{shipment_id}}")->
		toHtml(); ?>
</div>

<script type="text/javascript">
	jQuery(function(){
		Mall.translate.add("required", '<?php echo $_helper->__("This field is required.");?>');
		Mall.translate.add("Contact Vendor", '<?php echo $_helper->__("Contact Vendor");?>');
		Mall.sales.vendorContact.setFormTemplateId("vendor_contact_form_template");
		jQuery("a.contact-vendor").click(Mall.sales.vendorContact.handleClick);
		jQuery(window).resize(Mall.sales.vendorContact.handleResize);
	});
</script>