<?php $key = $this->getFacetKey(); ?>
<?php if($this->getCanShow()): ?>
	<h3><?php echo $this->getFacetLabel(); ?></h3>
	<dd>
		<ul id="category-layered-nav" class="category">
		<?php foreach ($this->getAllItems() as $item=>$count):?>
			
			<?php if (is_array($count)): ?>
				
				<?php if($count['is_root_category']): ?>
					
					<?php foreach($count['children'] as $child_item=>$children_count): ?>
							
						<?php if($this->getCanShowItem($child_item, $children_count)): ?>
							
							<li><a data-params='<?php echo $this->getItemJson($item);?>' href="<?php echo $this->getItemUrl($child_item) ?>" class=""><?php echo $this->getItemText($child_item); ?>&nbsp;<span>(<?php echo $children_count ?>)</span></a></li>
						
						<?php endif;?>
						
					<?php endforeach; ?>
					
				<?php else: ?>
					
					<li>
						<div><?php echo $this->getItemText($item); ?>&nbsp;<span>(<?php echo $count['total'] ?>)</span></div>
						<ul>
							
							<?php foreach($count['children'] as $child_item=>$children_count): ?>
								
								<?php if($this->getCanShowItem($child_item, $children_count)): ?>
									
									<li><a data-params='<?php echo $this->getItemJson($item);?>' href="<?php echo $this->getItemUrl($child_item) ?>" class=""><?php echo $this->getItemText($child_item); ?>&nbsp;<span>(<?php echo $children_count ?>)</span></a></li>
								
								<?php endif;?>
								
							<?php endforeach; ?>
							
						</ul>
					</li>
					
				<?php endif; ?>
				
				
			<?php else: ?>
				
				<?php if($this->getCanShowItem($item, $count)): ?>
					
					<li>
						<a data-params='<?php echo $this->getItemJson($item);?>' href="<?php echo $this->getItemUrl($item) ?>" class=""><?php echo $this->getItemText($item); ?>&nbsp;<span>(<?php echo $count ?>)</span></a>
					</li>
					
				<?php endif;?>
				
			<?php endif; ?>
			
		<?php endforeach;?>
		</ul>
	</dd>
<?php endif; ?>
