<?php $key = $this->getFacetKey(); ?>
<?php if ($this->getCanShow()): ?>
	<dt id="solr_search_<?php echo $key ?>_expander" onclick="Effect.toggle('content_holder_<?php echo $key ?>', 'slide', {duration: 0.3});
			$('solr_search_<?php echo $key ?>_expander').toggleClassName('collapsed');
			return false;"><?php echo $this->getFacetLabel(); ?></dt>
	<dd id="content_holder_<?php echo $key ?>">
		<?php echo $this->getParsedCategories();?>
	</dd>
<?php endif; ?>