<?php $key = $this->getFacetKey(); ?>
<?php if ($this->getCanShow()): ?>
	<dt id="solr_search_<?php echo $key ?>_expander" onclick="Effect.toggle('content_holder_<?php echo $key ?>', 'slide', {duration: 0.3});
			$('solr_search_<?php echo $key ?>_expander').toggleClassName('collapsed');
			return false;" <?php if($this->isFilterRolled()):?>class="collapsed"<?php endif;?>><?php echo $this->getFacetLabel(); ?></dt>
	<dd id="content_holder_<?php echo $key ?>" <?php if($this->isFilterRolled()):?>style="display:none;"<?php endif;?>>
		<ol class="visible_filters">
			<?php foreach ($this->getItems() as $item => $count): ?>
				<?php if ($this->getCanShowItem($item, $count)): ?>
					<li>					
						<a href="<?php echo $this->getItemUrl($item) ?>" data-params='<?php echo $this->getItemJson($item);?>' class="facet-item <?php echo $this->getItemClass($item); ?>"><?php echo $item ?>&nbsp;<span>(<?php echo $count ?>)</span></a>
					</li>
				<?php endif; ?>
			<?php endforeach; ?>
		</ol>
		<?php if ($this->getCanShowHidden()): ?>
			<ol style="display: none;" id="content_hidden_holder_<?php echo $key ?>">
				<?php foreach ($this->getHiddenItems() as $item => $count): ?>
					<li>
						<a href="<?php echo $this->getItemUrl($item) ?>" data-params='<?php echo $this->getItemJson($item);?>' class="facet-item <?php echo $this->getItemClass($item); ?>"><?php echo $item ?>&nbsp;<span>(<?php echo $count ?>)</span></a>
					</li>
				<?php endforeach; ?>
			</ol>
			<div id="solr_search_hidden_<?php echo $key ?>_expander">
				<a href="#"  onclick="Effect.toggle('content_hidden_holder_<?php echo $key ?>', 'slide', {duration: 0.3});
				$('solr_search_hidden_<?php echo $key ?>_expander').toggleClassName('collapsed').hide();
				return false;"><?php echo $this->__("show more");?></a>
			</div>
		<?php endif; ?>
	</dd>
<?php endif; ?>