<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
<head>
<?php echo $this->getChildHtml('head'); ?>
</head>
<body class="not-front not-logged-in <?php if($this->getIsCheckout()):?>checkout<?php endif;?> <?php echo $this->getBodyClass()?' '.$this->getBodyClass().'':'' ?>">
<!--[if lt IE 9]>
<p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
<![endif]-->
<div id="sb-site" class="sb-site fb-site">
    <?php echo $this->getChildHtml('after_body_start') ?>

    <?php echo $this->getChildHtml('global_notices') ?>

    <?php echo $this->getChildHtml('header') ?>

    <div class="container-fluid">


        <div class="row">
            <div class="col-sm-12">
                <?php /* echo  $this->getChildHtml('global_messages') */ ?>
                <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
            </div>
        </div>

    </div>

    <section id="main" class="<?php echo $this->getElementClass(); ?>">
        <header id="header-main">
            <div class="container-fluid">
                <div class="row hidden-xs">
                    <div id="breadcrumbs" class="col-sm-12">
                        <?php echo $this->getChildHtml('breadcrumbs') ?>
                    </div>
                </div>
            </div>
        </header>

        <?php echo $this->getChildHtml('content') ?>
    </section>

    <?php echo $this->getChildHtml('footer') ?>
    <?php echo $this->getChildHtml('global_cookie_notice') ?>
    <?php echo $this->getChildHtml('before_body_end') ?>

    <?php echo $this->getAbsoluteFooter() ?>

</div>

<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('navigation-sliding-left')->toHtml(); ?>
</body>
</html>
