<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
<head>
<?php echo $this->getChildHtml('head'); ?>
</head>
<body class="not-front not-logged-in <?php echo $this->getBodyClass()?' '.$this->getBodyClass().'':'' ?>">
<!--[if lt IE 9]>
<p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
<![endif]-->
<div id="sb-site" class="sb-site fb-site">
    <?php echo $this->getChildHtml('after_body_start') ?>

    <?php echo $this->getChildHtml('global_notices') ?>

    <?php echo $this->getChildHtml('header') ?>

    <div class="container-fluid">


        <div class="row"><div class="col-sm-12"><ul class="messages">
            <li class="error-msg">
                <ul>
                    <li><span>Review summary can't be empty</span></li>
                    <li><span>Nickname can't be empty</span></li>
                    <li><span>Recommend product can't be unchecked</span></li>
                    <li><span>Review can't be empty</span></li>
                </ul>
            </li>
        </ul></div></div>

    </div>

    <section id="main" class="<?php echo $this->getElementClass(); ?>">
        <header id="header-main">
            <div class="container-fluid">
                <div class="row hidden-xs">
                    <div id="breadcrumbs" class="col-sm-12">
                        <?php echo $this->getChildHtml('breadcrumbs') ?>
                    </div>
                </div>
            </div>
        </header>
        <?php echo $this->getChildHtml('global_messages') ?>


        <style type="text/css">
            ul.messages, ul.messages ul {
                list-style: none;
                padding-left: 0;
            }
            ul.messages ul {
                padding-left: 0;
            }
            ul.messages >li.success-msg ul>li {
                background: #73ac18 url("/skin/frontend/modago/default/images/msg_ico_success.png") no-repeat 5px 21px;
                margin-top: 10px;
            }
            ul.messages >li.error-msg ul>li, ul.messages >li.notice-msg ul>li {
                background: #e25856 url("/skin/frontend/modago/default/images/msg-ico-error.png") no-repeat 8px 18px;
                margin-top: 10px;
            }
            ul.messages >li ul>li>span {
                background-color: #deeaca;
                margin-left: 20px;
                height: 100%;
                display: block;
                min-height: 50px;
                padding-left: 15px;
                line-height: 50px;
                position: relative;
            }

            ul.messages >li.error-msg ul>li>span {
                background-color: #f2e6e6;
            }

            ul.messages ul>li>span>i {
                position: absolute;
                right: 16px;
                top: 17px;
            }
        </style>

        <script type="text/javascript">
        </script>

        <?php echo $this->getChildHtml('content') ?>
    </section>

    <?php echo $this->getChildHtml('footer') ?>
    <?php echo $this->getChildHtml('global_cookie_notice') ?>
    <?php echo $this->getChildHtml('before_body_end') ?>

    <?php echo $this->getAbsoluteFooter() ?>

</div>

<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('navigation-sliding-left')->toHtml(); ?>
</body>
</html>
