<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
<head>
    <?php echo $this->getChildHtml('head'); ?>
</head>
<body class="not-front not-logged-in <?php echo $this->getBodyClass()?' '.$this->getBodyClass().'':'' ?>">
<!--[if lt IE 9]>
<p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
<![endif]-->
<div id="sb-site" class="sb-site fb-site">
    <?php echo $this->getChildHtml('after_body_start') ?>

    <?php echo $this->getChildHtml('global_notices') ?>

    <?php echo $this->getChildHtml('header') ?>

    <div class="container-fluid">


        <div class="row">
            <div class="col-sm-12">
                <?php echo $this->getChildHtml('global_messages') ?>
            </div>
        </div>

    </div>

    <?php echo $this->getChildHtml('content'); ?>

    <script>
        (function($){
            $(window).load(function(){




                $( "#slider-range" ).slider({
                    range: true,
                    min: 0,
                    max: 500,
                    values: [ 75, 300 ],
                    slide: function(event, ui) {
                        $("#zakres_min").val(ui.values[0]);
                        $("#zakres_max").val(ui.values[1]);
                    }

                });

                $("#zakres_min").val($("#slider-range").slider("values", 0));
                $("#zakres_max").val($("#slider-range").slider("values", 1));


            });
        })(jQuery);
    </script>

    <?php echo $this->getChildHtml('footer') ?>
    <?php echo $this->getChildHtml('global_cookie_notice') ?>
    <?php echo $this->getChildHtml('before_body_end') ?>

    <?php echo $this->getAbsoluteFooter() ?>

</div>

<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('navigation-sliding-left')->toHtml(); ?>
</body>
</html>
