<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
<head>
    <?php echo $this->getChildHtml('head'); ?>
</head>
<body class="not-front not-logged-in <?php echo $this->getBodyClass()?' '.$this->getBodyClass().'':'' ?>">
<!--[if lt IE 9]>
<p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
<![endif]-->
<div id="sb-site" class="sb-site fb-site">
    <?php echo $this->getChildHtml('after_body_start') ?>

    <?php echo $this->getChildHtml('global_notices') ?>

    <?php echo $this->getChildHtml('header') ?>

    <div class="container-fluid">


        <div class="row">
            <div class="col-sm-12">
                <?php echo $this->getChildHtml('global_messages') ?>
            </div>
        </div>

    </div>

    <section id="main" class="<?php echo $this->getElementClass(); ?>">
        <header id="header-main">
            <div class="wrapp-section bg-w">
                <div class="container-fluid">
                    <div class="row ">
                        <div id="view-current-filter" class="col-sm-12 ">
                            <?php echo $this->getChildHtml('breadcrumbs') ?>


                            <h1>Sukienki</h1>
                            <a href="#" class="backToCategory underline visible-xs">Wróć do kategorii: Ona ></a>
                            <div class="view_filter clearfix">

                                <dl class="clearfix">
                                    <dt>Aktualnie ogladasz:</dt>
                                    <dd>
                                        <span class="label">Rozmiar: <span class="value">M</span><i class="fa fa-times"></i></span>
                                        <span class="label">Rozmiar: <span class="value">M</span><i class="fa fa-times"></i></span>
                                        <span class="label">Marka: <span class="value">Adidas</span><i class="fa fa-times"></i></span>
                                        <span class="label">Marka: <span class="value">Adidas</span><i class="fa fa-times"></i></span>
                                    </dd>
                                    <dd class="action"><a href="#" class="button button-third">Wyczyść filtry</a></dd>
                                </dl>
                                <a href="#" class="actionViewFilter button button-primary medium visible-xs"><i class="fa fa-chevron-right"></i> Filtruj Produkty</a>
                            </div>


                        </div>
                    </div>
                </div>
            </div>
        </header>

        <aside id="sort-criteria" class="container-fluid">
            <div class="col-sm-12">
                <ul class="sort clearfix">
                    <li id="number_products" class=""><span class="label">Ilość produktów: </span> <span class="value"> 12345</span></li>
                    <li>
                        <form action="">
                            <div class="form-group clearfix">
                                <div class="sort-by clearfix">
                                    <label for="sort-by">Sortuj:</label>

                                    <div class="select-group small test">
                                        <a class="button-select no-ajax" href="#"><span>według:</span> <span class="down"></span></a>
                                        <div class="dropdown-select mCustomScrollbar">
                                            <ul  data-role="listview">
                                                <li><a href="#" data-value="Item I"><span>Item I</span> <span class="suffix">(200)</span></a></li>
                                                <li><a href="#" data-value="Item II"><span>Item II</span> <span class="suffix">(200)</span></a></li>
                                                <li><a href="#" data-value="Item III"><span>Item III</span> <span class="suffix">(200)</span></a></li>
                                                <li><a href="#" data-value="Item IV"><span>Item IV</span> <span class="suffix">(200)</span></a></li>
                                                <li><a href="#" data-value="Item V"><span>Item V</span> <span class="suffix">(200)</span></a></li>
                                                <li class="divider"></li>
                                                <li><a href="#">Other</a></li>
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </li>
                </ul>
            </div>
        </aside>

        <div id="content" class="container-fluid">
        <div class="row">
        <div class="col-sm-12">
        <div id="sidebar" class="hidden-xs">

        </div>
        <div id="content-main">

            <?php echo $this->getChildHtml('content') ?>

        <!-- END jsMasonryContent -->
        <div class="addNewPositionListProductWrapper">
            <a href="#" class="addNewPositionListProduct">ZOBACZ KOLEJNE 100 PRODUKTÓW</a>
        </div>


        </div>
        </div>
        </div>
        </div>

    </section>
    <script>
        (function($){
            $(window).load(function(){




                $( "#slider-range" ).slider({
                    range: true,
                    min: 0,
                    max: 500,
                    values: [ 75, 300 ],
                    slide: function(event, ui) {
                        $("#zakres_min").val(ui.values[0]);
                        $("#zakres_max").val(ui.values[1]);
                    }

                });

                $("#zakres_min").val($("#slider-range").slider("values", 0));
                $("#zakres_max").val($("#slider-range").slider("values", 1));


            });
        })(jQuery);
    </script>

    <?php echo $this->getChildHtml('footer') ?>
    <?php echo $this->getChildHtml('global_cookie_notice') ?>
    <?php echo $this->getChildHtml('before_body_end') ?>

    <?php echo $this->getAbsoluteFooter() ?>

</div>

<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('navigation-sliding-left')->toHtml(); ?>
</body>
</html>
