<!-- PRODUCT SHOP -->
<?php
/** @var Zolago_Modago_Block_Catalog_Product_View_Shop $this */

/** @var Zolago_Catalog_Model_Product $_product */
$_product = $this->getProduct();
$currencyCode = Mage::app()->getStore()->getCurrentCurrencyCode();
$currencySymbol = Mage::app()->getLocale()->currency($currencyCode)->getSymbol();

/** @var Mage_Catalog_Helper_Output $_helper */
$_helper = $this->helper('catalog/output');

/** @var Zolago_Catalog_Helper_Data $hlp */
$hlp = Mage::helper('catalog');

/** @var Zolago_Catalog_Helper_Product $productHelper */
$productHelper = Mage::helper("zolagocatalog/product");

$isSalable = $_product->isSalable(); //product is salable
// prices
$price = $_product->getPrice();
$finalPrice = $_product->getFinalPrice();
$sizeAttr = $_product->getResource()->getAttribute('size');
$productAttrs = array();
if ($_product->getTypeId() == 'configurable') {
	$productAttrs = $_product->getTypeInstance(true)->getConfigurableAttributesAsArray($_product);
}

$_helperSizetable = Mage::helper('zolagosizetable');
/** @var Zolago_Sizetable_Helper_Data $_helperSizetable */
$vendor_id = $_product->getData('udropship_vendor');
$storeId = Mage::app()->getStore()->getStoreId();
$attributeSetId = $_product->getData('attribute_set_id');
$brandId = $_product->getData('manufacturer');
if ($_product->getTypeId() == 'configurable') { //fix for simple products
	/** @var Zolago_Catalog_Block_Product_View_Type_Configurable $salableCount */
	$salableCount = Mage::getBlockSingleton('zolagocatalog/product_view_type_configurable')->getSalableCount();
}
$sizeTableValue = '1';// allways 
$deliveryHeadline = trim($this->getStoreDeliveryHeadline());
$returnHeadline = trim($this->getStoreReturnHeadline());
?>


<?php

$productName = $_helper->productAttribute($_product, $_product->getName(), 'name');

//$vendor = Mage::helper('udropship')->getVendor($vendor_id);
//$vendorName = $vendor->getData("vendor_name");
//$vendorUrl = Mage::helper("umicrosite")->getVendorUrl($vendor);
//$productName = str_replace($vendorName, "<a itemprop='brand' href='".$vendorUrl."'>".$vendorName."</a>",$productName);
?>
<!-- PRODUCT NAME -->
<div id="product-name" class="col-md-12 product-name" style="overflow-x:visible;">
        <h1 itemprop="name"><?php echo $productName; ?></h1>
        <meta itemprop="sku" content="<?php echo $_product->getSku() ?>"/>
</div>
<!-- /PRODUCT NAME -->
<!-- SHORT DESCRIPTION -->
<div class="col-md-12" id="short-description-block">
    <div id="product_price_box" class="row">
        <div id="product-price" class="col-lg-7 col-md-7 col-sm-7 col-xs-7">
            <?php if ($_product->getCanShowPrice() !== false): ?>
                <div class="price-box-bundle">
                    <div class="price-box row">
                        <p class="price-box-line" itemprop="offers" itemscope itemtype="http://schema.org/Offer">
                            <?php if ($_product->getTypeId() == Mage_Catalog_Model_Product_Type::TYPE_CONFIGURABLE): ?>
                                <meta itemprop="price" content="<?php echo round($_product->getFinalPrice(), 2); ?>"/>
                            <?php endif; ?>

                            <meta itemprop="priceCurrency" content="<?php echo $currencyCode; ?>"/>
                            <meta itemprop="mpn" content="<?php echo $_product->getSku(); ?>"/>
                            
                            <?php if ($isSalable): ?>
                                <meta itemprop="availability" content="http://schema.org/InStock"/>
                            <?php else: ?>
                                <meta itemprop="availability" content="http://schema.org/OutOfStock"/>
                            <?php endif; ?>

                            <meta itemprop="itemCondition" itemtype="http://schema.org/OfferItemCondition" content="http://schema.org/NewCondition"/>
                            <span class="old-price"><?php if($_product->getTypeId() != Mage_Catalog_Model_Product_Type::TYPE_CONFIGURABLE && $_product->getStrikeoutPrice() != $_product->getFinalPrice()) : ?><?php echo str_replace(" ","&nbsp;",Mage::helper('core')->currency($_product->getStrikeoutPrice(), true, false)); ?><?php endif; ?></span>
                            <span class="price">
                                <?php if ($_product->getTypeId() != Mage_Catalog_Model_Product_Type::TYPE_CONFIGURABLE): ?>
                                    <span itemprop="price">
                                        <?php echo number_format($_product->getFinalPrice(), 2, ',', ' '); ?>
                                    </span> 
                                    <?php echo $currencySymbol; ?>
                                <?php endif; ?>
                            </span>
                        </p>
                    </div>
                </div>	    				    				    			
            <?php endif; ?>        
        </div>
        <div id="delivery-and-return" class="col-lg-5 col-md-5 col-sm-5 col-xs-5">
            <div>
                <?php if($deliveryHeadline): ?>
                    <?php echo $deliveryHeadline; ?>
                <?php endif; ?>
            </div>
            <div>
                <?php if($returnHeadline): ?>
                    <?php echo $returnHeadline; ?>
                <?php endif; ?>
            </div>
        </div>            
    </div>
    <div id="short-description" class="row">
            <?php echo $_helper->productAttribute($_product, nl2br($_product->getShortDescription()), 'short_description') ?>
    </div>

        <?php if ($_product->getTypeId() == Mage_Catalog_Model_Product_Type::TYPE_CONFIGURABLE) : ?>
					<!--    Meta tags-->
            <?php
					$childrenData = array();
					$childProducts = Mage::getModel('catalog/product_type_configurable')
						->getUsedProducts(null, $_product);
					foreach ($childProducts as $child) {
						$childrenData[$child->getId()] = $child->getSku();
					}

					$productViewTypeConfigurableBlock = Mage::getBlockSingleton('zolagocatalog/product_view_type_configurable');
					$config = $productViewTypeConfigurableBlock->getConfig();
					$basePrice = $config['basePrice'];
					if (isset($config['attributes']) & !empty($config['attributes'])):
						$attributes = $config['attributes'];
						foreach ($attributes as $attributeId => $attributeData):
							if ($attributeData['code'] == "size" && (isset($attributeData['options']) & !empty($attributeData['options']))):
								$options = $attributeData['options'];
								foreach ($options as $option):
									?>
									<span itemprop="offers" itemscope itemtype="http://schema.org/Offer">
                                        <meta itemprop="price" content="<?php echo round(($_product->getFinalPrice() + $option['price']), 2); ?>"/>
                                        <meta itemprop="priceCurrency" content="<?php echo $currencyCode; ?>"/>
                                        <meta itemprop="mpn" content="<?php echo $childrenData[$option['products'][0]]; ?>"/>
										<?php if ($option['is_salable']): ?>
											<meta itemprop="availability" content="http://schema.org/InStock"/>
										<?php else: ?>
											<meta itemprop="availability" content="http://schema.org/OutOfStock"/>
										<?php endif; ?>
										<meta itemprop="itemCondition" itemtype="http://schema.org/OfferItemCondition"
										      content="http://schema.org/NewCondition"/>
                                    </span>
									<?php
								endforeach;
							endif;
						endforeach;
					endif; 					
            ?>
                <!--    Meta tags-->
        <?php endif; ?>
        <div id="product-options" class="size-box-bundle">
            <?php if ($_product->getTypeId() == Mage_Catalog_Model_Product_Type::TYPE_CONFIGURABLE) : ?>
                <?php if (!empty($productAttrs)) : ?>
                    <?php foreach ($productAttrs as $_attribute) : ?>
                        <?php if (array_key_exists('attribute_code', $_attribute) && $_attribute['attribute_code'] == 'size') : ?>
                            <?php $haveSizes = true; ?>
                            <div class="size-box-label clearfix clr">
                                <div class="size-label"><?php echo Mage::helper('wfwf')->__("Size label"); ?></div>
                            </div>
                            <div class="size-box clearfix clr">                                
                                <div>
                                        <a href="#" class="view-sizing" data-toggle="modal"
												   data-target="#tabelaRozmiarow">
												   <?php if (!empty($sizeTableValue)) : ?>
                                                       <img src="<?php echo $this->getSkinUrl("images/svg/ruler.svg");?>"><?php echo $this->__("Sizes"); ?>
												   <?php endif; ?>
                                        </a>
                                </div>
                            </div>
                            
                        <?php endif; ?>
                    <?php endforeach; ?>
                <?php endif; ?>
            <?php endif; ?>
            <div class="action-box-bundle clearfix">
                <?php if ($isSalable): ?>
                    <button class="btn button button-primary addBasket"
                        <?php if (isset($haveSizes) && $haveSizes == true): ?><?php if ($salableCount > 1): ?>title="<?php echo $hlp->__("Choose size first"); ?>"
							        data-toggle="tooltip" <?php endif; ?>data-placemen="top"<?php endif; ?>
							        id="add-to-cart"
							        onclick="Mall.addToCart(<?php echo $_product->getId(); ?>, <?php echo !$_product->getStockItem()->getMinSaleQty() ? 1 : $_product->getStockItem()->getMinSaleQty(); ?>);return false;"><?php echo $this->__("add to cart"); 
                    ?></button>
                <?php endif; ?>
            </div>
        </div>
	<?php if (!$isSalable): ?>
                    <div class="temporary-absence-product-wrapper">
                        <span class="temporary-absence-product"><?php echo $hlp->__("Product temporary unavailable"); ?></span>
                    </div>
    <?php endif; ?>
    <div id="short-description-footer">
        <div id="same-collection-header">
        </div>
        <div id="same-product-list">
        </div>
    </div>

	<div id="box-social" class="row">
		<div class="col-lg-6 col-md-7 col-sm-7 col-xs-12">
			<div id="product-likeboxes">
				<div class="addLike-box" id="notadded-wishlist">
					<!-- placebo -->
					<span class="product-context-like-count" style="display: none"></span>
					<p>
						<a href="#" onclick="Mall.wishlist.addToWishlistFromProduct(<?php echo $_product->getEntityId(); ?>);return false;" class="addLike">
							<i class="i-unlike-wf">&nbsp;</i><span><?php echo $this->__("Add to favorites"); ?></span>
						</a>
					</p>
				</div>
			</div>
			<div class="question">
				<p>
					<i class="fa fa-comment-o">&nbsp;</i><span><a href="#" data-toggle="modal" data-target="#ask_question"><?php echo Mage::helper('wfwf')->__("Ask about product"); ?></a></span>
				</p>
			</div>
		</div>
		<div class="col-lg-6 col-md-5 col-sm-5 hidden-xs wrapper-addthis">
			<div class="followUs hidden-xs">
				<div class="addthis_sharing_toolbox"></div>
			</div>
		</div>
	</div>
</div>
<!-- SHORT DESCRIPTION -->
<?php /*
	<form action="<?php echo $this->getSubmitUrl($_product) ?>" method="post"
	      id="product_addtocart_form"<?php if ($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
		<?php echo $this->getBlockHtml('formkey') ?>
		<input type="hidden" name="product" value="<?php echo $_product->getId() ?>"/>
		<input type="hidden" name="related_product" id="related-products-field" value=""/>
		<div class="row">
			<div class="product-name col-lg-12">
				<h1 itemprop="name" <?php if($flag): ?>class="product-name-with-flag"<?php endif; ?>><?php echo $productName; ?></h1>
				<meta itemprop="sku" content="<?php echo $_product->getSku() ?>"/>
				<span class="average_note_client">
					<span class="note" data-number="5" data-score="<?php echo $this->getReviewsAvg(); ?>"></span> 
					<span>(<?php echo $this->getReviewsCount(); ?> <?php echo $this->getReviewsLabel(); ?>)</span>
				</span>
				<?php if($flag): ?>
				<div class="product-flag"><?php echo $flagLabel; ?></div>
				<?php endif; ?>
			</div>
		</div>
		<div class="row">
			<div class="col-lg-7 col-md-7">
				<?php if ($_product->getCanShowPrice() !== false):
					$currencyCode = Mage::app()->getStore()->getCurrentCurrencyCode();
					$currencySymbol = Mage::app()->getLocale()->currency($currencyCode)->getSymbol();;
					?>
					<div class="price-box-bundle">
						<div class="price-box">
							<p class="price" itemprop="offers" itemscope itemtype="http://schema.org/Offer">
								<?php if ($_product->getTypeId() == Mage_Catalog_Model_Product_Type::TYPE_CONFIGURABLE): ?>
									<meta itemprop="price" content="<?php echo round($_product->getFinalPrice(), 2); ?>"/>
								<?php endif; ?>

								<meta itemprop="priceCurrency" content="<?php echo $currencyCode; ?>"/>
								<meta itemprop="mpn" content="<?php echo $_product->getSku(); ?>"/>

								<?php if ($isSalable): ?>
									<meta itemprop="availability" content="http://schema.org/InStock"/>
								<?php else: ?>
									<meta itemprop="availability" content="http://schema.org/OutOfStock"/>
								<?php endif; ?>

								<meta itemprop="itemCondition" itemtype="http://schema.org/OfferItemCondition"
								      content="http://schema.org/NewCondition"/>
								<span class="price-label"><?php echo $this->__("price"); ?>:</span>
						<span class="old-price"><?php if ($_product->getTypeId() != Mage_Catalog_Model_Product_Type::TYPE_CONFIGURABLE && $_product->getStrikeoutPrice() != $_product->getFinalPrice()) : ?><?php echo str_replace(" ", "&nbsp;", Mage::helper('core')->currency($_product->getStrikeoutPrice(), true, false)); ?><?php endif; ?></span>
						<span class="price"><?php if ($_product->getTypeId() != Mage_Catalog_Model_Product_Type::TYPE_CONFIGURABLE): ?><span itemprop="price"><?php echo number_format($_product->getFinalPrice(), 2, ',', ' '); ?></span> <?php echo $currencySymbol; ?><?php endif; ?></span>
							</p>
						</div>
					</div>
				<?php endif; ?>
				<?php if ($_product->getTypeId() == Mage_Catalog_Model_Product_Type::TYPE_CONFIGURABLE) : ?>

					<!--    Meta tags-->
					<?php
					$childrenData = array();
					$childProducts = Mage::getModel('catalog/product_type_configurable')
						->getUsedProducts(null, $_product);
					foreach ($childProducts as $child) {
						$childrenData[$child->getId()] = $child->getSku();
					}

					$productViewTypeConfigurableBlock = Mage::getBlockSingleton('zolagocatalog/product_view_type_configurable');
					$config = $productViewTypeConfigurableBlock->getConfig();
					$basePrice = $config['basePrice'];
					if (isset($config['attributes']) & !empty($config['attributes'])):
						$attributes = $config['attributes'];
						foreach ($attributes as $attributeId => $attributeData):
							if ($attributeData['code'] == "size" && (isset($attributeData['options']) & !empty($attributeData['options']))):
								$options = $attributeData['options'];
								foreach ($options as $option):
									?>
									<span itemprop="offers" itemscope itemtype="http://schema.org/Offer">
                                        <meta itemprop="price" content="<?php echo round(($_product->getFinalPrice() + $option['price']), 2); ?>"/>
                                        <meta itemprop="priceCurrency" content="<?php echo $currencyCode; ?>"/>
                                        <meta itemprop="mpn" content="<?php echo $childrenData[$option['products'][0]]; ?>"/>
										<?php if ($option['is_salable']): ?>
											<meta itemprop="availability" content="http://schema.org/InStock"/>
										<?php else: ?>
											<meta itemprop="availability" content="http://schema.org/OutOfStock"/>
										<?php endif; ?>
										<meta itemprop="itemCondition" itemtype="http://schema.org/OfferItemCondition"
										      content="http://schema.org/NewCondition"/>
                                    </span>
									<?php
								endforeach;
							endif;
						endforeach;
					endif; ?>
					<!--    Meta tags-->
				<?php endif; ?>
				<div class="size-box-bundle" id="product-options">
					<?php if ($_product->getTypeId() == Mage_Catalog_Model_Product_Type::TYPE_CONFIGURABLE) : ?>
						<?php if (!empty($productAttrs)) : ?>
							<?php foreach ($productAttrs as $_attribute) : ?>
								<?php if (array_key_exists('attribute_code', $_attribute) && $_attribute['attribute_code'] == 'size') : ?>
									<?php $haveSizes = true; ?>
									<div class="size-box clearfix clr">
										<div class="size col-sm-12 col-md-12 col-xs-12">
											<span class="size-label col-sm-6 col-md-6 col-xs-12"><?php echo $this->__("Select size"); ?></span>
											<div class=" sizes-content form-group form-radio col-sm-6 col-md-5 col-xs-4">
												<br/>
												<a href="#" class="view-sizing underline pull-left" data-toggle="modal"
												   data-target="#tabelaRozmiarow"><?php if (!empty($sizeTableValue)) : ?><?php echo $this->__("Sizes"); ?><?php endif; ?></a>
											</div>
										</div>
									</div>
								<?php endif; ?>
							<?php endforeach; ?>
						<?php endif; ?>
					<?php endif; ?>
					<div class="action-box-bundle clearfix">
						<div id="product-likeboxes" style="display: inline-block;"></div>
						<?php if ($isSalable): ?>
							<button class="btn button button-primary ico addBasket"
							        <?php if (isset($haveSizes) && $haveSizes == true): ?><?php if ($salableCount > 1): ?>title="<?php echo $hlp->__("Choose size first"); ?>"
							        data-toggle="tooltip" <?php endif; ?>data-placemen="top"<?php endif; ?>
							        id="add-to-cart"
							        onclick="Mall.addToCart(<?php echo $_product->getId(); ?>, <?php echo !$_product->getStockItem()->getMinSaleQty() ? 1 : $_product->getStockItem()->getMinSaleQty(); ?>);return false;"><?php echo $this->__("add to cart"); ?></button>
						<?php else: ?>
							<div class="temporary-absence-product-wrapper">
								<span class="temporary-absence-product"><?php echo $hlp->__("Product temporary<br />unavailable");//?></span>
							</div>
						<?php endif; ?>
					</div>
				</div>
			</div>
			<div class="col-lg-5 col-md-5 hidden-sm hidden-xs">
				<?php
				$deliveryHeadline = trim($this->getStoreDeliveryHeadline());
				$returnHeadline = trim($this->getStoreReturnHeadline());
				?>
				<?php if($deliveryHeadline || $returnHeadline): ?>
				<div class="product-box-extra-info">
					<?php if($deliveryHeadline): ?>
						<div><i class="fa fa-truck"></i> <?php echo $deliveryHeadline; ?></div>
					<?php endif; ?>
					<?php if($returnHeadline): ?>
						<div><i class="fa fa-refresh"></i> <?php echo $returnHeadline; ?></div>
					<?php endif; ?>
				</div>
				<?php endif; ?>
				<?php echo $this->getChildHtml('catalog.product.related'); ?>
			</div>
		</div>
		<div class="row">
			<div class="col-lg-12">
				<p class="short-description visible-md hidden-xs">
					<?php echo $_helper->productAttribute($_product, nl2br($_product->getShortDescription()), 'short_description') ?>
					<a href="#description_product" class="scrollTo"><?php echo $hlp->__("see full description") ?></a>
				</p>
			</div>
		</div>
		<div class="row hidden-xs" id="product-additional-social">
			<div class="col-lg-7 product-additional-info">
				<a href="#" data-toggle="modal" data-target="#ask_question"><?php echo $hlp->__("Ask about product"); ?></a>
				<a href="#" data-toggle="modal" data-target="#terms_delivery"><?php echo $hlp->__("Delivery and return"); ?></a>
			</div>
			<div class="col-lg-5 followUsTop">
				<div class="addthis_sharing_toolbox"></div>
			</div>
		</div>
		<div class="row visible-xs visible-sm">
			<div class="col-sm-12 col-xs-12">
				<?php echo $this->getChildHtml('catalog.product.related'); ?>
			</div>
		</div>
	</form>
</div>
*/?>
<?php /* configurable price/stock data */ ?>
<?php if ($_product->getTypeId() == Mage_Catalog_Model_Product_Type::TYPE_CONFIGURABLE) : ?>

	<script type="text/javascript">
		var jsonConfig = <?php echo Mage::getBlockSingleton('zolagocatalog/product_view_type_configurable')->getJsonConfig(); ?>;
		var useSizeboxList =  1; 

		jsonConfig.useSizeboxList = useSizeboxList;
		Mall.product.productOptions(jsonConfig);
		Mall.product._current_product_type = "<?php echo Mage_Catalog_Model_Product_Type::TYPE_CONFIGURABLE; ?>";
	</script>
<?php endif; ?>
<script type="text/javascript">
	Mall.product._entity_id = <?php echo $_product->getEntityId(); ?>;
</script>