<?php 
$_helper = Mage::helper("ghapi");
$_ghApiVendorUser = $this->getGhApiVendorUser();
?>
<div class="widget box widget-closed">
	<div class="widget-header">
		<h4><i class="icon-plus"></i> <?php echo $_helper->__("Function %s","doLogin"); ?></h4>

		<div class="toolbar no-padding">
			<div class="btn-group">
				<span class="btn btn-xs widget-collapse"><i class="icon-angle-up"></i></span>
			</div>
		</div>
	</div>
	<div class="widget-content">		
    	<div class="form-group">
        	<label for="soap_login_vendor_id" class="col-md-3 control-label">
            	<?php echo $_helper->__("Partner ID"); ?>
            </label>
            <div class="col-md-9">
            	<input id="soap_login_vendor_id" name="ghapi_soap_vendor_id" value="<?php echo $this->getVendor()->getVendorId(); ?>" type="text" class="form-control" style="width:20%; min-width:50px;">
            </div>
        </div>
    	<div class="form-group">
        	<label for="soap_login_api_key" class="col-md-3 control-label">
            	<?php echo $_helper->__("API key"); ?>
            </label>
            <div class="col-md-9">
            	<input id="soap_login_api_key" name="ghapi_soap_api_key" value="<?php echo $_ghApiVendorUser->getApiKey(); ?>" type="text" class="form-control" size="10">
            </div>
        </div>
    	<div class="form-group">
        	<label for="soap_login_password" class="col-md-3 control-label">
            	<?php echo $_helper->__("API Password"); ?>
            </label>
            <div class="col-md-9">
            	<input id="soap_login_password" name="ghapi_soap_password" value="" type="password" class="form-control" size="10">
            </div>
        </div>
		<div class="form-group">
			<div class="col-md-3">
			</div>
			<div class="col-md-9">
				<button id="do_login_action" type="button" class="btn btn-primary"><?php echo $_helper->__('Send');?></button>
			</div>
		</div>
	</div>
</div>
