<?php $_helper = Mage::helper("ghapi"); ?>
<div class="widget box widget-closed">
	<div class="widget-header">
		<h4><i class="icon-plus"></i> <?php echo $_helper->__("Function %s","setOrderReservation"); ?></h4>

		<div class="toolbar no-padding">
			<div class="btn-group">
				<span class="btn btn-xs widget-collapse"><i class="icon-angle-up"></i></span>
			</div>
		</div>
	</div>
	<div class="widget-content" style="padding: 10px 15px">
        <div class="form-group">
            <label for="soap_reservation_token" class="col-md-3 control-label">
                <?php echo $_helper->__("Token"); ?>
            </label>
            <div class="col-xs-12 col-md-9 col-lg-6">
                <input id="soap_reservation_token" name="ghapi_soap_token" value="" type="text" class="form-control ghapi-token" size="10">
            </div>
        </div>
        <div class="form-group">
            <label for="soap_reservation_order_id" class="col-md-3 control-label">
                <?php echo $_helper->__("Order ID"); ?>
            </label>
            <div class="col-xs-12 col-md-9 col-lg-6">
                <input id="soap_reservation_order_id" name="ghapi_soap_order_id" value="" type="text" class="form-control" size="10">

            </div>
        </div>
        <div class="form-group">
            <label for="soap_shipment_reservation_status" class="col-md-3 control-label">
                <?php echo $_helper->__("Reservation status"); ?>
            </label>
            <div class="col-xs-12 col-md-9 col-lg-6">
                <select class="form-control" id="soap_shipment_reservation_status">
                    <option value="ok">ok</option>
                    <option value="problem">problem</option>
                </select>
            </div>
        </div>
        <div class="form-group">
            <label for="soap_reservation_message" class="col-md-3 control-label">
                <?php echo $_helper->__("Reservation message"); ?>
            </label>
            <div class="col-xs-12 col-md-9 col-lg-6">
                <input id="soap_reservation_message" name="ghapi_soap_reservation_message" value="" type="text" class="form-control" size="10">
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-3">
            </div>
            <div class="col-xs-12 col-md-9 col-lg-6">
                <button id="set_reservation_reservation_action" type="button" class="btn btn-primary"><?php echo $_helper->__('Send');?></button>
            </div>
        </div>
		<div id="soap_ajax_answer_reservation">
		</div>
	</div>
</div>
