<?php
/**
 * Author: Paweł Chyl <pawel.chyl@orba.pl>
 * Date: 19.05.14
 */
?>

<div class="footer-about ">
    <ul class="hidden-sm hidden-xs">
        <li><a href="#"><i class="fa fa-angle-right"></i> Pomoc</a></li>
        <li><a href="#"><i class="fa fa-angle-right"></i> Twoje konto</a></li>
        <li><a href="#"><i class="fa fa-angle-right"></i> Regulamin</a></li>
        <li><a href="#"><i class="fa fa-angle-right"></i> O nas</a></li>
    </ul>
    <?php echo $this->getChildHtml('footer.mobile.links'); ?>
</div>