<?php
$vendors = $this->getVendors();
$visibility = Mage::getSingleton('udqa/source')->setPath('visibility')->toOptionHash();
$session = Mage::getSingleton('customer/session');
/* @var $session Mage_Customer_Model_Session */
?>
<?php if($this->getProduct()->getUdropshipVendor()):?>
<form action="<?php echo $this->getFormAction(); ?>" id="question-form" method="post">
    <input type="hidden" name="question[product_id]" value="<?php echo $this->getProduct()->getId()?>" />
    <input type="hidden" name="question[vendor_id]" value="<?php echo $this->getProduct()->getUdropshipVendor()?>" />
    <input type="hidden" name="question[visibility]" value="0" />
    <div class="fieldset">
        <h2 class="legend"><?php echo $this->__('Ask Vendor A Question') ?></h2>
        <ul class="form-list">
			<?php if(!$session->isLoggedIn()):?>
            <li class="wide">
                <label for="customer_name" class="required"><em>*</em><?php echo $this->__('Your Name') ?></label>
                <div class="input-box">
                    <input type="text" name="question[customer_name]" id="customer_name" class="required-entry input-text" />
                </div>
            </li>
            <li class="wide">
                <label for="customer_email" class="required"><em>*</em><?php echo $this->__('Email') ?></label>
                <div class="input-box">
                    <input type="text" name="question[customer_email]" id="customer_email" class="validate-email required-entry input-text" />
                </div>
            </li>
			<?php else:?>
				<input type="hidden" name="question[customer_name]" value="<?php $this->escapeHtml($session->getCustomer()->getName()); ?>" />
				<input type="hidden" name="question[customer_email]" value="<?php $this->escapeHtml($session->getCustomer()->getEmail()); ?>" />
			<?php endif;?>
            <li class="wide">
                <label for="question_text" class="required"><em>*</em><?php echo $this->__('Question Text') ?></label>
                <div class="input-box">
                    <textarea name="question[question_text]" id="question_text" title="<?php echo $this->__('Question Text') ?>" class="required-entry input-text" cols="5" rows="3"></textarea>
                </div>
            </li>
        </ul>
    </div>
    <div class="buttons-set">
        <p class="required"><?php echo $this->__('* Required Fields') ?></p>
        <button type="submit" title="<?php echo $this->__('Submit') ?>" class="button"><span><span><?php echo $this->__('Submit') ?></span></span></button>
    </div>
</form>
<script type="text/javascript">
    //<![CDATA[
    var questionForm = new VarienForm('question-form', true);
    //]]>
</script>
<?php endif;?>
