<?php $hlp = Mage::helper('udropship');
$isViewCost = Mage::getSingleton('admin/session')->isAllowed('sales/order/actions/udpo_view_cost');
$qtyLast = !$isViewCost ? 'last' : '';
?>
<?php $_item = $this->getItem() ?>
<tr class="border">
    <td><?php echo $this->getColumnHtml($_item, 'name') ?></td>
    <?php if ($isViewCost): ?>
    <td><?php echo $hlp->displayPrices($this->getOrder(), $_item->getBaseCost()) ?></td>
    <?php endif ?>
    <td class="<?php echo $qtyLast?> ">
        <table cellspacing="0" class="qty-table">
            <tr>
                <td style="white-space:nowrap"><?php echo Mage::helper('udpo')->__('PO Sent') ?></td>
                <td><strong><?php echo $_item->getQty()*1 ?></strong></td>
            </tr>
            <?php if ((float) $_item->getQtyCanceled()): ?>
            <tr>
                <td style="white-space:nowrap"><?php echo Mage::helper('udpo')->__('PO Canceled') ?></td>
                <td><strong><?php echo $_item->getQtyCanceled()*1 ?></strong></td>
            </tr>
            <?php endif; ?>
            <?php if ((float) $_item->getQtyShipped()): ?>
            <tr>
                <td><?php echo Mage::helper('sales')->__('Shipped') ?></td>
                <td><strong><?php echo $_item->getQtyShipped()*1 ?></strong></td>
            </tr>
            <?php endif; ?>
        </table>
    </td>
    <?php if ($isViewCost): ?>
    <td class="last a-right"><?php echo $hlp->displayPrices($this->getOrder(), $_item->getBaseCost()*$_item->getQty()) ?></td>
    <?php endif ?>
</tr>
