<?php /** @var Zolago_Pos_Block_Dropship_Pos_Edit $this */ ?>
<?php $_helper = Mage::helper("zolagopos");?>
<?php $_pos = $this->getModel();?>
<div class="container">
	<!--=== Page Header ===-->
	<div class="page-heading row">
		<div class="col-lg-6">
			<h3>
			<?php if($_pos->getId()):?>
				<?php echo $_helper->__("Edit POS");?> <?php echo $this->escapeHtml($_pos->getName());?>
			<?php else:?>
				<?php echo $_helper->__("Create POS");?>
			<?php endif;?>
			</h3>
		</div>
		<div class="main-actions align-right col-md-6">
		
		</div>
	</div>
</div>
<div class="container">
	<form id="edit-pos" class="form-horizontal row-border" action="<?php echo $this->getForm()->getAction();?>" method="POST">
		<input type="hidden" name="pos_id" value="<?php echo $_pos->getId();?>"/>
		<?php echo $this->getLayout()->getBlock('formkey')->toHtml();?>
		<?php echo $this->getFormHtml();?>
		<div class="form-actions"> 
			<input type="submit" value="<?php echo $_helper->__("Save");?>" class="btn btn-primary pull-right"/> 
			<input type="button" class="btn pull-right" value="<?php echo $_helper->__("Cancel");?>" onclick="location.href='<?php echo $this->getUrl('*/*');?>'"/> 
		</div>
	</form>
</div>

<script type="text/javascript">
jQuery(function($){
	var form = $("#edit-pos");
	new Zolago.formIntegrator(form);
	form.validate({
		rules: {
			"phone": {
				required: true,
				"validate-telephone": true
			},
            "postcode": {
                required: true,
                postcodeWithReplace: true
            }
		},
        messages: {
            "postcode": {
                postcodeWithReplace: '<?php echo Mage::helper("zolagopos")->__("Zip code has not valid format (ex.12-345)"); ?>'
            }
        }
	});
});
</script>

<script type="text/javascript">
	
		var posControl = {
			init: function () {
				var regionSelect= $('region_id');
				var regionText = new Element("input", {"type": "text", "id": "region", "class": "input-text form-control", "name": "region", "value": "<?php echo $this->escapeHtml($this->getModel()->getRegion());?>"});
				regionText.hide();
				regionSelect.insert({before: regionText});

				var updater = new RegionUpdater('country_id', 'region', 'region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined);
				$("use_dhl").observe("change", function(e){
					posControl.enableDhl($F(e.target)=="1");
				});
				$("use_orbaups").observe("change", function(e){
					posControl.enableUps($F(e.target)=="1");
				});
				posControl.enableUps($F("use_orbaups")=="1");
				posControl.enableDhl($F("use_dhl")=="1");
			},
			enableDhl: function(state){
				if(!!state){
					$("dhl_login").up('.form-group').show();
					$("dhl_password").up('.form-group').show();
					$("dhl_account").up('.form-group').show();
					$("dhl_ecas").up('.form-group').show();
					$("dhl_terminal").up('.form-group').show();
					$("dhl_check_button").up('.form-group').show();
				}else{
					$("dhl_login").up('.form-group').hide();
					$("dhl_password").up('.form-group').hide();
					$("dhl_account").up('.form-group').hide();
					$("dhl_ecas").up('.form-group').hide();
					$("dhl_terminal").up('.form-group').hide();
					$("dhl_check_button").up('.form-group').hide();
				}
			},
			enableUps: function(state){
				if(!!state){
					$("orbaups_login").up('.form-group').show();
					$("orbaups_password").up('.form-group').show();
					$("orbaups_account").up('.form-group').show();
				}else{
					$("orbaups_login").up('.form-group').hide();
					$("orbaups_password").up('.form-group').hide();
					$("orbaups_account").up('.form-group').hide();
				}
			}
		};
		document.observe("dom:loaded", function() {
			posControl.init();
		});

		jQuery(document).ready(function () {

			var isAvailableAsPickupPoint = jQuery('#is_available_as_pickup_point');
			isAvailableAsPickupPoint.bootstrapSwitch({
				onText: '<?php echo $_helper->__("Yes");?>',
				offText: '<?php echo $_helper->__("No");?>'
			});
			if (isAvailableAsPickupPoint.val() == 1) {
				jQuery('#is_available_as_pickup_point').bootstrapSwitch('state', true);
			} else {
				jQuery('#is_available_as_pickup_point').bootstrapSwitch('state', false);
			}
			isAvailableAsPickupPoint.on('switchChange.bootstrapSwitch', function () {
				var isAvailableAsPickupPointState = jQuery(this).bootstrapSwitch('state');

				if (isAvailableAsPickupPointState) {
					jQuery('#is_available_as_pickup_point').val(1);
				} else {
					jQuery('#is_available_as_pickup_point').val(0);
				}
				event.preventDefault();
			}).change();


			var showPosOnMap = jQuery('#show_on_map');
			showPosOnMap.bootstrapSwitch({
				onText: '<?php echo $_helper->__("Yes");?>',
				offText: '<?php echo $_helper->__("No");?>'
			});
			if (showPosOnMap.val() == 1) {
				jQuery('#show_on_map').bootstrapSwitch('state', true);
				jQuery(".map-fields").show();
			} else {
				jQuery('#show_on_map').bootstrapSwitch('state', false);
				jQuery(".map-fields").hide();
			}

			showPosOnMap.on('switchChange.bootstrapSwitch', function () {
				var showOnMapFields = jQuery(this).bootstrapSwitch('state');

				if (showOnMapFields) {
					jQuery(".map-fields").slideDown();
					jQuery('#show_on_map').val(1);
				} else {
					jQuery(".map-fields").slideUp();
					jQuery('#show_on_map').val(0);
				}
				event.preventDefault();
			});




			// Trick for htmlspecialchars_decode
			var mapTimeOpened = jQuery('<textarea>').html(jQuery('#map_time_opened').text()).text();
			jQuery('#map_time_opened').text(mapTimeOpened);
		});
    Dhl.init('<?php echo Mage::getUrl('*/*/check_dhl',array('pos_id' => $this->getRequest()->getParam('pos_id')));?>');
    jQuery('.disable_dhl').change(function() {
        Dhl.setInfo('orange','<?php echo Mage::helper('orbashipping')->__('Please save changed settings.')?>');
        Dhl.disable();
    });
</script>