<?php $helper = Mage::helper('zolagopos'); ?>
<?php $vendor = $this->getVendor(); ?>
<?php $posList = $this->getPosList(); ?>
<br/>
    <div class="row">
        <div class="col-md-12">
            <form id="pos_settings" class="form-horizontal" method="post" action="/udropship/pos/settingsSave">
                <input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey(); ?>">
                <div class="widget box">
                    <div class="widget-header">
                        <h4><?php echo $helper->__("Pos settings");?></h4>
                    </div>
                    <div class="widget-content fiters">
                        <div>
                            <div class="form-group">
                                <label for="problem_pos_id" class="col-md-3 control-label">
                                    <?php echo $helper->__("Pos for problematic orders");?>
                                </label>
                                <div class="col-md-9">
                                    <select name="problem_pos_id" id="problem_pos_id" class="form-control">
                                        <option value="0"><?php echo $helper->__('-- choose POS --');?></option>
                                        <?php foreach ($posList as $pos): ?>
                                            <option value="<?php echo $pos->getPosId();?>"<?php if ($vendor->getProblemPosId() == $pos->getPosId()):?> selected<?php endif;?>><?php echo $pos->getName(); ?></option>
                                        <?php endforeach; ?>
                                    </select>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="form-actions">
                    <button type="reset" id="filter_reset" class="btn pull-right">
                        <span><span><?php echo $this->__('Cancel');?></span></span>
                    </button>
                    <button type="submit" id="filter_submit" class="btn btn-primary pull-right">
                        <span><span><?php echo $this->__('Save');?></span></span>
                    </button>
                </div>
            </form>
        </div>
    </div>

