<?php
/**
 * Author: Paweł Chyl <pawel.chyl@orba.pl>
 * Date: 25.04.14
 */
/** @var Zolago_Modago_Block_Home_Slider $this */
?>
<section id="recently-viewed" class="bg-w recently-viewed-cls bottom col-xs-12">
    <div class="container-fluid">
        <div class="recently-viewed">
            <h3 class="title-section-recently-viewed"><span><?php echo $this->__("Your Recently Viewed"); ?>:</span></h3>
            <div id="rwd-recently-viewed" class="rwdCarousel">
                <div class="rwd-carousel rwd-theme">

                </div>
            </div>
        </div>
    </div>
</section>