<?php /* @var $this Zolago_Modago_Block_Po_Email_Summary */ ?>
<?php $_helper = Mage::helper("zolagomodago");?>
<?php $_po = $this->getPo();?>

<?php if($this->getItems()): ?>
<table cellpadding="5" style="font-family:'Arial','Helvetica',sans-serif;min-width:100%;margin:0;padding:0" class="productsTable">
	<thead style="font-size: 13px; text-align: left">
	<tr>
		<th colspan="2" align="left" style="text-align:left" class="productColumn">Produkt</th>
		<th align="left" style="text-align:left" class="valueColumn">Wartość</th>
	</tr>
	</thead>
	<tbody style="font-size: 15px">
		<?php foreach($this->getItems() as $_item):?>
			<?php echo $this->renderItem($_item);?>
		<?php endforeach;?>

		<?php $_shippingCost = (float)$_po->getShippingAmountIncl();?>
		<?php $_discount = (float)$_po->getSubtotalDiscount();?>
		<tr>
			<td colspan="2" style="text-align:right;"><?php echo $_helper->__("Shipping cost");?>:</td>
			<td style="text-align:right;">
				<strong>
					<?php echo Mage::helper("core")->formatPrice($_shippingCost, false);?>
				</strong>
			</td>
		</tr>
		<?php if($_discount>0):?>
			<tr>
				<td colspan="2" style="text-align:right;"><?php echo $_helper->__("Discount");?>:</td>
				<td style="text-align:right;">
					<strong>
						<?php echo Mage::helper("core")->formatPrice($_discount * -1, false);?>
					</strong>
				</td>
			</tr>
		<?php endif;?>
		<tr>
			<td colspan="2" style="text-align:right;"><?php echo $_helper->__("Total");?>:</td>
			<td style="text-align:right;">
				<strong>
					<?php echo Mage::helper("core")->formatPrice($_po->getGrandTotalInclTax(), false);?>
				</strong>
			</td>
		</tr>
	</tbody>
</table>
<?php endif;?>