<?php
/**
 * user: Andrzej Spólnicki
 */
?>

<div id="content" class="container-fluid">
    <div id="checkout" class="row">

        <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('checkout-thank-you-page')->toHtml(); ?>

        <div id="content-main" class="col-md-10 col-md-push-1 col-sm-12 section">
            <section class="main bg-w">
                <header class="title-section">
                    <h2 class="open number_order"><?php echo $this->__('ORDER NUMBER:') ?><?php echo $this->escapeHtml($this->getOrderId()) ?></span>
                    </h2>
                </header>
            </section>
        </div>
    </div>
</div>

