<?php
$bannerHelper = Mage::helper('zolagobanner');
$bannerTypes = $bannerHelper->getBannersConfiguration();
$vendor = Mage::getSingleton('udropship/session')->getVendor();

$campaigns = $this->getCampaigns();
//Zend_Debug::dump($campaigns);
?>
<div class="container">
    <div class="page-heading row">
        <div class="col-lg-6">
            <h3><span data-source="category">Women's clothing</span></h3>
        </div>
    </div>
    <?php if (!empty($bannerTypes)): ?>
        <?php foreach ($bannerTypes as $bannerType): ?>
            <?php if (!empty($bannerType->position_count)): ?>
            <div class="row">
                <!--=== Example Box ===-->
                <div class="col-md-12">
                    <div class="widget box">
                        <div class="widget-header">
                            <h4><i class="icon-pin-flag"></i> <span data-source="banner-type"><?php echo $bannerType->title; ?></span></h4>
                            <div class="toolbar no-padding"> <div class="btn-group"> <span class="btn btn-xs widget-collapse"><i class="icon-angle-down"></i></span> </div> </div>
                        </div>
                        <div class="widget-content banner-type" style="display: block;">

                                <?php for($i=1; $i<= $bannerType->position_count; $i++): ?>
                                    <div class="row">
                                        <div class="col-md-6">
                                            <?php echo $bannerType->position_label; ?> <span data-source="position"><?php echo $i; ?></span>
                                        </div>
                                        <div class="col-md-6 align-right">
                                            drag to change order - priority

                                            <a href="#" class="btn btn-primary"
                                               data-toggle="modal"
                                               data-target="#basicModal"><i class="icon-plus-sign"></i><span><span> Add</span></span></a>
<!--                                            --><?php //$titleCode = Mage::getSingleton('zolagobanner/banner_type')->getTypCodeByTitle($bannerType->title); echo $titleCode;?>
<!--                                            --><?php //if (isset($campaigns[$titleCode]) && !empty($campaigns[$titleCode])): ?>
<!--                                                --><?php //foreach ($campaigns[$titleCode] as $campaign): ?>
<!--                                                    <div class="col-md-6">-->
<!--                                                        <h4>--><?php //echo $campaign->name; ?><!--</h4>-->
<!--                                                        <h4>--><?php //echo $vendor->getName(); ?><!--</h4>-->
<!--                                                        --><?php //Zend_Debug::dump($campaign->getData()); ?>
<!--                                                    </div>-->
<!--                                                --><?php //endforeach; ?>
<!--                                            --><?php //endif; ?>
                                        </div>
                                        <br /><br /><br />
                                    </div>
                                <?php endfor; ?>

                        </div>
                    </div>
                </div> <!-- /.col-md-12 -->
                <!-- /Example Box -->
            </div>
            <?php endif; ?>
        <?php endforeach; ?>
    <?php endif; ?>
</div>


<div class="modal fade" id="basicModal" tabindex="-1" role="dialog" aria-labelledby="basicModal" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">x</button>
                <h4 class="modal-title" id="myModalLabel">
                    Add new creative for:
                    <span data-val="category">Women's clothes</span>
                    - <span data-val="banner-type">Slider</span> - <span data-val="position">Slot 2</span>
                </h4>
            </div>
            <div class="modal-body row">
                <div class="col-md-6">
                    <h3>Choose campaign: </h3>
                    <select name="campaign">
                        <option value="1">1</option>
                    </select>

                    <h3>Choose creative: </h3>
                    <select name="banner">
                        <option value="1">1</option>
                    </select>

                    <h3>Set priority: </h3>
                    <select name="priority">
                        <option value="1">1</option>
                    </select>
                </div>
                <div class="col-md-6">
                    <h3>Preview: </h3>
                </div>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                <button type="button" class="btn btn-primary">Save</button>
            </div>
        </div>
    </div>
</div>
