<?php $_helper = Mage::helper("zolagocampaign");?>
<?php
$bannerHelper = Mage::helper('zolagobanner');
$bannerTypes = $bannerHelper->getBannersConfiguration();
$vendor = Mage::getSingleton('udropship/session')->getVendor();
$vendorName = $vendor->getVendorName();

$campaigns = Mage::helper('core')->jsonEncode($this->getCampaigns());

$placements = $this->getCategoryPlacements();
?>

<div class="container">
<form name="campaign-position" method="POST" action="/campaign/placement_category/save">
    <input type="text" name="category" value="<?php echo $this->getCategoryId(); ?>" />
    <div class="page-heading row">
        <div class="col-lg-6">
            <h3><span data-source="category"><?php echo $this->getCategoryName(); ?></span></h3>
        </div>
        <div class="col-lg-6">
            <h3><span></span></h3>
            <div class="pull-right">
                <button id="save-positions" class="btn btn-primary" type="button"><?php echo $_helper->__('Save'); ?></button>
            </div>
        </div>
    </div>
    <?php if (!empty($bannerTypes)): ?>
        <?php foreach ($bannerTypes as $bannerType): ?>
            <?php if (!empty($bannerType->position_count)): ?>
            <div class="row">
                <!--=== Example Box ===-->
                <div class="col-md-12">
                    <div class="widget box">
                        <div class="widget-header">
                            <h4><i class="icon-pin-flag"></i> <span data-source="banner-type"><?php echo $bannerType->title; ?></span></h4>

                            <?php $titleCode = Mage::getSingleton('zolagobanner/banner_type')->getTypCodeByTitle($bannerType->title); ?>


                            <div class="toolbar no-padding"> <div class="btn-group"> <span class="btn btn-xs widget-collapse"><i class="icon-angle-down"></i></span> </div> </div>
                        </div>
                        <div class="widget-content banner-type" style="display: block;">
                            <span data-source="banner-type-code" class="hidden"><?php echo $titleCode; ?></span>
                                <?php for($i=1; $i<= $bannerType->position_count; $i++): ?>
                                    <div class="banner-positions">
                                        <div class="col-md-6">
                                            <span data-source="position"><?php echo $bannerType->position_label; ?> <?php echo $i; ?></span>
                                            <span data-source="position-n" class="hidden"><?php echo $i; ?></span>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="align-right">
                                                <?php echo $_helper->__('Drag to change priority'); ?>

                                                <a href="#" class="btn btn-primary add-new"
                                                   data-toggle="modal"
                                                   data-target="#basicModal"><i class="icon-plus-sign"></i>
                                                    <span><span> <?php echo $_helper->__('Add'); ?></span></span>
                                                </a>
                                            </div>
                                        </div>
                                        <ul class="col-md-12 campaign-list">
                                            <?php if (!empty($placements) && isset($placements[$titleCode])): ?>
                                                <?php foreach ($placements[$titleCode] as $placement): ?>
                                                    <?php if($i == $placement['position']): ?>
                                                        <li class="col-md-3 banner-item">
                                                            <img src="/skin/frontend/modago/default/images/logo_header_lightbox.png">

                                                            <div class="row">
                                                                <div class="col-md-6">

                                                                    <input type="text" name="placement_id[]" value="<?php echo $placement['placement_id']; ?>">
                                                                    <input type="text" name="campaign_id[]" value="<?php echo $placement['campaign_id']; ?>">
                                                                    <input type="text" name="banner_id[]" value="<?php echo $placement['banner_id']; ?>">
                                                                    <input type="text" name="type[]" value="<?php echo $placement['type']; ?>">
                                                                    <input type="text" name="position[]" value="<?php echo $placement['position']; ?>">
                                                                    <input type="text" name="priority[]" value="<?php echo $placement['priority']; ?>">
                                                                    <h5>
                                                                        <span data-edit-source="campaign_name">
                                                                            <?php echo $placement['campaign_name']; ?>
                                                                        </span>
                                                                    </h5>
                                                                    <h5>
                                                                        <span data-edit-source="banner_name">
                                                                            <?php echo $placement['banner_name']; ?>
                                                                        </span>
                                                                    </h5>
                                                                    <h5><?php echo $vendorName; ?></h5>
                                                                </div>
                                                                <div class="col-md-4">
                                                                    <a href="#" class="btn btn-info"
                                                                       data-toggle="modal"
                                                                       data-target="#editModal">
                                                                        <span class="glyphicon glyphicon-pencil"></span>
                                                                        <span><span> <?php echo $_helper->__('Edit'); ?></span></span>
                                                                    </a>
                                                                </div>
                                                            </div>
                                                            <div class="dates">
                                                                <i class="icon-warning-sign"></i>
                                                                <span data-edit-source="campaign_date_from">
                                                                    <?php echo $placement['campaign_date_from']; ?>
                                                                </span>
                                                                <span data-edit-source="campaign_date_dash">
                                                                    <?php if (!empty($placement['campaign_date_from']) && !empty($placement['campaign_date_to'])): ?>-<?php endif; ?>
                                                                </span>
                                                                <span data-edit-source="campaign_date_to">
                                                                    <?php echo $placement['campaign_date_to']; ?>
                                                                </span>
                                                            </div>
                                                        </li>
                                                        <?php endif; ?>
                                                <?php endforeach; ?>
                                            <?php endif; ?>
                                        </ul>
                                        <br /><br /><br />
                                    </div>
                                <?php endfor; ?>

                        </div>
                    </div>
                </div> <!-- /.col-md-12 -->
                <!-- /Example Box -->
            </div>
            <?php endif; ?>
        <?php endforeach; ?>
    <?php endif; ?>
</form>
</div>


<div class="modal fade" id="basicModal" tabindex="-1" role="dialog" aria-labelledby="basicModal" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">x</button>
                <h4 class="modal-title" id="myModalLabel">
                    <?php echo $_helper->__('Add new creative for'); ?>:
                    <span data-val="category"></span>
                    - <span data-val="banner-type"></span> - <span data-val="position"></span>
                </h4>
            </div>
            <div class="modal-body row">
                <div class="col-md-8">
                    <div class="row">
                        <label><?php echo $_helper->__('Choose campaign'); ?>: </label>
                        <select name="campaign"></select>
                    </div>
                    <div class="row">
                        <label><?php echo $_helper->__('Choose creative'); ?>: </label>
                        <select name="banner"></select>
                    </div>
                    <div class="row">
<!--                        <label>Set priority: </label>-->
<!--                        <select name="priority">-->
<!--                            <option value="0">0</option>-->
<!--                            <option value="1">1</option>-->
<!--                            <option value="2">2</option>-->
<!--                            <option value="3">3</option>-->
<!--                        </select>-->
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="row">
                        <label><?php $_helper->__('Preview'); ?>: </label>
                    </div>
                </div>
                <div class="hidden">
                    <span data-val="campaign-date-from"></span>
                    <span data-val="campaign-date-to"></span>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal" id="add-placement-dismiss">
                    <?php echo $_helper->__('Cancel'); ?>
                </button>
                <button type="button" class="btn btn-primary" id="add-placement">
                    <?php echo $_helper->__('Save'); ?>
                </button>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="editModal" tabindex="-1" role="dialog" aria-labelledby="editModal" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">x</button>
                <h4 class="modal-title" id="myModalLabel">
                    <?php echo $_helper->__('Edit creative'); ?>
                </h4>
            </div>
            <div class="modal-body row">
                <div class="col-md-12">
                    <img src="/skin/frontend/modago/default/images/banner1.jpg" />
                </div>
                <div class="col-md-12">
                    <div class="row">
                        <label><?php echo $_helper->__('Campaign'); ?>: </label>
                        <span data-edit-val="campaign_name"></span>
                    </div>
                    <div class="row">
                        <label><?php echo $_helper->__('Creative'); ?>: </label>
                        <span data-edit-val="banner_name"></span>
                    </div>
                    <div class="row">
                        <label><?php echo $_helper->__('Campaign running time'); ?>: </label>
                        <span data-edit-val="dates"></span>
                    </div>
                    <div class="row">
                        <span class="glyphicon-ban-circle"></span> Campaign has ended. Creative is not active.
                        To restart., <a data-edit-val="link-edit" href="" target="_blank"><?php echo $_helper->__('go to campaign'); ?></a>.
                    </div>
                    <div class="row">
<!--                        <label>Change priority: </label>-->
<!--                        <select name="priority">-->
<!--                            <option value="0">0</option>-->
<!--                            <option value="1">1</option>-->
<!--                            <option value="2">2</option>-->
<!--                            <option value="3">3</option>-->
<!--                        </select>-->
                    </div>
                    <div class="row">
                        <a data-edit-val="link-delete" href="">
                            <?php echo $_helper->__('Delete this creative from the placement'); ?>
                        </a>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" id="save-edit" data-dismiss="modal">
                    <?php echo $_helper->__('Cancel'); ?>
                </button>
                <button type="button" class="btn btn-primary">
                    <?php echo $_helper->__('Save'); ?>
                </button>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    jQuery(function ($) {
        $(document).on('mouseover', '.banner-type .campaign-list', function () {
            $(this).sortable();
            $(this).disableSelection();
        })
        var compaigns = '<?php echo $campaigns; ?>';
        var compaignsObj = jQuery.parseJSON(compaigns);

        $(document).on('change', 'select[name=campaign]', function () {
            var campaign = $(this).val();
            getCampaignCreations(campaign, $('select[name=banner]'));
            getCampaignAdditionalInfo(campaign);
        })

        $("#basicModal").on("show.bs.modal", function (e) {
            var category = $('[data-source="category"]').html();
            var bannerType = $(e.relatedTarget).parents('.widget').find('[data-source="banner-type"]').html();
            var bannerTypeCode = $(e.relatedTarget).parents('.widget').find('[data-source="banner-type-code"]').html();
            var position = $(e.relatedTarget).parents('.widget .banner-positions').find('[data-source="position"]').html();

            //var compaignsObj = jQuery.parseJSON(compaigns);

            var options = '<option value="0">      </option>';
            if ($.type(compaignsObj[bannerTypeCode]) !== "undefined") {
                compaignsObj[bannerTypeCode].each(function (i, val) {
                    options += '<option value="' + i.campaign_id + '">' + i.name + '</option>';
                })
            }

            $(this).find('[name=campaign]').html(options);
            $(this).find('[data-val="category"]').html(category);
            $(this).find('[data-val="banner-type"]').html(bannerType);
            $(this).find('[data-val="position"]').html(position);


        });
        $('.add-new').click(function(){
            var position = $(this).closest('.banner-positions')
                .find('[data-source="position-n"]').text();
            var typeCode = $(this).closest('.banner-type').find('[data-source="banner-type-code"]').text();
            $(this).closest('.banner-positions')
                .find('.campaign-list')
                .append("<div data-targ='add' data-position='"+position+"' data-banner-type='"+typeCode+"'></div>");

        })
        $('#add-placement-dismiss[data-dismiss="modal"]').click(function(){
            $("[data-targ='add']").remove();
            clearOptions();
        })

        $('#save-positions').click(function(){
            setPriority();
            $('form[name=campaign-position]').submit();
            return false;
        })

        function setPriority(){
            $('form[name=campaign-position] .banner-positions .campaign-list').each(function(i,value){
                $(value).find('.banner-item').each(function(v,item){
                    $(item).find('[name="priority[]"]').val(parseInt($(item).index())+1)
                });

            })
        }

        $("#basicModal").on("hide.bs.modal", function (e) {
            $(this).find('[data-val="category"]').html('');
            $(this).find('[data-val="banner-type"]').html('');
            $(this).find('[data-val="position"]').html('');

        });
        $('#basicModal #add-placement').click(function () {
            var modal = $("#basicModal");
            var campaign = modal.find('[name=campaign] option:selected').val();
            var campaignName = modal.find('[name=campaign] option:selected').text();
            var banner = modal.find('[name=banner] option:selected').val();
            var bannerName = modal.find('[name=banner] option:selected').text();
            var position = modal.find('[name=priority] option:selected').val();


            var bannerType = $('[data-targ="add"]').data('banner-type');
            var pos = $('[data-targ="add"]').data('position');

            var dateFrom = modal.find('[data-val="campaign-date-from"]').text();
            var dateTo = modal.find('[data-val="campaign-date-to"]').text();

            if (parseInt(banner) > 0) {
                var edit = '<?php echo $this->__('Edit'); ?>';
                var vendorName = '<?php echo $vendorName; ?>';
                var dates = '';
                if (dateFrom.length > 0 && dateTo.length > 0) {
                    dates = dateFrom + ' - ' + dateTo;
                }
                var campaignBlock = '<li class="col-md-3 banner-item">' +
                    '<img src="/skin/frontend/modago/default/images/logo_header_lightbox.png" />' +
                    '<div class="row">' +
                    '<div class= "col-md-6" >' +
                    '<input type="text" name="placement_id[]" value="0">' +
                    '<input type="text" name="campaign_id[]" value="'+campaign+'">' +
                    '<input type="text" name="banner_id[]" value="'+banner+'">' +
                    '<input type="text" name="type[]" value="'+bannerType+'">' +
                    '<input type="text" name="position[]" value="'+pos+'">' +
                    '<input type="text" name="priority[]" value="0">' +
                    '<h5>' + campaignName + '</h5>' +
                    '<h5>' + bannerName + '</h5>' +
                    '<h5>' + vendorName + '</h5>' +
                    '</div>' +
                    '<div class="col-md-4">' +
                    '<a href="#" class="btn btn-info" data-toggle="modal" data-target="#editModal">' +
                    '<span class="glyphicon glyphicon-pencil"></span>' +
                    '<span><span> ' + edit + '</span></span>' +
                    '</a>' +
                    '</div>' +
                    '</div>' +
                    '<div class="dates">' +
                    '<i class="icon-warning-sign"></i> ' + dates +
                    '</div>' +
                    '</li>';

                $('[data-targ="add"]').replaceWith(campaignBlock);
            } else {
                $('[data-targ="add"]').remove();
            }
            clearOptions();

        })


        //edit
        $("#editModal").on("show.bs.modal", function (e) {
            //get data
            var nameSpace = $(e.relatedTarget).closest('.banner-item');
            var campaign = nameSpace.find('[name="campaign_id[]"]').val();
            var campaignName = nameSpace.find('[data-edit-source="campaign_name"]').text();

            var bannerName = nameSpace.find('[data-edit-source="banner_name"]').text();
            var banner = nameSpace.find('[name="banner_id[]"]').val();

            var vendorName = '<?php echo $vendorName; ?>';

            var campaignDateFrom = nameSpace.find('[data-edit-source="campaign_date_from"]').text();
            var campaignDateDash = nameSpace.find('[data-edit-source="campaign_date_dash"]').text();
            var campaignDateTo = nameSpace.find('[data-edit-source="campaign_date_to"]').text();

            var placementId = nameSpace.find('[name="placement_id[]"]').val();

            var dates = [campaignDateFrom, campaignDateDash, campaignDateTo].join(" ");
            //set data to modal
            var modal = $(this);
            modal.find('[data-edit-val="campaign_name"]').text(campaignName);
            modal.find('[data-edit-val="banner_name"]').text(bannerName);
            modal.find('[data-edit-val="dates"]').text(dates);

            modal.find('[data-edit-val="link-edit"]').attr("href", "/campaign/vendor/edit/id/" + campaign);

            if(parseInt(placementId) > 0){
                modal.find('[data-edit-val="link-delete"]').attr("href", "/campaign/placement_category/remove/id/" + placementId);
            }




        });

        $("#editModal").find('[data-edit-val="link-delete"]').click(function (e) {
            e.preventDefault();
            var href = $(this).attr("href");

            console.log(href);
            if(href.length > 0){
                //remove from db
                console.log('remove from db');
            } else {
                //remove added html
                console.log('remove added html');
            }


        })

        function clearOptions() {
            var modal = $("#basicModal");
            modal.find('select[name="campaign"]').html('');
            modal.find('select[name="banner"]').html('');
            modal.find('select[name="priority"]').html('');
            modal.modal('hide');
        }

        /**
         *
         * @param campaign
         * @param optionsContainer
         */
        function getCampaignCreations(campaign, optionsContainer) {
            var loading = '<?php echo $_helper->__("Loading..."); ?>';
            optionsContainer.html('<option value="0">'+loading+'</option>');
            campaign = parseInt(campaign);
            if(campaign > 0){
                $.ajax({
                    url : "/campaign/placement_category/getCampaignCreations",
                    data: {campaign : campaign},
                    success: function(result){
                        var banners = jQuery.parseJSON(result);
                        var bannerOptions = '<option value="0">      </option>';
                        $.each(banners, function(k,value){
                            bannerOptions += '<option value="' + value.banner_id + '">' + value.name + '</option>';
                        })

                        optionsContainer.html(bannerOptions);
                    }
                })
            }
        }

        function getCampaignAdditionalInfo(campaign){
            campaign = parseInt(campaign);
            if(campaign > 0){
                $.ajax({
                    url : "/campaign/vendor/getCompaignData",
                    data: {id : campaign},
                    success: function(result){
                        var data = jQuery.parseJSON(result);
                        $("#basicModal").find('[data-val="campaign-date-from"]').html(data.date_from);
                        $("#basicModal").find('[data-val="campaign-date-to"]').html(data.date_to);
                    }
                })
            }
        }
    })
</script>