<?php
/** @var Error_Processor $this */
?>
<!DOCTYPE html>
<html>
    <head>
        <title>Nastąpił błąd podczas przetwarzania żądania</title>
        <base href="<?php echo $this->getSkinUrl() ?>"/>
        <meta charset="utf-8"/>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
        <meta name="viewport" content="user-scalable=no, width=device-width"/>
        <meta name="description" content=""/>
        <meta name="keywords" content=""/>
        <meta name="robots" content="*"/>
        <link rel="stylesheet" href="css/styles.css" type="text/css"/>
        <link rel="icon" href="images/favicon.ico" type="image/x-icon"/>
        <link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon"/>
        <!--[if lt IE 9]>
        <script src="js/html5shiv.min.js"></script>
        <script src="js/respond.min.js'"></script>
        <![endif]-->
    </head>
    <body>
        <div>
            <header id="header">
                <div id="header_top_block_center">
                    <div id="logo">
                        <a href="<?php echo $this->getLogoUrl(); ?>" class="logo">
                            <img src="<?php echo $this->getLogoImageUrl(); ?>">
                        </a>
                    </div>
                </div>
            </header>
            <div class="main-container">
                <div class="main">
                    <?php require_once $contentTemplate; ?>
                </div>
            </div>
        </div>
    </body>
</html>
