<?php /* @var $this Zolago_Campaign_Varien_Data_Form_Element_Categorytree  */ ?>

<?php $_helper = Mage::helper("zolagocampaign");?>

<?php $secureBaseUrl = Mage::getUrl('',array('_secure'=>true)); ?>


<link rel="stylesheet" type="text/css" href="<?php echo $secureBaseUrl; ?>js/jqwidgets/styles/jqx.base.css"/>
<link rel="stylesheet" type="text/css" href="<?php echo $secureBaseUrl; ?>js/jqwidgets/styles/jqx.arctic.css"/>

<script type="application/javascript" src="<?php echo $secureBaseUrl; ?>js/jqwidgets/jqxcore.js"></script>
<script type="application/javascript" src="<?php echo $secureBaseUrl; ?>js/jqwidgets/jqxbuttons.js"></script>
<script type="application/javascript" src="<?php echo $secureBaseUrl; ?>js/jqwidgets/jqxscrollbar.js"></script>
<script type="application/javascript" src="<?php echo $secureBaseUrl; ?>js/jqwidgets/jqxpanel.js"></script>
<script type="application/javascript" src="<?php echo $secureBaseUrl; ?>js/jqwidgets/jqxtree.js"></script>
<script type="application/javascript" src="<?php echo $secureBaseUrl; ?>js/jqwidgets/jqxcheckbox.js"></script>


<input id="<?php echo $this->getFieldName(); ?>" name="<?php echo $this->getFieldName(); ?>"
       value="<?php echo $this->getFieldValue(); ?>" class="form-control col-md-2" style="width: 152px;" type="text">
<label style="margin: 8px; cursor: pointer;">
    <span data-toggle="modal" data-target="#browseCategory" title="<?php echo $_helper->__("Select Category");?>">
        <i class="icon-edit"></i>&nbsp;
    </span>
</label>

<script type="application/javascript" src="<?php echo $secureBaseUrl; ?>js/gh/campaign/category_tree.js"></script>