<?php /* @var $this Zolago_Modago_Block_Checkout_Cart_Sidebar_Shipping_Map */ ?>


<?php $populateData = $this->getPopulateData(); ?>

<?php $populateMapData = $this->getPopulateMapData(); ?>

<script type="text/javascript">
    var mapData = '<?php echo $populateMapData; ?>';
    
</script>
<?php foreach ($populateData as $lockerName => $lockerInfo): ?>
    <p>
        <a data-select-shipping-method-trigger="1"
           data-carrier-pointcode="<?php echo $lockerName; ?>"
           data-carrier-additional="<?php echo $lockerInfo; ?>" href="">
            <?php echo $lockerName; ?>
        </a>
    </p>
<?php endforeach; ?>

    <div id="map-container" style="width: 300px; height: 300px;" class="col-md-7 col-sm-12 col-xs-12">
        <div id="map"></div>
    </div>