<?php /* @var $this Zolago_Modago_Block_Checkout_Cart_Sidebar_Shipping_Map */ ?>
<p>
    <a data-select-shipping-method-trigger="1" data-carrier-pointcode="ALK01A" data-carrier-additional="Słowackiego 131<br>87-700 Aleksandrów Kujawski<br>(PM przy biurze usług ubezpieczeniowych , po lewej stronie od wejścia.)" href="">
        ALK01A</a>
</p>
<p>
    <a data-select-shipping-method-trigger="1" data-carrier-pointcode="WAW193" data-carrier-additional="Barkocińska 6<br>03-543 Warszawa<br>(Przy markecie Biedronka)" href="">
        WAW193</a>
</p>