<?php /* @var $this Zolago_Modago_Block_Checkout_Cart_Sidebar_Shipping_Map */ ?>


<?php $populateData = $this->getPopulateData(); ?>

<?php foreach ($populateData as $lockerName => $lockerInfo): ?>
    <p>
        <a data-select-shipping-method-trigger="1"
           data-carrier-pointcode="<?php echo $lockerName; ?>"
           data-carrier-additional="<?php echo $lockerInfo; ?>" href="">
            <?php echo $lockerName; ?>
        </a>
    </p>
<?php endforeach; ?>