<?php $_helper = Mage::helper("ghapi"); ?>

<div class="container">
    <!--=== Page Header ===-->
    <div class="page-header">
        <div class="page-title">
            <h3><?php echo $_helper->__("GH API");?></h3>
        </div>
    </div>
	<div class="tabbable tabbabble-custom">
		<ul class="nav nav-tabs" style="margin-top:6px" id="ghapiTabs">
			<li class="active"><a data-toggle="tab" href="#tab_1_1"><?php echo $_helper->__("Settings");?></a></li>
			<li><a data-toggle="tab" href="#tab_1_2"><?php echo $_helper->__('Test API');?></a></li>
			<li><a data-toggle="tab" href="#tab_1_3"><?php echo $_helper->__('Help');?></a></li>
		</ul>
	    <div class="tab-content">
			<div id="tab_1_1" class="tab-pane active">
				<div class="container" style="margin-top:15px;paddign: 10px">
					<?php echo $this->getChildHtml('ghapi_dropship_settings');?>
				</div>
			</div>
			<div id="tab_1_2" class="tab-pane">
				<div class="container" style="margin-top:15px;paddign: 10px">
					<?php echo $this->getChildHtml('ghapi_dropship_soap');?>				
				</div>
			</div>
            <div id="tab_1_3" class="tab-pane">
                <div class="container" style="margin-top:15px;paddign: 10px">
                    <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('ghapi-help')->toHtml();?>
                </div>
            </div>
		</div>
	</div>
</div>


