<?php $_helper = Mage::helper("ghapi"); ?>
<div class="row">
	<div class="col-md-12">
		<form class="form-horizontal">
			<?php echo $this->getChildHtml('ghapi_dropship_soap_login');?>
			<?php echo $this->getChildHtml('ghapi_dropship_soap_message');?>
			<?php echo $this->getChildHtml('ghapi_dropship_soap_confirmation');?>
			<?php echo $this->getChildHtml('ghapi_dropship_soap_orders');?>
			<?php echo $this->getChildHtml('ghapi_dropship_soap_collected');?>
			<?php echo $this->getChildHtml('ghapi_dropship_soap_shipment');?>
			<?php //echo $this->getChildHtml('ghapi_dropship_soap_reservation');?>
			<div id="soap_ajax_answer">
				<strong><?php echo $_helper->__('SOAP Request');?></strong>
				<pre>
					<code class="language-markup" id="soap_request">
					</code>
				</pre>
				<strong><?php echo $_helper->__('SOAP Response');?></strong>
				<pre>
					<code class="language-markup" id="soap_response">
				</code>
				</pre>
			</div>
		</form>
	</div>
</div>

<script>
jQuery(function ($) {
	function doSoapAjax(params) {
		$.ajax({
			url: 'test',
			method: 'POST',
			data: params,
			success: function(answer) {
				$('#soap_ajax_answer').html(answer);	
				Prism.highlightAll();
			}
		});
	};
	jQuery(document).on('click','#do_login_action',function () {
		var params = {};
		params.action = 'doLogin';
		params.vendorId = jQuery('#soap_login_vendor_id').val();
		params.password = jQuery('#soap_login_password').val();
		params.apiKey	= jQuery('#soap_login_api_key').val();
		doSoapAjax(params);
	});
	jQuery(document).on('click','#get_message_action',function () {
		var params = {};
		params.action = 'getChangeOrderMessage';
		params.token = jQuery('#soap_message_token').val();
		params.size = jQuery('#soap_message_size').val();
		params.messageType	= jQuery('#soap_message_type').val();
		doSoapAjax(params);
	});
	jQuery(document).on('click','#confirm_message_action',function () {
		var params = {};
		params.action = 'setChangeOrderMessageConfirmation';
		params.token = jQuery('#soap_confirmation_token').val();
		params.list = jQuery('#soap_confirm_list').val();
		doSoapAjax(params);
	});
	jQuery(document).on('click','#get_orders_action',function () {
		var params = {};
		params.action = 'getOrdersByID';
		params.token = jQuery('#soap_order_token').val();
		params.list = jQuery('#soap_order_list').val();
		doSoapAjax(params);
	});
	jQuery(document).on('click','#set_collected_action',function () {
		var params = {};
		params.action = 'setOrderAsCollected';
		params.token = jQuery('#soap_collected_token').val();
		params.list = jQuery('#soap_collected_list').val();
		doSoapAjax(params);
	});
    jQuery(document).on('click','#set_shipment_action',function () {
        var params = {};
        params.action = 'setOrderShipment';
        params.token = jQuery('#soap_shipment_token').val();
        params.orderID = jQuery('#soap_shipment_order_id').val();
        params.dateShipped = jQuery('#soap_shipment_date_shipped').val();
        params.shipmentTrackingNumber = jQuery('#soap_shipment_shipment_tracking_number').val();
        params.courier = jQuery('#soap_collected_courier').val();
        doSoapAjax(params);
    });
 		
});
</script>