<!DOCTYPE html>
<html lang="en">
<head>
<script type="text/javascript">
    var BLANK_URL = 'https://<?php echo $host; ?>/js/blank.html';
    var BLANK_IMG = 'https://<?php echo $host; ?>/js/spacer.gif';
    var BASE_URL = 'http://<?php echo $host; ?>/udropship/';
    var SKIN_URL = 'https://<?php echo $host; ?>/skin/frontend/default/udropship/';
    var FORM_KEY = '';
</script>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>PHPUnit Tests</title>
<meta name="description" content="Default Description" />
<meta name="keywords" content="Moda, fashion, marketplace" />
<meta name="robots" content="INDEX,FOLLOW" />
<link rel="icon" href="https://<?php echo $host; ?>/skin/frontend/default/default/favicon.ico" type="image/x-icon" />
<link rel="shortcut icon" href="https://<?php echo $host; ?>/skin/frontend/default/default/favicon.ico" type="image/x-icon" />
<!--[if lt IE 7]>
<script type="text/javascript">
//<![CDATA[
    var BLANK_URL = 'https://<?php echo $host; ?>/js/blank.html';
    var BLANK_IMG = 'https://<?php echo $host; ?>/js/spacer.gif';
//]]>
</script>
<![endif]-->
<link rel="stylesheet" type="text/css" href="https://<?php echo $host; ?>/skin/frontend/default/udropship/css/boostrap/bootstrap.css" media="all" />
<link rel="stylesheet" type="text/css" href="https://<?php echo $host; ?>/skin/frontend/default/udropship/css/melon/main.css" media="all" />
<link rel="stylesheet" type="text/css" href="https://<?php echo $host; ?>/skin/frontend/default/udropship/css/melon/plugins/jquery-ui.css" media="all" />
<link rel="stylesheet" type="text/css" href="https://<?php echo $host; ?>/skin/frontend/default/udropship/css/melon/plugins/daterangepicker.css" media="all" />
<link rel="stylesheet" type="text/css" href="https://<?php echo $host; ?>/skin/frontend/default/udropship/css/melon/plugins/uniform.css" media="all" />
<link rel="stylesheet" type="text/css" href="https://<?php echo $host; ?>/skin/frontend/default/udropship/css/melon/plugins/tagsinput.css" media="all" />
<link rel="stylesheet" type="text/css" href="https://<?php echo $host; ?>/skin/frontend/default/udropship/css/melon/plugins/select2.css" media="all" />
<link rel="stylesheet" type="text/css" href="https://<?php echo $host; ?>/skin/frontend/default/udropship/css/melon/plugins/duallistbox.css" media="all" />
<link rel="stylesheet" type="text/css" href="https://<?php echo $host; ?>/skin/frontend/default/udropship/css/melon/plugins/datatables_bootstrap.css" media="all" />
<link rel="stylesheet" type="text/css" href="https://<?php echo $host; ?>/skin/frontend/default/udropship/css/melon/plugins/datatables.css" media="all" />
<link rel="stylesheet" type="text/css" href="https://<?php echo $host; ?>/skin/frontend/default/udropship/css/melon/plugins/pickadate.css" media="all" />
<link rel="stylesheet" type="text/css" href="https://<?php echo $host; ?>/skin/frontend/default/udropship/css/melon/plugins/bootstrap-colorpicker.css" media="all" />
<link rel="stylesheet" type="text/css" href="https://<?php echo $host; ?>/skin/frontend/default/udropship/css/melon/plugins/typeahead.css" media="all" />
<link rel="stylesheet" type="text/css" href="https://<?php echo $host; ?>/skin/frontend/default/udropship/css/melon/plugins/fullcalendar.css" media="all" />
<link rel="stylesheet" type="text/css" href="https://<?php echo $host; ?>/skin/frontend/default/udropship/css/melon/plugins/nestable.css" media="all" />
<link rel="stylesheet" type="text/css" href="https://<?php echo $host; ?>/skin/frontend/default/udropship/css/melon/plugins/bootstrap-wysihtml5.css" media="all" />
<link rel="stylesheet" type="text/css" href="https://<?php echo $host; ?>/skin/frontend/default/udropship/css/melon/plugins/bootstrap-multiselect.css" media="all" />
<link rel="stylesheet" type="text/css" href="https://<?php echo $host; ?>/skin/frontend/default/udropship/css/melon/plugins/nprogress.css" media="all" />
<link rel="stylesheet" type="text/css" href="https://<?php echo $host; ?>/skin/frontend/default/udropship/css/melon/plugins/bootstrap-wizard.css" media="all" />
<link rel="stylesheet" type="text/css" href="https://<?php echo $host; ?>/skin/frontend/default/udropship/css/melon/plugins/bootstrap-switch.css" media="all" />
<link rel="stylesheet" type="text/css" href="https://<?php echo $host; ?>/skin/frontend/default/udropship/css/melon/responsive.css" media="all" />
<link rel="stylesheet" type="text/css" href="https://<?php echo $host; ?>/skin/frontend/default/udropship/css/melon/fontawesome/font-awesome.min.css" media="all" />
<link rel="stylesheet" type="text/css" href="https://<?php echo $host; ?>/skin/frontend/default/udropship/css/local/customs.css" media="all" />
<link rel="stylesheet" type="text/css" href="https://<?php echo $host; ?>/skin/frontend/default/udropship/css/local/noless.css" media="all" />
<script type="text/javascript" src="https://<?php echo $host; ?>/js/prototype/prototype.js"></script>
<script type="text/javascript" src="https://<?php echo $host; ?>/js/prototype/validation.js"></script>
<script type="text/javascript" src="https://<?php echo $host; ?>/js/scriptaculous/builder.js"></script>
<script type="text/javascript" src="https://<?php echo $host; ?>/js/scriptaculous/effects.js"></script>
<script type="text/javascript" src="https://<?php echo $host; ?>/js/scriptaculous/dragdrop.js"></script>
<script type="text/javascript" src="https://<?php echo $host; ?>/js/scriptaculous/controls.js"></script>
<script type="text/javascript" src="https://<?php echo $host; ?>/js/scriptaculous/slider.js"></script>
<script type="text/javascript" src="https://<?php echo $host; ?>/js/varien/js.js"></script>
<script type="text/javascript" src="https://<?php echo $host; ?>/js/varien/form.js"></script>
<script type="text/javascript" src="https://<?php echo $host; ?>/js/varien/menu.js"></script>
<script type="text/javascript" src="https://<?php echo $host; ?>/js/mage/translate.js"></script>
<script type="text/javascript" src="https://<?php echo $host; ?>/js/mage/cookies.js"></script>
<script type="text/javascript" src="https://<?php echo $host; ?>/js/unirgy/domloaded.js"></script>
<script type="text/javascript" src="https://<?php echo $host; ?>/js/unirgy/modal.js"></script>
<script type="text/javascript" src="https://<?php echo $host; ?>/js/unirgy/banner_media.js"></script>
<script type="text/javascript" src="https://<?php echo $host; ?>/js/unirgy/slider.js"></script>
<script type="text/javascript" src="https://<?php echo $host; ?>/skin/frontend/default/udropship/js/melon/libs/jquery-1.10.2.min.js"></script>
<script type="text/javascript" src="https://<?php echo $host; ?>/skin/frontend/default/udropship/js/integration.js"></script>
<script type="text/javascript" src="https://<?php echo $host; ?>/skin/frontend/default/udropship/js/plugins/jquery-ui/jquery-ui-1.10.2.custom.min.js"></script>
<script type="text/javascript" src="https://<?php echo $host; ?>/skin/frontend/default/udropship/js/boostrap/bootstrap.min.js"></script>
<script type="text/javascript" src="https://<?php echo $host; ?>/skin/frontend/default/udropship/js/melon/libs/lodash.compat.min.js"></script>
<script type="text/javascript" src="https://<?php echo $host; ?>/skin/frontend/default/udropship/js/plugins/touchpunch/jquery.ui.touch-punch.min.js"></script>
<script type="text/javascript" src="https://<?php echo $host; ?>/skin/frontend/default/udropship/js/plugins/event.swipe/jquery.event.move.js"></script>
<script type="text/javascript" src="https://<?php echo $host; ?>/skin/frontend/default/udropship/js/plugins/event.swipe/jquery.event.swipe.js"></script>
<script type="text/javascript" src="https://<?php echo $host; ?>/skin/frontend/default/udropship/js/melon/libs/breakpoints.js"></script>
<script type="text/javascript" src="https://<?php echo $host; ?>/skin/frontend/default/udropship/js/plugins/respond/respond.min.js"></script>
<script type="text/javascript" src="https://<?php echo $host; ?>/skin/frontend/default/udropship/js/plugins/cookie/jquery.cookie.min.js"></script>
<script type="text/javascript" src="https://<?php echo $host; ?>/skin/frontend/default/udropship/js/plugins/slimscroll/jquery.slimscroll.min.js"></script>
<script type="text/javascript" src="https://<?php echo $host; ?>/skin/frontend/default/udropship/js/plugins/slimscroll/jquery.slimscroll.horizontal.min.js"></script>
<script type="text/javascript" src="https://<?php echo $host; ?>/skin/frontend/default/udropship/js/melon/app.js"></script>
<script type="text/javascript" src="https://<?php echo $host; ?>/skin/frontend/default/udropship/js/melon/plugins.js"></script>
<script type="text/javascript" src="https://<?php echo $host; ?>/skin/frontend/default/udropship/js/melon/plugins.form-components.js"></script>
<script type="text/javascript" src="https://<?php echo $host; ?>/skin/frontend/default/udropship/js/plugins/pickadate/picker.js"></script>
<script type="text/javascript" src="https://<?php echo $host; ?>/skin/frontend/default/udropship/js/plugins/pickadate/picker.date.js"></script>
<script type="text/javascript" src="https://<?php echo $host; ?>/skin/frontend/default/udropship/js/plugins/pickadate/picker.time.js"></script>
<script type="text/javascript" src="https://<?php echo $host; ?>/skin/frontend/default/udropship/js/plugins/uniform/jquery.uniform.min.js"></script>
<script type="text/javascript" src="https://<?php echo $host; ?>/skin/frontend/default/udropship/js/cssbs.js"></script>
<!--[if IE 7]>
<link rel="stylesheet" type="text/css" href="https://<?php echo $host; ?>/skin/frontend/default/udropship/css/melon/fontawesome/font-awesome-ie7.min.css" media="all" />
<![endif]-->
<!--[if lt IE 9]>
<script type="text/javascript" src="https://<?php echo $host; ?>/skin/frontend/default/udropship/js/melon/libs/html5shiv.js"></script>
<![endif]-->
<script>
jQuery(document).ready(function(){
	"use strict";

	App.init(); // Init layout and core plugins
	Plugins.init(); // Init all plugins
	FormComponents.init(); // Init all form-specific plugins
});
</script>
</head>
<body class=" udropship-vendor-dashboard udropship-vendor">
	<div id="container">	
		<div id="content">
		    <h3>Test list</h3>
			<?echo $body; ?>
		</div>
	</div>
</body>
</html>