<div class="row col-md-9">
    <?php foreach ($classes as $name=>$class): ?>
    <?php if (!count($class['methods'])):?>
    <?php continue; ?>
    <?php endif;?>
    <div class="widget box widget-closed" style="cursor:pointer">
        <div class="widget-header">
            <h4><?php echo $name; ?></h4>
            <div class="toolbar no-padding">
                <span class="btn btn-xs widget-collapse"><i class="icon-angle-down"></i></span>
            </div>
        </div>        
        <div class="widget-content">
            <table class="table table-hover table-striped">
                <tbody>
                <?php foreach ($class['methods'] as $method): ?>
                    <tr>
                        <td class="col-md-10">
                            <?php echo $method; ?>
                        </td>
                        <td class="col-md-1">
                            <button class="btn btn-primary btn-xs start-test" data-class="<?php echo $class['file'];?>" data-method="<?php echo $method;?>">start</button>
                        </td>
                        <td class="col-md-1">
                            <div class="status"></div>
                        </td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
    <?php endforeach;?>
</div>
<script>
jQuery(function ($) {
    jQuery('.start-test').click(function(){
        doTest($(this).attr('data-class'),$(this).attr('data-method'),$(this));
    });
    function doTest(classname,method,button) {
        var params = {};
        params.classname = classname;
        params.method = method;
        button.html('wait');
        button.attr('disabled',true);
        $.ajax({
            url: '?action=execute',
            method: 'POST',
            data:params,
            success: function (answer) {
                button.parent().parent().find('.status').each(function() {
                    $(this).html(answer);
                });
                button.html('start');
                button.attr('disabled',false);
            },
            error: function () {
                button.html('error');
            }
        })
    }
})
</script>