<?php
/**
 * part of order_new email template for products table coresponding to vendor
 */

/** @var Zolago_Modago_Block_Sales_Order_Email_New $this */
/** @var Zolago_Sales_Helper_Data $helper */
/** @var Zolago_Sales_Model_Order $order */
/** @var Zolago_Po_Helper_Data $helperUDPO */
/** @var ZolagoOs_OmniChannelPo_Model_Mysql4_Po_Collection $poList */

$helper = Mage::helper('zolagosales');
//$order = Mage::getModel('sales/order')->load(30); //only for testing
$order = $this->getOrder();
if (!$order) {
    return; //only for not getting error when view template email
}
$helperUDPO = Mage::helper('udpo');
$poList = $order->getPoListByOrder();
$count = $poList->getSize();
$i = 1;

foreach ($poList as $po): /** @var Zolago_Po_Model_Po $po */ ?>

    <div style="border-bottom:25px solid white;line-height: 1.4em;margin:0;padding:0">
        <?php echo $helper->__("Max shipping date:"); ?> <?php echo $po->getMaxShippingDate(); ?> <?php echo ($po->isCod()) ? '' : $helper->__("(may change in the case of non-payment)"); ?>
    </div>

    <?php
    Mage::register("current_po", $po);// ugly hack for this block
    echo $this->getLayout()->createBlock('zolagomodago/po_email_summary')->setTemplate("zolagopo/email/summary.phtml")->toHtml();
    Mage::unregister("current_po");
    ?>
    <span class="spacer">&nbsp;</span>
<?php endforeach; ?>