<div class="entry-edit">
    <div class="entry-edit-head">
        <div style="float: right;"></div>
        <h4 class="fieldset-legend "><?php echo Mage::helper('zolagopos')->__("Browse vendors");?></h4>
    </div>
    <div class="fieldset">
        <div class="store-scope">
            <?php echo $this->getChildHtml('zolagopos_pos_vendor_grid'); ?>
            <?php echo $this->getChildHtml('zolagopos_pos_vendor_grid_serializer'); ?>
        </div>
    </div>
</div>