<?php /* @var $this Zolago_Modago_Block_Checkout_Cart_Sidebar_Shipping */?>



<?php
/** @var Zolago_Checkout_Helper_Data $helper */
$helper		= Mage::helper("zolagocheckout");

$items = $this->getItems();
$vendors = $items->vendors;

$vendorsJ = Mage::helper('core')->jsonEncode($vendors);

$allVendorsMethod = $items->allVendorsMethod;

$methods = $items->methods;
$rates = $items->rates;
$vednorCosts = $items->vendorCosts;
$costSumm = $this->getItemsShippingCost();
$cost = $items->cost;



$sessionShippingMethod = $this->getData("shipping_method");

//Zend_Debug::dump($sessionShippingMethod);

$locker		= $this->getInpostLocker();
$inpostLogo	= $this->getSkinUrl('images/inpost/checkout-logo.png');
//Zend_Debug::dump($locker);
?>


<?php if(!empty($rates)): ?>
<fieldset id="cart-shipping-methods">
    <form action="<?php echo $this->getUrl('checkout/singlepage/saveBasketShipping') ?>" method="post" id="cart-shipping-methods-form">
    <div class="data-validate"></div>
    <script type="text/javascript">
        (function(){
            Mall.reg.set("vendors", <?php echo $vendorsJ; ?>);
            Mall.reg.set("vendor_costs", <?php echo Mage::helper("core")->jsonEncode($vednorCosts); ?>);
        })();
    </script>
    <div class="shipping-collect-inpost">
        <?php if(!empty($locker->getData("locker_name"))): ?>
                <input type="hidden" name="inpost_code" value="<?php echo $locker->getData("locker_name"); ?>" required="required" />
        <?php endif; ?>
    </div>
    <div class="shipping-collect">
        <?php if(!empty($sessionShippingMethod)): ?>
            <?php foreach($sessionShippingMethod as $vendorId => $methodCode): ?>
                <input type="hidden" name="shipping_method[<?php echo $vendorId; ?>]" value="<?php echo $methodCode; ?>" required="required" />
                <?php endforeach; ?>
        <?php endif; ?>
    </div>
    
    
        
    <div class="shipping-method-selected row col-md-12">
        <?php foreach ($methods as $method): ?>
                <?php
                $formattedCost = '';
                if (isset($cost[$method['code']])) {
                    $costSum = array_sum($cost[$method['code']]);
                    $formattedCost = Mage::helper('core')->currency($costSum, true, false);
                }
                ?>
                <?php if (!empty($sessionShippingMethod) && in_array($method['code'], $sessionShippingMethod)): ?>
                    <div>
                        <div>
                                <div>

                                    <?php echo $this->escapeHtml($method['carrier_title']); ?><br />
                                    <?php echo $this->escapeHtml($method['method_title']); ?>

                                <?php endif; ?>

                                <?php if (strpos(strtolower($method["method_title"]), 'inpost') !== false): ?>
                                    <br />
                                    <div class="inpost-locker-data-holder">
                                        <div class="inpost-code-holder">
                                            <?php echo $locker->getData("locker_name"); ?>
                                        </div>
                                        <div>
                                            <div class="delivery-type-inpost-logo pull-left">
                                                <img
                                                    style="padding: 5px 7px; border: 1px solid lightgray;"
                                                    src="<?php echo $inpostLogo; ?>" height="50px"/>
                                            </div>
                                            <div class="pull-right">
                                                <a class="button button-third large pull-right" id="change-shipping-type"
                                                        style="bottom: -22px; position: relative;"
                                                        >
                                                    <?php echo $helper->__("Change"); ?>
                                                </a>
                                            </div>
                                        </div> 
                                    </div>                                    
                                    
                                </div>
                        </div>
                    </div>
                <?php endif; ?>
            <?php endforeach; ?>
    </div>
    <div class="shipping-method-selector row col-md-12" <?php if(!empty($sessionShippingMethod)): ?>style="display:none;"<?php endif; ?>>
        <?php foreach ($methods as $method): ?>
            <?php

            $formattedCost = '';
            if (isset($cost[$method['code']])) {
                $costSum = array_sum($cost[$method['code']]);
                $formattedCost = Mage::helper('core')->currency($costSum, true, false);
            } ?>
            <div class="panel panel-default panel-color">
                <div class="panel-body">
                    <dl>
                        <div class="pull-left">
                            <input type="radio"
                                   value="<?php echo $method['code']; ?>"
                                   <?php if(!empty($sessionShippingMethod) && in_array($method['code'], $sessionShippingMethod)): ?>checked<?php endif; ?>
                                   name="_shipping_method"
                                   data-carrier-inpost="<?php echo (int)(strpos(strtolower($method["method_title"]), 'inpost') !== false); ?>"
                                   required="required"
                                   class="shipping-method"
                                   data-carrier-name="<?php echo $this->escapeHtml($method['carrier_title']); ?>"
                                   data-carrier-method="<?php echo $this->escapeHtml($method['method_title']); ?>"
                                   data-method-cost="<?php echo $costSum; ?>"/>


                            <?php echo $method['carrier_title'] ?>
                            <br/>
                            <?php echo $method['method_title'] ?>

                            <?php if (strpos(strtolower($method["method_title"]), 'inpost') !== false): ?>
                                <br />
                                <div class="inpost-code-holder"><?php echo $locker->getData("locker_name"); ?></div>
                            <?php endif; ?>
                        </div>

                        <div class="pull-right"><strong><?php echo $formattedCost; ?> </strong></div>
                    </dl>
                </div>
            </div>
        <?php endforeach; ?>
    </div>  
    
    
        
    
    
    
        

    <?php else: ?>
        <div class="panel panel-default panel-color">
            <div class="panel-body">
                <dl class="pull-left">
                    <?php echo $this->__('No delivery method available'); ?>
                </dl>
            </div>
        </div>
    <?php endif; ?>
</form>
</fieldset>



<div class="modal fade bs-example-modal-lg" id="select_inpost_point" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true" style="z-index: 1050">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"></button>
                <h2 class="title_section"><?php echo $this->__("Select Paczkomat"); ?></h2>
            </div>

            <div class="modal-body">
                <a class="select-inpost-code" href="">BiedronkaUstka</a>
                <br />
                <a class="select-inpost-code" href="">MarketNettoUstka</a>
            </div>
        </div>
    </div>
</div>


