<?php /* @var $this Zolago_Modago_Block_Checkout_Cart_Sidebar_Shipping */?>



<?php

$items = $this->getItems();
$vendors = $items->vendors;

$vendorsJ = Mage::helper('core')->jsonEncode($vendors);

$allVendorsMethod = $items->allVendorsMethod;

$methods = $items->methods;
$rates = $items->rates;
$vednorCosts = $items->vendorCosts;
$costSumm = $this->getItemsShippingCost();
$cost = $items->cost;

//krumo($rates);
?>


<?php if(!empty($rates)): ?>
<fieldset id="shipping-methods">

    <div class="data-validate"></div>
    <script type="text/javascript">
        (function(){
            Mall.reg.set("vendors", <?php echo $vendorsJ; ?>);
            Mall.reg.set("vendor_costs", <?php echo Mage::helper("core")->jsonEncode($vednorCosts); ?>);
        })();
    </script>
    <div class="shipping-collect"></div>
    <?php foreach($methods as $method): ?>
        <?php
        $formattedCost = '';
        if (isset($cost[$method['code']])) {
            $costSum = array_sum($cost[$method['code']]);
            $formattedCost = Mage::helper('core')->currency($costSum, true, false);
        }?>
        <div class="panel panel-default panel-color">
            <div class="panel-body">
                <dl class="pull-left">

                    <dt>
                        <input type="radio"
                               value="<?php echo $method['code']; ?>"
                               name="_shipping_method"
                               required="required"
                               class="shipping-method"
                               data-carrier-name="<?php echo $this->escapeHtml($method['carrier_title']);?>"
                               data-carrier-method="<?php echo $this->escapeHtml($method['method_title']);?>"
                               data-method-cost="<?php echo $costSum;?>"/>

                        <?php echo $method['carrier_title']?></dt>
                    <dd><?php echo $method['method_title']?></dd>
                    <dd class="separator large"><?php echo $this->__('Shipping cost'); ?>: <strong><?php echo $formattedCost; ?> </strong></dd>
                </dl>
            </div>
        </div>
    <?php endforeach; ?>


    <?php else: ?>
        <div class="panel panel-default panel-color">
            <div class="panel-body">
                <dl class="pull-left">
                    <?php echo $this->__('No delivery method available'); ?>
                </dl>
            </div>
        </div>
    <?php endif; ?>
</fieldset>



