<?php
/**
 * Author: Paweł Chyl <pawel.chyl@orba.pl>
 * Date: 19.05.14
 */
?>

<ul class="visible-sm visible-xs">
    <li><a href="#"><i class="fa fa-angle-right"></i> Pomoc</a></li>
    <li><a href="#"><i class="fa fa-angle-right"></i> O nas</a></li>
    <li><a href="#"><i class="fa fa-angle-right"></i> Twoje konto</a></li>
    <li><a href="#"><i class="fa fa-angle-right"></i> Kontakt</a></li>
    <li><a href="#"><i class="fa fa-angle-right"></i> Pełna wersja wpisu</a></li>
</ul>