<?php /* @var $this Zolago_Modago_Block_Checkout_Onepage_Shared_Review */ ?>
<?php $_helper = Mage::helper("zolagocheckout"); ?>
<div class="checkout-shared-review node-type-summary-delivery-payment">

	<?php $_items = $this->getItems(); ?>
	<?php $this->preparePresentation(); ?>

	<div class="col-lg-9 col-md-8 col-sm-12 col-xs-12 section" id="content-main">
		<section class="main bg-w">
			<header class="title-section">
				<h2><?php echo $this->__("Your order"); ?></h2>
			</header>

			<?php $total = 0; ?>
			<?php foreach ($_items as $_item) : ?>
				<?php echo $this->getItemHtml($_item); ?>
				<?php $total += $_item->getData('row_total_incl_tax'); ?>
			<?php endforeach; ?>


			<div id="sumary_total_amount" class="panel panel-custom">
				<div class="panel-body">
					<div class="col-sm-6 visible-lg visible-md visible-sm">
						<div class="row">
							<a href="<?php echo $this->getBasketUrl(); ?>" 
							   id="zmiana_zawartosci_koszyka"
							   class="button button-third large pull-left"><?php echo $this->__('Change basket'); ?></a> 
						</div>
					</div>
					<div class="col-sm-6 col-xs-12">
						<div class="row">
							<dl>
								<dd><span class="lb"><?php echo $this->__('Summary value'); ?>:</span> <span><?php echo Mage::helper('core')->formatPrice($total); ?></span></dd>
								<dd><span class="lb"><?php echo $this->__('Shipping cost'); ?>:</span> <span class="total_shipping"></span></dd>
								<dt><span class="lb"><?php echo $this->__('To pay'); ?>:</span> <span class="total_value"></span></dt>
							</dl>
						</div>
					</div>

				</div>
			</div>

			<div class="row hidden-xs">
				<div class="col-md-6 col-sm-12 col-md-push-3">
					<p class="text-potwierdzenie"><?php echo $this->getCheckoutReviewInfo(); ?></p>
				</div>
				<div class="col-md-3 col-sm-6 col-md-pull-6">
					<a href="#"  id="step-2-prev"  class="button button-third large pull-left"><?php echo $this->__('Back'); ?></a>
				</div>
				<div class="col-md-3 col-sm-6">
					<button class="button button-primary large link pull-right" id="step-2-submit"><?php echo $this->__('Place order'); ?></button>
				</div>
			</div>


		</section>
	</div>
	
	
	<div class="sidebar-secound col-lg-3 col-md-4 col-sm-12 col-xs-12">
		<section class="main bg-w opened-panel-group sidebar-addresses">
			<header>
				<h2 class="open"><?php echo $_helper->__('Shipping information'); ?></h2>
			</header>
			<div class="row">
				<div class="col-md-12  col-sm-4">
					<h4><?php echo $_helper->__('Delivery address'); ?>:</h4>
					{{shipping}}
				</div>
				<div class="col-md-12  col-sm-4">
					<h4><?php echo $_helper->__('Sales document'); ?>:</h4>
					<dl>
						<dd>{{sales_document}}<dd>
					</dl>
				</div>
				<div class="col-md-12 col-sm-4 invoice-data">
					<h4><?php echo $_helper->__('Invoice data'); ?>:</h4>
					{{billing}}
				</div>
			</div>
			<div class="row">
				<div class="col-sm-12">
					<button class="button button-third large pull-right prev-button-address"><?php echo $_helper->__('Change'); ?></button>
				</div>
			</div>
		</section>
		<section class="main bg-w opened-panel-group sidebar-deliverypayment">
			<header>
				<h2 class="open"><?php echo $_helper->__('Delivery and payment'); ?></h2>
			</header>

			<div class="row">
				<div class="col-md-12  col-sm-4">
					<h4><?php echo $_helper->__('Delivery type'); ?>:</h4>
					<dl>
						<dd>{{carrier_name}} - {{carrier_method}}</dd>
					</dl>
				</div>
				<div class="col-md-12  col-sm-4">
					<h4><?php echo $_helper->__('Payment type'); ?>:</h4>
					<dl>
						<dd>{{payment_method}}</dd>
						<dd class="online-data">{{online_data}}</dd>
					</dl>
				</div>
			</div>
			<div class="row">
				<div class="col-sm-12">
					<button class="button button-third large pull-right  prev-button-deliverypaymnet"><?php echo $_helper->__('Change'); ?></button>
				</div>
			</div>

		</section>
		<div class="main bg-w visible-xs opened-panel-group">  
			<p><?php echo $this->getCheckoutReviewInfo(); ?></p>
			<div class="row">
				<div class="col-sm-6">
					<a  href="#"  id="step-2-prev" class="button button-third large pull-left"><?php echo $this->__('Back'); ?></a>
				</div>
				<div class="col-sm-6">
					<button class="button button-primary large link pull-right" id="step-2-submit"><?php echo $this->__('Place order'); ?></button>
				</div>
			</div>

		</div>
	</div>

</div>