<?php $formKey = Mage::getSingleton('core/session')->getFormKey(); ?>
<?php $_helper = Mage::helper("zolagocheckout");?>
<form autocomplete="off" action="<?php echo $this->getSaveUrl(); ?>" class="form" id="co-shippingpayment">
    <input type="hidden" name="form_key" value="<?php echo $formKey; ?>" />

<div class="sidebar-secound col-lg-3 col-md-4 col-sm-12 col-xs-12 col-lg-push-9 col-md-push-8">
    <section class="main bg-w  hidden-sm hidden-xs sidebar-addresses">
        <header>
            <h2 class="open"><?php echo $_helper->__('Shipping information'); ?></h2>
        </header>
        <div class="row">
            <div class="col-md-12  col-sm-4">
                <h4><?php echo $_helper->__('Delivery address'); ?>:</h4>
                {{shipping}}
            </div>
            <div class="col-md-12  col-sm-4">
                <h4><?php echo $_helper->__('Sales document'); ?>:</h4>
                <p>{{sales_document}}</p>
            </div>
            <div class="col-md-12 col-sm-4 invoice-data">
                <h4><?php echo $_helper->__('Invoice data'); ?>:</h4>
                {{billing}}
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12">
                <button class="button button-third large pull-right prev-button-address"><?php echo $_helper->__('Change'); ?></button>
            </div>
        </div>
    </section>
    <section class="p main bg-w hidden-sm hidden-xs">
        <header>
            <h2 class="open">Blok CMS</h2>
        </header>
        <div class="clearfix border-top">
            <ul>
                <li>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</li>
                <li>Pellentesque ultrices lectus ut felis tempor, eget rutrum nulla sodales.</li>
                <li>Nullam vel nunc eu enim hendrerit hendrerit eget non leo.</li>
                <li>Quisque sit amet diam elementum, aliquet risus non, dignissim tortor.</li>
            </ul>
        </div>
        <div class="clearfix border-top">
            <ol>
                <li>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</li>
                <li>Pellentesque oltrices lectus ut felis tempor, eget rutrum nulla sodales.</li>
                <li>Nullam vel nunc eu enim hendrerit hendrerit eget non leo.</li>
                <li>Quisque sit amet diam elementum, aliquet risus non, dignissim tortor.</li>

            </ol></div>
        <div class="clearfix border-top">
            <dl>
                <dt>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</dt>
                <dd class="separator">Pellentesque ultrices lectus ut fedds tempor, eget rutrum nulla sodales.</dd>
                <dd>Nullam vel nunc eu enim hendrerit hendrerit eget non leo.</dd>
                <dd class="separator">Quisque sit amet diam elementum, addquet risus non, dignissim tortor.</dd>
            </dl>
        </div>
    </section>
</div>
<div class="col-lg-9 col-md-8 col-sm-12 col-xs-12 col-lg-pull-3 col-md-pull-4 section" id="content-main">
    <section class="main bg-w">
        <header class="title-section">
            <h2><?php echo $_helper->__('Confirm delivery and payment method'); ?></h2>
        </header>
        <div class="row">
            <div id="containererreurtotal"  style="margin-bottom: 10px;"></div>
        </div>

        <?php echo $this->getChildHtml("shipping");?>
        <?php echo $this->getChildHtml("payment");?>

        <div class="row">
            <div class="col-sm-6">
                <a class="button button-third large pull-left" id="step-1-prev"><?php echo $_helper->__("Back"); ?></a>
            </div>
            <div class="col-sm-6">
                <button class="button button-primary large link pull-right" id="step-1-submit"><?php echo $_helper->__("Next"); ?></button>
            </div>
        </div>

    </section>

</div>

</form>










