<fieldset class="default_pay selected-payment">
    <?php /** @var Zolago_Checkout_Helper_Data $_helper */ ?>
    <?php $_helper = Mage::helper("zolagocheckout"); ?>
    <h4 class="fieldset-title"><?php echo $_helper->__("Select payment method"); ?>:</h4>
    <div class="data-validate"></div>
    <!-- PANEL -->
    <div class="panel panel-default">
        <div class="panel-body">
            <?php /* <!--            <div class="top-panel">-->
            <!--                <h4>--><?php //echo $_helper->__("Wybierz sposób płatności"); ?><!--</h4>-->
            <!--                <div class="row">-->
            <!--                    <div class="form-group form-checkbox small default_pay">-->
            <!--						--><?php //if($this->getHasDefaultPayment()):?>
            <!--							<input type="hidden" value="0" name="default_pay">-->
            <!--							<input type="checkbox" class="css-checkbox " id="default_pay" value="1" name="default_pay">-->
            <!--							<label class="css-label remember_this" for="default_pay">-->
            <!--								--><?php //echo $_helper->__("Set as default payment");?>
            <!--							</label>-->
            <!--						--><?php //endif;?>
            <!--                    </div>-->
            <!--                </div>-->
            <!--            </div>--> */ ?>
            <?php echo $this->getChildHtml('methods') ?>
            <?php // <!--        </div>--> ?>
        </div>
        <div class="panel-footer">
            <a class="underline" id="view_default_pay" href="#">
                <?php //echo $_helper->__('cancel changes'); ?>
            </a>
        </div>
        <script type="text/javascript">
            Mall.translate.add("cancel-changes", "<?php echo $this->__("cancel changes"); ?>");
            Mall.translate.add("select-payment-type", "<?php echo $this->__("select payment type"); ?>");
            Mall.translate.add("please-select-payment", "<?php echo $this->__("Please select payment type"); ?>");
            Mall.translate.add("please-select-bank", "<?php echo $this->__("Please select bank"); ?>");
            Mall.translate.add("please-select-card", "<?php echo $this->__("Please select card type"); ?>");
            Mall.translate.add("bank", "<?php echo $this->__("Bank"); ?>");
            Mall.translate.add("payment-supported-by", "<?php echo $this->__("Payment supported by"); ?>");
            Mall.translate.add("address-you-sure?", "<?php echo $this->__("Do you really want to remove this address?");?>");
        </script>
</fieldset>



