<?php /* @var $this Mage_Customer_Block_Form_Edit */ ?>
<?php $backUrl = $this->getUrl('customer/account'); ?>
<?php $_helper = Mage::helper("customer"); ?>
<?php $customer = $this->getCustomer(); ?>
<?php
/** @var Ced_SocialLogin_Helper_Data $socialLoginHelper */
$socialLoginHelper = Mage::helper("sociallogin");

/** @var Ced_SocialLogin_Block_Google_Button $socialLoginGoogle */
$socialLoginGoogle = $this->getChild('social-login-google');
$socialLoginGoogleEnabled = $socialLoginGoogle->toHtml() == false;

/** @var Ced_SocialLogin_Block_Facebook_Button $socialLoginFacebook */
$socialLoginFacebook = $this->getChild('social-login-facebook');
$socialLoginFacebookEnabled = $socialLoginFacebook->toHtml() == false;
?>

<div id="account-edit">
	<div class="page-title box-wrapper">
		<h1>
			<span><?php echo $this->__("Change password"); ?></span>
			<span class="back-sm"><a href="<?php echo $backUrl; ?>" class="underline"><?php echo $_helper->__('back: my account'); ?>&nbsp;&gt;</a></span>
			<span class="back-xs"><a href="<?php echo $backUrl; ?>" class="underline"><?php echo $_helper->__('back'); ?>&nbsp;&gt;</a></span>
		</h1>
	</div>
	<div class="background-wrapper box-wrapper container-fluid">
		<form action="<?php echo $this->getUrl('customer/account/editPass') ?>" method="post" id="editPassword-form" autocomplete="off">
			<?php echo $this->getBlockHtml('formkey')?>
			<input type="hidden" value="1" name="change_password" />
			<div class="clearfix accountfix"></div>
			<div class="form-container col-md-12">
				<div class="account_email_container account_data_container row">
					<div class="col-lg-2 col-md-3 col-sm-12 col-xs-12 account_data"><?php echo $this->__("Email address"); ?>:</div>
					<div class="col-lg-9 col-md-8 col-sm-12 col-xs-12 account_data"><?php echo $this->escapeHtml($customer->getEmail()); ?></div>
				</div>
				<div class="row">
					<div class="col-md-12">
						<div class="account_data_separator" id="account_data_separator_1"></div>
					</div>
				</div>
				<div class="account_pass_container account_data_container row">
					<label class="col-lg-2 col-md-3 col-sm-12 col-xs-12 control-label" for="customer_password"><?php echo $this->__("New password"); ?>:</label>
					<div class="col-lg-9 col-md-8 col-sm-11 col-xs-11">
						<!-- This is a dummy hidden field to trick firefox from auto filling the password -->
						<input type="text" name="dummy" id="dummy" style="display: none" />
						<input
							type="password"
							name="password"
							class="form-control password hint"
							required="true"
							id="customer_password"
							data-original-title="<?php echo $this->__("Password must contain at least 6 characters. It cannot contain spaces."); ?>"
							/>
					</div>
				</div>
				<div class="row">
					<div class="col-md-12">
						<div class="account_data_separator" id="account_data_separator_2"></div>
					</div>
				</div>
				<div class="account_confirmation_container account_data_container row">
					<label class="col-lg-2 col-md-3 col-sm-12 col-xs-12 control-label" for="customer_confirmation"><?php echo $this->__("Repeat password"); ?>:</label>
					<div class="col-lg-9 col-md-8 col-sm-11 col-xs-11">
						<input type="password"
						       name="confirmation"
						       class="form-control confirmation hint"
						       required="true"
						       id="customer_confirmation"
						       data-toggle="tooltip"
						       data-original-title="<?php echo $this->__("Repeat new password."); ?>"
							/>
					</div>
				</div>
				<div class="account_editpassword_submit_container row">
					<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
						<div class="bottom-links">
							<a class="button button-third large" href="<?php echo Mage::getUrl("customer/account");?>">
								<i class="glyphicon glyphicon-chevron-left"></i>
								<?php echo $_helper->__('back') ?>
							</a>
							<button type="submit" class="btn button button-primary pull-right">
								<?php echo $_helper->__("Save"); ?>
							</button>
							<div class="clearfix"></div>
						</div>
					</div>
				</div>

				<?php if($socialLoginFacebookEnabled || $socialLoginGoogleEnabled): ?>
				<div class="row">
					<div class="col-md-12">
						<div class="account_data_separator" id="account_data_separator_3"></div>
					</div>
				</div>
				<?php endif; ?>

				<?php if($socialLoginFacebookEnabled): ?>
				<div class="row">
					<div class="col-lg-2 col-md-3 col-sm-12 col-xs-12 social-login-button-container">
						<?php
						/** @var Ced_SocialLogin_Block_Facebook_Button $socialLoginFacebook */
						$socialLoginFacebook = $this->getChild('social-login-facebook');
						?>
						<?php echo $socialLoginFacebook->toHtml(); ?>
					</div>
					<div class="col-lg-9 col-md-8 col-sm-12 col-xs-12">
						<div class="social-login-caption">
							<?php if($socialLoginFacebook->isLogged()): ?>
								<?php echo $socialLoginHelper->__("Your accounts are connected. Right now you can login using your Facebook account."); ?>
							<?php else: ?>
								<?php echo $socialLoginHelper->__("Connect your account to be able to login using Facebook account."); ?>
							<?php endif; ?>
						</div>
					</div>
				</div>
				<?php endif; ?>

				<?php if($socialLoginFacebookEnabled && $socialLoginGoogleEnabled): ?>
				<div class="row">
					<div class="col-md-12">
						<div class="account_data_separator" id="account_data_separator_4"></div>
					</div>
				</div>
				<?php endif; ?>

				<?php if($socialLoginGoogleEnabled): ?>
				<div class="row">
					<div class="col-lg-2 col-md-3 col-sm-12 col-xs-12 social-login-button-container">
						<?php
						/** @var Ced_SocialLogin_Block_Google_Button $socialLoginGoogle */
						$socialLoginGoogle = $this->getChild('social-login-google');
						?>
						<?php echo $socialLoginGoogle->toHtml(); ?>
					</div>
					<div class="col-lg-9 col-md-8 col-sm-12 col-xs-12">
						<div class="social-login-caption">
							<?php if($socialLoginGoogle->isLogged()): ?>
								<?php echo $socialLoginHelper->__("Your accounts are connected. Right now you can login using your Google account."); ?>
							<?php else: ?>
								<?php echo $socialLoginHelper->__("Connect your account to be able to login using Google account."); ?>
							<?php endif; ?>
						</div>
					</div>
				</div>
				<?php endif; ?>
			</div>
		</form>
	</div>
</div>
<script>
	function addPasswordEditTranslations() {
		Mall.translate.add(
			"Please enter current password.",
			"<?php echo $this->__("Please enter current password."); ?>"
		);
		Mall.translate.add(
			"Please enter new password.",
			"<?php echo $this->__("Please enter new password."); ?>"
		);
		Mall.translate.add(
			"Password needs to have at least 6 characters",
			"<?php echo $this->__("Password needs to have at least 6 characters"); ?>"
		);
		Mall.translate.add(
			"Please repeat new password.",
			"<?php echo $this->__("Please repeat new password."); ?>"
		);
		Mall.translate.add(
			"Passwords must match",
			"<?php echo $this->__("Passwords must match"); ?>"
		)
	}

	<?php if($this->getCustomer()->getChangePassword()): ?>
	setPasswordForm(true);
	<?php endif; ?>
</script>