<?php /* @var $this Mage_Customer_Block_Form_Edit */ ?>
<?php $backUrl = $this->getUrl('customer/account'); ?>
<?php $_helper = Mage::helper("customer"); ?>
<?php $customer = $this->getCustomer(); ?>
<?php $isNew = !$customer->getFirstname() || !$customer->getLastname() ? true : false; ?>
<div id="account-edit">
	<div class="page-title box-wrapper">
		<h1>
			<span><?php echo $this->__("Contact details"); ?></span>
			<span class="back-sm"><a href="<?php echo $backUrl; ?>" class="underline"><?php echo $_helper->__('back: my account'); ?>&nbsp;&gt;</a></span>
			<span class="back-xs"><a href="<?php echo $backUrl; ?>" class="underline"><?php echo $_helper->__('back'); ?>&nbsp;&gt;</a></span>
		</h1>
	</div>
	<div class="background-wrapper box-wrapper container-fluid">
		<form action="<?php echo $this->getUrl('customer/account/editPost') ?>" method="post" id="editCustomer-form" autocomplete="off">
			<?php echo $this->getBlockHtml('formkey')?>
			<div class="clearfix accountfix"></div>
			<div class="form-container col-md-12">
				<div class="account_name_container account_data_container row">
					<?php if($isNew): ?>
						<label class="col-lg-2 col-md-3 col-sm-12 col-xs-12 control-label" for="customer_firstname"><?php echo $this->__("Firstname"); ?>:</label>
						<div class="col-lg-9 col-md-8 col-sm-11 col-xs-11">
							<input type="text"
							       name="firstname"
							       class="form-control firstname hint"
							       id="customer_firstname"
							       data-original-title="<?php echo $this->__("Enter name."); ?>"
							       value="<?php echo $customer->getFirstname(); ?>"
							/>
						</div>
						<div class="clearfix"></div>
						<label class="col-lg-2 col-md-3 col-sm-12 col-xs-12 control-label lastname-margin" for="customer_lastname"><?php echo $this->__("Lastname"); ?>:</label>
						<div class="col-lg-9 col-md-8 col-sm-11 col-xs-11 lastname-margin">
							<input type="text"
							       name="lastname"
							       class="form-control lastname hint"
							       id="customer_lastname"
							       data-original-title="<?php echo $this->__("Enter surname."); ?>"
							       value="<?php echo $customer->getLastname(); ?>"
							/>
						</div>
					<?php else: ?>
						<div class="col-lg-2 col-md-3 col-sm-12 col-xs-12 account_data"><?php echo $this->__("Name and surname"); ?>:</div>
						<div class="col-lg-9 col-md-8 col-sm-12 col-xs-12 account_data"><?php echo $this->escapeHtml($customer->getFirstname()." ".$customer->getLastname()); ?></div>
					<?php endif; ?>
				</div>
				<div class="row">
					<div class="col-md-12">
						<div class="account_data_separator" id="account_data_separator_1"></div>
					</div>
				</div>
				<div class="account_phone_container account_data_container row">
					<label class="col-lg-2 col-md-3 col-sm-12 col-xs-12 control-label" for="customer_phone"><?php echo $this->__("Phone number"); ?>:</label>
					<div class="col-lg-9 col-md-8 col-sm-11 col-xs-11">
						<?php $phone = $this->escapeHtml($customer->getPhone()); ?>
						<input type="text"
						       name="phone"
						       class="form-control phone hint"
						       id="customer_phone"
						       data-original-title="<div style='text-align: left !important;line-height: 1.4 !important;'><?php echo $this->__("Enter mobile or landline phone number."); ?><br /><?php echo $this->__("For landline remember about area code."); ?></div>"
						       value="<?php echo $phone ?>"
						       <?php if($phone): ?>required="true"<?php endif ?>
						/>
					</div>
					<div class="col-lg-offset-2 col-lg-9 col-md-offset-3 col-md-8 col-sm-11 col-xs-12 account_phone_desc">
						Numer telefonu potrzebujemy m.in. dla kuriera dostarczającego przesyłkę.<br />
						Nie wykorzystamy go w inny sposób bez Twojej zgody!
					</div>
				</div>
				<div class="row">
					<div class="col-md-12">
						<div class="account_data_separator" id="account_data_separator_2"></div>
					</div>
				</div>
				<div class="account_email_container account_data_container row">
					<label class="col-lg-2 col-md-3 col-sm-12 col-xs-12 control-label" for="customer_email"><?php echo $this->__("Email address"); ?>:</label>
					<div class="col-lg-9 col-md-8 col-sm-11 col-xs-11">
						<input type="email"
						       name="email"
						       class="form-control email hint"
						       required="true"
						       id="customer_email"
						       data-original-title="<?php echo $this->__("Enter email."); ?>"
						       value="<?php echo $this->escapeHtml($customer->getEmail()); ?>"
						/>
					</div>

				</div>
				<div class="bottom-links">
					<a class="button button-third large" href="<?php echo Mage::getUrl("customer/account");?>">
						<i class="glyphicon glyphicon-chevron-left"></i>
						<?php echo $_helper->__('back') ?>
					</a>
					<button type="submit" class="btn button button-primary pull-right">
						<?php echo $_helper->__("Save"); ?>
					</button>
					<div class="clearfix"></div>
				</div>
			</div>
		</form>
	</div>
</div>
<script>
	function addAccountEditTranslations() {
		Mall.translate.add(
			"Telephone number is too short. Number must contain 9 digits, without spacing.",
			"<?php echo $this->__("Telephone number is too short. Number must contain 9 digits, without spacing."); ?>"
		);
		Mall.translate.add(
			"Please enter phone number.",
			"<?php echo $this->__("Please enter phone number."); ?>"
		);
		Mall.translate.add(
			"Please enter correct email.",
			"<?php echo $this->__("Please enter correct email."); ?>"
		);
		Mall.translate.add(
			"Please enter email.",
			"<?php echo $this->__("Please enter email."); ?>"
		);
		Mall.translate.add(
			"This field is required",
			"<?php echo $this->__("This field is required"); ?>"
		)
	}
</script>