<div class="page-title category-title">
    <h1><?php echo $this->__('Search by Brands') ?></h1>
</div>

<form id="search_by_brands_form" action="<?php echo Mage::getUrl('solrsearch/by/brand') ?>" method="get">
    <div class="form-search">
        <label for="search"><?php echo $this->__('Search') ?>:</label>
        <input id="search" type="text" name="<?php echo $this->helper('catalogsearch')->getQueryParamName() ?>" value="<?php echo trim(trim($this->helper('catalogsearch')->getEscapedQueryText(),'"')) ?>" class="input-text" />
        <button type="submit" title="<?php echo $this->__('Search') ?>" class="button"><span><span><?php echo $this->__('Filter') ?></span></span></button>
        <span class="display-all"><a href="<?php echo Mage::getUrl('solrsearch/by/brand') ?>"><?php echo $this->__('Display all') ?></a></span>
    </div>
</form>

<?php
$brands = $this->getBrands();
?>
<?php if (count($brands) > 0):?>
	<ol id="search_by_brands_list" class="products-list">
		<?php foreach ($brands as $brand => $count):?>
			<li class="item" style="padding: 7px 10px"><a href="<?php echo Mage::getUrl('solrsearch', array('_query' => array('q' => $brand))) ?>"><?php echo $brand?> &nbsp;(<?php echo $count?>)</a></li>
		<?php endforeach;?>
	</ol>
<?php endif;?>