<div class="page-title category-title">
    <h1><?php echo $this->__('Search by Categories') ?></h1>
</div>

<form id="search_by_category_form" action="<?php echo Mage::getUrl('solrsearch/by/category') ?>" method="get">
    <div class="form-search">
        <label for="search"><?php echo $this->__('Search') ?>:</label>
        <input id="search" type="text" name="<?php echo $this->helper('catalogsearch')->getQueryParamName() ?>" value="<?php echo trim(trim($this->helper('catalogsearch')->getEscapedQueryText(),'"')) ?>" class="input-text" />
        <button type="submit" title="<?php echo $this->__('Search') ?>" class="button"><span><span><?php echo $this->__('Filter') ?></span></span></button>
        <span class="display-all"><a href="<?php echo Mage::getUrl('solrsearch/by/category') ?>"><?php echo $this->__('Display all') ?></a></span>
    </div>
</form>

<?php
$categories = $this->getCategories();
?>
<?php if (count($categories) > 0):?>
	<ol id="search_by_category_list" class="products-list">
		<?php foreach ($categories as $path => $count):?>
			<li class="item"><?php echo $this->formatCategoryPath($path, $count)?></li>
		<?php endforeach;?>
	</ol>
<?php endif;?>