<?php
$_item = $this->getItem();
/* @var $_item Mage_Sales_Model_Quote_Item */

$_itemPriceInclTax = (float)$_item->getPriceInclTax();
$_rowPriceInclTax = (float)$_item->getRowTotalInclTax();
$_discountPercent = (float)$_item->getDiscountPercent();
$_discountAmount = (float)$_item->getDiscountAmount();

$_productMsrpPrice = $_itemPriceInclTax;

if($_item->getProduct()){
	$_productMsrpPrice = $_item->getProduct()->getStrikeoutPrice();
}

$_qty = $this->getQty($_item);
$_helper = Mage::helper("zolagocataloginventory");
$isVisibleProduct = $_item->getProduct()->isVisibleInSiteVisibility();
$canApplyMsrp = Mage::helper('catalog')->canApplyMsrp($_item->getProduct(), Mage_Catalog_Model_Product_Attribute_Source_Msrp_Type::TYPE_BEFORE_ORDER_CONFIRM);
?>

	<div class="table-heading hidden-xs">
		<div class="hcena"><?php echo $this->__("Price");?></div>
		<div class="hilosc"><?php echo $this->__("Quantity");?></div>
		<div class="hwartosc"><?php echo $this->__("Value");?></div>
	</div>

	<div class="table-group clearfix">
		<div class="tabcol-2">
			<div class="ilosc">
				<span class="lb visible-xs"><?php echo $this->__("Quantity");?>:</span> 
				<span><?php echo $this->getQty($_item); ?></span>
			</div>
			<div class="cena">
				<?php if(round($_productMsrpPrice,2)>$_itemPriceInclTax):?>
				<span class="stara_cena">
					<?php echo Mage::helper("core")->formatPrice($_productMsrpPrice, false);?>
				</span>
				<?php endif;?>
				<span class="cena_zakupu">
					<?php echo Mage::helper("core")->formatPrice($_itemPriceInclTax, false);?>
				</span>
			</div>
			<div class="wartosc hidden-xs">
				<span class="wartosc_zakupu">
					<?php echo Mage::helper("core")->formatPrice($_itemPriceInclTax * $_qty, false);?>
				</span>
			</div>
		</div>
		<div class="tabcol-1">
			<div class="zdjecie">
				<img src="<?php echo $this->getProductThumbnail()->resize(53, 69); ?>" alt="<?php echo $this->escapeHtml($this->getProductName()) ?>"/>
			</div>
			<div class="nazwa_rozmiar">
				<dl>
					<dt class="nazwa_produktu"><?php echo $this->escapeHtml($this->getProductName()) ?></dt>
					<?php if ($_options = $this->getOptionList()):?>
                    <?php foreach ($_options as $_option) : ?>
                        <?php $_formatedOptionValue = $this->getFormatedOptionValue($_option) ?>
						<dd class="rozmiar_produktu"><?php echo $this->escapeHtml($_option['label']) ?>: <?php echo $_formatedOptionValue['value'] ?></dd>
                    <?php endforeach; ?>
                <?php endif;?>
				</dl>
			</div>
		</div>
	</div>

