<section class="section">
	<header class="title-section">
		<h2>Nie masz konta?</h2>

	</header>
	<ul class="benefits list bullet_01">
		<li>możesz je łatwo założyć przy składaniu zamówienia</li>
		<li>możesz zrobić zakupy bez rejestracji</li>
	</ul>

	<footer class="footer-section">
		<a title="Create an Account" class="button button-primary large link pull-right" href="#"><span><span>Kontynuuj</span></span></a>
	</footer>
</section>