<?php
$_element = $this->getElement();
$this->setFieldName($_element->getName());
$fValue = $_element->getValue();
//krumo($fValue);
?>

<div class="grid">
    <input id="<?php echo $this->getFieldName()?>" type="hidden" />
    <table cellspacing="0" class="data" id="<?php echo $this->suffixId('cfgTable')?>" style="width:70px">
        <col width="200" />
        <col width="300" />
        <col width="300" />
        <col width="100" />
        <thead>
            <tr class="headings">
                <th><?php echo Mage::helper('zolagobanner')->__('Type Name') ?></th>
                <th><?php echo Mage::helper('zolagobanner')->__('Images') ?></th>
                <th><?php echo Mage::helper('zolagobanner')->__('Captions') ?></th>
                <th><?php echo Mage::helper('zolagobanner')->__('Action') ?></th>
            </tr>
            <tr id="<?php echo $this->suffixId('rowTpl')?>" style="display:none">
                <td>
                    <h3><?php echo Mage::helper('zolagobanner')->__('Name')?></h3>
                    <input type="text" class="input-text" name="<?php echo $this->getFieldName()?>[$$ROW][title]" value="$$TITLE" style="width:200px" />
                    <input id="<?php echo $this->getFieldName()?>" type="hidden" />
                </td>
                <td>
                    <h3><?php echo Mage::helper('zolagobanner')->__('Image Definition')?></h3>

                    <div class="image_def-fieldset">
                        <div class="grid">

                            <table cellspacing="0" class="data" id="<?php echo $this->suffixId('cfgTable')?>" style="width:70px">
                                <col width="150" />
                                <col width="70" />
                                <col width="70" />
                                <thead>
                                <tr class="headings">
                                        <th><?php echo Mage::helper('zolagobanner')->__('Number Of Pictures') ?></th>
                                        <th><?php echo Mage::helper('zolagobanner')->__('Image Resolution') ?></th>
                                        <th><?php echo Mage::helper('zolagobanner')->__('Picture Url') ?></th>
                                </tr>
                                </thead>
                                <tfoot>
                                </tfoot>
                                <tbody>
                                <tr>
                                        <td>
                                            <input type="text" class="input-text" type="text"  name="<?php echo $this->getFieldName()?>[$$ROW][pictures_number]" style="width:50px;" value="$$PICTURES_NUMBER" />
                                        </td>
                                        <td>
                                            <table>
                                                <tr>
                                                    <td>
                                                        <?php echo Mage::helper('zolagobanner')->__('Desktop Image') ?>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td><?php echo Mage::helper('zolagobanner')->__('Width') ?>: <input type="text" class="input-text" name="<?php echo $this->getFieldName()?>[$$ROW][pictures_w]" value="$$PICTURES_W" style="width:50px;" /> px</td>
                                                </tr>
                                                <tr>
                                                    <td><?php echo Mage::helper('zolagobanner')->__('Height') ?>: <input type="text" class="input-text" name="<?php echo $this->getFieldName()?>[$$ROW][pictures_h]" value="$$PICTURES_H" style="width:50px;" /> px</td>
                                                </tr>
                                                <tr>
                                                    <td><?php echo Mage::helper('zolagobanner')->__('Mobile Devices Image') ?></td>
                                                </tr>
                                                <tr>
                                                    <td><?php echo Mage::helper('zolagobanner')->__('Width') ?>: <input type="text" class="input-text" name="<?php echo $this->getFieldName()?>[$$ROW][pictures_w_m]" value="$$PICTURES_W_M" style="width:50px;" /> px</td>
                                                </tr>
                                                <tr>
                                                    <td><?php echo Mage::helper('zolagobanner')->__('Height') ?>: <input type="text" class="input-text" name="<?php echo $this->getFieldName()?>[$$ROW][pictures_h_m]" value="$$PICTURES_H_M" style="width:50px;" /> px</td>
                                                </tr>
                                            </table>
                                        </td>
                                        <td>
                                            <span><?php echo Mage::helper('zolagobanner')->__('Can Be Empty')?></span>
                                            <input alt="is_required" name="<?php echo $this->getFieldName()?>[$$ROW][picture_can_be_empty]" value="1" style="width:50px" $$$$ type="checkbox" />
                                        </td>

                                </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>

                </td>
                <td>
                    <h3><?php echo Mage::helper('zolagobanner')->__('Caption Definition')?></h3>

                    <div class="caption_def-fieldset">
                        <div class="grid">
                            <table cellspacing="0" class="data" id="<?php echo $this->suffixId('cfgTable')?>" style="width:70px">
                                <col width="150" />
                                <col width="70" />
                                <col width="70" />
                                <thead>
                                <tr class="headings">
                                    <th><?php echo Mage::helper('zolagobanner')->__('Number Of Captions') ?></th>
                                    <th><?php echo Mage::helper('zolagobanner')->__('Caption Max. Symbols') ?></th>
                                    <th><?php echo Mage::helper('zolagobanner')->__('Caption Url') ?></th>
                                </tr>
                                </thead>
                                <tfoot>
                                </tfoot>
                                <tbody>
                                <tr>
                                    <td>
                                        <input type="text" class="input-text"  name="<?php echo $this->getFieldName()?>[$$ROW][captions_number]" style="width:50px;" value="$$CAPTIONS_NUMBER" />
                                    </td>
                                    <td>
                                        <input type="text" class="input-text" name="<?php echo $this->getFieldName()?>[$$ROW][caption_max_symbols]" value="$$CAPTION_MAX_SYMBOLS" style="width:50px;" />
                                    </td>
                                    <td>
                                        <span><?php echo Mage::helper('zolagobanner')->__('Can Be Empty')?></span>
                                        <input alt="is_required" name="<?php echo $this->getFieldName()?>[$$ROW][caption_can_be_empty]" value="1" style="width:50px" $$$$ type="checkbox" />
                                    </td>

                                </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>


                </td>
                <td>
                    <button type="button" class="scalable delete delete-fieldset"><span><?php echo $this->__('Remove') ?></span></button>
                </td>
            </tr>
        </thead>
        <tfoot>
            <tr>
                <th colspan="5" class="a-left">
                    <div class="left"><button type="button" class="scalable add" id="<?php echo $this->suffixId('addBtn')?>">
                            <span>+ <?php echo $this->__('Add Type') ?></span>
                        </button>
                    </div>
                </th>
            </tr>
        </tfoot>
        <tbody class="fieldset_config_body">
        </tbody>
    </table>
</div>

<style type="text/css">
</style>

<script type="text/javascript">
//<![CDATA[
(function ()
{
    window['udprodFields'] = <?php echo $this->getEditFieldsConfigSelect2Json()?>;
    var lastRowNum = 0;
    var tbody = $$('#<?php echo $this->suffixId('cfgTable')?> tbody.fieldset_config_body')[0]

    function addRow(inData)
    {
        var rowHtml = $('<?php echo $this->suffixId('rowTpl')?>').innerHTML
        var data = {
            title: '',
            pictures_number: '',
            pictures_w: '',
            pictures_h: '',
            pictures_w_m: '',
            pictures_h_m: '',
            picture_can_be_empty: '',
            captions_number: '',
            caption_max_symbols: '',
            caption_can_be_empty: ''
        }
        Object.extend(data, inData);
        data.row = ++lastRowNum;

        var isIE = (/msie [1-8]\./i).test(navigator.userAgent);
        var numericVars = ['sort_order'];
        var forcedNumericVars = [];
        var keys = $H(data).keys().sortBy(function(s){return (''+s).length}).reverse();
        for (j=0; j<keys.length; j++) {
            var i=keys[j];
            value = data[i] || ''
            if (-1 != numericVars.indexOf(i) && data[i]
                || -1 != forcedNumericVars.indexOf(i)
            ) {
                value *= 1;
                data[i] = value;
            }
            if (i!=='row' && isIE) value = '"'+value+'"';

            rowHtml = rowHtml.replace(new RegExp('\\$\\$'+i.toUpperCase(), 'g'), value);
            if(data.picture_can_be_empty == 1 || data.caption_can_be_empty == 1) {
                rowHtml = rowHtml.replace(new RegExp('\\$\\$\\$\\$', 'g'), 'checked="checked"');
            }

        }

        tbody.insert('<tr>'+rowHtml+'</tr>')
        var trs = tbody.childElements()
        var tr = trs[trs.length-1]
        tr.addClassName(lastRowNum%2 ? 'odd' : 'even')
        var del = $(tr).select('button.delete-fieldset')[0];
        if (del) {
            $(del).observe('click', function(e) { e.stop(); $(del.parentNode.parentNode).remove() })
        }
        (function () {
        $A(['image_def','caption_def']).each(function(colKey){
            if (Object.isArray(data[colKey]) && data[colKey].length>0) {
                var colAddBtnId = tr.down('.'+colKey+'-fieldset button.add').id;
                $A((data[colKey])).each(function(colRowData){
                    window[colAddBtnId+'udpAddRow'](colRowData);
                });
            }
        });
        }).defer();
    }

    $('<?php echo $this->suffixId('addBtn')?>').observe('click', function(e) { e.stop(); addRow() });

<?php if (is_array($fValue)): foreach ($fValue as $fV): ?>
    addRow(<?php echo Zend_Json::encode($fV) ?>);
<?php endforeach; endif; ?>
})();
//]]>
</script>



