<?php /* @var $this Mage_Catalog_Block_Product_View_Media */ ?>
<?php
$_product = $this->getProduct();
$_helper = $this->helper('catalog/output');
$_zolagoCatalogBlock = Mage::getBlockSingleton('zolagocatalog/product_view');
$_images = $this->getGalleryImages();
?>
<?php if (count($_images)): ?>
	<?php $_dimensions = array(); ?>
	<?php foreach ($_images as $k => $_image): ?>
		<?php $_dimensions[$k] = @getimagesize($_image->getPath()); ?>
	<?php endforeach; ?>
	<div id="lightbox" style="z-index: 1050">
		<div id="lightbox-inner">
			<div id="lightbox-header" class="clearfix">
				<img src="<?php echo $this->getSkinUrl('images/logo_header_lightbox.png'); ?>" alt="<?php echo $this->getLogoAlt(); ?>"
				     class="pull-left">
				<button id="lightbox-close" class="button button-third pull-right"><?php echo $this->__("Close"); ?></button>
			</div>
			<div id="lightbox-gallery">
				<div id="lightbox-gallery-thumbs">
					<div id="lightbox-gallery-thumbs-up" class="lightbox-gallery-thumbs-arrow">
						<i class="fa fa-chevron-up"></i>
					</div>
					<div id="lightbox-gallery-thumbs-images">
						<?php $slickIndex = 0; ?>
						<?php foreach ($_images as $k => $_image): ?>
							<?php if (isset($_dimensions[$k]) && is_array($_dimensions[$k]) && isset($_dimensions[$k][0], $_dimensions[$k][1])): ?>
								<div class="lightbox-gallery-thumb" data-slick-index="<?php echo $slickIndex++; ?>">
									<img
										src="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize(67, 86); ?>"
										width="67" height="86" alt="<?php echo $this->escapeHtml($_image->getLabel()) ?>"/>
								</div>
							<?php endif; ?>
						<?php endforeach; ?>
					</div>
					<div id="lightbox-gallery-thumbs-down" class="lightbox-gallery-thumbs-arrow">
						<i class="fa fa-chevron-down"></i>
					</div>
				</div>
				<?php $flag = $this->getProductFlag(); ?>
				<div id="lightbox-gallery-images"
					<?php if ($flag): ?>class="lightbox-gallery-has-flag lightbox-gallery-flag-<?php echo $flag; ?>"<?php endif; ?>>
					<?php foreach ($_images as $k => $_image): ?>
						<?php if (isset($_dimensions[$k]) && is_array($_dimensions[$k]) && isset($_dimensions[$k][0], $_dimensions[$k][1])): ?>
							<div class="lightbox-gallery-item">
								<div class="lightbox-gallery-image"
								     data-background="<?php echo $_image->getUrl(); ?>"
								     style="background-image: url('<?php echo $this->getSkinUrl("images/default-ajax-loader.gif"); ?>'); background-size: initial;"
								     data-max-width="<?php echo $_dimensions[$k][0]; ?>"
								     data-max-height="<?php echo $_dimensions[$k][1]; ?>"
								     data-ratio="<?php echo number_format((float)($_dimensions[$k][1] / $_dimensions[$k][0]), 2, '.', ''); ?>">
								</div>
							</div>
						<?php endif; ?>
					<?php endforeach; ?>
				</div>
			</div>
		</div>
	</div>
<?php endif; ?>