<div class="content-header">
   <h3><?php echo $this->getHeaderText() ?></h3>
   <p class="content-buttons form-buttons">
        <?php echo $this->getBackButtonHtml(); ?>
        <?php echo $this->getResetButtonHtml(); ?>
        <?php if ($this->getIsNew()): ?>
        <?php echo $this->getDeleteButtonHtml(); ?>
        <?php endif;?>
        <?php echo $this->getSaveButtonHtml(); ?>
    </p>
</div>
<form action="<?php echo $this->getSaveUrl() ?>" method="post" id="template_edit_form">
    <?php echo $this->getBlockHtml('formkey')?>
    <div class="no-display">
        <input type="hidden" id="change_flag_element" name="_change_type_flag" value="" />]
    </div>
    <?php echo $this->getForm() ?>
</form>
<script type="text/javascript">
//<![CDATA[
    var posForm = new varienForm('template_edit_form');
    var posControl = {
        init: function () {
            if ($('convert_button_back')) {
                $('convert_button_back').hide();
            }
            
            var regionSelect= $('region_id');
            var regionText = new Element("input", {"type": "text", "id": "region", "class": "input-text", "name": "region", "value": "<?php echo $this->escapeHtml($this->getModel()->getRegion());?>"});
            regionText.hide();
            regionSelect.insert({before: regionText});
            
            var updater = new RegionUpdater('country_id', 'region', 'region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined);
            $("use_dhl").observe("change", function(e){
				posControl.enableDhl($F(e.target)=="1");
			});
			posControl.enableDhl($F("use_dhl")=="1");
            updater.update();
        },
        save: function() {
            if (this.typeChange) {
                $('change_flag_element').value = '1';
            }
            posForm.submit();
            return false;
        },
        saveAs: function() {
            if (this.typeChange) {
                $('change_flag_element').value = '1';
            }

            $('save_as_flag').value = '1';

            posForm.submit();
            return false;
        },
        remove: function() {
            if(window.confirm("<?php echo Mage::helper('zolagopos')->__('Are you sure that you want to delete this POS?') ?>")) {
                window.location.href = '<?php echo $this->getDeleteUrl() ?>';
            }
        },			
		enableDhl: function(state){
				var login = $("dhl_login"),
					password = $("dhl_password"),
					account = $("dhl_account");
					
			
				if(!!state){
					login.className += " required-entry";
					login.up('tr').show();
					password.className += " required-entry";
					password.up('tr').show();
					account.className += " required-entry";
					account.up('tr').show();
				}else{
					login.className = login.className.replace(/\srequired-entry/g, "");
					login.up('tr').hide();
					password.className = password.className.replace(/\srequired-entry/g, "");
					password.up('tr').hide();
					account.className = account.className.replace(/\srequired-entry/g, "");
					account.up('tr').hide();
				}
			}
    };
    posControl.init();
    
</script>
