<div id="<?php echo $this->getHtmlId() ?>" class="massaction">
    <div class="pull-left inline-form-text">
		<?php if ($this->getUseSelectAll()):?>
			<a href="#" onclick="return <?php echo $this->getJsObjectName() ?>.selectAll()"><?php echo $this->__('Select All') ?></a>
			<span class="separator">|</span>
			<a href="#" onclick="return <?php echo $this->getJsObjectName() ?>.unselectAll()"><?php echo $this->__('Unselect All') ?></a>
			<span class="separator">|</span>
		<?php endif; ?>
		<a href="#" onclick="return <?php echo $this->getJsObjectName() ?>.selectVisible()"><?php echo $this->__('Select Visible') ?></a>
		<span class="separator">|</span>
		<a href="#" onclick="return <?php echo $this->getJsObjectName() ?>.unselectVisible()"><?php echo $this->__('Unselect Visible') ?></a>
		<span class="separator">|</span>
		<strong id="<?php echo $this->getHtmlId() ?>-count">0</strong> <?php echo $this->__('items selected') ?>
    </div>
    <div class="pull-right">
		<div class="entry-edit">
			<?php if ($this->getHideFormElement() !== true):?>
			<form action="" id="<?php echo $this->getHtmlId() ?>-form" method="post" class="form-inline">
			<?php endif ?>
				<?php echo $this->getBlockHtml('formkey')?>
				<div class="text-holder">
					<label><?php echo Mage::helper('zolagodropship')->__('Actions') ?></label>
				</div>
				<div class="form-group">
					<select id="<?php echo $this->getHtmlId() ?>-select" class="required-entry select absolute-advice local-validation form-control">
						<option value=""></option>
						<?php foreach($this->getItems() as $_item): ?>
							<option value="<?php echo $_item->getId() ?>"<?php echo ($_item->getSelected() ? ' selected="selected"' : '')?>><?php echo $_item->getLabel() ?></option>
						<?php endforeach; ?>
					</select>
				</div>
				<div class="form-group">
					<span class="outer-span" id="<?php echo $this->getHtmlId() ?>-form-hiddens"></span>
					<span class="outer-span" id="<?php echo $this->getHtmlId() ?>-form-additional"></span>
					<span class="field-row">
						<?php echo $this->getApplyButtonHtml() ?>
					</span>
				</div>
			<?php if ($this->getHideFormElement() !== true):?>
			</form>
			<?php endif ?>
		</div>

		<div class="hidden">
			<?php foreach($this->getItems() as $_item): ?>
				<div id="<?php echo $this->getHtmlId() ?>-item-<?php echo $_item->getId() ?>-block">
					<?php echo $_item->getAdditionalActionBlockHtml() ?>
				</div>
			<?php endforeach; ?>
		</div>
    </div>
	<div class="clearfix"></div>
</div>
<hr/>

<?php if(!$this->getParentBlock()->canDisplayContainer()): ?>
<script type="text/javascript">
    <?php echo $this->getJsObjectName() ?>.setGridIds('<?php echo $this->getGridIdsJson() ?>');
</script>
<?php endif; ?>
