<?php

/**
 * Licentia Fidelitas - Advanced Email and SMS Marketing Automation for E-Goi
 *
 * NOTICE OF LICENSE
 * This source file is subject to the Creative Commons Attribution-NonCommercial 4.0 International  
 * It is available through the world-wide-web at this URL:
 * http://creativecommons.org/licenses/by-nc/4.0/
 *
 * @title      Advanced Email and SMS Marketing Automation
 * @category   Marketing
 * @package    Licentia
 * @author     Bento Vilas Boas <bento@licentia.pt>
 * @copyright  Copyright (c) 2012 Licentia - http://licentia.pt
 * @license    Creative Commons Attribution-NonCommercial 4.0 International 
 */

?>

<div class="entry-edit">
    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend">
            <?php echo Mage::helper('fidelitas')->__('How to add a new sender') ?>
        </h4>
        <div class="form-buttons"></div>
    </div>
    <div class="fieldset">
        <table class="form-list" cellspacing="0">
            <tbody>
                <tr>
                    <td class="value"><?php echo Mage::helper('fidelitas')->__("To add senders to your account please login into your E-Goi account and navigate to 'MY ACCOUNT'/'SENDERS'/'ADD SENDER'. After that click %s to test again","<a href='".$this->getUrl('*/*/*/op/refresh')."'>Here</a>") ?></td>
                </tr>
            </tbody>
        </table>
    </div>
</div>