<?php
/** @var Zolago_Checkout_Helper_Data $helper */
$helper		= Mage::helper("zolagocheckout");


$inPostData = Zolago_Modago_Block_Checkout_Cart_Sidebar_Shipping_Map_Inpost::getPopulateMapData();
$inPostPoints = isset($inPostData["map_points"]) ? $inPostData["map_points"] : "";

?>
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal"></button>
    <h2 class="title_section"><?php echo $helper->__("Choose locker"); ?></h2>
</div>

<div class="modal-body">
    <div class="col-md-12 main_container">
        <div class="col-md-6 main_container_column">

            <div class="col-sm-10 col-md-12 row clearfix map_filter_container">
                <div class="col-sm-6 col-md-6 gui-form-control-wrapper">
                    <div class="gui-form-control">
                        <label for="name" class="gui-label"><?php echo $helper->__("City"); ?></label>
                        <select name="shipping_select_city" style="width: 100%;"  class="select2">
                            <option value=""><?php echo $helper->__("Select City"); ?></option>
                            <?php foreach ($inPostData["filters"] as $city => $value): ?>
                                <option value="<?php echo $city; ?>"><?php echo $city; ?></option>
                            <?php endforeach; ?>
                        </select>
                    </div>

                </div>
                <div class="col-sm-6 col-md-6 gui-form-control-wrapper">
                    <div class="gui-form-control">
                        <label for="name" class="gui-label"><?php echo $helper->__("Address"); ?></label>
                        <select class="select2" style="width: 100%;"   name="shipping_select_point" data-default="">
                            <option value=""><?php echo $helper->__("Choose city first"); ?></option>
                        </select>
                    </div>
                </div>

            </div>
            <div class="col-sm-10 col-md-12 row clearfix map_filter_container">
                <!--Selected Point here-->
                <div class="shipping_select_point_data"></div>
            </div>
            <div class="col-sm-10 col-md-12 row clearfix map_filter_container">
                <!--Selected Point here-->
                <div class="nearest_stores_container"></div>
            </div>
        </div>
        <div class="col-md-6 col-sm-12 main_container_column map_delivery_container_wrapper">
            <div class="col-md-12 map_delivery_container_show_up"></div>
            <div class="col-md-12 map_delivery_container">
                <div id="ghinpost_map_delivery" style="visibility:hidden;height: 350px;"></div>
            </div>
        </div>
    </div>

</div>