<?php
/**
 * Author: Paweł Chyl <pawel.chyl@orba.pl>
 * Date: 11.07.2014
 */

/** @var $this Zolago_Modago_Block_Catalog_Category */
$categoryCollection = $this->getCategoryCollection();
if ($this->getCategoryLabel() || count($categoryCollection)) : ?>
<nav id="navCategory" class="visible-xs">
    <?php if($this->getCategoryLabel()) : ?>
        <h3><?php echo $this->getCategoryLabel(); ?></h3>
        <a href="<?php echo $this->getMoveUpUrl(); ?>" class="backToCategory">
            przejdź wyżej <i class="fa fa-angle-up"></i>
        </a>
    <?php endif; ?>
    <?php if(count($categoryCollection)) : ?>
    <ul id="nav_category_mobile" class="navigation" role="navigation">
        <?php foreach ($categoryCollection as $cat) : ?>
        <li><a href="/<?php echo $cat['url']; ?>"><?php echo $cat['label']; ?></a></li>
        <?php endforeach; ?>
    </ul>
    <?php endif; ?>
</nav>
<?php endif;?>