<?php
/**
 * Used in cms block: navigation-main-wrapper
 */

/** @var $this Zolago_Modago_Block_Catalog_Category */
$categoryCollection = $this->getCategoryCollection();
if ($this->getCategoryLabel() || count($categoryCollection)) : ?>
<nav id="navCategory" class="visible-xs">
    <?php if(count($categoryCollection)) : ?>
    <ul id="nav_category_mobile" class="navigation" role="navigation">
        <?php foreach ($categoryCollection as $cat) : ?>
            <?php if ($cat["solr_product_count"] > 0): ?>
                <li>
                    <a href="<?php echo $cat['url']; ?>">
                        <?php echo $cat['name']; ?>
                        (<?php echo $cat["solr_product_count"]; //TODO ONLY FOR TEST ?>)
                    </a>
                </li>
            <?php endif; ?>
        <?php endforeach; ?>
    </ul>
    <?php endif; ?>
</nav>
<?php endif;?>