<?php if($this->isContentMode()): ?>
    <?php echo $this->getCmsBlockHtml() ?>

<?php elseif($this->isMixedMode()): ?>
    <?php echo $this->getCmsBlockHtml() ?>
    <?php echo $this->getProductListHtml() ?>

<?php else: ?>

        <?php echo $this->getChildHtml('solrsearch_result_title'); ?>
        <?php echo $this->getChildHtml('solrsearch_product_list_toolbar'); ?>

        <div id="content" class="container-fluid">
            <div class="row">
                <div class="col-sm-12">
                    <div id="sidebar" class="hidden-xs">

                        <?php echo $this->getChildHtml('searchFaces'); ?>

                    </div>
                    <div id="content-main">

                        <?php echo $this->getProductListHtml() ?>

                    </div>
                </div>
            </div>
        </div>

    </section>

<style type="text/css">
    #nav_category_mobile {display: none !important;}
</style>
<?php endif; ?>
