<?php if($this->isContentMode()): ?>
    <?php echo $this->getCmsBlockHtml() ?>
    <div id="content" class="container-fluid">
        <div class="row">
            <div class="col-sm-12">
                <div id="sidebar" class="hidden-xs">
                </div>
                <div id="content-main">
                    <?php echo $this->getChildHtml('vendor.banner'); ?>
                </div>
            </div>
        </div>
    </div>
    <section id="bottom" class="bg-w">
        <div class="container-fluid">
            <div class="col-sm-12">
                <?php echo $this->getChildHtml('vendor.banner.inspiration'); ?>
            </div>
        </div>
    </section>
    </section>
<?php elseif($this->isMixedMode()): ?>
    <?php echo $this->getCmsBlockHtml() ?>
    <?php echo $this->getProductListHtml() ?>

<?php else: ?>

        <?php echo $this->getChildHtml('solrsearch_result_title'); ?>
        <?php echo $this->getChildHtml('solrsearch_product_list_toolbar'); ?>

        <div id="content" class="container-fluid">
            <div class="row">
                <div class="col-sm-12">
                    <div id="sidebar" class="hidden-xs">

                        <?php echo $this->getChildHtml('searchFaces'); ?>

                    </div>
                    <div id="content-main">

                        <?php echo $this->getProductListHtml() ?>

                    </div>
                </div>
            </div>
        </div>

    </section>

<?php endif; ?>