<?php if($this->isContentMode()): ?>
            <?php //echo $this->getChildHtml('banner_result_title'); ?>
            <div id="content" class="container-fluid">
                <div class="row">
                    <div class="col-sm-12">
                        <div id="sidebar" class="hidden-xs clearfix">
                            <?php echo $this->getSidebarWrapper(); ?>
                        </div>
                        <div id="content-main">
                            <?php echo $this->getChildHtml('vendor.banner'); ?>
                        </div>
                    </div>
                </div>
            </div>
    <script type="text/javascript">
        jQuery(".wrapp-section").removeClass("bg-w");
    </script>
<?php elseif($this->isMixedMode()): ?>
    <?php echo $this->getCmsBlockHtml() ?>
    <?php echo $this->getProductListHtml() ?>

<?php else: ?>
	<section id="main" class="<?php echo $this->getElementClass(); ?>">
        <?php echo $this->getChildHtml('solrsearch_result_title'); ?>
        <?php echo $this->getChildHtml('solrsearch_product_list_activefaces'); ?>
        <?php echo $this->getChildHtml('solrsearch_product_list_toolbar'); ?>
        <div id="content" class="container-fluid">
            <div class="row">
                <div class="col-sm-12">
                    <div id="sidebar" class="hidden-xs">
                        <?php echo $this->getChildHtml('searchFaces'); ?>
                    </div>
                    <div id="content-main">
                        <?php echo $this->getProductListHtml() ?>
                    </div>
                </div>
            </div>
        </div>
    </section>

<style type="text/css">
    #nav_category_mobile {display: none !important;}
    #navCategory {display: none !important;}
</style>
    <script type="text/javascript">
        jQuery(document).ready(function() {
	        jQuery("#navCategory").removeClass("visible-xs");
	        Mall.translate.add("You","<?php echo $this->__("You"); ?>");
        });
    </script>
<?php endif; ?>
