<?php
$_element = $this->getElement();
$this->resetIdSuffix();
$this->setFieldName($_element->getName());
$fValue = $_element->getValue();
$isStatuses = strpos($_element->getName(), '[statuses]')!==false;
$_yesnoOpts = Mage::getSingleton('udropship/source')->setPath('yesno')->toOptionHash();
?>

<div class="grid">
    <input id="<?php echo $this->getFieldName()?>" type="hidden" />
    <table cellspacing="0" class="data" id="<?php echo $this->suffixId('cfgTable')?>" style="width:70px">
        <col width="80" />
        <col width="150" />
        <?php if ($isStatuses):?>
            <col width="300" />
            <col width="50" />
            <col width="50" />
        <?php endif ?>
        <col width="50" />
        <col width="100" />
        <thead>
        <tr class="headings">
            <th><?php echo Mage::helper('udropship')->__('Code') ?></th>
            <th><?php echo Mage::helper('udropship')->__('Title') ?></th>
            <?php if ($isStatuses):?>
                <th><?php echo Mage::helper('udropship')->__('Edit Address') ?></th>
                <th><?php echo Mage::helper('udropship')->__('Print Shipping Label') ?></th>
                <th><?php echo Mage::helper('udropship')->__('Vendor Comment') ?></th>
                <th><?php echo Mage::helper('udropship')->__('Customer Comment') ?></th>
                <th><?php echo Mage::helper('udropship')->__('Notify Customer') ?></th>
                
                <th><?php echo Mage::helper('udropship')->__('Customer Notes') ?></th>
                <th><?php echo Mage::helper('udropship')->__('Allow resolution notes') ?></th>
                <th><?php echo Mage::helper('udropship')->__('Show Receiver To Customer') ?></th>
                <th><?php echo Mage::helper('udropship')->__('Notify status by Email') ?></th>
            <?php endif ?>
            <th><?php echo Mage::helper('udropship')->__('Max. Response days') ?></th>
            <th><?php echo Mage::helper('udropship')->__('Sort Order') ?></th>

            <!-- <th><?php //echo Mage::helper('udropship')->__('Action') ?></th> -->
        </tr>
        <tr id="<?php echo $this->suffixId('rowTpl')?>" style="display:none">
            <td>
                <input type="text" class="input-text" name="<?php echo $this->getFieldName()?>[$ROW][code]" value="$CODE" style="width:80px" />
            </td>
            <td>
                <input type="text" class="input-text" name="<?php echo $this->getFieldName()?>[$ROW][title]" value="$TITLE" style="width:150px" />
            </td>
            <?php if ($isStatuses):?>
                <td>
	                <select name="<?php echo $this->getFieldName()?>[$ROW][edit_address]" style="width:50px">
	                    <?php foreach ($_yesnoOpts as $_id=>$_name): ?>
	                        <option alt="edit_address" value="<?php echo $_id ?>"><?php echo $this->htmlEscape($_name) ?></option>
	                    <?php endforeach ?>
	                </select>
                </td>
                
                <td>
	                <select name="<?php echo $this->getFieldName()?>[$ROW][print_shipping_label]" style="width:50px">
	                    <?php foreach ($_yesnoOpts as $_id=>$_name): ?>
	                        <option alt="print_shipping_label" value="<?php echo $_id ?>"><?php echo $this->htmlEscape($_name) ?></option>
	                    <?php endforeach ?>
	                </select>
                </td>
                
                <td>
	                <select name="<?php echo $this->getFieldName()?>[$ROW][vendor_comment]" style="width:50px">
	                    <?php foreach ($_yesnoOpts as $_id=>$_name): ?>
	                        <option alt="vendor_comment" value="<?php echo $_id ?>"><?php echo $this->htmlEscape($_name) ?></option>
	                    <?php endforeach ?>
	                </select>
                </td>
                
                <td>
	                <select name="<?php echo $this->getFieldName()?>[$ROW][customer_comment]" style="width:50px">
	                    <?php foreach ($_yesnoOpts as $_id=>$_name): ?>
	                        <option alt="customer_comment" value="<?php echo $_id ?>"><?php echo $this->htmlEscape($_name) ?></option>
	                    <?php endforeach ?>
	                </select>
                </td>
                
                <td>
	                <select name="<?php echo $this->getFieldName()?>[$ROW][notify_customer]" style="width:50px">
	                    <?php foreach ($_yesnoOpts as $_id=>$_name): ?>
	                        <option alt="notify_customer" value="<?php echo $_id ?>"><?php echo $this->htmlEscape($_name) ?></option>
	                    <?php endforeach ?>
	                </select>
                </td>
                
                <td>
                    <textarea class="input-text" name="<?php echo $this->getFieldName()?>[$ROW][customer_notes]" style="width:300px; height: 80px">$CUSTOMER_NOTES</textarea>
                </td>
                
                <td>
	                <select name="<?php echo $this->getFieldName()?>[$ROW][allow_resolution_notes]" style="width:50px">
	                    <?php foreach ($_yesnoOpts as $_id=>$_name): ?>
	                        <option alt="allow_resolution_notes" value="<?php echo $_id ?>"><?php echo $this->htmlEscape($_name) ?></option>
	                    <?php endforeach ?>
	                </select>
                </td>
                <td>
                    <select name="<?php echo $this->getFieldName()?>[$ROW][show_receiver]" style="width:50px">
                        <?php foreach ($_yesnoOpts as $_id=>$_name): ?>
                            <option alt="show_receiver" value="<?php echo $_id ?>"><?php echo $this->htmlEscape($_name) ?></option>
                        <?php endforeach ?>
                    </select>
                </td>
                <td>
                    <select name="<?php echo $this->getFieldName()?>[$ROW][notify_email]" style="width:50px">
                        <?php foreach ($_yesnoOpts as $_id=>$_name): ?>
                            <option alt="notify_email" value="<?php echo $_id ?>"><?php echo $this->htmlEscape($_name) ?></option>
                        <?php endforeach ?>
                    </select>
                </td>
            <?php endif ?>
            <td>
                <input type="text" class="input-text" name="<?php echo $this->getFieldName()?>[$ROW][max_response_days]" value="$MAX_RESPONSE_DAYS" style="width:50px" />
            </td>
            <td>
                <input type="text" class="input-text" name="<?php echo $this->getFieldName()?>[$ROW][sort_order]" value="$SORT_ORDER" style="width:50px" />
            </td>
        </tr>
        </thead>
        <tfoot style="display:none;">
        <tr>
            <th colspan="7" class="a-left">
                <div class="left"><button type="button" class="scalable add" id="<?php echo $this->suffixId('addBtn')?>"><span>+ <?php echo $this->__('Add') ?></span></button></div>
            </th>
        </tr>
        </tfoot>
        <tbody class="<?php echo $this->suffixId('body')?>">
        </tbody>
    </table>

</div>

<style type="text/css">
</style>

<script type="text/javascript">
//<![CDATA[
(function ()
{
    var lastRowNum = 0;
    var tbody = $$('#<?php echo $this->suffixId('cfgTable')?> tbody.<?php echo $this->suffixId('body')?>')[0]

    function addRow(inData)
    {
        var rowHtml = $('<?php echo $this->suffixId('rowTpl')?>').innerHTML
        var data = {
            customer_notes: '',
            title: '',
            code: '',
            allow_resolution_notes: '0',
            show_receiver: '0',
            max_response_days: '',
            sort_order: '0',
            notify_email: '0'
        }
        Object.extend(data, inData);
        data.row = ++lastRowNum;
        var isIE = (/msie [1-8]\./i).test(navigator.userAgent);
        var escapeVars = ['customer_notes'];
        var numericVars = ['sort_order'];
        var forcedNumericVars = [];
        var keys = $H(data).keys().sortBy(function(s){return (''+s).length}).reverse();
        for (j=0; j<keys.length; j++) {
            var i=keys[j];
            value = data[i] || '';
//console.log(keys);
            if (-1 != numericVars.indexOf(i) && data[i]
                || -1 != forcedNumericVars.indexOf(i)
                ) {
                value *= 1;
                data[i] = value;
            }
            if (i!=='row' && isIE) value = '"'+value+'"';
            if (-1!=escapeVars.indexOf(i)) value = (''+value).escapeHTML();
            rowHtml = rowHtml.replace(new RegExp('\\$'+i.toUpperCase(), 'g'), value)
        }
        var regExTpl = [
            new Template('<option (([^>]*(alt="?#{key}"?|value="?#{value}"?(?=[\\s>]))){2})'),
            new Template('<option $1 selected="selected"'),
            new Template('<input (([^>]*(alt="?#{key}"?|value="?#{value}"?(?=[\\s>])|type="?checkbox"?)){3})'),
            new Template('<input $1 checked="checked"')
        ];
        var selectFields = ['allow_resolution_notes','show_receiver', "print_shipping_label", "customer_comment", "notify_customer", "vendor_comment", "edit_address", "notify_email"];
        selectFields.each(function(key){
            for (var rxIdx=0; rxIdx<regExTpl.length; rxIdx+=2) {
                var varForEval = {key: key, value: data[key]};
                var rxFind = regExTpl[rxIdx].evaluate(varForEval);
                var rxReplace = regExTpl[rxIdx+1].evaluate(varForEval);
                rowHtml = rowHtml.replace(new RegExp(rxFind, 'i'), rxReplace);
            }
        });


        tbody.insert('<tr>'+rowHtml+'</tr>')
        var trs = tbody.childElements()
        var tr = trs[trs.length-1]
        tr.addClassName(lastRowNum%2 ? 'odd' : 'even')
        var del = $(tr).select('button.delete-fieldset')[0];
        if (del) {
            $(del).observe('click', function(e) { e.stop(); $(del.parentNode.parentNode).remove() })
        }
    }

    $('<?php echo $this->suffixId('addBtn')?>').observe('click', function(e) { e.stop(); addRow() });
    <?php if (is_array($fValue)): foreach ($fValue as $fV): ?>
    addRow(<?php echo Zend_Json::encode($fV) ?>);
    <?php endforeach; endif; ?>
})();
//]]>
</script>