<?php
/* @var $this Zolago_Modago_Block_Sales_Order_Item_Renderer_Default */
$_item = $this->getItem();
$_helper = Mage::helper("zolagocataloginventory");
$_product =$this->getItem()->getOrderItem()->getProduct();

$mediaGallery = $_product->getData('media_gallery');

$canApplyMsrp = Mage::helper('catalog')->canApplyMsrp($_item->getOrderItem()->getProduct(), Mage_Catalog_Model_Product_Attribute_Source_Msrp_Type::TYPE_BEFORE_ORDER_CONFIRM);
?>
<div class="table-row clearfix">
    <div class="colgroup-01 clearfix">
        <div class="clearfix">
            <figure>
                    <img src="<?php echo $this->getProductThumbnail()->resize(53, 69); ?>"
                         alt="<?php echo $this->escapeHtml($this->getProductName()) ?>"/>
            </figure>
            <div class="description_checked_product">
                <div class="product_name"><?php echo $this->escapeHtml($this->getProductName()) ?></div>
                <?php if ($_options = $this->getOptionList()):?>
                    <?php foreach ($_options as $_option) : ?>
                        <?php $_formatedOptionValue = $this->getFormatedOptionValue($_option) ?>

                        <div class="product_size"><?php echo $this->escapeHtml($_option['label']) ?>: <?php echo $_formatedOptionValue['value'] ?>
                            <?php if (isset($_formatedOptionValue['full_view'])): ?>
                                <div class="truncated_full_value">
                                    <?php echo $this->escapeHtml($_option['label']) ?>:
                                    <?php echo $_formatedOptionValue['full_view'] ?>
                                </div>
                            <?php endif; ?>
                        </div>
                    <?php endforeach; ?>
                <?php endif;?>
            </div>
        </div>
    </div>
    <div class="colgroup-02 clearfix">
        <div class="colgroup clearfix">
            <div class="col">
                <div class="cena hidden-xs"><span class="cart-price"><span class="price"></span></span>
                </div>
                <div class="ilosc">

                    <div class="small">Ilość:&nbsp;<?php echo round($_item->getQty()); ?>
                    </div>
                </div>

                <!--Sub total starts here -->
                <?php if (($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()) && !$_item->getNoSubtotal()): ?>
                    <div class="a-right" style="padding-top:5px;">
                        <?php
                        $_incl = $this->helper('checkout')->getSubtotalInclTax($_item);
                        //minus discount
                        $_incl = $_incl - $_item->getData('discount_amount');
                        ?>
                            <span class="cart-price">
                                <?php if (!empty($canApplyMsrp)): ?>
                                    <span class="cart-msrp-subtotal">--</span>
                                <?php else: ?>
                                    <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(0, 1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                                        <?php echo $this->helper('checkout')->formatPrice($_incl + Mage::helper('weee')->getRowWeeeTaxInclTax($_item)); ?>
                                    <?php else: ?>
                                        <?php echo $this->helper('checkout')->formatPrice($_incl-$_item->getWeeeTaxRowDisposition()) ?>
                                    <?php endif; ?>
                                <?php endif; ?>

        </span>


                            <?php if (Mage::helper('weee')->getApplied($_item)): ?>

                                <div class="cart-tax-info" id="subtotal-item-tax-details<?php echo $_item->getId(); ?>" style="display:none;">
                                    <?php if (Mage::helper('weee')->typeOfDisplay($_item, 1, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                                        <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                                            <span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['row_amount_incl_tax'],true,true); ?></span>
                                        <?php endforeach; ?>
                                    <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                                        <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                                            <span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['row_amount_incl_tax'],true,true); ?></span>
                                        <?php endforeach; ?>
                                    <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 4, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                                        <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                                            <span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['row_amount_incl_tax'],true,true); ?></span>
                                        <?php endforeach; ?>
                                    <?php endif; ?>
                                </div>

            <?php if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                                    <div class="cart-tax-total" onclick="taxToggle('subtotal-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
                                        <span class="weee"><?php echo Mage::helper('weee')->__('Total incl. tax'); ?>: <?php echo $this->helper('checkout')->formatPrice($_incl + Mage::helper('weee')->getRowWeeeTaxInclTax($_item)); ?></span>
                                    </div>
                                <?php endif; ?>
                            <?php endif; ?>
                    </div>
                <?php endif; ?>
            </div>
        </div>
    </div>
</div>
