<div>

	<div class="content-header">
		<h3 class="icon-head head-categories">GetResponse account</h3>
	</div>

	<h3>
		Connect GetResponse Account
	</h3>

	<form method="post"
		  action="<?php echo Mage::helper("adminhtml")->getUrl('getresponse/index/apikey'); ?>">

		<!-- API KEY -->
		<p>
			<label class="GR_label" for="api_key">API Key</label>
			<input class="GR_api" type="text" name="api_key"
				   value="<?php if (isset($settings->api['api_key'])) : echo $settings->api['api_key']; endif ?>">

			<a class="gr-tooltip">
				<span class="gr-tip" style="width:178px">
					<span>
						You can find your API key in integration settings of your GetResponse account. Log in to GetResponse and go to My account > API & OAuth to find the key.
					</span>
				</span>
			</a>
		</p>

		<!-- GetResponse 360 -->
		<p class="GR_checkbox_handler">
			<input class="GR_checkbox" type="checkbox" name="getresponse_360_account" id="getresponse_360_account"
				<?php if ( !empty($settings->api['api_domain'])) : ?> checked="checked" <?php endif ?> value="1">
			<label class="GR_label_checkbox" for="getresponse_360_account">I've purchased the Enterprise plan.</label>
		</p>

		<div
			id="getresponse_360_account_options" <?php if (empty($settings->api['api_domain'])) : ?> style="display: none" <?php endif ?>>

			<p style="font-style: italic;">You can get this information from your account manager.</p>

			<p>
				<label class="GR_label" for="api_url">Account type</label>
				<select class="" name="api_url" id="api_url">
					<option
						value="<?php echo $settings->main['api_url_360_pl']; ?>" <?php if (isset($settings->api['api_url']) && $settings->api['api_url'] == $settings->main['api_url_360_pl']) : ?> selected="selected" <?php endif ?>>
						GetResponse360 PL
					</option>
					<option
						value="<?php echo $settings->main['api_url_360_com']; ?>" <?php if (isset($settings->api['api_url']) && $settings->api['api_url'] == $settings->main['api_url_360_com']) : ?> selected="selected" <?php endif ?>>
						GetResponse360 COM
					</option>
				</select>
			</p>

			<!-- Domain -->
			<p>
				<label class="GR_label" for="api_domain">Your domain</label>
				<input class="GR_api" type="text" name="api_domain"
					   value="<?php if (isset($settings->api['api_domain'])) : echo $settings->api['api_domain']; endif ?>">

				<a class="gr-tooltip">
					<span class="gr-tip" style="width:178px">
						<span>
							Enter your domain without protocol http:// eg: "yourdomainname.com"
						</span>
					</span>
				</a>
			</p>

		</div>

		<input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>"/>

		<!-- SUBMIT -->
		<div style="margin-left: 270px; padding-top: 10px;">
			<button type="submit" name="Submit" class="save"><span><span>Connect</span></span></button>
		</div>


		<script>
			jQuery('#getresponse_360_account').change(function () {
				var value = jQuery('#getresponse_360_account:checked').val();
				if (value == '1') {
					jQuery('#getresponse_360_account_options').show();
				}
				else {
					jQuery('#getresponse_360_account_options').hide();
				}
			});
		</script>
</div>
</form>