<div>

	<div class="content-header">
		<h3 class="icon-head head-categories">Export customer data on demand</h3>
	</div>

	<?php include_once('add_campaign.phtml'); ?>

	<form id="getresponse_export_form" method="post"
		  action="<?php echo Mage::helper("adminhtml")->getUrl('getresponse/index/exported'); ?>">

		<p>
			You can export your customer information from Magento to your GetResponse account.
			This option is useful for one time export of existing customers. Choose the campaign
			where you want to export your contacts. You can also create a new campaign for the
			Magento contacts by clicking "Add new campaign". Select if you want to update specific
			fields. When this option is off only new contacts are exported.
		</p>

		<ul class="messages">
			<li class="notice-msg">
				<ul>
					<li>
						<span>Each customer export includes all entries from your Magento database.</span>
					</li>
				</ul>
			</li>
		</ul>

		<p>
			<label class="GR_label" for="campaign_id">Select campaign</label>
			<?php
			if ( !empty($settings->campaigns)) {
				?>
				<select class="GR_input" name="campaign_id" id="campaign_id">
					<?php
					foreach ($settings->campaigns as $id => $name) {
						echo '<option value="' . $id . '">' . $name . '</option>';
					}
					?>
				</select>
			<?php }
			else {
				?>
				<span class="error">An error occurred while trying to get campaigns.</span>
				<?php
			}
			?>
			<button id="create-campaign">Add new campaign</button>
		</p>


		<p id="cycle_day_section" style="padding: 5px 0px 10px 0px;">

			<label class="GR_label"></label>

			<span>
				<input type="checkbox" class="GR_checkbox" name="gr_autoresponder" id="gr_autoresponder" value="1" />
			</span>

			<label for="gr_autoresponder">Add to autoresponder sequence</label>
			<br />
			<label class="GR_label"></label>
			<select class="GR_input" name="cycle_day" id="cycle_day"></select>
		</p>

		<p>
			<span>
				<input
					class="GR_checkbox"
					type="checkbox"
					name="gr_sync_order_data"
					id="gr_sync_order_data"
					value="1"
					/>
			</span>
			<label style="font-weight: 600;" for="gr_sync_order_data">Update contact details</label>

			<a class="gr-tooltip">
				<span class="gr-tip" style="width:178px">
					<span>
						Select this option if you want to overwrite contact details that already exist in your GetResponse database. Clear this option to keep existing data intact.
					</span>
				</span>
			</a>
		</p>

		<p>
		<div id="customNameFields" style="display: none;">
		<p>Copy Magento customer details to custom fields</p>
		<div class="gr-custom-field">
				<select class="jsNarrowSelect" name="gr_custom_field" multiple="multiple">
					<?php
					if ( !empty($settings->customs)) {
						foreach ($settings->customs as $custom) {
							echo '<option data-inputvalue="' . $custom['custom_field'] . '" value="' . $custom['custom_field'] . '" id="' . $custom['custom_field'] . '"', ($custom['default'] == '1') ? ' selected="selected"' : '', $custom['default'] == '1' ? ' disabled="disabled"' : '', '>', $custom['custom_field'], '</option>';
						}
					}
					?>
				</select>
			</div>
		</div>
		</p>

		<script>
			var sod = jQuery('#gr_sync_order_data'), cfp = jQuery('#customNameFields');
			if (sod.prop('checked') == true) {
				cfp.show();
			}
			jQuery('.jsNarrowSelect').selectNarrowDown();

			//sod.switchButton();

			function switchHandler() {
				jQuery('#gr_sync_order_data').on("click", function () {
					cfp.toggle('slow');
				});
			}
			switchHandler();

			jQuery('#campaign_id').change(function () {
				getCycleDays();
			});

			function getCycleDays() {
				var campaign_id = jQuery('#campaign_id').val(),
					day_element = jQuery('#cycle_day'),
					checkbox = jQuery('#gr_autoresponder'),
					cycles = jQuery.parseJSON('<?php echo isset($settings->campaign_days) ? addslashes(json_encode($settings->campaign_days)) : "{}"; ?>');

				if (cycles.hasOwnProperty(campaign_id)) {
					day_element.html('');
					day_element.removeAttr('disabled');
					checkbox.removeAttr('disabled');

					var obj = cycles[campaign_id];
					for (var prop in obj) {
						if (obj.hasOwnProperty(prop)) {

							var option = '<option value="' + parseInt(obj[prop].day) + '">Day ' +
								obj[prop].day + ': ' + obj[prop].name + ' (' + obj[prop].status + ')' +
								'</option>';

							day_element.append(option);
						}
					}
				} else {
					day_element.html('<option value="">no autoresponders</option>');
					day_element.attr('disabled', 'disabled');
					checkbox.attr('disabled', 'disabled');
				}
			}

			getCycleDays();

		</script>

		<input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey(); ?>"/>

		<div style="margin-left: 212px;">
			<button style="margin-top: 12px;" id="gr_export" type="submit" name="Submit" class="save">
				<span><span>Export</span></span></button>
		</div>

	</form>
</div>