<?php
/**
 * Licentia Fidelitas - Advanced Email and SMS Marketing Automation for E-Goi
 *
 * NOTICE OF LICENSE
 * This source file is subject to the Creative Commons Attribution-NonCommercial 4.0 International  
 * It is available through the world-wide-web at this URL:
 * http://creativecommons.org/licenses/by-nc/4.0/
 *
 * @title      Advanced Email and SMS Marketing Automation
 * @category   Marketing
 * @package    Licentia
 * @author     Bento Vilas Boas <bento@licentia.pt>
 * @copyright  Copyright (c) 2012 Licentia - http://licentia.pt
 * @license    Creative Commons Attribution-NonCommercial 4.0 International 
 */
?>

<?php
$report = Mage::registry('current_report');
$networks = unserialize($report->getData('networks'));
?>

<div class="grid">
    <table cellspacing="0" id="storeGrid_table" class="data">
        <thead>
            <tr class="headings">
                <th class=" no-link last"><span class="nobr"><?php echo $this->__('SMS Sent') ?></span></th>
            </tr>
        </thead>
        <tbody id="">
            <tr>
                <td class="last" >
                    <div class=" content-header" style=" color: #EB5E00;    font-size: 100px;    font-weight: bold;    padding: 40px !important;    text-align: center;">
<?php echo (int) $report->getSent() ?>
                    </div>
                </td>
            </tr>
        </tbody>
    </table>
</div>

<div class="grid">
    <table cellspacing="0" id="storeGrid_table" class="data">
        <thead>
            <tr class="headings">
                <th class=" no-link last"><span class="nobr"><?php echo $this->__('City') ?></span></th>
            </tr>
        </thead>
        <tbody id="">
            <tr>
                <td class="last" style="text-align:center" >
                    <img src="https://chart.googleapis.com/chart?cht=p3&amp;chs=700x350&amp;chd=t:<?php echo (int) $report->getDelivered() ?>,<?php echo (int) $report->getNotDelivered() ?><?php echo (int) $report->getInvalid() ?>&amp;chl=<?php echo $this->__('Delivered') . ' - ' . (int) $report->getDelivered() ?>|<?php echo $this->__('Not Delivered') . ' - ' . (int) $report->getNotDelivered() ?>|<?php echo $this->__('Invalid') . ' - ' . (int) $report->getInvalid() ?>&amp;chf=bg,s,fafafa" >
                </td>
            </tr>
        </tbody>
    </table>
</div>
<div class="entry-edit">
    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('NetWorks') ?></h4>
    </div>
    <div class="fieldset">
<?php foreach ($networks as $net): ?>
            <div id="storeGrid">
                <div class="grid">
                    <div class="hor-scroll">
                        <table cellspacing="0" id="storeGrid_table" class="data">
                            <thead>
                                <tr class="headings">
                                    <th colspan="2"><span class="nobr"><span class="sort-title"><?php echo $net['name'] ?></span></span></th>
                                </tr>
                            </thead>
                            <tbody id="">

                                <tr title="#" class="even pointer">
                                    <td class="a-left "><?php echo $this->__('Sent') ?></td>
                                    <td class="a-left last"><?php echo $net['sent'] ?></td>
                                </tr>
                                <tr title="#" class=" pointer">
                                    <td class="a-left "><?php echo $this->__('Sent Errors') ?></td>
                                    <td class="a-left last"><?php echo $net['sent_errors'] ?></td>
                                </tr>
                                <tr title="#" class="even pointer">
                                    <td class="a-left "><?php echo $this->__('Views') ?></td>
                                    <td class="a-left last"><?php echo $net['views'] ?></td>
                                </tr>
                                <tr title="#" class=" pointer">
                                    <td class="a-left "><?php echo $this->__('View Errors') ?></td>
                                    <td class="a-left last"><?php echo $net['view_errors'] ?></td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
<?php endforeach; ?>
    </div>
</div>