<?php
$_helper = Mage::helper("zosiaishop");
$_session = Mage::getSingleton('udropship/session');
$_vendor = $_session->getVendor();
?>
<div class="container">
    <!--=== Page Header ===-->
    <div class="page-heading row">
        <div class="col-lg-6">
            <h3><?php echo $_helper->__("IAI-Shop settings");?></h3>
        </div>
    </div>
    <div class="tabbable tabbabble-custom">
        <div class="container" style="margin-top:15px;paddign: 10px">
            <div class="row">
                <div class="col-md-12">
                    <form id="iaishop_settings" class="form-horizontal" method="post" action="/iaishop/settings/save">
                        <div class="widget box">
                            <div class="widget-header">
                                <h4><?php echo $_helper->__("IAI-Shop API Login Data"); ?></h4>
                            </div>
                            <div class="widget-content">

                                <div class="form-group">
                                    <label for="iaishop_vendor_api_key" class="col-md-3 control-label">
                                        <?php echo $_helper->__("API Login"); ?>
                                    </label>

                                    <div class="col-xs-12 col-md-9 col-lg-6">
                                        <input id="iaishop_vendor_api_key" name="iaishop_vendor_api_key" value="<?php //echo $_ghApiVendorUser->getApiKey(); ?>" type="text" class="form-control" size="10">
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="iaishop_vendor_password" class="col-md-3 control-label">
                                        <?php echo $_helper->__("API Password"); ?>
                                    </label>

                                    <div class="col-xs-12 col-md-9 col-lg-6">
                                        <input id="iaishop_vendor_password" name="iaishop_vendor_password" value="" type="password" class="form-control" size="10">
                                        <p><span class="glyphicon glyphicon-exclamation-sign"></span>&nbsp;<?php echo $_helper->__('Minimum Length - 8 characters'); ?></p>
                                    </div>
                                </div>

                            </div>
                        </div>

                        <div class="form-actions">
                            <button type="submit" id="filter_submit" class="btn btn-primary pull-right">
                                <span><?php echo $this->__('Save'); ?></span>
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

