<?php
/** @var ZolagoOs_IAIShop_Block_Settings $this */

$_helper = Mage::helper("zosiaishop");
$_session = Mage::getSingleton('udropship/session');
$data = $_session->getFormData();
$login = isset($data['login']) ? $data['login'] : $_session->getVendor()->getIaishopLogin();
/** @var Zolago_Dropship_Model_Vendor $_vendor */
$_vendor = $_session->getVendor();
?>
<div class="container">
    <!--=== Page Header ===-->
    <div class="page-heading row">
        <div class="col-lg-6">
            <h3><?php echo $_helper->__("IAI-Shop settings");?></h3>
        </div>
    </div>
    <div class="tabbable tabbabble-custom">
        <div class="container" style="margin-top:15px;paddign: 10px">
            <div class="row">
                <div class="col-md-12">
                    <form id="iaishop_settings" class="form-horizontal" method="post" action="<?php echo $this->getFormAction();?>">
                        <div class="widget box">
                            <div class="widget-header">
                                <h4><?php echo $_helper->__("IAI-Shop API Login Data"); ?></h4>
                            </div>
                            <div class="widget-content">

                                <div class="form-group">
                                    <label for="iaishop_vendor_api_key" class="col-md-3 control-label">
                                        <?php echo $_helper->__("API Login"); ?>
                                    </label>

                                    <div class="col-xs-12 col-md-9 col-lg-6">
                                        <input id="iaishop_vendor_login" name="login" value="<?php echo $login; ?>" type="text" class="form-control" size="10">
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="iaishop_vendor_password" class="col-md-3 control-label">
                                        <?php echo $_helper->__("API Password"); ?>
                                    </label>

                                    <div class="col-xs-12 col-md-9 col-lg-6">
                                        <input id="iaishop_vendor_password" name="password" value="" type="password" class="form-control" size="10">
                                        <p>&nbsp;&nbsp;&nbsp;&nbsp;<?php echo $_helper->__('Leave empty for no change');?></p>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="form-actions">
                            <button type="submit" id="filter_submit" class="btn btn-primary pull-right">
                                <span><?php echo $this->__('Save'); ?></span>
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>


<script type="text/javascript">
    jQuery(function($){
        var form = $("#iaishop_settings");
        new Zolago.formIntegrator(form);
        form.validate({
            rules: {
                "login": {
                    required: true
                },
                "password": {
                    required: true
                }
            }
        });
    });
</script>
