<?php
/* @var $this Zolago_Po_Block_Rma */
$_helper = Mage::helper("sales");
$_order = Mage::getModel('sales/order');
$backUrl = $this->getUrl('customer/account');
$list = $this->getPoList();

/** @var Zolago_Rma_Helper_Data $hlpRma */
$hlpRma = Mage::helper('zolagorma');

?>
<div class="rma">
	<div class="page-title box-wrapper">
		<h1>
			<span><?php echo $this->__("Returns and complaints"); ?></span>
			<span class="back-sm"><a href="<?php echo $backUrl; ?>" class="underline"><?php echo $_helper->__('back: my account'); ?>&nbsp;&gt;</a></span>
			<span class="back-xs"><a href="<?php echo $backUrl; ?>" class="underline"><?php echo $_helper->__('back'); ?>&nbsp;&gt;</a></span>
		</h1>
	</div>
	<div class="background-wrapper box-wrapper rma-po-list">
		<?php if($list): ?>
			<p><?php echo $this->__("Choose package which contained products that you want to return or complaint"); ?>:</p>
			<table class="po-list-table data-table po-list-md">
				<thead>
				<tr>
					<th class="po-number">
						<span class="nowrap"><?php echo $hlpRma->__("Number"); ?></span>
					</th>
					<th>
						<?php echo $this->__("Date"); ?>
					</th>

					<th>
						<?php echo $this->__("Products"); ?>
					</th>
					<th>
					</th>
				</tr>
				</thead>
				<tbody>
				<?php foreach($list as $po): ?>
					<?php /* @var $po Zolago_Po_Model_Po */ ?>
					<tr>
						<td class="po-number">
							<span class="nowrap"><?php echo $po->getIncrementId(); ?></span>
						</td>
						<td>
							<span class="nowrap"><?php echo Mage::helper('core')->formatDate($po->getCreatedAt(), 'medium', false); ?></span>
						</td>
						<td>
							<table class="po-items-table">
								<tbody>
									<?php foreach($po->getItemsCollection() as $item):?>
										<?php $thumbUrl = $this->getPoItemThumb($item,40); ?>
										<?php $item = $item->getOrderItem(); ?>
										<?php if(!$item->getParentItem()): ?>
											<?php $name = $this->escapeHtml($item->getName()); ?>
											<tr>
												<td><img src="<?php echo $thumbUrl; ?>" alt="<?php echo $name; ?>" /></td>
												<td>
												<?php echo $name; ?><br/>
												<?php foreach($this->getProductAttributes($item->getProductOptions()) as $_option): ?>
													<span class="product-attribute"><?php echo $this->escapeHtml($_option['label']); ?>: <?php echo $this->escapeHtml($_option['value']); ?></span><br/>
												<?php endforeach;?>
												</td>
											</tr>
										<?php endif; ?>
									<?php endforeach;?>
								</tbody>
							</table>
						</td>
						<td>
							<a class="button button-third large" href="<?php echo $this->getUrl('sales/po/newrma/',array('po_id'=>$po->getId()));?>"><?php echo $this->__("Select"); ?></a>
						</td>
					</tr>
				<?php endforeach; ?>
				</tbody>
			</table>
			<table class="po-list-table-mobile po-list-sm">
				<tbody>
				<?php foreach($list as $po): ?>
					<?php /* @var $po Zolago_Po_Model_Po */ ?>
					<tr>
						<td>
							<table>
								<tbody>
									<tr>
										<td>
											<span class="bold uppercase"><?php echo $this->__("Order number"); ?></span>
											<span class="nowrap"><?php echo $po->getIncrementId(); ?></span>
										</td>
										<td>
											<a class="button button-third large" href="<?php echo $this->getUrl('sales/po/newrma/',array('po_id'=>$po->getId()));?>"><?php echo $this->__("Select"); ?></a>
										</td>
									</tr>
									<tr>
										<td colspan="2">
											<span class="bold uppercase"><?php echo $this->__("Date"); ?></span>
											<span class="nowrap"><?php echo Mage::helper('core')->formatDate($po->getCreatedAt(), 'medium', false); ?></span>
										</td>
									</tr>
									<tr>
										<td colspan="2">
											<span class="bold uppercase"><?php echo $this->__("Products"); ?></span>
											<?php foreach($po->getItemsCollection() as $item):?>
												<?php $item = $item->getOrderItem(); ?>
												<?php if(!$item->getParentItem()): ?>
													<?php $name = $this->escapeHtml($item->getName()); ?>
													<span><?php echo $name; ?></span>
													<?php foreach($this->getProductAttributes($item->getProductOptions()) as $_option): ?>
														<span class="product-attribute"><?php echo $this->escapeHtml($_option['label']); ?>: <?php echo $this->escapeHtml($_option['value']); ?></span>
													<?php endforeach;?>
												<?php endif; ?>
											<?php endforeach;?>
										</td>
									</tr>
								</tbody>
							</table>
						</td>
					</tr>
				<?php endforeach; ?>
				</tbody>
			</table>
		<?php else: ?>
			<p class="rma-po-empty"><?php echo $this->__("No delivered orders"); ?></p>
		<?php endif; ?>
		<div class="bottom-links">
			<a class="button button-third large" href="<?php echo $backUrl; ?>">
				<i class="glyphicon glyphicon-chevron-left"></i>
				<?php echo $_helper->__('back') ?>
			</a>
		</div>
	</div>
</div>