<?php
/**
 * Author: Paweł Chyl <pawel.chyl@orba.pl>
 * Date: 22.08.2014
 */

?>
<?php $key = $this->getFacetKey(); ?>
<?php if ($this->getCanShow()): ?>
    <?php
    $sectionClass = $this->isFilterRolled() ? 'closed' : 'open';
    $iconClass = $this->isFilterRolled() ? "fa-chevron-down" : "fa-chevron-up";
    $isOptionSelected = false;
    $key_withoutFacet = explode("_", $key);
    array_pop($key_withoutFacet);
    ?>

    <?php
    foreach($this->getItems() as $item => $count) {
        if(!$isOptionSelected && $this->isItemActive($item)) {
            $isOptionSelected = true;
        }
    }
    ?>

    <div class="section clearfix">
        <h3 class="<?php echo $sectionClass; ?>"><?php echo $this->getFacetLabel(); ?> <i class="fa <?php echo $iconClass; ?>"></i></h3>
        <div id="filter_<?php echo $key ?>" class="content select filter-droplist" >


            <div class="select-group medium">
                <?php if($isOptionSelected) : ?>
                    <?php foreach ($this->getItems() as $item => $count): ?>
                        <?php if ($this->getCanShowItem($item, $count)): ?>
                            <?php if($this->isItemActive($item)) : ?>
                                <a class="button-select ajax" href="<?php echo $this->getItemUrl($item) ?>"><span><?php echo $item ?></span> <span class="down"></span></a>
                            <?php endif; ?>
                        <?php endif; ?>
                    <?php endforeach; ?>
                <?php else: ?>
                    <a class="button-select ajax filter-droplist" href="#"><span><?php echo $this->__("Select one"); ?></span> <span class="down"></span></a>
                <?php endif; ?>
                <div class="dropdown-select mCustomScrollbar">
                    <ul class="filter-droplist">
    <?php foreach ($this->getItems() as $item => $count): ?>
        <?php if ($this->getCanShowItem($item, $count)): ?>

                        <li><a href="<?php echo $this->getItemUrl($item) ?>" data-url="<?php echo $this->getItemUrl($item) ?>" data-value="<?php echo $item; ?>"><span><?php echo $item ?></span> <span class="suffix">(<?php echo $count ?>)</span></a></li>
        <?php endif; ?>
    <?php endforeach; ?>
                    </ul>
                </div>
            </div>
        </div>
            <div class="action clear clearfix <?php if(!$isOptionSelected) : ?>hidden<?php endif; ?>">
                <a href="#" data-filter-type="<?php echo implode("_", $key_withoutFacet); ?>" onclick="Mall.listing.removeSingleFilterType(this);Mall.listing.reloadListing();return false;" class="button button-third clear">Wyczyść</a>
            </div>
    </div>
<?php endif; ?>