<?php $key = $this->getFacetKey(); ?>
<?php if ($this->getCanShow()): ?>
    <?php
    $sectionClass = $this->isFilterRolled() ? 'closed' : 'open';
    $iconClass = $this->isFilterRolled() ? "fa-chevron-down" : "fa-chevron-up";
    $isOptionSelected = false;
    $key_withoutFacet = explode("_", $key);
    array_pop($key_withoutFacet);
    ?>
    <div class="section clearfix" data-xs-rolled="closed" data-lg-rolled="<?php echo $sectionClass; ?>">
        <h3 class="<?php echo $sectionClass; ?>"><span><?php echo $this->getFacetLabel(); ?></span> <i class="fa <?php echo $iconClass; ?>"></i></h3>
        <div id="filter_<?php echo $key ?>" class="content filter-type">
    <?php foreach ($this->getItems() as $item => $count): ?>
        <?php if ($this->getCanShowItem($item, $count)): ?>
            <?php
            if(!$isOptionSelected && $this->isItemActive($item)) {
                $isOptionSelected = true;
            }
			$_value = $this->getValueObject($item);
			if ($_value) {
				$_image = $_value->getNormalImage();
			 	$_imageHover = $_value->getNormalHoveredImage();
			}

            ?>
            <div class="form-group form-checkbox">
				<table>
					<tbody>
						<tr>
							<td class="first-td">
								<div>
				 	               <input type="checkbox" 
										data-url='<?php echo $this->getItemUrl($item) ?>' 
										data-params='<?php echo $this->getItemJson($item);?>'
										name="<?php echo $this->getItemName($item);?>"
										value="<?php echo $this->getItemValue($item)?>"
										id="<?php echo $this->getItemId($item)?>" 
										class="css-checkbox" 
										<?php if($this->isItemActive($item)): ?>checked="checked" <?php endif; ?>/>
					                <label for="<?php echo $this->getItemId($item)?>">
						                <a href="<?php echo $this->getItemUrl($item); ?>"
						                   class="listing-link">
							                <img alt="" <?php if (!empty($_image)): ?>src="<?php echo Mage::getBaseUrl("media") . "/m-image/" . $_image;?>"<?php endif; ?>/>
						                </a>
									</label>
								</div>
							</td>
							<td class="last-td">
								<label for="<?php echo $this->getItemId($item); ?>" class="css-label">
			                        <span>
				                        <a href="<?php echo $this->getItemUrl($item); ?>"
				                           class="listing-link">
					                        <?php echo $item; ?>
				                        </a>
			                        </span>
									&nbsp;
			                        <span class="suffix">
				                        (<?php echo $count; ?>)
			                        </span>
								</label>
							</td>
						</tr>
					</tbody>
				</table>
            </div>
        <?php endif; ?>
    <?php endforeach; ?>
    <?php if ($this->getCanShowHidden()): ?>
        <?php foreach ($this->getHiddenItems() as $item => $count): ?>
            <div class="form-group form-checkbox" data-state="hidden" style="display: none;">
				<table>
					<tbody>
						<tr>
							<td class="first-td">
								<div>
				 	               <input type="checkbox" 
										data-url='<?php echo $this->getItemUrl($item) ?>' 
										data-params='<?php echo $this->getItemJson($item);?>'
										name="<?php echo $this->getItemName($item);?>"
										value="<?php echo $this->getItemValue($item)?>"
										id="<?php echo $this->getItemId($item)?>" 
										class="css-checkbox" 
										<?php if($this->isItemActive($item)): ?>checked="checked" <?php endif; ?>/>
					                <label for="<?php echo $this->getItemId($item)?>">
						                <a href="<?php echo $this->getItemUrl($item); ?>"
						                   class="listing-link">
							                <img alt="" <?php if (!empty($_image)): ?>src="<?php echo Mage::getBaseUrl("media") . "/m-image/" . $_image;?>"<?php endif; ?>/>
						                </a>
									</label>
								</div>
							</td>
							<td class="last-td">
								<label for="<?php echo $this->getItemId($item); ?>" class="css-label">
			                        <span>
				                        <a href="<?php echo $this->getItemUrl($item); ?>"
				                           class="listing-link">
					                        <?php echo $item; ?>
				                        </a>
			                        </span>
									&nbsp;
			                        <span class="suffix">
				                        (<?php echo $count; ?>)
			                        </span>
								</label>
							</td>
						</tr>
					</tbody>
				</table>
            </div>
        <?php endforeach; ?>
        <div class="action clearfix">
            <a href="#" class="go_read_filter underline showmore-filters" data-state="0"><?php echo $this->__("Show more"); ?></a>
        </div>
    <?php endif; ?>
            <div class="action clear clearfix <?php if(!$isOptionSelected) : ?>hidden<?php endif; ?>">
	            <?php $pureKey = implode("_", $key_withoutFacet); ?>
                <a href="<?php echo $this->getRemoveAllUrl($pureKey) ?>" data-filter-type="<?php echo $pureKey; ?>" class="button button-third clear"><?php echo $this->__("Clear"); ?></a>
            </div>
        </div>
    </div>
<?php endif; ?>