<?php $key = $this->getFacetKey(); ?>
<?php if ($this->getCanShow()): ?>
    <?php
    $sectionClass = $this->isFilterRolled() ? 'closed' : 'open';
    $iconClass = $this->isFilterRolled() ? "fa-chevron-down" : "fa-chevron-up";
    $isOptionSelected = false;
    $key_withoutFacet = explode("_", $key);
    array_pop($key_withoutFacet);
    ?>

    <div class="section clearfix">

        <h3 class="<?php echo $sectionClass; ?>"><?php echo $this->getFacetLabel(); ?> <i class="fa <?php echo $iconClass; ?>"></i></h3>
        <div class="content filter-size"  id="filter_<?php echo $key ?>">
    <?php foreach ($this->getItems() as $item => $count): ?>
        <?php if ($this->getCanShowItem($item, $count)): ?>
            <?php
            if(!$isOptionSelected && $this->isItemActive($item)) {
                $isOptionSelected = true;
            }
            ?>
            <label for="<?php echo $key ?>_<?php echo $item; ?>">
                <input data-url="<?php echo $this->getItemUrl($item) ?>" data-params="<?php echo $this->getItemJson($item);?>"  type="checkbox" id="<?php echo $key ?>_<?php echo $item; ?>" name="<?php echo $key ?>_<?php echo $item; ?>" <?php if($this->isItemActive($item)): ?>checked="checked" <?php endif; ?> /><span><?php echo $item ?></span>
            </label>
        <?php endif; ?>
    <?php endforeach; ?>
    <?php if ($this->getCanShowHidden()): ?>
        <?php foreach ($this->getHiddenItems() as $item => $count): ?>
            <label for="<?php echo $key ?>_<?php echo $item; ?>s">
                <input data-url="<?php echo $this->getItemUrl($item) ?>" data-params="<?php echo $this->getItemJson($item);?>"  type="checkbox" id="<?php echo $key ?>_<?php echo $item; ?>" name="<?php echo $key ?>_<?php echo $item; ?>" <?php if($this->isItemActive($item)): ?>checked="checked" <?php endif; ?> /><span><?php echo $item ?></span>
            </label>
        <?php endforeach; ?>
            <div class="action clearfix">
                <a href="#" class="go_read_filter underline showmore-filters" data-state="0"><?php echo $this->__("Show more"); ?></a>
            </div>
    <?php endif; ?>
            <div class="action clear <?php if(!$isOptionSelected) : ?>hidden<?php endif; ?> clearfix">
                <a href="#" class="btn clear" data-filter-type="<?php echo implode("_", $key_withoutFacet); ?>" onclick="Mall.listing.removeSingleFilterType(this);Mall.listing.reloadListing();return false;" ><?php echo $this->__("Clear"); ?></a>
            </div>

        </div>

    </div>

<?php endif; ?>