<?php $key = $this->getFacetKey(); ?>
<?php if ($this->getCanShow()): ?>
    <?php
    $sectionClass = $this->isFilterRolled() ? 'closed' : 'open';
    $iconClass = $this->isFilterRolled() ? "fa-chevron-down" : "fa-chevron-up";
    $isOptionSelected = false;
    $key_withoutFacet = explode("_", $key);
    array_pop($key_withoutFacet);
    $pureKey = implode("_", $key_withoutFacet);
    ?>

    <div class="section clearfix" data-xs-rolled="closed" data-lg-rolled="<?php echo $sectionClass; ?>">

        <h3 class="<?php echo $sectionClass; ?>"><span><?php echo $this->getFacetLabel(); ?></span> <i class="fa <?php echo $iconClass; ?>"></i></h3>
        <div class="content filter-size"  id="filter_<?php echo $key ?>">
    <?php foreach ($this->getItems() as $item => $count): ?>
        <?php if ($this->getCanShowItem($item, $count)): ?>
            <?php
            if(!$isOptionSelected && $this->isItemActive($item)) {
                $isOptionSelected = true;
            }
            ?>
            <label for="<?php echo $this->getItemId($item)?>">
                <input data-url="<?php echo $this->getItemUrl($item) ?>" 
					   data-params='<?php echo $this->getItemJson($item);?>'  
					   type="checkbox"
					   name="<?php echo $this->getItemName($item);?>"
					   value="<?php echo $this->getItemValue($item)?>"
					   id="<?php echo $this->getItemId($item)?>"
						<?php if($this->isItemActive($item)): ?>checked="checked" <?php endif; ?> />
				<span>
					<a href="<?php echo $this->getItemUrl($item); ?>"
					   class="listing-link">
						<?php echo $item; ?>
					</a>
				</span>
            </label>
        <?php endif; ?>
    <?php endforeach; ?>
    <?php if ($this->getCanShowHidden()): ?>
        <?php foreach ($this->getHiddenItems() as $item => $count): ?>
            <label for="<?php echo $this->getItemId($item)?>">
                <input data-url="<?php echo $this->getItemUrl($item) ?>" 
					   data-params='<?php echo $this->getItemJson($item);?>'  
					   type="checkbox" 
					   name="<?php echo $this->getItemName($item);?>"
					   value="<?php echo $this->getItemValue($item)?>"
					   id="<?php echo $this->getItemId($item)?>"
					   <?php if($this->isItemActive($item)): ?>checked="checked" <?php endif; ?> />
					<span>
						<a href="<?php echo $this->getItemUrl($item); ?>"
						   class="listing-link">
							<?php echo $item; ?>
						</a>
					</span>
            </label>
        <?php endforeach; ?>
            <div class="action clearfix">
                <a href="#" class="go_read_filter underline showmore-filters" data-state="0"><?php echo $this->__("Show more"); ?></a>
            </div>
    <?php endif; ?>
            <div class="action clear <?php if(!$isOptionSelected) : ?>hidden<?php endif; ?> clearfix">
                <a href="<?php echo $this->getRemoveAllUrl($pureKey) ?>" class="btn clear" data-filter-type="<?php echo $pureKey; ?>" ><?php echo $this->__("Clear"); ?></a>
            </div>
        </div>
        <?php if($isOptionSelected) : ?>
            <div class="content-xs" id="filter_<?php echo $key ?>_xs" data-content="xs">
                <dl class="clearfix">
                    <?php foreach ($this->getItems() as $item => $count): ?>
                        <?php if ($this->getCanShowItem($item, $count) && $this->isItemActive($item)): ?>
                            <dd>
                                <span class="label">
                                    <span class="value">
                                        <?php echo $this->getItemValue($item); ?>
                                    </span>
                                    <span>
                                        <a href="<?php echo $this->getItemUrl($item); ?>"
                                           class="fa fa-times active-filter-label"
                                           data-input="<?php echo $this->getItemId($item); ?>"></a>
                                    </span>
                                </span>
                            </dd>
                            <input type="hidden" name="fq[<?php echo $pureKey; ?>]"
                                   value="<?php echo $this->getItemValue($item); ?>"/>
                        <?php endif; ?>
                    <?php endforeach; ?>
                </dl>
                <div class="action clear <?php if(!$isOptionSelected) : ?>hidden<?php endif; ?> clearfix">
                    <a href="<?php echo $this->getRemoveAllUrl($pureKey) ?>" class="btn clear" data-filter-type="<?php echo $pureKey; ?>" ><?php echo $this->__("Clear"); ?></a>
                </div>
            </div>
        <?php endif; ?>
    </div>

<?php endif; ?>