<?php
$_productCollection = $this->getProductCollection();
$_helper = $this->helper('catalog/output');
if (is_null($_productCollection)) {
    return;
}
?>
<style type="text/css">
    .fidelitas ul.products-grid {
        list-style-type: none;
        padding: 0;
    }
    .fidelitas .regular-price .price{ 
        color:#E26703;
    }

    .fidelitas .products-grid .product-image {
        height: 100px;
        width: 100px;
    }

</style>

<div class="fidelitas block block-list">
    <div class="block-title">
        <strong><span><?php echo $this->getTitle(); ?></span></strong>
    </div>
    <div class="block-content">
        <div class=" category-products">
            <ul class="products-grid" >
                <?php $_collectionSize = $_productCollection->count() ?>
                <?php $_columnCount = 5; ?>
                <?php
                $i = 0;
                foreach ($_productCollection as $_product):
                    ?>
                    <li class="item">
                        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(100); ?>" width="100" height="100" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
                        <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
                            <?php echo $this->getPriceHtml($_product, true) ?>
                    </li>
                <?php endforeach ?>
            </ul>
        </div>
    </div>
</div>