<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2016 Amasty (https://www.amasty.com)
 * @package Magpleasure_Blog
 */

/** @var Magpleasure_Blog_Block_Content_Post_Wrapper $this */
?>
<?php
$post = $this->getPost();
?>
<?php if ($post->getCanonicalUrl()): ?>
<link rel="canonical" href="<?php echo $post->getCanonicalUrl(); ?>">
<?php endif; ?>

<?php if ($this->getGoogleProfileUrl()): ?>
<link rel="author" href="<?php echo $this->getGoogleProfileUrl(); ?>" />
<?php endif; ?>


