<?php $_helper = Mage::helper("zolagooperator");?>
<div class="container">
	<!--=== Page Header ===-->
	<div class="page-heading row">
		<div class="col-lg-6">
			<h3><?php echo $_helper->__("Agents list");?></h3>
			<span class="tageline"><?php echo Mage::helper("zolagopo")->__("Browse agents list");?></span>
		</div>
		<div class="main-actions align-right col-md-6">
			<a class="btn btn-success" href="<?php echo Mage::getUrl('udropship/operator/new');?>">
					<i class="icon-plus"></i>
					<?php echo $_helper->__("Create agent");?>
				</a> 
		</div>
	</div>
</div>

<div class="container z-grid">
	<div class="widget box">
		<div class="widget-content">
			<?php echo $this->getGridHtml(); ?>
		</div>
	</div>
</div>
<script type="text/javascript">
(function(){
	var gridObj = <?php echo $this->getGridJsObjectName();?>;
	// create integrator
	new Zolago.gridIntegrator(gridObj);
})();;
</script>