<?php $_helper = Mage::helper("zolagooperator");?>
<?php $_collection = $this->getCollection();?>
<?php echo $this->getMessagesBlock()->getGroupedHtml(); ?>
<fieldset class="generic-box">
	<div class="box-head">
		<h3 class="left"><?php echo $_helper->__("Operators list");?></h3>
		<button class="right form-button" type="button" id="new-operator"><span><?php echo $_helper->__("Create operator");?></span></button>
	</div>
	<?php if($_collection && $_collection->count()):?>
	<table cellspacing="0" class="data-table" id="udpo-grid">
		<colgroup>
			<col>
			<col>
			<col>
			<col>
			<col width="1">
			<col width="1">
		</colgroup>
		<thead>
			<tr>
				<th><?php echo $_helper->__("Operator login");?></th>
				<th><?php echo $_helper->__("First name");?></th>
				<th><?php echo $_helper->__("Last name");?></th>
				<th><?php echo $_helper->__("Phone");?></th>
				<th><?php echo $_helper->__("Is active");?></th></th>
				<th><?php echo $_helper->__("Edit operator");?></th></th>
			</tr>
		</thead>
		<tbody>
		<?php foreach($_collection as $_pos):?>
			<tr>
				<td><?php echo $this->escapeHtml($_pos->getEmail())?></td>
				<td><?php echo $this->escapeHtml($_pos->getFirstname())?></td>
				<td><?php echo $this->escapeHtml($_pos->getLastname())?></td>
				<td><?php echo $this->escapeHtml($_pos->getPhone())?></td>
				<td><?php echo $_helper->__((int)$_pos->getIsActive() ? "Yes" : "No");?></td>
				<td><a href="<?php echo Mage::getUrl("udropship/operator/edit", array("operator_id"=>$_pos->getId()));?>"><?php echo $_helper->__("Edit");?></a></td>
			</tr>
		<?php endforeach; ?>
        </tbody>
	</table>
	<?php else:?>
	<p class="warning"><?php echo $_helper->__("There is no operators");?></p>
	<?php endif;?>
	</div>
</fieldset>
<script type="text/javascript">
document.observe("dom:loaded", function() {
  $('new-operator').observe('click', function(){
	  document.location.href = '<?php echo Mage::getUrl('udropship/operator/new');?>';
  });
});
</script>