<?php
/**
 * @var $this Orba_Shipping_Block_Adminhtml_SystemConfigField_FuelChargeConfig
 */
?>
<?php
$_element = $this->getElement();
$this->setFieldName($_element->getName());
$fValue = $_element->getValue();
?>
<div class="grid">
    <input id="<?php echo $this->getFieldName()?>" type="hidden" />
    <table cellspacing="0" class="data" id="<?php echo $this->suffixId('cfgTable')?>" style="width:70px" class="config">
        <col width="500" />
        <col width="700" />
        <col width="700" />
        <thead>
            <tr class="headings">
                <th><?php echo Mage::helper('orbashipping')->__('%') ?></th>
                <th><?php echo Mage::helper('orbashipping')->__('From date') ?></th>
                <th><?php echo Mage::helper('orbashipping')->__('To date') ?></th>
            </tr>
        </thead>
        <tbody>

        </tbody>
        <tfoot>
        <tr>
            <th colspan="5" class="a-left">
                <div class="left">
                    <button id="addFuelChargeItem" type="button" class="scalable add" id="<?php echo $this->suffixId('addBtn')?>">
                        <span>+ <?php echo $this->__('Add Fuel Charge') ?></span>
                    </button>
                </div>
            </th>
        </tr>
        </tfoot>
    </table>
</div>
<script type="text/javascript">
    var fuelChargeTableId = '<?php echo $this->suffixId('cfgTable')?>';
    var fieldName = '<?php echo $this->getFieldName()?>';
</script>