<?php
$element = $this->getElement(); //->getElements()->getIterator();
$attrData = $element->getAttrData();
?>
<div class="widget box <?php echo $element->getClass(); ?>"
    <?php if (!empty($attrData)): ?>
        <?php foreach ($attrData as $data): ?>
            data-<?php echo $data->name; ?>="<?php echo $data->value; ?>"
        <?php endforeach; ?>
    <?php endif; ?>>
    <?php $iconClass = $this->getElement()->getIconClass(); ?>
	<div class="widget-header"> 
		<h4>
            <?php if(!empty($iconClass)): ?>
                <i class="<?php echo $iconClass; ?>"></i>
            <?php else: ?>
                <i class="icon-reorder"></i>
            <?php endif; ?>

			<?php echo $this->getElement()->getLegend() ?>
		</h4> 
	</div> 
	<div class="widget-content">
		<div style="margin: 0 5px;">
			<?php echo $element->getChildrenHtml();?>
		</div>
	</div>
</div>