<?php
/** @var $_product Zolago_Catalog_Model_Product */
/** @var $product Mage_Wishlist_Model_Item */
/** @var $_collection Mage_Wishlist_Model_Resource_Item_Collection */
$_collection = $this->getItems();
/** @var Zolago_Catalog_Helper_Product $_helper */
$_helper = Mage::helper('zolagocatalog/product');
$brandImagesList = Mage::helper('wishlist')->getBrandImagesList();

/** @var Zolago_Solrsearch_Helper_Data $zssHelper */
$zssHelper = Mage::helper("zolagosolrsearch");
?>

<div class="container-fluid" id="items-product">
    <div class="row">
        <div class="col-xs-12 col-sm-12">
            <div class="row">
                <div id="grid" class="shuffle--container shuffle--fluid">
                    <?php foreach ($_collection as $product): ?>
                        <?php
						$_product = $product->getProduct();
                        $stockItem = Mage::getModel('cataloginventory/stock_item')->loadByProduct($_product);

                        if(!!$stockItem->getBackorders()){
                            $maxSaleQty = (int) $stockItem->getMaxSaleQty();
                        } else {
                            $maxSaleQty = (int) $stockItem->getQty();
                        }

						$_product->setImage($_product->getThumbnail()); // trick
						$_productImageUrl = $zssHelper->getListingResizedImageUrl($_product);
                        $_productImageInfo = $_helper->getResizedImageInfo($_product);
						?>
                        <div id="prod-<?php echo $product->getEntityId();?>" class="item col-phone col-xs-4 col-sm-4 col-md-3 col-lg-3 size14">
                            <div class="box_listing_product">
                                <a href="<?php echo $_product->getProductUrl(); ?>"
                                   title="<?php echo $_product->getName(); ?>"
                                   data-entity="<?php echo $_product->getId(); ?>"
                                   data-sku="<?php echo $_product->getSku(); ?>"
                                   data-skuv="<?php echo $_product->getSkuv(); ?>"
                                   data-product-type="<?php echo $_product->getTypeId(); ?>">
	                                <figure class="img_product boxed">
	                                <figure class="img_product boxed">
		                                <img src="<?php echo $_productImageUrl; ?>"
		                                     alt="<?php $this->escapeHtml($product->getName()); ?>"
		                                     class="img-responsive" />
	                                </figure>
                                    <div class="name_product">
                                        <?php echo $this->escapeHtml($_product->getName()); ?>
                                    </div>

                                    <div class="price clearfix">
                                        <div class="col-price col-lg-6 col-md-6 col-sm-6 col-xs-6">
                                            <?php if (!$_product->getTypeId() == Mage_Catalog_Model_Product_Type::TYPE_BUNDLE && $_product->getPrice() != $_product->getFinalPrice()) : ?>
                                                <span class="old">
                                                        <?php echo $this->helper('core')->currency($product->getPrice(), true, false); ?>
                                                    </span>
                                            <?php endif; ?>
                                            <span>
                                                    <?php echo $this->helper('core')->currency($_product->getFinalPrice(), true, false); ?>
                                                </span>
                                        </div>
                                        <div class="like liked col-lg-6 text-right col-md-6 col-sm-6 col-xs-6"
                                             data-idproduct="<?php echo $_product->getId(); ?>">
                                            <span class="icoLike"></span>
	                                        <span class="likeAdded"><i class="fa fa-list"></i> <?php echo $_helper->__('remove from the list')?></span>
                                        </div>


                                        <div class="size-box-bundle col-lg-12 col-md-12 col-sm-12 col-xs-12 clearfix">
                                            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12 clearfix quantity_block">
                                                <?php if (	$_product->getTypeId() == Mage_Catalog_Model_Product_Type::TYPE_SIMPLE ||
                                                    $_product->getTypeId() == Mage_Catalog_Model_Product_Type::TYPE_BUNDLE) : ?>
                                                    <a href="#" class="qty_less" id="qty-less-<?php echo $_product->getId();?>" data-min_qty="<?php echo (int) $stockItem->getMinSaleQty(); ?>">-</a>
                                                    <div class="qty qty-box" id="input-box-<?php echo $_product->getId();?>"
                                                         title="<?php echo Mage::helper('zolagosolrsearch')->__("Maximum quantity&nbsp;%s", $maxSaleQty); ?>"
                                                         data-toggle="tooltip" data-placemen="top"><input type="text" name="quantity" value="1"/></div>
                                                    <a href="#" class="qty_more" id="qty-more-<?php echo $_product->getId();?>" data-qty="<?php echo $maxSaleQty; ?>">+</a>
                                                <?php else: ?>
                                                    <p class="variants"><?php echo Mage::helper('zolagosolrsearch')->__("Available in several variants"); ?></p>
                                                <?php endif; ?>
                                            </div>
                                            <div class="action-box-container col-lg-6 col-md-6 col-sm-6 col-xs-12 clearfix">
                                                <div class="action-box-bundle clearfix">
                                                    <?php if (	$_product->getTypeId() == Mage_Catalog_Model_Product_Type::TYPE_SIMPLE ||
                                                        $_product->getTypeId() == Mage_Catalog_Model_Product_Type::TYPE_BUNDLE) : ?>
                                                        <button class="btn button button-primary addBasket"
                                                                onclick="Mall.validateAddingToCartListing(<?php echo $_product->getId(); ?>, <?php echo (int) $stockItem->getMinSaleQty(); ?>, <?php echo $maxSaleQty; ?>);return false;">
                                                            <i class="fa fa-shopping-cart" aria-hidden="true"></i>
                                                            <?php echo Mage::helper('zolagosolrsearch')->__("Add"); ?>
                                                        </button>
                                                    <?php else: ?>
                                                        <span class="btn button button-primary addBasket">
																			<i class="fa fa-shopping-cart" aria-hidden="true"></i>
                                                            <?php echo Mage::helper('zolagosolrsearch')->__("See"); ?>
																		</span>
                                                    <?php endif; ?>
                                                </div>
                                            </div>
                                        </div>

                                    </div>
								</a>
                            </div>
                        </div>
                    <?php endforeach; ?>
                    <div class="col-xs-12 shuffle__sizer"></div>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
	//needed for like removal process
	var unlikingOnWishlist = true;

    Mall.translate.add("you-like-this", "<?php echo $this->__("You like this"); ?>");
    Mall.translate.add("remove-from-favorites", "<?php echo $this->__("remove from favorites"); ?>");
    Mall.translate.add("added-to-shopping-list", "<?php echo Mage::helper("zolagocatalog")->__("Added to shopping list"); ?>");
    Mall.translate.add("like-this-product", "<?php echo $this->__("like this product"); ?>");
    Mall.translate.add("likes-this-product", "<?php echo $this->__("likes this product"); ?>");
    Mall.translate.add("you-and", "<?php echo $this->__("You and"); ?>");
    Mall.translate.add("person", "<?php echo $this->__("person"); ?>");
    Mall.translate.add("people", "<?php echo $this->__("people"); ?>");
    Mall.translate.add("people-polish-more-than-few", "<?php echo $this->__("people polish more than few"); ?>");
    Mall.translate.add("you", "<?php echo $this->__("You"); ?>");
    Mall.translate.add("You", "<?php echo $this->__("You"); ?>");

    Mall.initUrls("<?php echo Mage::getBaseUrl(); ?>","<?php echo Mage::getUrl("/",array("_no_vendor"=>true)); ?>");
	

    <?php foreach ($_collection as $product): ?>
    <?php $_product = $product->getProduct(); ?>
    Mall.wishlist.addProduct({
        id: <?php echo $_product->getId(); ?>,
        wishlist_count: <?php echo (int)$_product->getWishlistCount(); ?>,
        in_your_wishlist: "true"
    });
    <?php endforeach; ?>
</script>


<div class="modal bs-example-modal-lg" id="popup-after-add-to-cart" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel"
     aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-error modal-header" style="display: none;">
                <button type="button" class="close" data-dismiss="modal"></button>
                <h2 class="title_section"><?php echo $this->__("Error occured!"); ?></h2>
            </div>
            <div class="modal-loading modal-header">
                <button type="button" class="close" data-dismiss="modal"></button>
                <h2 class="title_section"><?php echo $this->__("Adding product to cart..."); ?></h2>
            </div>
            <div class="modal-loaded modal-header" style="display: none;">
                <button type="button" class="close" data-dismiss="modal"></button>
                <h2 class="title_section"><?php echo $this->__("Product has been added to cart:"); ?></h2>
            </div>
            <div class="modal-body modal-error" style="display: none">
                <div class="modal-error-txt">

                </div>
            </div>
            <div class="modal-body modal-loading" style="text-align: center">
                <i class="fa fa-spinner fa-spin fa-2x"></i>
            </div>
            <div class="modal-loaded modal-body" style="display: none;">
                <table>
                    <tbody id="product-added">
                    <tr id="full-width-popup-table">
                        <td class="thumb" style="width: 55px;"><img style="width: 42px;" alt=""></td>
                        <td class="desc"><p class="name_product"></p>
                            <p class="quantity"><?php echo ucfirst($this->__("quantity")); ?>: <span>1</span></p></td>
                        <td class="price"></td>
                    </tr>
                    <tr id="small-width-popup-table">
                        <td></td>
                        <td class="price" style="padding: 0 5px;"></td>
                    </tr>
                    </tbody>
                </table>
                <div id="buttons-after-add-to-cart">
                    <div class="button-after-add-to-cart" id="continue-shopping-after-add-to-cart">
                        <a href="#" data-dismiss="modal" class="button button-third">
                            <?php echo $this->__("Continue shopping"); ?>
                        </a>
                    </div>
                    <div class="button-after-add-to-cart" id="cart-after-add-to-cart">
                        <a href="<?php echo Mage::getUrl('checkout/cart'); ?>" class="button button-primary medium link">
                            <?php echo $this->__("Go to shopping cart"); ?>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

