<?php
/** @var Zolago_Catalog_Block_Vendor_Product_Custom_Staticfilter $this */
$storeId		= $this->_getLabelStore()->getId();
$activeFilters	= $this->getCurrentStaticFilterValues();
?>

<?php if ($this->getStaticFilters($this->getCurrentAttributeSetId()) && $this->getCurrentAttributeSetId()): ?>

	<!-- Static Filters from All Attribute Groups: Start -->
	<?php foreach ($this->getStaticFilters($this->getCurrentAttributeSetId()) as $singleFilter): ?>
		<?php if ($singleFilter): ?>
			<?php
			$firstFilter = current($singleFilter);
			?>
			<?php if ($firstFilter['group'] !== Zolago_Catalog_Helper_Data::ADDITIONAL_ATTRIBUTES_GROUP): ?>

				<?php
				list ($filterLabel, $labelsCount) = $this->getStaticFilterLabel($singleFilter);
				$updateValues = $this->updateStaticFilterValues($singleFilter, $labelsCount);
				?>
				<div class="row  next-row">
					<label for="staticFilter" class="col-md-4 control-label">
						<?php echo $filterLabel; ?>
					</label>

					<div class="col-md-8">
						<select name="staticFilter" id="staticFilter-<?php echo $firstFilter['attribute_id']; ?>"
								class="form-control staticFilter">
							<option
								value=""><?php echo Mage::helper("zolagocatalog")->__("--- Select ---"); ?></option>
							<?php foreach ($singleFilter as $value): ?>
								<?php if (isset($value['option'])):
									$filterValue = $value['option'];
									$displayValue = $this->getOptionLabelbyId($firstFilter['attribute_id'],$filterValue, $storeId);
									if (!$displayValue):
										$displayValue = $this->getOptionLabelbyId($firstFilter['attribute_id'],$filterValue, 0);
									endif;
								else:
									$filterValue = $this->escapeHtml($value['value']);
									$displayValue = $this->escapeHtml($value['value']);
								endif;
								?>
								<?php if ($displayValue && $value['group'] !== Zolago_Catalog_Helper_Data::ADDITIONAL_ATTRIBUTES_GROUP): ?>
									<option
										value="<?php echo $value['attribute_id']; ?>" <?php if ($this->isFilterActive($activeFilters, $value['attribute_id'], $displayValue, $filterValue)): ?> selected="selected"<?php endif; ?>
										filterValue="<?php echo $this->escapeHtml($filterValue); ?>"><?php echo $this->getUpdatedFilterValues($displayValue, $filterLabel, $updateValues); ?></option>
								<?php endif; ?>
							<?php endforeach; ?>
						</select>
					</div>

				</div>
			<?php endif; ?>
		<?php endif; ?>
	<?php endforeach; ?>
	<!-- Static Filters from All Attribute Groups: End -->

<?php endif; ?>