<definitions name="GHApi"
   targetNamespace="<?php echo $this->getTargetNamespace();?>"
   xmlns="http://schemas.xmlsoap.org/wsdl/"
   xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
   xmlns:tns="<?php echo $this->getTns(); ?>"
   xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <types>
  	<xsd:schema targetNamespace="<?php echo $this->getTargetNamespace();?>">
		<xsd:complexType name="loginRequest">
			<xsd:all>
				<xsd:element name="vendorId" type="xsd:int"/>
				<xsd:element name="password" type="xsd:string"/>
				<xsd:element name="webApiKey" type="xsd:string"/>
			</xsd:all>
		</xsd:complexType>
		<xsd:complexType name="loginResponse">
			<xsd:all>
				<xsd:element name="token" type="xsd:string"/>
				<xsd:element name="message" type="xsd:string"/>
				<xsd:element name="status" type="xsd:boolean"/>
			</xsd:all>
		</xsd:complexType>
		<xsd:complexType name="changeOrderMessageRequest">
			<xsd:all>
				<xsd:element name="sessionToken" type="xsd:string"/>
				<xsd:element name="messageBatchSize" type="xsd:int"/>
				<xsd:element name="messageType" type="xsd:string" nillable="true"/>
			</xsd:all>
		</xsd:complexType>
		<xsd:complexType name="changeOrderMessageResponse">
			<xsd:all>
				<xsd:element name="list" type="tns:messageList"/>
				<xsd:element name="message" type="xsd:string"/>
				<xsd:element name="status" type="xsd:boolean"/>
			</xsd:all>
		</xsd:complexType>
		<xsd:complexType name="tns:message">
			<xsd:all>
				<xsd:element name="messageId" type="xsd:int"/>
				<xsd:element name="messageType" type="xsd:string"/>
				<xsd:element name="orderId" type="xsd:string"/>
			</xsd:all>		
		</xsd:complexType>
		<xsd:complexType name="tns:messageList">
			<xsd:sequence>
				<xsd:element name="message" type="tns:message" minOccurs="0" maxOccurs="unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
		<xsd:complexType name="tns:messageIdList">
			<xsd:sequence>
				<xsd:element name="messageId" type="xsd:int" minOccurs="0" maxOccurs="unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
		<xsd:complexType name="tns:orderIDList">
			<xsd:sequence>
				<xsd:element name="orderIDItem" type="xsd:string" minOccurs="1" maxOccurs="unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
		<xsd:complexType name="tns:orderList">
			<xsd:sequence>
				<xsd:element name="order" type="tns:order" minOccurs="0" maxOccurs="unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
		<xsd:complexType name="tns:orderItemList">
			<xsd:sequence>
				<xsd:element name="item" type="tns:orderItem" minOccurs="1" maxOccurs="unbounded"/>
			</xsd:sequence>
		</xsd:complexType>

		<xsd:complexType name="tns:orderItem">
			<xsd:all>
				<xsd:element name="is_delivery_item" type="xsd:int"/>
				<xsd:element name="item_sku" type="xsd:string"/>
				<xsd:element name="item_name" type="xsd:string"/>
				<xsd:element name="item_qty" type="xsd:int"/>
				<xsd:element name="item_value_before_discount" type="xsd:float"/>
				<xsd:element name="item_discount" type="xsd:float"/>
				<xsd:element name="item_value_after_discount" type="xsd:float"/>
			</xsd:all>		
		</xsd:complexType>

		<xsd:complexType name="tns:order">
			<xsd:all>
				<xsd:element name="vendor_id" type="xsd:int"/>
				<xsd:element name="vendor_name" type="xsd:string"/>
				<xsd:element name="order_id" type="xsd:string"/>
				<xsd:element name="order_date" type="xsd:string"/>
				<xsd:element name="order_max_shipping_date" type="xsd:string"/>
				<xsd:element name="order_status" type="xsd:string"/>
				<xsd:element name="order_total" type="xsd:float"/>
				<xsd:element name="payment_method" type="xsd:string"/>
				<xsd:element name="order_due_amount" type="xsd:float"/>
				<xsd:element name="delivery_method" type="xsd:string"/>
				<xsd:element name="shipment_tracking_number" type="xsd:string"/>
				<xsd:element name="pos_id" type="xsd:string"/>
				<xsd:element name="invoice_data" type="tns:invoiceData"/>	
				<xsd:element name="delivery_data" type="tns:deliveryData"/>	
				<xsd:element name="order_items" type="tns:orderItemList"/>	
			</xsd:all>		
		</xsd:complexType>

		<xsd:complexType name="deliveryData">
			<xsd:all>
				<xsd:element name="inpost_locker_id" type="xsd:string" nillable="true"/>
				<xsd:element name="delivery_address" type="tns:deliveryAddress"/>
			</xsd:all>
		</xsd:complexType>
		<xsd:complexType name="deliveryAddress">
			<xsd:all>
				<xsd:element name="delivery_first_name" type="xsd:string"/>
				<xsd:element name="delivery_last_name" type="xsd:string"/>
				<xsd:element name="delivery_company_name" type="xsd:string" nillable="true"/>
				<xsd:element name="delivery_street" type="xsd:string"/>
				<xsd:element name="delivery_city" type="xsd:string"/>
				<xsd:element name="delivery_zip_code" type="xsd:string"/>
				<xsd:element name="delivery_country" type="xsd:string"/>
				<xsd:element name="phone" type="xsd:string"/>
			</xsd:all>
		</xsd:complexType>

		<xsd:complexType name="invoiceData">
			<xsd:all>
				<xsd:element name="invoice_required" type="xsd:int"/>
				<xsd:element name="invoice_address" type="tns:invoiceAddress" nillable="true"/>
			</xsd:all>
		</xsd:complexType>
		<xsd:complexType name="invoiceAddress">
			<xsd:all>
				<xsd:element name="invoice_first_name" type="xsd:string"/>
				<xsd:element name="invoice_last_name" type="xsd:string"/>
				<xsd:element name="invoice_company_name" type="xsd:string" nillable="true"/>
				<xsd:element name="invoice_street" type="xsd:string"/>
				<xsd:element name="invoice_city" type="xsd:string"/>
				<xsd:element name="invoice_zip_code" type="xsd:string"/>
				<xsd:element name="invoice_country" type="xsd:string"/>
				<xsd:element name="invoice_tax_id" type="xsd:string" nillable="true"/>
			</xsd:all>
		</xsd:complexType>
		<xsd:complexType name="confirmationMessageRequest">
			<xsd:all>
				<xsd:element name="sessionToken" type="xsd:string"/>
				<xsd:element name="messageIdList" type="tns:messageIdList"/>
			</xsd:all>
		</xsd:complexType>
		<xsd:complexType name="orderIDRequest">
			<xsd:all>
				<xsd:element name="sessionToken" type="xsd:string"/>
				<xsd:element name="orderID" type="tns:orderIDList"/>
			</xsd:all>
		</xsd:complexType>
		<xsd:complexType name="simpleResponse">
			<xsd:all>
				<xsd:element name="message" type="xsd:string"/>
				<xsd:element name="status" type="xsd:boolean"/>
			</xsd:all>
		</xsd:complexType>
		<xsd:complexType name="shipmentRequest">
			<xsd:all>
				<xsd:element name="sessionToken" type="xsd:string"/>
				<xsd:element name="orderID" type="xsd:string"/>
				<xsd:element name="dateShipped" type="xsd:string"/>
				<xsd:element name="courier" type="xsd:string"/>
				<xsd:element name="shipmentTrackingNumber" type="xsd:string"/>
			</xsd:all>
		</xsd:complexType>
		<xsd:complexType name="getOrdersResponse">
			<xsd:all>
				<xsd:element name="message" type="xsd:string"/>
				<xsd:element name="status" type="xsd:boolean"/>
				<xsd:element name="orderList" type="tns:orderList" nillable="true"/>	
			</xsd:all>
		</xsd:complexType>
	</xsd:schema>
  </types>
  <message name="doLoginRequest">
      <part name="loginParameters" type="tns:loginRequest"/>
  </message>	
  <message name="doLoginResponse">
      <part name="loginResponse" type="tns:loginResponse"/>
  </message>	
  <message name="getChangeOrderMessageRequest">
      <part name="getChangeOrderMessageParameters" type="tns:changeOrderMessageRequest"/>
  </message>	
  <message name="getChangeOrderMessageResponse">
      <part name="getMessageResponse" type="tns:changeOrderMessageResponse"/>
  </message>	
  <message name="setChangeOrderMessageConfirmationRequest">
      <part name="setChangeOrderMessageConfirmationParameters" type="tns:confirmationMessageRequest"/>
  </message>	
  <message name="setChangeOrderMessageConfirmationResponse">
      <part name="confirmMessageResponse" type="tns:simpleResponse"/>
  </message>	
  <message name="setOrderAsCollectedRequest">
      <part name="setOrderAsCollectedRequestParameters" type="tns:orderIDRequest"/>
  </message>	
  <message name="setOrderAsCollectedResponse">
      <part name="setCollectedResponse" type="tns:simpleResponse"/>
  </message>	
  <message name="getOrdersByIDRequest">
      <part name="getOrdersByIDRequestParameters" type="tns:orderIDRequest"/>
  </message>	
  <message name="getOrdersByIDResponse">
      <part name="getOrderIDResponse" type="tns:getOrdersResponse"/>
  </message>	
  <message name="setOrderShipmentRequest">
      <part name="setOrderShipmentRequestParameters" type="tns:shipmentRequest"/>
  </message>	
  <message name="setOrderShipmentResponse">
      <part name="setShipmentResponse" type="tns:simpleResponse"/>
  </message>	
  <portType name="GHApi_PortType">
      <operation name="doLogin">
         <input message="tns:doLoginRequest"/>
         <output message="tns:doLoginResponse"/>
      </operation>
      <operation name="getChangeOrderMessage">
         <input message="tns:getChangeOrderMessageRequest"/>
         <output message="tns:getChangeOrderMessageResponse"/>
      </operation>
      <operation name="setChangeOrderMessageConfirmation">
         <input message="tns:setChangeOrderMessageConfirmationRequest"/>
         <output message="tns:setChangeOrderMessageConfirmationResponse"/>
      </operation>
      <operation name="setOrderAsCollected">
         <input message="tns:setOrderAsCollectedRequest"/>
         <output message="tns:setOrderAsCollectedResponse"/>
      </operation>
      <operation name="setOrderShipment">
         <input message="tns:setOrderShipmentRequest"/>
         <output message="tns:setOrderShipmentResponse"/>
      </operation>
      <operation name="getOrdersByID">
         <input message="tns:getOrdersByIDRequest"/>
         <output message="tns:getOrdersByIDResponse"/>
      </operation>
  </portType>
  <binding name="GHApi_Binding" type="tns:GHApi_PortType">
      <soap:binding style="document"
         transport="http://schemas.xmlsoap.org/soap/http"/>
      <operation name="doLogin">	
         <soap:operation soapAction="<?php echo $this->getWsUrl();?>doLogin"/>
         <input>
            <soap:body
               encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"
               use="encoded"/>
         </input>
         <output>
            <soap:body
               encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"
               use="encoded"/>
         </output>
      </operation>
      <operation name="getChangeOrderMessage">	
         <soap:operation soapAction="<?php echo $this->getWsUrl();?>getChangeOrderMessage"/>
         <input>
            <soap:body
               encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"
               use="encoded"/>
         </input>
         <output>
            <soap:body
               encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"
               use="encoded"/>
         </output>
      </operation>
      <operation name="setChangeOrderMessageConfirmation">	
         <soap:operation soapAction="<?php echo $this->getWsUrl();?>setChangeOrderMessageConfirmation"/>
         <input>
            <soap:body
               encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"
               use="encoded"/>
         </input>
         <output>
            <soap:body
               encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"
               use="encoded"/>
         </output>
      </operation>
      <operation name="getOrdersByID">	
         <soap:operation soapAction="<?php echo $this->getWsUrl();?>getOrdersByID"/>
         <input>
            <soap:body
               encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"
               use="encoded"/>
         </input>
         <output>
            <soap:body
               encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"
               use="encoded"/>
         </output>
      </operation>
      <operation name="setOrderAsCollected">	
         <soap:operation soapAction="<?php echo $this->getWsUrl();?>setOrderAsCollected"/>
         <input>
            <soap:body
               encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"
               use="encoded"/>
         </input>
         <output>
            <soap:body
               encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"
               use="encoded"/>
         </output>
      </operation>
      <operation name="setOrderShipment">	
         <soap:operation soapAction="<?php echo $this->getWsUrl();?>setOrderShipment"/>
         <input>
            <soap:body
               encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"
               use="encoded"/>
         </input>
         <output>
            <soap:body
               encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"
               use="encoded"/>
         </output>
      </operation>
  </binding>
  <service name="GHApi_Service">
	  <port binding="tns:GHApi_Binding" name="GHApi_Port">
         <soap:address
            location="<?php echo $this->getWsUrl();?>" />
      </port>
  </service>
</definitions>