<?php
$itemsCount = $this->getItems()->getSize();
if($itemsCount): ?>
    <?php
    $_product = Mage::getModel('catalog/product');
    $attr = $_product->getResource()->getAttribute("color");
    ?>

<div class="color-box-bundle">
    <div class="color-box">
        <div class="color">
            <h4 class="itemprop-isSimilarTo"><span class="color-label"><?php echo $this->__("Other colors"); ?>:</span></h4>

                <div id="wrapper-rwd-color">
                <div id="rwd-color" class="rwd-carousel <?php if($itemsCount <= 5): ?> no-size-carousel <?php endif; ?>">
                    <?php /** @var $_item Mage_Catalog_Model_Product */ ?>
                    <?php foreach($this->getItems() as $_item) : ?>
                    <div class="item">
                        <h5 itemprop="isSimilarTo" itemscope itemtype="http://schema.org/Product">
                            <div class="form-group form-radio">
                                <label for="color_<?php echo $_item->getId(); ?>">
                                    <input type="radio" name="color" id="color_<?php echo $_item->getId(); ?>">
                                    <meta itemprop="sku" content="<?php echo $_item->getSku(); ?>" />
                                    <meta itemprop="color" content="<?php echo $color_label = $attr->getSource()->getOptionText($_item->getColor()); ?>" />
                                    <a  itemprop="url" href="<?php echo $_item->getProductUrl(); ?>"><img src="<?php echo $this->helper('catalog/image')->init($_item, 'thumbnail')->resize(43, 54); ?>" alt="<?php echo $this->escapeHtml($_item->getName()); ?>"></a>
                                </label>
                            </div>
                        </h5>
                    </div>
                    <?php endforeach; ?>
                </div>
            </div>
        </div>
    </div>
</div>
<?php endif ?>