<?php /* @var $this Zolago_Modago_Block_Checkout_Cart_Sidebar_Shipping */?>

<?php
/** @var Zolago_Checkout_Helper_Data $helper */
$helper		= Mage::helper("zolagocheckout");

$items = $this->getRateItems();
$vendors = $items->vendors;

$vendorsJ = Mage::helper('core')->jsonEncode($vendors);

$allVendorsMethod = $items->allVendorsMethod;

$methods = $items->methods;
$rates = $items->rates;
$vednorCosts = $items->vendorCosts;
$costSumm = $this->getItemsShippingCost();
$cost = $items->cost;

$checkoutSession = Mage::getSingleton('checkout/session');

/* @var $locker GH_Inpost_Model_Locker  */
$locker		= $this->getInpostLocker();
$inpostLogo	= $this->getSkinUrl('images/inpost/checkout-logo.png');

$quote = $this->getQuote();

$sessionShippingMethod = "";
$selectedShipping = Mage::helper("zolagocheckout")->getSelectedShipping();
foreach($selectedShipping["methods"] as $vid => $methodSelectedData){
    $sessionShippingMethod = $methodSelectedData;
}
$deliveryPoint = $this->getDeliveryPointCheckout();
/**
 * Totals
 */
$totals = $quote->getTotals();
$productsPriceTotal = $totals["subtotal"]->getValue(); //Wartość produktów
$discountTotal = (isset($totals["discount"]) ? $totals["discount"]->getValue() : 0); //Zniżka
$shippingTotal = empty($totals['shipping'])? 0:$totals["shipping"]->getAddress()->getShippingInclTax(); //Delivery cost
$grandTotal = $totals["grand_total"]->getValue(); //Suma

$deliveryMethods = $this->getMapDeliveryMethodsJSON($methods);

 ?>

<?php
$inPostData = Zolago_Modago_Block_Checkout_Cart_Sidebar_Shipping_Map_Inpost::getPopulateMapData();
$inPostPoints = isset($inPostData["map_points"]) ? $inPostData["map_points"] : "";
?>

<script type="text/javascript">
    var inPostPointsData = '<?php echo $inPostPoints; ?>';
    var inPostPoints = (inPostPointsData.length > 0) ? jQuery.parseJSON(inPostPointsData) : [];

    var sessionPointName = '<?php echo $locker->getName(); ?>';
    Mall.reg.set("localeCode", '<?php echo substr(Mage::getStoreConfig('general/locale/code', Mage::app()->getStore()->getId()),0,2); ?>');

    Mall.translate.add("validation_please_select_shipping", "<?php echo $helper->__("Please select shipping");?>");
    Mall.translate.add("shipping_map_select_city", "<?php echo $helper->__("Select City"); ?>");
    Mall.translate.add("shipping_map_nearest", "<?php echo $helper->__("Nearest"); ?>");
    Mall.translate.add("shipping_map_show_nearest_link", "<?php echo $helper->__("show nearest"); ?>");
    Mall.translate.add("shipping_map_hide_nearest_link", "<?php echo $helper->__("hide nearest"); ?>");
    Mall.translate.add("shipping_map_show_map_link", "<?php echo $helper->__("show map"); ?>");
    Mall.translate.add("shipping_map_hide_map_link", "<?php echo $helper->__("hide map"); ?>");
    Mall.translate.add("shipping_map_method_select", "<?php echo $helper->__("choose"); ?>");
</script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl("js/mall/checkout/cart/shipping.js") ?>"></script>



<?php if(!empty($rates)): ?>
<fieldset id="cart-shipping-methods">
    <form action="<?php echo $this->getUrl('checkout/singlepage/saveBasketShipping') ?>" method="post" id="cart-shipping-methods-form">

    <script type="text/javascript">
        (function(){
            Mall.reg.set("vendors", <?php echo $vendorsJ; ?>);
            Mall.reg.set("vendor_costs", <?php echo Mage::helper("core")->jsonEncode($vednorCosts); ?>);
            Mall.reg.set("inpost_logo", '<?php echo $inpostLogo; ?>');

            Mall.reg.set("quote_grand_total", <?php echo $grandTotal; ?>);
            Mall.reg.set("quote_products_total", <?php echo $productsPriceTotal; ?>);
            Mall.reg.set("quote_discount_total", <?php echo $discountTotal; ?>);

            Mall.reg.set("deliverySet", <?php echo $deliveryMethods; ?>);
        })();
    </script>

        <div class="shipping-collect">
            <?php if (!empty($selectedShipping) && isset($selectedShipping["methods"])): ?>
                <?php foreach ($selectedShipping["methods"] as $vendorId => $methodSelected): ?>
                    <input type="hidden"
                           name="shipping_method[<?php echo $vendorId; ?>]"
                           value="<?php echo $methodSelected; ?>" />
                <?php endforeach; ?>
                <?php if (isset($methodSelected) && isset($selectedShipping["shipping_point_code"])): ?>
                    <?php $shippingPointCode = $this->getDeliveryPointData($selectedShipping["shipping_point_code"]); ?>
                    <?php if(!empty($shippingPointCode)): ?>
                        <input type="hidden" name="shipping_point_code"
                               data-id="<?php echo $shippingPointCode["id"]; ?>"
                               data-town="<?php echo $shippingPointCode["city"]; ?>"
                               value="<?php echo $shippingPointCode["value"]; ?>" />
                    <?php endif; ?>
                <?php endif; ?>
            <?php endif; ?>
        </div>

    <div class="shipping-method-selected" <?php if(empty($sessionShippingMethod)): ?>style="display:none;"<?php endif; ?>>
        <header>
            <h2><?php echo $this->__("Your shopping"); ?></h2>
        </header>
        <ul id="product_summary" class="shipping-method-selected" <?php if(empty($sessionShippingMethod)): ?>style="display:none;"<?php endif; ?>>
            <?php echo $this->getChildHtml('totals'); ?>
        </ul>
        <?php if (empty($sessionShippingMethod)): ?>
            <div class="shipping-method-selected-container">
                <div data-item="method"></div>
                <div class="shipping-data-additional">
                    <div data-item="additional"></div>
                    <div data-item="description"></div>
                    <div class="pull-left"><div data-item="logo"></div></div>
                    <?php if (count($methods) > 1): ?>
                        <div class="pull-right">
                            <a class="button button-third large pull-right" id="change-shipping-type">
                                <?php echo $helper->__("Change"); ?>
                            </a>
                        </div>
                    <?php endif; ?>
                </div>
            </div>
            <br />
            <?php else: ?>

            <?php foreach ($methods as $method): ?>
                <?php

                $formattedCost = '';
                if (isset($cost[$method['code']])) {
                    $costSum = array_sum($cost[$method['code']]);
                    $formattedCost = Mage::helper('core')->currency($costSum, true, false);
                }

                $daysInTransit = !empty($method["days_in_transit"]) ? $helper->__("ships within %s days", $method["days_in_transit"]) : "";
                ?>
                <?php if ($method['code'] ==$sessionShippingMethod): ?>
                    <div class="shipping-method-selected-container">
                        <div data-item="method"><?php echo $this->escapeHtml($method['method_title']); ?></div>


                        <div class="shipping-data-additional">
                            <div data-item="additional">
                                <?php if ($deliveryPoint->id): ?>
                                    <?php echo $this->getDeliveryDataAdditional($method["delivery_type"], $selectedShipping["shipping_point_code"]); ?>
                                <?php endif; ?>
                            </div>
                            <div data-item="description"><?php echo $daysInTransit; ?></div>

                            <div class="pull-left">
                                <div data-item="logo"><?php echo Mage::helper("wfwf/checkout_data")->getCarrierLogo($method["delivery_type"]); ?></div>
                            </div>
                            <?php if (count($methods) > 1): ?>
                                <div class="pull-right">
                                    <a class="button button-third large pull-right" id="change-shipping-type">
                                        <?php echo $helper->__("Change"); ?>
                                    </a>
                                </div>
                            <?php endif; ?>
                        </div>
                    </div>
                    <br />
                <?php endif; ?>
            <?php endforeach; ?>
            <?php endif; ?>
    </div>
    <div class="shipping-method-selector" <?php if(!empty($sessionShippingMethod)): ?>style="display:none;"<?php endif; ?>>
        <header>
            <h2><?php echo $this->__("Select delivery"); ?></h2>
        </header>
        <div class="data-validate"></div>
        <?php foreach ($methods as $method): ?>
            <?php
            $formattedCost = '';
            if (isset($cost[$method['code']])) {
                $costSum = array_sum($cost[$method['code']]);
                $formattedCost = Mage::helper('core')->currency($costSum, true, false);
            }
            $carrierLogo = Mage::helper("wfwf/checkout_data")->getCarrierLogo($method["delivery_type"]);
            $daysInTransit = !empty($method["days_in_transit"]) ? $helper->__("ships within %s days", $method["days_in_transit"]) : "";

            ?>
            <div class="panel panel-default data_shipping_item">
                <div class="panel-body">

                        <div class="pull-left">
                            <div class="form-group form-radio">
                                <input type="radio"
                                    <?php if(count($methods) == 1): ?> style="display: none;visibility: hidden; height: 0;" <?php endif; ?>
                                       value="<?php echo $method['code']; ?>"
                                       <?php if($method['code']==$sessionShippingMethod || (count($methods) == 1)): ?>checked<?php endif; ?>
                                       name="_shipping_method"
                                       required="required"
                                       class="shipping-method css-radio"
                                       data-select-shipping-method-trigger="<?php echo (int)(!$this->isDeliveryPointSelectRequired($method["delivery_type"])); ?>"
                                       data-carrier-name="<?php echo $this->escapeHtml($method['carrier_title']); ?>"
                                       data-carrier-method="<?php echo $this->escapeHtml($method['method_title']); ?>"
                                       data-carrier-description="<?php echo $daysInTransit; ?>"
                                       data-carrier-logo='<?php echo $carrierLogo; ?>'
                                       data-method-cost="<?php echo $costSum; ?>"
                                       data-method-cost-formatted="<?php echo $formattedCost; ?>"
                                       data-carrier-delivery-type="<?php echo $method["delivery_type"]; ?>"
                                       data-carrier-additional=""
                                       data-carrier-pointcode=""
                                />

                                <label class="css-label shipping-with-description clearfix">
                                    <span class="pull-left label-wrapper">
                                        <?php echo $method['method_title'] ?>
                                        <div class="shipping-description">
                                            <?php echo $daysInTransit; ?>
                                        </div>
                                    </span>

                                </label>
                            </div>
                        </div>

                        <div class="pull-right delivery_type_cost"><?php echo $formattedCost; ?></div>

                </div>
            </div>
        <?php endforeach; ?>
    </div>





    <?php else: ?>
        <div class="panel panel-default panel-color">
            <div class="panel-body">
                <dl class="pull-left">
                    <?php echo $this->__('No delivery method available'); ?>
                </dl>
            </div>
        </div>
    <?php endif; ?>
</form>
</fieldset>

<?php echo $this->getChildHtml('checkout_cart_shipping_additional'); ?>

<script type="text/javascript" src="//maps.google.com/maps/api/js?v=3&sensor=FALSE"></script>