<?php
/** @var Ced_SocialLogin_Block_Facebook_Button $this */
$url = $this->escapeUrl($this->_getButtonUrl());
$inLogin = $this->getRequest()->getActionName() == 'login';
?>
<?php if(!$this->isLogged()): ?>
	<?php $redirect = $this->getClient()->getRedirectUri(); ?>
	<a onclick="Mall.socialLogin('<?php echo $url ?>','<?php echo $redirect ?>');">
    <?php //echo $this->_getButtonText(); ?>
		<?php /* <div class="ced-sociallogin-facebook-inner <?php echo $this->_getButtonClass(); ?>"></div> */ ?>
		<div class="button btn-social fb small">
			<?php if($inLogin): ?>
				<?php echo Mage::helper("sociallogin")->__("Login"); ?>
			<?php else: ?>
				<?php echo Mage::helper("sociallogin")->__("Connect account"); ?>
			<?php endif; ?>
		</div>
    </a>
<?php else: ?>
	<a href="<?php echo $url ?>">
		<?php //echo $this->_getButtonText(); ?>
		<?php /* <div class="ced-sociallogin-facebook-inner <?php echo $this->_getButtonClass(); ?>"></div> */ ?>
		<div class="button btn-social fb small"><?php echo Mage::helper("sociallogin")->__("Disconnect account"); ?></div>
	</a>
<?php endif; ?>