<?php $key = $this->getFacetKey(); ?>
<?php if ($this->getCanShow()): ?>
    <?php
    $sectionClass = $this->isFilterRolled() ? 'closed' : 'open';
    $iconClass = $this->isFilterRolled() ? "fa-chevron-down" : "fa-chevron-up";
    $isOptionSelected = false;
    $key_withoutFacet = explode("_", $key);
    array_pop($key_withoutFacet);
    ?>
    <div class="section clearfix">
        <h3 class="<?php echo $sectionClass; ?>"><span><?php echo $this->getFacetLabel(); ?></span> <i class="fa <?php echo $iconClass; ?>"></i></h3>
        <div id="filter_<?php echo $key ?>" class="content checkbox filter-enum">
            <?php foreach ($this->getItems() as $item => $count): ?>
                <?php if ($this->getCanShowItem($item, $count)): ?>
                    <?php
                    if(!$isOptionSelected && $this->isItemActive($item)) {
                        $isOptionSelected = true;
                    }
                    ?>
                    <div class="form-group form-checkbox">
                        <input data-url="<?php echo $this->getItemUrl($item) ?>" data-params='<?php echo $this->getItemJson($item);?>' type="checkbox" name="check_<?php echo $item; ?>" id="check_<?php echo $item; ?>" class="css-checkbox" <?php if($this->isItemActive($item)): ?>checked="checked" <?php endif; ?>>
                        <label for="check_<?php echo $item; ?>" class="css-label"><span><?php echo $item ?></span>&nbsp;<span class="suffix">(<?php echo $count ?>)</span></label>
                    </div>
                <?php endif; ?>
            <?php endforeach; ?>
            <?php if ($this->getCanShowHidden()): ?>
                <?php foreach ($this->getHiddenItems() as $item => $count): ?>
                    <div class="form-group form-checkbox" data-state="hidden" style="display: none;">
                        <input data-url="<?php echo $this->getItemUrl($item) ?>" data-params='<?php echo $this->getItemJson($item);?>' type="checkbox" name="check_<?php echo $item; ?>" id="check_<?php echo $item; ?>" class="css-checkbox" <?php if($this->isItemActive($item)): ?>checked="checked" <?php endif; ?>>
                        <label for="check_<?php echo $item; ?>" class="css-label"><span><?php echo $item ?></span>&nbsp;<span class="suffix">(<?php echo $count ?>)</span></label>
                    </div>
                <?php endforeach; ?>
                <div class="action clearfix">
                    <a href="#" class="go_read_filter underline showmore-filters" data-state="0"><?php echo $this->__("Show more"); ?></a>
                </div>
            <?php endif; ?>
            <div class="action clear clearfix <?php if(!$isOptionSelected) : ?>hidden<?php endif; ?>">
                <a href="#" data-filter-type="<?php echo implode("_", $key_withoutFacet); ?>" onclick="Mall.listing.removeSingleFilterType(this);return false;" class="button button-third clear"><?php echo $this->__("Clear"); ?></a>
            </div>
        </div>
    </div>
<?php endif; ?>