<?php
/* @var $this Zolago_Solrsearch_Block_Catalog_Product_List_Header_Category */
$_categoryBlock = Mage::getBlockSingleton('zolagomodago/catalog_category');
/** @var Zolago_Dropship_Model_Vendor $vendor */
$vendor = Mage::helper('umicrosite')->getCurrentVendor();
$isBrandshop = $vendor ? $vendor->isBrandshop() : null;
$vendorTypeLabel =$vendor ?  $vendor->getVendorTypeLabel() : false;
?>

<?php if($this->isContentMode()): ?>
<header data-test="5" id="header-main"  class="visible-xs">
    <div class="wrapp-section bg-w">
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-12 header-panel">
                <?php if(!$vendor): ?>
                    <div id="breadcrumbs-header">
                        <?php //echo $this->getChildHtml('zolagocatalog_breadcrumbs'); ?>
                    </div>
                    <div id="view-current-filter" >
                        <h1><?php echo $this->getCategory()->getLongName(); ?></h1>
                        <a href="<?php echo $_categoryBlock->getMoveUpUrl(); ?>" class="backToCategory underline visible-xs"><?php echo $this->__("Go up"); ?></a>
                    </div>
                    <div id="active-filters-wrapper">
                        <?php echo $this->getChildHtml('solrsearch_product_list_active'); ?>
                    </div>
                <?php else: ?>
                    <div id="category-header-left">
                        <div id="category-header-vendor-box">
                            <?php if(!empty($vendorTypeLabel)): ?>
                            <div class="vendor-header-label">
                                <?php echo $vendor->getVendorTypeLabel(); ?>
                            </div>
                        <?php endif; ?>
                            <a href="<?php echo $vendor->getVendorUrl(); ?>">
                                <div class="vendor-header-logo" style="background-image:url(<?php echo $vendor->getVendorLogoUrl(); ?>)"></div>
                            </a>
                        </div>
                    </div>
                    <div style="clear:both" class="visible-xs"></div>
                    <div id="category-header-right">
                        <div class="right-wrapper">
                            <div id="breadcrumbs-header">
                                <?php //echo $this->getChildHtml('zolagocatalog_breadcrumbs'); ?>
                            </div>
                            <div id="view-current-filter">
                                <h1><?php echo $this->getCategory()->getLongName(); ?></h1>
                                <a href="<?php echo $_categoryBlock->getMoveUpUrl(); ?>" class="backToCategory underline visible-xs"><?php echo $this->__("Go up"); ?></a>
                            </div>
                            <div id="active-filters-wrapper">
                                <?php echo $this->getChildHtml('solrsearch_product_list_active'); ?>
                            </div>
                        </div>
                    </div>
                <?php endif; ?>
                </div>
            </div>
        </div>
    </div>
</header>
<?php endif; ?>





