<?php $_helper = Mage::helper("zolagorma"); ?>

<?php $_rma = $this->getRma();?>
<?php $poId = $_rma->getUdpoId(); ?>


<?php echo $this->getChildHtml("zolagormatranslate"); ?>
<div class="page-title box-wrapper">
	<h1>
		<span><?php echo $_helper->__("Returns and complaints"); ?></span>
		<span class="back-sm"><a href="<?php echo $this->getUrl('customer/account/index/');?>" class="underline"><?php echo $_helper->__('back: my account'); ?>&nbsp;&gt;</a></span>
		<span class="back-xs"><a href="<?php echo $this->getUrl('customer/account/index/');?>" class="underline"><?php echo $_helper->__('back'); ?>&nbsp;&gt;</a></span>
	</h1>
</div>
<form method="post" id="edit-rma" action="<?php echo $this->getUrl('*/rma/saveCourier') ?>">
	<input type="hidden" name="po_id" value="<?php echo $poId; ?>">
    <input type="hidden" name="rma_id" value="<?php echo $_rma->getId(); ?>">
    <?php echo $this->getChildHtml("bookcourier"); ?>
</form>
<?php echo $this->getChildHtml("zolagormajs"); ?>
