<?php $_helper = Mage::helper("zolagorma"); ?>
<?php $_po = $this->getPo(); ?>
<?php $_rma = $this->getRma();?>
<?php $_shippingAddress = $_po->getShippingAddress(); ?>
<?php $_itemsSingle = $_rma->getItemsSingle(); ?>
<?php $_itemsConditionSingle = $_rma->getItemsConditionSingle(); ?>
<?php if ($items = $this->getItemList()): ?>

<div class="page-title box-wrapper">
	<h1>
		<span><?php echo $_helper->__("Returns and complaints"); ?></span>
		<span class="back-sm"><a href="<?php echo $this->getUrl('customer/account/index/');?>" class="underline"><?php echo $_helper->__('back: my account'); ?>&nbsp;&gt;</a></span>
		<span class="back-xs"><a href="<?php echo $this->getUrl('customer/account/index/');?>" class="underline"><?php echo $_helper->__('back'); ?>&nbsp;&gt;</a></span>
	</h1>
</div>
<form method="post" id="new-rma" action="<?php echo $this->getUrl('*/*/saveRma', array("_secure"=>Mage::app()->getStore()->isCurrentlySecure())) ?>">
	<input type="hidden" name="po_id" value="<?php echo $this->getPo()->getId(); ?>">
	<?php echo $this->getChildHtml("zolagorma.new.step1");?>
	<?php echo $this->getChildHtml("zolagorma.new.step2");?>
	<?php echo $this->getChildHtml("zolagorma.new.step3");?>
</form>

<script type="text/javascript">
	jQuery(function(){
		var returnReasons = <?php echo Mage::helper('zolagorma')->getReturnReasons($_po, true); ?>;
		Mall.rma.new.setReturnReasons(returnReasons);
		
		<?php foreach($_helper->getItemConditionTitlesForFront() as $_key=>$_label):?>
		Mall.rma.new.addValidator(
			'must-be-available-<?php echo $_key; ?>',
			returnReasons[<?php echo $_key; ?>].message, 
			function(value, element, params){
				var currentReason = returnReasons[value];
				if(!currentReason){
					return false;
				}
				return currentReason.isAvailable;
			}
		);
		<?php endforeach;?>
			
		Mall.rma.new.setUnloadMessage('<?php echo $_helper->__('Do You really want to leave RMA process?');?>');
		Mall.rma.new.setNotAvailableText('<?php echo $_helper->__('Not available');?>');
		Mall.rma.new.init();
	});
</script>
<?php endif; ?>