<?php /* @var $this Zolago_Rma_Block_View */ ?>
<?php $_helper = Mage::helper("zolagorma"); ?>
<?php $_rma = $this->getRma();?>
<?php $carrierDate = $_rma->getCarrierDate(); ?>
<?php $weekdays = Mage::app()->getLocale()->getOptionWeekdays();?>
<div class="page-title box-wrapper">
	<h1>
		<span><?php echo $_helper->__("Returns and complaints"); ?></span>
		<span class="back-sm"><a href="<?php echo $this->getUrl('customer/account/index/');?>" class="underline"><?php echo $_helper->__('back: my account'); ?>&nbsp;&gt;</a></span>
		<span class="back-xs"><a href="<?php echo $this->getUrl('customer/account/index/');?>" class="underline"><?php echo $_helper->__('back'); ?>&nbsp;&gt;</a></span>
	</h1>
</div>

<div class="section background-wrapper box-wrapper rma-po-list <?php echo $this->getIsClaim($_rma) ? "rma-claim" : "rma-return";?>">
	<header class="title-section">
		<div class="headerTop">
			<h2><?php echo $_helper->__("RMA no."); ?>: <?php echo $_rma->getIncrementId();?></h2>
		</div>
	</header>
	<div class="rma-section rma-caption">
		<span class="bold"><?php echo $_helper->__("RMA Date"); ?></span>: <?php echo Mage::helper("core")->formatDate($_rma->getCreatedAt());?><br/>
		<span class="bold"><?php echo $_helper->__("Vendor"); ?></span>: <span class="uppercase"><?php echo $this->escapeHtml($_rma->getVendor()->getVendorName());?></span>
	</div>
	<?php if($_monits = $this->getMonits($_rma)):?>
	<div class="rma-monit rma-section">
                <?php foreach($_monits as $monit):?>
                    <?php echo $monit;?>
                <?php endforeach;?>
		<?php if(($_pdfUrl=$this->getPdfUrl($_rma)) && $this->isPendingPickup($_rma)):?>
			<a href="<?php echo $_pdfUrl;?>" class="button button-primary download-doc"><?php echo $_helper->__("Download a document"); ?></a>
		<?php endif;?>
        <?php if ($this->isPendingCourierBooking($_rma)): ?>
                <a href="/sales/rma/courier/id/<?php echo $_rma->getId(); ?>" class="button button-primary download-doc">
                    <?php echo $_helper->__("Book a courier"); ?>
                </a>
        <?php endif; ?>
	</div>
	<?php endif;?>
	<div class="row">
		<div class="col-sm-4">
			<div class="rma-status rma-section">
				<p>
					<i class="glyphicon glyphicon-info-sign"></i>
					<span class="uppercase"><?php echo $_helper->__("Progress status"); ?></span>
				</p>
				<div>
					<?php echo $this->escapeHtml($this->getStatusCustomerText($_rma));?>
				</div>
			</div>
			<?php if($this->isPendingPickup($_rma)):?>
				<div class="rma-section rma-content">
					<p>
						<i class="glyphicon glyphicon-time"></i>
						<span class="uppercase"><?php echo $_helper->__("Carrier date"); ?></span>
					</p>
					<div>
                        <?php if(!empty($carrierDate)): ?>
                        <?php echo $weekdays[date('w',strtotime($carrierDate))]['label'];?>
						<?php echo Mage::helper("core")->formatDate($carrierDate, "short");?><br/>
						<?php echo $_helper->__(
							"between %s and %s", 
							$_rma->getCarrierTimeFrom() ? $_rma->getCarrierTimeFrom() : $_helper->__("N/A"), 
							$_rma->getCarrierTimeTo() ? $_rma->getCarrierTimeTo() : $_helper->__("N/A")); 
						?>
                        <?php endif; ?>
					</div>
				</div>
				<?php if($_address=$_rma->getShippingAddress()):?>
					<div class="rma-section rma-content">
						<p>
							<i class="glyphicon glyphicon-envelope"></i>
							<span class="uppercase"><?php echo $_helper->__("Your address"); ?></span>
						</p>
						<div>
							<?php echo $_address->format("html");?>
						</div>
					</div>
				<?php endif;?>
			<?php endif;?>



			<div class="rma-section rma-content">
				<p>
					<i class="glyphicon glyphicon-list-alt"></i>
					<span class="uppercase"><?php echo $_helper->__("RMA Content"); ?></span>
				</p>
				<div class="rma-content-1">

						<?php foreach($_rma->getItemsCollection() as $item):?>
						<?php if($item->getPoItem()->getId()): ?>
						<div class="rma-content-item">
							<div class="img">
								<img src="<?php echo $this->getRmaItemThumb($item);?>" alt=""/>
							</div>
							<div class="desc" style="margin-top: -<?php echo$this->getRmaItemThumbHeight($item).'px;' ;?>">
								<p>
									<span><?php echo $this->escapeHtml($item->getName());?></span>
									<?php if($_attributes = $this->getConfigurableAttributesByItem($item)):?>
										<br/>
										<small>
										<?php foreach($_attributes as $value):?>
											<?php echo $this->escapeHtml($value['label']);?>: <?php echo $this->escapeHtml($value['value']);?>
										<?php endforeach;?>
										</small>
									<?php endif;?>
								</p>
								<div>
									<span class="bold"><?php echo $_helper->__("Return reason");?>:</span><br/>
									<?php echo $this->getItemCondition($item);?>
								</div>
							</div>
						</div>
						<?php endif; ?>
						<?php endforeach;?>

				</div>
				<?php if($_rma->getCommentText()):?>
				<div class="comment-text">
					<?php echo $this->escapeHtml($_rma->getCommentText());?>
				</div>
				<?php endif;?>
			</div>
		</div>
		<div class="col-sm-8">
            <div class="rma-connect-vendor">
                <div class="rma-connect-vendor-pannel rma-section">
                    <p>
                        <i class="glyphicon glyphicon-comment"></i>
                        <span class="caption uppercase">
                            <?php echo $_helper->__("Contact with vendor"); ?>
                        </span>
                        <i class="fa fa-chevron-down"></i>
                    </p>
                </div>
                <div class="rma-connect-vendor-form rma-section">
                    <?php echo $this->getChildHtml("zolagorma_vendor_detail"); ?>
                </div>
            </div>

			<div class="rma-section rma-comments">
				<p>
					<i class="glyphicon glyphicon-align-left"></i>
					<span class="uppercase"><?php echo $_helper->__("History"); ?></span>
				</p>
				<?php $_comments = $this->getCommentCollection($_rma)?>
				<?php if($_comments->getSize()):?>
					<table>
						<tbody>
							<?php foreach($_comments as $_comment):?>
							<?php /* @var $_comment ZolagoOs_Rma_Model_Rma_Comment */ ?>
							<tr>
								<td class="author">
									<?php echo Mage::helper('core')->formatDate($_comment->getCreatedAt(), "short", true);?><br/>
									<?php echo $this->getCommentAuthor($_comment); ?>
								</td>
								<td class="desc">
									<p><?php echo $_helper->formatComment($_comment);?></p>
								</td>
							</tr>
							<?php endforeach;?>
						</tbody>
					</table>
				<?php else:?>
					<p><?php echo $_helper->__("There is no RMA comments"); ?></p>
				<?php endif;?>
			</div>
		</div>
	</div>
</div>