<?php $_helper = Mage::helper("zolagorma"); ?>

<?php $_rma = $this->getRma();?>
<?php
$poId = $_rma->getUdpoId();
$_po = $this->getPo();

?>
<?php $_shippingAddress = $_po->getShippingAddress();
?>
<?php $_itemsSingle = $_rma->getItemsSingle(); ?>
<?php $_itemsConditionSingle = $_rma->getItemsConditionSingle(); ?>
<?php $dateList = $this->getDateList(); ?>
<?php $weekdays = Mage::app()->getLocale()->getOptionWeekdays();?>
<?php $vendor = $_po->getVendor();?>

<div class="page-title box-wrapper">
	<h1>
		<span><?php echo $_helper->__("Returns and complaints"); ?></span>
		<span class="back-sm"><a href="<?php echo $this->getUrl('customer/account/index/');?>" class="underline"><?php echo $_helper->__('back: my account'); ?> &gt;</a></span>
		<span class="back-xs"><a href="<?php echo $this->getUrl('customer/account/index/');?>" class="underline"><?php echo $_helper->__('back'); ?> &gt;</a></span>
	</h1>
</div>
<form method="post" id="new-rma" action="<?php echo $this->getUrl('*/rma/saveCourier') ?>">
	<input type="hidden" name="po_id" value="<?php echo $poId; ?>">
    <input type="hidden" name="rma_id" value="<?php echo $_rma->getId(); ?>">
    <div class="steps step-2 background-wrapper box-wrapper" id="step-2">
        <input type="hidden" name="form_key" value="<?php echo $this->getFormKey();?>"/>
        <input type="hidden" name="country_id" id="country_id" value="<?php echo $this->getDefaultCountryId();?>"/>
        <div class="rma-container">
            <?php //if (($this->isDhlEnabled()) && count($dateList)) : ?>
                <div id="pickup-address-form" class="fieldset flow-return">
                    <input type="hidden" id="can_init_addressbook" value="1"/>
                    <input type="hidden" name="rma[customer_address_id]" id="customer_address_id" value="<?php echo $this->getSelectedShipping(); ?>"/>
                    <input type="hidden" name="rma[override_address]" value="0"/>
                    <h3 class="legend-big"><?php echo $_helper->__("Book the courier"); ?></h3>
                    <h3 class="legend"><?php echo $_helper->__("Confirm or change pickup address for the courier"); ?>:</h3>

                    <!-- selected address tmplate -->
                    <div class="hidden" id="selected-address-template">
                        <p class="pull-right small-no-float"><?php echo $_helper->__("Selected carrier address");?></p>
                        <dl class="pull-left" >
                            <dt>{{firstname}} {{lastname}}</dt>
                            <dd>{{street}}</dd>
                            <dd>{{postcode}} {{city}}</dd>
                            <dd class="phone"><?php echo $this->__("Contact phone")?>: <span>{{telephone}}</span></dd>
                            <dd class="action separator">
                                <a href="#" class="underline edit"><?php echo $this->__("edit");?></a>
                            </dd>
                        </dl>
                    </div>

                    <!-- normal address tmplate -->
                    <div class="panel panel-default hidden" id="normal-address-template">
                        <div class="panel panel-default">
                            <div class="panel-body">
                                <dl class="pull-left small-no-float">
                                    <dt>{{firstname}} {{lastname}}</dt>
                                    <dd>{{street}}</dd>
                                    <dd>{{postcode}} {{city}}</dd>
                                    <dd class="action separator">
                                        <a href="#" class="underline edit"><?php echo $this->__("edit");?></a>
                                        <a href="#" class="underline remove"><?php echo $this->__("remove");?></a>
                                    </dd>
                                </dl>
                                <button class="btn-select button button-third large choose"><?php echo $this->__("Choose")?></button>
                            </div>
                        </div>
                    </div>

                    <!-- add new template -->
                    <div class="panel add-new hidden" id="addressbook-add-new-template" data-toggle="modal" data-target="#addressbook-modal">
                        <div class="panel-body">
                            <h4 class="addressbook-add-new"><i class="fa fa-plus-circle fa-lg"></i>&nbsp;<strong><?php echo $this->__("ADD NEW ADDRESS"); ?></strong></h4>
                            <div class="panel-body-content">

                            </div>
                        </div>
                    </div>

                    <!-- Edit / add mdoal -->
                    <div class="modal fade bs-example-modal-lg" id="addressbook-modal" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true" style="overflow-y: scroll !important">
                        <div class="modal-dialog modal-lg">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <button type="button" class="close" data-dismiss="modal"></button>
                                    <h2 class="title_section" id="modal-title"></h2>
                                </div>
                                <div class="modal-body" id="modal-body">
                                </div>
                            </div>
                        </div>
                    </div>


                    <div class="panel panel-default">
                        <div class="panel-body panel-body-with-footer">
                            <div class="current-rma-address current-address shipping clearfix">
                                <!-- content from js -->
                            </div>
                            <div class="panel-adresses shipping">
                                <!-- content from js -->
                            </div>
                        </div>
                        <div class="panel-footer clearfix">
                            <a href="#" class="underline pull-right change_address shipping">
                                <?php echo $this->__("Change address");?>
                            </a>
                        </div>
                    </div>

                </div>
                <div id="pickup-date-form">
                    <h3 class="legend"><?php echo $_helper->__("Schedule pickup date that is convenient for you"); ?></h3>
                    <div class="panel panel-default">
                        <div class="panel-body">
                            <?php if(count($dateList) != 0): ?>
                            <div class="current-rma-date clearfix">
                                <div id="pickup-date-form-panel" class="fieldset flow-return">

                                    <label class="required choose-date" for="carrier-date"><?php echo $_helper->__("Choose the date"); ?>
                                        <em>:</em></label>

                                    <div class="input-box" id="dateList">
                                        <?php $isEven = true; ?>
                                        <?php $number = 1; ?>
                                        <?php foreach ($dateList as $date=>$item): ?>

                                            <input
                                                type="radio"
                                                name="rma[carrier_date]"
                                                id="carrier_date_<?php echo $date;?>"
                                                value="<?php echo date('Y-m-d',$date);?>"
                                                />
                                            <label for="carrier_date_<?php echo $date;?>" class="<?php echo $isEven ? 'label-even' : 'label-odd'; ?> <?php echo "label-$number";?>">
                                            <span>
                                                <span class="rma-dayname"><?php echo $weekdays[date('w',$date)]['label'];?></span>
                                                <br/>
                                                <span class="rma-date"><?php echo $this->getFormattedDate($date);?></span>
                                            </span>
                                            </label>
                                            <?php $isEven = !$isEven; ?>
                                            <?php $number++; ?>
                                        <?php endforeach; ?>
                                    </div>

                                    <label class="required carrier-time-from"
                                           for="carrier-time-from"><?php echo $_helper->__("Select the time interval"); ?>
                                        <em>:</em></label>
                                    <div class="choose-time">
                                        <div class="field">
                                            <div class="input-box">
                                                <input type="hidden" name="rma[carrier_time_from]" id="carrier-time-from"
                                                       value="<?php echo $_rma->getCarrierTimeFrom(); ?>"
                                                       title="<?php echo $_helper->__("Choose time-from of the day"); ?>"/>
                                                <input type="hidden" name="rma[carrier_time_to]" id="carrier-time-to"
                                                       value="<?php echo $_rma->getCarrierTimeTo(); ?>"
                                                       title="<?php echo $_helper->__("Choose time-to of the day"); ?>"/>
                                            </div>
                                            <div id="pickup-time"></div>
                                        </div>
                                        <div id="slider-range"></div>
                                    </div>
                                </div>
                                <?php endif; ?>
                                <?php if(count($dateList) == 0): ?>
                                    <?php echo $_helper->__("For the given address is not possible to order a courier"); ?>
                                <?php endif; ?>
                            </div>
                        </div>

                    </div>
                </div>

            <?php //endif;?>


        </div>
        <div class="rma-container">
            <a href="/sales/rma/view/id/<?php echo $_rma->getId(); ?>" class="button button-third large back pull-left">
                <?php echo $_helper->__("Back"); ?>
            </a>
            <button class="btn button button-primary next pull-right"
                    type="button" id="btn-next-step-2"><?php echo $_helper->__("Next"); ?></button>
        </div>
    </div>
</form>


<script type="text/javascript">
    //TRANSLATIONS
    Mall.translate.add("Selected time", "<?php echo $_helper->__('Selected time') ?>");
    Mall.translate.add("For your address is only available time interval", "<?php echo $_helper->__('For your address is only available time interval') ?>");
    Mall.translate.add("between the hours", "<?php echo $_helper->__("between the hours") ?>");
    Mall.translate.add("and", "<?php echo $_helper->__("and") ?>");
    Mall.translate.add("For your address, there are dates from ", "<?php echo $_helper->__("For your address, there are dates from ") ?>");
    Mall.translate.add(" to ", "<?php echo $_helper->__(" to ") ?>");
    Mall.translate.add("Bank account number must contain 26 digits.", "<?php echo $_helper->__("Bank account number must contain 26 digits.") ?>");
    // Addressbook transaltion
    Mall.translate.add("no-addresses", "<?php echo $_helper->__("No addresses");?>");
    Mall.translate.add("edit-address", "<?php echo $_helper->__("Edit address");?>");
    Mall.translate.add("add-new-address", "<?php echo $_helper->__("Add new address");?>");
    Mall.translate.add("save", "<?php echo $_helper->__("Save");?>");
    Mall.translate.add("firstname", "<?php echo $_helper->__("Firstname");?>");
    Mall.translate.add("lastname", "<?php echo $_helper->__("Lastname");?>");
    Mall.translate.add("company-name", "<?php echo $_helper->__("Company name");?>");
    Mall.translate.add("optional", "<?php echo $_helper->__("optional");?>");
    Mall.translate.add("nip", "<?php echo $_helper->__("NIP");?>");
    Mall.translate.add("street-and-number", "<?php echo $_helper->__("Street and number");?>");
    Mall.translate.add("postcode", "<?php echo $_helper->__("Postcode");?>");
    Mall.translate.add("city", "<?php echo $_helper->__("City");?>");
    Mall.translate.add("phone", "<?php echo $_helper->__("Phone");?>");
    Mall.translate.add("address-cant-be-removed", "<?php echo $_helper->__("Address can't be removed.");?>");
    Mall.translate.add("selected-carrier-address", "<?php echo $_helper->__("Selected carrier address") ?>");
    Mall.translate.add("change-address", "<?php echo $_helper->__("Change address");?>");
    Mall.translate.add("your-additional-addresses", "<?php echo $_helper->__("Your additional addresses");?>");
    Mall.translate.add("roll-up", "<?php echo $_helper->__("Roll up");?>");
    // Messages
    Mall.translate.add("Invalid zip-cod. Zip-code should include 5 numbers in XX-XXX format.", "<?php echo $this->__("Invalid zip-cod. Zip-code should include 5 numbers in XX-XXX format."); ?>");
    Mall.translate.add("Telephone numer is too short. Number must contain 9 digits, without spacing.", "<?php echo $this->__("Telephone numer is too short. Number must contain 9 digits, without spacing."); ?>");
    Mall.translate.add("email", "<?php echo $this->__('Valid email is required.') ?>");
    Mall.translate.add("Password needs to have at least %s characters", "<?php echo $this->__("Password needs to have at least %s characters", Mage::helper("zolagocustomer")->getPasswordMinLength()); ?>");
    Mall.translate.add("Zip code should be entered in the format xx-xxx.", "<?php echo $this->__("Zip code should be entered in the format xx-xxx."); ?>");
    Mall.translate.add("required", "<?php echo $this->__("This is a required field."); ?>");
    Mall.translate.add("email", "<?php echo $this->__("E-mail address is in invalid format or contains invalid characters. Please enter correct address."); ?>");
    Mall.translate.add("Tax numer is incorrect. Enter as a string of digits e.g. 1234567890.", "<?php echo $this->__('Tax numer is incorrect. Enter as a string of digits e.g. 1234567890.') ?>");
    Mall.translate.add("Enter name.", "<?php echo $this->__('Enter name.') ?>");
    Mall.translate.add("Enter last name.", "<?php echo $this->__('Enter last name.') ?>");
    Mall.translate.add("Enter email address.", "<?php echo $this->__('Enter email address.') ?>");
    Mall.translate.add("Enter street and number.", "<?php echo $this->__('Enter street and number.') ?>");
    Mall.translate.add("Enter company name.", "<?php echo $this->__('Enter company name.') ?>");
    Mall.translate.add("Enter city name.", "<?php echo $this->__('Enter city name.') ?>");
    Mall.translate.add("Zip-code should be entered in the format xx-xxx.", "<?php echo $this->__('Zip-code should be entered in the format xx-xxx.') ?>");
    Mall.translate.add("Phone number we need only to contact concerning orders for example courier delivering the shipment.", "<?php echo $this->__('Phone number we need only to contact concerning orders for example courier delivering the shipment.') ?>");

    //TRANSLATIONS END

    //INIT DATA
    var rmaCarrierTimeFrom = '<?php echo $_rma->getCarrierTimeFrom(); ?>';
    var rmaCarrierTimeTo = '<?php echo $_rma->getCarrierTimeTo(); ?>';
    var dateList = <?php echo json_encode($dateList); ?>;
    var dateListFormatedDate = [];

    <?php // formatted date for next 20 (max) days from today
    for($count = 0; $count < 20 ; $count++) {
        $timestamp = time()+$count*3600*24;
        $index = date('Y-m-d',$timestamp);
        echo "dateListFormatedDate['$index'] = '" . $this->getFormattedDate($timestamp) . "';\n";
    }
    ?>


    //converting weekdays to array
    var weekdays = <?php echo json_encode($weekdays); ?>;
    var arr = [];
    for (var prop in weekdays) {
        arr[prop] = (weekdays[prop].label);
    }
    weekdays = arr;
    //converting weekdays to array END

    //applyFlow
    var isAcknowledged = false;
    var returnReasons = '<?php echo Mage::helper("zolagorma")->getReturnReasons($_po, true); ?>';
    var flowAcknowledged = '<?php echo Zolago_Rma_Model_Rma::FLOW_ACKNOWLEDGED; ?>';
    var ajaxLoaderSkinUrl = '<?php echo $this->getSkinUrl("images/modago-ajax-loader.gif"); ?>';
    //INIT DATE END

    jQuery(function () {
        // Address book handling
        var addressBook = new Mall.customer.AddressBook();

        addressBook.setAddressBook(<?php echo $this->getCustomerAddressesJson(); ?>);
        addressBook.setDefaultShipping(<?php echo $this->asJson($this->getDefaultShipping())?>);

        Mall.rma.new.addressbook.setAddressBook(addressBook);

        var returnReasons = <?php echo Mage::helper('zolagorma')->getReturnReasons($_po, true); ?>;
        Mall.rma.new.setReturnReasons(returnReasons);

        <?php foreach($_helper->getItemConditionTitles() as $_key=>$_label):?>
        Mall.rma.new.addValidator(
            'must-be-available-<?php echo $_key; ?>',
            returnReasons[<?php echo $_key; ?>].message,
            function (value, element, params) {
                var currentReason = returnReasons[value];
                if (!currentReason) {
                    return false;
                }
                return currentReason.isAvailable;
            }
        );
        <?php endforeach;?>


        Mall.rma.new.setNotAvailableText('<?php echo $_helper->__('Not available');?>');
        Mall.rma.new.init();
    });
</script>