<?php $_helper = Mage::helper("zolagorma"); ?>

<?php $_rma = $this->getRma();?>
<?php
$poId = $_rma->getUdpoId();
$_po = $this->getPo();

?>
<?php $_shippingAddress = $_po->getShippingAddress();
?>
<?php $_itemsSingle = $_rma->getItemsSingle(); ?>
<?php $_itemsConditionSingle = $_rma->getItemsConditionSingle(); ?>
<?php $_selectedShipping = $this->getSelectedShippingAddress();?>
<?php $dateList = array();?>
<?php //$dateList = $this->getDateList($_helper->getPostcode($_selectedShipping));?>
<?php $weekdays = Mage::app()->getLocale()->getOptionWeekdays();?>
<?php $vendor = $_po->getVendor();?>
<?php echo $this->getChildHtml("zolagorma.courier.translate"); ?>
<div class="page-title box-wrapper">
	<h1>
		<span><?php echo $_helper->__("Returns and complaints"); ?></span>
		<span class="back-sm"><a href="<?php echo $this->getUrl('customer/account/index/');?>" class="underline"><?php echo $_helper->__('back: my account'); ?> &gt;</a></span>
		<span class="back-xs"><a href="<?php echo $this->getUrl('customer/account/index/');?>" class="underline"><?php echo $_helper->__('back'); ?> &gt;</a></span>
	</h1>
</div>
<form method="post" id="edit-rma" action="<?php echo $this->getUrl('*/rma/saveCourier') ?>">
	<input type="hidden" name="po_id" value="<?php echo $poId; ?>">
    <input type="hidden" name="rma_id" value="<?php echo $_rma->getId(); ?>">
    <div class="steps step-2 background-wrapper box-wrapper" id="step-2">
        <input type="hidden" name="form_key" value="<?php echo $this->getFormKey();?>"/>
        <input type="hidden" name="country_id" id="country_id" value="<?php echo $this->getDefaultCountryId();?>"/>
        <div class="rma-container">
                <div id="pickup-address-form" class="fieldset flow-return">
                    <input type="hidden" id="can_init_addressbook" value="1"/>
                    <input type="hidden" name="rma[customer_address_id]" id="customer_address_id" value="<?php echo $_selectedShipping ? $_selectedShipping->getId() : ""; ?>"/>
                    <input type="hidden" name="rma[customer_postcode]" id="customer_address_postcode" value="<?php echo $_selectedShipping ? $_helper->getPostcode($_selectedShipping) : ''; ?>"/>
                    <input type="hidden" name="rma[override_address]" value="0"/>
                    <h3 class="legend-big"><?php echo $_helper->__("Book the courier"); ?></h3>
                    <h3 class="legend"><?php echo $_helper->__("Confirm or change pickup address for the courier"); ?>:</h3>

                    <?php echo $this->getChildHtml("zolagorma.courier.jstemplates"); ?>

                </div>
                <div id="pickup-date-form">
                    <h3 class="legend"><?php echo $_helper->__("Schedule pickup date that is convenient for you"); ?></h3>
                    <div class="panel panel-default">
                        <div class="panel-body">
                            <?php if (($this->isDhlEnabled()) && count($dateList)): ?>
                            <input type="hidden" id="can_init_carrier" value="1"/>
                            <div class="current-rma-date clearfix">
                                <div id="pickup-date-form-panel" class="fieldset flow-return">
                                    <label class="required choose-date" for="carrier-date"><?php echo $_helper->__("Choose the date"); ?>
                                        <em>:</em></label>

                                    <div class="input-box" id="dateList">
                                        <?php $number = 1; ?>
                                        <?php foreach ($dateList as $date=>$item): ?>

                                            <input
                                                type="radio"
                                                name="rma[carrier_date]"
                                                id="carrier_date_<?php echo $date;?>"
                                                value="<?php echo date('Y-m-d',$date);?>"
                                                />
                                            <label for="carrier_date_<?php echo $date;?>" class="<?php echo "label-$number";?>">
                                            <span>
                                                <span class="rma-dayname"><?php echo $weekdays[date('w',$date)]['label'];?></span>
                                                <br/>
                                                <span class="rma-date"><?php echo $this->getFormattedDate($date);?></span>
                                            </span>
                                            </label>
                                            <?php $number++; ?>
                                        <?php endforeach; ?>
                                    </div>

                                    <label class="required carrier-time-from"
                                           for="carrier-time-from"><?php echo $_helper->__("Select the time interval"); ?>
                                        <em>:</em></label>
                                    <div class="choose-time">
                                        <div class="field">
                                            <div class="input-box">
                                                <input type="hidden" name="rma[carrier_time_from]" id="carrier-time-from"
                                                       value="<?php echo $_rma->getCarrierTimeFrom(); ?>"
                                                       title="<?php echo $_helper->__("Choose time-from of the day"); ?>"/>
                                                <input type="hidden" name="rma[carrier_time_to]" id="carrier-time-to"
                                                       value="<?php echo $_rma->getCarrierTimeTo(); ?>"
                                                       title="<?php echo $_helper->__("Choose time-to of the day"); ?>"/>
                                            </div>
                                            <div id="pickup-time"></div>
                                        </div>
                                        <div id="slider-range"></div>
                                    </div>
                                </div>
                            </div>
                            <?php endif; ?>
                            <?php if(count($dateList) == 0): ?>
                                <?php echo $_helper->__("For the given address is not possible to order a courier"); ?>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>

                <div>
                    <a href="/sales/rma/view/id/<?php echo $_rma->getId(); ?>" class="button button-third large back pull-left">
                        <?php echo $_helper->__("Back"); ?>
                    </a>
                    <button class="btn button button-primary next pull-right" id="btn-next-step-2"><?php echo $_helper->__("Next"); ?></button>
                    <div class="clearfix"></div>
                </div>
        </div>
    </div>
</form>

<?php echo $this->getChildHtml("zolagorma.courier.js"); ?>
