<?php $_helper = Mage::helper("zolagorma"); ?>
<?php $_po = $this->getPo(); ?>
<?php $_rma = $this->getRma();?>
<?php $_shippingAddress = $_po->getShippingAddress(); ?>
<?php $_itemsSingle = $_rma->getItemsSingle(); ?>
<?php $_itemsConditionSingle = $_rma->getItemsConditionSingle(); ?>
<?php if ($items = $this->getItemList()): ?>

<div class="page-title box-wrapper">
	<h1>
		<span><?php echo $_helper->__("Returns and complaints"); ?></span>
		<span class="back-sm"><a href="<?php echo $this->getUrl('customer/account/index/');?>" class="underline"><?php echo $_helper->__('back: my account'); ?> &gt;</a></span>
		<span class="back-xs"><a href="<?php echo $this->getUrl('customer/account/index/');?>" class="underline"><?php echo $_helper->__('back'); ?> &gt;</a></span>
	</h1>
</div>

	<form method="post" id="new-rma" action="<?php echo $this->getUrl('*/*/saveRma') ?>">
		<input type="hidden" name="po_id" value="<?php echo $this->getPo()->getId(); ?>">
		<?php echo $this->getChildHtml("zolagorma.new.step1");?>
		<?php echo $this->getChildHtml("zolagorma.new.step2");?>
		<?php echo $this->getChildHtml("zolagorma.new.step3");?>
	</form>
<?php endif; ?>