<?php /** @var Zolago_Rma_Block_Pdf $this */ ?>
<?php $_helper = Mage::helper("zolagorma"); ?>
<?php $_rma = $this->rma;?>
<html>
<meta charset="utf-8">
<head>
	<style>
		body {
			font-family: Arial, Helvetica, sans-serif;
			margin: 0;
			padding: 0;
		}
		#logo {
			text-align: center;
			margin-bottom: 20px;
		}
		#rmaInfo {
			border: 1px solid #cccccc;
		}
		.rmaRow,.rmaProducts {
			padding: 10px;
		}
		.rmaRow {
			border-top: 1px solid #cccccc;
		}
		.rmaRow:first-child {
			border-top: none;
		}
		.rmaTitle {
			font-weight: bold;
			margin-bottom: 3px;
		}
		.rmaContent {
			padding-left: 3px;
		}
		#rmaVendor .rmaContent {
			text-transform: uppercase;
		}
		#rmaProductsTable {
			border: 1px solid #cccccc;
			border-collapse: collapse;
			width: 100%;
		}
		#rmaProductsTable td {
			border: 1px solid #cccccc;
			border-collapse: collapse;
			padding: 5px 10px;
		}
		#rmaProductsTable td.img {
			width: 10px;
			padding: 0;
		}
		#rmaProductsTitle {
			margin-top: 20px;
		}
	</style>
</head>
<body>
	<div id="rmaContainer">
	    <?php if ($this->getLogo()) : ?>
		<div id="logo">
			<img src="<?php echo $this->getLogo(); ?>" />
		</div>
		<?php endif; ?>
		<div id="rmaInfo">
			<div id="rmaDelivery" class="rmaRow">
				<div class="rmaTitle">
					<?php echo $_helper->__("Package delivery address"); ?>:
				</div>
				<div class="rmaContent">
					<?php echo $this->getDeliveryAddress(); ?>
				</div>
			</div>
			<div id="rmaNumber" class="rmaRow">
				<div class="rmaTitle">
					<?php echo $_helper->__("RMA reference number"); ?>:
				</div>
				<div class="rmaContent">
					<?php echo $_rma->getIncrementId(); ?>
				</div>
			</div>
			<div id="rmaOrderNumber" class="rmaRow">
				<div class="rmaTitle">
					<?php echo $_helper->__("RMA order number"); ?>:
				</div>
				<div class="rmaContent">
					<?php echo $_rma->getPo()->getIncrementId(); ?>
				</div>
			</div>
			<div id="rmaDate" class="rmaRow">
				<div class="rmaTitle">
					<?php echo $_helper->__("RMA creation date"); ?>:
				</div>
				<div class="rmaContent">
					<?php echo Mage::helper("core")->formatDate($_rma->getCreatedAt()); ?>
				</div>
			</div>
			<div id="rmaPickupDate" class="rmaRow">
				<div class="rmaTitle">
					<?php echo $_helper->__("Date and time of courier package pickup"); ?>:
				</div>
				<div class="rmaContent">
					<?php echo $this->weekdays[date('w',strtotime($_rma->getCarrierDate()))];?>,
					<?php echo Mage::helper("core")->formatDate($_rma->getCarrierDate(), "short");?><br />
					<?php echo $_helper->__(
						"between %s and %s",
						$_rma->getCarrierTimeFrom() ? $_rma->getCarrierTimeFrom() : $_helper->__("N/A"),
						$_rma->getCarrierTimeTo() ? $_rma->getCarrierTimeTo() : $_helper->__("N/A"));
					?>
				</div>
			</div>
			<div id="rmaPickupAddress" class="rmaRow">
				<div class="rmaTitle">
					<?php echo $_helper->__("Package pickup address"); ?>:
				</div>
				<div class="rmaContent">
					<?php echo $_rma->getShippingAddress()->format("html"); ?>
				</div>
			</div>
			<?php if($_rma->getCommentText()):?>
				<div id="rmaComments" class="rmaRow">
					<div class="tmaTitle">
						<?php echo $this->__("Customer comments"); ?>:
					</div>
					<div class="rmaContent">
						<?php echo $this->escapeHtml($_rma->getCommentText()); ?>
					</div>
				</div>
			<?php endif;?>
		</div>
	</div>
	<div class="rmaProducts rmaTitle" id="rmaProductsTitle">
		<?php echo $_helper->__("Products:"); ?>
	</div>
	<table class="rmaProducts" id="rmaProductsTable">
		<tbody>
		<?php foreach($_rma->getItemsCollection() as $item):?>
			<?php if($item->getPoItem()->getId()): ?>
			<tr>
<!--				<td class="img" rowspan="2">-->
<!--					<img src="--><?php //echo $this->getRmaItemThumb($item);?><!--" alt=""/>-->
<!--				</td>-->
				<td class="desc" style="border-bottom: none;" valign="middle">
					<span><?php echo $this->escapeHtml($item->getName());?></span>
					<?php if($_attributes = $this->getConfigurableAttributesByItem($item)):?>
						<small>
							<?php foreach($_attributes as $value):?>
								<br /><?php echo $this->escapeHtml($value['label']);?>: <?php echo $this->escapeHtml($value['value']);?>
							<?php endforeach;?>
						</small>
					<?php endif;?>
				</td>
			</tr>
			<tr>
				<td class="reason" valign="middle">
					<b><?php echo $_helper->__("Return reason");?>:</b><br />
					<?php echo $this->getItemCondition($item);?>
				</td>
			</tr>
			<?php endif; ?>
		<?php endforeach;?>
		</tbody>
	</table>
</body>
</html>