<?php $_helper = Mage::helper("zolagorma"); ?>
<script type="text/javascript">
    //TRANSLATIONS
    Mall.translate.add("Selected time", "<?php echo $_helper->__('Selected time') ?>");
    Mall.translate.add("For your address is only available time interval", "<?php echo $_helper->__('For your address is only available time interval') ?>");
    Mall.translate.add("between the hours", "<?php echo $_helper->__("between the hours") ?>");
    Mall.translate.add("and", "<?php echo $_helper->__("and") ?>");
    Mall.translate.add("For your address, there are dates from ", "<?php echo $_helper->__("For your address, there are dates from ") ?>");
    Mall.translate.add(" to ", "<?php echo $_helper->__(" to ") ?>");
    Mall.translate.add("Bank account number must contain 26 digits.", "<?php echo $_helper->__("Bank account number must contain 26 digits.") ?>");
    Mall.translate.add("For a given zip code can not be ordered a courier. ZIP Code may be wrong.", "<?php echo $_helper->__("For a given zip code can not be ordered a courier. ZIP Code may be wrong.") ?>");
    // Addressbook transaltion
    Mall.translate.add("no-addresses", "<?php echo $_helper->__("No addresses");?>");
    Mall.translate.add("edit-address", "<?php echo $_helper->__("Edit address");?>");
    Mall.translate.add("add-new-address", "<?php echo $_helper->__("Add new address");?>");
    Mall.translate.add("save", "<?php echo $_helper->__("Save");?>");
    Mall.translate.add("firstname", "<?php echo $_helper->__("Firstname");?>");
    Mall.translate.add("lastname", "<?php echo $_helper->__("Lastname");?>");
    Mall.translate.add("company-name", "<?php echo $_helper->__("Company name");?>");
    Mall.translate.add("optional", "<?php echo $_helper->__("optional");?>");
    Mall.translate.add("nip", "<?php echo $_helper->__("NIP");?>");
    Mall.translate.add("street-and-number", "<?php echo $_helper->__("Street and number");?>");
    Mall.translate.add("add-address", "<?php echo $_helper->__("Add address");?>");
    Mall.translate.add("postcode", "<?php echo $_helper->__("Postcode");?>");
    Mall.translate.add("city", "<?php echo $_helper->__("City");?>");
    Mall.translate.add("phone", "<?php echo $_helper->__("Phone");?>");
    Mall.translate.add("address-cant-be-removed", "<?php echo $_helper->__("Address can't be removed.");?>");
    Mall.translate.add("selected-carrier-address", "<?php echo $_helper->__("Selected carrier address") ?>");
    Mall.translate.add("change-address", "<?php echo $_helper->__("Change address");?>");
    Mall.translate.add("your-additional-addresses", "<?php echo $_helper->__("Your additional addresses");?>");
    Mall.translate.add("roll-up", "<?php echo $_helper->__("Roll up");?>");
    Mall.translate.add("choose-the-date", "<?php echo $_helper->__("Choose the date");?>");
    Mall.translate.add("select-the-time-interval", "<?php echo $_helper->__("Select the time interval");?>");
    Mall.translate.add("address-you-sure?", "<?php echo $_helper->__("Do you really want to remove this address?");?>");
    // Messages
    Mall.translate.add("Invalid zip-code. Zip-code should include 5 numbers in XX-XXX format.", "<?php echo $this->__("Invalid zip-code. Zip-code should include 5 numbers in XX-XXX format."); ?>");
    Mall.translate.add("Telephone number is too short. Number must contain 9 digits, without spacing.", "<?php echo $this->__("Telephone number is too short. Number must contain 9 digits, without spacing."); ?>");
    Mall.translate.add("email", "<?php echo $this->__('Valid email is required.') ?>");
    Mall.translate.add("Password needs to have at least %s characters", "<?php echo $this->__("Password needs to have at least %s characters", Mage::helper("zolagocustomer")->getPasswordMinLength()); ?>");
    Mall.translate.add("Zip code should be entered in the format xx-xxx.", "<?php echo $this->__("Zip code should be entered in the format xx-xxx."); ?>");
    Mall.translate.add("required", "<?php echo $this->__("This is a required field."); ?>");
    Mall.translate.add("email", "<?php echo $this->__("E-mail address is in invalid format or contains invalid characters. Please enter correct address."); ?>");
    Mall.translate.add("Tax number is incorrect. Enter as a string of digits e.g. 1234567890.", "<?php echo $this->__('Tax number is incorrect. Enter as a string of digits e.g. 1234567890.') ?>");
    Mall.translate.add("Enter name.", "<?php echo $this->__('Enter name.') ?>");
    Mall.translate.add("Enter last name.", "<?php echo $this->__('Enter last name.') ?>");
    Mall.translate.add("Enter email address.", "<?php echo $this->__('Enter email address.') ?>");
    Mall.translate.add("Enter street and number.", "<?php echo $this->__('Enter street and number.') ?>");
    Mall.translate.add("Enter company name.", "<?php echo $this->__('Enter company name.') ?>");
    Mall.translate.add("Enter city name.", "<?php echo $this->__('Enter city name.') ?>");
    Mall.translate.add("Zip-code should be entered in the format xx-xxx.", "<?php echo $this->__('Zip-code should be entered in the format xx-xxx.') ?>");
    Mall.translate.add("Phone number we need only to contact concerning orders for example courier delivering the shipment.", "<?php echo $this->__('Phone number we need only to contact concerning orders for example courier delivering the shipment.') ?>");
</script>