<?php /* @var $this Zolago_Rma_Block_View */ ?>
<?php $_helper = Mage::helper("zolagorma"); ?>
<?php $_rma = $this->getRma();?>
<?php
Mage::app()->getLayout()
    ->getMessagesBlock()
    ->setMessages(Mage::getSingleton('udqa/session')->getMessages(true));


?>
<div class="messages-box">
    <?php echo $this->getMessagesBlock()->getGroupedHtml(); ?>
</div>

<div class="page-title box-wrapper">
	<h1>
		<span class="hidden-md hidden-lg"><?php echo $_helper->__("Returns and complaints"); ?></span>
		<span class="visible-md visible-lg"><?php echo $_helper->__("RMA no. %s", $_rma->getIncrementId()); ?></span>
		<span class="back-sm"><a href="<?php echo $this->getUrl('customer/account/index/');?>" class="underline"><?php echo $_helper->__('back: my account'); ?> &gt;</a></span>
		<span class="back-xs"><a href="<?php echo $this->getUrl('customer/account/index/');?>" class="underline"><?php echo $_helper->__('back'); ?> &gt;</a></span>
	</h1>
</div>

<div class="background-wrapper box-wrapper rma-po-list <?php echo $this->getIsClaim($_rma) ? "rma-claim" : "rma-return";?>">
	<div class="rma-section rma-caption">
		<span class="bold"><?php echo $_helper->__("RMA Date"); ?></span>: <?php echo Mage::helper("core")->formatDate($_rma->getCreatedAt());?><br/>
		<span class="bold"><?php echo $_helper->__("Vendor"); ?></span>: <?php echo $this->escapeHtml($_rma->getVendor()->getVendorName());?>
	</div>
	<?php if($this->isPendingPickup($_rma) && $_message=$this->getMonitMessage($_rma)):?>
	<div class="rma-monit rma-section">
		<?php echo $_message?>
		<?php if($_pdfUrl=$this->getPdfUrl($_rma)):?>
			<a href="<?php echo $_pdfUrl;?>" class="button button-primary download-doc"><?php echo $_helper->__("Download a document"); ?> [DEV]</a>
		<?php endif;?>
	</div>
	<?php endif;?>
	<div class="row">
		<div class="col-sm-4">
			<div class="rma-status rma-section">
				<p>
					<i class="glyphicon glyphicon-info-sign"></i>
					<span class="uppercase"><?php echo $_helper->__("Progress status"); ?></span>
				</p>
					<div>
						<?php echo $this->escapeHtml($_rma->getRmaStatusName());?>
					</div>
			</div>
			<?php if($this->isPendingPickup($_rma)):?>
				<div class="rma-section rma-content">
					<p>
						<i class="glyphicon glyphicon-time"></i>
						<span class="uppercase"><?php echo $_helper->__("Carrier date"); ?></span>
					</p>
					<div>
						<?php echo $this->getDayOfWeek($_rma);?> <?php echo Mage::helper("core")->formatDate($_rma->getCarrierDate(), "short");?><br/>
						<?php echo $_helper->__(
							"between %s and %s", 
							$_rma->getCarrierTimeFrom() ? $_rma->getCarrierTimeFrom() : $_helper->__("N/A"), 
							$_rma->getCarrierTimeTo() ? $_rma->getCarrierTimeTo() : $_helper->__("N/A")); 
						?>
					</div>
				</div>
				<?php if($_address=$_rma->getShippingAddress()):?>
					<div class="rma-section rma-content">
						<p>
							<i class="glyphicon glyphicon-envelope"></i>
							<span class="uppercase"><?php echo $_helper->__("Your address"); ?></span>
						</p>
						<div>
							<?php echo $_address->format("html");?>
						</div>
					</div>
				<?php endif;?>
			<?php endif;?>
			<div class="rma-section rma-content">
				<p>
					<i class="glyphicon glyphicon-list-alt"></i>
					<span class="uppercase"><?php echo $_helper->__("RMA Content"); ?></span>
				</p>
				<table>
					<tbody>
						<?php foreach($_rma->getItemsCollection() as $item):?>
						<tr>
							<td class="img">
								<img src="<?php echo $this->getRmaItemThumb($item);?>" alt=""/>
							</td>
							<td class="desc">
								<p>
									<span><?php echo $this->escapeHtml($item->getName());?></span>
									<?php if($_attributes = $this->getConfigurableAttributesByItem($item)):?>
										<br/>
										<small>
										<?php foreach($_attributes as $value):?>
											<?php echo $this->escapeHtml($value['label']);?>: <?php echo $this->escapeHtml($value['value']);?>
										<?php endforeach;?>
										</small>
									<?php endif;?>
								</p>
								<div>
									<span class="bold"><?php echo $_helper->__("Return reason");?>:</span></br>
									<?php echo $this->getItemCondition($item);?>
								</div>
							</td>
						</tr>
						<?php endforeach;?>
					</tbody>
				</table>
				<?php if($_rma->getCommentText()):?>
				<div class="comment-text">
					<?php echo $this->escapeHtml($_rma->getCommentText());?>
				</div>
				<?php endif;?>
			</div>
		</div>
		<div class="col-sm-8">
            <div class="rma-connect-vendor">
                <div class="rma-connect-vendor-pannel rma-section">
                    <p>
					<span class="caption">
                        <span class="glyphicon glyphicon-comment"></span>
						<span class="uppercase"><?php echo $_helper->__("Contact with vendor"); ?></span>
					</span>
                        <i class="fa fa-chevron-down"></i>
                    </p>
                </div>
                <div class="rma-connect-vendor-form rma-section">
                    <?php echo $this->getChildHtml("zolagorma_vendor_question"); ?>
                </div>
            </div>

			<div class="rma-section rma-comments">
				<p>
					<i class="glyphicon glyphicon-align-left"></i>
					<span class="uppercase"><?php echo $_helper->__("History"); ?></span>
				</p>
				<?php $_comments = $this->getCommentCollection($_rma)?>
				<?php if($_comments->getSize()):?>
					<table>
						<tbody>
							<?php foreach($_comments as $_comment):?>
							<?php /* @var $_comment Unirgy_Rma_Model_Rma_Comment */ ?>
							<tr>
								<td class="author">
									<?php echo Mage::helper('core')->formatDate($_comment->getCreatedAt(), "short", true);?><br/>
									<?php echo $this->getCommentAuthor($_comment); ?>
								</td>
								<td class="desc">
									<?php echo $this->escapeHtml($_comment->getComment());?>
								</td>
							</tr>
							<?php endforeach;?>
						</tbody>
					</table>
				<?php else:?>
					<p><?php echo $_helper->__("There is no RAM comments"); ?></p>
				<?php endif;?>
			</div> 
			<?php if($this->getIsReturn($_rma)):?>
			<div class="rma-cancel">
				<a href="#"><?php echo $_helper->__("Cancel RMA");?> [DEV]</a>
			</div>
			<?php endif;?>
		</div>
		
	</div>
</div>
<script type="text/javascript">
    jQuery(document).ready(function(){
        fixMessage();
        jQuery(window).resize(fixMessage);

        function fixMessage (){
            if(jQuery(window).innerWidth() <= 754){
                jQuery(".messages-box").addClass("fix");
            } else {
                jQuery(".messages-box").removeClass("fix");
            }
        }
    })
</script>
	