<?php /* @var $this Zolago_Modago_Block_Checkout_Onepage_Logged_Addressbook */ ?>
<?php $formKey = Mage::getSingleton('core/session')->getFormKey(); ?>

<?php echo $this->getStep1Sidebar(); ?>

<div id="content-main" class="col-lg-9 col-md-8 col-sm-12 col-xs-12 col-lg-pull-3 col-md-pull-4 section">
	<section class="main bg-w">
		<header class="title-section">
			<h2>Potwierdź dane do wysyłki</h2>
		</header>


		<form action="<?php echo $this->getSaveUrl();?>" class="form">
			<input type="hidden" name="form_key" value="<?php echo $formKey; ?>">
			<h4>Adres dostawy:</h4>
			<div class="panel panel-default">
				<div class="panel-body">
					
					<div class="hidden" id="selected-address-template">
						<p class="pull-right default_delivery small-no-float">{{default_caption}}</p>
						<dl class="pull-left" >
							<dt>{{firstname}} {{lastname}}</dt>
							<dd>{{street}}</dd>
							<dd>{{postcode}} {{city}}</dd>
							<dd class="separator phone"><?php echo $this->__("Contact phone")?>: <span>{{telephone}}</span></dd>
						</dl>
					</div>
					
					<div class="current-addres clearfix shipping">
						
					</div>
					<!-- PANEL -->
					<div class="panel panel-default ">
						<div class="panel-body">
							<dl class="pull-left small-no-float">
								<dt>Jan Kowalski</dt>
								<dd>ul. Nowakowa 1a/3</dd>
								<dd>03-221 Warszawa</dd>
								<dd class="action separator"><a href="#" class="underline">edytuj</a> <a href="#" class="underline">usuń</a> <a href="#" class="underline">ustaw jako domyślny</a></dd>
							</dl> 
							<button class="btn-select button button-third large">Wybierz</button>
						</div>
					</div>
					<!-- END PANEL -->
					<!-- PANEL -->
					<div class="panel panel-default ">
						<div class="panel-body">
							<dl class="pull-left small-no-float">
								<dt>Fajna Firma Sp. z.o.o.</dt>
								<dt>Nip: 321 321 321</dt>
								<dt>Jan Nowak</dt>
								<dd>ul. Nowakowa 1a/3</dd>
								<dd>03-221 Warszawa</dd>
								<dd class="action separator"><a href="#" class="underline">edytuj</a> <a href="#" class="underline">usuń</a> <a href="#" class="underline">ustaw jako domyślny</a></dd>
							</dl> 
							<button class="btn-select button button-third large">Wybierz</button>
						</div>
					</div>
					<!-- END PANEL -->
					<!-- PANEL -->
					<div class="panel panel-default ">
						<div class="panel-body">
							<dl class="pull-left small-no-float">
								<dt>Jan Kowalski</dt>
								<dd>ul. Nowakowa 1a/3</dd>
								<dd>03-221 Warszawa</dd>
								<dd class="action separator"><a href="#" class="underline">edytuj</a> <a href="#" class="underline">usuń</a> <a href="#" class="underline">ustaw jako domyślny</a></dd>
							</dl> 
							<button class="btn-select button button-third large">Wybierz</button>
						</div>
					</div>
					<!-- END PANEL -->
					<!-- PANEL -->
					<div class="panel panel-default current  ">
						<div class="panel-body">

							<dl class="pull-left small-no-float">
								<dt>Jan Kowalski</dt>
								<dd>ul. Nowakowa 1a/3</dd>
								<dd>03-221 Warszawa</dd>
								<dd class="action separator"><a href="#" class="underline">edytuj</a> <a href="#" class="underline">usuń</a></dd>
							</dl> 
							<p class="staining_delivery_address">Wybrany adres dostawy</p>
						</div>
					</div>
					<!-- END PANEL -->
					<!-- PANEL -->
					<div class="panel panel-default  ">
						<div class="panel-body">
							<h4><strong>INNY ADRES DOSTAWY:</strong></h4>
							<div class="form-group clearfix">
								<div class="row">
									<label class="col-sm-3" for="for_first_name">Imię i Nazwisko</label>
									<div class="col-sm-9">
										<div class="row">
											<div class="col-lg-6 col-xs-6 form-group "><input type="text" class="form-control firstName hint" id="for_first_name" title="" data-original-title="Wprowadź imię"></div>
											<div class="col-lg-6 col-xs-6 form-group "><input type="text" class="form-control lastName hint" id="for_last_name" title="" data-original-title="Wprowadź nazwisko"></div>
										</div>

									</div>        
								</div>
							</div>

							<div class="form-group clearfix border-top">
								<div class="row">
									<label class="col-sm-3 double-line" for="firm_name">Nazwa firmy<br>(opcjonalnie)</label>
									<div class="col-sm-9">

										<input type="text" class="form-control firm hint" id="firm_name" data-original-title="" title="">

									</div>
								</div>
							</div>

							<div class="form-group clearfix border-top">
								<div class="row">
									<label class="col-sm-3 double-line" for="nip">NIP<br>(opcjonalnie)</label>
									<div class="col-sm-9">

										<input type="tel" class="form-control nip hint" id="nip">

									</div>
								</div>
							</div>

							<div class="form-group clearfix border-top">
								<div class="row">
									<label class="col-sm-3" for="street">Ulica i Numer</label>
									<div class="col-sm-9">

										<input type="text" class="form-control street hint" id="street" data-original-title="" title="">

									</div>
								</div>
							</div>

							<div class="form-group clearfix border-top">
								<div class="row">
									<label class="col-sm-3" for="zip_code">Kod pocztowy</label>
									<div class="col-sm-9">

										<input type="tel" class="form-control zipcode hint" id="zip_code" maxlength="6">

									</div>
								</div>
							</div>

							<div class="form-group clearfix border-top">
								<div class="row">
									<label class="col-sm-3" for="city">Miejscowość</label>
									<div class="col-sm-9">

										<input type="text" class="form-control city hint" id="city" data-original-title="" title="">

									</div>
								</div>
							</div>

							<div class="form-group clearfix border-top">
								<div class="row">
									<label class="col-sm-3" for="phone_number">Numer telefonu</label>
									<div class="col-sm-9">

										<input type="text" class="form-control phone hint" id="phone_number" title="" data-original-title="Numer telefonu potrzebujemy tylko do kontaktu dotyczącego zamówienia np. dla kuriera dostarczającego przesyłkę.">

									</div>
								</div>
							</div>
							<div class="form-group clearfix"><button class="button button-third large pull-right">Wybierz</button></div>

						</div>
					</div>
					<!-- END PANEL -->
				</div>
				<div class="panel-footer clearfix"><a href="#" class="underline pull-right change_address">zmień adres</a></div>
			</div>
			<div id="invoice" class="form-group form-checkbox small">
				<input type="checkbox" name="rodzaj" id="invoice_this" class="css-checkbox ">
				<label for="invoice_this" class="css-label invoice_this">Chcę otrzymać fakturę VAT </label>
			</div>



			<div id="block_invoice">
				<h4>Dane do faktury:</h4>
				<div class="panel panel-default">
					<div class="panel-body">
						<div class="current-addres clearfix">
							<p class="pull-right default_delivery small-no-float">DOMYŚLNY DANE DO FAKTURY</p>
							<dl class="pull-left small-no-float">
								<dt>Jan Kowalski</dt>
								<dd>ul. Nowakowa 1a/3</dd>
								<dd>03-221 Warszawa</dd>
								<dd class="separator phone">Telefon kontaktowy: <span>+48 58 666 66 66</span></dd>
							</dl>

						</div>
						<!-- PANEL -->
						<div class="panel panel-default">
							<div class="panel-body">
								<dl class="pull-left small-no-float">
									<dt>Jan Kowalski</dt>
									<dd>ul. Nowakowa 1a/3</dd>
									<dd>03-221 Warszawa</dd>
									<dd class="action separator"><a href="#" class="underline">edytuj</a> <a href="#" class="underline">usuń</a> <a href="#" class="underline">ustaw jako domyślny</a></dd>
								</dl> 
								<button class="btn-select button button-third large">Wybierz</button>
							</div>
						</div>
						<!-- END PANEL -->
						<!-- PANEL -->
						<div class="panel panel-default">
							<div class="panel-body">
								<dl class="pull-left small-no-float">
									<dt>Fajna Firma Sp. z.o.o.</dt>
									<dt>Nip: 321 321 321</dt>
									<dt>Jan Nowak</dt>
									<dd>ul. Nowakowa 1a/3</dd>
									<dd>03-221 Warszawa</dd>
									<dd class="action separator"><a href="#" class="underline">edytuj</a> <a href="#" class="underline">usuń</a> <a href="#" class="underline">ustaw jako domyślny</a></dd>
								</dl> 
								<button class="btn-select button button-third large">Wybierz</button>
							</div>
						</div>
						<!-- END PANEL -->
						<!-- PANEL -->
						<div class="panel panel-default">
							<div class="panel-body">
								<dl class="pull-left small-no-float">
									<dt>Jan Kowalski</dt>
									<dd>ul. Nowakowa 1a/3</dd>
									<dd>03-221 Warszawa</dd>
									<dd class="action separator"><a href="#" class="underline">edytuj</a> <a href="#" class="underline">usuń</a> <a href="#" class="underline">ustaw jako domyślny</a></dd>
								</dl> 
								<button class="btn-select button button-third large">Wybierz</button>
							</div>
						</div>
						<!-- END PANEL -->
						<!-- PANEL -->
						<div class="panel panel-default current">
							<div class="panel-body"> 
								<dl class="pull-left small-no-float">
									<dt>Jan Kowalski</dt>
									<dd>ul. Nowakowa 1a/3</dd>
									<dd>03-221 Warszawa</dd>
									<dd class="action separator"><a href="#" class="underline">edytuj</a> <a href="#" class="underline">usuń</a></dd>
								</dl> 
								<p class="staining_delivery_address">Wybrane DANE DO FAKTURY</p>
							</div>
						</div>
						<!-- END PANEL -->
						<!-- PANEL -->
						<div class="panel panel-default">
							<div class="panel-body">
								<h4><strong>INNY ADRES DO FAKTURY:</strong></h4>
								<div class="form-group clearfix">
									<div class="row">
										<label class="col-sm-3" for="invoice_data_for_first_name">Imię i Nazwisko</label>
										<div class="col-sm-9">
											<div class="row">

												<div class="col-lg-6 col-xs-6 form-group "><input type="text" class="form-control firstName hint" id="invoice_data_for_first_name" data-original-title="" title=""></div>
												<div class="col-lg-6 col-xs-6 form-group "><input type="text" class="form-control lastName hint" id="invoice_data_for_last_name" data-original-title="" title=""></div>

											</div>

										</div>        
									</div>
								</div>

								<div class="form-group clearfix border-top">
									<div class="row">
										<label class="col-sm-3 double-line" for="firm_name">Nazwa firmy<br>(opcjonalnie)</label>
										<div class="col-sm-9">

											<input type="text" class="form-control firm hint" id="firm_name" data-original-title="" title="">

										</div>
									</div>
								</div>

								<div class="form-group clearfix border-top">
									<div class="row">
										<label class="col-sm-3 double-line" for="nip">NIP<br>(opcjonalnie)</label>
										<div class="col-sm-9">

											<input type="tel" class="form-control nip hint" id="nip">

										</div>
									</div>
								</div>

								<div class="form-group clearfix border-top">
									<div class="row">
										<label class="col-sm-3" for="street">Ulica i Numer</label>
										<div class="col-sm-9">

											<input type="text" class="form-control street hint" id="street" data-original-title="" title="">

										</div>
									</div>
								</div>

								<div class="form-group clearfix border-top">
									<div class="row">
										<label class="col-sm-3" for="vat_zip_code">Kod pocztowy</label>
										<div class="col-sm-9">

											<input type="tel" class="form-control zipcode hint" id="vat_zip_code" maxlength="6">

										</div>
									</div>
								</div>

								<div class="form-group clearfix border-top">
									<div class="row">
										<label class="col-sm-3" for="city">Miejscowość</label>
										<div class="col-sm-9">

											<input type="text" class="form-control city hint" id="city" data-original-title="" title="">

										</div>
									</div>
								</div>

								<div class="form-group clearfix border-top">
									<div class="row">
										<label class="col-sm-3" for="phone_number">Numer telefonu</label>
										<div class="col-sm-9">

											<input type="text" class="form-control phone hint" id="phone_number" title="" data-original-title="Numer telefonu potrzebujemy tylko do kontaktu dotyczącego zamówienia np. dla kuriera dostarczającego przesyłkę">

										</div>
									</div>
								</div>
								<div class="form-group clearfix"><button class="button button-third large pull-right">Wybierz</button></div>

							</div>
						</div>
						<!-- END PANEL -->
					</div>
					<div class="panel-footer clearfix"><a href="#" class="underline pull-right change_address">zmień adres</a></div>
				</div>
			</div>
			<div class="row">
				<div class="col-sm-6">
					<a id="back" href="<?php echo $this->getPreviousStepUrl(); ?>" class="button button-third large pull-left"><?php echo $this->__("Back"); ?></a>
				</div>
				<div class="col-sm-6">
					<button class="button button-primary large link pull-right"><?php echo $this->__("Next"); ?></button>
				</div>
			</div>

		</form>  
	</section>

</div>     
