<?php
/**
 * Author: Paweł Chyl <pawel.chyl@orba.pl>
 * Date: 25.04.14
 */

?>

<section id="bottom" class="bg-w">
    <div class="container-fluid">
        <div class="col-sm-12">

            <div class="recently-viewed">
                <h3 class="title-section">ostatnio oglądane:</h3>

                <div id="rwd-recently-viewed" class="rwdCarousel">
                    <div class="rwd-carousel rwd-theme">
                        <div class="item">
                            <a href="#" class="simple">

                                <div class="box_listing_product">
                                    <figure class="img_product">
                                        <img src="skin/frontend/modago/default/images/last-seen-2.jpg " alt="" />
                                    </figure>
                                    <div class="name_product hidden-xs">Zara krótki płaszcz z guzikami</div>
                                </div>

                            </a>
                        </div>
                        <div class="item ">
                            <a href="#" class="simple">

                                <div class="box_listing_product">
                                    <figure class="img_product">
                                        <img src="skin/frontend/modago/default/images/last-seen-2.jpg " alt="" />
                                    </figure>
                                    <div class="name_product hidden-xs">Zara krótki płaszcz z guzikami</div>
                                </div>

                            </a>
                        </div>
                        <div class="item">
                            <a href="#" class="simple">

                                <div class="box_listing_product">
                                    <figure class="img_product">
                                        <img src="skin/frontend/modago/default/images/last-seen-2.jpg " alt="" />
                                    </figure>
                                    <div class="name_product hidden-xs">Zara krótki płaszcz z guzikami</div>
                                </div>

                            </a>
                        </div>
                        <div class="item">
                            <a href="#" class="simple">

                                <div class="box_listing_product">
                                    <figure class="img_product">
                                        <img src="skin/frontend/modago/default/images/last-seen-2.jpg " alt="" />
                                    </figure>
                                    <div class="name_product hidden-xs">Zara krótki płaszcz z guzikami</div>
                                </div>

                            </a>
                        </div>
                        <div class="item">
                            <a href="#" class="simple">

                                <div class="box_listing_product">
                                    <figure class="img_product">
                                        <img src="skin/frontend/modago/default/images/last-seen-2.jpg " alt="" />
                                    </figure>
                                    <div class="name_product hidden-xs">Zara krótki płaszcz z guzikami</div>
                                </div>

                            </a>
                        </div>
                        <div class="item">
                            <a href="#" class="simple">

                                <div class="box_listing_product">
                                    <figure class="img_product">
                                        <img src="skin/frontend/modago/default/images/last-seen-2.jpg " alt="" />
                                    </figure>
                                    <div class="name_product hidden-xs">Zara krótki płaszcz z guzikami</div>
                                </div>

                            </a>
                        </div>
                        <div class="item">
                            <a href="#" class="simple">

                                <div class="box_listing_product">
                                    <figure class="img_product">
                                        <img src="skin/frontend/modago/default/images/last-seen-2.jpg " alt="" />
                                    </figure>
                                    <div class="name_product hidden-xs">Zara krótki płaszcz z guzikami</div>
                                </div>

                            </a>
                        </div>
                        <div class="item">
                            <a href="#" class="simple">

                                <div class="box_listing_product">
                                    <figure class="img_product">
                                        <img src="skin/frontend/modago/default/images/last-seen-2.jpg " alt="" />
                                    </figure>
                                    <div class="name_product hidden-xs">Zara krótki płaszcz z guzikami</div>
                                </div>

                            </a>
                        </div>
                    </div>

                </div>
            </div>

        </div>
    </div>
</section>
