<?php
/**
 * Author: Paweł Chyl <pawel.chyl@orba.pl>
 * Date: 25.04.14
 */

?>

<!--last seen-->

<div class="white-wrapper ">
    <div class="container last-seen">
        <h3><?php echo $this->__("last seen"); ?>:</h3>

        <div class="jcarousel-wrapper listComics">
            <div class="canvas-left"></div>
            <div class="jcarousel last-seen1">
                <ul class="last-seen-list">
                    <li class="col-sm-2">
                        <a href="#" class="productItem-wrapper">
                            <img src="<?php echo $this->getSkinUrl('images/last-seen-1.jpg'); ?>" alt="..." class="border1px-rd2-img-gray">
                            <span>ZARA krótki płaszcz z guzikami</span>
                        </a>
                    </li>
                    <li class="col-sm-2">
                        <a href="#" class="productItem-wrapper">
                            <img src="<?php echo $this->getSkinUrl('images/last-seen-2.jpg'); ?>" alt="..." class="border1px-rd2-img-gray">
                            <span>Zara krótki płaszcz z guzikami</span>
                        </a>
                    </li>
                    <li class="col-sm-2">
                        <a href="#" class="productItem-wrapper">
                            <img src="<?php echo $this->getSkinUrl('images/last-seen-1.jpg'); ?>" alt="..." class="border1px-rd2-img-gray">
                            <span>Zara krótki płaszcz z guzikami</span>
                        </a>
                    </li>
                    <li class="col-sm-2">
                        <a href="#" class="productItem-wrapper">
                            <img src="<?php echo $this->getSkinUrl('images/last-seen-2.jpg'); ?>" alt="..." class="border1px-rd2-img-gray">
                            <span>Zara krótki płaszcz z guzikami</span>
                        </a>
                    </li>
                    <li class="col-sm-2">
                        <a href="#" class="productItem-wrapper">
                            <img src="<?php echo $this->getSkinUrl('images/last-seen-1.jpg'); ?>" alt="..." class="border1px-rd2-img-gray">
                            <span>Zara krótki płaszcz z guzikami</span>
                        </a>
                    </li>
                    <li class="col-sm-2">
                        <a href="#" class="productItem-wrapper">
                            <img src="<?php echo $this->getSkinUrl('images/last-seen-2.jpg'); ?>" alt="..." class="border1px-rd2-img-gray">
                            <span>Zara krótki płaszcz z guzikami</span>
                        </a>
                    </li>
                    <li class="col-sm-2">
                        <a href="#" class="productItem-wrapper">
                            <img src="<?php echo $this->getSkinUrl('images/last-seen-1.jpg'); ?>" alt="..." class="border1px-rd2-img-gray">
                            <span>Zara krótki płaszcz z guzikami</span>
                        </a>
                    </li>
                    <li class="col-sm-2">
                        <a href="#" class="productItem-wrapper">
                            <img src="<?php echo $this->getSkinUrl('images/last-seen-2.jpg'); ?>" alt="..." class="border1px-rd2-img-gray">
                            <span>Zara krótki płaszcz z guzikami</span>
                        </a>
                    </li>
                    <li class="col-sm-2">
                        <a href="#" class="productItem-wrapper">
                            <img src="<?php echo $this->getSkinUrl('images/last-seen-1.jpg'); ?>" alt="..." class="border1px-rd2-img-gray">
                            <span>Zara krótki płaszcz z guzikami</span>
                        </a>
                    </li>
                    <li class="col-sm-2">
                        <a href="#" class="productItem-wrapper">
                            <img src="<?php echo $this->getSkinUrl('images/last-seen-2.jpg'); ?>" alt="..." class="border1px-rd2-img-gray">
                            <span>Zara krótki płaszcz z guzikami</span>
                        </a>
                    </li>
                    <li class="col-sm-2">
                        <a href="#" class="productItem-wrapper">
                            <img src="<?php echo $this->getSkinUrl('images/last-seen-1.jpg'); ?>" alt="..." class="border1px-rd2-img-gray">
                            <span>Zara krótki płaszcz z guzikami</span>
                        </a>
                    </li>
                    <li class="col-sm-2">
                        <a href="#" class="productItem-wrapper">
                            <img src="<?php echo $this->getSkinUrl('images/last-seen-2.jpg'); ?>" alt="..." class="border1px-rd2-img-gray">
                            <span>Zara krótki płaszcz z guzikami</span>
                        </a>
                    </li>
                </ul>
            </div>

            <a href="#" class="jcarousel-control-prev carousel-small-ctr-lt"></a>
            <a href="#" class="jcarousel-control-next carousel-small-ctr-gt"></a>

            <div class="canvas-right"></div>
        </div>

    </div>
</div>
