<?php
/**
 * Author: Paweł Chyl <pawel.chyl@orba.pl>
 * Date: 25.04.14
 */

?>

<section id="bottom" class="bg-w recently-viewed-cls" style="display: none;">
    <div class="container-fluid">
        <div class="col-sm-12">

            <div class="recently-viewed">
                <h3 class="title-section">ostatnio oglądane:</h3>

                <div id="rwd-recently-viewed" class="rwdCarousel">
                    <div class="rwd-carousel rwd-theme">

                    </div>

                </div>
            </div>

        </div>
    </div>
</section>
