<?php
/** @var Zolago_Modago_Block_Dropshipmicrositepro_Vendor_Menu $this */

$categories = $this->getMainVendorCategoriesMobile();
?>

<?php if (count($categories) > 0) : ?>
    <?php foreach ($categories as $cat) : ?>
        <?php if($cat["solr_product_count"] > 0): ?>
            <li>
                <a href="<?php echo (isset($cat['url'])) ? $cat['url'] : '#'; ?>" <?php echo (isset($cat['has_dropdown']) && $cat['has_dropdown']) ? '' : 'class="clickable"' ?>>
                    <?php echo $this->escapeHtml($cat['name']); ?> (<?php echo $cat["solr_product_count"]; //TODO ONLY FOR TEST ?>)
                    <?php echo (isset($cat['has_dropdown']) && $cat['has_dropdown']) ? '<i class="fa fa-chevron-down"></i>'
                        : '<i class="fa fa-chevron-right"></i>'; ?>
                </a>
                <?php if (isset($cat['has_dropdown']) && $cat['has_dropdown'] && ($cat["solr_product_count"] > 0)) : ?>
                    <ul>
                        <?php foreach ($cat['has_dropdown'] as $child) : ?>
                            <?php if ($child["solr_product_count"] > 0): ?>
                                <li>
                                    <a href="<?php echo $child['url']; ?>" class="clickable">
                                        <?php echo $this->escapeHtml($child['name']); ?>
                                        (<?php echo $child["solr_product_count"]; //TODO ONLY FOR TEST ?>)
                                    </a>
                                </li>
                            <?php endif; ?>
                        <?php endforeach; ?>
                    </ul>
                <?php endif; ?>
            </li>
        <?php endif; ?>
    <?php endforeach; ?>
<?php endif; ?>