<?php
/**
 * User: Andrzej Spólnicki
 */
$vendor = Mage::helper('umicrosite')->getCurrentVendor();
$baseUrl = Mage::helper("zolagodropshipmicrosite")->getBaseUrl();
$messagesBlock = $this->getMessagesBlock()->getGroupedHtml();
?>
<?php
$topBottomHeaderDesktopModel = Mage::getModel('cms/block')->load('top-bottom-header-desktop-v-' . $vendor['vendor_id']);
$topBottomHeaderMobileModel = Mage::getModel('cms/block')->load('top-bottom-header-mobile-v-' . $vendor['vendor_id']);
?>

<?php if ($topBottomHeaderDesktopModel->getId() && $topBottomHeaderDesktopModel->getIsActive() == 1): ?>
    <div class="top_bottom  bg-w clearfix hidden-xs">
        <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('top-bottom-header-desktop-v-' . $vendor['vendor_id'])->toHtml(); ?>
    </div>
<?php endif; ?>

<?php if(!empty($messagesBlock)): ?>
<div class="top_bottom clearfix hidden-xs">
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12" style="">
                <?php echo $messagesBlock; ?>
            </div>
        </div>
    </div>
</div>
<?php endif; ?>

<?php if ($topBottomHeaderMobileModel->getId() && $topBottomHeaderMobileModel->getIsActive() == 1): ?>
<div class="top_bottom  bg-w visible-xs clearfix">
    <!--mobile part-->
    <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('top-bottom-header-mobile-v-' . $vendor['vendor_id'])->toHtml(); ?>
</div>
<?php endif; ?>

<?php if(!empty($messagesBlock)): ?>
<div class="top_bottom  visible-xs clearfix">
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-12" style="">
                    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
                </div>
            </div>
        </div>
</div>
<?php endif; ?>

    <div class="top_bottom  bg-w visible-xs clearfix">
        <div id="shop_navigation" class="col-sm-12">
            <ul id="shop_nav_mobile" class="navigation visible-xs" role="navigation">

                <?php echo $this->getChildHtml('vendor.menu.mobile'); ?>

                <!--            vendor.info.mobile-->
                <?php echo $this->getChildHtml('vendor.info.mobile'); ?>
                <!--            vendor.info.mobile end-->

                <!-- question form mobile-->
                <li><a href="#"><?php echo $this->__("Submit a question to seller"); ?><i
                            class="fa fa-chevron-down"></i></a>
                    <ul>
                        <li style="height: inherit; padding: 8px 20px 8px 10px;">
                            <div>
                                <?php echo $this->getChildHtml('vendor.question.mobile'); ?>
                            </div>
                        </li>
                    </ul>
                </li>
                <!-- question form mobile end-->

                <!-- back to main gallery -->
                <li><a href="<?php echo $baseUrl; ?>" class="clickable"><?php echo $this->__("Back to main gallery"); ?></a>

                </li>
                <!-- back to main gallery -->
            </ul>
        </div>

</div>
<!--mobile part end-->

<script>
    <?php /* Messges are twice time **/ ?>
    jQuery(document).ready(function () {
        jQuery('ul.messages').first().remove();
    });
</script>