<?php
//$_deliveryreturnInfo = $this->getChild("product.vendor.deliveryreturn");

$vendor = Mage::helper('umicrosite')->getCurrentVendor();
$session = Mage::getSingleton('customer/session');
/* @var $session Mage_Customer_Model_Session */
$baseUrl = Mage::helper("zolagodropshipmicrosite")->getBaseUrl();
?>

<?php //echo get_class($this); ?>

<div class="container-fluid">
    <div class="action-box-bundle clearfix" style="margin-bottom: 20px;">
        <div class="row" style="margin-bottom: 15px;">
            <div class="col-sm-6 col-md-4 col-lg-3" style="text-align: center;">
                <button class="btn button button-primary" style="margin-top: 15px;" data-toggle="modal"
                        data-target="#seller_description"><?php echo $this->__("Seller's info"); ?></button>
            </div>
            <div class="col-sm-6 col-md-4 col-lg-3" style="text-align: center;">
                <button class="btn button button-primary" style="margin-top: 15px;" data-toggle="modal"
                        data-target="#terms_delivery"><?php echo $this->__("RMA rules"); ?></button>
            </div>

            <div class="col-sm-6 col-md-4 col-lg-3" style="text-align: center;">
                <button class="btn button button-primary" style="margin-top: 15px;" data-toggle="modal"
                        data-target="#ask_question"><?php echo $this->__("Submit a question to seller"); ?></button>
            </div>
            <div class="col-sm-6 col-md-4 col-md-offset-4 col-lg-3 col-lg-offset-0" style="text-align: center;">
                <a href="<?php echo $baseUrl; ?>" class="btn button button-primary"
                   style="margin-top: 15px;"><?php echo $this->__("Back to main gallery"); ?></a>
            </div>
        </div>
    </div>
</div>

<!--SHOP INFO-->
<div class="modal fade bs-example-modal-lg" id="seller_description" tabindex="-1" role="dialog"
     aria-labelledby="myLargeModalLabel" aria-hidden="true" style="z-index: 1050">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"></button>
                <h2 class="title_section"><?php echo $this->__("SHOP INFO"); ?></h2>
            </div>

            <div class="modal-body" style="color: #000000;">
                <?php if ($this->getVendorInfoHtml()): ?>
                    <?php echo $this->getVendorInfoHtml(); ?>
                <?php else: ?>
                    <dd>
                        <img src="<?php echo $this->getLogoUrl(); ?>"
                             alt="<?php echo $this->escapeHtml($this->getVendorName()); ?>"><br/>
                        <strong><?php echo $this->__("Seller"); ?>:</strong> <?php echo $this->getVendorName(); ?>
                    </dd>
                <?php endif; ?>
            </div>
        </div>
    </div>
</div>
<!--SHOP INFO end-->

<!--DELIVERY & RETURNS-->
<div class="modal fade bs-example-modal-lg" id="terms_delivery" tabindex="-1" role="dialog"
     aria-labelledby="myLargeModalLabel" aria-hidden="true" style="z-index: 1050">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"></button>
                <h2 class="title_section"><?php echo $this->__("DELIVERY & RETURNS"); ?></h2>
            </div>
            <div class="modal-body" style="color: #000000;">
                <?php echo $this->getVendorDeliveryHtml(); ?>
            </div>
        </div>
    </div>
</div>
<!--DELIVERY & RETURNS end-->

<!--ASK QUESTION-->
<?php echo $this->getChildHtml('vendor.question.desktop'); ?>
<!--ASK QUESTION END-->