<?php /* @var $this Zolago_DropshipMicrositePro_Block_Vendor_Logo */ ?>

<?php $vendorLogo = $this->getLogo(); ?>
<div class="vendor-top-bottom-header-label">
    <a href="<?php echo $this->getVendorUrl(); ?>"><?php echo $this->getVendorLabel(); ?> </a>
</div>
<div class="vendor-top-bottom-header-logo">
    <a href="<?php echo $this->getVendorUrl(); ?>">
        <img src="<?php if(!empty($vendorLogo)) { echo $vendorLogo; } ?>" alt="<?php echo $this->getVendorName(); ?>"/>
    </a>
</div>
