<?php /* @var $this Zolago_DropshipMicrositePro_Block_Vendor_Logo */ ?>
<?php $vendorTypeLabel = $this->getVendorTypeLabel(); ?>
<div style="min-width: 295px;">
<?php if(!empty($vendorTypeLabel)): ?>
<div class="vendor-top-bottom-header-label">
    <?php echo $this->getVendorTypeLabel(); ?>
</div>
<?php endif; ?>
<a href="<?php echo $this->getVendorUrl(); ?>">
    <div class="vendor-top-bottom-header-logo" style="background-image:url(<?php echo $this->getLogoUrl(); ?>)"></div>
</a>
</div>

