<?php /*var_dump($_SERVER); */?>
<?php $q = array(); ?>
<?php $filterQuery = $this->getFilterQuery(); ?>

<div id="active-filters">
    <div class="wrapp-section bg-w">
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-12">
                    <?php if(sizeof($filterQuery) > 0 && $this->isSelectedFacetActive()) : ?>
                        <dl class="clearfix" >
                            <dt><?php echo $this->__('Currently Shopping:') ?></dt>
                            <dd>
                                <?php foreach ($filterQuery as $key => $values): ?>
                                    <?php foreach ($values as $v): ?>
                                        <?php if($key != 'category_id'): ?>
                                            <?php $face_key = substr($key, 0, strrpos($key, '_')) ?>
                                            <?php
                                            $selectedFacetValue = $v;
                                            if($face_key == 'price') {
                                                $selectedFacetValue = $this->formatFacetPrice($v);
                                            }
                                            ?>
                                            <span class="label">
                                                <?php echo $this->__($this->getFacetLabel($key)); ?>:
                                                <span class="value">
                                                    <?php echo $this->facetFormat($selectedFacetValue) ?>
                                                </span>
												<span>
													<a href="<?php echo $this->getRemoveFacesUrl($face_key, $v); ?>"
													   class="fa fa-times active-filter-label"
													   data-input="<?php echo $this->getItemId($face_key, $v)?>"></a>
												</span>
                                            </span>

                                            <?php if($face_key != 'price'): ?>
                                                <input type="hidden" name="fq[<?php echo $face_key ?>]"
                                                       value="<?php echo $v ?>"/>
                                            <?php endif; ?>
                                        <?php endif; ?>
                                    <?php endforeach; ?>
                                <?php endforeach; ?>
                            </dd>
                            <dd class="action hidden-xs">
                                <a data-params='<?php echo $this->getRemoveAllJson(); ?>'
                                   href="<?php echo $this->getRemoveAllUrl() ?>"
                                   class="active-filters-remove button button-third"><?php echo $this->__('Clear all filters') ?></a>
                            </dd>
                        </dl>
                    <?php endif; ?>
                </div>
            </div>
            <div class="row" id="filters-btn">
                <div class="col-sm-12">
                    <dl>
                        <dd class="visible-xs">
                            <div class="view_filter clearfix">
                                <a href="#" class="actionViewFilter button button-primary medium visible-xs"><i
                                        class="fa fa-chevron-right"></i> <?php echo $this->__("Filter Products"); ?></a>
                            </div>
                        </dd>
                        <?php if(sizeof($filterQuery) > 0 && $this->isSelectedFacetActive()) : ?>
                            <dd class="action visible-xs">
                                <a data-params='<?php echo $this->getRemoveAllJson(); ?>'
                                   href="<?php echo $this->getRemoveAllUrl() ?>"
                                   class="active-filters-remove button button-third"><?php echo $this->__('Clear all filters') ?></a>
                            </dd>
                        <?php endif; ?>
                    </dl>
                </div>
            </div>
        </div>
    </div>
</div>