<?php
/** @var $this Zolago_Modago_Block_Solrsearch_Faces */
?>
<?php if ($this->isLayerNavigationActive()):?>
<?php $filterQuery = $this->getFilterQuery(); ?>

    <div class="sidebar solr_search_facets"  id="solr_search_facets">
        <div class=" block-filter" >
			<form name="searchFacets" method="get"
				  autocomplete="false"
				  action="<?php echo $this->helper('solrsearch')->getResultUrl() ?>">
				<input type="hidden" name="q" value="<?php echo $this->getData('querytext') ?>"/>
                <?php if ($this->isShoppingOptionsActive()): ?>
						<?php foreach ($this->getFilterBlocks() as $filterBlock): ?>
                            <?php /** @var $filterBlock Zolago_Modago_Block_Solrsearch_Faces_Category */ ?>
							<!-- Blocks here -->
							<?php echo $filterBlock->toHtml(); ?>
						<?php endforeach; ?>
				<?php endif; ?>
			</form>
        </div>
    </div>
<?php endif;?>
