<?php
/** @var Zolago_Modago_Block_Sales_Order_Process_Merge $this */

/** @var Zolago_Sales_Helper_Data $_helper */
$_helper = Mage::helper("zolagosales");

$request = Mage::app()->getRequest();
$customerAccountPage = false;
if ($request->getRouteName() == "customer" && $request->getControllerName() == "account" && $request->getActionName() == "index") {
	$customerAccountPage = true;
}

if($_helper->getGuestOrders()->count()): ?>
	<div class="order-view order-view-multi<?php if($customerAccountPage): ?> hidden-xs<?php endif; ?>">
		<div class="section " id="content-main">
			<section class="main bg-w ">
				<?php echo $this->getChildHtml('cms'); ?>
				<a class="button button-primary large link pull-right" style="width:auto"
				   href="<?php echo $this->getUrl("sales/order/attach"); ?>">
					<?php echo $_helper->__("Attach my orders"); ?>
				</a>
				<div class="clearfix"></div>
			</section>
		</div>
	</div>
<?php endif;
