<?php $_helper = Mage::helper("zolagorma"); ?>

<!-- selected address tmplate -->
<div class="hidden" id="selected-address-template">
    <p class="pull-right small-no-float"><?php echo $_helper->__("Selected carrier address");?></p>
    <dl class="pull-left" >
        <dt>{{firstname}} {{lastname}}</dt>
        <dd>{{street}}</dd>
        <dd>{{postcode}} {{city}}</dd>
        <dd class="phone"><?php echo $this->__("Contact phone")?>: <span>{{telephone}}</span></dd>
        <dd class="action separator">
            <a href="#" class="underline edit"><?php echo $this->__("edit");?></a>
        </dd>
    </dl>
</div>

<!-- normal address tmplate -->
<div class="panel panel-default hidden" id="normal-address-template">
    <div class="panel panel-default">
        <div class="panel-body">
            <dl class="pull-left small-no-float">
                <dt>{{firstname}} {{lastname}}</dt>
                <dd>{{street}}</dd>
                <dd>{{postcode}} {{city}}</dd>
                <dd class="action separator">
                    <a href="#" class="underline edit"><?php echo $this->__("edit");?></a>
                    <a href="#" class="underline remove"><?php echo $this->__("remove");?></a>
                </dd>
            </dl>
            <button class="btn-select button button-third large choose"><?php echo $this->__("Choose")?></button>
        </div>
    </div>
</div>

<!-- add new template -->
<div class="panel add-new hidden" id="addressbook-add-new-template" data-toggle="modal" data-target="#addressbook-modal">
    <div class="panel-body">
        <h4 class="addressbook-add-new"><i class="fa fa-plus-circle fa-lg"></i>&nbsp;<strong><?php echo $this->__("ADD NEW ADDRESS"); ?></strong></h4>
        <div class="panel-body-content">

        </div>
    </div>
</div>

<!-- Edit / add mdoal -->
<div class="modal fade bs-example-modal-lg" id="addressbook-modal" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"></button>
                <h2 class="title_section" id="modal-title"></h2>
            </div>
            <div class="modal-body" id="modal-body">
            </div>
        </div>
    </div>
</div>


<div class="panel panel-default">
    <div class="panel-body panel-body-with-footer">
        <div class="current-rma-address current-address shipping clearfix">
            <!-- content from js -->
        </div>
        <div class="panel-adresses shipping">
            <!-- content from js -->
        </div>
    </div>
    <div class="panel-footer clearfix">
        <a href="#" class="underline pull-right change_address shipping">
            <?php echo $this->__("Change address");?>
        </a>
    </div>
</div>