
<?php
/* @var $this Zolago_Catalog_Block_Product_Vendor_Info */

$marketingInformation = $this->getMarketingInfo();
$deliveryReturnsInfo = !empty($marketingInformation->delivery_information) || !empty($marketingInformation->return_information);
?>
<!-- brand details -->
<?php if (!empty($marketingInformation->brand_information_title)&&!empty($marketingInformation->brand_information)): ?>
    <li>
        <a href="#"><?php echo $this->__($marketingInformation->brand_information_title); ?><i class="fa fa-chevron-down"></i></a>
        <ul class="vendor-menu-mobile-content">
            <li style="height: inherit; padding: 8px 20px 8px 10px;">
                <div>
                    <?php echo $marketingInformation->brand_information; ?>
                </div>
            </li>
        </ul>
    </li>
<?php endif; ?>
<!-- end brand details -->


<!-- vendor details -->
<?php if (!empty($marketingInformation->store_information_title)): ?>
<li>
    <a href="#"><?php echo $this->__($marketingInformation->store_information_title); ?><i class="fa fa-chevron-down"></i></a>
    <ul class="vendor-menu-mobile-content">
        <li style="height: inherit; padding: 8px 20px 8px 10px;">
            <div>
                <?php if (!empty($marketingInformation->store_information)): ?>
                    <?php echo $marketingInformation->store_information; ?>
                <?php else: ?>
                    <dd>
                        <img src="<?php echo $this->getLogoUrl(); ?>" alt="<?php echo $this->escapeHtml($this->getVendorName()); ?>"><br/>
                        <strong><?php echo $this->__("Seller"); ?>:</strong> <?php echo $this->getVendorName(); ?>
                    </dd>
                <?php endif;?>
            </div>
        </li>
    </ul>
</li>
<?php endif; ?>
<!-- end vendor details -->





<!-- vendor Shipping and Returns -->
<?php if ($deliveryReturnsInfo): ?>
<li>
    <a href="#"><?php echo $this->__("DELIVERY & RETURNS"); ?><i class="fa fa-chevron-down"></i></a>
    <ul class="vendor-menu-mobile-content">
        <li style="height: inherit; padding: 8px 20px 8px 10px;">
            <div>
                <div id="termsDeliveryInformation"><?php echo $marketingInformation->delivery_information; ?></div>
                <div id="termsReturnInformation"><?php echo $marketingInformation->return_information; ?></div>
            </div>
        </li>
    </ul>
</li>
<?php endif; ?>
<!-- end vendor Shipping and Returns -->