<?php
$vendorId = Mage::app()->getRequest()->getParam("id", null);
$helper = Mage::helper("zolagodropship");
?>

<?php if ($vendorId): ?>

    <?php
    $vendor = Mage::getModel("udropship/vendor")->load($vendorId);
    $vendorEmail = $vendor->getEmail();
    ?>

    <button id="modago_salesmanago_create_account">
        <?php echo $helper->__("Create account SALESmanago account"); ?>
    </button>

    <div id="modago_salesmanago_create_account_wrapper" style="display: none;">
        <img src="<?php echo Mage::getBaseUrl("js"); ?>/spinner.gif"/>
    </div>
    <div id="modago_salesmanago_create_account_data"></div>

    <script type="text/javascript">
        jQuery(document).ready(function () {
            var email = '<?php echo $vendorEmail; ?>';

            function accountCreated() {
                jQuery("#modago_salesmanago_create_account_wrapper").hide();
                alert('<?php echo $helper->__("Account has been created. You will have information on %s about active account after verification", $vendorEmail); ?>');
            }

            jQuery("#modago_salesmanago_create_account").click(function (e) {
                e.preventDefault();
                var r = confirm('<?php echo $helper->__("This function will create account in Marketing Automation SalesManago using Vendor email and actual password. Do you want to continue?"); ?>');


                if (r == true) {
                    jQuery("#modago_salesmanago_create_account_wrapper").show();
                    //"Konto zostało założone - po weryfikacji na adres email .... otrzymasz informację, że konto jest aktywne"
                    setTimeout(
                        function () {
                            accountCreated();
                        }, 5000);

                }


            });

        });
    </script>
<?php endif; ?>

