<?php $_helper = Mage::helper("zolagooperator");?>
<?php $_pos = $this->getModel();?>
<div class="container">
	<!--=== Page Header ===-->
	<div class="page-heading row">
		<div class="col-lg-6">
			<h3>
			<?php if(!$this->getIsNew()):?>
				<?php echo $_helper->__("Edit agent");?> <?php echo $this->escapeHtml($_pos->getEmail());?>
			<?php else:?>
				<?php echo $_helper->__("Create agent");?>
			<?php endif;?>
			</h3>
		</div>
		<div class="main-actions align-right col-md-6">
		
		</div>
	</div>
</div>

<div class="container">
	<form id="edit-operator" class="form-horizontal row-border" action="<?php echo $this->getForm()->getAction();?>" method="POST">
		<input type="hidden" name="operator_id" value="<?php echo $_pos->getId();?>"/>
		<?php echo $this->getLayout()->getBlock('formkey')->toHtml();?>
		<?php echo $this->getFormHtml();?>
		<div class="form-actions"> 
			<input type="submit" value="<?php echo $_helper->__("Save");?>" class="btn btn-primary pull-right"> 
			<input type="button" value="<?php echo $_helper->__("Cancel");?>" class="btn pull-right" onclick="location.href='<?php echo $this->getUrl('*/*/');?>'"> 
		</div>
	</form>
</div>

<script type="text/javascript">
jQuery(function($){
	var form = $("#edit-operator");
	new Zolago.formIntegrator(form);
    form.validate();
});
</script>