<?php $_helper = Mage::helper("zolagooperator");?>
<?php $_pos = $this->getModel();?>
<?php echo $this->getMessagesBlock()->getGroupedHtml(); ?>
<div class="page-title">
	<h1>
		<?php if(!$this->getIsNew()):?>
			<?php echo $_helper->__("Edit operator");?> <?php echo $this->escapeHtml($_pos->getEmail());?>
		<?php else:?>
			<?php echo $_helper->__("Create operator");?>
		<?php endif;?>
	</h1>
</div>
<div>
	<form id="edit-operator" action="<?php echo $this->getForm()->getAction();?>" method="POST">
		<?php echo $this->getLayout()->getBlock('formkey')->toHtml();?>
		<?php echo $this->getFormHtml();?>
		<div>
			<button class="form-button" type="submit"><span><?php echo $_helper->__("Save operator");?></span></button>
		</div>
	</form>
	<script type="text/javascript">
		var posForm = new VarienForm('edit-operator');
	</script>
</div>