<?php /* @var $this Zolago_Modago_Block_Sales_Order_Process */ ?>

<?php $_orders = $this->getOrders(); ?>
<?php $_helper = Mage::helper("zolagosales");?>
<?php $baseUrl = Mage::helper("core/url")->getHomeUrl(); ?>

<?php
$request = Mage::app()->getRequest();
$customerAccountPage = false;
if ($request->getRouteName() == "customer"
	&& $request->getControllerName() == "account"
	&& $request->getActionName() == "index") {
    $customerAccountPage = true;
}
?>
<input type="hidden" value="<?php echo (int)$customerAccountPage; ?>" name="customer_account_page" />
<div class="page-title box-wrapper <?php if($customerAccountPage): ?> hidden-xs <?php endif; ?>">
	<h1>
		<span><?php echo $this->__('Orders in the realization') ?></span>
		<span class="back-sm"><a href="<?php echo $baseUrl ?>customer/account/index/" class="underline"><?php echo $_helper->__('back: my account'); ?>&nbsp;&gt;</a></span>
		<span class="back-xs"><a href="<?php echo $baseUrl ?>customer/account/index/" class="underline"><?php echo $_helper->__('back'); ?>&nbsp;&gt;</a></span>
	</h1>
</div>
<?php echo $this->getChildHtml("attach"); ?>
<div class="order-view order-view-multi <?php if($customerAccountPage): ?> hidden-xs <?php endif; ?>">
	<div class="section " id="content-main">
	<?php if($_orders->getSize()): ?>
		<?php foreach($_orders as $_order):?>
		<?php /* @var $_order Mage_Sales_Model_Order */ ?>
			<?php /* @see sales/order/process/view.phtml */ ?>
			<?php echo $this->getOrderHtml($_order); ?>
		<?php endforeach;?>
	<?php else: ?>
		<?php echo $this->getChildHtml("empty");?>
	<?php endif ?>
	</div>
</div>

<div class="hidden " id="vendor_contact_form_template">
	<?php echo $this->getChild("question")->
		setVendorId("{{vendor_id}}")->
		setOrderId("{{order_id}}")->
		setShipmentId("{{shipment_id}}")->
		toHtml(); ?>
</div>

<script type="text/javascript">
	jQuery(function(){
		Mall.translate.add("Ask question about order", '<?php echo $_helper->__("Ask question about order");?>');
		Mall.translate.add("This field is required.", '<?php echo $_helper->__("This field is required.");?>');
		Mall.sales.vendorContact.setFormTemplateId("vendor_contact_form_template");
		jQuery("a.contact-vendor").click(Mall.sales.vendorContact.handleClick);
		jQuery(window).resize(Mall.sales.vendorContact.handleResize);
		
		jQuery(".mobile-toggler a").click(function(){
			var el = jQuery(this),
				text = el.data(el.parent().hasClass("open") ? "close" : "open");
			el.
				find('span').
					text(text).
					end().
				find("i").
					toggleClass("fa-chevron-down").
					toggleClass("fa-chevron-up").
					end().
				parent().
					toggleClass("open").
					end().
				parents(".panel").
				find(".mobile-toggle").
					toggleClass("visisble-xs").
					toggleClass("hidden-xs");
			return false;
		})
	});
    var customerAccountPage = "<?php echo (int)$customerAccountPage; ?>";
    if (customerAccountPage == 1) {
        jQuery(".section ul.nav li:first-child a").addClass("active");
    }
</script>