<?php
$rewriteData = Mage::helper("ghrewrite")->getCategoryRewriteData();

$categoryWithFiltersBlock = "";
if (!empty($rewriteData) && isset($rewriteData["text_field_category"]) && !empty($rewriteData["text_field_category"])) {
    $categoryWithFiltersBlock = $rewriteData["text_field_category"];
}
?>
<div id="category_with_filters">
    <?php if (!empty($categoryWithFiltersBlock)): ?>
        <div class="sidebar solr_search_facets">
            <div class="section clearfix  category_with_filters">
                <div class="content">
                    <?php echo $categoryWithFiltersBlock; ?>
                </div>
            </div>
        </div>
    <?php endif; ?>
</div>

