<?php $hlp = Mage::helper('udropship') ?>
<?php $_po    = $this->getPo() ?>
<?php $_order = $this->getOrder() ?>
<?php if ($_po && $_order): ?>
<table cellspacing="0" cellpadding="0" border="0" width="100%" style="border:1px solid #bebcb7; background:#f8f7f5;">
    <thead>
        <tr>
            <th align="left" bgcolor="#d9e5ee" style="padding:3px 9px"><?php echo $this->__('Item') ?></th>
            <th align="left" bgcolor="#d9e5ee" style="padding:3px 9px"><?php echo $this->__('Sku') ?></th>
            <th align="center" bgcolor="#d9e5ee" style="padding:3px 9px"><?php echo $this->__('Cost') ?></th>
            <th align="center" bgcolor="#d9e5ee" style="padding:3px 9px"><?php echo $this->__('Qty') ?></th>
            <th align="center" bgcolor="#d9e5ee" style="padding:3px 9px"><?php echo $this->__('Row Cost') ?></th>
        </tr>
    </thead>

    <?php $i=0; foreach ($_po->getAllItems() as $_item): ?>
    <?php if($_item->getOrderItem()->getParentItem()) continue; else $i++; ?>
    <tbody<?php echo $i%2 ? ' bgcolor="#eeeded"' : '' ?>>
        <?php echo $this->getItemHtml($_item) ?>
    </tbody>
    <?php endforeach; ?>

    <tfoot>
        <tr>
            <td colspan="4" align="right" style="padding:3px 9px">Total Cost</td>
            <td align="right" style="padding:3px 9px"><?php echo $hlp->displayPrices($_order, $_po->getTotalCost()) ?></td>
        </tr>
    </tfoot>

</table>

<?php if($_order->getGiftMessageId() && $_giftMessage = $this->helper('giftmessage/message')->getGiftMessage($_order->getGiftMessageId())): ?>

<br />

<table cellspacing="0" cellpadding="0" border="0" width="100%" style="border:1px solid #bebcb7; background:#f8f7f5;">
    <thead>
        <tr>
            <th align="left" bgcolor="#d9e5ee" style="padding:3px 9px"><strong><?php echo $this->__('Gift Message for this Order') ?></strong></th>
        </tr>
    </thead>

    <tbody>
        <tr>
            <td colspan="4" align="left" style="padding:3px 9px">
            <strong><?php echo $this->__('From:'); ?></strong> <?php echo $this->htmlEscape($_giftMessage->getSender()) ?>
            <br /><strong><?php echo $this->__('To:'); ?></strong> <?php echo $this->htmlEscape($_giftMessage->getRecipient()) ?>
            <br /><strong><?php echo $this->__('Message:'); ?></strong><br /> <?php echo $this->htmlEscape($_giftMessage->getMessage()) ?>
            </td>
        </tr>
    </tbody>
</table>

<?php endif; ?>

<?php endif; ?>
