<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2016 Amasty (https://www.amasty.com)
 * @package Magpleasure_Blog
 */

/** @var Magpleasure_Blog_Block_Sidebar_Recentpost $this */

/** @var Magpleasure_Blog_Model_Mysql4_Category_Collection $collection  */
$collection = $this->getCollection();
?>
<?php if ($this->getDisplay() && count($collection)): ?>
<div class="block mpblog-recentposts">
    <div class="block-title">
        <strong><span><?php echo $this->getBlockHeader(); ?></span></strong>
    </div>
    <div class="block-content">
        <ul class="mbplog-recent-posts">
        <?php foreach ($collection as $post): ?>
            <?php /** @var Magpleasure_Blog_Model_Post $post */ ?>
            <li class="mpblog-recent-post<?php if ($post->getIsActive()): ?> active<?php endif; ?> mpblog-recent-post-<?php echo $post->getId(); ?> fix-me">
                <?php if ($this->hasThumbnail($post)): ?>
                <a class="thumbnail" href="<?php echo $post->getPostUrl(); ?>" title="<?php echo $this->escapeHtml($post->getTitle()); ?>">
                    <img class="img" src="<?php echo $this->getThumbnailSrc($post); ?>" alt="<?php echo $this->escapeHtml($post->getTitle()); ?>" >
                </a>
                <?php endif; ?>
                <a href="<?php echo $post->getPostUrl(); ?>"><?php echo $this->escapeHtml($post->getTitle()); ?></a>
                <?php if ($this->showDate()): ?>
                <div class="mp-recentpost-date">
                    <?php echo $this->renderDate($post->getCreatedAt()); ?>
                </div>
                <?php endif; ?>
                <?php if ($this->showThesis()): ?>
                <div class="mp-post-thesis">
                    <?php echo $this->getStrippedContent($post->getShortContent()); ?>
                </div>
                <?php endif; ?>

            </li>
        <?php endforeach; ?>
        </ul>
    </div>
</div>
<?php endif; ?>
