<?php /* @var $this Zolago_Customer_Block_Account_Forgotpasswordmessage */ ?>
<?php
/**
 * Author: Paweł Chyl <pawel.chyl@orba.pl>
 * Date: 04.09.2014
 */

?>

<?php
$_hlp = $this->helper("zolagocustomer");
?>

<div id="content" class="container-fluid">
    <div id="logIn" class="row">
        <div id="content-main" class="">
            <div class="col-sm-12 column-block">
                <div class="main bg-w equalBlock col-01">

                    <?php echo $this->getMessageHtml(); ?>

                </div>
            </div>
        </div>
    </div>
</div>

<style type="text/css">
    #nav_mobile {display: none !important;}
    #header-main {display: none !important;}
</style>