<?php
/** @var $_product Zolago_Catalog_Model_Product */
/** @var $product Mage_Wishlist_Model_Item */
/** @var $_collection Mage_Wishlist_Model_Resource_Item_Collection */
$_collection = $this->getItems();
/** @var Zolago_Catalog_Helper_Product $_helper */
$_helper = Mage::helper('zolagocatalog/product');
$brandImagesList = Mage::helper('wishlist')->getBrandImagesList();
?>

<div class="container-fluid" id="items-product">
    <div class="row">
        <div class="col-xs-12 col-sm-12">
            <div class="row">
                <div id="grid" class="shuffle--container shuffle--fluid">
                    <?php foreach ($_collection as $product): ?>
                        <?php $_product = $product->getProduct(); ?>
                        <?php $_productImageUrl = $_helper->getResizedImageUrl($_product); ?>
                        <?php $_productImageInfo = $_helper->getResizedImageInfo($_product); ?>
                        <div id="prod-<?php echo $product->getEntityId();?>" class="item col-phone col-xs-4 col-sm-4 col-md-3 col-lg-3 size14">
                            <div class="box_listing_product">
                                <a href="<?php echo $_product->getProductUrl(); ?>">
	                                <figure class="img_product" style="padding-bottom: <?php echo 100 * round(($_productImageInfo["height"] /  $_productImageInfo["width"]),2); ?>%">
		                                <img src="<?php echo $_productImageUrl; ?>"
		                                     alt="<?php $this->escapeHtml($product->getName()); ?>"
		                                     class="img-responsive" />
	                                </figure>
                                    <div class="name_product">
                                        <?php echo $this->escapeHtml($_product->getName()); ?>
                                    </div>
                                </a>
                                    <div class="price clearfix">
                                        <div class="col-price">
                                            <?php if ($_product->getPrice() != $_product->getFinalPrice()) : ?>
                                                <span class="old">
                                                        <?php echo $this->helper('core')->currency($product->getPrice(), true, false); ?>
                                                    </span>
                                            <?php endif; ?>
                                            <span>
                                                    <?php echo $this->helper('core')->currency($_product->getFinalPrice(), true, false); ?>
                                                </span>
                                        </div>
                                        <?php
                                        // like count
                                        $wishlistCount = "";
                                        $inMyWishlist = "";
                                        $plusSign = "";
                                        if ($_product->getWishlistCount() - 1 > 0) {
                                            $wishlistCount = $_product->getWishlistCount();
//                                            if ($_product->getInMyWishlist()) {
                                                $wishlistCount -= 1;
//                                            }
                                        }

//                                        if ($product->getInMyWishlist()) {
                                            $inMyWishlist = $this->__("You");
                                            if ($_product->getWishlistCount() > 1) {
                                                $plusSign = " + ";
                                            }
//                                        }
                                        ?>
                                        <div class="like liked"
                                             data-idproduct="<?php echo $_product->getId(); ?>">
                                            <span class="like_count">
                                                <span>
                                                    <?php echo $inMyWishlist; ?>
                                                    <?php echo $plusSign; ?>
                                                </span>
	                                            <?php echo $wishlistCount > 99 ? "99+" : $wishlistCount; ?>
                                            </span>
	                                        <span class="icoLike"></span>
                                            <div class="toolLike"></div>
                                        </div>
                                    </div>

                            </div>
                        </div>
                    <?php endforeach; ?>
                    <div class="col-xs-12 shuffle__sizer"></div>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
	//needed for like removal process
	var unlikingOnWishlist = true;

    Mall.translate.add("you-like-this", "<?php echo $this->__("You like this"); ?>");
    Mall.translate.add("remove-from-favorites", "<?php echo $this->__("remove from favorites"); ?>");
    Mall.translate.add("add-to-br-favorites", "<?php echo $this->__("Add to<br />favorites"); ?>");
    Mall.translate.add("like-this-product", "<?php echo $this->__("like this product"); ?>");
    Mall.translate.add("likes-this-product", "<?php echo $this->__("likes this product"); ?>");
    Mall.translate.add("you-and", "<?php echo $this->__("You and"); ?>");
    Mall.translate.add("person", "<?php echo $this->__("person"); ?>");
    Mall.translate.add("people", "<?php echo $this->__("people"); ?>");
    Mall.translate.add("people-polish-more-than-few", "<?php echo $this->__("people polish more than few"); ?>");
    Mall.translate.add("you", "<?php echo $this->__("You"); ?>");
    Mall.translate.add("You", "<?php echo $this->__("You"); ?>");

    Mall.initUrls("<?php echo Mage::getBaseUrl(); ?>","<?php echo Mage::getUrl("/",array("_no_vendor"=>true)); ?>");

    var grid = jQuery('#grid'),
        sizer = jQuery(grid).find('.shuffle__sizer');

    grid.shuffle({throttleTime: 800, speed: 0, supported: false });
    grid.shuffle('update');

    jQuery(grid).on('layout.shuffle', function() {
        Mall.wishlist.likePriceView();
        //fix for footer
        jQuery(window).resize();
    });

    jQuery(grid).find('.img_product img').on('load', function(){
        grid.shuffle('layout');
    });

    <?php foreach ($_collection as $product): ?>
    <?php $_product = $product->getProduct(); ?>
    Mall.wishlist.addProduct({
        id: <?php echo $_product->getId(); ?>,
        wishlist_count: <?php echo (int)$_product->getWishlistCount(); ?>,
        in_your_wishlist: "true"
    });
    <?php endforeach; ?>
</script>

