
<div class="section clearfix visible-xs" id="customer-account-navigation-mobile-wrapp">
    <div class="wrapp-section bg-w">
        <h1><?php echo $this->__('My Account'); ?></h1>
    </div>
    <div class="header_bottom">
        <div class="container-fluid">
            <ul class="navigation" id="customer-account-navigation-mobile" role="navigation">
                <?php $_links = $this->getLinks(); ?>
                <?php $_index = 1; ?>
                <?php $_count = count($_links); ?>
                <?php foreach ($_links as $_link): ?>
                    <?php $_last = ($_index++ >= $_count); ?>
                    <li>
                        <a href="<?php echo $_link->getUrl() ?>" class=""><?php echo $_link->getLabel() ?>
                            <i class="fa fa-chevron-right"></i>
                        </a>
                    </li>
                <?php endforeach; ?>
            </ul>
        </div>

    </div>
</div>