<?php
/** @var $this Zolago_Solrsearch_Block_Active */
$q = array();
$filterQuery = $this->getFilterQuery();
$rewriteData = Mage::helper("ghrewrite")->getCategoryRewriteData();
$filterLabel = $this->__('Currently Shopping:');
$categoryWithFiltersTitle = "";
if(!empty($rewriteData)){
    if(isset($rewriteData["text_field_filter"]) && !empty($rewriteData["text_field_filter"])){
        $filterLabel = $rewriteData["text_field_filter"];
    }
    if(isset($rewriteData["listing_title"]) && !empty($rewriteData["listing_title"])){
        $categoryWithFiltersTitle = $rewriteData["listing_title"];
    }
}
$category = $this->getCurrentCategory();

/* @var $campaign Zolago_Campaign_Model_Campaign */
$campaign = $category->getCurrentCampaign();
$campaignActiveFilterLabel = $campaign ? $campaign->getActiveFilterLabel() : "";

/* @var $listModel Zolago_Solrsearch_Model_Catalog_Product_List */
$listModel = Mage::getSingleton("zolagosolrsearch/catalog_product_list");
$type = $listModel->getMode()==$listModel::MODE_SEARCH ? "search" : "category";

?>
<?php if(!$this->isContentMode()): ?>
<div id="active-filters">
    <div class="wrapp-section bg-w">
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-12">
                    <?php if(sizeof($filterQuery) > 0 && $this->isSelectedFacetActive()) : ?>
                        <dl class="clearfix" >
                            <dt><?php echo $filterLabel; ?></dt>
                            <dd>
                                <?php foreach ($filterQuery as $key => $values):?>
                                    <?php foreach ($values as $v): ?>
                                        <?php if($key != 'category_id'): ?>
                                            <?php $face_key = substr($key, 0, strrpos($key, '_')) ?>
                                            <?php
                                            $selectedFacetValue = $v;
                                            if ($face_key == 'price') {
                                                $selectedFacetValue = $this->formatFacetPrice($v);
                                            } elseif (in_array($face_key, array(Zolago_Campaign_Model_Campaign::ZOLAGO_CAMPAIGN_ID_CODE, Zolago_Campaign_Model_Campaign::ZOLAGO_CAMPAIGN_INFO_CODE))) {
                                                $selectedFacetValue = ($campaign) ? $campaign->getNameCustomer() : "";

                                                if (!empty($campaignActiveFilterLabel))
                                                    $selectedFacetValue = $campaignActiveFilterLabel;
                                            }
                                            ?>
                                            <span class="label">
                                                <?php if (!in_array($key, array("campaign_info_id_facet", "campaign_regular_id_facet"))
                                                || empty($campaignActiveFilterLabel)
                                                ): ?>
                                                    <?php echo $this->__($this->getFacetLabel($key)); ?>:
                                                <?php endif; ?>
                                                <span class="value">
                                                    <?php echo $this->facetFormat($selectedFacetValue) ?>
                                                </span>
												<span>
													<a  href="<?php echo $this->getRemoveFacesUrl($face_key, $v); ?>"
													   class="fa fa-times active-filter-label"
                                                        data-input="<?php echo $this->getItemId($face_key, $v)?>"></a>
												</span>
                                            </span>

                                            <?php if($face_key != 'price'): ?>
                                                <input type="hidden" name="fq[<?php echo $face_key ?>]"
                                                       value="<?php echo $v ?>"/>
                                            <?php endif; ?>
                                        <?php endif; ?>
                                    <?php endforeach; ?>
                                <?php endforeach; ?>
                            </dd>
                            <dd class="action hidden-xs hidden-sm-to-smmd">
                                <a data-params='<?php echo $this->getRemoveAllJson(); ?>'
                                   href="<?php echo $this->getRemoveAllUrl() ?>"
                                   class="active-filters-remove button button-third"><?php echo $this->__('Clear all filters') ?></a>
                            </dd>
                        </dl>
                    <?php endif; ?>
                </div>
            </div>
            <div class="row" id="filters-btn">
                <div class="col-sm-12">
                    <dl>
                        <dd class="visible-xs visible-sm-to-smmd col-xs-5">
                            <div class="view_filter clearfix">
                                <a href="#" class="actionViewFilter button button-primary medium visible-xs visible-sm-to-smmd">
                                    <i class="fa fa-chevron-right"></i>
                                    <?php echo $this->__("Filter Products"); ?>
                                </a>
                            </div>
                        </dd>
                        <?php if(sizeof($filterQuery) > 0 && $this->isSelectedFacetActive()) : ?>
                            <dd class="action visible-xs visible-sm-to-smmd btn-clearall-xs">
                                <a data-params='<?php echo $this->getRemoveAllJson(); ?>'
                                   href="<?php echo $this->getRemoveAllUrl() ?>"
                                   class="active-filters-remove button button-third"><?php echo $this->__('Clear all filters') ?></a>
                            </dd>
                        <?php endif; ?>
                    </dl>
                </div>
            </div>
        </div>
    </div>
</div>
    <?php if (!empty($categoryWithFiltersTitle)): ?>
        <div class="category-with-filters-description" style="margin-left: -15px;padding-bottom: 15px;">
            <div class="wrapp-section bg-w">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-sm-12">
                            <?php echo $categoryWithFiltersTitle; ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    <?php endif; ?>
<?php else: ?>
    <div style="display: block;width: 100%; height:15px" class="hidden-xs"></div>
<?php endif; ?>
