<div id="content" class="container-fluid">
	<div id="logIn" class="row">
		<div id="content-main" class="">
			<div class="col-sm-6 column-block login-column">
				<div class="main bg-w equalBlock col-01">  
					<form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="login-form" class="form-horizontal" autocomplete="off" role="form" style="margin-bottom:70px">
						<?php echo $this->getBlockHtml('formkey'); ?>
						<?php if($_isCheckout):?>
							<input name="is_checkout" type="hidden" value="1"/>
						<?php endif;?>
						<?php if($this->getRequest()->getParam('redirect')): ?>
							<input name="redirect" type="hidden" value="<?php echo $this->getRequest()->getParam('redirect'); ?>" />
						<?php endif; ?>
						<section class="section clearfix">
							<header class="title-section">
								<h2><?php echo $_hlp->__('Do you have account already?') ?></h2>
								<p class="form-instructions ff_os fz_11"><?php echo $_hlp->__("Log in to access your order history and shipping addresses");?></p>
							</header>
							<ul class="form-list clearfix">
								<li>
									<div class="form-group">
										<label for="email" class="col-md-3 col-sm-12 col-xs-12 control-label"><?php echo $_hlp->__("Email address");?></label>

										<div class="col-md-9 col-sm-12 col-xs-12">
											<input type="email" name="login[username]" value="" id="email" class="form-control email input-text required-entry validate-email" autocomplete="off" title="" tabindex="1">
										</div>
									</div>
								</li>
								<li>
									<div class="form-group">
										<label for="pass" class="col-md-3 col-sm-12 col-xs-12 control-label required"><?php echo $_hlp->__("Password");?></label>

										<div class="col-md-9 col-sm-12 col-xs-12">
											<div class="inner-form-group">
												<a class="forgot-password underline visible-sm visible-xs" href="<?php echo $this->getForgotPasswordUrl() ?>"><?php echo $this->__('Forgot Your Password?') ?></a>
												<input type="password" name="login[password]" class="form-control input-text required-entry validate-password login-text-field" id="pass" title="" autocomplete="off" tabindex="2">
												<a class="forgot-password underline hidden-sm hidden-xs" href="<?php echo $this->getForgotPasswordUrl() ?>" style="left: 157px;"><?php echo $_hlp->__("You don't remember password?"); ?></a>
											</div>
										</div>
									</div>
								</li>
							</ul>
							<?php /* echo $this->getChildHtml('persistent.remember.me') */; ?>
							<?php echo $this->getChildHtml('form.additional.info'); ?>
							<button type="submit" name="send" class="button button-primary large link pull-right" style="bottom:30px;" id="login-button"><?php echo $_hlp->__('Login') ?></button>

						</section>
					</form>
				</div>
			</div>
			<div class="col-sm-6 column-block register-column">
				<div class="main bg-w equalBlock col-02">
					<?php echo $this->getChildHtml("form.register.continue");?>
				</div>
			</div>
		</div>
	</div>
</div>

    <script type="text/javascript">
        Mall.i18nValidation.add("required", "<?php echo $this->__('This field is required') ?>");
        Mall.i18nValidation.add("email", "<?php echo $this->__('Valid email is required.') ?>");
    </script>
    <style type="text/css">
        #nav_mobile {display: none !important;}
        #header-main {display: none !important;}
    </style>
<?php /*
<div class="account-login">
    <div class="page-title">
        <h1><?php echo $this->__('Login or Create an Account') ?></h1>
    </div>
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="login-form">
        <?php echo $this->getBlockHtml('formkey'); ?>
        <div class="col2-set">
            <div class="col-1 new-users">
                <div class="content">
                    <h2><?php echo $this->__('New Customers') ?></h2>
                    <p><?php echo $this->__('By creating an account with our store, you will be able to move through the checkout process faster, store multiple shipping addresses, view and track your orders in your account and more.') ?></p>
                </div>
            </div>
            <div class="col-2 registered-users">
                <div class="content">
                    <h2><?php echo $this->__('Registered Customers') ?></h2>
                    <p><?php echo $this->__('If you have an account with us, please log in.') ?></p>
                    <ul class="form-list">
                        <li>
                            <label for="email" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>
                            <div class="input-box">
                                <input type="text" name="login[username]" value="<?php echo $this->escapeHtml($this->getUsername()) ?>" id="email" class="input-text required-entry validate-email" title="<?php echo $this->__('Email Address') ?>" />
                            </div>
                        </li>
                        <li>
                            <label for="pass" class="required"><em>*</em><?php echo $this->__('Password') ?></label>
                            <div class="input-box">
                                <input type="password" name="login[password]" class="input-text required-entry validate-password" id="pass" title="<?php echo $this->__('Password') ?>" />
                            </div>
                        </li>
                        <?php echo $this->getChildHtml('form.additional.info'); ?>
                        <?php echo $this->getChildHtml('persistent.remember.me'); ?>
                    </ul>
                    <?php echo $this->getChildHtml('persistent.remember.me.tooltip'); ?>
                    <p class="required"><?php echo $this->__('* Required Fields') ?></p>
                </div>
            </div>
        </div>
        <div class="col2-set">
            <div class="col-1 new-users">
                <div class="buttons-set">
                    <button type="button" title="<?php echo $this->__('Create an Account') ?>" class="button" onclick="window.location='<?php echo Mage::helper('persistent')->getCreateAccountUrl($this->getCreateAccountUrl()) ?>';"><span><span><?php echo $this->__('Create an Account') ?></span></span></button>
                </div>
            </div>
            <div class="col-2 registered-users">
                <div class="buttons-set">
                    <a href="<?php echo $this->getForgotPasswordUrl() ?>" class="f-left"><?php echo $this->__('Forgot Your Password?') ?></a>
                    <button type="submit" class="button" title="<?php echo $this->__('Login') ?>" name="send" id="send2"><span><span><?php echo $this->__('Login') ?></span></span></button>
                </div>
            </div>
        </div>
        <?php if (Mage::helper('checkout')->isContextCheckout()): ?>
            <input name="context" type="hidden" value="checkout" />
        <?php endif; ?>
    </form>
    <script type="text/javascript">
    //<![CDATA[
        var dataForm = new VarienForm('login-form', true);
    //]]>
    </script>
</div>

*/ ?>