<?php /** @var Mage_Customer_Block_Form_Register $this */ ?>
<?php
/** @var Zolago_Modago_Helper_Data $modagoHelper */
$modagoHelper = Mage::helper('zolagomodago');
?>
<div id="content" class="container-fluid">
	<div class="account-create row">
        <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('customer-register-right')->toHtml(); ?>
		<div id="content-main" class="col-lg-9 col-md-8 col-sm-8 col-xs-12 col-lg-pull-3 col-md-pull-4 col-sm-pull-4 section">
			<section class="main bg-w">
				<header class="title-section">
					<h2><?php echo $this->__('Create an Account') ?></h2>
				</header>
				<div class="row">
					<form autocomplete="off" action="<?php echo $this->getPostActionUrl() ?>" class="form"
					      id="createAccountForm" method="post" role="form" novalidate="novalidate">
						<div class="col-lg-6 col-md-7 col-sm-11 col-xs-12">
							<div class="form-group clearfix">
								<div class="row">
									<label class="col-lg-4 col-md-4 col-sm-4 col-xs-12"
									       for="account_email">
										<?php echo $this->__('Email Address'); ?>
									</label>
									<div class="col-lg-8 col-md-8 col-sm-8 col-xs-12 control-label required">
										<input type="email" value="" class="form-control email"
										       required="true" id="account_email" title=""
										       name="email" data-original-title="<?php echo $this->__("Please enter email."); ?>"
										       aria-required="true"/>
									</div>
								</div>
							</div>
							<div class="form-group clearfix">
								<div class="row">
									<label class="col-lg-4 col-md-4 col-sm-4 col-xs-12 control-label required"
									       for="account_password">
										<?php echo $this->__('Password'); ?>
									</label>
									<div class="col-lg-8 col-md-8 col-sm-8 col-xs-12">
										<input type="password" class="form-control hint password"
										       required="true" id="account_password" title=""
										       name="password" data-original-title="<?php echo $this->__("Password needs to have at least 6 characters"); ?>"
										       data-placement="bottom" aria-required="true"/>
									</div>
								</div>
							</div>
						</div>

						<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
							<div class="agreement-nocheck-registration">
								<?php echo $modagoHelper->getAgreementHtml('register_info') ?>
							</div>
							<div class="form-group form-checkbox small text-align-left" id="tos_agreement_container_registration">
								<input type="checkbox" id="agreement" class="css-checkbox required"
									   required="true"
									   name="agreement"
									   aria-required="true">
								<label for="agreement" class="css-label agreement-label control-label required">
									<?php echo $modagoHelper->getAgreementHtml('policy') ?>
								</label>
							</div>
							<div class="form-group form-checkbox small text-align-left" id="newsletter_agreement_container_registration">
								<input type="checkbox" id="is_subscribed" class="css-checkbox"
								       name="is_subscribed" style="opacity: 0; visibility: visible;">
								<label for="is_subscribed" class="css-label agreement-label">
									<?php echo $modagoHelper->getAgreementHtml('newsletter') ?>
								</label>
							</div>
						</div>
						<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
							<div class="row action">
								<div class="col-sm-6">
									<a id="back" href="<?php echo $this->getBackUrl(); ?>"
									   class="button button-third large pull-left">
										<i class="glyphicon glyphicon-chevron-left"></i>
										<?php echo $this->__("back"); ?>
									</a>
								</div>
								<div class="col-sm-6">
									<button type="submit" class="button button-primary large link pull-right">
										<?php echo $this->__('Save') ?>
									</button>
								</div>
							</div>
						</div>
					</form>
				</div>
			</section>
		</div>
	</div>
</div>
<script type="text/javascript">
	Mall.translate.add(
		"Please enter password.",
		"<?php echo $this->__("Please enter password."); ?>"
	);
	Mall.translate.add(
		"Password needs to have at least 6 characters",
		"<?php echo $this->__("Password needs to have at least 6 characters"); ?>"
	);
	Mall.translate.add(
		"Please enter email.",
		"<?php echo $this->__("Please enter email."); ?>"
	);
	Mall.translate.add(
		"Please enter correct email.",
		"<?php echo $this->__("Please enter correct email."); ?>"
	);
	Mall.translate.add(
		"You must accept our Terms of Service",
		"<?php echo $this->__("You must accept our Terms of Service"); ?>"
	);
</script>
<?php //Old registration form: ?>
<?php /*
<div class="account-create">
    <div class="page-title">
        <h1><?php echo $this->__('Create an Account') ?> Asdsadasdasd</h1>
    </div>
    <?php echo $this->getChildHtml('form_fields_before') ?>
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="form-validate">
        <div class="fieldset">
            <input type="hidden" name="success_url" value="<?php echo $this->getSuccessUrl() ?>" />
            <input type="hidden" name="error_url" value="<?php echo $this->getErrorUrl() ?>" />
            <h2 class="legend"><?php echo $this->__('Personal Information') ?></h2>
            <ul class="form-list">
                <li class="fields">
                    <?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getFormData())->setForceUseCustomerAttributes(true)->toHtml() ?>
                </li>
                <li>
                    <label for="email_address" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>
                    <div class="input-box">
                        <input type="text" name="email" id="email_address" value="<?php echo $this->escapeHtml($this->getFormData()->getEmail()) ?>" title="<?php echo $this->__('Email Address') ?>" class="input-text validate-email required-entry" />
                    </div>
                </li>
                <?php if ($this->isNewsletterEnabled()): ?>
                <li class="control">
                    <div class="input-box">
                        <input type="checkbox" name="is_subscribed" title="<?php echo $this->__('Sign Up for Newsletter') ?>" value="1" id="is_subscribed"<?php if($this->getFormData()->getIsSubscribed()): ?> checked="checked"<?php endif; ?> class="checkbox" />
                    </div>
                    <label for="is_subscribed"><?php echo $this->__('Sign Up for Newsletter') ?></label>
                </li>
                <?php endif ?>
            <?php $_dob = $this->getLayout()->createBlock('customer/widget_dob') ?>
            <?php if ($_dob->isEnabled()): ?>
                <li><?php echo $_dob->setDate($this->getFormData()->getDob())->toHtml() ?></li>
            <?php endif ?>
            <?php $_taxvat = $this->getLayout()->createBlock('customer/widget_taxvat') ?>
            <?php if ($_taxvat->isEnabled()): ?>
                <li><?php echo $_taxvat->setTaxvat($this->getFormData()->getTaxvat())->toHtml() ?></li>
            <?php endif ?>
            <?php $_gender = $this->getLayout()->createBlock('customer/widget_gender') ?>
            <?php if ($_gender->isEnabled()): ?>
                <li><?php echo $_gender->setGender($this->getFormData()->getGender())->toHtml() ?></li>
            <?php endif ?>
            </ul>
        </div>
    <?php if($this->getShowAddressFields()): ?>
        <div class="fieldset">
            <input type="hidden" name="create_address" value="1" />
            <h2 class="legend"><?php echo $this->__('Address Information') ?></h2>
            <ul class="form-list">
                <li class="fields">
                    <div class="field">
                        <label for="company"><?php echo $this->__('Company') ?></label>
                        <div class="input-box">
                            <input type="text" name="company" id="company" value="<?php echo $this->escapeHtml($this->getFormData()->getCompany()) ?>" title="<?php echo $this->__('Company') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('company') ?>" />
                        </div>
                    </div>
                    <div class="field">
                        <label for="telephone" class="required"><em>*</em><?php echo $this->__('Telephone') ?></label>
                        <div class="input-box">
                            <input type="text" name="telephone" id="telephone" value="<?php echo $this->escapeHtml($this->getFormData()->getTelephone()) ?>" title="<?php echo $this->__('Telephone') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('telephone') ?>" />
                        </div>
                    </div>
                </li>
            <?php $_streetValidationClass = $this->helper('customer/address')->getAttributeValidationClass('street'); ?>
                <li class="wide">
                    <label for="street_1" class="required"><em>*</em><?php echo $this->__('Street Address') ?></label>
                    <div class="input-box">
                        <input type="text" name="street[]" value="<?php echo $this->escapeHtml($this->getFormData()->getStreet(1)) ?>" title="<?php echo $this->__('Street Address') ?>" id="street_1" class="input-text <?php echo $_streetValidationClass ?>" />
                    </div>
                </li>
            <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
            <?php for ($_i = 2, $_n = $this->helper('customer/address')->getStreetLines(); $_i <= $_n; $_i++): ?>
                <li class="wide">
                    <div class="input-box">
                        <input type="text" name="street[]" value="<?php echo $this->escapeHtml($this->getFormData()->getStreet($_i)) ?>" title="<?php echo $this->__('Street Address %s', $_i) ?>" id="street_<?php echo $_i ?>" class="input-text <?php echo $_streetValidationClass ?>" />
                    </div>
                </li>
            <?php endfor; ?>
                <li class="fields">
                    <div class="field">
                        <label for="city" class="required"><em>*</em><?php echo $this->__('City') ?></label>
                        <div class="input-box">
                            <input type="text" name="city" value="<?php echo $this->escapeHtml($this->getFormData()->getCity()) ?>" title="<?php echo $this->__('City') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('city') ?>" id="city" />
                        </div>
                    </div>
                    <div class="field">
                        <label for="region_id" class="required"><em>*</em><?php echo $this->__('State/Province') ?></label>
                        <div class="input-box">
                            <select id="region_id" name="region_id" title="<?php echo $this->__('State/Province') ?>" class="validate-select" style="display:none;">
                                <option value=""><?php echo $this->__('Please select region, state or province') ?></option>
                            </select>
                            <script type="text/javascript">
                            //<![CDATA[
                                $('region_id').setAttribute('defaultValue', "<?php echo $this->getFormData()->getRegionId() ?>");
                            //]]>
                            </script>
                            <input type="text" id="region" name="region" value="<?php echo $this->escapeHtml($this->getRegion()) ?>" title="<?php echo $this->__('State/Province') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('region') ?>" style="display:none;" />
                        </div>
                    </div>
                </li>
                <li class="fields">
                    <div class="field">
                        <label for="zip" class="required"><em>*</em><?php echo $this->__('Zip/Postal Code') ?></label>
                        <div class="input-box">
                            <input type="text" name="postcode" value="<?php echo $this->escapeHtml($this->getFormData()->getPostcode()) ?>" title="<?php echo $this->__('Zip/Postal Code') ?>" id="zip" class="input-text validate-zip-international <?php echo $this->helper('customer/address')->getAttributeValidationClass('postcode') ?>" />
                        </div>
                    </div>
                    <div class="field">
                        <label for="country" class="required"><em>*</em><?php echo $this->__('Country') ?></label>
                        <div class="input-box">
                            <?php echo $this->getCountryHtmlSelect() ?>
                        </div>
                    </div>
                </li>
            </ul>
            <input type="hidden" name="default_billing" value="1" />
            <input type="hidden" name="default_shipping" value="1" />
        </div>
    <?php endif; ?>
        <div class="fieldset">
            <h2 class="legend"><?php echo $this->__('Login Information') ?></h2>
            <ul class="form-list">
                <li class="fields">
                    <div class="field">
                        <label for="password" class="required"><em>*</em><?php echo $this->__('Password') ?></label>
                        <div class="input-box">
                            <input type="password" name="password" id="password" title="<?php echo $this->__('Password') ?>" class="input-text required-entry validate-password" />
                        </div>
                    </div>
                    <div class="field">
                        <label for="confirmation" class="required"><em>*</em><?php echo $this->__('Confirm Password') ?></label>
                        <div class="input-box">
                            <input type="password" name="confirmation" title="<?php echo $this->__('Confirm Password') ?>" id="confirmation" class="input-text required-entry validate-cpassword" />
                        </div>
                    </div>
                </li>
                <?php echo $this->getChildHtml('form.additional.info'); ?>
                <?php echo $this->getChildHtml('persistent.remember.me'); ?>
            </ul>
            <?php echo $this->getChildHtml('persistent.remember.me.tooltip'); ?>
        </div>
        <div class="buttons-set">
            <p class="required"><?php echo $this->__('* Required Fields') ?></p>
            <p class="back-link"><a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>" class="back-link"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
            <button type="submit" title="<?php echo $this->__('Submit') ?>" class="button"><span><span><?php echo $this->__('Submit') ?></span></span></button>
        </div>
        <?php if (Mage::helper('checkout')->isContextCheckout()): ?>
            <input name="context" type="hidden" value="checkout" />
        <?php endif; ?>
    </form>
    <script type="text/javascript">
    //<![CDATA[
        var dataForm = new VarienForm('form-validate', true);
        <?php if($this->getShowAddressFields()): ?>
        new RegionUpdater('country', 'region', 'region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'zip');
        <?php endif; ?>
    //]]>
    </script>
</div>
*/ ?>
