<?php

/**
 * Licentia Fidelitas - Advanced Email and SMS Marketing Automation for E-Goi
 *
 * NOTICE OF LICENSE
 * This source file is subject to the Creative Commons Attribution-NonCommercial 4.0 International  
 * It is available through the world-wide-web at this URL:
 * http://creativecommons.org/licenses/by-nc/4.0/
 *
 * @title      Advanced Email and SMS Marketing Automation
 * @category   Marketing
 * @package    Licentia
 * @author     Bento Vilas Boas <bento@licentia.pt>
 * @copyright  Copyright (c) 2012 Licentia - http://licentia.pt
 * @license    Creative Commons Attribution-NonCommercial 4.0 International 
 */

?>

    <?php echo $this->getBlockHtml('formkey') ?>
    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend">
                <?php echo Mage::helper('fidelitas')->__('Products Added to Compare History') ?>
            </h4>
            <div class="form-buttons"></div>
        </div>
        <div class="fieldset">
            <div class="hor-scroll">
                <table cellspacing="0" class="form-list">
                    <tbody>
                        <?php echo $this->getFormObject()->getElement('compare')->toHtml() ?>
                        <?php echo $this->getFormObject()->getElement('compare_weight')->toHtml() ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend">
                <?php echo Mage::helper('fidelitas')->__('Products views History') ?>
            </h4>
            <div class="form-buttons"></div>
        </div>
        <div class="fieldset">
            <div class="hor-scroll">
                <table cellspacing="0" class="form-list">
                    <tbody>
                        <?php echo $this->getFormObject()->getElement('compare')->toHtml() ?>
                        <?php echo $this->getFormObject()->getElement('compare_weight')->toHtml() ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend">
                <?php echo Mage::helper('fidelitas')->__('Products Added to Wishlist History') ?>
            </h4>
            <div class="form-buttons"></div>
        </div>
        <div class="fieldset">
            <div class="hor-scroll">
                <table cellspacing="0" class="form-list">
                    <tbody>
                        <?php echo $this->getFormObject()->getElement('wishlist')->toHtml() ?>
                        <?php echo $this->getFormObject()->getElement('wishlist_weight')->toHtml() ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend">
                <?php echo Mage::helper('fidelitas')->__('Products Parent Categories History') ?>
            </h4>
            <div class="form-buttons"></div>
        </div>
        <div class="fieldset">
            <div class="hor-scroll">
                <table cellspacing="0" class="form-list">
                    <tbody>
                        <?php echo $this->getFormObject()->getElement('categories')->toHtml() ?>
                        <?php echo $this->getFormObject()->getElement('categories_weight')->toHtml() ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend">
                <?php echo Mage::helper('fidelitas')->__('Products Attributes History') ?>
            </h4>
            <div class="form-buttons"></div>
        </div>
        <div class="fieldset">
            <div class="hor-scroll">
                <table cellspacing="0" class="form-list">
                    <tbody>
                        <?php echo $this->getFormObject()->getElement('attributes')->toHtml() ?>
                        <?php echo $this->getFormObject()->getElement('attributes_weight')->toHtml() ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>