<div class="main-actions align-right col-lg-4 " style="padding-right: 0;">
	<form>
		<select name="attribute_set_id" id="attribute_set_id" class="form-control" data-base="<?php echo $this->getUrl("*/*/*");?>">
			<option value="" ><?php echo Mage::helper("zolagocatalog")->__("--- Select ---"); ?></option>
			<?php foreach($this->getAttributeSets() as $value=>$label):?>
				<option value="<?php echo $value;?>" <?php if($this->getCurrentAttributeSetId()==$value):?> selected="selected"<?php endif;?>><?php echo $this->escapeHtml($label);?></option>
			<?php endforeach;?>
		</select>
	</form>
</div>
