<?php /* @var $this Zolago_Catalog_Block_Vendor_Product_Grid*/?>

<div class="container" id="content-wrapper">

	<div id="grid-holder"></div>

</div>
<style type="text/css">
	#content{
		position: relative;
	}
	#grid-holder{
		position: absolute;
		height:auto;
		bottom:20px;
		left:20px;
		right:20px;
		top: 100px;
		background: #f3f3f3;
	}
	#grid-holder .filterable{
		width: 100px;
	}
	#grid-holder .dgrid-column-set-0{
		width: 300px;
	}
	#grid-holder  .dgrid-column-set-0 .dgrid-cell.field-name{
		width: 230px;
	}
	#grid-holder  .dgrid-column-set-0 .dgrid-cell.field-thumbnail{
		width: 45px;
	}
	#grid-holder .dgrid-column-set-0 .dgrid-cell.field-0-0-0{
		vertical-align: middle;
		width: 20px;
	}
	
	#grid-holder .dgrid-cell.type-multiselect,
	#grid-holder .dgrid-cell.type-options{
		text-align: center;
	}
	
	/** Thumb column **/
	#grid-holder  .dgrid-column-set-0 .dgrid-cell.field-thumbnail a{
		position: relative;
		display: block;
	}
	
	#grid-holder  .dgrid-column-set-0 .dgrid-cell.field-thumbnail span{
		position: absolute;
		bottom: 6px;
		right:1px;
		background: #666;
		line-height: 12px;
		font-size:10px;
		color: #fff;
		width: 12px;
		height: 12px;
		text-align: center;
	}
	
	/** Name column **/
	#grid-holder  .dgrid-column-set-0 .dgrid-cell.field-name p{
		margin:0;
		padding:0;
		overflow: hidden;
		text-overflow: ellipsis;
		white-space: nowrap;
	}
	#grid-holder  .dgrid-column-set-0 .dgrid-cell.field-name p.info{
		color: #666;
		font-size: 10px;
	}
</style>
<script type="text/javascript">
	require(['vendor/catalog/productGrid'], function(productGrid){
		productGrid.setColumns(<?php echo $this->getJsonColumns();?>);
		productGrid.startup("grid-holder");
	});
</script>