<?php
/** @var $this Zolago_Catalog_Block_Vendor_Product_Grid */
/** @var Zolago_Catalog_Helper_Data $helper */
$helper = Mage::helper("zolagocatalog");
?>
<div class="container" id="content-wrapper">
	<div id="grid-holder"></div>
</div>
<style type="text/css">
	#content{
		position: relative;
	}
	#grid-holder{
		position: absolute;
		/*height:auto;*/
		left:20px;
		top: 100px;
		bottom:20px;
		right:20px;
		background: #f3f3f3;
	}
    @media (max-width: 1060px) {
        #grid-holder {
            top: 115px;
        }
    }

	#grid-holder .dgrid-cell{
		vertical-align: middle;
	}
	#grid-holder td.dgrid-cell{
		  cursor: default;
	}
	#grid-holder td.dgrid-cell.dgrid-focus{
		 box-shadow: inset 0 0 5px rgba(0,0,0,0.4);
	}
	
	#grid-holder th.header.field-required::after{
		color: red;
		content: '*';
		margin-left: 4px;
	}
	#grid-holder .dgrid-spacer-row th.field-required::after,
	#grid-holder th.field-required.field-thumbnail::after{
		content: '';
		margin-left: 0;
	}
	#grid-holder td.editable{
		font-weight: normal;
		position: relative;
		cursor: pointer;
	}
	
	#grid-holder td.editable,
	#grid-holder td.field-thumbnail,
	#grid-holder td.dgrid-selector{
		cursor: pointer;
	}
	
	#grid-holder td.editable.dgrid-focus,
	#grid-holder td.field-thumbnail.dgrid-focus{
		 box-shadow: inset 0 0 10px #53AFFF;
	}
	
	#grid-holder .dgrid-selected td.editable.dgrid-focus,
	#grid-holder .dgrid-row:hover td.editable.dgrid-focus,
	#grid-holder .dgrid-selected td.field-thumbnail.dgrid-focus,
	#grid-holder .dgrid-row:hover td.field-thumbnail.dgrid-focus{
		 box-shadow: inset 0 0 10px #006dcc;
	}
	
	#grid-holder td.editable:active{
		cursor: default;
	}
	#grid-holder td.editable:empty::after{
		position: absolute;
		left:50%;
		top:50%;
		margin-top: -7px;
		margin-left: -7px;
		opacity: 0.4;
		letter-spacing: 2px;
		font-size: 10px;
		font-weight: normal;
		content: '...';
	}
	#grid-holder .filterable{
		width: 90px;
	}
	#grid-holder .dgrid-column-set-cell{
		padding:0;
	}
	#grid-holder .dgrid-column-set-1 tr .dgrid-cell{
		border-left: none;
	}
	#grid-holder .dgrid-column-set-0{
		width: 360px;
	}
	#grid-holder  .dgrid-column-set-0 .dgrid-cell.field-name{
		width: 230px;
	}
	#grid-holder  .dgrid-column-set-0 .dgrid-cell.field-thumbnail{
		width: <?php echo (int)$this->getThumbWidth();?>px;
	}
	#grid-holder .dgrid-column-set-0 .dgrid-cell.field-0-0-0{
		vertical-align: middle;
		width: 20px;
	}
	
	#grid-holder .dgrid-cell.type-multiselect,
	#grid-holder .dgrid-cell.type-options{
		text-align: center;
		width: 120px;
	}
	
	#grid-holder .dgrid-cell.type-price,
	#grid-holder .dgrid-cell.type-number{
		text-align: right;
	}
	
	#grid-holder  .dgrid-cell.type-text,
	#grid-holder  .dgrid-cell.type-textarea{
		overflow: hidden;
		text-overflow: ellipsis;
		white-space: nowrap;
	}
	#grid-holder td.dgrid-cell.field-thumbnail{
		position: relative;
		padding:0;
		border-left:0;
	}
	/** Thumb column **/
	#grid-holder td.dgrid-cell.field-thumbnail p,
	#grid-holder td.dgrid-cell.field-thumbnail a{
		position: relative;
		display: block;
		margin:0;
		padding:0;
	}
	#grid-holder td.dgrid-cell.field-thumbnail img{
		position: absolute;
		z-index: -1;
		display:block;
		margin-top: -30px;
		top: 50%;
		left:0;
	}
	
	#grid-holder td.dgrid-cell.field-thumbnail a,
	#grid-holder td.dgrid-cell.field-thumbnail p,
	#grid-holder td.dgrid-cell.field-thumbnail img{
		width: <?php echo (int)$this->getThumbWidth();?>px;
		height: <?php echo (int)$this->getThumbHeight();?>px;
	}
	
	
	#grid-holder td.dgrid-cell.field-thumbnail p{
		text-align: center;
		display: table-cell;
		vertical-align: middle;
		color: #CCC;
	}
	
	
	#grid-holder td.dgrid-cell.field-thumbnail span{
		position: absolute;
		bottom: 1px;
		right:1px;
		background: #666;
		line-height: 12px;
		font-size:10px;
		color: #fff;
		width: 12px;
		height: 12px;
		text-align: center;
	}
	
	/** Name column **/
	#grid-holder .dgrid-cell.field-name p{
		margin:0;
		padding:0;
		overflow: hidden;
		text-overflow: ellipsis;
		white-space: nowrap;
	}
	#grid-holder .dgrid-cell.field-name p.info{
		color: #666;
		font-size: 10px;
	}
	/** Status **/
	#grid-holder .dgrid-cell.field-status{
		width: 40px;
	}
	/** Total quantity - is in stock column **/
	#grid-holder .dgrid-cell.field-is_in_stock {
		width: 60px;
	}
	
	/** Editor definition **/
	
	#grid-holder .dgrid-editors{
		position: absolute;
		z-index: 100;
		top:0;
		bottom:0;
	}
	#grid-holder .editor{
		background: #fff;
		box-shadow: rgba(0,0,0,0.5) 0px 3px 5px;
		min-width: 200px;
		position: absolute;
		z-index: 200;
		padding: 15px;
	}
	#grid-holder a.close{
		position: absolute;
		top: 5px;
		right: 10px;
	}
	#grid-holder .editor h4,
	#grid-holder .editor form{
		margin:0;
		padding:0;
	}
	#grid-holder .editor h4{
		margin-bottom: 10px;
	}
	#grid-holder .editor .selection,
	#grid-holder .editor .save-as-rule{
		display: none;
	}
    #grid-holder .editor.editor-field-name {
        width: 400px;
    }
	#grid-holder .editor.use-selection .selection,
	#grid-holder .editor.use-save-as-rule .save-as-rule{
		display: block;
	}
	#grid-holder .editor textarea{
        width: 400px;
        height: 250px;
	}
	#grid-holder .editor select[multiple]{
		max-height: 90px;
	}
	#grid-holder .editor .close.disabled:hover{
		opacity: 0.2 !important;
		cursor: default !important;
	}
    #grid-holder .dgrid-column-set-0 .dgrid-cell.field-0-0-0 {
        cursor: pointer;
        text-align: center;
        color: #4d7496;
        font-weight: bold;
    }
    #grid-holder .header.field-required-highlight {
        background-color: #FFFFE2;

        background: -moz-linear-gradient(top, #FFFFE2 0%, #eeeeee 100%);
        background: -webkit-gradient(linear, left top, left bottom, color-stop(0%,#FFFFE2), color-stop(100%,#eeeeee));
        background: -webkit-linear-gradient(top, #FFFFE2 0%,#eeeeee 100%);
        background: -o-linear-gradient(top, #FFFFE2 0%,#eeeeee 100%);
        background: -ms-linear-gradient(top, #FFFFE2 0%,#eeeeee 100%);
        background: linear-gradient(top, #FFFFE2 0%,#eeeeee 100%);
    }
    #grid-holder .header.field-required-highlight:hover {
        background-color: #FFFFE2;

        background: -moz-linear-gradient(top, #FFFFEF 0%, #eeeeee 100%);
        background: -webkit-gradient(linear, left top, left bottom, color-stop(0%,#FFFFEF), color-stop(100%,#eeeeee));
        background: -webkit-linear-gradient(top, #FFFFEF 0%,#eeeeee 100%);
        background: -o-linear-gradient(top, #FFFFEF 0%,#eeeeee 100%);
        background: -ms-linear-gradient(top, #FFFFEF 0%,#eeeeee 100%);
        background: linear-gradient(top, #FFFFEF 0%,#eeeeee 100%);
    }
	
	/** Fix tooltip **/
	.tooltip-inner{
		max-width: 400px;
		font-size: 11px;
		text-align: left;
	}
	
	@media (max-width: 768px){
		#grid-holder{
			left:0px;
			right:0px;
		}
		
		#grid-holder .dgrid-column-set-0{
			width: 215px;
		}
		#grid-holder  .dgrid-column-set-0 .dgrid-cell.field-name{
			width: 130px;
		}
	}
	
	@media (max-width: 480px){
		#grid-holder{
			top: 120px;
		}
		.page-header .page-title{
			float: left;
		}
	}
</style>

<script type="text/javascript" src="<?php echo $this->getSkinUrl("js/rwd.carousel/rwd.carousel.js"); ?>"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl("js/modernizr.custom.js"); ?>"></script>

<script type="text/javascript">
	require(['vendor/catalog/productGrid'], function(productGrid) {
		productGrid.setColumns(<?php echo $this->getJsonColumns();?>);
        window.productGrid = productGrid.startup("grid-holder");
        var modal = jQuery("#product-image-popup");
        modal.keydown(function(e) {
            var car = jQuery('#product-image-popup .carousel');
            switch(e.keyCode) {
                case 39:
                    car.trigger('rwd.next');
                    break;                        
                case 37:
                    car.trigger('rwd.prev');
                    break;
            }
        });
	});
</script>

<div id="product-image-popup" class="modal ui-draggable in" role="dialog" aria-hidden="false">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal">
					<span aria-hidden="true">×</span>
					<span class="sr-only">Close</span>
				</button>
				<h4 class="modal-title"></h4>
			</div>
			<div class="modal-body"></div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal"><?php echo $helper->__("Close"); ?></button>
			</div>
		</div>
	</div>
</div>
