<?php /* @var $this Zolago_Catalog_Block_Vendor_Product_Grid*/?>

<div class="container" id="content-wrapper">
	<div id="grid-holder"></div>
</div>
<style type="text/css">
	#content{
		position: relative;
	}
	#grid-holder{
		position: absolute;
		height:auto;
		left:20px;
		top: 100px;
		bottom:20px;
		right:20px;
		background: #f3f3f3;
	}
	#grid-holder .dgrid-cell{
		vertical-align: middle;
	}
	#grid-holder th.header.field-required::after{
		color: red;
		content: '*';
		margin-left: 4px;
	}
	#grid-holder .dgrid-spacer-row th.field-required::after,
	#grid-holder th.field-required.field-thumbnail::after{
		content: '';
		margin-left: 0;
	}
	#grid-holder .filterable{
		width: 90px;
	}
	#grid-holder .dgrid-column-set-cell{
		padding:0;
	}
	#grid-holder .dgrid-column-set-1 tr .dgrid-cell{
		border-left: none;
	}
	#grid-holder .dgrid-column-set-0{
		width: 315px;
	}
	#grid-holder  .dgrid-column-set-0 .dgrid-cell.field-name{
		width: 230px;
	}
	#grid-holder  .dgrid-column-set-0 .dgrid-cell.field-thumbnail{
		width: <?php echo (int)$this->getThumbWidth();?>px;
	}
	#grid-holder .dgrid-column-set-0 .dgrid-cell.field-0-0-0{
		vertical-align: middle;
		width: 20px;
	}
	
	#grid-holder .dgrid-cell.type-multiselect,
	#grid-holder .dgrid-cell.type-options{
		text-align: center;
		width: 120px;
	}
	
	#grid-holder .dgrid-cell.type-price,
	#grid-holder .dgrid-cell.type-number{
		text-align: right;
	}
	
	#grid-holder  .dgrid-cell.type-text{
		overflow: hidden;
		text-overflow: ellipsis;
		white-space: nowrap;
	}
	#grid-holder td.dgrid-cell.field-thumbnail{
		padding:0;
	}
	/** Thumb column **/
	#grid-holder td.dgrid-cell.field-thumbnail p,
	#grid-holder td.dgrid-cell.field-thumbnail a{
		position: relative;
		display: block;
		margin:0;
		padding:0;
	}
	
	#grid-holder td.dgrid-cell.field-thumbnail a,
	#grid-holder td.dgrid-cell.field-thumbnail p,
	#grid-holder td.dgrid-cell.field-thumbnail img{
		width: <?php echo (int)$this->getThumbWidth();?>px;
		height: <?php echo (int)$this->getThumbHeight();?>px;
	}
	
	
	#grid-holder td.dgrid-cell.field-thumbnail p{
		text-align: center;
		display: table-cell;
		vertical-align: middle;
		color: #CCC;
	}
	
	
	#grid-holder td.dgrid-cell.field-thumbnail span{
		position: absolute;
		bottom: 1px;
		right:1px;
		background: #666;
		line-height: 12px;
		font-size:10px;
		color: #fff;
		width: 12px;
		height: 12px;
		text-align: center;
	}
	
	/** Name column **/
	#grid-holder .dgrid-cell.field-name p{
		margin:0;
		padding:0;
		overflow: hidden;
		text-overflow: ellipsis;
		white-space: nowrap;
	}
	#grid-holder .dgrid-cell.field-name p.info{
		color: #666;
		font-size: 10px;
	}
	/** Status **/
	#grid-holder .dgrid-cell.field-status{
		width: 40px;
	}
	#grid-holder td.dgrid-cell.field-status::after{
		content: "";
		display: inline-block;
		width:0;
		height:0;
		border-radius:5px;
		border: 5px green solid;
	}
	#grid-holder td.dgrid-cell.field-status.status-off::after{
		border-color: red;
	}
	#grid-holder td.dgrid-cell.field-status.status-wait::after{
		border-color: orange;
	}
	
	@media (max-width: 768px){
		#grid-holder{
			left:0px;
			right:0px;
		}
		
		#grid-holder .dgrid-column-set-0{
			width: 215px;
		}
		#grid-holder  .dgrid-column-set-0 .dgrid-cell.field-name{
			width: 130px;
		}
	}
	
	@media (max-width: 480px){
		#grid-holder{
			top: 120px;
		}
		.page-header .page-title{
			float: left;
		}
	}
</style>
<script type="text/javascript">
	require(['vendor/catalog/productGrid'], function(productGrid){
		productGrid.setColumns(<?php echo $this->getJsonColumns();?>);
		productGrid.startup("grid-holder");
	});
</script>