<div class="col-lg-4 main-actions ">
	<label><?php echo Mage::helper("zolagocatalog")->__("Selected");?>: </label>
	<button class="btn" disabled="disabled" id="disable-products">
		<i class="icon icon-off"></i> 
		<?php echo Mage::helper("zolagocatalog")->__("Disable products");?>
	</button>
	<button class="btn" disabled="disabled" id="confirm-products">
		<i class="icon icon-check"></i> 
		<?php echo Mage::helper("zolagocatalog")->__("Confirm products");?>
	</button>
</div>