<?php
/** @var $this Mage_Core_Block_Template */
?>
<div class="col-xs-4 main-actions">
	<?php if($this->getParentBlock()->getCanShowGrid()):?>
	<div style="position: relative;">
	<button class="btn btn-default dropdown-toggle" type="button" disabled="disabled" id="massActions" data-toggle="dropdown" aria-expanded="true">
		<?php echo $this->__("Selected"); ?>
		<span class="caret"></span>
	</button>
	<ul class="dropdown-menu" role="menu" aria-labelledby="massActions">
		<li role="presentation">
			<a role="menuitem" tabindex="-1" href="#" id="massConfirmProducts">
				<i class="icon icon-check"></i> 
				<?php echo Mage::helper("zolagocatalog")->__("Accept description"); ?>
			</a>
		</li>
        <li role="presentation">
            <a role="menuitem" tabindex="-1" href="#" id="massAttributeRules">
                <i class="icon icon-puzzle-piece"></i>
                <?php echo Mage::helper("gh_attributerules")->__("Apply rules");?>
            </a>
        </li>
		<li role="presentation">
			<a role="menuitem" tabindex="-1" href="#"  data-toggle="modal" data-target="#massChangeAttributeSet">
				<i class="glyphicon glyphicon-send"></i>
				<?php echo Mage::helper("zolagocatalog")->__("Move to other category");?>
			</a>
		</li>
	</ul>
	</div>
	<?php endif;?>
</div>
