<div class="content-header">
	<table cellspacing="0">
		<tbody>
			<tr>
				<td style="width:50%;">
					<h3 class="icon-head head-backups-control"><?php echo $this->__("Process queue");?></h3>
				</td>
				<td class="a-right">
					<button title="Dodaj produkt" type="button" class="scalable" onclick="setLocation('<?php echo $this->getUrl("*/*/processQueue");?>')"><span><span><span><?php echo $this->__("Start processing");?></span></span></span></button>       
				</td>
			</tr>
		</tbody>
	</table>
</div>
<div>
	<p><?php echo $this->__("To start processing queue click the button");?></p>
</div>