<?php /* @var $this Zolago_Modago_Block_Sales_Order_View */ ?>
<?php $_helper = Mage::helper("zolagosales");?>
<?php $baseUrl = Mage::helper("core/url")->getHomeUrl(); ?>
<?php $_order = $this->getOrder();?>
<?php $_hasPo = $this->getHasAnyPo(); ?>
<?php $_grandTotal = $this->getGrandTotal();?>

<?php
$request = Mage::app()->getRequest();
$customerAccountPage = false;
if ($request->getRouteName() == "customer" && $request->getControllerName() == "account" && $request->getActionName() == "index") {
    $customerAccountPage = true;
}
?>
<section class="main bg-w  <?php if($customerAccountPage): ?> hidden-xs <?php endif; ?>">
	<header class="title-section">
		<div class="headerTop">
			<div class="table-row clearfix" id="order_header">
				<div class="pull-left">
					<h2>
					<?php echo $_helper->__("Order number");?>:
					<?php echo $_order->getIncrementId();?>
					</h2>
				</div>
				<div class="order-date hidden-xs">
					<?php echo $_helper->__('Order date') ?>:
					<?php echo $_helper->formatDate($_order->getCreatedAt());?>
				</div>
			</div>
		</div>
		<?php if($_hasPo):?>
		<p class="visible-xs">
			<?php echo $_helper->__('Order date') ?>:
			<?php echo $_helper->formatDate($_order->getCreatedAt());?>
<!--		<p>-->
<!--			--><?php //echo $_helper->__('Total order value')?><!--:-->
<!--			--><?php //echo Mage::helper('core')->formatPrice($_grandTotal);?>
<!--		</p>-->
		<p>
			<?php echo $_helper->__('Payment');?>:
			<?php echo $this->getPaymentHtml();?>
		</p>
		<?php endif;?>
	</header>
	<?php if($_hasPo):?>
		<?php $total = 1; ?>
		<?php $_items = $this->getItems();?>
		<?php $_itemsCount = $_items->getSize();?>
		<?php foreach ($this->getItems() as $nr => $_item) : ?>
		<?php /* @var $_item Zolago_Po_Model_Po */ ?>
		<?php $_shipment = $_item->getLastNotCanceledShipment();?>
		<div class="panel panel-default no-border-top order-view-mobile">
			<div class="tableWrapper">
				<div class="table-row clearfix panel-header vendor-header">
					<?php $_v = $_item->getVendor(); ?>
						<div class="panel-heading pull-left col-sm-6 col-xs-12">
							<?php printf($this->__('Shipment %d of %d'), ($total++), count($_items)); ?>
							<a class="small underline visible-xs contact-vendor" href="#"
							   data-order-id="<?php echo $_item->getId();?>" data-vendor-id="<?php echo $_v->getId();?>"
							   data-vendor-name="<?php echo $this->escapeHtml($_v->getVendorName());?>"
							   <?php if($_shipment):?>data-shipment-id="<?php echo $_shipment->getId();?>"<?php endif;?>>
								   <?php echo $_helper->__("Ask question about order"); ?>
							</a>
						</div>
						<div class="pull-right panel-heading col-sm-6 col-xs-12 hidden-xs">
							<a class="small underline pull-right rght-margin-30 contact-vendor" href="#"
							   data-order-id="<?php echo $_item->getId();?>" data-vendor-id="<?php echo $_v->getId();?>"
							   data-vendor-name="<?php echo $this->escapeHtml($_v->getVendorName());?>"
							   <?php if($_shipment):?>data-shipment-id="<?php echo $_shipment->getId();?>"<?php endif;?>>
								<?php echo $_helper->__("Ask question about order"); ?>
							</a>
						</div>
					</div>
				</div>
				<div class="panel-body visible-xs panel-contact-vendor">
					<div id="contact-vendor-<?php echo $_v->getId();?>-<?php echo $_item->getId();?>"></div>
				</div>
				<?php $_shipmentHtml = $this->getShipmentBlock($_item);?>

				<div class="panel-body visible-xs">
					<div class="table-row clearfix sales-order-top-row">
						<?php echo $_shipmentHtml; ?>
					</div>
				</div>

				<div class="panel-body visible-xs mobile-toggler">
					<a href="#" class="small underline" data-open="<?php echo $this->__("Hide details");?>" data-close="<?php echo $this->__("Show details");?>">
						<span><?php echo $this->__("Show details");?></span>
						<i class="fa fa-chevron-down"></i>
					</a>
				</div>

				<div class="panel-body hidden-xs mobile-toggle">
					<div class="table-row clearfix sales-order-top-row">
						<div class="hidden-xs"><?php echo $_shipmentHtml; ?></div>
						<?php echo $this->getInfoBlock($_item); ?>
					</div>
					<div class="tableWrapper table-cart">
						<!-- Thead -->
						<?php foreach ($_item->getAllItems() as $_product) : ?>
							<?php if (!$_product->getOrderItem()->getParentItemId()): ?>
								<?php echo $this->getItemHtml($_product); ?>
							<?php endif; ?>
						<?php endforeach; ?>
						<!-- TFoot -->
						<div class="table-footer-group hidden-xs">
							<div class="table-row clearfix">
								<div class="table-cell cell-01 td">
								</div>

								<div class="table-cell cell-03 label_value td">
									<div class="value_quality_delivery">
										<?php echo $_helper->__("Shipping cost"); ?>:

									</div>
									<div class="value_quality_price"><?php echo $_helper->__('Sum:') ?></div>
								</div>
								<div class="table-cell cell-04 td">
									<div class="quality_delivery"><?php echo Mage::helper('core')->formatPrice($_item->getData('shipping_amount_incl')); ?></div>
									<div class="quality_price"><?php echo Mage::helper('core')->formatPrice($_item->getData('grand_total_incl_tax')) ?></div>
								</div>
								<div class="table-cell cell-05 td"></div>
							</div>

						</div>
						<!-- TFoot mobile-->
						<div class="table-footer-group visible-xs">
							<div class="table-row clearfix">
								<div class="table-cell cell-01 td">
								</div>
								<div class="table-cell cell-03 label_value td">
									<div class="value_quality_price"><?php echo $_helper->__("Sum:"); ?></div>
									<div class="value_quality_delivery"><?php echo $_helper->__("Shipping cost"); ?>:</div>
								</div>
								<div class="table-cell cell-04 td">
									<div class="quality_price"><?php echo Mage::helper('core')->formatPrice($_item->getData('grand_total_incl_tax')) ?></div>
									<div class="quality_delivery"><?php echo Mage::helper('core')->formatPrice($_item->getData('shipping_amount_incl')); ?></div>
								</div>
								<div class="table-cell cell-05 td">
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		<?php endforeach; ?>
	<?php else:?>
		<p class="alert alert-info has-no-po">
			<?php echo $_helper->__('Your order should be visible in few minutes. Pleas visit site again later.');?>
		</p>
	<?php endif;?>
</section>