<div class="container hidden-xs">
    <div id="carousel-top-generic" class="carousel slide border1px-rd2-img-gray" data-ride="carousel">
        <!-- Indicators -->
        <ol class="carousel-indicators" id="carousel-top-indicators">
            <li data-target="#carousel-top-generic" data-slide-to="0" class="active"></li>
            <li data-target="#carousel-top-generic" data-slide-to="1"></li>
        </ol>

        <!-- Wrapper for slides -->
        <div class="carousel-inner">
            <div class="item active">
                <img src="<?php echo $this->getSkinUrl('images/banner1.jpg'); ?>" alt="">
                <div class="carousel-caption">
                    <a href=""><?php echo $this->__("browse stylisation"); ?><img src="<?php echo $this->getSkinUrl('images/ico-green-arrow-small.png'); ?>" alt=""/></a>
                    <a class="margin-top-20px" href=""><?php echo $this->__("enter the shop"); ?><img src="<?php echo $this->getSkinUrl('images/ico-green-arrow-small.png'); ?>" alt=""/></a>
                </div>
            </div>
            <div class="item">
                <img src="<?php echo $this->getSkinUrl('images/banner1.jpg'); ?>" alt="">
                <div class="carousel-caption">
                    <a href=""><?php echo $this->__("browse stylisation"); ?><img src="<?php echo $this->getSkinUrl('images/ico-green-arrow-small.png'); ?>" alt=""/></a>
                    <a class="margin-top-20px" href=""><?php echo $this->__("enter the shop"); ?><img src="<?php echo $this->getSkinUrl('images/ico-green-arrow-small.png'); ?>" alt=""/></a>
                </div>
            </div>
        </div>

    </div>
</div>

<div class="container visible-xs">
    <div class="row">
        <div class="col-xs-12">

            <div id="carousel-top-mobile-generic" class="carousel slide" data-ride="carousel">
                <!-- Indicators -->
                <ol class="carousel-indicators" id="carousel-top-mobile-indicators">
                    <li data-target="#carousel-top-mobile-generic" data-slide-to="0" class="active"></li>
                    <li data-target="#carousel-top-mobile-generic" data-slide-to="1"></li>
                </ol>

                <!-- Wrapper for slides -->
                <div class="carousel-inner">
                    <div class="item active">
                        <img class="border1px-rd2-img-gray" src="<?php echo $this->getSkinUrl('images/bannermobile1.jpg'); ?>" alt="">
                        <div class="carousel-caption">
                        </div>
                    </div>
                    <div class="item">
                        <img class="border1px-rd2-img-gray" src="<?php echo $this->getSkinUrl('images/bannermobile1.jpg'); ?>" alt="">
                        <div class="carousel-caption">
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>