<?php
/**
 * Author: Paweł Chyl <pawel.chyl@orba.pl>
 * Date: 25.04.14
 */
?>
<!--inspiracje-->
<div class="white-wrapper border1px-rd2-img-gray noborder-lft-rgt">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="inspiration-strips"></div>
                <h2 class="insp-h"><?php echo $this->__("inspirations"); ?></h2>
            </div>
        </div>

        <div class="jcarousel-wrapper listComics">
            <div class="canvas-left"></div>
            <div class="jcarousel">
                <ul>
                    <li class="col-sm-3">
                        <a href="#" class="productItem-wrapper">
                            <img src="<?php echo $this->getSkinUrl('images/insp-1.jpg'); ?>" alt="...">
                            <span class="insp-carousel-title-bold">lady in the bushes</span>
                            <span class="insp-carousel-title-gray">Drugi wiersz opisu</span>
                            <span class="insp-carousel-seemore"><?php echo $this->__("see"); ?> &gt;</span>
                        </a>
                    </li>
                    <li class="col-sm-3">
                        <a href="#" class="productItem-wrapper">
                            <img src="<?php echo $this->getSkinUrl('images/insp-2.jpg'); ?>" alt="...">

                            <span class="insp-carousel-title-bold">lady in the bushes</span>
                            <span class="insp-carousel-title-gray">Drugi wiersz opisu</span>
                            <span class="insp-carousel-seemore"><?php echo $this->__("see"); ?> &gt;</span>
                        </a>
                    </li>
                    <li class="col-sm-3">
                        <a href="#" class="productItem-wrapper" data-json="c_01">

                            <img src="<?php echo $this->getSkinUrl('images/insp-3.jpg'); ?>" alt="...">
                            <span class="insp-carousel-title-bold">lady in the bushes</span>
                            <span class="insp-carousel-title-gray">Drugi wiersz opisu</span>
                            <span class="insp-carousel-seemore"><?php echo $this->__("see"); ?> &gt;</span>
                        </a>
                    </li>
                    <li class="col-sm-3">
                        <a href="#" class="productItem-wrapper" data-json="c_02">

                            <img src="<?php echo $this->getSkinUrl('images/insp-1.jpg'); ?>" alt="...">
                            <span class="insp-carousel-title-bold">lady in the bushes</span>
                            <span class="insp-carousel-title-gray">Drugi wiersz opisu</span>
                            <span class="insp-carousel-seemore"><?php echo $this->__("see"); ?> &gt;</span>
                        </a>
                    </li>
                    <li class="col-sm-3">
                        <a href="#" class="productItem-wrapper">

                            <img src="<?php echo $this->getSkinUrl('images/insp-1.jpg'); ?>" alt="...">
                            <span class="insp-carousel-title-bold">lady in the bushes</span>
                            <span class="insp-carousel-title-gray">Drugi wiersz opisu</span>
                            <span class="insp-carousel-seemore"><?php echo $this->__("see"); ?> &gt;</span>
                        </a>
                    </li>
                    <li class="col-sm-3">
                        <a href="#" class="productItem-wrapper">

                            <img src="<?php echo $this->getSkinUrl('images/insp-1.jpg'); ?>" alt="...">
                            <span class="insp-carousel-title-bold">lady in the bushes</span>
                            <span class="insp-carousel-title-gray">Drugi wiersz opisu</span>
                            <span class="insp-carousel-seemore"><?php echo $this->__("see"); ?> &gt;</span>
                        </a>
                    </li>
                    <li class="col-sm-3">
                        <a href="#" class="productItem-wrapper">

                            <img src="<?php echo $this->getSkinUrl('images/insp-1.jpg'); ?>" alt="...">
                            <span class="insp-carousel-title-bold">lady in the bushes</span>
                            <span class="insp-carousel-title-gray">Drugi wiersz opisu</span>
                            <span class="insp-carousel-seemore"><?php echo $this->__("see"); ?> &gt;</span>
                        </a>
                    </li>
                    <li class="col-sm-3">
                        <a href="#" class="productItem-wrapper">

                            <img src="<?php echo $this->getSkinUrl('images/insp-1.jpg'); ?>" alt="...">
                            <span class="insp-carousel-title-bold">lady in the bushes</span>
                            <span class="insp-carousel-title-gray">Drugi wiersz opisu</span>
                            <span class="insp-carousel-seemore"><?php echo $this->__("see"); ?> &gt;</span>
                        </a>
                    </li>
                </ul>
            </div>

            <a href="#" class="jcarousel-control-prev"></a>
            <a href="#" class="jcarousel-control-next"></a>

            <div class="canvas-right"></div>
        </div>

    </div>
</div>
