
<!--small banners-->
<div class="container ">
    <div class="row hidden-xs visible-lg visible-md visible-sm small-banners-lg">
        <div class="col-lg-3 col-md-3 col-sm-3">
            <a href=""><img class="border1px-rd2-img-gray margin-10-top img-responsive" width="100%" src="<?php echo $this->getSkinUrl('images/banner-small-1.jpg'); ?>" alt=""/></a>
        </div>
        <div class="col-lg-3 col-md-3 col-sm-3">
            <a href=""><img class="border1px-rd2-img-gray margin-10-top img-responsive" width="100%" src="<?php echo $this->getSkinUrl('images/banner-small-2.jpg'); ?>" alt=""/></a>
        </div>
        <div class="col-lg-3 col-md-3 col-sm-3">
            <a href=""><img class="border1px-rd2-img-gray margin-10-top img-responsive" width="100%" src="<?php echo $this->getSkinUrl('images/banner-small-3.jpg'); ?>" alt=""/></a>
        </div>
        <div class="col-lg-3 col-md-3 col-sm-3">
            <a href=""><img class="border1px-rd2-img-gray margin-10-top img-responsive" width="100%" src="<?php echo $this->getSkinUrl('images/banner-small-4.jpg'); ?>" alt=""/></a>
        </div>
    </div>
    <div class="row visible-xs">
        <div class="col-xs-6 col-sm-6 col-md-6">
            <a href=""><img class="border1px-rd2-img-gray margin-10-top img-responsive" width="100%" src="<?php echo $this->getSkinUrl('images/banner-small-1.jpg'); ?>" alt=""/></a>
        </div>
        <div class="col-xs-6 col-sm-6 col-md-6">
            <a href=""><img class="border1px-rd2-img-gray margin-10-top img-responsive" width="100%" src="<?php echo $this->getSkinUrl('images/banner-small-2.jpg'); ?>" alt=""/></a>
        </div>
    </div>
    <div class="row visible-xs hidden-md hidden-sm">
        <div class="col-xs-6 col-sm-6 col-md-6">
            <a href=""><img class="border1px-rd2-img-gray margin-10-top img-responsive" width="100%" src="<?php echo $this->getSkinUrl('images/banner-small-3.jpg'); ?>" alt=""/></a>
        </div>
        <div class="col-xs-6 col-sm-6 col-md-6">
            <a href=""><img class="border1px-rd2-img-gray margin-10-top img-responsive" width="100%" src="<?php echo $this->getSkinUrl('images/banner-small-4.jpg'); ?>" alt=""/></a>
        </div>
    </div>
</div>