<?php /* images should be 64x64px */ ?>
<?php /*
<div class="benefits">
	<div class="benefit-item">
	    <div class="benefit-text" style="background-image: url('/skin/frontend/modago/vissavi/images/svg/benefits_transport.svg')">
	        <h3>Darmowa dostawa</h3>
	        <p>na&nbsp;wszysktie&nbsp;produkty</p>
	    </div>
	</div>
	<div class="benefit-item">
	    <div class="benefit-text" style="background-image: url('/skin/frontend/modago/vissavi/images/svg/about_delivery_quick.svg')">
	        <h3>Szybka wysyłka</h3>
	        <p>w ciągu 24h</p>
	    </div>
	</div>
	<div class="benefit-item">
	    <div class="benefit-text" style="background-image: url('/skin/frontend/modago/vissavi/images/svg/benefits_return.svg')">
	        <h3>Darmowy zwrot</h3>
	        <p>w&nbsp;ciągu 14&nbsp;dni</p>
	    </div>
	</div>
	<div class="benefit-item">
	    <div class="benefit-text" style="background-image: url('/skin/frontend/modago/vissavi/images/svg/about_promotions.svg')">
	        <h3>Specjalne rabaty</h3>
	        <p>
		        <a href="#">dla&nbsp;klientów&nbsp;e-sklepu</a>
	        </p>
	    </div>
	</div>
</div>
*/ ?>
