<!-- PRODUCT SHOP -->
<?php
/** @var Zolago_Modago_Block_Catalog_Product_View_Shop $this */

/** @var Zolago_Catalog_Model_Product $_product */
$_product = $this->getProduct();
$currencyCode = Mage::app()->getStore()->getCurrentCurrencyCode();
$currencySymbol = Mage::app()->getLocale()->currency($currencyCode)->getSymbol();

/** @var Mage_Catalog_Helper_Output $_helper */
$_helper = $this->helper('catalog/output');

/** @var Zolago_Catalog_Helper_Data $hlp */
$hlp = Mage::helper('catalog');

/** @var Zolago_Catalog_Helper_Product $productHelper */
$productHelper = Mage::helper("zolagocatalog/product");

$isSalable = $_product->isSalable(); //product is salable
// prices
$price = $_product->getPrice();
$finalPrice = $_product->getFinalPrice();
$sizeAttr = $_product->getResource()->getAttribute('size');
$productAttrs = array();
if ($_product->getTypeId() == 'configurable') {
	$productAttrs = $_product->getTypeInstance(true)->getConfigurableAttributesAsArray($_product);
}


$_helperSizetable = Mage::helper('zolagosizetable');
/** @var Zolago_Sizetable_Helper_Data $_helperSizetable */
$vendor_id = $_product->getData('udropship_vendor');
$storeId = Mage::app()->getStore()->getStoreId();
$attributeSetId = $_product->getData('attribute_set_id');
$brandId = $_product->getData('manufacturer');
if ($_product->getTypeId() == 'configurable') { //fix for simple products
	/** @var Zolago_Catalog_Block_Product_View_Type_Configurable $salableCount */
	$salableCount = Mage::getBlockSingleton('zolagocatalog/product_view_type_configurable')->getSalableCount();
}
$sizeTableValue = '1';//$_helperSizetable->getSizetableCMS($vendor_id, $storeId, $attributeSetId, $brandId);
$deliveryHeadline = trim($this->getStoreDeliveryHeadline());
$returnHeadline = trim($this->getStoreReturnHeadline());
$reviewsAvg = $this->getReviewsAvg();
$reviewsCount = $this->getReviewsCount();
$reviewsLabel = $this->getReviewsLabel();


$inventory = Mage::getModel('cataloginventory/stock_item')->loadByProduct($_product);

$maxQty = (int)$inventory->getQty();
$minQty = (int)$inventory->getMinSaleQty();

if(!!$inventory->getBackorders()){
	$maxQty = (int)$inventory->getMaxSaleQty();
}

?>


<?php

$productName = $_helper->productAttribute($_product, $_product->getName(), 'name');
?>
<!-- PRODUCT NAME -->
<div id="product-name" class="col-md-12 product-name" style="overflow-x:visible;">
	<h1 itemprop="name"><?php echo $productName; ?></h1>
	<meta itemprop="sku" content="<?php echo $_product->getSku() ?>"/>
	<div id="average_rating" data-number="5" data-score="<?php echo $reviewsAvg; ?>"></div>
	<div class="review_count">(<?php echo $reviewsLabel; ?>: <?php echo $reviewsCount; ?>)</div>
</div>
<!-- /PRODUCT NAME -->
<!-- SHORT DESCRIPTION -->
<div class="col-md-12" id="short-description-block">
	<div id="short-description" class="row">
		<?php echo $_helper->productAttribute($_product, nl2br($_product->getShortDescription()), 'short_description') ?>
	</div>
	<div id="product_price_box" class="row">
		<div id="product-price" class="col-lg-7 col-md-7 col-sm-7 col-xs-7">
			<?php if ($_product->getCanShowPrice() !== false): ?>
				<div class="price-box-bundle">
					<div class="price-box row">
						<p class="price-box-line" itemprop="offers" itemscope itemtype="http://schema.org/Offer">
							<?php if ($_product->getTypeId() == Mage_Catalog_Model_Product_Type::TYPE_CONFIGURABLE): ?>
								<meta itemprop="price" content="<?php echo round($_product->getFinalPrice(), 2); ?>"/>
							<?php endif; ?>

							<meta itemprop="priceCurrency" content="<?php echo $currencyCode; ?>"/>
							<meta itemprop="mpn" content="<?php echo $_product->getSku(); ?>"/>

							<?php if ($isSalable): ?>
								<meta itemprop="availability" content="http://schema.org/InStock"/>
							<?php else: ?>
								<meta itemprop="availability" content="http://schema.org/OutOfStock"/>
							<?php endif; ?>

							<meta itemprop="itemCondition" itemtype="http://schema.org/OfferItemCondition" content="http://schema.org/NewCondition"/>
							<span class="old-price"><?php if($_product->getTypeId() != Mage_Catalog_Model_Product_Type::TYPE_CONFIGURABLE && !$_product->getTypeId() == Mage_Catalog_Model_Product_Type::TYPE_BUNDLE &&  $_product->getStrikeoutPrice() != $_product->getFinalPrice()) : ?><?php echo str_replace(" ","&nbsp;",Mage::helper('core')->currency($_product->getStrikeoutPrice(), true, false)); ?><?php endif; ?></span>
                            <span class="price">
                                <?php if (
									$_product->getTypeId() != Mage_Catalog_Model_Product_Type::TYPE_CONFIGURABLE
									&& $_product->getTypeId() !== Mage_Catalog_Model_Product_Type::TYPE_BUNDLE): ?>
									<span itemprop="price">
                                        <?php echo number_format($_product->getFinalPrice(), 2, ',', ' '); ?>
                                    </span>
									<?php echo $currencySymbol; ?>
								<?php endif; ?>
                            </span>


							<?php if ($_product->getTypeId() == Mage_Catalog_Model_Product_Type::TYPE_BUNDLE) : ?>
								<?php echo $this->getChildHtml('product_type_data') ?>
							<?php endif; ?>
						</p>
					</div>
				</div>
			<?php endif; ?>
		</div>
		<div id="delivery-and-return" class="col-lg-5 col-md-5 col-sm-5 col-xs-12">
			<div>
				<?php if($deliveryHeadline): ?>
					<?php echo $deliveryHeadline; ?> <i class="fa fa-truck fa-lg fa-flip-horizontal"></i>
				<?php endif; ?>
			</div>
			<div>
				<?php if($returnHeadline): ?>
					<?php echo $returnHeadline; ?>
				<?php endif; ?>
			</div>
		</div>
	</div>

	<?php if ($_product->getTypeId() == Mage_Catalog_Model_Product_Type::TYPE_CONFIGURABLE) : ?>
		<!--    Meta tags-->
		<?php
		$childrenData = array();
		$childProducts = Mage::getModel('catalog/product_type_configurable')
			->getUsedProducts(null, $_product);
		foreach ($childProducts as $child) {
			$childrenData[$child->getId()] = $child->getSku();
		}

		$productViewTypeConfigurableBlock = Mage::getBlockSingleton('zolagocatalog/product_view_type_configurable');
		$config = $productViewTypeConfigurableBlock->getConfig();
		$basePrice = $config['basePrice'];
		if (isset($config['attributes']) & !empty($config['attributes'])):
			$attributes = $config['attributes'];
			foreach ($attributes as $attributeId => $attributeData):
				if ($attributeData['code'] == "size" && (isset($attributeData['options']) & !empty($attributeData['options']))):
					$options = $attributeData['options'];
					foreach ($options as $option):
						?>
						<span itemprop="offers" itemscope itemtype="http://schema.org/Offer">
                                        <meta itemprop="price" content="<?php echo round(($_product->getFinalPrice() + $option['price']), 2); ?>"/>
                                        <meta itemprop="priceCurrency" content="<?php echo $currencyCode; ?>"/>
                                        <meta itemprop="mpn" content="<?php echo $childrenData[$option['products'][0]]; ?>"/>
							<?php if ($option['is_salable']): ?>
								<meta itemprop="availability" content="http://schema.org/InStock"/>
							<?php else: ?>
								<meta itemprop="availability" content="http://schema.org/OutOfStock"/>
							<?php endif; ?>
							<meta itemprop="itemCondition" itemtype="http://schema.org/OfferItemCondition"
								  content="http://schema.org/NewCondition"/>
                                    </span>
						<?php
					endforeach;
				endif;
			endforeach;
		endif;
		?>
		<!--    Meta tags-->
	<?php endif; ?>
	<!--        catalog.product.related-->
	<?php echo $this->getChildHtml('catalog.product.related'); ?>
	<!--        catalog.product.related end-->

	<div id="product-options" class="size-box-bundle">
		<div class="block_to_size">
			<?php if ($_product->getTypeId() == Mage_Catalog_Model_Product_Type::TYPE_CONFIGURABLE) : ?>
				<?php if (!empty($productAttrs)) : ?>
					<?php foreach ($productAttrs as $_attribute) : ?>
						<?php if (array_key_exists('attribute_code', $_attribute) && $_attribute['attribute_code'] == 'size') : ?>
							<?php $haveSizes = true; ?>
							<div class="size-box-label clearfix clr">
								<div class="size-label"><?php  echo $hlp->__("Size label"); ?>:</div>
							</div>
							<div class="size-box clearfix clr">
								<div>
									<a style="display:none;" href="#" class="view-sizing" data-toggle="modal"
									   data-target="#tabelaRozmiarow">
										<?php if (!empty($sizeTableValue)) : ?>
											<?php echo $this->__("Sizes"); ?>
										<?php endif; ?>
									</a>
								</div>
							</div>
						<?php endif; ?>
					<?php endforeach; ?>
				<?php endif; ?>
			<?php endif; ?>
		</div>
		<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12 clearfix quantity_block">
			<div class="qty_label"><?php echo $this->__("Quantity").":";?></div>
			<a href="#" class="qty_less">-</a>
			<div class="qty"><input type="text" name="quantity" value="1"/></div>
			<a href="#" class="qty_more">+</a>
			<label id="qty-error" class="error"><?php echo $hlp->__("Maximum quantity: %s", $maxQty); ?></label>
		</div>
		<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12 clearfix">
			<div class="action-box-bundle clearfix">
				<?php if ($isSalable): ?>
					<?php if ($_product->getTypeId() == Mage_Catalog_Model_Product_Type::TYPE_CONFIGURABLE): ?>
						<button class="btn button button-primary addBasket"
								<?php if (isset($haveSizes) && $haveSizes == true): ?><?php if ($salableCount > 1): ?>title="<?php echo $hlp->__("Choose size first"); ?>"
								data-toggle="tooltip" <?php endif; ?>data-placemen="top"<?php endif; ?>
								id="add-to-cart"
								onclick="Mall.validateAddingToCart(<?php echo $_product->getId(); ?>);return false;"><i class="fa fa-shopping-cart" aria-hidden="true"></i><?php echo $this->__("Add to cart");
							?></button>
					<?php else: ?>
						<button class="btn button button-primary addBasket"
								<?php if (isset($haveSizes) && $haveSizes == true): ?><?php if ($salableCount > 1): ?>title="<?php echo $hlp->__("Choose size first"); ?>"
								data-toggle="tooltip" <?php endif; ?>data-placemen="top"<?php endif; ?>
								id="add-to-cart"
								onclick="Mall.validateSimpleAddingToCart(<?php echo $_product->getId(); ?>, <?php echo $minQty; ?>, <?php echo $maxQty; ?>, '<?php echo $_product->getTypeId(); ?>');return false;"><i class="fa fa-shopping-cart" aria-hidden="true"></i><?php echo $this->__("Add to cart");
							?></button>
					<?php endif; ?>

				<?php endif; ?>
			</div>
		</div>
	</div>
	<?php if (!$isSalable): ?>
		<div class="temporary-absence-product-wrapper">
			<span class="temporary-absence-product"><?php echo $hlp->__("Product temporary unavailable"); ?></span>
		</div>
	<?php endif; ?>
	<div id="short-description-footer">
		<div id="same-collection-header">
		</div>
		<div id="same-product-list">
		</div>
	</div>

	<div id="box-social" class="row">
		<div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
			<div class="product-likeboxes">
				<div class="addLike-box" id="notadded-wishlist">
					<!-- placebo -->
					<span class="product-context-like-count" style="display: none"></span>
					<p>
						<a href="#" onclick="Mall.wishlist.addToWishlistFromProduct(<?php echo $_product->getEntityId(); ?>);return false;" class="addLike">
							<i class="fa fa-list" aria-hidden="true"></i><?php echo Mage::helper("zolagocatalog")->__("Add to shopping list"); ?></span>
						</a>
					</p>
				</div>
			</div>

		</div>
	</div>
</div>
<?php if ($_product->getTypeId() == Mage_Catalog_Model_Product_Type::TYPE_CONFIGURABLE) : ?>

	<script type="text/javascript">
		var jsonConfig = <?php echo Mage::getBlockSingleton('zolagocatalog/product_view_type_configurable')->getJsonConfig(); ?>;
		var useSizeboxList =  1;

		jsonConfig.useSizeboxList = useSizeboxList;
		Mall.product.productOptions(jsonConfig);
		Mall.product._current_product_type = "<?php echo Mage_Catalog_Model_Product_Type::TYPE_CONFIGURABLE; ?>";
	</script>
<?php endif; ?>
<script type="text/javascript">
	Mall.product._entity_id = <?php echo $_product->getEntityId(); ?>;
	jQuery(document).ready(function() {
		jQuery("input[name=quantity]").change(function(){
			jQuery("#qty-error").hide();
		});
	});
</script>
<?php if ($_product->getTypeId() == Mage_Catalog_Model_Product_Type::TYPE_CONFIGURABLE): ?>
	<script type="text/javascript">
		jQuery(document).ready(function() {
			jQuery(".sizes-content select").change(function(){
				jQuery("#qty-error").hide();
				var newMinQty = jQuery(this).attr('minqty');
				var newMaxQty = jQuery(this).children('option:selected').attr('maxqty');
				var currentQty = jQuery("input[name=quantity]").val();
				if(parseInt(newMaxQty) < parseInt(currentQty)){
					jQuery("input[name=quantity]").val(newMaxQty);
					jQuery("#qty-error").text('<?php echo $hlp->__("Maximum quantity:"); ?>' + ' ' + newMaxQty);
					jQuery("#qty-error").show();
				}
			});
			jQuery("a.qty_more").click(function(e){
				e.preventDefault();
				var attrId = jQuery("ul.selectboxit-options li.selectboxit-focus").attr('data-val');
				if(!attrId){
					jQuery("#qty-error").text('<?php echo $hlp->__("Choose size first"); ?>');
					jQuery("#qty-error").show();
				}else{
					var maxQty;
					var minQty;
					jQuery(".sizes-content select option").each(function(){
						if(jQuery(this).val() == attrId){
							maxQty = jQuery(this).attr('maxqty');
							minQty = jQuery(this).attr('minqty');
						}
					});
					var quantity =  jQuery("input[name=quantity]").val();
					jQuery("#qty-error").hide();
					if(parseInt(quantity) < parseInt(maxQty)) {
						quantity++;
						jQuery("input[name=quantity]").val(quantity);
					}
					else{
						jQuery("#qty-error").text('<?php echo $hlp->__("Maximum quantity:"); ?>' + ' ' + maxQty);
						jQuery("#qty-error").show();
						jQuery("input[name=quantity]").val(maxQty);
					}
				}
			});
			jQuery("a.qty_less").click(function(e){
				e.preventDefault();
				var attrId = jQuery("ul.selectboxit-options li.selectboxit-focus").attr('data-val');
				if(!attrId){
					jQuery("#qty-error").text('<?php echo $hlp->__("Choose size first"); ?>');
					jQuery("#qty-error").show();
				}else{
					var maxQty;
					var minQty;
					jQuery(".sizes-content select option").each(function(){
						if(jQuery(this).val() == attrId){
							maxQty = jQuery(this).attr('maxqty');
							minQty = jQuery(this).attr('minqty');
						}
					});
					var quantity =  jQuery("input[name=quantity]").val();
					jQuery("#qty-error").hide();
					if(parseInt(quantity) > parseInt(minQty)){
						quantity--;
						jQuery("input[name=quantity]").val(quantity);
					}
					if(parseInt(quantity) > parseInt(maxQty)) {
						jQuery("#qty-error").text('<?php echo $hlp->__("Maximum quantity:"); ?>' + ' ' + maxQty);
						jQuery("#qty-error").show();
						jQuery("input[name=quantity]").val(maxQty);
					}
				}
			});
		});
	</script>
<?php else: ?>
	<script type="text/javascript">
		jQuery(document).ready(function() {
			var maxQty = "<?php echo $maxQty; ?>";
			var minQty = "<?php echo $minQty; ?>";
			var productType = "<?php echo $_product->getTypeId(); ?>";
			jQuery("a.qty_more").click(function(e){
				e.preventDefault();
			    var quantityMore =  jQuery("input[name=quantity]").val();
			    jQuery("#qty-error").hide();
			    if((parseInt(quantityMore) >= parseInt(maxQty)) && productType != "<?php echo Mage_Catalog_Model_Product_Type::TYPE_BUNDLE; ?>") {
				   jQuery("#qty-error").show();
				   jQuery("input[name=quantity]").val(maxQty);
			    }else{
			    	quantityMore++;
				    jQuery("input[name=quantity]").val(quantityMore);
			    }
			});
			jQuery("a.qty_less").click(function(e){
			    e.preventDefault();
			    var quantityLess =  jQuery("input[name=quantity]").val();
			    jQuery("#qty-error").hide();
			    if(parseInt(quantityLess) > parseInt(minQty)){
				   quantityLess--;
				   jQuery("input[name=quantity]").val(quantityLess);
			    }
			    if((parseInt(quantityLess) > parseInt(maxQty)) && productType != "<?php echo Mage_Catalog_Model_Product_Type::TYPE_BUNDLE; ?>") {
			 	  jQuery("#qty-error").show();
			 	  jQuery("input[name=quantity]").val(maxQty);
			    }
			});
		});
	</script>
<?php endif; ?>

