<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2016 Amasty (https://www.amasty.com)
 * @package Magpleasure_Blog
 */
?>
<?php if($this->getCollection()->getSize()): ?>
    <?php if($this->getLastPageNum()>1): ?>
    <div class="mp-pager pagination-line pagination-bottom">
        <div class="listing-pagination">
            <div class="pages">
                <?php if (!$this->isFirstPage()): ?>
                    <a class="page-prev<?php if ($this->isOldStyle()): ?> old-style<?php endif; ?>" href="<?php echo $this->getPreviousPageUrl() ?>" rel="prev" title="<?php echo $this->__('Newer Entries') ?>"><i class="<?php echo $this->getColorClass(); ?> fa fa-angle-double-left"></i></a>
                <?php else: ?>
                    <a class="page-disabled">
                        <i class="fa fa-angle-double-left"></i>
                    </a>
                <?php endif;?>


                <?php if (!$this->isLastPage()): ?>
                    <a class="page-next<?php if ($this->isOldStyle()): ?> old-style<?php endif; ?>" href="<?php echo $this->getNextPageUrl() ?>" rel="next" title="<?php echo $this->__('Older Entries') ?>"><i class="<?php echo $this->getColorClass(); ?> fa fa-angle-double-right"></i></a>
                <?php else: ?>
                    <a class="page-disabled">
                        <i class="fa fa-angle-double-right"></i>
                    </a>
                <?php endif;?>

            </div>
            <div class="fixed"></div>
        </div>
    </div>
    <?php endif; ?>
<?php endif ?>