<?php
/* @var $this Zolago_Modago_Block_Home_Vendor */
$vendors = $this->getVendorColleciton();
$actualVendorsCount = $vendors->getSize();
$vendorsCount = Mage::getStoreConfig('design/popular_brands/popular_brands_count');

$config = json_decode(Mage::getStoreConfig('design/popular_brands/popular_brands_config'), true);
$configMax = array();
$addDummies = false;
foreach($config as $k=>$c) {
	$configMax[$k] = $k * $c;
	if($configMax[$k] > $vendorsCount) {
		$addDummies = true;
	}
}
if($addDummies) {
	$this->addDummyVendorsToCollection($vendors, $configMax);
}
?>

<?php if (count($vendors) > 0) : ?>
	<section id="popular-brands">
		<div class="container-fluid">
			<div class="col-sm-12 vendor-logo-container">
				<div class="row">
					<div>
						<div class="vendor-logo-items">
							<h3><?php echo $this->__("popular brands"); ?></h3>
							<?php $n = 1; ?>

							<?php foreach ($vendors as $v): ?>
								<div
									class="col-xxs col-xxs-landscape col-xs-4 col-xs-landscape col-sm-2 col-sm-landscape col-md-2 col-lg-3-eight vendor-logo-item
									<?php
									if($v->getDummy()) {
										echo $v->getClasses();
									} else {
										echo $n <= $configMax[2] ? '' : 'hidden-2 ';
										echo $n <= $configMax[3] ? '' : 'hidden-3 ';
										echo $n <= $configMax[4] ? '' : 'hidden-4 ';
										echo $n <= $configMax[5] ? '' : 'hidden-5 ';
										echo $n <= $configMax[6] ? '' : 'hidden-6 ';
										echo $n <= $configMax[7] ? '' : 'hidden-7 ';
										echo $n <= $configMax[8] ? '' : 'hidden-8 ';
									}
                                    ?>
									">
									<a href="<?php echo $v->getDummy() ? '#' : $this->getVendorBaseUrl($v); ?>" <?php echo $v->getDummy() ? 'style="cursor:default;"' : '' ?>>
										<span class="pop-shop-img-wr">
											<img src="<?php echo $v->getDummy() ? $v->getVendorResizedLogoUrl() : $this->getVendorResizedLogoUrl($v, 100, 44); ?>"
											     alt="<?php echo $v->getVendorName(); ?>">
										</span>
										<?php if(!$v->getDummy()): ?>
										<span class="vendor-logo-item-name">
											<?php echo $v->getVendorName(); ?> &gt;
										</span>
										<?php endif; ?>
									</a>
								</div>

								<?php if ($n % 2 == 0): ?>
									<div class="clearfix visible-xxs"></div>
								<?php endif; ?>

								<?php if ($n % 3 == 0): ?>
									<div class="clearfix visible-xs"></div>
								<?php endif; ?>

								<?php if ($n % 4 == 0): ?>
									<div class="clearfix visible-xss-landscape"></div>
								<?php endif; ?>

								<?php if ($n % 5 == 0): ?>
									<div class="clearfix visible-xs-landscape"></div>
								<?php endif; ?>

								<?php if ($n % 6 == 0): ?>
									<div class="clearfix visible-sm"></div>
									<div class="clearfix visible-md"></div>
								<?php endif; ?>

								<?php if ($n % 7 == 0): ?>
									<div class="clearfix visible-sm-landscape"></div>
								<?php endif; ?>

								<?php if ($n % 8 == 0): ?>
									<div class="clearfix visible-lg"></div>
								<?php endif; ?>

								<?php $n++; ?>
							<?php endforeach; ?>
						</div>
					</div>
				</div>
				<?php
				$showmoreClass = '';
				if($actualVendorsCount <= $vendorsCount) {
					foreach($configMax as $col=>$num) {
						if($actualVendorsCount < $num) {
							$showmoreClass .= ' hidden-'.$col;
						}
					}
				}
				?>
				<a class="pop-shop-seemore <?php echo $showmoreClass; ?>" href="<?php echo $this->getViewMoreUrl(); ?>">
					<?php echo $this->__("see more brands"); ?>
				</a>
			</div>
		</div>
	</section>
<?php endif; ?>
