
<!--popular brands-->
<div class="content-wrapper">
    <div class="container popular-shops">
        <h3><?php echo $this->__("popular brands"); ?></h3>
        <ul class="pop-shop-lst">
            <li><a href="#"><span class="pop-shop-img-wr"><img src="<?php echo $this->getSkinUrl('images/ck-logo-small.jpg'); ?>"
                                                               alt=""/></span><span>Calvin Klein &gt;</span></a></li>
            <li><a href="#"><span class="pop-shop-img-wr"><img src="<?php echo $this->getSkinUrl('images/ck-logo-small.jpg'); ?>"
                                                               alt=""/></span><span>Calvin Klein &gt;</span></a></li>
            <li><a href="#"><span class="pop-shop-img-wr"><img src="<?php echo $this->getSkinUrl('images/ck-logo-small.jpg'); ?>"
                                                               alt=""/></span><span>Calvin Klein &gt;</span></a></li>
        </ul>
        <ul class="pop-shop-lst">
            <li><a href="#"><span class="pop-shop-img-wr"><img src="<?php echo $this->getSkinUrl('images/ck-logo-small.jpg'); ?>"
                                                               alt=""/></span><span>Calvin Klein &gt;</span></a></li>
            <li><a href="#"><span class="pop-shop-img-wr"><img src="<?php echo $this->getSkinUrl('images/ck-logo-small.jpg'); ?>"
                                                               alt="<?php echo $this->getSkinUrl('images/ck-logo-small.jpg'); ?>"/></span><span>Calvin Klein &gt;</span></a></li>
            <li><a href="#"><span class="pop-shop-img-wr"><img src="<?php echo $this->getSkinUrl('images/ck-logo-small.jpg'); ?>"
                                                               alt="<?php echo $this->getSkinUrl('images/ck-logo-small.jpg'); ?>"/></span><span>Calvin Klein &gt;</span></a></li>
        </ul>
        <ul class="pop-shop-lst">
            <li><a href="#"><span class="pop-shop-img-wr"><img src="<?php echo $this->getSkinUrl('images/ck-logo-small.jpg'); ?>"
                                                               alt="<?php echo $this->getSkinUrl('images/ck-logo-small.jpg'); ?>"/></span><span>Calvin Klein &gt;</span></a></li>
            <li><a href="#"><span class="pop-shop-img-wr"><img src="<?php echo $this->getSkinUrl('images/ck-logo-small.jpg'); ?>"
                                                               alt="<?php echo $this->getSkinUrl('images/ck-logo-small.jpg'); ?>"/></span><span>Calvin Klein &gt;</span></a></li>
            <li><a href="#"><span class="pop-shop-img-wr"><img src="<?php echo $this->getSkinUrl('images/ck-logo-small.jpg'); ?>"
                                                               alt="<?php echo $this->getSkinUrl('images/ck-logo-small.jpg'); ?>"/></span><span>Calvin Klein &gt;</span></a></li>
        </ul>
        <ul class="pop-shop-lst hidden-xs ">
            <li><a href="#"><span class="pop-shop-img-wr"><img src="<?php echo $this->getSkinUrl('images/ck-logo-small.jpg'); ?>"
                                                               alt="<?php echo $this->getSkinUrl('images/ck-logo-small.jpg'); ?>"/></span><span>Calvin Klein &gt;</span></a></li>
            <li><a href="#"><span class="pop-shop-img-wr"><img src="<?php echo $this->getSkinUrl('images/ck-logo-small.jpg'); ?>"
                                                               alt="<?php echo $this->getSkinUrl('images/ck-logo-small.jpg'); ?>"/></span><span>Calvin Klein &gt;</span></a></li>
            <li><a href="#"><span class="pop-shop-img-wr"><img src="<?php echo $this->getSkinUrl('images/ck-logo-small.jpg'); ?>"
                                                               alt="<?php echo $this->getSkinUrl('images/ck-logo-small.jpg'); ?>"/></span><span>Calvin Klein &gt;</span></a></li>
        </ul>
        <ul class="pop-shop-lst hidden-xs hidden-md hidden-sm">
            <li><a href="#"><span class="pop-shop-img-wr"><img src="<?php echo $this->getSkinUrl('images/ck-logo-small.jpg'); ?>"
                                                               alt="<?php echo $this->getSkinUrl('images/ck-logo-small.jpg'); ?>"/></span><span>Calvin Klein &gt;</span></a></li>
            <li><a href="#"><span class="pop-shop-img-wr"><img src="<?php echo $this->getSkinUrl('images/ck-logo-small.jpg'); ?>"
                                                               alt="<?php echo $this->getSkinUrl('images/ck-logo-small.jpg'); ?>"/></span><span>Calvin Klein &gt;</span></a></li>
            <li><a href="#"><span class="pop-shop-img-wr"><img src="<?php echo $this->getSkinUrl('images/ck-logo-small.jpg'); ?>"
                                                               alt="<?php echo $this->getSkinUrl('images/ck-logo-small.jpg'); ?>"/></span><span>Calvin Klein &gt;</span></a></li>
        </ul>
        <ul class="pop-shop-lst hidden-xs hidden-md hidden-sm">
            <li><a href="#"><span class="pop-shop-img-wr"><img src="<?php echo $this->getSkinUrl('images/ck-logo-small.jpg'); ?>"
                                                               alt="<?php echo $this->getSkinUrl('images/ck-logo-small.jpg'); ?>"/></span><span>Calvin Klein &gt;</span></a></li>
            <li><a href="#"><span class="pop-shop-img-wr"><img src="<?php echo $this->getSkinUrl('images/ck-logo-small.jpg'); ?>"
                                                               alt="<?php echo $this->getSkinUrl('images/ck-logo-small.jpg'); ?>"/></span><span>Calvin Klein &gt;</span></a></li>
            <li><a href="#"><span class="pop-shop-img-wr"><img src="<?php echo $this->getSkinUrl('images/ck-logo-small.jpg'); ?>"
                                                               alt="<?php echo $this->getSkinUrl('images/ck-logo-small.jpg'); ?>"/></span><span>Calvin Klein &gt;</span></a></li>
        </ul>
        <ul class="pop-shop-lst hidden-xs">
            <li><a href="#"><span class="pop-shop-img-wr"><img src="<?php echo $this->getSkinUrl('images/ck-logo-small.jpg'); ?>"
                                                               alt="<?php echo $this->getSkinUrl('images/ck-logo-small.jpg'); ?>"/></span><span>Calvin Klein &gt;</span></a></li>
            <li><a href="#"><span class="pop-shop-img-wr"><img src="<?php echo $this->getSkinUrl('images/ck-logo-small.jpg'); ?>"
                                                               alt="<?php echo $this->getSkinUrl('images/ck-logo-small.jpg'); ?>"/></span><span>Calvin Klein &gt;</span></a></li>
            <li><a href="#"><span class="pop-shop-img-wr"><img src="<?php echo $this->getSkinUrl('images/ck-logo-small.jpg'); ?>"
                                                               alt="<?php echo $this->getSkinUrl('images/ck-logo-small.jpg'); ?>"/></span><span>Calvin Klein &gt;</span></a></li>
        </ul>
    </div>
    <a class="pop-shop-seemore" href=""><?php echo $this->__("see more brands"); ?></a>
</div>
