<?php /* @var $this Zolago_Modago_Block_Mypromotions_Header */ ?>
<?php $helper = Mage::helper("zolagomodago"); ?>
<?php if ($this->isLogged()): ?>
    <header id="header-main" class="mypromotions-header logged-in">
        <div class="wrapp-section bg-w">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-sm-12 header-panel">
                        <?php echo $this->getLayout()->getBlock('breadcrumbs')->toHtml(); ?>
                        <div class="header-title">
                            <h1><?php echo $helper->__("Your promotion coupons"); ?></h1>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </header>
<?php endif; ?>