<?php
/** @var Mage_Core_Block_Template $this */
$smcid = $this->getRequest()->getParam('smclient');
$customers = Mage::getModel("customer/customer")->getCollection()->addFieldToFilter("salesmanago_contact_id", $smcid);
$customer = $customers->getFirstItem();
$isValid = $customer->getId() ? true : false;
?>
<style>
    .is-invalid .hide-if-invalid {display:none;}
    #logIn .is-invalid form {margin-bottom:0px}
</style>
<div id="content" class="container-fluid">
    <div id="logIn" class="row">
        <div id="content-main" class="">
            <div class="col-sm-12 column-block">
                <div class="main bg-w equalBlock col-01 <?php echo !$isValid ? 'is-invalid' : ''; ?>">
                    <form action="<?php echo $this->getUrl("newsletter/subscriber/subscribeAgain");?>" method="post" class="form-horizontal" >
                        <input type="hidden" name="smcid" value="<?php echo $smcid ?>"/>
                        <?php echo $this->getChildHtml("zolagonewsletter.sm.unsubscribe.redirect.formkey");?>
                        <?php echo $this->getChildHtml("salesmanago_unsubscribe_redirect");?>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>