<?php
/** @var Zolago_Modago_Block_Promotions_Gotoregister $this */
/** @var Zolago_Salesrule_Helper_Data $helper */
$helper = Mage::helper('zolagosalesrule');
?>
<div class="container-fluid">
	<div class="row">
		<section id="mypromotions-gotoregister"
		         class="main bg-w col-lg-8 col-md-10 col-sm-12 col-xs-12 col-lg-push-2 col-md-push-1">
			<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('mypromotions_gotoregister')->toHtml(); ?>
		</section>
	</div>
</div>