<?php $hlp = Mage::helper('ghregulation');?>
<?php $list = $this->getList(); ?>
<table class="form-list">
<tr>
<td class="label">
    <?php echo $hlp->__('Document type list'); ?>
</td>
<td class="grid">
<table class="data">
<?php if (!count($list)):?>
<thead>
<tr class="headings">
    <th colspan="3">
    <?php echo $hlp->__('No assigned types of documents'); ?>
    </th>
</tr>
</thead>
<?php else: ?>
<thead>
<tr class="headings">
    <th>
        <?php echo $hlp->__('Type name');?>
    </th>
    <th>
        <?php echo $hlp->__('Active from');?>
    </th>
    <th>
        <?php echo $hlp->__('Actions');?>
    
    </th>
</tr>
</thead>
<tbody>
<?php foreach ($list as $item) : ?>
<tr class="option-row">
    <td>
        <?php echo $item->getName();?>
    </td>
    <td>
        <?php echo $item->getDate();?>
    </td>
    <td>
        <button onclick="deleteConfirm('<?php echo $hlp->__('Are you sure?');?>','<?php echo $this->_getDeleteUrl($item->getId());?>')" class="scalable delete" type="button"><?php echo $hlp->__('Remove');?></button>
    </td>
</tr>
<?php endforeach;?>
</tbody>
<?php endif; ?>
<tfoot>
<tr>
    <th colspan="3">
    <button style="" onclick="setLocation('<?php echo $this->getData('createUrl'); ?>')" class="scalable add" type="button"><?php echo $hlp->__('Assign type');?></button>
    </th>
</tfoot>
</table>
</td>
</tr>
</table>