<div class="content-header">
   <h3><?php echo $this->getHeaderText() ?></h3>
   <p class="content-buttons form-buttons">
        <?php echo $this->getButtonsHtml(); ?>
    </p>
</div>
<form action="<?php echo $this->getSaveUrl() ?>" method="post" id="mapper_edit_form">
    <?php echo $this->getBlockHtml('formkey')?>
    <div class="no-display">
        <input type="hidden" id="change_flag_element" name="_change_type_flag" value="" />]
    </div>
    <?php echo $this->getChild('form')->toHtml(); ?>
</form>
<script type="text/javascript">
//<![CDATA[
    var editForm = new varienForm('mapper_edit_form');
    var mapperControl = {
        save: function() {
            if (this.typeChange) {
                $('change_flag_element').value = '1';
            }
            editForm.submit();
            return false;
        },	
		run: function(){
			$("do_run").value = 1;
			editForm.submit();
		},
		next: function(){
			var attributeSetId = $F("attribute_set_id");
			if(!attributeSetId){
				alert("<?php echo Mage::helper('zolagomapper')->__('Choose attribute set!') ?>");
			}
			var nextUrl = "<?php echo $this->getUrl("*/*/new", array("_current"=>true, "attribute_set_id"=>"{{attribute_set_id}}"));?>";
			var template = new Template(nextUrl, /(^|.|\r|\n)({{(\w+)}})/);
			setLocation(template.evaluate({attribute_set_id:attributeSetId}));
            return false;
		},
		remove: function() {
            if(window.confirm("<?php echo Mage::helper('zolagomapper')->__('Are you sure that you want to delete this mapper?') ?>")) {
                window.location.href = '<?php echo $this->getDeleteUrl() ?>';
            }
        },
        saveAndQueue: function() {
            $("do_saveAndQueue").value = 1;
            editForm.submit();
        }
    };
    
</script>
