<div class="content-header">
   <h3><?php echo $this->getHeaderText() ?></h3>
   <p class="content-buttons form-buttons">
        <?php echo $this->getButtonsHtml(); ?>
    </p>
</div>
<form action="<?php echo $this->getSaveUrl() ?>" method="post" id="mapper_edit_form">
    <?php echo $this->getBlockHtml('formkey')?>
    <div class="no-display">
        <input type="hidden" id="change_flag_element" name="_change_type_flag" value="" />]
    </div>
    <?php echo $this->getChild('form')->toHtml(); ?>
</form>
<script type="text/javascript">
//<![CDATA[
    var editForm = new varienForm('mapper_edit_form');
    var mapperControl = {
        init: function () {
            if ($('convert_button_back')) {
                $('convert_button_back').hide();
            }
        },
        save: function() {
            if (this.typeChange) {
                $('change_flag_element').value = '1';
            }
            editForm.submit();
            return false;
        },
        saveAs: function() {
            if (this.typeChange) {
                $('change_flag_element').value = '1';
            }

            $('save_as_flag').value = '1';

            editForm.submit();
            return false;
        },
        remove: function() {
            if(window.confirm("<?php echo Mage::helper('zolagomapper')->__('Are you sure that you want to delete this mapper?') ?>")) {
                window.location.href = '<?php echo $this->getDeleteUrl() ?>';
            }
        }
    };
    mapperControl.init();
    
</script>
