<div class="content-header">
   <h3><?php echo Mage::helper('zolagomapper')->__('Mapper index'); ?></h3>
      <p class="content-buttons form-buttons">
        <?php echo $this->getButtonsHtml(); ?>
      </p>
</div>
<?php if (count($this->getProducts())) { ?>
<div>
	<dl>
	<?php foreach($this->getProducts() as $prodcut):?>	
			<dt><?php echo $prodcut->getName();?> (<?php echo Mage::helper("core")->currency($prodcut->getPrice());?>)</dt>
			<?php foreach ($this->getCategories() as $category):?>
			<dd><?php echo $category->getName();?></dd>
			<?php endforeach;?>
		</tr>
	<?php endforeach;?>
	</dl>
</div>
<style type="text/css">
dt{font-weight: bold;}
dd{margin-left: 20px;}
</style>
<?php 
} else { 
    echo Mage::helper('zolagomapper')->__('No products');
}
?>
